#!/usr/bin/env python3
"""Finite tensor-word certificate for the reflection identity.

This checker never constructs the 16x16 or 64x64 matrices.  It works in the
abstract real Pauli algebra generated by I, X, Z, J and in Q[alpha,beta].
"""

from collections import defaultdict
from fractions import Fraction
import sys


if sys.flags.optimize:
    raise RuntimeError("optimized Python is not permitted for scientific verification")


class Poly:
    """A sparse polynomial in alpha and beta with rational coefficients."""

    __slots__ = ("terms",)

    def __init__(self, terms=None):
        self.terms = {
            monomial: Fraction(coefficient)
            for monomial, coefficient in (terms or {}).items()
            if coefficient
        }

    @staticmethod
    def monomial(alpha_power=0, beta_power=0, coefficient=1):
        return Poly({(alpha_power, beta_power): Fraction(coefficient)})

    def __add__(self, other):
        other = as_poly(other)
        out = defaultdict(Fraction)
        for monomial, coefficient in self.terms.items():
            out[monomial] += coefficient
        for monomial, coefficient in other.terms.items():
            out[monomial] += coefficient
        return Poly(out)

    __radd__ = __add__

    def __neg__(self):
        return Poly({monomial: -coefficient for monomial, coefficient in self.terms.items()})

    def __sub__(self, other):
        return self + (-as_poly(other))

    def __rsub__(self, other):
        return as_poly(other) - self

    def __mul__(self, other):
        other = as_poly(other)
        out = defaultdict(Fraction)
        for (a1, b1), c1 in self.terms.items():
            for (a2, b2), c2 in other.terms.items():
                out[(a1 + a2, b1 + b2)] += c1 * c2
        return Poly(out)

    __rmul__ = __mul__

    def __truediv__(self, n):
        n = Fraction(n)
        return Poly({monomial: coefficient / n for monomial, coefficient in self.terms.items()})

    def __eq__(self, other):
        return self.terms == as_poly(other).terms

    def __bool__(self):
        return bool(self.terms)

    def specialize_squares(self, alpha_squared, beta_squared):
        """Reduce powers using alpha^2 and beta^2, retaining parity only."""
        out = defaultdict(Fraction)
        for (a, b), coefficient in self.terms.items():
            coefficient *= Fraction(alpha_squared) ** (a // 2)
            coefficient *= Fraction(beta_squared) ** (b // 2)
            out[(a % 2, b % 2)] += coefficient
        return Poly(out)

    def __repr__(self):
        if not self.terms:
            return "0"
        pieces = []
        for (a, b), coefficient in sorted(self.terms.items(), reverse=True):
            factors = [str(coefficient)]
            if a:
                factors.append("alpha" if a == 1 else f"alpha^{a}")
            if b:
                factors.append("beta" if b == 1 else f"beta^{b}")
            pieces.append("*".join(factors))
        return " + ".join(pieces)


def as_poly(value):
    return value if isinstance(value, Poly) else Poly.monomial(coefficient=value)


ALPHA = Poly.monomial(alpha_power=1)
BETA = Poly.monomial(beta_power=1)


SINGLE_PRODUCT = {}
for letter in "IXZJ":
    SINGLE_PRODUCT[("I", letter)] = (1, letter)
    SINGLE_PRODUCT[(letter, "I")] = (1, letter)
SINGLE_PRODUCT.update(
    {
        ("X", "X"): (1, "I"),
        ("Z", "Z"): (1, "I"),
        ("J", "J"): (-1, "I"),
        ("X", "Z"): (1, "J"),
        ("Z", "X"): (-1, "J"),
        ("X", "J"): (1, "Z"),
        ("J", "X"): (-1, "Z"),
        ("J", "Z"): (1, "X"),
        ("Z", "J"): (-1, "X"),
    }
)


def multiply_words(left, right):
    if len(left) != len(right):
        raise AssertionError("tensor words have different lengths")
    sign = 1
    result = []
    for a, b in zip(left, right):
        local_sign, letter = SINGLE_PRODUCT[(a, b)]
        sign *= local_sign
        result.append(letter)
    return sign, "".join(result)


def algebra_add(*summands):
    out = defaultdict(Poly)
    for scalar, element in summands:
        scalar = as_poly(scalar)
        for word, coefficient in element.items():
            out[word] = out[word] + scalar * coefficient
    return {word: coefficient for word, coefficient in out.items() if coefficient}


def algebra_multiply(left, right):
    out = defaultdict(Poly)
    for word_left, coefficient_left in left.items():
        for word_right, coefficient_right in right.items():
            sign, word = multiply_words(word_left, word_right)
            out[word] = out[word] + sign * coefficient_left * coefficient_right
    return {word: coefficient for word, coefficient in out.items() if coefficient}


def singleton(word, coefficient=1):
    return {word: as_poly(coefficient)}


def assert_element_equal(label, left, right):
    difference = algebra_add((1, left), (-1, right))
    if difference:
        word, coefficient = next(iter(sorted(difference.items())))
        raise AssertionError(f"{label}: coefficient of {word} is {coefficient}")
    print(f"[ok] {label}")


def main():
    identity4 = singleton("IIII")
    a = "ZIZZ"
    b = "ZIJJ"
    c = "JIZJ"
    d = "JIJZ"
    e = "XIXX"

    for word in (a, b, c, d, e):
        assert_element_equal(
            f"{word}^2 = I",
            algebra_multiply(singleton(word), singleton(word)),
            identity4,
        )

    for left, right in ((a, b), (a, c), (b, c)):
        assert_element_equal(
            f"{left} commutes with {right}",
            algebra_multiply(singleton(left), singleton(right)),
            algebra_multiply(singleton(right), singleton(left)),
        )

    abc = algebra_multiply(
        algebra_multiply(singleton(a), singleton(b)),
        singleton(c),
    )
    assert_element_equal("D = ABC", singleton(d), abc)

    for word in (a, b, c, d):
        anticommutator = algebra_add(
            (1, algebra_multiply(singleton(e), singleton(word))),
            (1, algebra_multiply(singleton(word), singleton(e))),
        )
        assert_element_equal(f"E anticommutes with {word}", anticommutator, {})

    h = {
        a: -ALPHA / 2,
        b: -ALPHA / 2,
        c: -ALPHA / 2,
        d: ALPHA / 2,
        e: BETA,
    }
    h_squared = algebra_multiply(h, h)
    expected_h_squared = singleton("IIII", ALPHA * ALPHA + BETA * BETA)
    assert_element_equal(
        "H(alpha,beta)^2 = (alpha^2 + beta^2) I",
        h_squared,
        expected_h_squared,
    )

    h1 = {word + "II": coefficient for word, coefficient in h.items()}
    h2 = {"II" + word: coefficient for word, coefficient in h.items()}
    residual = algebra_add(
        (1, algebra_multiply(algebra_multiply(h1, h2), h1)),
        (-1, algebra_multiply(algebra_multiply(h2, h1), h2)),
        (Fraction(-1, 3), h1),
        (Fraction(1, 3), h2),
    )

    c_a_neg = ALPHA / 6 - ALPHA * BETA * BETA / 2
    c_a_pos = -c_a_neg
    c_mix_pos = ALPHA * ALPHA * ALPHA / 2 - ALPHA * BETA * BETA
    c_mix_neg = -c_mix_pos
    c_b_neg = (
        -BETA * ALPHA * ALPHA
        + BETA * BETA * BETA
        + BETA / 3
    )
    c_b_pos = -c_b_neg

    expected_groups = (
        (c_a_neg, ("IIJIJZ", "JIZJII", "ZIJJII", "ZIZZII")),
        (c_a_pos, ("IIJIZJ", "IIZIJJ", "IIZIZZ", "JIJZII")),
        (c_b_neg, ("IIXIXX",)),
        (c_mix_pos, ("JIJZXX", "JIZJXX", "XIJXZJ", "ZIZZXX")),
        (c_mix_neg, ("XIJXJZ", "XIZXJJ", "XIZXZZ", "ZIJJXX")),
        (c_b_pos, ("XIXXII",)),
    )
    expected_residual = {}
    for coefficient, words in expected_groups:
        for word in words:
            expected_residual[word] = coefficient

    if len(residual) != 18:
        raise AssertionError(f"cubic residual has {len(residual)} words, not 18")
    assert_element_equal(
        "the cubic residual has exactly the printed 18-word certificate",
        residual,
        expected_residual,
    )

    for word, coefficient in residual.items():
        specialized = coefficient.specialize_squares(
            alpha_squared=Fraction(2, 3),
            beta_squared=Fraction(1, 3),
        )
        if specialized:
            raise AssertionError(
                f"specialized residual coefficient of {word} is {specialized}"
            )
    print("[ok] all 18 coefficients vanish for alpha^2=2/3, beta^2=1/3")

    alpha_axis = residual["IIXIXX"].specialize_squares(
        alpha_squared=0,
        beta_squared=1,
    )
    if not alpha_axis:
        raise AssertionError("alpha=0, beta^2=1 was incorrectly accepted")
    beta_axis = residual["ZIZZII"].specialize_squares(
        alpha_squared=1,
        beta_squared=0,
    )
    if not beta_axis:
        raise AssertionError("beta=0, alpha^2=1 was incorrectly accepted")
    if c_a_neg != ALPHA * (1 - 3 * BETA * BETA) / 6:
        raise AssertionError("nondegenerate obstruction did not factor as expected")
    print("[ok] alpha=0, beta=0, and nondegenerate converse branches are certified")

    print()
    print("The 18 surviving words and their coefficients are:")
    for coefficient, words in expected_groups:
        print(f"  {repr(coefficient):<55} : {', '.join(words)}")

    print()
    print("All tensor-word checks passed.")
    print("On alpha^2 + beta^2 = 1, the only nondegenerate obstruction is")
    print("3 beta^2 - 1; hence beta^2 = 1/3 and alpha^2 = 2/3.")


if __name__ == "__main__":
    main()
