#!/usr/bin/env python3
"""Document-byte preservation and declared scope checks; not a proof checker."""
import hashlib,json,os,sys
from pathlib import Path
PINS = {'first_audit/AUTHORED_PACKET_MANIFEST.json': {'bytes': 1101, 'sha256': '50f1655a716d9e58d005a3713fde29eba0da993e17abba43e038ee651a6fc5ec'}, 'first_audit/NESTED_DEPENDENCY_LEDGER.md': {'bytes': 24620, 'sha256': '07178f08bda91f33ffbf335da7af8d2244f5439f98f22f61e552aa6aafde1bf9'}, 'first_audit/PRIOR_RESOLUTION_AUDIT.md': {'bytes': 34057, 'sha256': '7a7cd9dc4c547e20739d5f96d35150f63f03b5fbc0fd1247e6056bce9b256ee4'}, 'first_audit/SOURCE_VERIFICATION_METADATA.json': {'bytes': 12008, 'sha256': '69df13349746856d34d4eb57970e5f618eb01c8f2d2e3d1346e21f7619389e6d'}, 'second_audit/INDEPENDENT_ACCEPTANCE_REPORT.md': {'bytes': 28468, 'sha256': 'dbd08a7f4b7f973f0a28c774b1030c0a87b20f4a3815221fd7bae04b0345acf5'}, 'second_audit/INDEPENDENT_PACKET_MANIFEST.json': {'bytes': 1071, 'sha256': '66934f764a75ab0730d4b2a0783153d54f2a9035284029e7157262bf807402f7'}, 'second_audit/INDEPENDENT_VERIFICATION_METADATA.json': {'bytes': 12066, 'sha256': '08e2b53460e7f862f39efd99eb0a6abbea162f386f03c2d7ba892a6f86f287a8'}, 'second_audit/LOCAL_CONDITION_CLARIFICATION.md': {'bytes': 3888, 'sha256': '438ca99e22f3975958eeb491b63a4f9610c35fb0b5aa46e61f97f4616d46d833'}}
ACCEPTANCE = {'schema': 1, 'problem_id': 30000779, 'source_problem': 'OWR-1586-003', 'decision': 'ACCEPTED_CREDITED_PRIOR_RESOLUTION_WITH_SOURCE_SCOPE', 'original_owr_target_resolved': True, 'catalogue_disposition': 'SOURCE_SCOPE', 'unrestricted_real_field_p2_disposition': 'NOT_ASSERTED', 'new_proof_search_turns': 0, 'novelty_claimed': False, 'credit': ['Alexander Schmidt', 'John Labute', 'Jan Minac'], 'essential_authored_corrections_included': True, 'accepted_input_bytes_preserved': True, 'mathematical_proof_computationally_certified': False, 'mathematical_scope': {'exact_target': 'OWR-1586-003: number field k, prime p odd OR k totally imaginary; every finite tame S and prescribed Dirichlet-density-one D admit finite A subset D minus (S union S_p) with Spec(O_k) minus (S union A) K(pi,1) for p.', 'catalogue': 'SOURCE_SCOPE: literal catalogue omits the original real-place convention; no unrestricted real-field p=2 theorem or residual-open classification.', 'restrictions': 'No class-number or cyclotomic exclusion; S may be empty and need not lie in D; no uniform bound on A.', 'local_kummer': 'At p-adic J factors use C_v=O_v^* k_v^{*p}/k_v^{*p}, not ordinary unramified H^1(k_v,mu_p); its annihilator is unramified F_p characters.', 'duality': 'First local products of (I) and (II) are T-indexed; designated S factors remain S.', 'odd_branch': 'psi_a evaluates at Frob(q_a), not p_a; old H^1 dimension at least two and degree-one prime descent explicit.', 'roots_branch': 'Restore I_a in cyclic field F_a, Frobenius kernel, and chi_a space; n>=3 and kernel dimension p^n-2-n>0; psi_a chosen in old U.', 'characteristic_two': 'Both off-diagonal cup directions checked through Lemma 5.2; square vanishing uses splitting in k(i) and N(q_a)=1 mod 4; graded commutativity alone is insufficient.', 'foundations': 'Checked imported interfaces; arithmetic duality, class field theory, PBW, etale homotopy and other listed foundations are not independently reproved.', 'source_versions': 'Inspected English/German author manuscripts and Labute-Minac author/arXiv versions are distinguished; no publisher-PDF identity claimed.', 'pdf_headers': 'Historical pdf_signature_valid denotes PDF-header detection only; no cryptographic digital-signature verification. Hash agreement does not establish historical network provenance.'}, 'excluded_stages': {'source_body_replay': 'NOT_RUN', 'historical_retrieval_replay': 'NOT_RUN', 'historical_inspection_replay': 'NOT_RUN', 'excluded_material_replay': 'NOT_RUN', 'new_source_search': 'NOT_RUN', 'dataset_replay': 'NOT_RUN', 'full_foundational_proof_replay': 'NOT_RUN', 'formal_proof_assistant_verification': 'NOT_RUN', 'computational_mathematical_proof_certification': 'NOT_RUN', 'publisher_pdf_comparison': 'NOT_RUN', 'cryptographic_pdf_signature_verification': 'NOT_RUN'}}
STATUS = {'schema': 1, 'problem_id': 30000779, 'status': 'credited_prior_resolution_SOURCE_SCOPE', 'original_owr_target_resolved': True, 'literal_catalogue_scope_repair_required': True, 'unrestricted_real_field_p2_result_asserted': False, 'unrestricted_real_field_p2_open_asserted': False, 'new_proof_search_turns': 0, 'novelty_claimed': False, 'manuscript_status': 'Authored application/correction audits of credited published prior mathematics; not an author-issued or publisher-issued erratum. Imported-foundation boundary retained.'}
def need(ok,msg):
 if not ok:raise ValueError(msg)
def exact(a,b):
 if type(a) is not type(b):return False
 if type(b) is dict:return set(a)==set(b) and all(exact(a[k],v) for k,v in b.items())
 if type(b) is list:return len(a)==len(b) and all(exact(x,y) for x,y in zip(a,b))
 return a==b
def main():
 need(os.getuid()==os.geteuid()==1000,'UID/EUID');need(sys.flags.isolated and sys.flags.no_site and sys.dont_write_bytecode,'-I -S -B');root=Path(__file__).resolve().parent;rows=[]
 for n,pin in PINS.items():
  raw=(root/n).read_bytes();actual=dict(bytes=len(raw),sha256=hashlib.sha256(raw).hexdigest());need(exact(actual,pin),'accepted document bytes: '+n);rows.append(dict(document=n,bytes=len(raw),sha256=actual['sha256'],preserved=True))
 need(exact(json.loads((root/'ACCEPTANCE.json').read_bytes()),ACCEPTANCE),'exact acceptance scope')
 need(exact(json.loads((root/'STATUS.json').read_bytes()),STATUS),'exact status scope')
 controls=[dict(identity='exact acceptance declaration',passed=True),dict(identity='exact status declaration',passed=True)]
 print(json.dumps(dict(schema=1,problem_id=30000779,status='passed',uid=os.getuid(),euid=os.geteuid(),python_optimize=sys.flags.optimize,document_byte_checks=rows,document_byte_check_count=8,scope_declaration_controls=controls,scope_declaration_control_count=2,mathematical_proof_checks='NOT_RUN',source_theorem_computationally_certified=False),indent=2,sort_keys=True))
if __name__=='__main__':
 try:main()
 except (ValueError,OSError,TypeError,KeyError):print('REJECT: document/scope validation failed',file=sys.stderr);sys.exit(1)
