"""Separately authored digital-review controls. No author checker imports."""
from itertools import product,combinations
from collections import Counter
from fractions import Fraction
import json
C=Counter()
def ck(b,name):
    assert b,name
    C[name]+=1
# The coordinate union underlying any-dimensional caterpillars, including negative support.
def d(x,k):return x-(x>k)
for k in range(-12,13):
 for lo in range(-15,16):
  vals=[d(x,t) for x in (lo,lo+1) for t in (k,k+1)]
  ck(max(vals)-min(vals)<=1,'coordinate_union')
# A nonflag complex must not be replaced by pairwise adjacency.
triangle_boundary={frozenset(s) for size in range(3) for s in combinations(range(3),size)}
ck(all(frozenset(e) in triangle_boundary for e in combinations(range(3),2)),'nonflag_pairs_linked')
ck(frozenset(range(3)) not in triangle_boundary,'nonflag_triple_not_linked')
# Direct, independently enumerated cross-time graph versus simplex test.
for bits in product((0,1),repeat=3):
 E={(i,i) for i in range(3)}
 for e,on in zip(combinations(range(3),2),bits):
  if on:E.update((e,e[::-1]))
 domain=[(0,0),(0,1),(1,0),(1,1)]
 images=[v for v in product(range(3),repeat=4) if all((x,y) in E for x in v for y in v)]
 for f in images:
  for g in images:
   cube=all((x,y) in E for x in f+g for y in f+g)
   cross=all((f[i],g[j]) in E for i in range(4) for j in range(4))
   ck(cube==cross,'square_time_simplex')
# A based six-label sphere array on an 8x8 square, with the actual octahedral adjacency.
def sphere(x,y):
 a,b=x-4,y-4;r=max(abs(a),abs(b))
 if r>=3:return 0
 if r==0:return 1
 if a>=abs(b):return 2
 if -a>=abs(b):return 3
 return 4 if b>0 else 5
def adj(a,b):return b!=(a^1)
def box(M,N):return list(product(range(M+1),range(N+1)))
def pairs(M,N):
 for p in box(M,N):
  for dx,dy in product((-1,0,1),repeat=2):
   q=(p[0]+dx,p[1]+dy)
   if 0<=q[0]<=M and 0<=q[1]<=N:yield p,q
ck(set(sphere(*v) for v in box(8,8))==set(range(6)),'all_six_labels')
for p,q in pairs(8,8):ck(adj(sphere(*p),sphere(*q)),'sphere_strong_edges')
# Four varied source rectangles: original, reflected, stretched by delay, and padded.
arrs=[]
for M,N,fn in [(8,8,sphere),(8,8,lambda x,y:sphere(8-x,y)),(9,8,lambda x,y:sphere(d(x,3),y)),(8,10,lambda x,y:sphere(x,d(d(y,5),2)))]:
 A={p:fn(*p) for p in box(M,N)}
 ck(all(A[p]==0 for p in A if p[0] in (0,M) or p[1] in (0,N)),'array_based')
 for p,q in pairs(M,N):ck(adj(A[p],A[q]),'varied_array_edges')
 arrs.append((M,N,A))
# Translation path generated by reverse layer insertion, then patched to a fixed left array.
for m,n,F in arrs:
 for r,s,G in arrs:
  M,N=m+r+1,n+s+1
  E=list(pairs(M,N)); pts=box(M,N)
  def assemble(R):return {p:(F.get(p,0) if p[0]<=m else R.get((p[0]-m-1,p[1]),0)) for p in pts}
  R=dict(G); previous=assemble(R)
  for shift in range(n+1):
   old=R
   # Descending threshold constructs a full shift with no one-step shortcut.
   for threshold in range(s+shift,-1,-1):
    Rnew={(x,y):old.get((x,d(y,threshold)),0) for x,y in box(r,N)}
    current=assemble(Rnew)
    for p,q in E:ck(adj(previous[p],current[q]),'regional_cross_time_edges')
    ck(all(current[p]==0 for p in pts if p[0] in (0,M) or p[1] in (0,N)),'regional_boundary')
    previous=current
   R=Rnew
  diagonal={p:(F.get(p,0) if p[0]<=m else G.get((p[0]-m-1,p[1]-n-1),0)) for p in pts}
  ck(previous==diagonal,'published_diagonal_endpoint')
# Whole translated supported loop and a negative support homotopy restore to an anchored box.
loop={i:x for i,x in enumerate((0,2,4,3,5,2,0))}
for shift in range(-8,9):
 f=lambda i:loop.get(i-shift,0)
 for k in range(shift,shift+7):
  for i in range(shift-2,shift+10):
   for j in (i-1,i,i+1):ck(adj(f(d(i,k)),f(d(j,k+1))),'negative_support_caterpillar')
 # sufficiently positive common translation brings original and all slices into one box.
 off=max(0,-shift)+3
 ck(all(i+off>=1 for i in range(shift,shift+8)),'negative_support_common_anchor')
# Octahedral clique complex gives the requested six-vertex sphere, with exact chain ranks.
V=list(range(6)); simplices={k:[c for c in combinations(V,k+1) if all(adj(a,b) for a,b in combinations(c,2))] for k in range(4)}
ck([len(simplices[k]) for k in range(4)]==[6,12,8,0],'octahedron_face_vector')
def rank(A):
 A=[[Fraction(x) for x in row] for row in A];i=0
 if not A:return 0
 for j in range(len(A[0])):
  h=next((h for h in range(i,len(A)) if A[h][j]),None)
  if h is None:continue
  A[i],A[h]=A[h],A[i];p=A[i][j];A[i]=[x/p for x in A[i]]
  for h in range(len(A)):
   if h!=i:
    p=A[h][j];A[h]=[x-p*y for x,y in zip(A[h],A[i])]
  i+=1
  if i==len(A):break
 return i
def boundary(k):
 rows=simplices[k-1];cols=simplices[k];A=[[0]*len(cols) for _ in rows]
 for j,c in enumerate(cols):
  for h in range(k+1):A[rows.index(c[:h]+c[h+1:])][j]=(-1)**h
 return A
B1=boundary(1);B2=boundary(2)
ck(all(sum(B1[i][k]*B2[k][j] for k in range(12))==0 for i in range(6) for j in range(8)),'boundary_squared_zero')
ck((rank(B1),rank(B2))==(5,7),'octahedron_ranks')
ck((6-rank(B1),12-rank(B1)-rank(B2),8-rank(B2))==(1,0,1),'octahedron_betti')
# Same C4 counterexample under box homotopy, excluding strong equivalence.
ce=lambda a,b:(a-b)%4 in (0,1,3)
a=(0,1,2,3);b=(0,0,3,3);c=(0,0,0,0)
ck(all(ce(f[i],f[(i+1)%4]) for f in (a,b,c) for i in range(4)),'box_slices')
ck(all(ce(f[i],g[i]) for f,g in ((a,b),(b,c)) for i in range(4)),'box_tracks')
ck(not ce(a[1],b[2]),'box_not_strong')
print(json.dumps({'status':'PASS','assertions':sum(C.values()),'counts':dict(sorted(C.items())),'scope':'Independent finite controls; all-degree and source-scope verdict rests on the written audit and credited primary theorems.'},indent=2,sort_keys=True))
