"""UNEXECUTED SOURCE. ROOT reads, copies unchanged adjacent to A47, then runs.
No production imports, Git commands, scientific helpers or native writes.
The explicit personal-reading argument is ROOT's attestation, not inferred proof.
"""
from pathlib import Path, PurePosixPath
import datetime as dt, hashlib, json, math, os, re, stat, sys
A=Path(__file__).absolute().parent;R=A.parents[2];H=A/'acceptance_preparation_family';F=A/'acceptance_source_adversary_family';W=A/'current_whole_adversary_family';C=A/'reviewed_candidate';B=A.parent/'pr45_9900007';P46=A.parent/'pr46_30004438';H46=P46/'acceptance_preparation_family_v2'
PREP='1a10442d9962db99c608412f53fef754870bfadf24fd76e7e899112fc38ebef1';FM='a4c15b8bc831c71b61e0b6d830904813519eab147d1c7bd1d96987b2e98c0222';PREP46='f44ccf65fa4397736305881de926eafcf211c33ef9e6fec5e5596c99d252ef40'
ROOT_CAPS=[('root_pr47_acceptance_source_closure_actual_capture','e743ef3ee37694d5e668410bcfd75c6ae566bcf01a956c12a1a51d49dcfcbe71',0),('root_pr47_acceptance_source_closed_readback_actual_capture','c01f2b3db1b8d825d59aa4e408108fbdfd3570c2a6d36a45be1ed2497cf0d3e4',0),('root_pr47_acceptance_source_adversary_closure_actual_capture','c8b6233c102476ea31ac4ef13f9562b56f021205c56c3aeeac11bc96f8410ed7',0),('root_pr47_acceptance_source_adversary_closed_readback_v2_actual_capture','8cb8b55c9ce52a848761790636b02d28a5541e7af9c139723131e012f0b4b018',0),('root_pr47_acceptance_source_adversary_closed_readback_actual_capture','bc1ccf66eb0ee51054af9b5553406d749306610704b73dba747cf9b12bbc9fb7',1)]
def need(v,s):
    if not v:raise ValueError(s)
def sha(b):return hashlib.sha256(b).hexdigest()
def now():return dt.datetime.now(dt.timezone.utc).isoformat()
def raw(p):need(p.is_file() and not p.is_symlink() and all(not q.is_symlink() for q in p.parents),'Regular nonsymlink file');return p.read_bytes()
def load(p):
    def pairs(items):
        d={}
        for k,v in items:need(k not in d,'Duplicate JSON key');d[k]=v
        return d
    def floating(s):v=float(s);need(math.isfinite(v),'Nonfinite JSON');return v
    return json.loads(raw(p),object_pairs_hook=pairs,parse_float=floating,parse_constant=lambda s:(_ for _ in ()).throw(ValueError(s)))
def eq(a,b):return type(a) is type(b) and (a.keys()==b.keys() and all(eq(a[k],b[k]) for k in a) if type(a) is dict else len(a)==len(b) and all(eq(x,y) for x,y in zip(a,b)) if type(a) is list else a==b)
def safe(n):
    need(type(n) is str and n and n!='.' and '\\' not in n and '\0' not in n,'Literal path');p=PurePosixPath(n);need(not p.is_absolute() and p.as_posix()==n and not {'.','..','.git','__pycache__'}&set(p.parts),'Canonical repository member');return n
def ref(p,mode=False):
    b=raw(p);o=dict(path=safe(p.relative_to(R).as_posix()),bytes=len(b),sha256=sha(b))
    if mode:o['full_mode']=stat.S_IMODE(p.stat().st_mode)
    return o
def check(z,mode=False):
    need(type(z) is dict and set(z)==({'path','bytes','sha256','full_mode'} if mode else {'path','bytes','sha256'}),'Strict reference keyset');safe(z['path']);need(type(z['bytes']) is int and z['bytes']>=0 and type(z['sha256']) is str and re.fullmatch('[0-9a-f]{64}',z['sha256']),'Typed length/SHA')
    if mode:need(type(z['full_mode']) is int and 0<=z['full_mode']<=0o7777,'Full mode integer')
    need(eq(ref(R/z['path'],mode),z),'Entire bound body/full mode changed');return z
def triple(z):return {k:z[k] for k in ('path','bytes','sha256')}
def clock(s):need(type(s) is str and s==s.strip(),'UTC string');v=dt.datetime.fromisoformat(s[:-1]+'+00:00' if s.endswith('Z') else s);need(v.utcoffset()==dt.timedelta(0),'Aware UTC');return v
def closure(d,n,pin,count):
    need(sha(raw(d/n))==pin,'Exact closed manifest pin');m=load(d/n);need(m['self_excluded']==[n] and type(m['files_count']) is int and m['files_count']==len(m['files'])==count,'Exact self-only count');names=set();out=[]
    for z in m['files']:
        need((set(z)=={'path','bytes','sha256'} or (set(z)=={'path','bytes','sha256','full_mode'} and z['full_mode']=='0444')) and z['path'] not in names,'Unique exact member, preserving WHOLE string0444');safe(z['path']);names.add(z['path']);check(dict(triple(z),path=d.relative_to(R).as_posix()+'/'+z['path']));out.append(ref(d/z['path'],True))
    files=set();dirs=set()
    for p in d.rglob('*'):
        need(not p.is_symlink(),'No symlink');x=safe(p.relative_to(d).as_posix())
        if p.is_file():files.add(x);need(stat.S_IMODE(p.stat().st_mode)==0o444,'Full0444 including special bits')
        else:need(p.is_dir(),'No special member');dirs.add(x)
    need(files==names|{n} and dirs=={p.as_posix() for x in files for p in PurePosixPath(x).parents if p.as_posix()!='.'},'Entire recursive topology')
    if 'directories' in m:need(type(m['directories']) is list and len(m['directories'])==len(dirs) and set(m['directories'])==dirs,'Entire declared directories')
    return m,out
def captured(p,expected=0):
    c=load(p);d=p.parent;need(type(c['exit_code']) is int and c['exit_code']==expected and clock(c['started_utc'])<=clock(c['finished_utc'])<=clock(now()),'Actual exit/UTC');need(type(c['argv']) is list and c['argv'] and all(type(x) is str for x in c['argv']),'Typed actual argv');members={x.name for x in d.iterdir()};need(all(x.is_file() and not x.is_symlink() for x in d.iterdir()),'Only capture files')
    private=c['schema']=='pr47-source-adversary-real-command-capture/v1'
    for k in ('stdout','stderr'):
        z=c[k];q=Path(z['path']) if private else d/safe(z['path']);need(q==d/(k+'.bin'),'Literal stream');need(type(z['bytes']) is int and len(raw(q))==z['bytes'] and sha(raw(q))==z['sha256'],'Whole stream')
    if private:
        need(type(c['child_pid']) is int and c['child_pid']>0 and type(c['operator_pid']) is int and c['operator_pid']>0 and c['expected_exit']==expected and c['status']=='PASS_EXPECTED_EXIT','Real private child');pre=load(d/'PRELAUNCH.json');need(eq(pre['argv'],c['argv']) and pre['operator_pid']==c['operator_pid'] and clock(pre['created_utc'])<=clock(c['started_utc']),'Private prelaunch')
        for k,name in [('operator','prelaunch_operator.py'),('child_source','prelaunch_child_source.py')]:
            z=c[k]
            if z is not None:need(sha(raw(d/name))==z['sha256'] and len(raw(d/name))==z['bytes'],'Complete private prelaunch body');need(eq(pre[k],z),'Original archived source row')
        need(eq(pre['child_source'],c['child_source']) and (c['child_source'] is not None or c['argv'][0]=='git'),'Genuine null Git source');z=c['prelaunch'];need(sha(raw(d/'PRELAUNCH.json'))==z['sha256'] and len(raw(d/'PRELAUNCH.json'))==z['bytes'],'Bound private prelaunch');need(members=={'CAPTURE.json','PRELAUNCH.json','prelaunch_operator.py','stdout.bin','stderr.bin'}|({'prelaunch_child_source.py'} if c['child_source'] is not None else set()),'Exact private CAP5/6')
    else:
        need(c['actual_execution'] is True and c['completed'] is True and type(c['pid']) is int and c['pid']>0 and c['stdin_supplied'] is False and c['operator_unchanged'] is True,'True typed actual completed child')
        if 'PRELAUNCH.json' in members:
            need(members=={'CAPTURE.json','PRELAUNCH.json','PRELAUNCH_SOURCE.py','PRELAUNCH_OPERATOR.py','stdout.bin','stderr.bin'} and type(c['operator_pid']) is int and c['operator_pid']>0,'Exact CAP6 and actual typed operator PID');pre=load(d/'PRELAUNCH.json');need(all(eq(c[k],v) for k,v in pre.items() if k!='schema'),'Whole original prelaunch');need(c['source_unchanged'] is True and sha(raw(d/'PRELAUNCH_SOURCE.py'))==c['source_sha256'] and sha(raw(d/'PRELAUNCH_OPERATOR.py'))==c['operator_sha256'],'Full actual source/operator')
        else:need(members=={'CAPTURE.json','prelaunch_operator.py','stdout.bin','stderr.bin'} and c['schema']=='root-explicit-command-capture/v1' and sha(raw(d/'prelaunch_operator.py'))==c['operator_sha256'],'Exact real ROOT CAP4')
    if expected==0:need(raw(d/'stderr.bin')==b'','Whole success stderr')
    return dict(capture=ref(p),complete_capture=c,complete_members=[ref(x,True) for x in sorted(d.iterdir())])
def predecessor():
    m=load(P46/'state_mirror_bindings.json');post=load(P46/'post_acceptance_verification.json');rp=load(P46/'ROOT_ACTUAL_POST_INSPECTION.json');contract=load(H46/'ROOT_POST_CONTRACT.json');closure(H46,'PREPARATION_MANIFEST.json',PREP46,109)
    need(contract['schema']=='pr46-future-ROOT-whole-post-contract/v1' and contract['source_only'] is True and len(contract['required_ROOT_complete_keyset'])==22 and set(rp)==set(contract['required_ROOT_complete_keyset']),'Genuine entire corrected46V2 ROOT contract');need(rp['schema']==contract['required_ROOT_schema'] and all(eq(rp[k],v) for k,v in contract['required_completed_values'].items()) and eq(rp['entire_post'],post),'Every typed completed ROOT value and entire actual post')
    pinnames=['preparation_manifest_sha256','final_plan','final_plan_sha256','final_receipt','final_receipt_sha256','final_manifest','final_manifest_sha256','reconciliation_capture','reconciliation_capture_sha256','previous_mirror','previous_mirror_sha256','previous_post','previous_post_sha256','fresh_preimage','fresh_preimage_sha256','root_bindings','root_bindings_sha256'];expected={**contract['required_entire_post_values'],**{k:post[k] for k in pinnames},'utc':post['utc'],'merge_commit':post['merge_commit'],'merge_tree':post['merge_tree'],'actual_remote_state':'MERGED'}
    need(eq(post,expected) and post['preparation_manifest_sha256']==PREP46,'Entire exact typed actual46 post, not a subset receipt');need(clock(post['utc'])<=clock(rp['utc'])<=clock(now()),'Predecessor genuinely precedes47 approval')
    for n in ['final_plan','final_receipt','final_manifest','reconciliation_capture','previous_mirror','previous_post','fresh_preimage','root_bindings']:safe(post[n]);need(type(post[n+'_sha256']) is str and re.fullmatch('[0-9a-f]{64}',post[n+'_sha256']) and sha(raw(R/post[n]))==post[n+'_sha256'],'Every exact actual46 final pin')
    need(type(m['entries']) is list and len(m['entries'])==36 and all(type(z['pr']) is int for z in m['entries']) and sorted(z['pr'] for z in m['entries'])==m['required_completed_prs'] and len(set(m['required_completed_prs']))==36 and 46 in m['required_completed_prs'] and 47 not in m['required_completed_prs'] and len(m['duplicate_mirrors'])==1,'Whole actual predecessor primary/duplicate membership')
    phases=['preflight','overlay','prepush','finalize','mirror','post'];need(type(rp['all_six_real_phase_captures']) is list and len(rp['all_six_real_phase_captures'])==6,'Exactly six genuine phase captures');caps=[];end=None
    for phase,z in zip(phases,rp['all_six_real_phase_captures']):
        check(z);p=P46/('root_'+phase+'_actual_capture')/'CAPTURE.json';need(z['path']==p.relative_to(R).as_posix(),'Exact phase identity');row=captured(p);c=row['complete_capture'];name={'mirror':'state_mirror_reconciliation.py','post':'verify_post_acceptance.py'}.get(phase,'integrate_reviewed_partial.py');need(c['schema']=='ROOT_actual_reviewed_acceptance_phase_capture_v1' and c['phase']==phase and c['cwd']==str(R) and c['argv'][:3]==['/usr/bin/python3','-B',str(H46/name)] and c['source_sha256']==sha(raw(H46/name)) and c['operator_sha256']==sha(raw(P46/'run_actual_acceptance_phases.py')),'Actual46 exact source/operator/argv');need((end is None or end<=clock(c['started_utc'])) and clock(c['finished_utc'])<=clock(rp['utc']),'Phase order and post-exit ROOT read')
        for n in pinnames:flag='--'+n.replace('_','-');need(c['argv'].count(flag)==1 and c['argv'][c['argv'].index(flag)+1]==post[n],'Every actual46 phase argv pin matches entire post')
        end=clock(c['finished_utc']);caps.append(row)
    need(type(rp['current13']) is list and len(rp['current13'])==13 and {z['path'] for z in rp['current13']}=={z['path'] for z in load(H/'INPUT_BINDINGS.json')['dated_native13']},'Complete exact native13 identities, current bodies checked separately')
    mutable4={'draft_pr_publication_program_20260930/inventory.json','unsolved_math_prioritization/QUEUE.md','unsolved_math_prioritization/state.json','unsolved_math_prioritization/history.jsonl'}
    for z in rp['current13']:
        need(set(z)=={'path','bytes','sha256','worktree_mode'} and type(z['worktree_mode']) is int and z['worktree_mode']==0o644 and type(z['bytes']) is int and z['bytes']>=0 and type(z['sha256']) is str and re.fullmatch('[0-9a-f]{64}',z['sha256']),'Typed historical actual13 restricted full0644 row');safe(z['path']);need(ref(R/z['path'],True)['full_mode']==0o644,'Every current13 remains regular full0644')
        if z['path'] not in mutable4:check(dict(triple(z),full_mode=z['worktree_mode']),True)
    mirrorplan=load(P46/'state_mirror_plan.json');intent=load(P46/'state_mirror_intent.json');currentstate=load(R/'unsolved_math_prioritization/state.json');need(eq(currentstate,mirrorplan['state_after']) and len(currentstate)==37 and all(type(v['turns_used']) is int for v in currentstate.values()) and sum(v['turns_used'] for v in currentstate.values())==44 and eq(raw(R/'unsolved_math_prioritization/history.jsonl'),(intent['before_history_bytes']+mirrorplan['history_append_bytes']).encode()),'Current complete genuine46 state/history baseline remains37targets44turns36primary; mutable4 dated pins are not forever-live authority')
    return m,post,rp,caps
def qualified_predecessor_readback(rp,phases):
    p=P46/'root_complete_actual_post_inspection_capture_v2/CAPTURE.json';need(sha(raw(p))=='3b7fc6fec64677e59433d5c385b151346c0ad570a1a30bb121f10b3c40f9c27b','Genuine pinned actual46 V2 whole-post CAP4');cap=captured(p);c=cap['complete_capture'];source=P46/'inspect_complete_actual_post_v2.py';need(c['argv']==['/usr/bin/python3','-B',str(source)] and sha(raw(source))==sha(raw(P46/'ROOT_POST_INSPECTION_PRELAUNCH_SOURCE_V2.py'))=='2b0e50f0415d25a9236cdb931b26562fda64c5c2a200dec724fa4843df1e517f','Whole genuine V2 ROOT source');need(clock(c['started_utc'])<=clock(rp['utc'])<=clock(c['finished_utc']),'ROOT whole-post created during actual V2 child')
    q=P46/'ROOT_POST_DATED_FOREIGN_CHANGE_READBACK.json';need(sha(raw(q))=='1e9bf1dd2ecbf7826a7aaaf47d92f590616be29418208f40b41a1d2a2424e91e' and sha(raw(P46/'ROOT_ACTUAL_POST_INSPECTION.json'))=='17777f55e0049b3ec0239a045ac5ea59ceaf936b29d8e8c7e4a7f4374fce1c04','Actual qualified22-key post and separate dated record');d=load(q);out=load(p.parent/'stdout.bin');need(eq(out,dict(status='PASS_COMPLETE_ACTUAL_ROOT_POST_INSPECTION',merge_commit=rp['entire_post']['merge_commit'],primary_acceptances=36,targets=37,consumed_substantive_turns=44,inspection=ref(P46/'ROOT_ACTUAL_POST_INSPECTION.json'),dated_foreign_readback=ref(q))),'Entire actual V2 stdout pins both mandatory records')
    values=dict(schema='pr46-root-post-dated-foreign-change-readback/v2',status='VERIFIED_LATER_APPEND_WITH_QUALIFIED_OLD_EPOCH',outside_22_key_contract=True,separate_record_is_required_readback=True,no_live_foreign_body_equality_claim=True,all_five_live_bodies_equal_preflight=False,foreign_file_mutated_by_inspection=False,all_other_four_live_protected_bodies_and_modes_exact=True,all_five_live_Git_HEAD_index_checked_by_qualified_guard=True,qualified_regular_proxy_only_path='draft_pr_descending_audit_20261002/audits/pr373_30004435/RESEARCH_LOG.md',qualified_checks=['foreign_check','owned_log_append_check']);need(all(eq(d[k],v) for k,v in values.items()),'Every exact typed old-epoch qualification required, never blanket current equality');need(eq(d['original_post_phase_capture'],phases[-1]['capture']) and d['original_post_finished_utc']==phases[-1]['complete_capture']['finished_utc'] and clock(d['original_post_finished_utc'])<clock(d['later_append_utc'])<=clock(d['utc'])<=clock(rp['utc']) and clock(c['started_utc'])<=clock(d['utc']),'Original completed post, later append and actual readback order')
    snapshots={}
    for k in ['prefix_snapshot','current_body_snapshot','entire_append_snapshot']:z=d[k];need(set(z)=={'path','bytes','sha256','worktree_mode'} and type(z['worktree_mode']) is int and z['worktree_mode']==0o644,'Exact dated snapshot0644');check(dict(triple(z),full_mode=z['worktree_mode']),True);snapshots[k]=raw(R/z['path'])
    need(snapshots['prefix_snapshot']+snapshots['entire_append_snapshot']==snapshots['current_body_snapshot'] and sha(snapshots['prefix_snapshot'])==d['entire_original_preflight_row']['sha256'],'Exact retained old prefix plus entire actual later append');rows=d['all_five_actual_current_worktree_readbacks'];need(type(rows) is list and len(rows)==5 and len({z['path'] for z in rows})==5 and sum(z['live_equals_preflight_body'] is False for z in rows)==1 and all(type(z['live_equals_preflight_body']) is bool and type(z['worktree_mode']) is int and z['worktree_mode']==0o644 for z in rows),'Five dated observations, exactly one changed body; not live dependencies');need(eq(d['live_HEAD_index_before'],d['live_HEAD_index_after']),'Actual dated HEAD/index preserved')
    for k in ['current_V2_source','failed88416_capture','failed88416_entire_stderr','failed88416_source','actual_readonly_Git_command_index']:check(d[k])
    failed=captured(R/d['failed88416_capture']['path'],1);need(failed['complete_capture']['status']=='FAIL' and failed['complete_capture']['pid']==88416,'Actual failed older ROOT read remains failure');return dict(actual_whole_post_capture=cap,entire_qualified_dated_foreign_record=d,dated_record_reference=ref(q),current_V2_source=ref(source),complete_failed_prior_whole_post_capture=failed,dated_foreign_rows_are_not_future_live_closure_dependencies=True)
def put(p,b):
    need(p.parent==A and not p.exists() and not p.is_symlink(),'Absent adjacent ROOT output only')
    with p.open('xb') as f:f.write(b);f.flush();os.fsync(f.fileno())
    need(stat.S_IMODE(p.stat().st_mode)==0o644,'ROOT author outputs full0644 under explicit0022 umask')
def encode(o):return (json.dumps(o,indent=2,sort_keys=True,ensure_ascii=False,allow_nan=False)+'\n').encode()
def main():
    need(__debug__ and sys.flags.optimize==0 and sys.argv==[sys.argv[0],'--personally-read-complete-source'],'ROOT personally reads before explicit attestation');need(A.name=='pr47_2849' and raw(Path(__file__))==raw(A/'root_acceptance_author_preparation/author_ROOT_acceptance.py'),'ROOT must copy exact SOURCE adjacent, never execute preparation path')
    outputs=['capture_root_final_operation.py','ROOT_SOURCE_ACCEPTANCE_REVIEW.json','ROOT_IMMUTABLE_ACCEPTANCE_BINDINGS.json','ROOT_FINAL_PLAN.json'];need(all(not (A/n).exists() and not (A/n).is_symlink() for n in outputs),'Never replace ROOT records');previous,post,rp,previouscaps=predecessor();qualified46=qualified_predecessor_readback(rp,previouscaps)
    prep,prepared=closure(H,'PREPARATION_MANIFEST.json',PREP,126);fm,owned=closure(F,'SELF_MANIFEST.json',FM,85);inputs=load(H/'INPUT_BINDINGS.json');external=load(F/'EXTERNAL_INPUT_BINDINGS.json');need(external['files_count']==len(external['files'])==3478 and external['mutable_native4_are_dated_observations_not_live_closure_dependencies'] is True and external['unfinished_design_recorded_mode_is_dated'] is True,'Exact stable fixed union and dated qualifications')
    need(len({z['path'] for z in external['files']})==3478,'Unique complete external identities')
    for z in external['files']:check(z,True)
    current,_=closure(C,'MANIFEST.json','a7d1acc9dbbf8cd5435d0bebd8f6b1a540ecb0f2aea8d0c616c46bc5bf6b4ea5',1328);whole,_=closure(W,'MANIFEST.json','658133399198e8528aa2a45b89c87a19f3b69edd6998b86b7e8227c850f5fd78',385)
    for p,n in [(C/'CURRENT_DEPENDENCIES.json','EXPECTED_CURRENT_DEPENDENCIES.json'),(W/'MANIFEST.json','EXPECTED_WHOLE_MANIFEST.json'),(W/'VERDICT.json','EXPECTED_WHOLE_VERDICT.json'),(A/'ROOT_WHOLE_CURRENT_REVIEW.json','EXPECTED_ROOT_WHOLE_REVIEW.json'),(A/'ROOT_PRIMARY_READ_LEDGER.json','EXPECTED_PRIMARY_READ_LEDGER.json'),(A/'ROOT_SCIENCE_CARD.json','EXPECTED_SCIENCE_CARD.json'),(A/'root_original_actual_reproduction/ROOT_REPRODUCTION_RESULT.json','EXPECTED_ORIGINAL_CAPTURE_RESULT.json')]:need(eq(load(p),load(H/n)),'Whole typed fixed record differs')
    need(len(inputs['external_input_rows'])==inputs['external_input_count']==2933 and inputs['actual_predecessor_PR46_completed'] is False and inputs['whole_binding_completed'] is True,'SOURCE not actual predecessor');science=load(H/'SCIENTIFIC_SCOPE.json');plan=load(H/'DRAFT_FINAL_PLAN.json');need(eq(plan['scientific_scope'],science) and science['literal_target_status']=='unsolved' and science['original_substantive_attempts']==1 and science['new_substantive_attempts']==science['audit_turns']==0 and science['partial_valid'] is True and science['realized_example_instanton_rank_computed'] is False and science['quartic_model_realized_as_Chern_Simons'] is False and science['trefoil_auxiliary_version_scope_only'] is True,'Entire UNSOLVED1/5 realized/quartic/trefoil scope')
    v=load(F/'VERDICT.json');need(v['schema']=='pr47-acceptance-source-adversary-verdict/v1' and v['verdict']=='PASS_SOURCE_ONLY_SCOPED' and v['preparation_manifest_sha256']==PREP and v['mandatory_corrections']==[] and v['production_imported_compiled_executed'] is False and v['future_acceptance_approved'] is False,'Scoped SOURCE verdict only')
    own=[]
    for p in sorted(H.rglob('CAPTURE.json')):own.append(captured(p,1 if p.parent.name in {'private_controls_v1_actual_capture','expected_negative_actual_capture'} else 0))
    need(len(own)==10 and {z['complete_capture']['pid'] for z in own if z['complete_capture']['exit_code']==1}=={8441,17860},'Preserve exact ten preparation captures and both real failures');own += [captured(p) for p in sorted(F.rglob('CAPTURE.json'))];need(len(own)==22,'All twelve fresh SOURCE private/Git captures')
    rootcaps=[]
    for n,pin,exit_code in ROOT_CAPS:p=B/n/'CAPTURE.json';need(sha(raw(p))==pin,'Pinned actual ROOT source-close/readback capture');rootcaps.append(captured(p,exit_code))
    for first,last,m,closer,verifier in [(rootcaps[0],rootcaps[1],prep,H/'close_source.py',H/'verify_closed_source.py'),(rootcaps[2],rootcaps[3],fm,F/'close_source_adversary.py',F/'verify_closed_source_adversary.py')]:
        c,d=first['complete_capture'],last['complete_capture'];need(c['argv'][2]==str(closer) and d['argv'][2]==str(verifier) and clock(c['started_utc'])<=clock(m['utc'])<=clock(c['finished_utc'])<clock(d['started_utc']),'Actual manifest creation and separate post-exit readback')
    native_before=[ref(R/z['path'],True) for z in rp['current13']]
    for p in [R/'draft_pr_publication_program_20260930/RESEARCH_LOG.md',A/'ROOT_RESEARCH_LOG.md']:
        if p.exists():need(stat.S_IMODE(p.stat().st_mode)==0o644 and not p.is_symlink(),'Existing mutable owned log must be full0644 in restricted ROOT scope')
    old_umask=os.umask(0o022);inspection=dict(schema='pr47-root-complete-acceptance-source-inspection/v1',status='PASS_ROOT_COMPLETE_ACCEPTANCE_SOURCE_INSPECTION',utc=now(),all_prepared_source_and_controls_fully_read=True,exact_preparation_closure_and_full_modes_checked=True,all_individual_source_adversary_inputs_checked=True,all_complete_actual_captures_checked=True,complete_VERDICT_object=v,preparation_manifest_sha256=PREP,acceptance_source_manifest=ref(F/'SELF_MANIFEST.json'),acceptance_source_verdict=ref(F/'VERDICT.json'),mandatory_corrections=[],future_execution_approved=False,complete_prepared_bindings=prepared,complete_closed_adversary_bindings=owned,normalized_complete_external_input_bindings=external['files'],complete_actual_closing_and_postclosing_readback_captures=rootcaps[2:4],all_complete_source_captures=own+rootcaps,entire_actual_PR46_post=post,entire_actual_PR46_ROOT_post=rp,complete_actual_PR46_phase_captures=previouscaps,archived_capture_modes_are_dated_not_final_modes=True,native13_before_authoring=native_before,ROOT_permission_authority_scope=dict(native13_and_mutable_destinations_full_mode=0o644,required_operator_umask=0o022,actual_author_previous_umask=old_umask,actual_author_umask=0o022,arbitrary_mode_writer_correctness_accepted=False,later_phase_umask_and_before_after_modes_must_be_enforced_by_ROOT=True,frozen0444_science_is_a_separate_scope=True),ROOT_personal_reading='ROOT attests personal complete source/report/contract and prior current/whole reading before running; runtime checks reconcile all fixed bodies/types/full modes and genuine completed46. Authority is restricted to full0644 mutable writes with operator umask0022; general arbitrary-mode correctness is not accepted. This source preparation supplies no such approval.')
    inspection['complete_actual_PR46_qualified_whole_post_readback']=qualified46
    inspection['actual_PR46_native13_epoch_qualification']=dict(historical_current13=rp['current13'],mutable_native4_are_dated_observations_not_future_live_authority=True,current13_regular_full0644_checked=True,current_stable9_exact_old_post_checked=True,complete_current46_state_history_baseline_checked=True,current_QUEUE_and_inventory_need_separate_fresh47_ROOT_authority=True,author_current13_before_after_guarantee_is_own_epoch_only=True)
    operator_body=raw(H/'capture_root_final_operation.py');operator=A/'capture_root_final_operation.py';inspection_body=encode(inspection);bindings=load(H/'DRAFT_ROOT_IMMUTABLE_BINDINGS.json');bindings.update(status='ROOT_APPROVED_CLOSED_WHOLE_SOURCE_AND_ACTUAL_PR46_EVIDENCE',created_utc=now(),root_full_current_read_completed=True,root_full_whole_read_completed=True,root_acceptance_source_review_completed=True,independent_whole_current_pass=True,root_actual_PR46_predecessor_read_completed=True)
    paths=dict(whole_manifest=W/'MANIFEST.json',root_whole_inspection=A/'ROOT_WHOLE_CURRENT_REVIEW.json',previous_mirror=P46/'state_mirror_bindings.json',previous_post=P46/'post_acceptance_verification.json',previous_root_post=P46/'ROOT_ACTUAL_POST_INSPECTION.json',previous_post_contract=H46/'ROOT_POST_CONTRACT.json',acceptance_source_manifest=F/'SELF_MANIFEST.json',acceptance_source_verdict=F/'VERDICT.json')
    for k,p in paths.items():bindings[k]=ref(p)
    bindings['root_capture_operator']=dict(path=operator.relative_to(R).as_posix(),bytes=len(operator_body),sha256=sha(operator_body));bindings['root_source_inspection']=dict(path=(A/'ROOT_SOURCE_ACCEPTANCE_REVIEW.json').relative_to(R).as_posix(),bytes=len(inspection_body),sha256=sha(inspection_body));bindings_body=encode(bindings);binding_ref=dict(path=(A/'ROOT_IMMUTABLE_ACCEPTANCE_BINDINGS.json').relative_to(R).as_posix(),bytes=len(bindings_body),sha256=sha(bindings_body))
    refs=[triple(inputs['pins'][n]) for n in sorted(inputs['pins'])]+[ref(C/'MANIFEST.json'),ref(C/'CURRENT_DEPENDENCIES.json'),ref(W/'MANIFEST.json'),ref(W/'AUDIT.md'),ref(W/'VERDICT.json'),ref(A/'ROOT_WHOLE_CURRENT_REVIEW.json'),binding_ref]+[bindings[k] for k in ['previous_mirror','previous_post','previous_root_post','previous_post_contract','acceptance_source_manifest','acceptance_source_verdict','root_source_inspection','root_capture_operator']];dedup={}
    for z in refs:need(z['path'] not in dedup or eq(dedup[z['path']],z),'Exact immutable plan identity');dedup[z['path']]=z
    plan.update(plan_status='ROOT_REVIEWED_FOR_ACTUAL_RECONCILIATION',partial_valid=True,preparation_manifest_sha256=PREP,root_bindings=binding_ref['path'],root_bindings_sha256=binding_ref['sha256'],whole_manifest_sha256=bindings['whole_manifest']['sha256'],root_full_current_read_completed=True,root_full_whole_read_completed=True,root_acceptance_source_review_completed=True,independent_whole_current_pass=True,root_actual_PR46_predecessor_read_completed=True,immutable_evidence_references=sorted(dedup.values(),key=lambda z:z['path']))
    for p,b in [(operator,operator_body),(A/'ROOT_SOURCE_ACCEPTANCE_REVIEW.json',inspection_body),(A/'ROOT_IMMUTABLE_ACCEPTANCE_BINDINGS.json',bindings_body),(A/'ROOT_FINAL_PLAN.json',encode(plan))]:put(p,b)
    for z in refs:check(z)
    need(eq(native_before,[ref(R/z['path'],True) for z in rp['current13']]),'ROOT author must leave all native13 bodies/full0644 modes unchanged')
    print(json.dumps(dict(status='PASS_ROOT_COMPLETE_SOURCE_AND_GENUINE_ACTUAL46_BINDINGS',actual_pid=os.getpid(),prepared=126,adversary=85,individual_external=3478,complete_source_captures=len(own)+len(rootcaps),actual46_phase_captures=6,plan_references=len(dedup),future_execution_approved=False)))
if __name__=='__main__':main()
