import Bell

/-! Generated axiom-dependency queries for public theorem declarations.
Private helper dependencies are checked transitively through their public clients.
Generating these commands does not execute Lean or establish any theorem. -/

#print axioms Bell.two_three_ordering
#print axioms Bell.no_two_input_extreme_separator
#print axioms Bell.two_input_convex_equality
#print axioms Bell.universal_two_input_equality
#print axioms Bell.at_most_two_input_equality
#print axioms Bell.main_claims
#print axioms Bell.minimum_inputs
#print axioms Bell.minimum_inputs_attained
#print axioms Bell.no_two_input_strict_separation
#print axioms Bell.binary_span_sum_le_three
#print axioms Bell.binary_bob_simulation
#print axioms Bell.extreme_binary_bob_simulation
#print axioms Bell.ConeCircuits.outcomeVector_sum
#print axioms Bell.ConeCircuits.coarsening_refined_behavior
#print axioms Bell.ConeCircuits.binary_circuit_mem_convexPVM
#print axioms Bell.ConeCircuits.circuit_section_mem_convexPVM
#print axioms Bell.ClassicalProduct.total_mass
#print axioms Bell.ClassicalProduct.total_mass_one
#print axioms Bell.ClassicalProduct.pin_mass
#print axioms Bell.ClassicalProduct.marginal
#print axioms Bell.ClassicalProduct.conditional_normalized
#print axioms Bell.ClassicalProduct.weight_nonnegative
#print axioms Bell.ClassicalProduct.weight_normalized
#print axioms Bell.ClassicalProduct.entry_zero_of_marginal_zero
#print axioms Bell.ClassicalProduct.reconstruction
#print axioms Bell.FullPureStrategy.reduced_definite
#print axioms Bell.FullPureStrategy.steered_positive
#print axioms Bell.FullPureStrategy.steered_sum
#print axioms Bell.FullPureStrategy.behavior_steered
#print axioms Bell.FullPureStrategy.filteredTable_mem_rawPOVM
#print axioms Bell.extreme_common_coefficients
#print axioms Bell.extreme_common_span_scalar
#print axioms Bell.ConeCircuits.weights_convex
#print axioms Bell.ConeCircuits.weights_isClosed
#print axioms Bell.ConeCircuits.weights_isCompact
#print axioms Bell.ConeCircuits.balance_sideSum
#print axioms Bell.ConeCircuits.mass_sideSum
#print axioms Bell.ConeCircuits.sideSum_equal
#print axioms Bell.ConeCircuits.sideSum_time_half
#print axioms Bell.ConeCircuits.sideSupport_nonempty
#print axioms Bell.ConeCircuits.extreme_relation_zero
#print axioms Bell.ConeCircuits.extreme_support_le_four
#print axioms Bell.ConeCircuits.future_nonnegative_smul
#print axioms Bell.ConeCircuits.future_sum
#print axioms Bell.ConeCircuits.sideSum_future
#print axioms Bell.ConeCircuits.extreme_singleton_other_le_one
#print axioms Bell.ConeCircuits.side_card_sum
#print axioms Bell.ConeCircuits.extreme_side_card_le_two
#print axioms Bell.ConeCircuits.all_weights_map_into
#print axioms Bell.QubitGeometry.dot_self_positive
#print axioms Bell.QubitGeometry.normalizeVector_unit
#print axioms Bell.QubitGeometry.exists_unit_annihilator
#print axioms Bell.QubitGeometry.compress_time
#print axioms Bell.QubitGeometry.compress_orthogonal
#print axioms Bell.QubitGeometry.compress_square
#print axioms Bell.QubitGeometry.compress_future
#print axioms Bell.QubitGeometry.compress_pairing
#print axioms Bell.QubitGeometry.normalHyperplane_dim_le_three
#print axioms Bell.QubitGeometry.exists_spatial_unit_perpendicular
#print axioms Bell.QubitGeometry.radius_nonnegative
#print axioms Bell.QubitGeometry.radius_square
#print axioms Bell.QubitGeometry.radius_le_time
#print axioms Bell.QubitGeometry.splitDirection_time
#print axioms Bell.QubitGeometry.splitDirection_unit
#print axioms Bell.QubitGeometry.radius_direction
#print axioms Bell.QubitGeometry.nullPiece_sum
#print axioms Bell.QubitGeometry.nullPiece_null_or_zero
#print axioms Bell.QubitGeometry.nullPiece_in_plane
#print axioms Bell.finite_mixture_bound
#print axioms Bell.linear_bound_on_convexHull
#print axioms Bell.filtering_average
#print axioms Bell.binary_spectral_weights
#print axioms Bell.Lorentz.DeterministicGap.reset_ray
#print axioms Bell.Lorentz.DeterministicGap.reset_unit
#print axioms Bell.Lorentz.DeterministicGap.reset_idempotent
#print axioms Bell.Lorentz.DeterministicGap.compatibility_reset
#print axioms Bell.Lorentz.DeterministicGap.compatibility_id
#print axioms Bell.Lorentz.DeterministicGap.stationary_gap
#print axioms Bell.Lorentz.DeterministicGap.multipliers_positive
#print axioms Bell.Lorentz.DeterministicGap.multiplier_formula
#print axioms Bell.ClassicalProduct.reconstruction_alice_marginal
#print axioms Bell.ClassicalProduct.reconstruction_with_deterministic_input
#print axioms Bell.otherInput_ne
#print axioms Bell.eq_otherInput_of_ne
#print axioms Bell.born_deterministic
#print axioms Bell.replacement_behavior
#print axioms Bell.replaceBobInput_mem_convexPVM
#print axioms Bell.replaceBobRay_mem_convexPVM
#print axioms Bell.strict_gap_to_deterministic_replacements
#print axioms Bell.ideal_dual_slack0
#print axioms Bell.ideal_dual_slack1
#print axioms Bell.ideal_dual_slack2
#print axioms Bell.ideal_dual_feasible
#print axioms Bell.ideal_complementarity
#print axioms Bell.ideal_discrimination_upper
#print axioms Bell.ideal_discrimination_attained
#print axioms Bell.tensor_add_left
#print axioms Bell.tensor_add_right
#print axioms Bell.tensor_sub_left
#print axioms Bell.tensor_sub_right
#print axioms Bell.tensor_smul_left
#print axioms Bell.tensor_smul_right
#print axioms Bell.tensor_zero_left
#print axioms Bell.tensor_zero_right
#print axioms Bell.tensor_neg_left
#print axioms Bell.tensor_neg_right
#print axioms Bell.tensor_one_one
#print axioms Bell.tensor_mul
#print axioms Bell.tensor_conjTranspose
#print axioms Bell.tensor_sum_left
#print axioms Bell.tensor_sum_right
#print axioms Bell.positive_trace_nonneg
#print axioms Bell.expectation_apply
#print axioms Bell.state_expectation_one
#print axioms Bell.state_expectation_square_nonneg
#print axioms Bell.state_expectation_positive
#print axioms Bell.tensor_positive
#print axioms Bell.born_nonnegative
#print axioms Bell.born_eq_expectation
#print axioms Bell.born_sum_alice
#print axioms Bell.born_sum_bob
#print axioms Bell.born_normalization
#print axioms Bell.strategy_behavior_nonnegative
#print axioms Bell.strategy_behavior_normalization
#print axioms Bell.strategy_no_signaling_to_alice
#print axioms Bell.strategy_no_signaling_to_bob
#print axioms Bell.extreme_perturbation_marginals
#print axioms Bell.extreme_scalar_relation
#print axioms Bell.extreme_effect_independent
#print axioms Bell.extreme_fullrank_effect_deterministic
#print axioms Bell.extreme_nondeterministic_effects_null
#print axioms Bell.probabilitySimplex_isCompact
#print axioms Bell.combinations_isCompact
#print axioms Bell.combinations_subset_convexHull
#print axioms Bell.convexHull_eq_finite_combinations
#print axioms Bell.compact_convexHull
#print axioms Bell.extreme_midpoint
#print axioms Bell.extreme_positive_combination
#print axioms Bell.contains_compact_of_contains_extreme
#print axioms Bell.mem_range_iff_annihilators
#print axioms Bell.finite_functional_coordinates
#print axioms Bell.Lorentz.nullRowMap_single
#print axioms Bell.Lorentz.metricDifferential_apply
#print axioms Bell.Lorentz.metricDifferential_pairing
#print axioms Bell.Lorentz.metric_stationary_iff
#print axioms Bell.Lorentz.exists_metric_increment
#print axioms Bell.Lorentz.exists_compatible_metric
#print axioms Bell.UnnormalizedAssemblage.root_hermitian
#print axioms Bell.UnnormalizedAssemblage.root_square
#print axioms Bell.UnnormalizedAssemblage.root_invertible
#print axioms Bell.UnnormalizedAssemblage.normalizedAssemblage_invertible
#print axioms Bell.UnnormalizedAssemblage.normalized_behavior
#print axioms Bell.UnnormalizedAssemblage.behavior_mem_rawPOVM
#print axioms Bell.Lorentz.frameGram_symmetric
#print axioms Bell.Lorentz.frameGram_pair
#print axioms Bell.Lorentz.steeringFrame_time
#print axioms Bell.Lorentz.steeringFrame_square
#print axioms Bell.Lorentz.frame_probability
#print axioms Bell.Lorentz.isOpen_framePositive
#print axioms Bell.Lorentz.frame_table_mem_rawPOVM
#print axioms Bell.Lorentz.symmetricMatrix_symmetric
#print axioms Bell.Lorentz.symmetricCoordinates_matrix
#print axioms Bell.Lorentz.symmetricMatrix_coordinates
#print axioms Bell.Lorentz.frameGram_hasStrictFDerivAt
#print axioms Bell.Lorentz.gramCoordinates_hasStrictFDerivAt
#print axioms Bell.Lorentz.gramMatrixDerivative_right_inverse
#print axioms Bell.Lorentz.gramDerivative_surjective
#print axioms Bell.Lorentz.exists_local_gram_lift
#print axioms Bell.Lorentz.eventually_feasible_mem_rawPOVM
#print axioms Bell.Lorentz.physical_maximum_is_incidence_maximum
#print axioms Bell.exists_level_curve
#print axioms Bell.Lorentz.continuous_weightedGram
#print axioms Bell.Lorentz.quadratic_gap_limit
#print axioms Bell.Lorentz.eventually_score_improvement
#print axioms Bell.Lorentz.not_local_max_of_uphill_curve
#print axioms Bell.Lorentz.linearOfMatrix_apply
#print axioms Bell.Lorentz.matrixOfLinear_mulVec
#print axioms Bell.Lorentz.matrixOfLinear_id
#print axioms Bell.Lorentz.matrixOfLinear_add
#print axioms Bell.Lorentz.matrixOfLinear_smul
#print axioms Bell.Lorentz.linearOfMatrix_matrixOfLinear
#print axioms Bell.Lorentz.matrixPair_apply
#print axioms Bell.Lorentz.matrixPair_transpose
#print axioms Bell.Lorentz.matrixPair_symmetric
#print axioms Bell.Lorentz.matrixPair_add_matrix
#print axioms Bell.Lorentz.matrixPair_sub_matrix
#print axioms Bell.Lorentz.matrixPair_smul_matrix
#print axioms Bell.Lorentz.pullbackForm_apply
#print axioms Bell.Lorentz.chartMetric_add
#print axioms Bell.Lorentz.chartMetric_sub
#print axioms Bell.Lorentz.chartMetric_symmetric
#print axioms Bell.Lorentz.metricVariation_symmetric
#print axioms Bell.Lorentz.metricVariation_quadratic
#print axioms Bell.Lorentz.chartMetric_null
#print axioms Bell.Lorentz.chartMetric_unit
#print axioms Bell.Lorentz.weightedPairing_mul
#print axioms Bell.Lorentz.weightedCross_self
#print axioms Bell.Lorentz.weightedGram_zero_of_null
#print axioms Bell.Lorentz.weightedGram_add_metric
#print axioms Bell.Lorentz.weightedGram_sub_metric
#print axioms Bell.Lorentz.weightedCross_add_right
#print axioms Bell.Lorentz.weightedGram_add_frame
#print axioms Bell.Lorentz.weightedGram_smul_frame
#print axioms Bell.Lorentz.exact_stationary_score_gap
#print axioms Bell.Lorentz.contDiff_incidenceConstraints
#print axioms Bell.Lorentz.polynomial_score_gap
#print axioms Bell.Lorentz.constraintDerivativeCLM_apply
#print axioms Bell.Lorentz.nullDerivative_symmetric
#print axioms Bell.Lorentz.incidenceNull_hasStrictFDerivAt
#print axioms Bell.Lorentz.probabilityBlock_hasStrictFDerivAt
#print axioms Bell.Lorentz.incidenceMass_hasStrictFDerivAt
#print axioms Bell.Lorentz.incidenceConstraints_hasStrictFDerivAt
#print axioms Bell.Lorentz.nullDerivativeSeed_values
#print axioms Bell.Lorentz.matrixPair_mul_frames
#print axioms Bell.Lorentz.nullDerivative_seed_preimage
#print axioms Bell.Lorentz.constraintDerivative_radial
#print axioms Bell.Lorentz.constraintDerivative_surjective
#print axioms Bell.Lorentz.constraintDerivative_range
#print axioms Bell.Lorentz.frameEquiv_apply
#print axioms Bell.Lorentz.kernel_dimension_le_three
#print axioms Bell.Lorentz.uphill_annihilating_kernel
#print axioms Bell.Lorentz.weightedGram_frame_action
#print axioms Bell.Lorentz.exists_positive_normalized_tangent
#print axioms Bell.Lorentz.high_rank_not_local_max
#print axioms Bell.Lorentz.rank_zero_rows
#print axioms Bell.Lorentz.rank_one_row_coordinates
#print axioms Bell.Lorentz.rank_one_stationarity_impossible
#print axioms Bell.Lorentz.chartMetric_parameterVector
#print axioms Bell.Lorentz.timeFunctional_eq_matrixPair
#print axioms Bell.Lorentz.rank_zero_block_mem
#print axioms Bell.Lorentz.tableOfBlock_apply
#print axioms Bell.Lorentz.actedBlock_mulVec
#print axioms Bell.Lorentz.actedBlock_id
#print axioms Bell.Lorentz.actedTable_apply
#print axioms Bell.Lorentz.sum_effectRay
#print axioms Bell.Lorentz.tableOfBlock_bob_marginal
#print axioms Bell.Lorentz.reset_effectRay
#print axioms Bell.Lorentz.actedTable_reset
#print axioms Bell.Lorentz.actedTable_reset_physical
#print axioms Bell.Lorentz.blockMass_actedBlock
#print axioms Bell.Lorentz.weightedPairing_actedBlock
#print axioms Bell.Lorentz.multipliers_positive_from_physical_separator
#print axioms Bell.Lorentz.tableOfBlock_eq_transformedMetricTable
#print axioms Bell.exists_normalized_lagrange
#print axioms Bell.Lorentz.constraint_functional_coordinates
#print axioms Bell.Lorentz.feasible_iff_constraints_eq
#print axioms Bell.Lorentz.exists_incidence_lagrange
#print axioms Bell.Lorentz.lagrange_frame_variations
#print axioms Bell.Lorentz.lagrange_metric_variations
#print axioms Bell.Lorentz.metric_invertible_of_block
#print axioms Bell.Lorentz.frame_invertible_of_block
#print axioms Bell.Lorentz.lagrange_block_stationarity
#print axioms Bell.Lorentz.lagrange_metric_stationarity
#print axioms Bell.Lorentz.exists_incidence_stationarity
#print axioms Bell.deterministic_behavior
#print axioms Bell.deterministic_mem_rawPVM
#print axioms Bell.finite_local_mixture_mem_convexPVM
#print axioms Bell.transportMixture_mem
#print axioms Bell.transportMixture_eq
#print axioms Bell.rankZeroTable_mem_of_transport
#print axioms Bell.rankZeroTable_mem
#print axioms Bell.Lorentz.binary_circuit
#print axioms Bell.Lorentz.ternary_circuit
#print axioms Bell.Lorentz.circuit_kernel
#print axioms Bell.Lorentz.weightedOuter_injective_zero
#print axioms Bell.Lorentz.metric_quadratic
#print axioms Bell.Lorentz.coefficient_rays_null
#print axioms Bell.Lorentz.metric_normalization
#print axioms Bell.Lorentz.phi_differences
#print axioms Bell.Lorentz.phi_minor
#print axioms Bell.Lorentz.inverse_identity
#print axioms Bell.Lorentz.inverse_homogeneous
#print axioms Bell.Lorentz.generic_recovery
#print axioms Bell.Lorentz.phi_zero_null_base
#print axioms Bell.Lorentz.baseLines_phi_zero
#print axioms Bell.Lorentz.cross_x2_identity
#print axioms Bell.Lorentz.cross_x3_identity
#print axioms Bell.Lorentz.cross_x2_is_base
#print axioms Bell.Lorentz.cross_x3_is_base
#print axioms Bell.Lorentz.direct_zero_chart_unique
#print axioms Bell.Lorentz.linearEliminant_of_common_root
#print axioms Bell.Lorentz.resultant01
#print axioms Bell.Lorentz.resultant23
#print axioms Bell.Lorentz.simultaneous_coefficient_obstruction01
#print axioms Bell.Lorentz.simultaneous_coefficient_obstruction23
#print axioms Bell.Lorentz.null01_coefficient_nonzero
#print axioms Bell.Lorentz.null23_coefficient_nonzero
#print axioms Bell.Lorentz.bilinear_square_completion
#print axioms Bell.positive_sum
#print axioms Bell.positive_coordinates
#print axioms Bell.positive_trace_zero_iff
#print axioms Bell.positive_trace_positive
#print axioms Bell.positive_null_coordinates
#print axioms Bell.positive_definite_coordinates
#print axioms Bell.isOpen_futureTimelike
#print axioms Bell.eventually_positive_perturbation
#print axioms Bell.exists_positive_perturbation
#print axioms Bell.qubit_cayley_hamilton_entrywise
#print axioms Bell.determinant_complement
#print axioms Bell.rank_one_binary_projector
#print axioms Bell.future_between_null
#print axioms Bell.positive_below_rank_one
#print axioms Bell.POVM.complement_positive
#print axioms Bell.posDef_real_smul
#print axioms Bell.active_coefficients_operator
#print axioms Bell.coefficient_sum_mem_span
#print axioms Bell.effect_coordinates_mem_span
#print axioms Bell.timeUnit_mem_effectSpan
#print axioms Bell.effectSpan_finrank_of_independent
#print axioms Bell.nondeterministic_support_at_least_two
#print axioms Bell.extreme_span_intersection_le_one
#print axioms Bell.extreme_active_outcome_sum_le_five
#print axioms Bell.extreme_two_or_three_outcomes
#print axioms Bell.povm_output_positive
#print axioms Bell.singleOutput_zero
#print axioms Bell.strategy_no_inputs
#print axioms Bell.strategy_single_bob
#print axioms Bell.strategy_single_alice
#print axioms Bell.strategy_one_input
#print axioms Bell.one_input_equality
#print axioms Bell.product_behavior_mem_convexPVM
#print axioms Bell.trace_product_im_zero
#print axioms Bell.Assemblage.right_complement_positive
#print axioms Bell.Assemblage.singular_mem_convexPVM
#print axioms Bell.Assemblage.mem_convexPOVM
#print axioms Bell.qubit_cayley_hamilton
#print axioms Bell.orthogonal_idempotent_det_zero
#print axioms Bell.singular_idempotent_trace_one
#print axioms Bell.ternary_pvm_has_zero
#print axioms Bell.pvmSignObservable_matrix
#print axioms Bell.weighted_born_sum
#print axioms Bell.alice_signed_sum
#print axioms Bell.bob_signed_sum
#print axioms Bell.projective_correlation
#print axioms Bell.physical_bell_expectation
#print axioms Bell.binary_effect_complement
#print axioms Bell.auxiliary_complement_of_zero1
#print axioms Bell.auxiliary_complement_of_zero0
#print axioms Bell.auxiliary_complement_of_zero2
#print axioms Bell.physical_bell_zero1
#print axioms Bell.physical_bell_zero2
#print axioms Bell.physical_bell_zero0
#print axioms Bell.projective_strategy_rational_upper
#print axioms Bell.raw_projective_rational_upper
#print axioms Bell.sqrtTwo_rational_lower
#print axioms Bell.rational_bound_lt_paper_upper
#print axioms Bell.rational_bound_lt_witness
#print axioms Bell.projective_global_upper_bound
#print axioms Bell.convex_projective_rational_upper
#print axioms Bell.three_by_two_separation
#print axioms Bell.witness_margin_over_projective
#print axioms Bell.Lorentz.phi_zero
#print axioms Bell.Lorentz.phi_homogeneous
#print axioms Bell.Lorentz.null_homogeneous
#print axioms Bell.Lorentz.sameRay_refl
#print axioms Bell.Lorentz.sameRay_symm
#print axioms Bell.Lorentz.sameRay_trans
#print axioms Bell.Lorentz.nonzero_image_implies_nonzero
#print axioms Bell.Lorentz.sameRay_of_homogeneous_inverse
#print axioms Bell.Lorentz.image_zero_transfers
#print axioms Bell.Lorentz.image_eq_transfers
#print axioms Bell.Lorentz.phi_zero_of_last_pair_zero
#print axioms Bell.Lorentz.phi_zero_of_first_pair_zero
#print axioms Bell.Lorentz.phi_zero_of_fifth_line
#print axioms Bell.Lorentz.zero2Inverse_homogeneous
#print axioms Bell.Lorentz.zero2Coefficient_of_null
#print axioms Bell.Lorentz.zero2Inverse_identity
#print axioms Bell.Lorentz.zero2Weight_nonzero
#print axioms Bell.Lorentz.zero2_plane_of_target
#print axioms Bell.Lorentz.zero3Inverse_homogeneous
#print axioms Bell.Lorentz.zero3Coefficient_of_null
#print axioms Bell.Lorentz.zero3Inverse_identity
#print axioms Bell.Lorentz.zero3Weight_nonzero
#print axioms Bell.Lorentz.zero3_plane_of_target
#print axioms Bell.Lorentz.equal01Inverse_homogeneous
#print axioms Bell.Lorentz.equal01Coefficient_of_null
#print axioms Bell.Lorentz.equal01Inverse_identity
#print axioms Bell.Lorentz.equal01Weight_nonzero
#print axioms Bell.Lorentz.equal01_plane_of_target
#print axioms Bell.Lorentz.equal23Inverse_homogeneous
#print axioms Bell.Lorentz.equal23Coefficient_of_null
#print axioms Bell.Lorentz.equal23Inverse_identity
#print axioms Bell.Lorentz.equal23Weight_nonzero
#print axioms Bell.Lorentz.equal23_plane_of_target
#print axioms Bell.Lorentz.projective_fiber_injective
#print axioms Bell.Lorentz.projective_fiber_injective_of_sameRay
#print axioms Bell.SOS.words_hermitian
#print axioms Bell.SOS.bell02_certificate
#print axioms Bell.SOS.bell02_upper
#print axioms Bell.SOS.bell01_certificate
#print axioms Bell.SOS.bell01_upper
#print axioms Bell.SOS.chsh_switch
#print axioms Bell.localTrace_apply
#print axioms Bell.localTrace_comm
#print axioms Bell.posSemidef_real_smul
#print axioms Bell.localTrace_nonnegative
#print axioms Bell.pureDensity_positive
#print axioms Bell.pureDensity_trace
#print axioms Bell.pureDensity_born
#print axioms Bell.Assemblage.root_hermitian
#print axioms Bell.Assemblage.root_square
#print axioms Bell.Assemblage.root_invertible
#print axioms Bell.Assemblage.purified_behavior
#print axioms Bell.Assemblage.mem_rawPOVM
#print axioms Bell.inverse_congruence_trace
#print axioms Bell.rawPVM_subset_rawPOVM
#print axioms Bell.convexPVM_subset_convexPOVM
#print axioms Bell.gram_positive
#print axioms Bell.joint_gram_positive
#print axioms Bell.strategy_has_gram_data
#print axioms Bell.rawPOVM_eq_gram_image
#print axioms Bell.rawPVM_eq_gram_image
#print axioms Bell.trace_gram_norms
#print axioms Bell.entry_norm_sq_le_trace_gram
#print axioms Bell.matrixBox_isCompact
#print axioms Bell.gramBox_isCompact
#print axioms Bell.gramValid_subset_box
#print axioms Bell.gramValid_isClosed
#print axioms Bell.gramProjective_isClosed
#print axioms Bell.gramBehavior_continuous
#print axioms Bell.rawPOVM_isCompact
#print axioms Bell.rawPVM_isCompact
#print axioms Bell.convexPOVM_isCompact
#print axioms Bell.convexPVM_isCompact
#print axioms Bell.convexPVM_isClosed
#print axioms Bell.counterexample_has_extreme_maximum
#print axioms Bell.QubitGeometry.pauli_isHermitian
#print axioms Bell.QubitGeometry.coordinates_pauli
#print axioms Bell.QubitGeometry.pauli_coordinates
#print axioms Bell.QubitGeometry.minkowski_square
#print axioms Bell.QubitGeometry.minkowski_transpose
#print axioms Bell.QubitGeometry.pauli_timeUnit
#print axioms Bell.QubitGeometry.lorentzPair_eq_matrixPair
#print axioms Bell.QubitGeometry.lorentzPair_self
#print axioms Bell.QubitGeometry.pauli_trace
#print axioms Bell.QubitGeometry.pauli_det
#print axioms Bell.QubitGeometry.pauli_trace_product
#print axioms Bell.QubitGeometry.pauli_injective
#print axioms Bell.QubitGeometry.qubit_psd_iff
#print axioms Bell.QubitGeometry.pauli_posSemidef_iff
#print axioms Bell.QubitGeometry.FutureNull.posSemidef
#print axioms Bell.QubitGeometry.FutureNull.nonzero
#print axioms Bell.QubitGeometry.future_time_zero
#print axioms Bell.QubitGeometry.future_nonzero_time
#print axioms Bell.QubitGeometry.posDef_of_posSemidef_det_ne_zero
#print axioms Bell.QubitGeometry.FutureTimelike.posDef
#print axioms Bell.QubitGeometry.lorentz_pair_squares
#print axioms Bell.QubitGeometry.future_pair_nonnegative
#print axioms Bell.QubitGeometry.null_pair_zero_sameRay
#print axioms Bell.QubitGeometry.null_pair_positive_of_distinct
#print axioms Bell.QubitGeometry.timelike_pair_positive
#print axioms Bell.Lorentz.coefficient_rays_projectively_distinct
#print axioms Bell.Lorentz.transformed_rays_projectively_distinct
#print axioms Bell.Lorentz.positive_sum_not_singleton
#print axioms Bell.Lorentz.rank_one_positive_stationarity_impossible
#print axioms Bell.Lorentz.images_on_line_sameRay
#print axioms Bell.Lorentz.transformed_rank_one_obstruction
#print axioms Bell.Lorentz.circuitSign_ne_zero
#print axioms Bell.Lorentz.circuitSign_squared
#print axioms Bell.Lorentz.signed_circuit
#print axioms Bell.Lorentz.circuit_kernel_sign
#print axioms Bell.Lorentz.baseLines_ray_multiple
#print axioms Bell.Lorentz.timeFunctional_unit
#print axioms Bell.Lorentz.timeFunctional_ray_positive
#print axioms Bell.Lorentz.null_base_future_multiple
#print axioms Bell.Lorentz.ray_assignment_injective
#print axioms Bell.Lorentz.permuted_circuit_coefficients
#print axioms Bell.Lorentz.not_three_in_binary_pair
#print axioms Bell.Lorentz.circuit_scale_positive
#print axioms Bell.Lorentz.circuit_partition_and_scale
#print axioms Bell.Lorentz.binary_sum_preserved
#print axioms Bell.Lorentz.rank_zero_normalized_rigidity
#print axioms Bell.Lorentz.metricTable_eq_rankZeroTable
#print axioms Bell.Lorentz.metricTable_mem_convexPVM
#print axioms Bell.Lorentz.binaryLabelMap_injective
#print axioms Bell.Lorentz.ternaryLabelMap_injective
#print axioms Bell.Lorentz.effectRay_binary_index
#print axioms Bell.Lorentz.effectRay_ternary_index
#print axioms Bell.Lorentz.effectRay_ternary_label
#print axioms Bell.Lorentz.effectRay_under_transformation
#print axioms Bell.Lorentz.transformedMetricTable_relabel
#print axioms Bell.Lorentz.rank_zero_transformed_table_mem
#print axioms Bell.relabelProjectiveStrategy_behavior
#print axioms Bell.relabel_mem_rawPVM
#print axioms Bell.relabel_mem_convexPVM
#print axioms Bell.Lorentz.frame_future_pairing
#print axioms Bell.Lorentz.frame_timeFunctional_positive
#print axioms Bell.Lorentz.no_strict_residual_maximum
#print axioms Bell.Lorentz.coefficient_rays_distinct
#print axioms Bell.Lorentz.frame_rays_distinct
#print axioms Bell.Lorentz.metric_normal_form
#print axioms Bell.Lorentz.ResidualFrames.gram_null
#print axioms Bell.Lorentz.ResidualFrames.gram_unit
#print axioms Bell.Lorentz.ResidualFrames.gram_off_diagonal_positive
#print axioms Bell.Lorentz.ResidualFrames.parameters_gram
#print axioms Bell.Lorentz.ResidualFrames.alice_transformed
#print axioms Bell.Lorentz.ResidualFrames.gram_transformed
#print axioms Bell.Lorentz.ResidualFrames.transformed_invertible
#print axioms Bell.Lorentz.ResidualFrames.transformed_null
#print axioms Bell.Lorentz.ResidualFrames.block_normalized
#print axioms Bell.Lorentz.ResidualFrames.feasible
#print axioms Bell.Lorentz.ResidualFrames.frame_positive
#print axioms Bell.Lorentz.ResidualFrames.not_strict_maximum
#print axioms Bell.effectSpan_le_of_effects
#print axioms Bell.effectSpan_coarsen_le
#print axioms Bell.effectSpan_encode
#print axioms Bell.measurementFrame_effectRay
#print axioms Bell.measurementFrame_ray
#print axioms Bell.measurementFrame_unit
#print axioms Bell.matrix_det_unit_of_surjective
#print axioms Bell.matrix_det_unit_of_injective
#print axioms Bell.measurementFrame_range
#print axioms Bell.paddingMap_behavior
#print axioms Bell.encoded_frame_invertible
#print axioms Bell.steered_hermitian
#print axioms Bell.steeringTransform_injective
#print axioms Bell.steeredFrame_effectRay
#print axioms Bell.steeredFrame_invertible
#print axioms Bell.encodePOVM_below_nonzero
#print axioms Bell.encodePOVM_null
#print axioms Bell.steeredFrame_unit
#print axioms Bell.steeredFrame_ray
#print axioms Bell.steering_nonzero
#print axioms Bell.localTrace_coordinates
#print axioms Bell.pure_frame_behavior
#print axioms Bell.physicalResidualFrames_behavior
#print axioms Bell.no_strict_extreme_binary_ternary
#print axioms Bell.SOS.rotate_three_sums
#print axioms Bell.SOS.gram_ldl
#print axioms Bell.SOS.expectation_gram_nonnegative
#print axioms Bell.SOS.upper_bound_of_gram
#print axioms Bell.SOS.pivot_positive
#print axioms Bell.SOS.coefficient_factorization
#print axioms Bell.SOS.numerator_symmetric
#print axioms Bell.sqrtTwo_sq
#print axioms Bell.sqrtTwo_pos
#print axioms Bell.sqrtTwo_lt_two
#print axioms Bell.gap_identity
#print axioms Bell.strict_gap
#print axioms Bell.le_of_square_le
#print axioms Bell.sqrt_deficit_one_identity
#print axioms Bell.sqrt_deficit_four_identity
#print axioms Bell.sqrt_deficit_one
#print axioms Bell.sqrt_deficit_four
#print axioms Bell.robust_square_identity
#print axioms Bell.robust_certificate_nonnegative
#print axioms Bell.robust_pair_bound
#print axioms Bell.complete_square
#print axioms Bell.global_upper_from_deficits
#print axioms Bell.strengthened_gt_lower
#print axioms Bell.strengthened_gt_upper
#print axioms Bell.strengthened_family_bound
#print axioms Bell.two_input_strategy_simulable
#print axioms Bell.finite_projective_simulation
#print axioms Bell.one_binary_party_simulation
#print axioms Bell.two_input_linear_bound_transfer
#print axioms Bell.two_input_linear_bound_iff
#print axioms Bell.POVM.ext_effect
#print axioms Bell.coarsenPOVM_comp
#print axioms Bell.coarsenPOVM_id
#print axioms Bell.coarsenPOVM_const
#print axioms Bell.activeSupport_nonempty
#print axioms Bell.encodingLabel_cast
#print axioms Bell.encodePOVM_cast
#print axioms Bell.encodePOVM_above
#print axioms Bell.encoding_coarsens
#print axioms Bell.encodePOVM_effect_cases
#print axioms Bell.deterministic_alice_local
#print axioms Bell.deterministic_bob_local
#print axioms Bell.gram_rows_density
#print axioms Bell.State.amplitudes_density
#print axioms Bell.State.steer_positive
#print axioms Bell.State.steer_sum
#print axioms Bell.State.reduced_positive
#print axioms Bell.State.reduced_normalized
#print axioms Bell.State.born_steer
#print axioms Bell.Strategy.toAssemblage_behavior
#print axioms Bell.full_pure_of_not_mem_convexPVM
#print axioms Bell.full_pure_marginal_positive
#print axioms Bell.StrategyMap.strategy_behavior
#print axioms Bell.StrategyMap.mem_rawPOVM
#print axioms Bell.StrategyMap.mem_rawPVM
#print axioms Bell.StrategyMap.mem_convexPVM
#print axioms Bell.swap_born
#print axioms Bell.swapStrategy_behavior
#print axioms Bell.swap_mem_convexPVM
#print axioms Bell.swap_mem_convexPOVM
#print axioms Bell.swap_extreme
#print axioms Bell.FullPureStrategy.swap_behavior
#print axioms Bell.Strengthened.q_sq
#print axioms Bell.Strengthened.q_pos
#print axioms Bell.Strengthened.q_gt_one
#print axioms Bell.Strengthened.a_pos
#print axioms Bell.Strengthened.b_pos
#print axioms Bell.Strengthened.a_sq
#print axioms Bell.Strengthened.b_sq
#print axioms Bell.Strengthened.scaled_a_sq
#print axioms Bell.Strengthened.scaled_b_sq
#print axioms Bell.Strengthened.state_norm
#print axioms Bell.Strengthened.k_a
#print axioms Bell.Strengthened.k_sq_lt_one
#print axioms Bell.Strengthened.q_product_sq
#print axioms Bell.Strengthened.observable_norm
#print axioms Bell.Strengthened.auxiliary_positive
#print axioms Bell.Strengthened.alice_positive
#print axioms Bell.Strengthened.alice_normalized
#print axioms Bell.Strengthened.bob_positive
#print axioms Bell.Strengthened.bob_normalized
#print axioms Bell.Strengthened.coefficient_normalized
#print axioms Bell.Strengthened.parameter_score
#print axioms Bell.Strengthened.auxiliary_value
#print axioms Bell.Strengthened.locking_value
#print axioms Bell.Strengthened.value
#print axioms Bell.strengthened_attainment
#print axioms Bell.main_claims_with_strengthening
#print axioms Bell.bellScore_add
#print axioms Bell.bellScore_smul
#print axioms Bell.convex_projective_bound_of_raw
#print axioms Bell.three_by_two_separation_of_projective_upper_bound
#print axioms Bell.no_strict_separation_of_equal_hulls
#print axioms Bell.minimum_inputs_of_equality_theorems
#print axioms Bell.main_claims_of_missing_theorems
#print axioms Bell.Transport.three_intervals
#print axioms Bell.Transport.exists_capacity_transport
#print axioms Bell.Transport.capacity_representation
#print axioms Bell.Transport.exists_transport
#print axioms Bell.Transport.Certificate.complement_nonnegative
#print axioms Bell.Transport.Certificate.diagonal_zero
#print axioms Bell.Transport.Certificate.complement_row
#print axioms Bell.Transport.Certificate.complement_column
#print axioms Bell.Transport.Certificate.mass_first
#print axioms Bell.Transport.Certificate.mass_second
#print axioms Bell.Transport.Certificate.total_branch_mass
#print axioms Bell.Transport.Certificate.ternary_block
#print axioms Bell.Transport.Certificate.mixed_blocks
#print axioms Bell.Lorentz.dot_ray_basis
#print axioms Bell.Lorentz.positive_weighted_ray_squares
#print axioms Bell.Lorentz.secondForm_rankOne
#print axioms Bell.Lorentz.nonzero_kernel_of_three_constraints
#print axioms Bell.Lorentz.compatibility_rankOne
#print axioms Bell.Lorentz.uphill_of_three_compatibilities
#print axioms Bell.Lorentz.compatibility_sum
#print axioms Bell.Lorentz.compatibility_add_identity
#print axioms Bell.Lorentz.secondForm_add_identity
#print axioms Bell.Lorentz.normalized_uphill_of_three_compatibilities
#print axioms Bell.polarEffect_hermitian
#print axioms Bell.polarEffect_idempotent
#print axioms Bell.polarEffect_positive
#print axioms Bell.polarEffect_complement
#print axioms Bell.halfRoot_sq
#print axioms Bell.aux0_gram
#print axioms Bell.aux1_gram
#print axioms Bell.aux2_gram
#print axioms Bell.aux0_positive
#print axioms Bell.aux1_positive
#print axioms Bell.aux2_positive
#print axioms Bell.auxiliary_normalized
#print axioms Bell.auxiliary_not_projective
#print axioms Bell.phi_gram
#print axioms Bell.phi_positive
#print axioms Bell.phi_normalized
#print axioms Bell.phi_trace_tensor
#print axioms Bell.alice_positive
#print axioms Bell.bob_positive
#print axioms Bell.alice_normalized
#print axioms Bell.bob_normalized
#print axioms Bell.witness_mem_raw
#print axioms Bell.witness_mem_convex
#print axioms Bell.witness_auxiliary_probabilities
#print axioms Bell.witness_correlations
#print axioms Bell.witness_value
#print axioms Bell.physical_povm_value_above_numeric_upper
