"""Read-only complete submitted PR301 snapshot; original claims remain hypotheses."""
from pathlib import Path
from datetime import datetime,timezone
import base64,gzip,hashlib,json,os,stat,subprocess,sys
R=Path('/Users/alec/Documents/Math');A=Path(__file__).parent;P=A.parent.parent;HEAD='125d90fa3f5a4f90b813fec7a7c0f1918914d885';PREFIX='problems/30004365_gentle_derived_invariant/';sha=lambda b:hashlib.sha256(b).hexdigest();utc=lambda:datetime.now(timezone.utc).isoformat();load=lambda p:json.loads(Path(p).read_bytes())
def need(v,m):
 if not v:raise RuntimeError(m)
def pin(p):
 p=Path(p);need(p.is_file() and not p.is_symlink(),'literal complete file');b=p.read_bytes();return dict(path=str(p),bytes=len(b),sha256=sha(b),mode=stat.S_IMODE(p.stat().st_mode))
COUNT=0
def api(label,endpoint):
 global COUNT
 COUNT+=1;d=A/'snapshot_actual_api'/f'{COUNT:03d}_{label}';d.mkdir(parents=True,exist_ok=False);argv=['/opt/homebrew/bin/gh','api',endpoint];q=dict(argv=argv,cwd=str(R),requested_UTC=utc(),source=pin(__file__),read_only=True,automatic_retry=False);(d/'request.json').write_text(json.dumps(q,indent=2)+'\n');(d/'source.gz').write_bytes(gzip.compress(Path(__file__).read_bytes(),mtime=0));proc=subprocess.Popen(argv,cwd=R,stdin=subprocess.DEVNULL,stdout=subprocess.PIPE,stderr=subprocess.PIPE,start_new_session=True);start=dict(**q,actual_PID=proc.pid,start_UTC=utc());(d/'started.json').write_text(json.dumps(start,indent=2)+'\n');out,err=proc.communicate(timeout=55);streams={}
 for n,b in [('stdout',out),('stderr',err)]:
  p=d/(n+'.gz');p.write_bytes(gzip.compress(b,mtime=0));streams[n]=dict(stored=pin(p),logical_bytes=len(b),logical_sha256=sha(b))
 (d/'execution.json').write_text(json.dumps(dict(**start,end_UTC=utc(),exit_code=proc.returncode,parent_reaped=True,streams=streams),indent=2)+'\n');need(proc.returncode==0 and not err,'actual full read-only API result');return json.loads(out)
def main():
 need(not sys.flags.optimize,'no optimization');need(not (A/'snapshot_manifest.json').exists(),'snapshot already exists');intake=load(P/'status_filter_after_pr302_20261005_v02/RESULT.json');e=intake['next_eligible'];need(e['PR']==301 and e['original_head']==e['current_head']==HEAD and e['original_status']=='claimed_solved','exact submitted eligibility')
 log=A/'RESEARCH_LOG.md';need(not log.exists(),'new dedicated effort');log.write_text(f'{utc()} — Begin independent PR301 audit of original claimed_solved1/5 head {HEAD}. Target is Plamondon Problem3.4, claimed explicit terminating theoretical algorithm for gentle-algebra derived invariants; universal correctness, totality and source scope are hypotheses awaiting independent proof reconstruction. No efficiency/full-software/priority/human-review claim accepted. Mathematics0%,priority0%,workflow5%. Only read-only snapshot; no Git/shared-control/service mutation.\n')
 pr=api('metadata','repos/AlecKriebel/Math/pulls/301');need(pr['state']=='open' and pr['draft'] and pr['head']['sha']==HEAD and pr['changed_files']==18,'fresh original open18-file draft');files=api('changed_files','repos/AlecKriebel/Math/pulls/301/files?per_page=100');need(len(files)==18 and {x['status'] for x in files}=={'added','modified'},'complete original changed-file domain');tree=api('tree',f'repos/AlecKriebel/Math/git/trees/{HEAD}?recursive=1');need(not tree['truncated'] and tree['sha']==HEAD,'complete original Git tree');entries={x['path']:x for x in tree['tree']};targetpaths={x for x in entries if x.startswith(PREFIX) and entries[x]['type']=='blob'};changed={x['filename'] for x in files};need(len(targetpaths)==17 and changed==targetpaths|{'unsolved_math_prioritization/QUEUE.md'},'exact17 proof artifacts and sole QUEUE change')
 snapshot=A/'snapshot';snapshot.mkdir(exist_ok=False);rows=[]
 for i,rel in enumerate(sorted(changed)):
  t=entries[rel];need(t['type']=='blob' and t['mode']=='100644','regular original Git blob');response=api(f'blob{i:02d}',f'repos/AlecKriebel/Math/git/blobs/{t["sha"]}');need(response['encoding']=='base64' and response['sha']==t['sha'],'full native blob API');b=base64.b64decode(response['content']);blob=hashlib.sha1(b'blob '+str(len(b)).encode()+b'\0'+b).hexdigest();need(len(b)==response['size']==t['size'] and blob==t['sha'],'whole original byte/Git identity');need(next(x for x in files if x['filename']==rel)['sha']==blob,'PR changed-file blob agrees');p=snapshot/rel;p.parent.mkdir(parents=True,exist_ok=True);p.write_bytes(b);p.chmod(0o444);rows.append(dict(path=rel,bytes=len(b),sha256=sha(b),git_blob_sha=blob,git_mode=t['mode'],snapshot=pin(p)))
 q=(snapshot/'unsolved_math_prioritization/QUEUE.md').read_bytes();lines=[x for x in q.splitlines() if x.startswith(b'|') and len(x.split(b'|'))==14 and x.split(b'|')[2].strip().split(b'/')[0].strip()==b'30004365'];need(len(lines)==1 and lines[0].split(b'|')[8].strip()==b'claimed_solved' and lines[0].split(b'|')[9].strip()==b'1/5','actual original claimed1/5 row')
 final=api('final_metadata','repos/AlecKriebel/Math/pulls/301');need(final['head']['sha']==HEAD and final['state']=='open' and final['draft'],'head stable through full snapshot');manifest=dict(status='PASS_COMPLETE_ORIGINAL_PR301_READ_ONLY_SNAPSHOT',UTC=utc(),actual_recorder_PID=os.getpid(),source=pin(__file__),PR=301,head=HEAD,original_submitted_status='claimed_solved',original_author_budget='1/5',target_problem_id='30004365',original_queue_row=lines[0].decode(),files=rows,original_artifact_count=17,complete_changed_file_count=18,actual_read_only_API_captures=COUNT,all_original_full_bodies_modes_blobs_verified=True,no_write_authority=True,estimates_percent=dict(mathematical_review=0,priority=0,workflow=5));out=A/'snapshot_manifest.json';out.write_text(json.dumps(manifest,indent=2)+'\n');out.chmod(0o444);log.write_text(log.read_text()+f'{utc()} — Complete unchanged18-file snapshot authenticated against whole original Git tree and PR changed-file/API blobs; original17 artifacts and sole claimed_solved1/5 QUEUE row preserved. All {COUNT} actual read-only API captures retain full source/request/PID/time/streams. Mathematics0%,priority0%,workflow5%; start independent materially distinct mathematical review families.\n');print(json.dumps(dict(status=manifest['status'],manifest=pin(out),API_captures=COUNT,artifact_count=17),indent=2))
if __name__=='__main__':main()
