#!/usr/bin/env python3
"""Transparent static inventory helpers. These are not a Lean parser or proof checker."""
from __future__ import annotations
import hashlib,json,re
from pathlib import Path

class AuditError(RuntimeError): pass

FORBIDDEN=[r'\bsorry\b',r'\badmit\b',r'\bsorryAx\b',r'^\s*axiom\s',
           r'\bnative_decide\b',r'decide\s*\+native',r'\bofReduceBool\b',
           r'\btrustCompiler\b',r'skipKernelTC',r'implemented_by',r'^\s*unsafe\s']

def strip_comments(text:str)->str:
    # Preserve line numbers, nested block comments, and strings. Strings remain
    # visible to the conservative forbidden-pattern scan; this cannot certify syntax.
    out=[];i=0;depth=0;quoted=False
    while i<len(text):
        if depth:
            if text.startswith('/-',i): depth+=1;out.extend('  ');i+=2
            elif text.startswith('-/',i):depth-=1;out.extend('  ');i+=2
            else:out.append('\n' if text[i]=='\n' else ' ');i+=1
        elif quoted:
            out.append(text[i])
            if text[i]=='\\' and i+1<len(text):out.append(text[i+1]);i+=2
            else:
                if text[i]=='"':quoted=False
                i+=1
        elif text.startswith('/-',i):depth=1;out.extend('  ');i+=2
        elif text.startswith('--',i):
            j=text.find('\n',i)
            if j<0:j=len(text)
            out.extend(' '*(j-i));i=j
        else:
            if text[i]=='"':quoted=True
            out.append(text[i]);i+=1
    if depth: raise AuditError('unclosed block comment')
    if quoted: raise AuditError('unclosed string')
    return ''.join(out)

def scan_text(text:str):
    source=strip_comments(text)
    for pattern in FORBIDDEN:
        if re.search(pattern,source,re.M):raise AuditError('forbidden source pattern: '+pattern)
    return source

def module_name(root:Path,p:Path)->str:
    return '.'.join(p.relative_to(root).with_suffix('').parts)

def source_files(root:Path):
    return sorted((root/'Kourovka').rglob('*.lean'))+[root/'Kourovka.lean']

def inventory(root:Path):
    files=source_files(root); graph={};decls=[];anonymous=[];private=[];external=set();hashes={}
    # Deliberately only recognizes ordinary named commands used by this package.
    declaration=re.compile(r'^(?P<mods>(?:(?:noncomputable|private|protected|local)\s+)*)'
       r'(?P<kind>theorem|lemma|def|abbrev|instance|structure|inductive|class)\b\s*'
       r'(?P<name>[A-Za-z_][\w\'.]*)?')
    for p in files:
        rel=p.relative_to(root).as_posix();text=p.read_text();source=scan_text(text)
        hashes[rel]=hashlib.sha256(p.read_bytes()).hexdigest();mod=module_name(root,p)
        imports=[];stack=[]
        for no,line in enumerate(source.splitlines(),1):
            s=line.strip()
            if not s:continue
            if s.startswith('import '):
                for name in s[7:].split():
                    if name=='Kourovka' or name.startswith('Kourovka.'):imports.append(name)
                    else:external.add(name)
                continue
            if s.startswith('namespace '):stack.append(('namespace',s.split()[1]));continue
            if s=='section' or s.startswith('section '):stack.append(('section',s[7:].strip()));continue
            if s=='end' or s.startswith('end '):
                if not stack:raise AuditError(f'unmatched end at {rel}:{no}')
                kind,label=stack.pop();arg=s[3:].strip()
                if arg and label!=arg:raise AuditError(f'end mismatch at {rel}:{no}: {label!r} / {arg!r}')
                continue
            s=re.sub(r'^(?:@\[[^]]+\]\s*)+','',s)
            match=declaration.match(s)
            if not match:continue
            kind=match['kind'];name=match['name'];mods=match['mods'].split()
            entry={'module':mod,'path':rel,'line':no,'kind':kind,'source_status':'not_determined_by_static_inventory'}
            if not name:
                if kind=='instance':anonymous.append(entry);continue
                raise AuditError(f'unnamed {kind} at {rel}:{no}')
            # Commands generated by Lean (constructors, recursors, anonymous instance
            # names) are NOT guessed. Their acceptance follows from the actual build;
            # transitive axiom queries below cover dependencies of the named roots.
            ns='.'.join(a for k,a in stack if k=='namespace')
            if name.startswith('_root_.'):full=name[7:]
            else:full='.'.join(filter(None,[ns,name]))
            entry['name']=full
            if 'private' in mods or 'local' in mods:private.append(entry)
            else:decls.append(entry)
        if stack:raise AuditError(f'unclosed namespace/section in {rel}: {stack}')
        graph[mod]=sorted(set(imports))
    for mod,imports in graph.items():
        for dep in imports:
            if dep not in graph:raise AuditError(f'{mod} imports missing local module {dep}')
    done=set();active=set();ordered=[]
    def visit(mod):
        if mod in active:raise AuditError('import cycle at '+mod)
        if mod in done:return
        active.add(mod)
        for dep in graph[mod]:visit(dep)
        active.remove(mod);done.add(mod);ordered.append(mod)
    visit('Kourovka')
    orphan=set(graph)-done
    if orphan:raise AuditError('source modules omitted from root import closure: '+', '.join(sorted(orphan)))
    names=[x['name'] for x in decls]
    if len(names)!=len(set(names)):
        duplicates=sorted({n for n in names if names.count(n)>1})
        raise AuditError('duplicate named declarations: '+', '.join(duplicates))
    return {'format':'source-inventory-not-an-elaborated-environment-v3',
       'lean_compiled':None,'compilation_status':'not_determined_by_static_inventory','all_source_modules_in_root_import_closure':True,
       'source_hashes':hashes,'imports':graph,'topological_order':ordered,
       'external_imports':sorted(external),'named_declarations':decls,
       'private_or_local_named_declarations':private,'anonymous_instances':anonymous,
       'notes':['Static command inventory is not an elaborated declaration inventory.',
         'Compilation status is not determined here; consult actual build and query records.',
         'Private/local names and anonymous/generated declarations are not guessed in external queries.',
         'Named roots are audited transitively after compilation; all source modules are built.',
         'A positive static result is not a proof, and final group certification is unavailable.']}

def closure(inv:dict,mod:str)->set[str]:
    if mod not in inv['imports']:raise AuditError('unknown requested module '+mod)
    seen=set()
    def walk(m):
        if m in seen:return
        seen.add(m)
        for d in inv['imports'][m]:walk(d)
    walk(mod);return seen

def write_inventory(root:Path):
    inv=inventory(root)
    (root/'reference/source_inventory.json').write_text(json.dumps(inv,indent=2)+'\n')
    write_queries(root/'validation','Kourovka',[d['name'] for d in inv['named_declarations']])
    return inv

def write_queries(dest:Path,mod:str,names:list[str]):
    dest.mkdir(parents=True,exist_ok=True)
    (dest/'AxiomAudit.lean').write_text('/- Generated inspection commands; not a proof. -/\nimport '+mod+'\n\n'+
      '\n'.join('#print axioms '+n for n in names)+'\n')
    (dest/'Statements.lean').write_text('/- Generated type-inspection commands; not a proof. -/\nimport '+mod+
      '\nset_option pp.all true\n\n'+'\n'.join('#check @'+n for n in names)+'\n')

def parse_axioms(text:str,names:list[str]):
    pattern=re.compile(r"'([^']+)' (?:does not depend on any axioms|depends on axioms:\s*\[([^]]*)\])",re.S)
    out={}
    for m in pattern.finditer(text):
        name=m[1]
        if name in out:raise AuditError('duplicate actual axiom report '+name)
        deps=[a.strip() for a in (m[2] or '').split(',') if a.strip()]
        unexpected=set(deps)-{'propext','Classical.choice','Quot.sound'}
        if unexpected:raise AuditError(f'{name}: unexpected actual axioms {sorted(unexpected)}')
        out[name]=deps
    if set(out)!=set(names):
        raise AuditError(f'axiom-report names mismatch: missing {sorted(set(names)-set(out))[:12]}, '
                         f'unexpected {sorted(set(out)-set(names))[:12]}')
    return out
