"""Write only this audit's first-party artifacts and custody metadata."""
from pathlib import Path
import json, hashlib, datetime, os

B=Path(__file__).resolve().parent
A=B.parent
now=datetime.datetime.now(datetime.timezone.utc).isoformat()
def save(name,obj):
    (B/name).write_text(json.dumps(obj,indent=2,ensure_ascii=False)+'\n')
def digest(path):
    data=path.read_bytes()
    return {'bytes':len(data),'sha256':hashlib.sha256(data).hexdigest()}
cli=[json.loads(x) for x in (B/'CLI_LEDGER.jsonl').read_text().splitlines()]
bylabel={x['label']:x for x in cli}
sources=[
 {'id':'S0','authors':'Volker Kaibel','title':'Open Problem: Arborescences and NP-hardness','publication':'Oberwolfach Report 50/2018, printed 3014–3015','url':'https://ems.press/content/serial-article-files/46772?nt=1','primary_kind':'original workshop contribution','read_scope':'Full contribution, both Problem1 and Problem2 plus both motivations; PDF pages46–47. Read FIRST, before candidate proof.','retrieval_label':'kaibel_full_contribution','parent_pdf':'../primary_sources_20261006/owr.pdf','model':'Problem1 is one common undirected spanning tree, every vertex root, complete root-specific single-arc vectors, whole-arborescence sums. Problem2 differs.','status':'full relevant original read'},
 {'id':'S1','authors':'D.S. Johnson, J.K. Lenstra, A.H.G. Rinnooy Kan','title':'The complexity of the network design problem','publication':'Mathematisch Centrum BW70/77, cover FEBRUARI1977; journal Networks8(4),1978,279–285','doi':'10.1002/net.3230080402','url':'https://ir.cwi.nl/pub/9700/9700D.pdf','publisher_url':'https://onlinelibrary.wiley.com/doi/10.1002/net.3230080402','primary_kind':'institutional archived author preprint; official journal metadata','read_scope':'FULL preprint, cover, definitions, Theorem1 knapsack proof, Theorem2 exact3cover proof, all body pages1–5 and references.','retrieval_label':'jlrk1977_cwi','extract_label':'jlrk1977_full','model':'Unit-length graph, tree budget, sum of unordered pair distances. Threshold-forced core is fixed; element attachments are leaves.','status':'full relevant proof read; two empty archive downloads recovered through CWI'},
 {'id':'S2','authors':'T.C. Hu','title':'Optimum communication spanning trees','publication':'SIAM Journal on Computing3(3),September1974,188–195','doi':'10.1137/0203015','url':'https://epubs.siam.org/doi/10.1137/0203015','primary_kind':'official publisher metadata only','read_scope':'Publisher definition/metadata; full PDF retrieval failed. No Hu proof checked.','retrieval_label':'hu1974','model':'Communication requirements multiplied by pair-path lengths; original special-case proofs remain an access gap.','status':'FULL-PROOF ACCESS GAP: curl exit56, zero stdout bytes'},
 {'id':'S3','authors':'Christian Tilk, Stefan Irnich','title':'Combined Column-and-Row-Generation for the Optimal Communication Spanning Tree Problem','publication':'Technical Report LM-2016-03,April12,2016','url':'https://download.uni-mainz.de/RePEc/pdf/Discussion_Paper_1613.pdf','primary_kind':'institutional author technical report','read_scope':'Full paper read; relevant complete definitions, §3.1–3.2 all-root models and §4.3.2 pricing model especially rechecked.','retrieval_label':'ocst2016','extract_label':'ocst2016_full','model':'One shared tree and all-origin orientations, but objective is on flow amount f, not orientation support y.','status':'full relevant models read; no exact target transfer'},
 {'id':'S4','authors':'Eduardo Alvarez-Miranda, Ivana Ljubic, Markus Luipersbeck, Markus Sinnl','title':'Solving Minimum-Cost Shared Arborescence Problems','publication':'Author preprint February14,2016; European Journal of Operational Research2017','doi':'10.1016/j.ejor.2016.11.004','url':'https://msinnl.github.io/pdfs/MKLSTP-main.pdf','primary_kind':'author-hosted preprint','read_scope':'Complete relevant §§1–2.2, Figure1, formulations1–11/SCF, §3 directed-cut model and §3.1 subproblem models. Computational rest not read in full.','retrieval_label':'shared2016','extract_label':'shared2016_full','lead_provenance':'Parent source lead delivered AFTER independent freeze; not counted as independent discovery.','model':'Generic topology-family MCSN versus specialized common-root Steiner shared arborescences; shared directed network can have2cycles/multiple incoming arcs.','status':'full relevant models read; broad containment is not subclass hardness'},
 {'id':'S5','authors':'Carlos Zetina, Ivan Contreras, Elena Fernandez, Carles Luna-Mota','title':'Solving the Optimum Communication Spanning Tree Problem','publication':'CIRRELT-2017-72,December2017','url':'https://www.cirrelt.ca/documentstravail/cirrelt-2017-72.pdf','primary_kind':'institutional author technical report','read_scope':'Complete §§1–2 definitions and arc formulation1–7, printed1–4; start§3. Later computational sections not read in full. No new hardness proof in read portion.','retrieval_label':'ocst2017','extract_label':'ocst2017_full','model':'Common undirected spanning tree with pair-demand/path objective.','status':'full relevant model read'},
 {'id':'S6','authors':'Alexander Medvedovsky, Vineet Bafna, Uri Zwick, Roded Sharan','title':'An Algorithm for Orienting Graphs Based on Cause-Effect Pairs and Its Applications to Orienting Protein Networks','publication':'2008 author-hosted paper','url':'https://www.cs.tau.ac.il/~roded/orient.pdf','primary_kind':'author-hosted primary paper','read_scope':'Definitions and complete Theorem1 MaxDiCut→star proof and Theorem2 Max2SAT→binary-tree proof; algorithm sections scanned, not claimed complete-paper read.','retrieval_label':'orientation2008','extract_label':'orientation2008_full','model':'Input is a fixed tree; freely choose an orientation to maximize satisfied ordered-pair reachability.','status':'full relevant hardness proofs read'},
 {'id':'S7','authors':'Didem Gozupek, Mordechai Shalom, Ariella Voloshin, Shmuel Zaks','title':'On the complexity of constructing minimum changeover cost arborescences','publication':'Theoretical Computer Science540–541(2014),40–52','doi':'10.1016/j.tcs.2014.03.023','url':'https://bilmuh.gtu.edu.tr/~dgozupek/Gozupek_TCS14.pdf','primary_kind':'author-hosted publisher PDF','read_scope':'Complete relevant §2 definitions and ALL §§3–4 hardness proofs, Claim1 and Theorems1–4; part§5 positive results. Earlier SEA2011 conference version not retrieved; related revised2013 primary preprint independently retrieved and checked as S9.','retrieval_label':'mincca2014','extract_label':'mincca2014_full','model':'One fixed root; tree cost depends on the color pair of each edge and its chosen predecessor edge.','status':'full relevant hardness proofs read'},
 {'id':'S8','authors':'Kristof Berczi, Tamas Kiraly, Yutaro Yamaguchi, Yu Yokoi','title':'Rainbow Arborescence Conjecture','publication':'arXiv2412.15457,first posted December19,2024; retrieved v2 December9,2025','url':'https://arxiv.org/abs/2412.15457','pdf_url':'https://arxiv.org/pdf/2412.15457','primary_kind':'author arXiv preprint','read_scope':'Full §1 definitions/related work; complete §2 Theorem2.1 3DM reduction, printed3–4; complete §4.4 Theorem4.8 common-underlying-tree induction, printed9. Long cycle proof§5 not read.','retrieval_label':'rainbow2024','extract_label':'rainbow2024_full','model':'One output rooted rainbow arborescence; exactly one arc from each input color-arborescence, possibly parallel arcs.','status':'full relevant hardness and common-tree proofs read'},
 {'id':'S9','authors':'Giulia Galbiati, Stefano Gualandi, Emiliano Traversi, Frank Baumann','title':'Complexity and Exact Solution Approaches to the Minimum Changeover Cost Arborescence Problem','publication':'Retrieved author preprint August10,2013; repository posted September16,2011 and updated September23,2013','url':'https://optimization-online.org/wp-content/uploads/2011/09/3166.pdf','repository_url':'https://optimization-online.org/2011/09/3166/','conference_antecedent':{'authors':'Giulia Galbiati, Stefano Gualandi, Francesco Maffioli','title':'On Minimum Changeover Cost Arborescences','publication':'SEA2011,LNCS6630,112–123','doi':'10.1007/978-3-642-20662-7_10','publisher_url':'https://link.springer.com/chapter/10.1007/978-3-642-20662-7_10','read_scope':'Publisher metadata/abstract only; subscription full proof not retrieved. Do not date all revised2013 theorems to2011.'},'primary_kind':'author-posted optimization repository preprint','read_scope':'Complete §§1–2 including both full reductions and proofs (Minimum Ones, Set Cover), §3.1 lower-bound comparison, and §4 complete BQP model2–5. Later computational sections not read in full.','retrieval_label':'mincca2013','extract_label':'mincca2013_full','model':'One fixed-root directed arborescence with quadratic adjacent chosen-arc/color costs; the paper explicitly uses minimum single-arc-cost arborescence only as a lower-bound problem.','status':'full relevant revised proofs/model read; original2011 proof version remains a narrower chronology/access gap'},
]
for s in sources:
    for key in ['retrieval_label','extract_label']:
        if key in s:
            c=bylabel[s[key]]
            s[key+'_receipt']={k:c[k] for k in ['UTC_started','UTC_finished','operator_PID','child_PID','exit_code','stdout_bytes','stdout_sha256']}
save('SOURCES_AND_READ_SCOPE.json',{'UTC':now,'sources':sources,'third_party_custody':'PDFs, extracted text, web response snapshots, stderr and challenge HTML are private. Public records contain metadata and first-party comparative evidence only.','read_scope_rule':'A full extracted text file is not a claim that every page was read; per-source read_scope states the actual scope.'})

queries=[
 ['"spanning tree" "root dependent" NP hard costs','"optimal requirement spanning tree" NP-complete','"routing cost" spanning tree "nonuniform" NP hard','"compatible branchings" NP hard spanning tree'],
 ['"Johnson" "Lenstra" "Rinnooy" "spanning trees" 1978','"Optimal communication spanning trees" "Hu" pdf','"minimum routing cost" "Johnson" 1978 pdf','"root-dependent" "spanning" Kaibel'],
 ['"The complexity of the network design problem" "pdf" -site:researchgate.net','"Optimum communication spanning trees" "Hu" "doi"','"spanning tree" "orientation" "cost" "NP-hard" -routing -steiner -euclidean','"spanning tree" "root-dependent costs"'],
 ['site:ir.cwi.nl "complexity" "network design" Johnson Lenstra','site:repub.eur.nl "complexity of the network design"','"root-dependent" tree costs NP hardness Kaibel','"arborescences and NP-hardness" Kaibel'],
 ['"common arborescence" "NP" tree','"spanning tree" "different roots" "NP-hard" cost','"minimum" "arborescences" "common" "Hamiltonian"','"spanning tree" "two roots" "cost" "hard"'],
 ['"arborescence" "Hamiltonian path" "compatible"','"spanning tree" "two roots" "Hamiltonian"','"simultaneous" "arborescences" NP-hard','"minimum" "common spanning tree" "directed"'],
 ['"spanning tree" "orientation costs" roots','"spanning tree" "arborescences" "compatible" cost','"tree" "root-specific" "cost" optimization','"spanning tree" "root-dependent" -pet -coverage'],
 ['"arborescences" "same underlying tree"','"arborescences" "common undirected" cost','"spanning tree" "cost vector" "each" "root"','"minimizes" "arborescences" "sum" "roots" costs'],
 ['"0203015" pdf Hu','"Optimum Communication Spanning Trees" filetype:pdf -site:researchgate.net -site:scispace.com','"tree orientation" "NP-complete" spanning','"minimum cost" "compatible" "branchings"'],
 ['"On the complexity of constructing minimum changeover cost arborescences" pdf','"compatible branchings" optimization trees','"spanning tree" "colored" "Hamiltonian" "root" cost','"root dependent spanning" NP hardness'],
 ['"Gozupek" "Shalom" "Voloshin" "Zaks" "2014" pdf','"On the complexity of constructing minimum" "pdf" -site:researchgate.net -site:scispace.com','"rainbow arborescence" "NP-complete" reduction','"directed Hamiltonian" "two" "arborescences" "spanning tree"'],
 ['"minimum spanning tree" "multiple roots" "cost" NP-hard','"common" "rooted spanning trees" costs','"arborescences" "same tree" "cost"','"spanning" "root-dependent" "Kaibel"'],
 ['"optimum communication spanning trees" site:math.ucsd.edu','"optimum communication spanning trees" site:cs.wisc.edu','"optimum requirement" "spanning trees" "root" cost','"spanning-tree" "arborescence" "orientation" "Hamiltonian path" costs'],
 ['"arborescences" "cost" "Kaibel" NP-hard -site:researchgate.net','"spanning tree" "root-dependent" hardness "Martin"','"minimum-cost" "rooted orientations" tree','"tree" "all roots" "cost vectors" optimization'],
 ['"Reducing" "constraint" "Martin" "1991" "spanning tree" pdf','"root-dependent" "tree" "cost" NP-hardness','"optimal requirement spanning tree" "NP-hard" reduction','"minimum cost" "compatible branchings"'],
 ['"On minimum changeover cost arborescences" pdf Galbiati Gualandi Maffioli','site:mat.unipv.it "changeover" arborescences','site:unipv.it "changeover" Galbiati','"On minimum changeover cost arborescences" "doi"'],
]
search={'UTC_assembled':now,'query_date_UTC':'2026-10-06','time_precision':'Date and ordered batch; web tool does not expose a CLI PID. Do not infer exact query timestamps from later file custody times. Initial freeze UTC binds batches1–2 before freeze; source CLI receipts provide exact retrieval times.','batches':[{'sequence':i+1,'queries':q,'before_independent_freeze':i<2} for i,q in enumerate(queries)],'primary_evidence_source_ids':['S0','S1','S2','S3','S4','S5','S6','S7','S8','S9'],'parent_lead_after_freeze':'S4 only; original author notes inspected after freeze, yielded no additional primary source receipts.','raw_snapshot_retention':[],'coverage_gaps':['Hu1974 full proof unavailable from publisher; no claim its special-case proofs were checked.','Galbiati/Gualandi/Maffioli SEA2011 original conference proof not retrieved; associated author revised2013 preprint S9 full relevant proofs/model checked. Chronology must not assign revised2013 Theorem2 to2011.','No dedicated full-paper directed-Hamiltonian or compatible-branchings hardness construction for the literal target was located in these queries. Search silence is not nonexistence.','Martin formulation-equivalence is outside this candidate claim; no prior equivalence theorem authenticated here.','Secondary snippets, slides, mirrors and third-party bulk journal scans were discovery leads only, not theorem evidence.']}
for f in ['first_classical_search.json','first_primary_search.json']:
    search['raw_snapshot_retention'].append({'private_path':'_private/'+f,**digest(B/'_private'/f)})
save('SEARCH_LEDGER.json',search)

bundle={'literal_feasible_set':'one common undirected spanning tree; induced arborescences at EVERY vertex root','objective':'sum of complete rooted-tree arc costs with independent explicit cost vectors','graph':'connected simple; sparse gadget graph, at most1+2n+3m edges','encoding':'dense finite input cost table, NOT a dense or complete graph restriction','costs_original':['0','1','n+1'],'threshold_original':'(n+1)m+n','strong_NP_and_unary':'polynomially bounded explicit integer values and threshold','B2_audit_consequence':'same structural identity for B≥2: p+Bq=(Bm+n)+(1-h)+(B-1)(q-m); choosing B2 gives costs0,1,2 and threshold2m+n','positive_shift':'add1 to every root/arc entry and N(N-1) to threshold; original gives1,2,n+2, B2 gives1,2,3','not_claimed':['unrestricted OPT=K+min-unsatisfied-clauses','bounded degree','planar','fixed number of active roots','approximation','formulation equivalence','neighboring Problem2']}
matrix=[
 {'source':'S1','classical_restrictions_verified':'Connected simple unit-length input graph; tree budget N−1; polynomial-sized replication/threshold, hence strong/unary hardness for its own model.','same_common_tree':'yes','all_roots_single_arc_objective':'no: unordered pair distances','entire_target_bundle_implication':'NOT ESTABLISHED','exact_gap':'Published threshold-forced support family has fixed core and variable leaf attachments; literal target cost on this family is separable, unlike the grouping savings in the published objective. A different gadget/feasible-set/objective map would need proof.','strongest_genuinely_new_residual':'unknown; exact-target priority unresolved'},
 {'source':'S2','classical_restrictions_verified':'Publisher metadata/definition only; full proof unavailable. No hardness restriction authenticated.','same_common_tree':'yes at definition level','all_roots_single_arc_objective':'no: requirement-weighted pair paths','entire_target_bundle_implication':'UNASSESSED FULL PROOF GAP','exact_gap':'Retrieve/check full original proofs; pair-path cost identity is not target identity.','strongest_genuinely_new_residual':'unknown'},
 {'source':'S3','classical_restrictions_verified':'Simple undirected graph, finite edge transportation costs and pair communication data; all-origin flow model and NP-hard pricing subproblem described.','same_common_tree':'yes','all_roots_single_arc_objective':'no: flow amounts multiply arc costs; pricing also has fixed arc costs','entire_target_bundle_implication':'NOT ESTABLISHED','exact_gap':'Removing flow charges changes pricing problem to minimum arborescence; no fixed c_r reproducing arbitrary tree-dependent demand amount on every feasible tree demonstrated.','strongest_genuinely_new_residual':'unknown'},
 {'source':'S4','classical_restrictions_verified':'Specialized shared Steiner arborescence problem uses a common root, terminal subsets, shared directed network fixed costs and user arc costs. Generic topology model permits arbitrary topology families.','same_common_tree':'no in specialized hardness model','all_roots_single_arc_objective':'no: common root/user subsets; network may have2cycles','entire_target_bundle_implication':'NOT ESTABLISHED','exact_gap':'Superclass containment does not imply hardness of one undirected-tree/all-root subclass. Must preserve identical support and all-root full-tree charges.','strongest_genuinely_new_residual':'unknown'},
 {'source':'S5','classical_restrictions_verified':'Common tree model, complete-graph assumption in formulation portion, pair requirements/distance inputs. No new hardness proof in checked sections.','same_common_tree':'yes','all_roots_single_arc_objective':'no: pair paths','entire_target_bundle_implication':'NOT ESTABLISHED','exact_gap':'Pair-distance costs do not become support costs by renaming variables; dense graph versus dense cost table must be distinguished.','strongest_genuinely_new_residual':'unknown'},
 {'source':'S6','classical_restrictions_verified':'NP-hardness on fixed stars, and fixed binary trees; unweighted ordered-pair satisfaction objective.','same_common_tree':'tree is INPUT, orientation is selected','all_roots_single_arc_objective':'no: arbitrary one orientation, reachability pair score','entire_target_bundle_implication':'NOT ESTABLISHED','exact_gap':'On a fixed input tree the literal target has exactly one feasible support and all root orientations are forced; no choice corresponds to MTO orientation variables. Degree/approximation results cannot transfer.','strongest_genuinely_new_residual':'unknown'},
 {'source':'S7','classical_restrictions_verified':'Directed and undirected NP/APX hardness proofs; undirected degree bound and cost0/1 with two colors are in checked Theorem3. Other restrictions differ by theorem.','same_common_tree':'one tree but fixed root','all_roots_single_arc_objective':'no: predecessor-edge/color-pair charge','entire_target_bundle_implication':'NOT ESTABLISHED','exact_gap':'The predecessor edge is a chosen variable. A prescribed c_r(u,v) cannot simply substitute for cost of that edge pair. No explicit gadget/cost correspondence provided.','strongest_genuinely_new_residual':'unknown'},
 {'source':'S8','classical_restrictions_verified':'NP-complete RootedRA, even with two distinct input arborescence roots in §2 construction; output root fixed. Color constraints and possible parallel colored arcs.','same_common_tree':'no: choose rainbow output from colored input supports','all_roots_single_arc_objective':'no: one-per-color feasibility','entire_target_bundle_implication':'NOT ESTABLISHED','exact_gap':'Input root count is not number of target cost vectors; identical-underlying-tree theorem is an existence result. Need simple-graph/all-root cost encoding of color feasibility and full objective.','strongest_genuinely_new_residual':'unknown'},
 {'source':'S9','classical_restrictions_verified':'Directed fixed-root color model; complete Minimum Ones and Set Cover constructions with bounded in/out degree and nonnegative integer color-pair costs; revised2013 model is quadratic.','same_common_tree':'one rooted directed support, NOT all induced vertex-root supports','all_roots_single_arc_objective':'no: adjacent selected-arc/color-pair products','entire_target_bundle_implication':'NOT ESTABLISHED','exact_gap':'Per-arc cost model in §3.1 is only a lower bound on changeover cost. Need exact directed-to-undirected/all-root feasible-set and full-cost mapping; original2011 chronology version not checked.','strongest_genuinely_new_residual':'unknown'},
]
for row in matrix:
    row['target_restriction_transfer']={key:'unestablished: no exact feasible-set/full-objective map' for key in ['connected_simple','nonnegative_integer','dense_finite_per_root_arc_table','strong_NP','unary_encoding','original_alphabet_0_1_n_plus_1','B2_alphabet_0_1_2','strictly_positive_shift']}
save('NOVELTY_MATRIX.json',{'UTC':now,'candidate_bundle':bundle,'rows':matrix,'restriction_transfer_rule':'Unestablished transfer does not say the source lacks a named restriction; it says that restriction has not been proved for the literal target by this source construction.','cross_row_conclusion':'No checked classical construction implies the entire literal target bundle. This finding is bounded source comparison, not novelty establishment. Constant alphabet B2 is an audit consequence of the same candidate identity, not independent novelty clearance.'})

proof=A/'repaired_diagnostics_v1/PROOF.md'
inputs={'original_head':'3526d46bf143b08e5055ffa7728c6278e9f958ea','candidate_proof':{'path':'../repaired_diagnostics_v1/PROOF.md',**digest(proof)},'original_source_pdf':{'path':'../primary_sources_20261006/owr.pdf',**digest(A/'primary_sources_20261006/owr.pdf')},'gate':{'path':'../ROOT_MATHEMATICAL_GATE_20261006.json',**digest(A/'ROOT_MATHEMATICAL_GATE_20261006.json')}}
save('INPUT_BINDINGS.json',inputs)
save('COMPARISON_RESULTS.json',json.loads((B/'_private/cost_model_comparison_v2.stdout').read_text()))
verdict={'UTC':now,'family':'classical spanning-tree, communication/routing, tree-cut, orientation, compatible/colored-arborescence mechanisms','target':'30003996 / OWR-16633-013 / eligible claimed_solved PR108','scope':'priority audit of existing claims; no new central proof-search route','status':'BOUNDED_FAMILY_AUDIT_COMPLETE_WITH_ACCESS_GAPS','mathematical_gate_inherited_percent':100,'priority_established_percent':0,'novelty_cleared':False,'full_bundle_prior_implication_found':False,'genuinely_new_residual_certified':None,'strongest_verified_comparative_result':'Checked published classical models differ in feasible choices or full costs; JLRK forced-tree leaf family yields a separable literal objective rather than its grouping objective. This blocks only a direct same-support cost transfer.','earliest_relevant_definition_printing_checked':'Hu journal September1974 metadata only','earliest_relevant_full_hardness_printing_checked':'JLRK institutional preprint February1977; journal1978','earlier_exact_target_resolution_authenticated':None,'original_substantive_approaches_used':2,'original_approach_cap':5,'new_central_proof_search_approaches':0,'original_structured_turn_ledger_present':False,'original_budget_provenance':'QUEUE plus two-approach prose retained; no structured original turn ledger invented','candidate_excluded_claims':bundle['not_claimed'],'access_and_coverage_gaps':search['coverage_gaps'],'recommendation':{'current':'Keep priority0% and avoid a novelty claim; parent should combine independent families and obtain its fresh adversarial review before any promotion decision.','concrete_followups':['Hu1974 full original special-case/cut-tree proofs, when primary access is available.','SEA2011 original chapter to check exactly which revised2013 claims/constructions were already present.','Only a newly located exact-target lead or an explicit proposed model-transfer mapping warrants further family proof audit.'],'exhaustive_history':'A finite search cannot guarantee absence of every earlier result. No impossible exhaustive-history guarantee is made a completion prerequisite for this bounded packet.','not_automatic_blockers':'Unretrieved chronology versions and related-model sources are explicit limits, not evidence of prior exact-target sufficiency.'},'authority':'No human-referee, novelty, publication, submission, outreach, or closure authority claimed.','write_scope':str(B),'side_effects':'Only files in write_scope; no Git/index, service/editor, publication/outreach or preparation of outreach.'}
verdict['independent_go_no_go']={'go':'Proceed to the parent\'s fresh combined adversarial review and, if it passes, a narrowly attributed answer to the cited2018 question. No identified classical-family priority obstruction to that limited claim.','no_go':'Certified novelty, absolute first-discovery, or exhaustive prior-history language.','inaccessible_sources_assessment':'Hu1974 and SEA2011 are coverage/chronology limits in visibly different pair-path and predecessor-edge models. No concrete evidence of a sufficient literal-target antecedent or proposed exact map was identified.','transformation_uncertainty':'Generic unknown polynomial transformations are not an identified material obstruction; any actual proposed transfer would require full feasible-set/objective/restriction audit.','authority_limit':'Source-priority recommendation only; parent adjudication/fresh adversary and human publication authority remain distinct.'}
save('VERDICT.json',verdict)
if 'Checkpoint3.' not in (B/'RESEARCH_LOG.md').read_text():
 with (B/'RESEARCH_LOG.md').open('a') as f:
    f.write(f'\n- {now}: Checkpoint3. Full relevant MINCCA2014 and RainbowArborescence v2 hardness/common-tree proofs checked; candidate restrictions compared. Fixed-core leaf separability derived as a model-comparison lemma and checked on four supports; K4 checks retained. Family review90%; novelty0%; new central proof-search approaches0.\n')
    f.write(f'- {now}: Checkpoint4. Bounded audit packet assembled, source scope/access failures and search precision recorded; no exact earlier literal-target implication authenticated. Packet completion100%; broader priority/discovery goal0% established, with Hu1974 and antecedent coverage gaps. No authority escalation.\n')
