// Floating distance steers a bounded search; every coloring count and witness sign is exact.
#include <bits/stdc++.h>
using namespace std;using ll=long long;using I=__int128_t;
string dec(I x){if(!x)return"0";bool neg=x<0;if(neg)x=-x;string s;while(x){s+=char('0'+x%10);x/=10;}if(neg)s+='-';reverse(s.begin(),s.end());return s;}
int main(){mt19937 rng(53003338);vector<vector<int>>P={{1,2,12},{1,4,10},{1,6,8},{1,14},{2,4,9},{2,5,8},{2,13},{3,4,8},{3,12},{4,11},{5,10},{6,9},{7,8},{15}};double base[]={44,35,35,44,35,26,44,44,44,44,44,35,44,22};double target[14];for(int i=0;i<14;i++)target[i]=.99*base[i]/540+.01*(P[i].size()<=2?1.0/8:0);
struct Eval{double dist;ll z,f,g,j;array<ll,14>hist;};double best=1e100;int bestn=0;vector<int>bestnb;Eval bestval{};long long evaluations=0;
for(int n:{6,7,8}){int N=1<<n,Q=1;for(int i=0;i<n;i++)Q*=3;vector<unsigned char>factor(size_t(Q)*N);vector<int>pid(Q),zero(Q);vector<int>allowed;for(int mask=1;mask<N;mask++)if(__builtin_popcount((unsigned)mask)>=2&&__builtin_popcount((unsigned)(mask&15))<=2)allowed.push_back(mask);
for(int code=0;code<Q;code++){int x=code;vector<int>colors(n),seen(N);for(int i=0;i<n;i++){colors[i]=x%3;x/=3;if(i<4&&!colors[i])zero[code]|=1<<i;}vector<int>parts;for(int c=0;c<3;c++){int mask=0;for(int i=0;i<4;i++)if(colors[i]==c)mask|=1<<i;if(mask)parts.push_back(mask);}sort(parts.begin(),parts.end());pid[code]=find(P.begin(),P.end(),parts)-P.begin();for(int mask=1;mask<N;mask++){int j=__builtin_ctz((unsigned)mask);seen[mask]=seen[mask&(mask-1)]|(1<<colors[j]);factor[size_t(code)*N+mask]=3-__builtin_popcount((unsigned)seen[mask]);}}
auto evaluate=[&](const vector<int>&nb){Eval e{};for(int code=0;code<Q;code++){ll w=1;for(int mask:nb){w*=factor[size_t(code)*N+mask];if(!w)break;}e.z+=w;e.hist[pid[code]]+=w;if((zero[code]&3)==3)e.f+=w;if((zero[code]&12)==12)e.g+=w;if(zero[code]==15)e.j+=w;}for(int k=0;k<14;k++){double v=double(e.hist[k])/e.z-target[k];e.dist+=v*v/target[k];}evaluations++;return e;};
for(int restart=0;restart<10;restart++){vector<int>nb;int m=4+rng()%12;for(int j=0;j<m;j++)nb.push_back(allowed[rng()%allowed.size()]);Eval cur=evaluate(nb);for(int step=0;step<400;step++){vector<int>next=nb;int op=rng()%3;if(op==0&&next.size()<20)next.push_back(allowed[rng()%allowed.size()]);else if(op==1&&next.size()>2)next.erase(next.begin()+rng()%next.size());else next[rng()%next.size()]=allowed[rng()%allowed.size()];Eval ev=evaluate(next);I cov=I(ev.j)*ev.z-I(ev.f)*ev.g;if(cov<0){cout<<"{\"status\":\"SOURCE_COUNTEREXAMPLE_CANDIDATE\",\"nA\":"<<n<<",\"q\":3,\"observed\":[0,1,2,3],\"B_neighborhoods\":[";for(size_t j=0;j<next.size();j++){if(j)cout<<',';cout<<next[j];}cout<<"],\"total\":"<<ev.z<<",\"massF\":"<<ev.f<<",\"massG\":"<<ev.g<<",\"massFG\":"<<ev.j<<",\"covariance_numerator\":\""<<dec(cov)<<"\"}\n";return 1;}if(ev.dist<best){best=ev.dist;bestn=n;bestnb=next;bestval=ev;}double temp=.03*pow(.002,double(step)/400);double u=(double(rng())+.5)/(double(mt19937::max())+1);if(ev.dist<cur.dist||u<exp((cur.dist-ev.dist)/temp)){nb=move(next);cur=ev;}}}}
cout<<setprecision(17)<<"{\n \"status\":\"NO_SOURCE_WITNESS_IN_BOUNDED_SIGNATURE_SEARCH\",\n \"seed\":53003338,\n \"exact_graph_evaluations\":"<<evaluations<<",\n \"A_sizes\":[6,7,8],\n \"observed_A_vertices\":[0,1,2,3],\n \"q\":3,\n \"best_A_size\":"<<bestn<<",\n \"best_B_neighborhoods\":[";for(size_t j=0;j<bestnb.size();j++){if(j)cout<<',';cout<<bestnb[j];}cout<<"],\n \"best_distance_diagnostic\":"<<best<<",\n \"best_exact_counts\":["<<bestval.z<<","<<bestval.f<<","<<bestval.g<<","<<bestval.j<<"],\n \"best_covariance_numerator\":\""<<dec(I(bestval.j)*bestval.z-I(bestval.f)*bestval.g)<<"\",\n \"scope\":\"Heuristic distance to an abstract color-symmetric regression countermeasure; actual graph counts exact. No realizability theorem and no source counterexample.\"\n}\n";}
