// Exact bounded association controls. No numerical inference of an all-graph result.
#include <bits/stdc++.h>
using namespace std;
using ll=long long; using big=__int128_t;
vector<uint32_t> upsets(int n){if(n==0)return {0,1};auto v=upsets(n-1);vector<uint32_t>o;int shift=1<<(n-1);for(auto a:v)for(auto b:v)if((a&b)==a)o.push_back(a|(b<<shift));return o;}
vector<ll> distribution(int n,int q,const vector<int>&nb){vector<ll>w(1<<n);vector<int>c(n);int total=1;for(int i=0;i<n;i++)total*=q;for(int code=0;code<total;code++){int z=code,mask=0;for(int i=0;i<n;i++){c[i]=z%q;z/=q;if(!c[i])mask|=1<<i;}ll ways=1;for(int t:nb){int seen=0;for(int i=0;i<n;i++)if(t>>i&1)seen|=1<<c[i];ways*=q-__builtin_popcount((unsigned)seen);}w[mask]+=ways;}return w;}
struct Result{bool ok;uint32_t a,b;ll za,zb,zab,total;unsigned long long pairs;};
Result check(int n,const vector<ll>&w){auto U=upsets(n);ll z=accumulate(w.begin(),w.end(),0LL);array<array<ll,256>,4>T{};for(int block=0;block<4;block++)for(int a=1;a<256;a++){int k=__builtin_ctz((unsigned)a);T[block][a]=T[block][a&(a-1)]+((8*block+k<(1<<n))?w[8*block+k]:0);}auto mass=[&](uint32_t a){ll s=0;for(int j=0;j<4;j++)s+=T[j][(a>>(8*j))&255];return s;};vector<ll>M;for(auto u:U)M.push_back(mass(u));unsigned long long count=0;for(size_t i=0;i<U.size();i++)for(size_t j=i;j<U.size();j++){ll a=M[i],b=M[j],ab=mass(U[i]&U[j]);count++;if(big(ab)*z<big(a)*b)return {false,U[i],U[j],a,b,ab,z,count};}return {true,0,0,0,0,0,z,count};}
int main(){unsigned long long pairs=0,graphs=0;vector<int>types;for(int i=1;i<16;i++)if(__builtin_popcount((unsigned)i)>=2)types.push_back(i);assert(types.size()==11);for(int q=3;q<=8;q++)for(int code=0;code<(1<<11);code++){vector<int>nb;for(int j=0;j<11;j++)if(code>>j&1)nb.push_back(types[j]);auto w=distribution(4,q,nb);auto r=check(4,w);graphs++;pairs+=r.pairs;if(!r.ok){cout<<"FAIL q="<<q<<" neighborhood-selection="<<code<<" events="<<r.a<<","<<r.b<<"\n";return 1;}}vector<int>dreidel={25,14,22,6};auto w=distribution(5,3,dreidel);auto r=check(5,w);if(!r.ok){cout<<"DREIDEL FAIL events "<<r.a<<","<<r.b<<"\n";return 1;}
cout<<"{\n  \"status\":\"PASS_FINITE_CONTROLS_ONLY\",\n  \"A4_distinct_nontrivial_neighborhood_graphs_per_q\":2048,\n  \"q_values\":[3,4,5,6,7,8],\n  \"graph_q_cases\":"<<graphs<<",\n  \"A4_upsets\":"<<upsets(4).size()<<",\n  \"A4_event_pair_checks\":"<<pairs<<",\n  \"dreidel_A5_upsets\":"<<upsets(5).size()<<",\n  \"dreidel_event_pair_checks\":"<<r.pairs<<",\n  \"dreidel_coloring_total\":"<<r.total<<",\n  \"dreidel_zero_mask_weights\":[";for(int i=0;i<32;i++){if(i)cout<<",";cout<<w[i];}cout<<"],\n  \"scope\":\"Exhaustive within the stated finite graph family and complete increasing-event sets; no full conjecture inferred.\"\n}\n";
}
