// Fixed-seed exact witness search; absence of a witness is finite evidence only.
#include <bits/stdc++.h>
using namespace std;using ll=long long;using big=__int128_t;
string dec(big x){if(!x)return "0";bool neg=x<0;if(neg)x=-x;string s;while(x){s+=char('0'+x%10);x/=10;}if(neg)s+='-';reverse(s.begin(),s.end());return s;}
int main(){mt19937 rng(30003338);unsigned long long graphs=0,principal=0,mixed=0;vector<pair<int,int>>families={{5,3},{6,3},{7,3},{8,3},{9,3},{5,4},{6,4},{7,4},{8,4},{5,5},{6,5}};
for(auto [n,q]:families){int N=1<<n,Q=1;for(int i=0;i<n;i++)Q*=q;vector<unsigned char>factor(size_t(Q)*N);vector<int>zm(Q);for(int code=0;code<Q;code++){int x=code,z=0;vector<int>c(n),seen(N);for(int i=0;i<n;i++){c[i]=x%q;x/=q;if(!c[i])z|=1<<i;}zm[code]=z;factor[size_t(code)*N]=q;for(int mask=1;mask<N;mask++){int j=__builtin_ctz((unsigned)mask);seen[mask]=seen[mask&(mask-1)]|(1<<c[j]);factor[size_t(code)*N+mask]=q-__builtin_popcount((unsigned)seen[mask]);}}
for(int trial=0;trial<1200;trial++){int m=2+rng()%19;vector<int>nb;for(int b=0;b<m;b++){int mask;if(b&&rng()%4==0)mask=nb[rng()%nb.size()];else{int degree=2+rng()%min(4,n-1);mask=0;while(__builtin_popcount((unsigned)mask)<degree)mask|=1<<(rng()%n);}nb.push_back(mask);}vector<ll>w(N);for(int code=0;code<Q;code++){ll ways=1;for(int mask:nb){ways*=factor[size_t(code)*N+mask];if(!ways)break;}w[zm[code]]+=ways;}ll Z=accumulate(w.begin(),w.end(),0LL);if(Z<=0){cerr<<"impossible nonpositive count";return 2;}vector<ll>upper=w;for(int bit=0;bit<n;bit++)for(int s=0;s<N;s++)if(!(s>>bit&1))upper[s]+=upper[s|(1<<bit)];auto fail=[&](string type,string A,string B,ll massA,ll massB,ll massAB){cout<<"{\"status\":\"COUNTEREXAMPLE_CANDIDATE\",\"type\":\""<<type<<"\",\"n\":"<<n<<",\"q\":"<<q<<",\"trial\":"<<trial<<",\"neighborhoods\":[";for(size_t i=0;i<nb.size();i++){if(i)cout<<',';cout<<nb[i];}cout<<"],\"eventA\":"<<A<<",\"eventB\":"<<B<<",\"total\":"<<Z<<",\"massA\":"<<massA<<",\"massB\":"<<massB<<",\"massAB\":"<<massAB<<",\"covariance_numerator\":\""<<dec(big(massAB)*Z-big(massA)*massB)<<"\"}\n";};
for(int a=1;a<N;a++)for(int b=a+1;b<N;b++){principal++;if(big(upper[a|b])*Z<big(upper[a])*upper[b]){fail("principal",to_string(a),to_string(b),upper[a],upper[b],upper[a|b]);return 1;}}
// Random upward events as unions of principal upsets; exact mass lookup.
int blocks=(N+7)/8;vector<array<ll,256>> tab(blocks);for(int block=0;block<blocks;block++){tab[block][0]=0;for(int s=1;s<256;s++){int bit=__builtin_ctz((unsigned)s);tab[block][s]=tab[block][s&(s-1)]+w[8*block+bit];}}vector<vector<unsigned char>>ev;vector<vector<int>>mins;vector<ll>mass;
for(int j=0;j<48;j++){vector<int>a;int k=1+rng()%5;for(int l=0;l<k;l++)a.push_back(1+rng()%(N-1));vector<unsigned char>e(blocks);ll val=0;for(int s=0;s<N;s++){bool in=false;for(int t:a)if((s&t)==t){in=true;break;}if(in){e[s/8]|=1<<(s%8);val+=w[s];}}mins.push_back(a);ev.push_back(e);mass.push_back(val);}
for(int a=0;a<48;a++)for(int b=a+1;b<48;b++){ll both=0;for(int block=0;block<blocks;block++)both+=tab[block][ev[a][block]&ev[b][block]];mixed++;if(big(both)*Z<big(mass[a])*mass[b]){auto fmt=[](vector<int>v){string s="[";for(size_t j=0;j<v.size();j++){if(j)s+=",";s+=to_string(v[j]);}return s+"]";};fail("union-of-principal",fmt(mins[a]),fmt(mins[b]),mass[a],mass[b],both);return 1;}}graphs++;}
cerr<<"finished n="<<n<<" q="<<q<<"\n";}
cout<<"{\n  \"status\":\"NO_WITNESS_IN_FIXED_FINITE_SEARCH\",\n  \"seed\":30003338,\n  \"graph_q_cases\":"<<graphs<<",\n  \"principal_event_pair_checks\":"<<principal<<",\n  \"sampled_upset_pair_checks\":"<<mixed<<",\n  \"families\":[[5,3],[6,3],[7,3],[8,3],[9,3],[5,4],[6,4],[7,4],[8,4],[5,5],[6,5]],\n  \"graphs_per_family\":1200,\n  \"B_size\":\"2 through 20\",\n  \"B_degrees\":\"2 through min(5,|A|); repeated neighborhoods allowed\",\n  \"scope\":\"Every tested covariance exact; finite fixed-seed search does not prove positive association.\"\n}\n";}
