// Exact minimum-upset covariance via a maximum-closure network.
#include <bits/stdc++.h>
using namespace std;using ll=long long;using I=__int128_t;
string str(I x){if(!x)return "0";bool minus=x<0;if(minus)x=-x;string s;while(x){s+=char('0'+x%10);x/=10;}if(minus)s+='-';reverse(s.begin(),s.end());return s;}
struct Dinic{struct E{int to,rev;I cap;};int n;vector<vector<E>>g;vector<int>lev,it;Dinic(int n):n(n),g(n),lev(n),it(n){}void add(int a,int b,I c){E x{b,(int)g[b].size(),c},y{a,(int)g[a].size(),0};g[a].push_back(x);g[b].push_back(y);}bool bfs(int s,int t){fill(lev.begin(),lev.end(),-1);queue<int>Q;Q.push(s);lev[s]=0;while(!Q.empty()){int a=Q.front();Q.pop();for(auto&e:g[a])if(e.cap>0&&lev[e.to]<0){lev[e.to]=lev[a]+1;Q.push(e.to);}}return lev[t]>=0;}I dfs(int a,int t,I f){if(a==t)return f;for(int &i=it[a];i<(int)g[a].size();i++){E&e=g[a][i];if(e.cap>0&&lev[e.to]==lev[a]+1){I z=dfs(e.to,t,min(f,e.cap));if(z){e.cap-=z;g[e.to][e.rev].cap+=z;return z;}}}return 0;}I flow(int s,int t){I ans=0,inf=I(1)<<125;while(bfs(s,t)){fill(it.begin(),it.end(),0);while(I x=dfs(s,t,inf))ans+=x;}return ans;}vector<char>reach(int s){vector<char>v(n);v[s]=1;queue<int>Q;Q.push(s);while(!Q.empty()){int a=Q.front();Q.pop();for(auto&e:g[a])if(e.cap>0&&!v[e.to]){v[e.to]=1;Q.push(e.to);}}return v;}};
vector<ll>dist(int n,int q,vector<int>nb){int N=1<<n,Q=1;for(int i=0;i<n;i++)Q*=q;vector<ll>w(N);vector<int>c(n),seen(N);for(int code=0;code<Q;code++){int x=code,zeros=0;for(int i=0;i<n;i++){c[i]=x%q;x/=q;if(!c[i])zeros|=1<<i;}seen[0]=0;for(int mask=1;mask<N;mask++){int j=__builtin_ctz((unsigned)mask);seen[mask]=seen[mask&(mask-1)]|(1<<c[j]);}ll z=1;for(int mask:nb){z*=q-__builtin_popcount((unsigned)seen[mask]);if(!z)break;}w[zeros]+=z;}return w;}
struct R{I cov;vector<char>G;ll total,a,b,ab;};R optimize(int n,const vector<ll>&w,const vector<char>&F){int N=1<<n;ll Z=accumulate(w.begin(),w.end(),0LL),a=0;for(int s=0;s<N;s++)if(F[s])a+=w[s];I negative=0;vector<I>cost(N);for(int s=0;s<N;s++){cost[s]=I(w[s])*(I(Z)*F[s]-a);if(cost[s]<0)negative-=cost[s];}Dinic D(N+2);I inf=negative+1;for(int s=0;s<N;s++){if(cost[s]<0)D.add(N,s,-cost[s]);else D.add(s,N+1,cost[s]);for(int j=0;j<n;j++)if(!(s>>j&1))D.add(s,s|(1<<j),inf);}I f=D.flow(N,N+1);auto G=D.reach(N);G.resize(N);ll b=0,ab=0;for(int s=0;s<N;s++)if(G[s]){b+=w[s];if(F[s])ab+=w[s];for(int j=0;j<n;j++)if(!(s>>j&1)&&!G[s|(1<<j)])throw runtime_error("not upward");}I cov=I(ab)*Z-I(a)*b;if(cov!=f-negative)throw runtime_error("cut mismatch");return{cov,G,Z,a,b,ab};}
vector<char>event(int n,const vector<int>&mins){vector<char>e(1<<n);for(int s=0;s<(1<<n);s++)for(int t:mins)if((s&t)==t){e[s]=1;break;}return e;}
vector<int>minimal(const vector<char>&e,int n){vector<int>v;for(int s=0;s<(1<<n);s++)if(e[s]){bool ok=true;for(int j=0;j<n;j++)if((s>>j&1)&&e[s^(1<<j)])ok=false;if(ok)v.push_back(s);}return v;}
string arr(vector<int>v){string s="[";for(size_t i=0;i<v.size();i++){if(i)s+=',';s+=to_string(v[i]);}return s+"]";}
vector<uint32_t>upsets(int n){if(!n)return{0,1};auto v=upsets(n-1);vector<uint32_t>o;for(auto a:v)for(auto b:v)if((a&b)==a)o.push_back(a|(b<<(1<<(n-1))));return o;}
int main(){mt19937 rng(33003338);unsigned long long flows=0,graphs=0;
auto dw=dist(5,3,{25,14,22,6});vector<ll>pin(16);for(int s=0;s<16;s++){int full=(s&1)|2|((s&14)<<1);pin[s]=dw[full];}auto neg=optimize(4,pin,event(4,{1}));if(neg.cov>-16)throw runtime_error("negative control failed");
// Independent complete-event validation of the known unconditioned dreidel case.
for(auto bits:upsets(5)){vector<char>F(32);for(int s=0;s<32;s++)F[s]=(bits>>s)&1;auto r=optimize(5,dw,F);flows++;if(r.cov<0)throw runtime_error("dreidel mismatch");}
unsigned long long brute_controls=0;mt19937 control_rng(918373);auto U4=upsets(4);for(int trial=0;trial<20;trial++){vector<ll>w(16);for(auto &x:w)x=control_rng()%11;ll Z=accumulate(w.begin(),w.end(),0LL);for(auto fb:U4){vector<char>F(16);ll a=0;for(int j=0;j<16;j++){F[j]=(fb>>j)&1;if(F[j])a+=w[j];}I best=0;for(auto gb:U4){ll b=0,ab=0;for(int j=0;j<16;j++)if(gb>>j&1){b+=w[j];if(F[j])ab+=w[j];}best=min(best,I(ab)*Z-I(a)*b);}auto r=optimize(4,w,F);if(r.cov!=best)throw runtime_error("brute closure mismatch");brute_controls++;}}
auto run=[&](int n,int q,vector<int>nb,int random_events,string label){auto w=dist(n,q,nb);vector<vector<int>>tests;for(int s=1;s<(1<<n);s++)if(__builtin_popcount((unsigned)s)==2||__builtin_popcount((unsigned)s)==3)tests.push_back({s});for(int i=0;i<random_events;i++){vector<int>v;int k=2+rng()%4;for(int j=0;j<k;j++)v.push_back(1+rng()%((1<<n)-1));tests.push_back(v);}for(auto mi:tests){auto F=event(n,mi);auto r=optimize(n,w,F);flows++;if(r.cov<0){cout<<"{\"status\":\"COUNTEREXAMPLE_CANDIDATE\",\"label\":\""<<label<<"\",\"n\":"<<n<<",\"q\":"<<q<<",\"B_neighborhoods\":"<<arr(nb)<<",\"event_F_minimal\":"<<arr(minimal(F,n))<<",\"event_G_minimal\":"<<arr(minimal(r.G,n))<<",\"total\":"<<r.total<<",\"mass_F\":"<<r.a<<",\"mass_G\":"<<r.b<<",\"mass_FG\":"<<r.ab<<",\"covariance_numerator\":\""<<str(r.cov)<<"\"}\n";return false;}}graphs++;return true;};
// Every one-edge subdivision of each labeled simple graph on four vertices with at least three edges.
for(int code=0;code<64;code++){vector<pair<int,int>>ed;int bit=0;for(int i=0;i<4;i++)for(int j=i+1;j<4;j++,bit++)if(code>>bit&1)ed.push_back({i,j});if(ed.size()<3)continue;vector<int>nb(4);for(size_t e=0;e<ed.size();e++){nb[ed[e].first]|=1<<e;nb[ed[e].second]|=1<<e;}int n=ed.size();for(int q:{3,4,5})if(!run(n,q,nb,80,"subdivision-H4"))return 1;}
// Dense five-vertex latent graphs, observed on their subdivided edges.
for(int code:{1023,1022,1020,1017,1008,927,831,639}){vector<pair<int,int>>ed;int bit=0;for(int i=0;i<5;i++)for(int j=i+1;j<5;j++,bit++)if(code>>bit&1)ed.push_back({i,j});vector<int>nb(5);for(size_t e=0;e<ed.size();e++){nb[ed[e].first]|=1<<e;nb[ed[e].second]|=1<<e;}if(!run(ed.size(),3,nb,120,"subdivision-H5"))return 1;}
for(auto [n,q]:vector<pair<int,int>>{{6,3},{7,3},{8,3},{6,4},{7,4}})for(int trial=0;trial<200;trial++){vector<int>nb;int m=3+rng()%14;for(int j=0;j<m;j++){int mask=0,deg=2+rng()%min(4,n-1);if(j&&rng()%3==0)mask=nb[rng()%j];else while(__builtin_popcount((unsigned)mask)<deg)mask|=1<<(rng()%n);nb.push_back(mask);}if(!run(n,q,nb,32,"random-repeated-neighborhood"))return 1;}
cout<<"{\n \"status\":\"NO_WITNESS_IN_FINITE_OPTIMAL_UPSET_SEARCH\",\n \"seed\":33003338,\n \"graph_q_cases\":"<<graphs<<",\n \"exact_minimum_closure_runs\":"<<flows+brute_controls+1<<",\n \"brute_force_cross_checks\":"<<brute_controls<<",\n \"dreidel_full_event_controls\":7581,\n \"pinned_dreidel_control_covariance_numerator\":\""<<str(neg.cov)<<"\",\n \"scope\":\"For each tested increasing F the entire increasing-G space was optimized exactly. Tested F and graph lists remain finite.\"\n}\n";}
