"""Root privately reproduces the fresh whole-package adversary and live gate."""
from pathlib import Path
from concurrent.futures import ThreadPoolExecutor
import datetime, hashlib, json, os, re, subprocess, sys

A=Path(__file__).resolve().parent;D=A/'clean_final_adversary'
W=A/'tmp/root_clean_final';assert not W.exists(),'Preserve earlier runs.'
W.mkdir(parents=True);C=W/'control';C.mkdir()
PY=A.parent/'pr378_30004322/sources_effective_review/private_runtime/bin/python'
def sha(b):return hashlib.sha256(b).hexdigest()
name=sys.argv[1] if len(sys.argv)>1 else 'PUBLIC_MANIFEST.json'
mf=json.loads((D/name).read_text());before={str(D/name):sha((D/name).read_bytes())}
for e in mf['files']:
    assert not {'tmp','raw_sources'} & set(Path(e['path']).parts)
    p=D/e['path'];b=p.read_bytes();assert len(b)==e['bytes'] and sha(b)==e['sha256'],str(p)
    before[str(p)]=sha(b);q=C/e['path'];q.parent.mkdir(parents=True,exist_ok=True);q.write_bytes(b)
(C/name).write_bytes((D/name).read_bytes())
# Verify every original source independently against root's own download.
mapping={'OWR':'OWR_2019_50.pdf','FGKv3':'FGK_2022_arxiv.pdf','FGKpublished':'FGK_2023_published.pdf','MaoSongv2':'Mao_Song_2026.pdf','divisorPower':'de_la_Breteche_Tenenbaum_2026.pdf'}
source_bindings=[]
for local,root in mapping.items():
    b=(D/'tmp'/(local+'.pdf')).read_bytes();assert b==(A/'raw_sources'/root).read_bytes()
    p=C/'tmp'/(local+'.pdf');p.parent.mkdir(parents=True,exist_ok=True);p.write_bytes(b)
    source_bindings.append(dict(file=local+'.pdf',bytes=len(b),sha256=sha(b),root_fresh_bytes_identical=True))
# Route only input locations to the frozen real audit. ROOT remains the real
# repository; H and every temporary/output location remain private controls.
for program in ['package_audit.py','final_integration.py']:
    code=(C/program).read_text();assert code.count('ROOT=H.parents[3]')==1
    code=code.replace('ROOT=H.parents[3]','ROOT=Path('+repr(str(A.parents[2]))+')\nINPUT=Path('+repr(str(A))+')')
    code=re.sub(r'\bH\.parent\b','INPUT',code)
    (C/program).write_text(code)
jobs=[('source_first','independent_controls.py','PRE_CANDIDATE_CONTROLS.json','created_utc'),('mathematics','mathematical_controls.py','MATHEMATICAL_CONTROLS.json','created_utc'),('rank_extension','rank_extension_controls.py','RANK_EXTENSION_CONTROLS.json','utc'),('package','package_audit.py','PACKAGE_REPLAY_RECEIPT.json','utc')]
def run(job):
    label,program,expected,volatile=job
    r=subprocess.run([str(PY),'-B',str(C/program)],cwd=C,capture_output=True,env=dict(os.environ,PYTHONDONTWRITEBYTECODE='1'))
    (A/('root_clean_'+label+'.stdout')).write_bytes(r.stdout);(A/('root_clean_'+label+'.stderr')).write_bytes(r.stderr)
    assert r.returncode==0 and not r.stderr,(label,r.stderr.decode())
    actual=json.loads(r.stdout);want=json.loads((D/expected).read_text())
    actual.pop(volatile);want.pop(volatile);assert actual==want,label
    return dict(program=program,expected=expected,exit_code=0,stderr_empty=True,stdout_bytes=len(r.stdout),stdout_sha256=sha(r.stdout),complete_json_equal_except=[volatile])
with ThreadPoolExecutor(max_workers=3) as pool:results=list(pool.map(run,jobs))
# Compare every entire author/history/public wrapper stream generated by the
# new private package replay to the auditor's preserved stream.
replay=json.loads((D/'PACKAGE_REPLAY_RECEIPT.json').read_text());streams=[]
for e in replay['replays']:
    for kind in ['stdout','stderr']:
        p=C/'tmp/replay'/(e['name']+'.'+kind);b=p.read_bytes();assert sha(b)==e[kind+'_sha256']
        streams.append(dict(name=e['name'],kind=kind,bytes=len(b),sha256=sha(b)))
# Independently fetch final metadata with the exact recorded fields, and
# separately bind the current API/base, commit parents/tree and remote refs.
livepath=D/'tmp/live_pr375_metadata.json'
keys=sorted(json.loads(livepath.read_text()))
prevkeys=sorted(json.loads((D/'tmp/live_pr376_merge.json').read_text()))
cmds=[('live375',['gh','pr','view','375','--json',','.join(keys)]),('live375_base',['gh','pr','view','375','--json','number,baseRefOid,headRefOid']),('remote_refs',['git','ls-remote','origin','refs/heads/main','refs/heads/math/30004293-reviewed-prefix-growth']),('live376',['gh','pr','view','376','--json',','.join(prevkeys)]),('live_main_ref',['gh','api','repos/AlecKriebel/Math/git/ref/heads/main']),('commit',['gh','api','repos/AlecKriebel/Math/git/commits/6b4d7afefb1b98c2fe06c1dceada279d4c21c055'])]
observations={}
for tag,cmd in cmds:
    r=subprocess.run(cmd,capture_output=True);(A/('root_clean_final_'+tag+'.stdout')).write_bytes(r.stdout);(A/('root_clean_final_'+tag+'.stderr')).write_bytes(r.stderr)
    assert r.returncode==0 and not r.stderr,(tag,r.stderr.decode());observations[tag]=r.stdout
metadata=C/'ROOT_FRESH_LIVE_PR375.json';metadata.write_bytes(observations['live375'])
pr=json.loads(observations['live375']);frozen=json.loads(livepath.read_text());assert pr==frozen
m=json.loads((A/'repaired_snapshot_manifest.json').read_text())
prbase=json.loads(observations['live375_base'])
assert pr['headRefOid']==m['head'] and prbase['baseRefOid']==m['base'] and prbase['headRefOid']==m['head'] and pr['mergeable']=='MERGEABLE' and pr['mergeStateStatus']=='CLEAN'
refs=dict(line.split()[::-1] for line in observations['remote_refs'].decode().splitlines())
assert refs=={'refs/heads/main':m['base'],'refs/heads/math/30004293-reviewed-prefix-growth':m['head']}
prev=json.loads(observations['live376']);assert prev['state']=='MERGED' and prev['mergeCommit']['oid']=='f193a85b640eae025089d8a7d35b8c00024e6ae7' and prev['mergedAt']=='2026-10-03T07:18:29Z'
commit=json.loads(observations['commit']);assert commit['sha']==m['head'] and commit['tree']['sha']=='1884a51f9e5f8605b2007227a9470245c96c0578' and [x['sha'] for x in commit['parents']]==[m['original_frozen_head'],m['base']]
private_bindings=[]
for name,content in [('live_main_ref.json',observations['live_main_ref']),('live_pr376_merge.json',observations['live376'])]:
    assert content==(D/'tmp'/name).read_bytes(),name
    (C/'tmp'/name).write_bytes(content)
    private_bindings.append(dict(name=name,bytes=len(content),sha256=sha(content),fresh_readback_byte_exact=True))
oldbody=(D/'tmp/live_pr375_metadata.pre_body_append.json').read_bytes()
(C/'tmp/live_pr375_metadata.pre_body_append.json').write_bytes(oldbody)
assert sha(json.loads(oldbody)['body'].encode())=='4fab85e37f3f47c8d58d9c6d2862339d0ddcda8849b88896599e5c0df006f78f'
private_bindings.append(dict(name='live_pr375_metadata.pre_body_append.json',bytes=len(oldbody),sha256=sha(oldbody),previous_owned_metadata_copied=True))
def git(*args):return subprocess.check_output(['git',*args],cwd=A.parents[2])
# Stronger literal queue reconstruction, retaining line endings and spaces.
old=git('show',m['base']+':unsolved_math_prioritization/QUEUE.md');new=git('show',m['head']+':unsolved_math_prioritization/QUEUE.md');rows=old.splitlines(keepends=True);after=new.splitlines(keepends=True)
assert len(rows)==len(after) and [i for i,(x,y) in enumerate(zip(rows,after)) if x!=y]==[411]
cells=rows[411].split(b'|');changed=after[411].split(b'|');assert [i for i,(x,y) in enumerate(zip(cells,changed)) if x!=y]==[8,9]
assert cells[8:10]==[b' queued ',b' 0/5 '];cells[8]=b' unsolved ';cells[9]=b' 5/5 ';rows[411]=b'|'.join(cells);assert b''.join(rows)==new
r=subprocess.run([str(PY),'-B',str(C/'final_integration.py'),'--metadata',str(metadata)],cwd=C,capture_output=True)
(A/'root_clean_final_integration.stdout').write_bytes(r.stdout);(A/'root_clean_final_integration.stderr').write_bytes(r.stderr)
assert r.returncode==0 and not r.stderr,r.stderr.decode()
actual=json.loads(r.stdout);want=json.loads((D/'FINAL_INTEGRATION_CERTIFICATE.json').read_text());actual.pop('utc');want.pop('utc');assert actual==want
assert all(sha(Path(p).read_bytes())==h for p,h in before.items())
receipt=dict(status='PASS',utc=datetime.datetime.now(datetime.timezone.utc).isoformat(),workflow_percent=100,original_resolution_percent=0,public_manifest_sha256=sha((D/(sys.argv[1] if len(sys.argv)>1 else 'PUBLIC_MANIFEST.json')).read_bytes()),public_members=len(mf['files']),sources=source_bindings,private_metadata_bindings=private_bindings,programs=results,full_package_streams=streams,final_complete_certificate_equal_except_utc=True,fresh_live_API_commit_remote_agree=True,all54_Git_objects=True,target53_unchanged=True,all220_nested_bindings=True,author42_unchanged=True,historical120_current172_distinction_verified=True,literal_queue_only_two_cells=True,stronger_postseal_rank_deduction_reproduced=True,reviewer_evidence_unchanged=True)
(A/'root_clean_final_reproduction_receipt.json').write_text(json.dumps(receipt,indent=2)+'\n')
print(json.dumps({k:v for k,v in receipt.items() if k not in ['sources','full_package_streams']},indent=2))
