"""Close current bookkeeping only after actual merge, publication and readback."""
from pathlib import Path
from datetime import datetime,timezone
import hashlib,json
A=Path(__file__).resolve().parent;P=A.parent.parent;D=A/'publication'
load=lambda p:json.loads(p.read_bytes())
sha=lambda b:hashlib.sha256(b).hexdigest()
merged=load(A/'ACTUAL_MERGE_VERIFICATION.json');root=load(A/'root_exact_live_receipt.json');post=load(A/'root_postmerge_scope_receipt.json')
published=load(D/'inspect_published_receipt.json');public=load(D/'PUBLIC_RECORD_VERIFICATION.json');tracker=load(D/'TRACKER_COMPLETE.json')
assert merged['status']=='claimed_solved' and merged['turns']=='4/5' and merged['all_target_file_hashes_exact']==43
assert root['status']=='PASS_COMPLETE_ROOT_EXACT_LIVE_AND_ALL_OUTPUTS' and root['head']==merged['reviewed_head']
assert post['status']=='PASS_ENTIRE_POSTMERGE_REPORT_AND_EVERY_FULL_CAPTURE' and post['actual_merge']==merged['actual_merge']
assert published['state']=='published' and published['environment']=='production' and published['metadata_normalizations']==[]
assert public['status']=='PASS_PUBLIC_RECORD_EXACT_METADATA_AND_ALL_FILE_BYTES' and public['doi']==published['doi']==tracker['doi']
assert published['doi_resolution']['status']=='resolved' and published['doi_resolution']['http_status']==200
assert tracker['status']=='PASS_ONE_ROW_APPENDED_AND_EXACT_READBACK' and tracker['gid']==1254632077
clearance=load(A/'PUBLISHING_CLEARANCE.json')
for r in clearance['sealed_submission_files']:
 b=(A/'preprint'/r['path']).read_bytes();assert len(b)==r['bytes'] and sha(b)==r['sha256']
t=datetime.now(timezone.utc).isoformat()
status={'utc':t,'status':'MERGED_PUBLISHED_AND_TRACKER_VERIFIED','workflow_completion_percent':100,'fixed_input_problem_resolution_percent':100,'accepted_status':'claimed_solved','author_turns':'4/5','original_head':clearance['original_head'],'accepted_head':merged['reviewed_head'],'actual_merge':merged['actual_merge'],'merged_at':merged['merged_at'],'zenodo_record':published['id'],'doi':published['doi'],'doi_url':published['doi_url'],'record_url':published['record_url'],'published_verified_utc':published['verified_utc'],'doi_resolves':True,'tracker_gid':tracker['gid'],'tracker_updated_range':tracker['updatedRange'],'tracker_exact_readback':True,'sealed_submission_files':clearance['sealed_submission_files'],'two_sequential_fresh_preprint_reviews_cleared':True,'root_full_exact_live_checks':root['check_count'],'root_full_postmerge_checks':post['check_count'],'all_public_metadata_and_download_bytes_verified':True,'historical_novelty_or_first_priority_certified':False,'external_human_peer_review_received':False,'extensive_AI_use_disclosed':True,'journal_submission':False,'GitHub_release':False,'no_person_contact_or_conversation_shared':True,'earlier_pending_records_are_immutable_dated_history':True,'git_checkpoint_state':'Ready for scoped commit and push of this final publication receipt'}
(A/'CURRENT_PUBLICATION_STATUS.json').write_text(json.dumps(status,indent=2)+'\n')
c=load(A/'acceptance_criteria.json');c.update(workflow_percent=100,workflow_completion_percent=100,actual_merge_pending=False,zenodo_publication_pending=False,tracker_pending=False,doi=published['doi'],zenodo_record=published['id'],tracker_updated_range=tracker['updatedRange'],current_publication_status='CURRENT_PUBLICATION_STATUS.json',root_complete_postmerge_scope_receipt='root_postmerge_scope_receipt.json')
(A/'acceptance_criteria.json').write_text(json.dumps(c,indent=2)+'\n')
inv=load(P/'inventory.json');row=next(x for x in inv['items'] if x['number']==367)
assert row['actual_merge']==merged['actual_merge'] and inv['completed_by_descending']==22
row.update(disposition='merged_claimed_solved_published_zenodo_tracker_verified',audit_workflow_percent=100,doi=published['doi'],zenodo_record=published['id'],tracker_updated_range=tracker['updatedRange'],current_publication_status='audits/pr367_11000151/CURRENT_PUBLICATION_STATUS.json')
(P/'inventory.json').write_text(json.dumps(inv,indent=2)+'\n')
(D/'README.md').write_text('# Verified preprint publication\n\nPublished version1.0: [Zenodo record23124601]('+published['record_url']+'), [DOI '+published['doi']+']('+published['doi_url']+'). The DOI resolves to the record with HTTP200. The six-page PDF and complete60-member source/verification ZIP are exactly the repaired bytes cleared by two sequential fresh adversarial reviewers. Every reviewed metadata key and both entire unauthenticated public downloads were independently compared; no metadata normalization or semantic change occurred.\n\nThe single authorized Google Workspace CLI append is independently read back at `Math Puzzles!A13:D13` on requested gid1254632077. It includes the exact problem identifier, DOI, title, author/ORCID, version/date, scope and review disclosures. The chat-URL cell is blank because no portable shared link was supplied and no conversation was shared. Full prior tracker rows and public-download duplicates remain private.\n\nActual merged PR367 is `'+merged['actual_merge']+'`; all43 original mathematical files and only own queue line400 cells8/9 agree with the accepted result. Extensive AI use and unrefereed/no-external-human-review status are disclosed. The fixed-generator classification is complete under both conventions: one/one/two strict classes at lengths20/30/40, giving three classes with simultaneous conjugation. Classical presentation, length-spectrum and Casson crossing credit are preserved; first priority and historical novelty are not certified. No journal submission, GitHub release or person contact occurred.\n\nEarlier dated85/93/95% clearance and acceptance receipts intentionally remain immutable historical records. `../CURRENT_PUBLICATION_STATUS.json` is the current100% outcome. `stage`, `inspect_draft`, `publish` and `inspect_published` outputs retain the actual single-deposition sequence. Publication used one POST with exact ID23124601, followed by read-only verification. The PDF/ZIP/metadata were not edited after review or upload.\n')
line='\n'+t+': PR367 COMPLETE: actual merge `'+merged['actual_merge']+'`, claimed_solved4/5, fixed-input resolution100%, workflow100%. Two fresh sequential preprint reviews cleared after global first-review repair; full4260 whole/4172 root exact-live checks,2863 whole/1170 root actual-post checks and all full outputs passed. Published exact PDF/ZIP/metadata as DOI `'+published['doi']+'`; DOI resolves200 and both whole public downloads match. Single GWS row '+tracker['updatedRange']+' exact-readback verified. Historical priority is not certified; AI extensive, unrefereed/no external human review. No journal/release/person contact. Descending22/349='+format(100*22/349,'.4f')+'%; PR8 remains excluded.\n'
for p in [A/'README.md',A/'RESEARCH_LOG.md',A/'ACCEPTANCE_DECISION.md',P/'RESEARCH_LOG.md']:
 with p.open('a') as f:f.write(line)
print(json.dumps({k:v for k,v in status.items() if k!='sealed_submission_files'},indent=2))
