#!/usr/bin/env python3
"""PR11 finite checks independent of both frozen checking implementations.

Input is explicit polynomial ideals. Groebner normal forms construct regular
representations and certify quotient dimensions. Rank uses SymPy DomainMatrix
over exact fields, and all exterior differentials are generated by the generic
boundary rule. Expected Betti vectors come from the separately documented ideal
certificates, not by rearranging the proposed rank identity. A matrix-only
evaluator enumerates spectra and filters candidates without decomposition.

Audited with Python 3.9.6; use Python 3.9–3.12 for the full pinned dependency
stack in adjacent requirements.txt. No all-future-Python compatibility claim.
Dependencies: SymPy 1.14.0, mpmath 1.3.0; NumPy 2.0.2 only for the expressly
noncertifying floating-point diagnostic. No author's checking code is imported.
"""
from datetime import datetime, timezone
from itertools import combinations, product
from math import comb
from pathlib import Path
import json
import sys

import sympy as sp
from sympy.polys.matrices import DomainMatrix

HERE = Path(__file__).resolve().parent
RANK_DOMAINS = set()

def exact_rank(matrix):
    if not matrix.rows or not matrix.cols:
        return 0
    domain_matrix = DomainMatrix.from_Matrix(matrix, extension=True).to_field()
    RANK_DOMAINS.add(str(domain_matrix.domain))
    assert not domain_matrix.domain.is_EX, 'rank must use an explicit exact field'
    return domain_matrix.rank()

def monomial(exponents, variables):
    return sp.prod(v**e for v,e in zip(variables, exponents))

def quotient(variables, generators):
    """Normal-form quotient construction; finite basis certified by pure LTs."""
    gb = sp.groebner(generators, *variables, order='lex', extension=True)
    assert gb.is_zero_dimensional
    lead = [p.monoms()[0] for p in gb.polys]
    bounds = []
    for j in range(len(variables)):
        powers = [e[j] for e in lead if e[j] and
                  all(i == j or e[i] == 0 for i in range(len(variables)))]
        assert powers, (variables, lead)
        bounds.append(min(powers))
    basis = sorted([e for e in product(*(range(b) for b in bounds))
                    if not any(all(a<=b for a,b in zip(l,e)) for l in lead)],
                   key=lambda e:(sum(e),e))
    indices = {e:i for i,e in enumerate(basis)}
    n = len(basis)
    matrices = []
    for x in variables:
        matrix = sp.zeros(n,n)
        for col,e in enumerate(basis):
            normal = gb.reduce(x*monomial(e,variables))[1]
            for f,c in sp.Poly(normal,*variables,extension=True).terms():
                assert f in indices, (normal,f,basis)
                matrix[indices[f],col] = c
        matrices.append(matrix)
    unit = sp.zeros(n,1)
    unit[indices[(0,)*len(variables)],0] = 1
    return {'variables':variables, 'generators':generators, 'gb':gb,
            'basis':basis, 'bounds':bounds, 'matrices':matrices, 'unit':unit}

def evaluate_polynomial(expression, variables, matrices):
    n = matrices[0].rows
    answer = sp.zeros(n,n)
    for e,c in sp.Poly(expression,*variables,extension=True).terms():
        value = sp.eye(n)
        for m,p in zip(matrices,e):
            value = value*(m**p)
        answer += c*value
    return answer.applyfunc(sp.simplify)

def cyclic_span(matrices, unit):
    """Certify one polynomial orbit spans the whole representation."""
    columns = [unit]
    dimension = 1
    frontier = [unit]
    while frontier:
        next_frontier = []
        for vector in frontier:
            for matrix in matrices:
                candidate = matrix*vector
                newdim = exact_rank(sp.Matrix.hstack(*(columns+[candidate])))
                if newdim > dimension:
                    columns.append(candidate)
                    next_frontier.append(candidate)
                    dimension = newdim
        frontier = next_frontier
    return dimension

def exterior_differentials(matrices, point):
    """All Koszul maps from the same generic exterior-boundary definition."""
    d,n = len(matrices),matrices[0].rows
    shifts = [m-v*sp.eye(n) for m,v in zip(matrices,point)]
    result = []
    for p in range(1,d+1):
        source = list(combinations(range(d),p))
        target = list(combinations(range(d),p-1))
        index = {w:i for i,w in enumerate(target)}
        differential = sp.zeros(len(target)*n,len(source)*n)
        for col,wedge in enumerate(source):
            for r,variable in enumerate(wedge):
                row = index[wedge[:r]+wedge[r+1:]]
                differential[row*n:(row+1)*n,col*n:(col+1)*n] = (-1)**r*shifts[variable]
        result.append(differential)
    for a,b in zip(result,result[1:]):
        assert (a*b).applyfunc(sp.simplify) == sp.zeros(a.rows,b.cols)
    return result

def full_betti(matrices,point):
    d,n = len(matrices),matrices[0].rows
    maps = exterior_differentials(matrices,point)
    ranks = [0]+[exact_rank(m) for m in maps]+[0]
    betti = [comb(d,p)*n-ranks[p]-ranks[p+1] for p in range(d+1)]
    return betti,ranks[1:-1]

def spectra_filter(matrices):
    """The tested evaluator takes matrices only; no ideal/decomposition input."""
    spectra = [sorted(m.eigenvals().keys(),key=sp.default_sort_key) for m in matrices]
    accepted = []
    rejected = []
    n = matrices[0].rows
    for point in product(*spectra):
        first = sp.Matrix.hstack(*(m-v*sp.eye(n) for m,v in zip(matrices,point)))
        rank = exact_rank(first)
        (accepted if rank < n else rejected).append((point,rank))
    return spectra,accepted,rejected

def conjugator(n):
    s = sp.eye(n)
    for i in range(n-1):
        s[i,i+1] = sp.Rational(i+1,17)
    for i in range(n-2):
        s[i,i+2] = -1
    assert s.det() == 1
    return s

def encode_point(point):
    return [str(v) for v in point]

def check_case(name, matrices, unit, support, expected_length, certificates,
               quotient_data=None):
    d,n = len(matrices),matrices[0].rows
    assert n == expected_length
    assert all(m.rows == m.cols == n for m in matrices)
    assert all(a*b == b*a for a,b in combinations(matrices,2))
    assert cyclic_span(matrices,unit) == n
    spectra,accepted,rejected = spectra_filter(matrices)
    actual = {tuple(map(sp.simplify,p)) for p,r in accepted}
    assert actual == set(support), (name,actual,set(support))
    assert all(r == n-1 for p,r in accepted)
    s = conjugator(n)
    changed = [s*m*s.inv() for m in matrices]
    points = []
    for point,expected_betti in support.items():
        betti,ranks = full_betti(matrices,point)
        assert betti == expected_betti, (name,point,betti,expected_betti)
        mu = expected_betti[1]
        second_rank = ranks[1] if d > 1 else 0
        assert (d-1)*n+1-second_rank == mu
        assert (second_rank == (d-1)*(n-1)) == (mu == d)
        changed_maps = exterior_differentials(changed,point)
        assert [exact_rank(m) for m in changed_maps[:2]] == ranks[:2]
        points.append({'point':encode_point(point),'rank_D1':ranks[0],
            'rank_D2':second_rank,'full_differential_ranks':ranks,
            'betti_vector':betti, 'independently_certified_local_mu':mu,
            'CI_target_using_global_N':(d-1)*(n-1),
            'is_CI_at_point':mu == d, 'conjugation_D1_D2_invariant':True})
    outside = tuple(sp.Integer(101+j) for j in range(d))
    outside_betti,outside_ranks = full_betti(matrices,outside)
    assert outside_betti == [0]*(d+1)
    payload = {'name':name,'d':d,'length':n,'certificate_routes':certificates,
        'regular_representation_cyclic_dimension':n,
        'individual_spectra':[encode_point(s) for s in spectra],
        'cartesian_candidates':len(accepted)+len(rejected),
        'accepted_points':len(accepted),'rejected_false_combinations':len(rejected),
        'points':points,'outside_point':encode_point(outside),
        'outside_betti':outside_betti,'outside_differential_ranks':outside_ranks}
    if quotient_data:
        q=quotient_data
        for relation in q['generators']:
            assert evaluate_polynomial(relation,q['variables'],matrices) == sp.zeros(n,n)
        payload['polynomial_ideal'] = [str(g) for g in q['generators']]
        payload['groebner_basis'] = [str(p.as_expr()) for p in q['gb'].polys]
        payload['standard_monomial_basis'] = [str(monomial(e,q['variables'])) for e in q['basis']]
        payload['pure_leading_power_bounds'] = q['bounds']
        if len(support) == 1:
            point = next(iter(support))
            nilpotent = [m-v*sp.eye(n) for m,v in zip(matrices,point)]
            assert all(t**n == sp.zeros(n,n) for t in nilpotent)
            payload['nonzero_nilpotent_coordinates'] = [j for j,t in enumerate(nilpotent)
                                                      if t != sp.zeros(n,n)]
            payload['socle_dimension'] = n-exact_rank(sp.Matrix.vstack(*nilpotent))
    return payload

def product_representations(components):
    d = len(components[0][0]['matrices'])
    matrices = []
    for j in range(d):
        blocks = [q['matrices'][j]+shift[j]*sp.eye(q['matrices'][j].rows)
                  for q,shift in components]
        matrices.append(sp.diag(*blocks))
    unit = sp.Matrix.vstack(*(q['unit'] for q,shift in components))
    return matrices,unit

def main():
    results=[]
    def add(name,variables,generators,support,n,certificate):
        q=quotient(variables,generators)
        results.append(check_case(name,q['matrices'],q['unit'],support,n,certificate,q))
        print('PASS '+name,flush=True)
        return q
    x,y,z,s,t=sp.symbols('x y z s t')
    add('d1_nonreduced_plus_algebraic_reduced_supports',(x,),[x**4+x**2],
        {(sp.Integer(0),):[1,1],(sp.I,):[1,1],(-sp.I,):[1,1]},4,
        ['principal ideal; multiplicities 2,1,1 in x²(x²+1)'])
    add('d2_hidden_redundant_cubic_relation',(x,y),[x**2-y**3,x*y,y**4],
        {(0,0):[1,2,1]},5,
        ['y(x²-y³)-x(xy)=-y⁴; two-generator height-two CI'])
    k = add('d2_nonhomogeneous_nonmonomial_nonCI',(x,y),[x**4,x*y-x**3,y**2],
        {(0,0):[1,3,2]},5,
        ['triangular automorphism of (a⁴,ab,b²); explicit Hilbert–Burch resolution'])
    j = add('d3_Gorenstein_nonCI_cross_quadric',(x,y,z),
        [x**2,y**2,x*z,y*z,z**2-x*y],{(0,0,0):[1,5,5,1]},5,
        ['five independent quadratic minimal generators; length5 socle1; graded Gorenstein resolution'])
    add('d3_Gorenstein_nonCI_equal_squares',(x,y,z),
        [x**2-y**2,x**2-z**2,x*y,x*z,y*z],{(0,0,0):[1,5,5,1]},5,
        ['five independent quadrics; length5 socle1; graded Gorenstein resolution'])
    c = add('d3_triangular_nonlinear_CI',(x,y,z),
        [x**3,(y-x**2)**2,z-x*y],{(0,0,0):[1,3,3,1]},6,
        ['polynomial coordinates a=x,b=y-x²,c=z-xy; ideal (a³,b²,c)'])
    add('d4_tensor_nonlinear_nonCI',(x,y,s,t),
        [x**4,x*y-x**3,y**2,s**2,t**2],{(0,0,0,0):[1,5,9,7,2]},20,
        ['Hilbert–Burch K tensored with Koszul (s²,t²); minimal resolution'])
    add('d5_tensor_Gorenstein_nonCI',(x,y,z,s,t),
        [x**2,y**2,x*z,y*z,z**2-x*y,s**2,t**2],
        {(0,0,0,0,0):[1,7,16,16,7,1]},20,
        ['Gorenstein J tensored with Koszul (s²,t²); minimal resolution'])
    variables=sp.symbols('a0:5')
    add('d5_square_zero',(variables),[a*b for a,b in combinations(variables,2)]+
        [a*a for a in variables],{(0,)*5:[1,15,40,45,24,5]},6,
        ['all 15 degree-two monomials minimal; linear resolution of S/m²'])
    variables=sp.symbols('b0:6')
    add('d6_curvilinear_nonlinear_embedding',variables,
        [variables[i]-variables[0]**(i+1) for i in range(1,6)]+[variables[0]**7],
        {(0,)*6:[comb(6,i) for i in range(7)]},7,
        ['triangular polynomial automorphism of (b0⁷,b1,…,b5); Koszul resolution'])
    add('d2_algebraic_support_nonreduced',(x,y),[x**2-2,y**2],
        {(sp.sqrt(2),0):[1,2,1],(-sp.sqrt(2),0):[1,2,1]},4,
        ['two-point split over Q(sqrt2); local ideals (x±sqrt2,y²)'])
    add('d2_four_algebraic_reduced_points',(x,y),[x**2-2,y**2+1],
        {(a,b):[1,2,1] for a in (sp.sqrt(2),-sp.sqrt(2)) for b in (sp.I,-sp.I)},4,
        ['separable product; four reduced points; CI ideal of two independent univariate equations'])
    add('d2_algebraic_coefficients_and_support',(x,y),[x**2-sp.sqrt(2),y**2],
        {(2**sp.Rational(1,4),0):[1,2,1],(-2**sp.Rational(1,4),0):[1,2,1]},4,
        ['effective algebraic coefficient field; simple x roots and double y root'])
    # Four distinct first coordinates give explicit CRT separation, independent
    # of the spectrum-filter routine. Each block itself is a certified quotient.
    k3=quotient((x,y,z),[x**4,x*y-x**3,y**2,z])
    reduced=quotient((x,y,z),[x,y,z])
    mixed,unit=product_representations([(k3,(0,0,0)),(j,(-2,3,5)),
                                      (c,(2,-1,4)),(reduced,(7,-1,4))])
    results.append(check_case('d3_four_support_mixed_global_N17',mixed,unit,
        {(0,0,0):[1,4,5,2],(-2,3,5):[1,5,5,1],
         (2,-1,4):[1,3,3,1],(7,-1,4):[1,3,3,1]},17,
        ['CRT product separated by four distinct x coordinates; local resolutions certified separately']))
    print('PASS d3_four_support_mixed_global_N17',flush=True)
    # Outside-scope falsifier: dual of the plane square-zero regular module.
    qbad=quotient((x,y),[x**2,x*y,y**2])
    dual=[m.T for m in qbad['matrices']]
    bad_betti,bad_ranks=full_betti(dual,(0,0))
    assert bad_ranks == [1,2]
    assert bad_ranks[1] == (2-1)*(3-1)
    assert bad_ranks[0] != 3-1
    assert all(evaluate_polynomial(g,(x,y),dual)==sp.zeros(3,3)
               for g in qbad['generators'])
    # Faithful dual has the same annihilator because polynomial evaluation
    # transposes; I, X, Y are independent in the original and in the dual.
    assert exact_rank(sp.Matrix.hstack(*(m.reshape(9,1) for m in [sp.eye(3)]+dual))) == 3
    dual_guard={'tuple':'transposed regular matrices of Q[x,y]/(x,y)²',
        'annihilator_mu':3,'annihilator_is_CI':False,'N':3,
        'rank_D1':bad_ranks[0],'rank_D2':bad_ranks[1],
        'CI_rank_target':2,'D2_only_false_positive_outside_scope':True,
        'failed_regular_support_rank':True,'betti_for_dual_module':bad_betti}
    # Exact perturbation family in a fixed basis 1,x,y. Relations are
    # x²=xy=0, y²=epsilon*x. Every tuple is regular and has length three.
    eps_values=[sp.Integer(0),sp.Integer(1),sp.Rational(1,10**18)]
    perturbation=[]
    for eps in eps_values:
        mx=sp.Matrix([[0,0,0],[1,0,0],[0,0,0]])
        my=sp.Matrix([[0,0,0],[0,0,eps],[1,0,0]])
        unit=sp.Matrix([1,0,0])
        assert cyclic_span([mx,my],unit)==3
        assert mx**2 == mx*my == my*mx == sp.zeros(3,3)
        assert my**2 == eps*mx
        b,r=full_betti([mx,my],(0,0))
        assert b == ([1,3,2] if eps==0 else [1,2,1])
        q=quotient((x,y),[x**2,x*y,y**2-eps*x])
        assert len(q['basis'])==3
        columns=[]
        for e in [(0,0),(1,0),(0,1)]:
            columns.append(evaluate_polynomial(monomial(e,(x,y)),(x,y),q['matrices'])*q['unit'])
        basis_change=sp.Matrix.hstack(*columns)
        assert basis_change.det()!=0
        assert all(basis_change*m == qm*basis_change
                   for m,qm in zip([mx,my],q['matrices']))
        perturbation.append({'epsilon':str(eps),'rank_D1':r[0],'rank_D2':r[1],
                            'local_mu':b[1],'is_CI':eps!=0})
    import numpy as np
    numerical_matrix=exterior_differentials([mx,my],(0,0))[1]
    singular=np.linalg.svd(np.array(numerical_matrix.tolist(),dtype=float),compute_uv=False)
    numerical={'epsilon':'1/10^18','singular_values':singular.tolist(),
               'numpy_default_rank':int(np.linalg.matrix_rank(np.array(numerical_matrix.tolist(),dtype=float))),
               'exact_rank':2,'scope':'Noncertifying floating-point diagnostic only'}
    assert numerical['numpy_default_rank'] != numerical['exact_rank']
    # Misusing a component length in the full-matrix target can give a false
    # positive at a non-CI point. Global N=4, local length3, d2 rank2.
    point=quotient((x,y),[x,y])
    misuse,m_unit=product_representations([(qbad,(0,0)),(point,(2,3))])
    b,r=full_betti(misuse,(0,0))
    assert r[:2]==[3,2] and b[1]==3
    global_N_guard={'global_N':4,'component_length':3,'d':2,
        'rank_D2_at_nonCI_component':2,'correct_global_target':3,
        'incorrect_component_target':2,'incorrect_target_false_positive':True}
    payload={'timestamp_utc':datetime.now(timezone.utc).isoformat(),
        'scope':'Finite exact validation and scope falsifiers; not a proof of the arbitrary-d,N global theorem.',
        'python':sys.version,'sympy_version':sp.__version__,
        'numpy_version':np.__version__,'rank_fields':sorted(RANK_DOMAINS),
        'case_count':len(results),'cases':results,'dual_module_scope_guard':dual_guard,
        'fixed_basis_exact_perturbation_family':perturbation,
        'numerical_rank_diagnostic':numerical,'global_N_misuse_guard':global_N_guard,
        'passes':True}
    (HERE/'independent_quotient_results.json').write_text(json.dumps(payload,indent=2)+'\n')
    print('PASS '+str(len(results))+' exact ideal-derived cases plus scope/instability guards',flush=True)

if __name__ == '__main__':
    main()
