#!/usr/bin/env python3
"""Clean-room symbolic bookkeeping audit for the mixed-P4 rank recurrence.

This script does not import the candidate or any campaign evaluator.  It
checks the finite set identities, mover tables, rank arithmetic, named-target
rows, and the direction of every C-145 use in the frozen candidate.
"""

from __future__ import annotations

import hashlib
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
CANDIDATE = ROOT / "math/working/family_mixed_p4_rank_recurrence"


def canon(state: set[str] | frozenset[str]) -> str:
    return "{" + ",".join(sorted(state)) + "}"


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def main() -> None:
    anchors = frozenset({"a", "b", "c"})
    path = ("x0", "x1", "x2", "x3")
    lists = {
        "x0": frozenset({"a"}),
        "x1": frozenset({"a", "c"}),
        "x2": frozenset({"b", "c"}),
        "x3": frozenset({"b"}),
    }

    # Positive roles are graph edges.  C-070 supplies the two endpoint
    # c-edges.  No negative role is entered as a graph nonedge.
    anchor_path_edges = {
        frozenset((guard, target))
        for target, guards in lists.items()
        for guard in guards
    }
    anchor_path_edges |= {
        frozenset(("c", "x0")),
        frozenset(("c", "x3")),
    }
    root_degrees = {
        target: sum(
            frozenset((guard, target)) in anchor_path_edges for guard in anchors
        )
        for target in path
    }
    assert root_degrees == {"x0": 2, "x1": 2, "x2": 2, "x3": 2}

    # A ridge exchange S -> S-g+r has the same exchanged successor
    # C+{x}.  Its membership alone is insufficient for a response role:
    # domination of the opposite exchanged vertex supplies the missing
    # x-r or x-g edge.  This records the exact C-064 step the candidate
    # must cite or prove.
    shared = frozenset({"v", "w"})
    ridge_transport = {
        "source": canon(set(shared) | {"g"}),
        "target": canon(set(shared) | {"r"}),
        "common_successor": canon(set(shared) | {"x"}),
        "forward_edge_forced_by_domination_of": "r",
        "reverse_edge_forced_by_domination_of": "g",
    }
    assert set(shared).isdisjoint({"g", "r", "x"})

    # Exact integer consequence used in Theorem 3.1.
    rank_rows = []
    for h in range(1, 33):
        allowed = [
            rank
            for rank in range(0, h)
            if abs(h - rank) <= 1
        ]
        assert allowed == [h - 1]
        rank_rows.append({"h": h, "forced_successor_rank": allowed[0]})

    # Named-target audit for Q0.  The reflected Q3 rows are generated by
    # the displayed involution rather than independently assumed.
    q0 = frozenset({"a", "b", "x0"})
    q3 = frozenset({"a", "b", "x3"})
    named_q0 = {
        "x1": {
            "auxiliary_source": canon({"b", "c", "x0"}),
            "retained_successor": canon({"b", "x0", "x1"}),
            "restoration_rejected": canon({"c", "x0", "x1"}),
            "missing_anchors": ["a", "b"],
            "available_restoration_roles": ["a", "c"],
        },
        "x2": {
            "mover": "x0",
            "retained_successor": canon({"a", "b", "x2"}),
        },
        "x3": {
            "mover": "x0",
            "successor": canon(q3),
            "conclusion": "opposite-endpoint strict rank descent",
        },
    }
    assert (
        set(named_q0["x1"]["missing_anchors"])
        - set(named_q0["x1"]["available_restoration_roles"])
        == {"b"}
    )
    assert frozenset({"a", "b", "x2"}) == anchors - {"c"} | {"x2"}
    assert q0 - {"x0"} | {"x3"} == q3

    reflection = {
        "a": "b",
        "b": "a",
        "c": "c",
        "x0": "x3",
        "x1": "x2",
        "x2": "x1",
        "x3": "x0",
    }
    assert {reflection[v] for v in q0} == set(q3)
    assert all(reflection[reflection[v]] == v for v in reflection)

    # Fresh multi-hit table.  Root is {c,l,m}, endpoint state {u,l,m}.
    s = frozenset({"c", "l", "m"})
    q = frozenset({"u", "l", "m"})
    root_neighborhoods = (
        frozenset({"c", "l"}),
        frozenset({"c", "m"}),
        frozenset({"l", "m"}),
        s,
    )
    expected_movers = {
        (frozenset({"c", "l"}), False): frozenset({"l"}),
        (frozenset({"c", "m"}), False): frozenset({"m"}),
        (frozenset({"c", "l"}), True): frozenset({"u", "l"}),
        (frozenset({"c", "m"}), True): frozenset({"u", "m"}),
        (frozenset({"l", "m"}), False): frozenset({"l", "m"}),
        (frozenset({"l", "m"}), True): frozenset({"u", "l", "m"}),
        (s, False): frozenset({"l", "m"}),
        (s, True): frozenset({"u", "l", "m"}),
    }

    cells = []
    for neighborhood in root_neighborhoods:
        for ur in (False, True):
            movers = (neighborhood & q) | ({"u"} if ur else set())
            movers = frozenset(movers)
            assert movers == expected_movers[(neighborhood, ur)]
            successors = {
                mover: canon(set(q) - {mover} | {"r"}) for mover in movers
            }
            cells.append(
                {
                    "root_neighborhood": sorted(neighborhood),
                    "ur": ur,
                    "movers": sorted(movers),
                    "successors": successors,
                }
            )
    assert len(cells) == 8

    # Direction and common-nonneighbor audits for all C-145 applications.
    c145_uses = [
        {
            "cell": ["c", "m"],
            "ur": False,
            "forward": "l▷u",
            "hypothetical_missing_reverse": "u▷l",
            "common_nonneighbor": "r",
            "forced_ridge": canon({"l", "u", "r"}),
            "candidate_successor": canon(q - {"m"} | {"r"}),
        },
        {
            "cell": ["c", "g"],
            "ur": True,
            "forward": "g▷r",
            "hypothetical_missing_reverse": "r▷g",
            "common_nonneighbor": "q",
            "forced_ridge": canon({"g", "r", "q"}),
            "candidate_successor": canon({"g", "q", "r"}),
        },
        {
            "cell": ["l", "m"],
            "ur": "either",
            "forward": "g▷r",
            "hypothetical_missing_reverse": "r▷g",
            "common_nonneighbor": "c",
            "forced_ridge": canon({"c", "g", "r"}),
            "candidate_successor": canon({"c", "g", "r"}),
        },
    ]
    assert c145_uses[0]["forced_ridge"] == c145_uses[0]["candidate_successor"]
    assert c145_uses[1]["forced_ridge"] == c145_uses[1]["candidate_successor"]
    assert c145_uses[2]["forced_ridge"] == c145_uses[2]["candidate_successor"]

    # Outer-collision completion alternative.  These are the exact
    # set-theoretic consequences; the script does not pretend to certify
    # the universal graph argument computationally.
    completion_audit = {
        "outer_collision": ["l", "m"],
        "missed_pair": ["c", "r"],
        "empty_completion_set_equivalent_to": "{c,r} dominates",
        "two_nonadjacent_completions_would_create_independent_4_set": [
            "c",
            "r",
            "w",
            "w'",
        ],
        "completion_missing_both_anchors_would_create_independent_4_set": [
            "c",
            "l",
            "m",
            "w",
        ],
        "ridge_for_missing_l": {
            "states": [canon({"c", "l", "w"}), canon({"c", "r", "w"})],
            "conclusion": "r↔l",
        },
        "ridge_for_missing_m": {
            "states": [canon({"c", "m", "w"}), canon({"c", "r", "w"})],
            "conclusion": "r↔m",
        },
    }

    candidate_hashes = {
        name: sha256(CANDIDATE / name)
        for name in ("NOTE.md", "OBSERVED_RESULTS.json", "RESEARCH_LOG.md")
    }

    result = {
        "schema": "family-mixed-p4-rank-recurrence-hostile-bookkeeping-v1",
        "verdict": "PASS_BOOKKEEPING_ONLY",
        "candidate_hashes": candidate_hashes,
        "root_neighbor_counts": root_degrees,
        "ridge_transport": ridge_transport,
        "rank_rows": rank_rows,
        "named_q0": named_q0,
        "reflection": reflection,
        "multi_hit_cells": cells,
        "c145_uses": c145_uses,
        "completion_audit": completion_audit,
        "guardrail": (
            "Only positive response roles were entered as graph edges; "
            "no omitted family response was entered as a graph nonedge."
        ),
        "scope": (
            "This checks finite bookkeeping and rank arithmetic.  The "
            "universal implications remain proof claims audited in REVIEW.md."
        ),
    }
    print(json.dumps(result, indent=2, sort_keys=True))


if __name__ == "__main__":
    main()
