#!/usr/bin/env python3
"""Exact adversarial mutations for the independent analytic review."""

from __future__ import annotations

import argparse
import hashlib
import importlib.util
import json
import sys
from fractions import Fraction as F
from pathlib import Path


HERE = Path(__file__).resolve().parent
VERIFY = HERE / "verify_adversarial.py"


def load_audit():
    spec = importlib.util.spec_from_file_location("k2p_adversarial_audit", VERIFY)
    if spec is None or spec.loader is None:
        raise RuntimeError("cannot load verifier")
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


def canonical_bytes(value: object) -> bytes:
    return json.dumps(value, sort_keys=True, separators=(",", ":")).encode()


def main() -> int:
    if not __debug__:
        raise RuntimeError("mutation audit disabled under Python -O")
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", type=Path)
    args = parser.parse_args()
    audit = load_audit()
    tests = []

    def rejected(name: str, condition: bool, witness: str) -> None:
        if not condition:
            raise RuntimeError(f"mutation survived: {name}")
        tests.append({"name": name, "rejected": True, "witness": witness})

    rejected(
        "close_strict_stochastic_facet",
        not audit.in_dplus(F(3, 4), F(1, 2)),
        "g=2s-1 is outside the strict domain",
    )
    rejected(
        "declare_unmarked_degree_two_free",
        audit.matrix_rank([[1, 1]]) < 2,
        "the exponent kernel is generated by (1,-1)",
    )

    # Omitting G from the serial threshold can make the last g coordinate exceed one.
    S, G, R = F(1, 5), F(9, 10), F(1, 2)
    rejected(
        "serial_threshold_omit_G",
        not audit.in_dplus(S / R, G / R),
        "(S,G,R)=(1/5,9/10,1/2) gives G/R=9/5",
    )
    # Omitting 2S-G can violate the stochastic facet after division.
    S, G, R = F(9, 10), F(81, 100), F(19, 20)
    rejected(
        "serial_threshold_omit_2S_minus_G",
        not audit.in_dplus(S / R, G / R),
        "R=19/20 exceeds S and G but not 2S-G=99/100",
    )
    rejected(
        "serial_threshold_allow_equality",
        not audit.in_dplus(F(1, 5) / F(9, 10), F(9, 10) / F(9, 10)),
        "R=G puts the last g coordinate on g=1",
    )

    # Omitting either incidence-product upper bound breaks physical gluing.
    A, B = F(1, 10), F(1)
    rejected(
        "D_plus_gluing_omit_A_bound",
        not audit.in_dplus(F(1, 4) / A, F(1, 3) / B),
        "s/A=5/2",
    )
    A, B = F(1), F(1, 10)
    rejected(
        "D_plus_gluing_omit_B_bound",
        not audit.in_dplus(F(1, 4) / A, F(1, 3) / B),
        "g/B=10/3",
    )
    A, B, s, g = F(1, 10), F(1), F(1, 20), F(1, 100)
    rejected(
        "CT_gluing_omit_B_over_A_squared_lower_bound",
        audit.in_ct(s, g) and not audit.in_ct(s / A, g / B),
        "the source is CT but the transformed pair has (s,g)=(1/2,1/100)",
    )

    lift = audit.check_unconditional_lift_counterexample()
    rejected(
        "unconditional_selected_marginal_lift",
        lift["status"] == "COUNTEREXAMPLE_CONFIRMED",
        "equal open selected projections but restored intersection only at a=1/2",
    )

    rejected(
        "quartet_positivity_allow_internal_identity",
        F(1) - F(1) == 0,
        "the crossing-tree witness factor 1-a vanishes at the excluded boundary a=1",
    )
    rejected(
        "quartet_positivity_allow_zero_switch_weight",
        F(0) * (F(1) - F(1, 2)) == 0,
        "a displayed switching with zero inheritance weight contributes no strict sign",
    )

    S, G = F(9, 10), F(81, 100)
    M = max(S, G, 2 * S - G, F(0))
    bad_r = F(19, 20)
    rejected(
        "physical_saturation_split_below_threshold",
        bad_r * bad_r <= M
        and not audit.in_dplus(S / (bad_r * bad_r), G / (bad_r * bad_r)),
        "r^2=361/400 is below M=99/100, so the residual factor crosses the stochastic facet",
    )

    report: dict[str, object] = {
        "schema": "k2p-adversarial-analytic-mutations-v1",
        "status": "PASS",
        "passed": len(tests),
        "tests": tests,
    }
    report["payload_sha256"] = hashlib.sha256(canonical_bytes(report)).hexdigest()
    if args.output:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(json.dumps(report, sort_keys=True, indent=2) + "\n")
    print(json.dumps(report, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
