"""Record checked actual/post-merge outcome, retaining all historical phases."""
from pathlib import Path
from datetime import datetime,timezone
import hashlib,json
A=Path(__file__).resolve().parent;P=A.parents[1];sha=lambda b:hashlib.sha256(b).hexdigest()
r=json.loads((A/'root_postmerge_verification_receipt.json').read_bytes());assert r['status']=='PASS_ENTIRE_POSTMERGE_EVIDENCE_AND_REEXECUTION' and r['check_count']==1140
assert r['manifest_files']==99 and r['manifest_sha256']=='55c60a61723775553ab221c9261bb06d57efdfafe630ec36c2f86a38a8a905d2'
assert len(r['all88_command_reexecutions'])==88 and len(r['extra_current_commands'])==28
now=datetime.now(timezone.utc).isoformat()
c=json.loads((A/'acceptance_criteria.json').read_bytes());c.update({'workflow_completion_percent':100,'workflow_percent':100,'post_merge_verification_pending':False,'root_post_merge_checks':1140,'whole_post_merge_assertions':635,'whole_post_merge_commands':88,'closed_post_merge_manifest':r['manifest_sha256'],'root_post_merge_receipt_sha256':sha((A/'root_postmerge_verification_receipt.json').read_bytes()),'fresh_descendant_main':r['refreshed_main'],'audit_artifact_publication_pending':True,'final_review_completion_utc':now})
(A/'acceptance_criteria.json').write_text(json.dumps(c,indent=2)+'\n')
o=json.loads((P/'inventory.json').read_bytes());assert o['completed_by_descending']==23
e=next(e for e in o['items'] if e['number']==366);e.update({'audit_completion_percent':100,'audit_workflow_percent':100,'audit_disposition':'PASS_SOURCE_MATH_PRIORITY_LIMITS_REPRODUCTION_PREPARED_ACTUAL_AND_POSTMERGE','post_merge_independently_verified':True,'root_post_merge_checks':1140,'post_merge_public_manifest':r['manifest_sha256'],'credited_method_resolution_percent':100,'novel_original_problem_resolution_claimed':False,'final_review_completion_utc':now,'audit_artifact_publication_pending':True})
(P/'inventory.json').write_text(json.dumps(o,indent=2)+'\n')
text=f'''{now}: PR366 FINAL REVIEW COMPLETE100%, credited direct-method resolution100%, novel theorem0%. Actual merge `{r['actual_merge']}` preserves all21 source/proof/code/review files; complete1966-line queue only406 cells8/9, already_solved1/5. Independent post review635 assertions/all88 full commands/43 remote contents, all48 nested bindings, earlier228 sealed public files and new99-file manifest `{r['manifest_sha256']}` PASS. ROOT fully read all post programs/reports, verified all99 whole artifacts, reexecuted all88 readonly commands and independently checked28 additional current-main commands,1140 checks PASS. Two stopped ROOT comparisons are preserved: literal main advanced to a single-parent unrelated research checkpoint; then two repo.updated_at timestamps changed. Final whole comparison allows only enumerated typed repo metadata and explicit descendant main ref/SHA/URL observations, with every22 current HEAD/worktree file and entire descendant changed-path set checked. Original99 and194-file namespaces unchanged. The broad negative label was honestly clarified and a literal target-row negative added. Real ENOSPC preparation failures remain distinct from mathematical checks; safe completed-own private PDF dedup preserves every byte/path. Ordinary Borel capacitability/polar equivalence remain explicit foundations; source historical dataset revision is unavailable locally and no exhaustive historical-ref, novelty, or nonintegrable-gauge certificate is asserted. No essential accepted-claim gap, paper, Zenodo, DOI, tracker row, release, journal, or external-person communication. Program23/349=6.5903%; final audit commit/push prepared next, receipt will record observed publication rather than guess it.\n'''
for name in ['DECISION.md','ACCEPTANCE_DECISION.md','README.md','RESEARCH_LOG.md']:
 with (A/name).open('a') as f:f.write('\n'+text)
with (P/'RESEARCH_LOG.md').open('a') as f:f.write('\n'+text)
(A/'CURRENT_ACCEPTANCE_STATUS.md').write_text('# Current PR366 accepted outcome\n\n'+text+'\nEarlier provisional percentages and pending records are historical. This current record supersedes them for mathematical/integration review; the final audit publication receipt is a separate observed event.\n')
print(json.dumps({'status':'FINAL_REVIEW_COMPLETE_FINAL_AUDIT_PUBLICATION_PENDING','utc':now,'program_completed':23,'program_total':349,'root_checks':1140}))
