#!/usr/bin/env python3
"""Write original audit metadata, without public copies of private primary bodies."""
from pathlib import Path
import os, datetime, json, hashlib
W=Path(__file__).resolve().parent
utc=datetime.datetime.now(datetime.timezone.utc).isoformat()
def write(name,d):
    (W/name).write_text(json.dumps(d,indent=2,ensure_ascii=False)+'\n')
queries=[
    '"k603" "antipedal"','"k_{603}"','"antipedal" "foci" invariant proof','"Eighty New Invariants" antipedal proof',
    'Reznik billiard invariants k603 GitHub','"antipedal" "billiard" "proof"','"antipedal" "sum" "foci"','"focal antipedal"',
    'site:eulersolve.org/papers/amr-050-0032','"antipedal" "distance" "2025" billiard','"antipedal" "k603" proof',
    '"Equal sum of distances" "Antipedal" proof','"Reznik" "invariants" "antipedal" -site:researchgate.net -site:eulersolve.org -site:scribd.com',
    '"k603" billiard -site:researchgate.net','"k_{603}" billiard -site:researchgate.net','"New Invariants" "Poncelet" antipedal',
    '"Reznik" "antipedal" "2022"','"Reznik" "antipedal" "2023"','"Reznik" "antipedal" "2024"','"Reznik" "antipedal" "2025"',
    '"Garcia" "Billiards" "33" "colloquium" pdf','"33CBM06" pdf','"New Invariants of Poncelet Polygons" Garcia Koiller Reznik',
    '"k603" site:arxiv.org','"Discovering Poncelet invariants in the plane" pdf','"33CBM06" "impa"','"978-65-89124-43-6"',
    '"Estimating elliptic billiard invariants with spatial integrals" antipedal','"Average Elliptic Billiard Invariants" arxiv',
    '"k603" "proof" ellipse -site:researchgate.net','"antipedal" "foci" "equal" ellipse -site:researchgate.net -site:scribd.com',
    '"33CBM06-eBook.pdf"','"Discovering Poncelet" filetype:pdf -site:scribd.com','"Poncelet Surprises" pdf',
    '"antipedal" "focal" "telescoping"','ellipse billiard "circumradii" foci sum','ellipse billiard "circumradius" "focus" sum',
    '"antipedal" "focal" invariant proof ellipse -site:researchgate.net -site:scribd.com','"antipedal" "k_603"',
    '"When Grünbaum meets Poncelet" "2026" arxiv','"When Grünbaum meets Poncelet" configurations pdf'
]
write('QUERY_LOG.json',{'schema':'pr110-exact-history-web-query-log/v1','written_UTC':utc,'actual_writer_PID':os.getpid(),
    'retrieval_date_UTC':'2026-10-06','per_query_OS_PID':None,'per_query_exact_UTC':None,
    'timestamp_limit':'Browser tools expose neither an OS PID nor exact per-query UTC. These are actual literal queries from the audit tool calls; the date is honest calendar retrieval date, not a fabricated precision timestamp.',
    'queries':queries,'query_count':len(queries),
    'mathematical_evidence_policy':'Only inspected primary source statements support mathematical comparisons. Secondary search results and OpenAlex were discovery only.',
    'overall_search_result':'No full exact k603 proof located. Found original source, author ledgers/book, current 2026 neighboring centroid/area notes and generic Poncelet citation follow-ups. Negative discovery does not prove global absence.'})

sources=[
    {'id':'source_arxiv_v11','url':'https://arxiv.org/abs/2004.12497v11','private_text':'private_review_materials/arxiv_source_v11.txt','read_boundary':'Freshly read §§3.5–3.7 and Table7 (text lines318–435). Complete body keyword-screened; root full-source reading not falsely counted as this family full reading. Current abs submission history fully read; bodiesv1–v10 not downloaded.','mapping':'Literal k603 target, observation with question-mark proof field in2020.'},
    {'id':'source_published2021','DOI':'10.1007/s40598-021-00174-y','private_text':'private_review_materials/source_published2021.txt','read_boundary':'Freshly read §§3.5–3.7 and Tables5–7, especially p349 (text lines332–466). Complete body keyword-screened; not represented as fresh full-paper reading.','mapping':'Exact historical k603 remains unproved entry; not a present2026 certificate.'},
    {'id':'self_intersected_arxiv_v3','url':'https://arxiv.org/abs/2011.06640v3','private_text':'private_review_materials/self_intersected_v3.txt','read_boundary':'Main body text lines1–650 read. Later low-N algebraic appendices not fully read; whole extraction keyword-screened.','mapping':'Selected low-N invariants/geometry; no general603 theorem identified.'},
    {'id':'self_intersected_published2022','DOI':'10.33039/ami.2022.02.001','url':'https://ami.uni-eszterhazy.hu/uploads/papers/finalpdf/AMI_55_from49to75.pdf','private_text':'private_review_materials/published_self_intersected2022.txt','read_boundary':'Whole extraction keyword-screened and final Table1 lines263–319 read directly. Not a full reread of final1323-line body.','mapping':'Final selected invariant table still excludes603; selected low-N derivations are not covering proof.'},
    {'id':'inversive_v2','url':'https://arxiv.org/abs/2012.03020v2','DOI':'10.1007/s40879-021-00489-2','private_text':'private_review_materials/inversive_triangle.txt','read_boundary':'Main introduction and §§1–3 through text line275 read; remaining locus/centroid sections and appendix not fully read. Whole extraction keyword-screened.','mapping':'Focus-inversive vertex norms/perimeter use different construction and observable.'},
    {'id':'bicentric_v3','url':'https://arxiv.org/abs/2103.11260v3','DOI':'10.1007/s40598-021-00188-6','private_text':'private_review_materials/bicentric.txt','read_boundary':'Main Theorems1–2, proofs, Corollary1, polarity mapping and AppendixA main lemma boundaries lines1–430 and440–530 read. Remaining algebraic appendix not fully read. Whole extraction keyword-screened. Journal final PDF not retrieved here.','mapping':'Limiting-point pedal/focus-inverse perimeter is not focal antipedal radial sum.'},
    {'id':'spatial_integrals_v1','url':'https://arxiv.org/abs/2102.10899v1','private_text':'private_review_materials/spatial_integrals.txt','read_boundary':'Introduction/main-result declarations lines1–125 and ending questions/references lines530–575 read. Entire text keyword-screened. Intermediate integral derivations and final2023 journal version not fully read.','mapping':'Declared observables perimeter/cosine averages; no target focal-antipedal norm equality.'},
    {'id':'circumcenter_v3','url':'https://arxiv.org/abs/2202.02551v3','private_text':'private_review_materials/circumcenter2022.txt','read_boundary':'Introduction, main results and classical Stewart/Johnson review through text line215 read. Later iteration-topology sections not fully read. Whole extraction keyword-screened.','mapping':'Corollary1 gives exact aliasq=2R(f,A,B), but no ellipse-focal all-N sum identity.'},
    {'id':'IMPA_official_preview','url':'https://coloquio33.impa.br/pdf/33CBM06-eBook-preview.pdf','ISBN':'978-65-89124-43-6','private_text':'private_review_materials/garcia_reznik_IMPA2021.txt','read_boundary':'Actual official15-page preview, title/copyright/contents/introduction examined; not the full250-page book.','mapping':'Book identified but final body exclusion cannot be certified.'},
    {'id':'IMPA_author_snapshot','url':'https://github.com/dan-reznik/33CBM06-IMPA-Garcia-Reznik/tree/0b5b417fe2ba3185087979749bc8bcf8c702315d','source_commit':'0b5b417fe2ba3185087979749bc8bcf8c702315d','source_date':'2021-06-07T19:24:09Z','selected_text_files':145,'read_boundary':'All145 selected text sources searched; all byte-exact Git blob authenticated. Entire ii_chap_05/05_040_invariants_billiard.tex read; ii_chap_08 experimental placeholder and selected antipedal-definition/research/centroid contexts read. Not every chapter read line-by-line. Compiled PDF invalid/truncated; final July2021 content equivalence unknown.','mapping':'No general603 proof found in author source; residual final-version gap retained.'},
    {'id':'2026_original_antipedal_centroid','url':'https://eulersolve.org/papers/amr-050-0023/paper.pdf?v=efab7f38f6a5','DOI':'10.5281/zenodo.23092466','private_text':'private_review_materials/ferudun_k405.txt','read_boundary':'Complete305-line primary manuscript read.','mapping':'Original polygon but vector centroid/even least-period functional, not radial norm sums/allN.'},
    {'id':'2026_outer_focal_antipedal_centroid','url':'https://eulersolve.org/papers/amr-050-0026/paper.pdf?v=317178430532','DOI':'10.5281/zenodo.23071366','private_text':'private_review_materials/ferudun_k407.txt','read_boundary':'Complete313-line primary manuscript read, decisive full reread after an earlier combined output truncation.','mapping':'Outer primed polygon centroid/even least period, not original603.'},
    {'id':'2026_focal_area_product','url':'https://eulersolve.org/papers/amr-050-0021/paper.pdf?v=34ff068237a7','DOI':'10.5281/zenodo.23079799','private_text':'private_review_materials/ferudun_k403b.txt','read_boundary':'Complete318-line primary manuscript read; title/abstract reread individually.','mapping':'Signed same-focus area product, least period0mod4, not ordinary allN radial sum.'},
    {'id':'parable2025_v2','url':'https://arxiv.org/abs/2502.08656v2','DOI':'10.1016/j.exmath.2025.125717','private_text':'private_review_materials/parable2025.txt','read_boundary':'Abstract/introduction/declared scope lines1–122 read; whole1693-line body keyword-screened. Remaining proof sections not fully read.','mapping':'Circle/parabola triangles/quadrilaterals, not allN confocal ellipse focal-antipedal theorem.'},
    {'id':'configuration2026_final','DOI':'10.1017/fms.2026.10254','private_text':'private_review_materials/configuration2026_published.txt','read_boundary':'Final primary PDF retrieved. Abstract/main statements/introduction lines1–173, §3.3.1 Chasles and beginning incircle discussion lines923–1150, full §3.3.3 billiard coordinate discussion lines1223–1381 read. Whole1915-line body keyword-screened. Other proof sections/appendix not fully read.','mapping':'Join/meet incidence and distorted index-shift geometry do not preserve/prove ordinary focal antipedal norm traces.'}
]
citers=json.loads((W/'private_sources/source_openalex_citers.json').read_text())
network=[{'title':r.get('display_name'),'publication_date':r.get('publication_date'),'DOI':r.get('doi'),'OpenAlex_id':r.get('id'),'reading':'Discovery metadata only except primary candidates explicitly listed in sources.'} for r in citers.get('results',[])]
operations=[]
for p in sorted((W/'actual_operations').glob('*/execution.json')):
    d=json.loads(p.read_text());stdout=(p.parent/'stdout.bin').read_bytes()
    operations.append({'label':p.parent.name,'execution_receipt':str(p.relative_to(W)),'child_PID':d['child_PID'],'UTC_start':d['UTC_start'],'UTC_end':d['UTC_end'],'exit_code':d['exit_code'],'stdout_sha256':d['stdout']['sha256'],'stderr_sha256':d['stderr']['sha256'],'HTTP_diagnostic':stdout.decode('utf-8','replace').strip() if p.parent.name.startswith('fetch_') else None})
write('SOURCE_COVERAGE.json',{'schema':'pr110-independent-exact-history-source-coverage/v1','UTC':utc,'actual_writer_PID':os.getpid(),'cutoff':'2026-10-06','sources':sources,'citations_discovery_count':len(network),'OpenAlex_response_count':citers.get('meta',{}).get('count'),'citation_metadata_only':network,'actual_recorded_operations':operations,'complete_source_body_screen_not_full_read':True,'private_bodies_excluded_from_public_payload':True})
write('VERDICT.json',{'schema':'pr110-independent-exact-invariant-history-verdict/v1','UTC':utc,'actual_writer_PID':os.getpid(),'PR':110,'id':5100032,'code':'AMR-050-0032','original_head':'3d159f0a00d0bd7ff8d558d6fbc75af5094f7a35','original_PROOF_sha256':'8478d2a792944c5fb9e8a53324e0c6bce8eba317de29c31a6fcbd6ca0205709d','cutoff':'2026-10-06','status':'NO_EARLIER_FULL_COVER_FOUND_BOUNDED_SUBSTANTIVE_NOVELTY_SUPPORTED_WITH_EXPLICIT_GAPS',
    'earlier_full_cover_found':False,'earlier_result_mapping':None,'reclassification_as_already_solved_supported':False,'bounded_substantive_novelty_supported':True,
    'supported_candidate':'All-period ordinary-positive focal-antipedal distance difference identityq+−q−=GammaΔy and closure proof of literal unprimed k603. Observation, constructions, classical circumcenter alias and low-period ingredients credited as prior.',
    'final_book_gap_negates_bounded_assessment':False,'final_book_gap_prevents_unqualified_final_book_exclusion':True,'absolute_history_priority_established':False,'family_priority_clearance':False,
    'family_priority_clearance_reason':'This family supplies bounded evidence, not unilateral publication clearance. Root must combine3 independent families and fresh adjudication; retain the June-author-source versus July-final-book gap.',
    'publication_authorized':False,'root_math_gate_inherited':True,'new_central_proof_search_turns':0,'other_fresh_priority_reports_read':False,
    'required_findings':[],
    'residual_reading_gaps':[
       {'id':'final_IMPA_2021_book','exact_gap':'Official preview15pages; author compiled PDF invalid. Authenticated June7 source145files is not certified identical to July2021 printed final book.','effect':'No unqualified final-book negative claim; does not itself supply a prior proof or cancel bounded novelty evidence.'},
       {'id':'source_video_and_notebooks','exact_gap':'Author ledger/video metadata and notebook filenames inspected; linked experiment video and low-N notebook bodies not watched/read/executed.','effect':'Discovery credit supported; no assertion that complete accompanying bodies contain no proof.'},
       {'id':'partial_candidate_body_reads','exact_gap':'Appendices/locus sections and2023 spatial-integral journal final are unread as recorded inSOURCE_COVERAGE; generic citation metadata is not full-body review.','effect':'Finite audit only. Main theorem mappings do not cover target; absence claims restricted to actual read/screened scope.'},
       {'id':'global_literature','exact_gap':'Search engines and one17-record citation index can omit unindexed work or variants.','effect':'No absolute first-proof claim.'}],
    'recommendation':'Do not close as already_solved based on this family. Candidate has substantive bounded novelty evidence; root adjudication should evaluate residual source-version limitations and independent covering-mechanism audits before promotion.'})
log=W/'RESEARCH_LOG.md'
with log.open('a') as f:
    f.write('\n'+utc+': Checkpoint: source revision endpoint and historical exact table verified;3 immediate follow-ups, classical circumcenter alias, author ledgers/repositories,145 authenticated book-source files,3 closest2026 papers and2 late citation candidates inspected at honest reading boundaries. No earlier full cover found. Bounded family investigation85% complete; global priority remains root adjudication with final-book/version uncertainty.\n')
    f.write(utc+': Final analysis prepared; substantive candidate novelty supported within finite scope. The June-source/July-final-book gap is retained and does not establish already_solved. Family report/artifact preparation95% pending seal verification; no publication, outreach or Git action.\n')
print(json.dumps({'UTC':utc,'actual_writer_PID':os.getpid(),'written':['QUERY_LOG.json','SOURCE_COVERAGE.json','VERDICT.json'],'source_rows':len(sources),'citation_discovery_rows':len(network),'recorded_operations':len(operations)}))
