"""Own SOURCE authoring only. Proposed production is read and written as literal text."""
from pathlib import Path
import datetime as dt, hashlib, json, os, re
H = Path(__file__).resolve().parent; A = H.parent; R = A.parents[2]
T = R/'draft_pr_publication_program_20260930/audits/pr45_9900007/acceptance_preparation_family'
P = T.parent; C = A/'reviewed_candidate'
def sha(b): return hashlib.sha256(b).hexdigest()
def load(p): return json.loads(p.read_bytes())
def pin(p):
    b = p.read_bytes(); return {'path':p.relative_to(R).as_posix(),'bytes':len(b),'sha256':sha(b)}
def put(n, value):
    body = value.encode() if type(value) is str else (json.dumps(value,sort_keys=True,indent=2,ensure_ascii=False)+'\n').encode()
    with (H/n).open('xb') as stream: stream.write(body); stream.flush(); os.fsync(stream.fileno())
def fn(source, name, replacement):
    start = source.index('def '+name+'('); end = source.find('\n\ndef ',start+1)
    return source[:start] + replacement.strip()+'\n' + (source[end:] if end>=0 else '')
def line(source, name, value):
    start = source.index(name+' = '); end = source.index('\n',start)
    return source[:start]+name+' = '+repr(value)+source[end:]
def adapt(source):
    pairs = {'pr44_2912':'__PREDECESSOR__','PR44':'__PREDECESSOR_PR__','pr44':'__PREDECESSOR_SCHEMA__','pr45':'pr46','PR45':'PR46','9900007':'30004438','AMR-098-0007':'OWR-17475-003','d9b4acf5d070d1f04ffac86a4f08916a5629ff16':'a39d178b10f75fb127058b08e0d0002b3ae97f8a','01358d66fc67d1c462bddf31c0d4ee5b120e6737':'c6975ca76f9f667f1250ba403d0e6da2aafe14d0','d136815406dc35265a828deece080813c716c69c2bb915192e606acafdcdd4c5':sha((C/'MANIFEST.json').read_bytes()),'e215d1b33f3cdc562aeb53cee76519386d7d203acbe8c1c251370b3fd3bd2410':sha((C/'CURRENT_DEPENDENCIES.json').read_bytes()),'PARTIAL.md':'SOURCE_STATUS.md','CURRENT_PARTIAL_CONTEXT.md':'CURRENT_SOURCE_STATUS_CONTEXT.md','review/verdict.json':'independent_review/verdict.json','turns.jsonl':'turns.json','original18':'original13','Original18':'Original13','immutable12':'immutable10','immutable12':'immutable10','183402':'89103','original19':'original14','Original19':'Original14','19-path':'14-path','original1/5':'original0/5','Original1/5':'Original0/5','unsolved1/5':'already_solved0/5','one-turn_JSONL':'zero_turn_object','one_turn_JSONL':'zero_turn_object','one-turn JSONL':'zero-turn JSON object'}
    pattern = re.compile('|'.join(re.escape(k) for k in sorted(pairs,key=len,reverse=True)))
    source = pattern.sub(lambda m:pairs[m.group()], source)
    source = source.replace('__PREDECESSOR__','pr45_9900007').replace('__PREDECESSOR_PR__','PR45').replace('__PREDECESSOR_SCHEMA__','pr45')
    for old,new in [("'pr':45","'pr':46"),("'pr': 45","'pr': 46"),("'number':45","'number':46"),("'number': 45","'number': 46"),("'pr':45,","'pr':46,"),("['required_completed_prs']+[45]","['required_completed_prs']+[46]"),("current_pr=46","current_pr=47"),("'current_pr':46","'current_pr':47"),("'current_pr': 46","'current_pr': 47"),("z['number']==45","z['number']==46"),("identities.count(45)","identities.count(46)"),("'original_substantive_attempts':1","'original_substantive_attempts':0"),("'original_substantive_attempts': 1","'original_substantive_attempts': 0"),("'substantive_attempts_used':1","'substantive_attempts_used':0"),("'substantive_attempts_used': 1","'substantive_attempts_used': 0"),("original_attempts='1/5'","original_attempts='0/5'"),("cumulative_attempts='1/5'","cumulative_attempts='0/5'"),("'original_attempts':'1/5'","'original_attempts':'0/5'"),("'cumulative_attempts':'1/5'","'cumulative_attempts':'0/5'"),("'used':1","'used':0"),("'turns_used':1","'turns_used':0"),("'status':'unsolved'","'status':'already_solved'"),("queue_status='unsolved'","queue_status='already_solved'"),("queue_status':'unsolved'","queue_status':'already_solved'"),("unsolved_accepted_partial","already_solved_accepted_known_result"),("unsolved_accepted_standard_partial","already_solved_accepted_credited_known_result"),("len(state)==35","len(state)==36"),("len(prior)==35","len(prior)==36"),("len(current)==36","len(current)==37"),("len(plan['state_after'])==36","len(plan['state_after'])==37"),("sum(z['turns_used'] for z in state.values())==43","sum(z['turns_used'] for z in state.values())==44"),("sum(z['turns_used'] for z in prior.values())==43","sum(z['turns_used'] for z in prior.values())==44"),("plan['primary_count']==35","plan['primary_count']==36"),("'primary_acceptances':35","'primary_acceptances':36"),("'primary_acceptances': 35","'primary_acceptances': 36"),("'current_targets':36","'current_targets':37"),("'prior_state_entries_preserved':35","'prior_state_entries_preserved':36"),("'targets':36","'targets':37"),("'targets': 36","'targets': 37"),("'program_completed_count':35","'program_completed_count':36"),("'completed_count':35","'completed_count':36"),("inv['completed_count']==35","inv['completed_count']==36"),("inv['completed_count']==34","inv['completed_count']==35"),("z.get('stage')=='complete' for z in inv['items'])==34","z.get('stage')=='complete' for z in inv['items'])==35"),("z.get('stage')=='complete' for z in inv['items'])==35","z.get('stage')=='complete' for z in inv['items'])==36")]:
        source = source.replace(old,new)
    return source
SCIENCE = {'full_problem_solved':True,'full_target_prior_result_verified':True,'full_target_resolved_in_prior_preprint':True,'full_problem_solved_by_project':False,'project_solved':False,'campaign_new_discovery':False,'prior_publication_doi':None,'partial_valid':True,'novelty_claimed':False,'priority_claimed':False,'original_substantive_attempts':0,'original_source_verification_responses':1,'turn_limit':5,'new_substantive_attempts':0,'audit_turns':0,'verification_attempts_added':0,'current_model':None,'current_reasoning_effort':None,'current_deadline_utc':None,'paper_or_new_doi_or_tracker':False,'paper_created':False,'new_DOI_created':False,'tracker_row_created':False,'human_referee_review_claimed':False,'human_peer_review_claimed':False,'formal_certification_claimed':False,'journal_publication_certified':False,'existing_result_credit':['Khazhgali Kozhasov','Mario Kummer'],'source_publication_kind':'2020 preprint'}
GAPS = ['ROOT final reconciliation and independently fresh then-current native/main acceptance authority']
SCOPE = {**SCIENCE,'schema':'pr46-proposed-accepted-scientific-scope/v1','id':'30004438','problem_number':'OWR-17475-003','literal_target_status':'already_solved','literal_target':'For every d>=2, a nonempty ordinary real-open subset of the full dimension2d+1 real degree-d rational-map parameter space has all projective periodic points in RP1 for every positive period, including infinity.','strongest_verified_result':'The exact target is a credited existing Kozhasov–Kummer2020 preprint result; independently checked interlacing/real-fiber/degree counting and imaginary-growth/persistent-attractor mechanisms verify its full ambient and all-period scope.','exact_mathematical_gap_remaining':None,'exact_remaining_gaps':GAPS,'prior_publication_kind':'preprint','prior_result_publication_year':2020,'full2dplus1_ordinary_ambient_real_openness':True,'every_degree_at_least_two':True,'all_positive_periods_and_infinity':True,'entire_real_periodic_locus_open_claimed':False,'Zariski_openness_claimed':False,'classification_Hermite_or_higher_dimension_claimed':False,'finite_51_and848_checks_are_diagnostics_only':True,'plain_source_record_and_prior_key_absence_distinct_from_null_and_empty':True,'original13_and_immutable10_unchanged':True,'object_ledger_not_JSONL':True,'historical_metadata_archival_only':True,'historical_PASS_transferred':False,'frozen_builder_prefix43_final_original_inner45_after_exit_distinguished':True,'legacy_PDF_hashes_attributed_not_freshly_ROOT_authenticated':True,'fresh_ROOT_pixel_inspection_claimed':False,'exhaustive_journal_priority_history_claimed':False,'global_qualification_path':'SOURCE_PRECISION_QUALIFICATIONS.md','global_qualification_sha256':sha((C/'SOURCE_PRECISION_QUALIFICATIONS.md').read_bytes()),'AI_tools_used_extensively':True,'human_peer_review':False,'formal_certification':False}
IMMUTABLE = {'SOURCE_STATUS.md','independent_review/REVIEW.md','independent_review/independent_checks.py','independent_review/independent_results.json','independent_review/review_summary.json','provenance.json','source_record.json','turns.json','verification.json','verify.py'}
BODY = 'Accept PR46 / 30004438 / OWR-17475-003 as an already_solved repository report crediting Khazhgali Kozhasov and Mario Kummer’s 2020 preprint. For every d>=2, a nonempty ordinary real-open subset of the full dimension2d+1 real degree-d rational-map space has exclusively RP1 periodic points at all positive periods, including infinity. The complete proof and independent mechanisms verify this exact target; finite51/848 checks are diagnostic evidence. This is a correction of the imported open-status assessment, with no campaign discovery or novelty. The original13 and ten operative science/helper/result/source/ledger bodies stay exact. Original0/5, source-verification responses1, new0, audit0; turns.json is a JSON object. Prior-key absence is distinct from raw null or present empty fallback. Current model/reasoning/deadline are null. Historical source/access/PASS/runtime/publication-state claims remain dated; full final after-exit original inner45 commands and outer capture are separately bound, and the frozen inner43 prefix remains archival. The newly closed independent whole-current and actual ROOT reading/reconciliation supply present evidence only. No exhaustive journal-history or fresh legacy-PDF/pixel authentication is claimed. AI tools were used extensively; this is unrefereed, with no claimed human peer review or formal certification. No new paper, DOI, tracker entry or release. One present zero-turn native acceptance event follows the exact original-head no-ff merge and preserves all prior states/history.\n'
PRESENT = 'Actual acceptance is bound in acceptance.json. This CURRENT_ACCEPTANCE_SCOPE.md applies globally to SOURCE_STATUS.md, SOURCE_PRECISION_QUALIFICATIONS.md, all current presentations and all metadata. The full mathematical target is a credited known Kozhasov–Kummer2020 preprint result; project_solved and campaign novelty are false. Every d>=2, all positive periods, infinity, ordinary real openness and full ambient dimension2d+1 are retained. The entire locus, Zariski openness, Hermite, higher-dimensional cases and exhaustive journal history are not asserted. Original13 and immutable10 retain their bytes, including the complete object ledger original0/5 with source-verification responses1; new0/audit0. The plain raw source/prior-key absence and saved{} fallback are distinct from null/present empty source. All frozen prospective PENDING, old PASS/model/access/publication-state statements, V1’s superseded chronology, the frozen inner43 prefix and separately dated approvals remain literal archives; they do not override this present accepted disposition. Complete actual final original inner45 commands were read only after actual builder exit; only the outer CAPTURE was completed postexit. Fresh whole-current and ROOT final evidence are separate from historical review. Current runtime fields remain null; no new discovery, journal certification, fresh ROOT legacy-PDF or pixel authentication, human referee review, formal certification, paper/new DOI/tracker/release. Extensive AI use; unrefereed.\n'
MIRROR_SCOPE = 'Incremental present accepted primary PR46 exact known rational-map result credited to Kozhasov–Kummer2020preprint; original0/5 plus source-verification responses1, no new proof turn or historical reconstruction.'
ORIGINAL_FUNCTION = r'''
def original_native(base):
    snapshot=load(A/'snapshot_manifest.json')
    require(snapshot['schema']=='pr46-original-source-snapshot/v1' and snapshot['head']==HEAD and snapshot['merge_base']==ORIGINAL_BASE and snapshot['github_base']==ORIGINAL_BASE and len(snapshot['files'])==13,'Literal original13/head/equal GitHubbase and mergebase')
    exact(base,{z['relative_path'] for z in snapshot['files']})
    for z in snapshot['files']:
        n=z['relative_path'];relative(n);require(z['path']=='unsolved_math_prioritization/attempts/'+ID+'/'+n and z['git_mode']=='100644','Exact original literal paths/Git mode')
        raw=regular(base,n).read_bytes();require(raw==regular(A/'source_snapshot',n).read_bytes() and len(raw)==z['bytes'] and sha(raw)==z['sha256'],'Original13 complete bytes differ')
'''
SOURCE_FUNCTION = r'''
def source(base):
    original_native(base/'original_archive')
    for n in IMMUTABLE:require(regular(base,n).read_bytes()==regular(A/'source_snapshot',n).read_bytes(),'Immutable10 science/helper/result/source/object-ledger changed')
    require(sha(regular(base,'SOURCE_STATUS.md').read_bytes())==SCIENCE_SHA and sha(regular(base,'source_record.json').read_bytes())==SOURCE_SHA,'Science/source anchors differ')
    raw=regular(base,'turns.json').read_bytes();require(raw==regular(A/'source_snapshot','turns.json').read_bytes() and sha(raw)==LEDGER_SHA,'Literal complete original zero-turn JSON object ledger')
    ledger=parse(raw);require(equal(ledger,load(HERE/'EXPECTED_ORIGINAL_LEDGER.json')),'Entire original typed object ledger unchanged')
    required(ledger,{'problem_id':30004438,'problem_number':CODE,'turn_limit':5,'substantive_turns_used':0,'source_verification_responses':1},'Original0/5 plus one source-verification response')
    record=load(base/'source_record.json');require(type(record) is dict and type(record['id']) is int and record['id']==30004438 and record['problem_number']==CODE,'Plain original raw problem object')
    require(sha(regular(base,'SOURCE_PRECISION_QUALIFICATIONS.md').read_bytes())==load(HERE/'SCIENTIFIC_SCOPE.json')['global_qualification_sha256'],'Global exact known-result/provenance/chronology qualifications')
'''
BASIS_FUNCTION = r'''
def basis(root_bindings,root_bindings_sha256):
    approved,rp=root_binding_input(root_bindings,root_bindings_sha256);inputs=load(HERE/'INPUT_BINDINGS.json');refs=[]
    require(inputs['whole_binding_completed'] is True,'No pending whole family may confer authority')
    for n in sorted(inputs['pins']):z=exact_reference(inputs['pins'][n]);check(R,[z]);refs.append(z)
    frozen=manifest(C,'MANIFEST.json',CURRENT_SHA,946,frozen=True);deps=load(C/'CURRENT_DEPENDENCIES.json')
    require(equal(deps,load(HERE/'EXPECTED_CURRENT_DEPENDENCIES.json')),'Entire dated current dependencies required')
    require(sha((C/'CURRENT_DEPENDENCIES.json').read_bytes())==DEPS_SHA and len(rows(deps['files']))==826,'All826 dependencies');check(A,deps['files']);source(C)
    for n in ADMIN:require(equal(load(C/n),load(HERE/'EXPECTED_CURRENT_ADMIN.json')),'Entire prospective administrative metadata')
    wm=exact_reference(approved['whole_manifest']);require(equal(wm,inputs['closed_whole_manifest']),'Closed whole exact identity');w=A/'current_whole_adversary_family';whole=parse(bound(wm))
    require(equal(whole,load(HERE/'EXPECTED_WHOLE_MANIFEST.json')),'Entire closed whole typed manifest')
    rr=rows(whole['files']);require(type(whole['files_count']) is int and whole['files_count']==len(rr) and whole['self_excluded']==[Path(wm['path']).name],'Whole literal self-only manifest count')
    check(w,rr);exact(w,{z['path'] for z in rr}|{Path(wm['path']).name});frozen_files(w,rr,Path(wm['path']).name)
    if 'directories' in whole:require(equal(sorted(topology(w)[1]),sorted(z if type(z) is str else z['path'] for z in whole['directories'])),'Complete whole directory topology')
    inventory=load(R/inputs['closed_whole_external_inventory']['path']);require(equal(inventory,load(HERE/'EXPECTED_EXTERNAL_INPUT_INVENTORY.json')),'Entire external read inventory')
    references=inputs['external_input_rows'];require(type(references) is list and len(references)==inputs['external_input_count'],'Whole individual external count')
    names=set()
    for z in references:
        keyset(z,{'path','bytes','sha256'},'Complete absolute excluded input identity');p=resolve_foreign_literal(z['path']);raw=p.read_bytes();require(type(z['bytes']) is int and len(raw)==z['bytes'] and sha(raw)==digest(z['sha256']),'Full excluded input changed');names.add(p.relative_to(R).as_posix())
    require(len(names)==len(references),'No repeated absolute external identity')
    historical={'draft_pr_publication_program_20260930/inventory.json','unsolved_math_prioritization/QUEUE.md','unsolved_math_prioritization/state.json','unsolved_math_prioritization/history.jsonl'};dated_head=deps['current_main_head'];dated=load(A/'ROOT_CURRENT_INPUT_PREIMAGES.json');require(dated['current_head']==dated_head,'Frozen epoch never rebound');native={z['path']:z for z in rows(dated['files'])};require(set(native)==NATIVE,'Exact dated13')
    require((NATIVE-historical)<=names and not historical.intersection(names),'Dated Git native4 plus stable live9 distinction')
    for n in sorted(historical):
        entries=git_bytes('ls-tree','-z',dated_head,'--',n).decode().split('\0');require(len(entries)==2 and entries[-1]=='','One frozen Git entry');fields,literal=entries[0].split('\t');mode,kind,blob=fields.split();require(mode=='100644' and kind=='blob' and literal==n,'Frozen native100644 mode/path');raw=git_bytes('show',dated_head+':'+n);require(len(raw)==native[n]['bytes'] and sha(raw)==native[n]['sha256'],'Entire frozen native4 Git bodies')
    verdict=parse(bound(inputs['closed_whole_result']));require(equal(verdict,load(HERE/'EXPECTED_WHOLE_VERDICT.json')),'Entire typed actual whole verdict');require(verdict['mandatory_corrections']==[],'Whole mandatory corrections must be empty')
    bound(inputs['closed_whole_report']);rootref=exact_reference(approved['root_whole_inspection']);require(equal(rootref,inputs['closed_root_whole_inspection']),'Genuine actual ROOT full whole-read pin')
    root=parse(bound(rootref));require(equal(root,load(HERE/'EXPECTED_ROOT_WHOLE_REVIEW.json')) and equal(root['complete_VERDICT_object'],verdict),'Entire genuinely completed ROOT whole record and typed verdict')
    require(root['future_execution_approved'] is False,'Whole reading supplies no future execution approval');require(utc_clock(inputs['root_whole_read_completed_utc'],'Actual whole read')<=utc_clock(approved['created_utc'],'Actual ROOT approval'),'Whole reading before approval')
    freeze=load(A/'ROOT_ACTUAL_CURRENT_FREEZE_INSPECTION.json');require(equal(freeze,load(HERE/'EXPECTED_ROOT_CURRENT_FREEZE.json')),'Complete genuinely finished original inner/outer ROOT record')
    required(freeze,{'schema':'pr46-root-complete-actual-current-freeze-readback/v2','status':'PASS_COMPLETED_ORIGINAL_INNER_OUTER_FULL_READBACK','packet_files_count':946,'packet_directories':142,'frozen_inner_prefix_commands':43,'final_original_inner_commands':45,'all_dependency_members_read':826,'ROOT_full_command_record_and_outer_streams_personally_read':True,'old_PASS_transferred':False,'future_acceptance_approved':False},'Exact after-exit current evidence, historical prefix not final')
    for z in freeze['complete_stream_members']:check(A,[z])
    ledger=load(A/'ROOT_PRIMARY_READ_LEDGER.json');card=load(A/'ROOT_SCIENCE_CARD.json');require(equal(ledger,load(HERE/'EXPECTED_PRIMARY_READ_LEDGER.json')) and equal(card,load(HERE/'EXPECTED_SCIENCE_CARD.json')),'Entire genuine primary read ledger/science card')
    flags=ledger['root_flags'];require(len(flags)==9 and ledger['reading_completed'] is True and card['reading_completed'] is True and equal(flags,card['root_flags']) and all(v is True for v in flags.values()),'Nine genuinely completed mathematical/source flags')
    required(card,{'status':'already_solved','exact_known_target_verified':True,'full_problem_solved':True,'full_target_prior_result_verified':True,'project_solved':False,'novelty_claimed':False,'original_substantive_attempts':0,'original_source_verification_responses':1,'new_substantive_attempts':0,'audit_turns':0,'paper_created':False,'new_DOI_created':False,'tracker_row_created':False,'operative_preparation_directory':'current_preparation_family_v2'},'Known credit scope only')
    refs += [pin(C/'MANIFEST.json'),pin(C/'CURRENT_DEPENDENCIES.json'),wm,inputs['closed_whole_result'],inputs['closed_whole_report'],inputs['closed_whole_external_inventory'],rootref,pin(rp)]+[approved[n] for n in ['previous_mirror','previous_post','previous_root_post','acceptance_source_manifest','acceptance_source_verdict','root_source_inspection','root_capture_operator']]
    out={}
    for z in refs:require(z['path'] not in out or equal(out[z['path']],z),'Conflicting immutable identity');out[z['path']]=z
    return frozen,sorted(out.values(),key=lambda z:z['path'])
'''
ROOT_FUNCTION = r'''
def root_binding_input(name,pin_value):
    p=regular(R,name);require(p.parent==A and p.name=='ROOT_IMMUTABLE_ACCEPTANCE_BINDINGS.json','Genuine adjacent final ROOT approval required');require(sha(p.read_bytes())==digest(pin_value),'Actual ROOT approval pin')
    o=parse(p.read_bytes());draft=load(HERE/'DRAFT_ROOT_IMMUTABLE_BINDINGS.json');keys=['whole_manifest','root_whole_inspection','root_capture_operator','previous_mirror','previous_post','previous_root_post','acceptance_source_manifest','acceptance_source_verdict','root_source_inspection']
    for k in keys:exact_reference(o[k]);check(R,[o[k]])
    draft.update(status='ROOT_APPROVED_CLOSED_WHOLE_SOURCE_AND_ACTUAL_PR45_EVIDENCE',created_utc=o['created_utc'],root_full_current_read_completed=True,root_full_whole_read_completed=True,root_acceptance_source_review_completed=True,independent_whole_current_pass=True,root_actual_PR45_predecessor_read_completed=True)
    for k in keys:draft[k]=o[k]
    require(equal(o,draft),'Complete known typed final ROOT bindings; extra approvals prohibited');require(utc_clock(o['created_utc'],'Actual ROOT approval')<=dt.datetime.now(dt.timezone.utc),'No future approval clock')
    inputs=load(HERE/'INPUT_BINDINGS.json')
    for k in ['previous_mirror','previous_post','previous_root_post']:require(equal(o[k],inputs[k]),'Exact actual PR45 predecessor identity')
    previous=load(R/o['previous_mirror']['path']);post=load(R/o['previous_post']['path']);rootpost=load(R/o['previous_root_post']['path'])
    require(equal(post,load(HERE/'EXPECTED_PREVIOUS_POST.json')) and equal(rootpost,load(HERE/'EXPECTED_PREVIOUS_ROOT_POST.json')),'Entire genuine PR45 post evidence')
    require(rootpost['schema']=='pr45-root-complete-actual-post-inspection/v1' and equal(rootpost['entire_post'],post),'Known exact actual PR45 complete ROOT post schema')
    require(type(previous['entries']) is list and len(previous['entries'])==35 and all(type(z['pr']) is int for z in previous['entries']),'All35 prior primary entries')
    nums=[z['pr'] for z in previous['entries']];require(len(set(nums))==35 and 45 in nums and 46 not in nums and equal(sorted(nums),previous['required_completed_prs']),'Exact actual prior35 primary membership')
    require(utc_clock(rootpost['utc'],'Actual PR45 post')<=utc_clock(o['created_utc'],'Actual ROOT46 approval'),'Actual predecessor precedes approval')
    require(o['root_capture_operator']['path']==(A/'capture_root_final_operation.py').relative_to(R).as_posix() and bound(o['root_capture_operator'])==regular(HERE,'capture_root_final_operation.py').read_bytes(),'Literal prepared operator separately read by ROOT')
    sm=regular(R,o['acceptance_source_manifest']['path']);sv=regular(R,o['acceptance_source_verdict']['path']);sr=regular(R,o['root_source_inspection']['path'])
    require(sm.parent==sv.parent and sm.parent.parent==A and sm.parent not in {C,HERE,A/'current_whole_adversary_family',A/'current_source_adversary_family_v2'} and sm.name=='SELF_MANIFEST.json' and sv.name=='VERDICT.json','New distinct acceptance SOURCE adversary closure required')
    own=load(sm);rr=rows(own['files']);require(own['self_excluded']==['SELF_MANIFEST.json'] and type(own['files_count']) is int and own['files_count']==len(rr),'Literal SOURCE self-only closure')
    check(sm.parent,rr);exact(sm.parent,{z['path'] for z in rr}|{'SELF_MANIFEST.json'});frozen_files(sm.parent,rr,'SELF_MANIFEST.json')
    verdict=load(sv);required(verdict,{'schema':'pr46-acceptance-source-adversary-verdict/v1','verdict':'PASS_SOURCE_ONLY_SCOPED','preparation_manifest_sha256':sha((HERE/'PREPARATION_MANIFEST.json').read_bytes()),'mandatory_corrections':[],'production_imported_compiled_executed':False,'future_acceptance_approved':False},'New acceptance SOURCE gate')
    require(sr.parent==A and sr.name=='ROOT_SOURCE_ACCEPTANCE_REVIEW.json','Genuine standalone ROOT acceptance SOURCE read')
    root=load(sr);required(root,{'schema':'pr46-root-complete-acceptance-source-inspection/v1','status':'PASS_ROOT_COMPLETE_ACCEPTANCE_SOURCE_INSPECTION','all_prepared_source_and_controls_fully_read':True,'exact_preparation_closure_and_full_modes_checked':True,'all_individual_source_adversary_inputs_checked':True,'all_complete_actual_captures_checked':True,'complete_VERDICT_object':verdict,'preparation_manifest_sha256':sha((HERE/'PREPARATION_MANIFEST.json').read_bytes()),'acceptance_source_manifest':o['acceptance_source_manifest'],'acceptance_source_verdict':o['acceptance_source_verdict'],'mandatory_corrections':[],'future_execution_approved':False},'Actual complete ROOT acceptance SOURCE read')
    require(utc_clock(root['utc'],'Actual SOURCE read')<=utc_clock(o['created_utc'],'Actual approval'),'SOURCE reading must precede approval')
    return o,p
'''
INVENTORY_FUNCTION = r'''
def derive_inventory(before,remote,finalized_utc):
    require(type(before) is dict and type(before.get('items')) is list and len(before['items'])==180,'Retained complete180 inventory');require(all(type(z) is dict and type(z.get('number')) is int for z in before['items']),'Typed original inventory identities')
    identities=[z['number'] for z in before['items']];require(len(set(identities))==180 and identities.count(46)==1,'Unique PR46 target');require(type(before.get('completed_count')) is int and before['completed_count']==35 and sum(z.get('stage')=='complete' for z in before['items'])==35,'Exactly35 prior completions')
    required(remote,{'state':'MERGED','isDraft':False,'number':46,'headRefOid':HEAD,'headRefName':'dot/math-'+ID,'baseRefName':'main'},'Actual credited known-result merge');require(type(remote['mergeCommit']) is dict and set(remote['mergeCommit'])=={'oid'} and type(remote['mergeCommit']['oid']) is str and re.fullmatch('[0-9a-f]{40}',remote['mergeCommit']['oid']),'Actual exact merge object')
    clock=utc_clock(finalized_utc,'Actual finalization');merged=utc_clock(remote['mergedAt'],'Actual merge');require(merged<=clock<=dt.datetime.now(dt.timezone.utc),'No reversed/future actual merge clocks')
    inv=copy.deepcopy(before);chosen=next(z for z in inv['items'] if z['number']==46);require(chosen.get('stage')!='complete','Selected target not already complete')
    chosen.update(stage='complete',outcome='already_solved_accepted_known_result',queue_status='already_solved',audited_head=HEAD,merge_commit=remote['mergeCommit']['oid'],merged_at=remote['mergedAt'],workflow_completion_estimate_percent=100,original_attempts='0/5',original_source_verification_responses=1,new_substantive_attempts=0,cumulative_attempts='0/5',paper_or_new_doi_or_tracker=False)
    require(sum(z.get('stage')=='complete' for z in inv['items'])==36,'Exactly36 derived primary completions');inv.update(updated_at_utc=finalized_utc,last_checkpoint_utc=finalized_utc,completed_count=36,program_completion_estimate_percent=36/180*100,completion_estimate_percent=36/180*100,current_pr=47)
    return inv
'''
QUEUE_FUNCTION = r'''
def queue_after(before):
    row=g.selected(before);cells=row.split('|');g.require(cells[8].strip()=='queued' and cells[9].strip()=='0/5','Fresh selected queue row queued0/5')
    cells[8]=' already_solved ';cells[9]=' 0/5 ';cells[11]=' Exact full ambient-interior and all-period RP1 theorem verified and credited to Kozhasov–Kummer2020preprint; no campaign novelty or journal certification. [Accepted known-result source correction](attempts/30004438/ACCEPTANCE.md). Original0/5, source-verification responses1, new0, audit0; no paper/new DOI/tracker. '
    after_row='|'.join(cells);changed=[i for i in range(len(cells)) if cells[i]!=row.split('|')[i]]
    g.require(set(changed)=={8,11} and cells[9]==row.split('|')[9] and cells[10]==row.split('|')[10] and cells[12]==row.split('|')[12],'Only Status/Findings bytes differ; named Turns remains0/5; Chat/DOI preserved')
    g.require(before.count(row.encode())==1,'One literal target row');after=before.replace(row.encode(),after_row.encode(),1);g.require(after.replace(after_row.encode(),row.encode(),1)==before,'Full queue inverse equality');return after,after_row
'''
def main():
    assert __debug__ and not (H/'pr46_guards.py').exists()
    templates = ['pr45_guards.py','seal_final_evidence.py','capture_root_final_operation.py','integrate_reviewed_partial.py','state_mirror_reconciliation.py','verify_post_acceptance.py']
    for n in templates: (H/'TEMPLATE_'+n).write_bytes((T/n).read_bytes())
    source=adapt((T/'pr45_guards.py').read_text());source=source.replace('import pr45_guards','import pr46_guards')
    source=re.sub(r"ID, CODE, PR = .*", "ID, CODE, PR = '30004438', 'OWR-17475-003', 46",source)
    for name,value in [('SOURCE_SHA',sha((C/'source_record.json').read_bytes())),('LEDGER_SHA',sha((C/'turns.json').read_bytes())),('SCIENCE_SHA',sha((C/'SOURCE_STATUS.md').read_bytes())),('ADMIN',{'status.json','readiness.json','independent_review/verdict.json'}),('IMMUTABLE',IMMUTABLE),('SCIENCE',SCIENCE)]: source=line(source,name,value)
    source=source.replace("'full_problem_solved','novelty_claimed','original_substantive_attempts','new_substantive_attempts','audit_turns','full_permission_mode'","'full_problem_solved','campaign_new_discovery','novelty_claimed','original_substantive_attempts','original_source_verification_responses','new_substantive_attempts','audit_turns','full_permission_mode'")
    for name,text in [('original_native',ORIGINAL_FUNCTION),('source',SOURCE_FUNCTION),('root_binding_input',ROOT_FUNCTION),('basis',BASIS_FUNCTION),('derive_inventory',INVENTORY_FUNCTION)]:source=fn(source,name,text)
    source=source.replace("manifest(C,'MANIFEST.json',CURRENT_SHA,497", "manifest(C,'MANIFEST.json',CURRENT_SHA,946")
    source=source.replace("root_actual_PR45_predecessor_read_completed", "root_actual_PR45_predecessor_read_completed")
    source=source.replace("partial_valid=True,preparation_manifest", "partial_valid=True,preparation_manifest")
    source=source.replace("'full_target_resolved_in_prior_published_literature':False", "'full_target_resolved_in_prior_preprint':True")
    source=source.replace("'substantive_attempts_used':0", "'substantive_attempts_used':0,'original_source_verification_responses':1")
    source=source.replace("'unsolved'", "'already_solved'")
    source=source.replace("'outcome':'already_solved_accepted_known_result_merged'", "'outcome':'already_solved_accepted_known_result_merged'")
    source=source.replace("for n in ['previous_mirror','previous_post']", "for n in ['previous_mirror','previous_post']")
    source=source.replace("'pr46-accepted-qualified-standard-partial/v1'", "'pr46-accepted-qualified-known-result/v1'")
    # Object ledger remains exact, while the bound native mirror uses its independently
    # checked accepted source bytes instead of interpreting JSONL or charging a turn.
    start=source.index('def ledger_list(');end=source.index('\n\ndef keyset(',start);source=source[:start]+source[end+2:]
    source=source.replace("'negative_ledger_controls':['empty','whitespace_only','invented_JSONL','bool_used','wrong_used','wrong_limit']", "'negative_ledger_controls':['empty','whitespace_only','invented_object','bool_used','wrong_used','wrong_limit']")
    source=source.replace("'current_gate':'accepted_qualified_partial'", "'current_gate':'accepted_credited_known_result'")
    source=source.replace("current_gate='accepted_qualified_partial'", "current_gate='accepted_credited_known_result'")
    source=source.replace("'whole_current497_and416dependencies_bound'", "'whole_current946_and826dependencies_bound'")
    source=source.replace("'full_problem_solved':False", "'full_problem_solved':True")
    source=source.replace("'original_substantive_attempts':0,'new_substantive_attempts'", "'original_substantive_attempts':0,'original_source_verification_responses':1,'new_substantive_attempts'")
    put('pr46_guards.py',source)
    for n in ['seal_final_evidence.py','capture_root_final_operation.py','integrate_reviewed_partial.py','state_mirror_reconciliation.py','verify_post_acceptance.py']:
        text=adapt((T/n).read_text()).replace('import pr45_guards','import pr46_guards')
        if n=='integrate_reviewed_partial.py':
            text=line(line(text,'BODY',BODY),'PRESENT_SCOPE',PRESENT);text=fn(text,'queue_after',QUEUE_FUNCTION)
            text=text.replace("inv['completed_count']==35 and sum(z.get('stage')=='complete' for z in inv['items'])==36", "inv['completed_count']==35 and sum(z.get('stage')=='complete' for z in inv['items'])==35")
            text=text.replace("'named_changes':['Status','Turns','Findings']", "'named_changes':['Status','Turns','Findings']")
            text=text.replace("'# Accepted unsolved illustrative synchronous coupling obstruction: 30004438 / OWR-17475-003", "'# Accepted credited known rational-map result: 30004438 / OWR-17475-003")
            text=text.replace("original one-line JSONL exactly bound", "original JSON object exactly bound")
            text=text.replace("Program35/180=19.4444%", "Program36/180=20%")
        if n=='state_mirror_reconciliation.py':
            text=text.replace("Incremental present accepted primary PR46 illustrative synchronous coupling obstruction; original0/5, no new proof turn or historical reconstruction.",MIRROR_SCOPE)
            old="[('empty',b'',1,5),('whitespace_only',b'\\n',1,5),('invented_JSONL',b'{\"turn\":1}\\n',1,5),('bool_used',g.regular(g.K,'turns.json').read_bytes(),True,5),('wrong_used',g.regular(g.K,'turns.json').read_bytes(),2,5),('wrong_limit',g.regular(g.K,'turns.json').read_bytes(),1,4)]"
            new="[('empty',b'',0,5),('whitespace_only',b'\\n',0,5),('invented_object',b'{\"substantive_turns_used\":0}\\n',0,5),('bool_used',g.regular(g.K,'turns.json').read_bytes(),False,5),('wrong_used',g.regular(g.K,'turns.json').read_bytes(),1,5),('wrong_limit',g.regular(g.K,'turns.json').read_bytes(),0,4)]"
            assert old in text; text=text.replace(old,new)
            text=text.replace("'budget':{'used':0,'limit':5", "'budget':{'used':0,'limit':5")
        if n=='verify_post_acceptance.py':
            text=text.replace("'entire_history_prefix_and35prior_states_preserved'", "'entire_history_prefix_and36prior_states_preserved'").replace("'whole_current497_and416dependencies_bound'", "'whole_current946_and826dependencies_bound'")
            text=text.replace("'full_problem_solved':False", "'full_problem_solved':True").replace("'full_target_resolved_in_prior_published_literature':False", "'full_target_resolved_in_prior_preprint':True")
        if n!='capture_root_final_operation.py':text=text.replace("current_gate='accepted_qualified_partial'", "current_gate='accepted_credited_known_result'")
        put(n,text)
    guard=(H/'pr46_guards.py').read_text();guard=guard.replace("Incremental present accepted primary PR46 illustrative synchronous coupling obstruction; original0/5, no new proof turn or historical reconstruction.",MIRROR_SCOPE)
    (H/'pr46_guards.py').write_text(guard)
    put('SCIENTIFIC_SCOPE.json',SCOPE);put('EXPECTED_ORIGINAL_LEDGER.json',load(C/'turns.json'))
    for name,path in [('EXPECTED_PRIMARY_READ_LEDGER.json',A/'ROOT_PRIMARY_READ_LEDGER.json'),('EXPECTED_SCIENCE_CARD.json',A/'ROOT_SCIENCE_CARD.json'),('EXPECTED_ROOT_CURRENT_FREEZE.json',A/'ROOT_ACTUAL_CURRENT_FREEZE_INSPECTION.json'),('EXPECTED_CURRENT_ADMIN.json',C/'status.json'),('EXPECTED_CURRENT_DEPENDENCIES.json',C/'CURRENT_DEPENDENCIES.json'),('EXPECTED_PREVIOUS_POST.json',P/'post_acceptance_verification.json'),('EXPECTED_PREVIOUS_ROOT_POST.json',P/'ROOT_ACTUAL_POST_INSPECTION.json')]:put(name,load(path))
    keys=['whole_manifest','root_whole_inspection','root_capture_operator','previous_mirror','previous_post','previous_root_post','acceptance_source_manifest','acceptance_source_verdict','root_source_inspection']
    draft={'schema':'pr46-root-approved-immutable-acceptance-bindings/v1','status':'PENDING_ROOT_SOURCE_AND_PREDECESSOR_READING','created_utc':None,'root_full_current_read_completed':False,'root_full_whole_read_completed':False,'root_acceptance_source_review_completed':False,'independent_whole_current_pass':False,'root_actual_PR45_predecessor_read_completed':False,'mandatory_corrections':[],'original_substantive_attempts':0,'original_source_verification_responses':1,'new_substantive_attempts':0,'audit_turns':0,**{k:None for k in keys}}
    put('DRAFT_ROOT_IMMUTABLE_BINDINGS.json',draft)
    plan={**SCIENCE,'schema':'pr46-root-reviewed-final-plan/v1','plan_status':'PENDING_ROOT_FULL_REVIEW_AND_ACTUAL_RECONCILIATION','pr':46,'problem_id':30004438,'original_head':'a39d178b10f75fb127058b08e0d0002b3ae97f8a','original_base':'c6975ca76f9f667f1250ba403d0e6da2aafe14d0','original_github_base':'c6975ca76f9f667f1250ba403d0e6da2aafe14d0','reviewed_candidate_manifest_sha256':sha((C/'MANIFEST.json').read_bytes()),'current_dependencies_sha256':sha((C/'CURRENT_DEPENDENCIES.json').read_bytes()),'whole_manifest_sha256':None,'preparation_manifest_sha256':None,'partial_valid':None,'root_bindings':None,'root_bindings_sha256':None,'root_full_current_read_completed':False,'root_full_whole_read_completed':False,'root_acceptance_source_review_completed':False,'independent_whole_current_pass':False,'root_actual_PR45_predecessor_read_completed':False,'immutable_evidence_references':[],'science_reexecution_of_current':False,'historical_PASS_transferred':False,'mandatory_corrections':[],'scientific_scope':SCOPE}
    put('DRAFT_FINAL_PLAN.json',plan)
    inputs={'schema':'pr46-acceptance-source-input-bindings/v1','whole_binding_completed':False,'closed_whole_manifest':None,'closed_whole_result':None,'closed_whole_report':None,'closed_root_whole_inspection':None,'closed_whole_external_inventory':None,'external_input_rows':[],'external_input_count':None,'root_whole_read_completed_utc':None,'previous_mirror':pin(P/'state_mirror_bindings.json'),'previous_post':pin(P/'post_acceptance_verification.json'),'previous_root_post':pin(P/'ROOT_ACTUAL_POST_INSPECTION.json'),'pins':{}}
    for path in [A/'snapshot_manifest.json',A/'ROOT_PRIMARY_READ_LEDGER.json',A/'ROOT_SCIENCE_CARD.json',A/'ROOT_ACTUAL_CURRENT_FREEZE_INSPECTION.json',A/'ROOT_CURRENT_INPUT_PREIMAGES.json',A/'ROOT_MATHEMATICAL_REVIEW.md',P/'state_mirror_bindings.json',P/'state_mirror_plan.json',P/'state_mirror_receipt.json',P/'ROOT_ACTUAL_POST_INSPECTION.json',P/'post_acceptance_verification.json',P/'ROOT_POST_INSPECTION_PRELAUNCH_SOURCE.py',P/'root_complete_actual_post_inspection_capture/CAPTURE.json']:
        inputs['pins'][path.relative_to(A).as_posix() if path.is_relative_to(A) else str(path.relative_to(R))]=pin(path)
    put('INPUT_BINDINGS_PENDING_ROOT.json',inputs);put('INPUT_BINDINGS.json',inputs)
    put('EXPECTED_NATIVE_TRANSITION.json',{'schema':'pr46-prospective-native-transition/v1','before':{'targets':36,'consumed_substantive_turns':44,'primary_acceptances':35,'duplicate_mirrors':1,'completed':35,'current_pr':46},'after':{'targets':37,'consumed_substantive_turns':44,'primary_acceptances':36,'duplicate_mirrors':1,'completed':36,'current_pr':47,'program_completion_estimate_percent':20.0},'original_attempts':'0/5','original_source_verification_responses':1,'new_substantive_attempts':0,'audit_turns':0,'history_events_added':1,'entire_old_states_and_history_prefix_preserved':True,'new_duplicate_added':False,'whole_inventory_derived_preserving179others':True,'proposal_executed':False,'selected_id':'30004438','selected_status':'already_solved','predecessor_pr':45,'predecessor_merge':load(P/'post_acceptance_verification.json')['merge_commit'],'predecessor_tree':load(P/'post_acceptance_verification.json')['merge_tree']})
    put('SOURCE_STATUS.json',{'schema':'pr46-acceptance-source-status/v1','status':'PENDING_GENUINE_CLOSED_WHOLE_ROOT_READING','production_imported_compiled_executed':False,'future_acceptance_approved':False,'whole_binding_completed':False,'original_substantive_attempts':0,'original_source_verification_responses':1,'new_substantive_attempts':0,'audit_turns':0,'discovery_credit_percent':0})
    print(json.dumps({'status':'SOURCE_AUTHORED_PENDING_WHOLE','production_executed':False,'future_acceptance_approved':False,'generated_sources':6,'current_manifest':sha((C/'MANIFEST.json').read_bytes()),'whole_binding_completed':False},sort_keys=True))
if __name__=='__main__': main()
