# PR60 independent initial geometry/PDE scope

Prepared before reading candidate, author program, historical review, or any other fresh family. Source directly read: Danny Calegari, Problems in Foliations and Laminations of 3-manifolds, arXiv math/0209081v1 (2002-09-08, version 0.78), Question 13.1 and its adjacent remarks, https://arxiv.org/html/math/0209081.

The question asks whether every minimal taut C² foliation of an atoroidal 3-manifold with nonzero Godbillon–Vey pairing admits a defining 1-form alpha and associated omega, d alpha = alpha wedge omega, whose 3-form omega wedge d omega is everywhere nonnegative or everywhere nonpositive. This is a weak pointwise sign question; strict contact positivity is stronger. The primary remarks separate torus and nonminimal obstructions from the specified regime, and distinguish strict contact from the allowed zero locus. I have not read the candidate or claimed an answer.

## Initial independently derived audit hypotheses

1. Global admissibility. A global nonzero alpha is possible precisely when the normal line bundle is trivial (coorientation); oriented M and global volume are needed to translate a top form to a scalar sign. Where assumed, fix these explicitly rather than inventing them from tautness. On a connected cooriented foliation all defining forms in the chosen coorientation have positive ratio, so alpha-prime = exp(f) alpha is globally available. An arbitrary locally selected f need not patch to one global function, and a global slice for gauge freedom must itself be proved.

2. PDE versus gauge class. A derived first-order transport equation is an exact reformulation only for the class of variations actually represented. Solving a fixed-alpha subproblem, ruling out one gauge/slice, or solving in one flowbox does not decide existence over every defining alpha and every admissible omega. There can be nontrivial leafwise cohomology and global period compatibility. Minimality of leaves does not assert that the particular characteristic vector field is nonvanishing, minimal, has a global cross-section, or has a smooth inverse transport operator.

3. Global transport tests. For L_X u + a u = b on a closed manifold, an invariant integrating-factor/periodic-orbit compatibility condition is necessary; along a closed orbit the monodromy identity must hold. For a = 0, an invariant finite measure requires integral b = 0. Even dense irrational-flow characteristics do not imply smooth solvability: small denominators can defeat it. These are falsifiable diagnostics of a proposed transport ansatz, not counterexamples to the original foliation question unless constructed from admissible foliations and invariant under all gauges.

4. Cohomology is insufficient. A top-degree class with positive integral has positive representatives, but a representative of the form omega wedge d omega constrained by the same foliation need not realize every exact perturbation. The missing surjectivity is central. Opposite-sign representatives in one gauge or outside the atoroidal/minimal regime are not a disproof.

5. Weak sign and attainment. A maximizing or approximate sequence of gauges does not yield a genuine weak-sign representative without topology/regularity bounds and a convergent subsequence whose limit is still globally nonvanishing and satisfies the defining relation. Weak sign alone provides no uniform positive margin; zeros invalidate promotion to contact or Euler-class obstructions. Nonzero total integral excludes the identically-zero representative but allows a nonempty zero set.

6. Regularity. The target explicitly allows C² foliations. Smooth local identities may be a useful conditional reduction, but applicability at the target regularity and the meaning of derivatives and pointwise sign must be supplied rather than inferred from a smooth diagnostic. The classical Godbillon–Vey invariant is available at C²; that fact does not automatically justify every additional differentiability or compactness step in a smooth PDE proof.

Success criterion for this family: verify exact global hypotheses and any asserted existence/obstruction; identify the strongest true conditional reduction and exact unsolved gap. Do not solve a different strict-sign problem. No candidate/native/Git/remote changes, no external human contact, no novelty, human peer-review, formal-proof or ROOT-acceptance claim.
