"""Ordered group-word checks of cited virtual cocycles and welded descent."""
from itertools import product
from collections import Counter
from pathlib import Path
import json
C=Counter();one=((),0)
# Coefficients are Free(a,b) x Z(z), or the cyclic group generated by a.
def mul(a,b,mode):
 w=list(a[0])
 for q in b[0]:
  if w and ((mode=='C2' and q==w[-1]) or q==-w[-1]):w.pop()
  else:w.append(q)
 return tuple(w),a[1]+b[1]

def ops(case):
 if case=='original':
  r=lambda x,y:(y,x);s=lambda x,y:(1-y,1-x);f=lambda x,y:((1,),0) if x!=y else one;g=lambda x,y:one
 elif case=='derived':
  r=lambda x,y:(1-y,1-x);s=lambda x,y:(y,x);f=lambda x,y:((1,),0) if x==y else one;g=lambda x,y:one
 else:
  r=lambda x,y:(y,x);s=r;f=lambda x,y:one if x==y else (((1,) if x==0 else (2,)),0);g=lambda x,y:one if x==y else ((),1 if x==0 else -1)
 return r,s,f,g

def step(state,k,i,case,mode):
 r,s,f,g=ops(case);state=list(state);x,l,u=state[i];y,m,v=state[i+1]
 if k==0:
  a,b=r(x,y);state[i]=(a,m,v);state[i+1]=(b,l,mul(u,f(x,y),mode))
 else:
  a,b=s(x,y);gg=g(x,y);state[i]=(a,m,mul(v,gg,mode));state[i+1]=(b,l,mul(u,gg,mode))
 return tuple(state)
def word(state,w,case,mode):
 for k,i in reversed(w):state=step(state,k,i,case,mode)
 return state
rels=[('YBE_r',[(0,0),(0,1),(0,0)],[(0,1),(0,0),(0,1)]),('YBE_s',[(1,0),(1,1),(1,0)],[(1,1),(1,0),(1,1)]),('s_square',[(1,0),(1,0)],[]),('virtual',[(1,0),(0,1),(1,0)],[(1,1),(0,0),(1,1)]),('welded',[(1,0),(0,1),(0,0)],[(0,1),(0,0),(1,1)])]
fail={}
for case,mode in [('original','Z'),('derived','Z'),('original','C2'),('derived','C2'),('free_twist','free')]:
 count=0
 for colors in product(range(2),repeat=3):
  state=tuple((x,i,one) for i,x in enumerate(colors))
  for name,L,R in rels:
   same=word(state,L,case,mode)==word(state,R,case,mode)
   if mode=='Z' and name=='welded':count+=not same
   else:assert same,(case,mode,colors,name);C[case+'_'+mode+'_'+name]+=1
 if mode=='Z':assert count>0;fail[case]=count;C['virtual_only_failure_detected']+=1
 # Direct general welded coefficient formulas, independently from lifted words.
 r,s,f,g=ops(case)
 for x,y,z in product(range(2),repeat=3):
  a,b=r(x,y);c,d=r(b,z);gg1=g(a,c);gg2=g(y,z)
  L=mul(f(x,y),f(b,z),mode);h,k=s(y,z);ll,mm=r(x,h);R=mul(f(x,h),f(mm,k),mode)
  if mode!='Z':assert gg1==gg2 and L==R;C['direct_weld_equations']+=1
# All-n color-only transport tested across multiple finite strand counts.
for mode in ['Z','C2']:
 for n in range(2,7):
  for colors in product(range(2),repeat=n):
   state=tuple((x,i,one) for i,x in enumerate(colors))
   H=lambda st:tuple((x^(i%2),l,u) for i,(x,l,u) in enumerate(st))
   for i in range(n-1):
    for k in [0,1]:
     assert H(step(state,k,i,'original',mode))==step(H(state),k,i,'derived',mode);C['color_only_weighted_intertwiner']+=1
assert mul(((1,),0),((2,),0),'free')!=mul(((2,),0),((1,),0),'free');C['nonabelian_control']+=1
print(json.dumps({'status':'PASS','exact_assertions':sum(C.values()),'families':dict(C),'infinite_cyclic_weld_failures_out_of_8':fail,'scope':'Ordered strand products, not abelianized whole-crossing weights. Cited general-s virtual family descends exactly when a^2=1 and then transfers locally; a separate twist-second example retains noncommuting a,b. General Q1/Q2 unresolved.'},indent=2))
