"""Own exhaustive finite controls for Turn 1's commuting-permutation theorem."""
from itertools import permutations,product
from collections import Counter
import json
C=Counter()
def comp(f,g):return tuple(f[g[x]] for x in range(len(f)))
def inv(f):return tuple(f.index(x) for x in range(len(f)))
def power(f,k):
 if k<0:return power(inv(f),-k)
 o=tuple(range(len(f)))
 for _ in range(k):o=comp(f,o)
 return o

def pair(op,x,i):return x[:i]+op(x[i],x[i+1])+x[i+2:]
def word(ops,x):
 for op,i in reversed(ops):x=pair(op,x,i)
 return x
families=0
for m in (2,3):
 perms=list(permutations(range(m)))
 for f,g,h in product(perms,repeat=3):
  if any(comp(a,b)!=comp(b,a) for a,b in [(f,g),(f,h),(g,h)]):continue
  families+=1;fi=inv(f);hi=inv(h)
  r=lambda x,y:(f[y],g[x]);ss=lambda x,y:(h[y],hi[x]);rr=lambda x,y:(y,f[g[x]])
  qq=lambda x,y:(h[fi[y]],f[hi[x]]);tt=lambda x,y:(y,x)
  R=lambda x,y:(f[hi[y]],h[g[x]])
  for x in product(range(m),repeat=3):
   for a,b in [(r,ss),(rr,qq),(R,tt)]:
    assert word([(a,0),(a,1),(a,0)],x)==word([(a,1),(a,0),(a,1)],x);C['YBE_r']+=1
    assert word([(b,0),(b,1),(b,0)],x)==word([(b,1),(b,0),(b,1)],x);C['YBE_s']+=1
    assert word([(b,0),(b,0)],x)==x;C['involutive_s']+=1
    assert word([(b,0),(a,1),(b,0)],x)==word([(b,1),(a,0),(b,1)],x);C['virtual']+=1
    assert word([(b,0),(a,1),(a,0)],x)==word([(a,1),(a,0),(b,1)],x);C['welded']+=1
  for n in (2,3,4):
   for x in product(range(m),repeat=n):
    J=lambda v:tuple(power(f,i)[v[i]] for i in range(n))
    H=lambda v:tuple(power(h,i)[v[i]] for i in range(n))
    for i in range(n-1):
     assert J(pair(r,x,i))==pair(rr,J(x),i);C['classical_guitar']+=1
     assert J(pair(ss,x,i))==pair(qq,J(x),i);C['virtual_guitar_local']+=1
     assert H(pair(r,x,i))==pair(R,H(x),i);C['permutation_violin_r']+=1
     assert H(pair(ss,x,i))==pair(tt,H(x),i);C['permutation_violin_s']+=1
     # An h-diagonal invariant weight, generated by its orbit minimum.
     def weight(a,b):
      orb=[];u,v=a,b
      for j in range(6):orb.append((u,v));u,v=h[u],h[v]
      a,b=min(orb);return 2+a*m+b
     hx=H(x)
     assert weight(x[i],x[i+1])==weight(hx[i],hi[hx[i+1]]);C['weight_locality']+=1
print(json.dumps({'status':'PASS','commuting_families':families,'exact_assertions':sum(C.values()),'families':dict(C),'scope':'Finite diagnostics of universally proved commuting-permutation subclass and sufficient weight invariance. Not a resolution of the two general source questions.'},indent=2))
