#!/usr/bin/env python3
"""Deterministic exact audit of the smallest bounded-defect critical shells.

This is a calibration/search tool, not the universal proof.  It enumerates
13,704 distinct five-complex strongly connected topologies generated by a
Hamilton cycle and at most three added edges.  For each nonconservative graph
it checks four exact positive-integer rate assignments.  The stationary
level drift is computed by the three-state Markov-chain tree formula over Q[n].
"""
from __future__ import annotations
import hashlib,itertools,json,random
from fractions import Fraction
from pathlib import Path
import sympy as sp

NAMES=['X','C','D','VC','VD']; PH=[0,1,2,1,2]; QLEV=[0,0,0,1,1]; FAC=[2,1,1,1,1]
EDGES=list(itertools.permutations(range(5),2))
Z=[(2,0,0),(0,1,0),(0,0,1),(0,1,0),(0,0,1)]

def _add(a,b):
 n=max(len(a),len(b));c=[Fraction(0)]*n
 for i in range(n):c[i]=(a[i] if i<len(a) else 0)+(b[i] if i<len(b) else 0)
 while len(c)>1 and c[-1]==0:c.pop()
 return c

def _mul(a,b):
 c=[Fraction(0)]*(len(a)+len(b)-1)
 for i,x in enumerate(a):
  for j,y in enumerate(b):c[i+j]+=x*y
 while len(c)>1 and c[-1]==0:c.pop()
 return c

def _scale(a,s):return [x*s for x in a]

def conservative(es):
 A=sp.Matrix([[Z[j][a]-Z[i][a] for i,j in es] for a in range(3)])
 m=sp.Matrix([[QLEV[j]-QLEV[i] for i,j in es]])
 return A.rank()==A.col_join(m).rank()

def asymptotic(es,ks):
 off=[[[Fraction(0)] for _ in range(3)] for _ in range(3)];d=[[Fraction(0)] for _ in range(3)]
 for (i,j),k in zip(es,ks):
  poly=[Fraction(k*FAC[i])] if QLEV[i]==0 else [Fraction(0),Fraction(k*FAC[i])]
  d[PH[i]]=_add(d[PH[i]],_scale(poly,QLEV[j]-QLEV[i]))
  if PH[i]!=PH[j]:off[PH[i]][PH[j]]=_add(off[PH[i]][PH[j]],poly)
 q01,q02=off[0][1],off[0][2];q10,q12=off[1][0],off[1][2];q20,q21=off[2][0],off[2][1]
 t0=_add(_add(_mul(q10,q20),_mul(q10,q21)),_mul(q12,q20))
 t1=_add(_add(_mul(q01,q21),_mul(q01,q20)),_mul(q02,q21))
 t2=_add(_add(_mul(q02,q12),_mul(q02,q10)),_mul(q01,q12))
 den=_add(_add(t0,t1),t2);num=_add(_add(_mul(t0,d[0]),_mul(t1,d[1])),_mul(t2,d[2]))
 while len(num)>1 and num[-1]==0:num.pop()
 while len(den)>1 and den[-1]==0:den.pop()
 return len(num)-len(den),num[-1]/den[-1],num,den

def run_audit()->dict:
 seen=set();graphs=0;rate_cases=0;nonconservative=0;bad=[];critical=[]
 digest=hashlib.sha256()
 for perm in itertools.permutations(range(1,5)):
  cyc=(0,)+perm;base=frozenset((cyc[i],cyc[(i+1)%5]) for i in range(5));remain=[e for e in EDGES if e not in base]
  for nextra in range(4):
   for extra in itertools.combinations(remain,nextra):
    es=tuple(sorted(base|set(extra)))
    if es in seen:continue
    seen.add(es);graphs+=1
    if conservative(es):continue
    nonconservative+=1
    sets=[(1,)*len(es)];rng=random.Random(hash(es)&0xffffffff)
    for _ in range(3):sets.append(tuple(rng.randint(1,9) for _ in es))
    for ks in sets:
     rate_cases+=1;power,coef,num,den=asymptotic(es,ks)
     payload=(es,ks,power,str(coef),tuple(map(str,num)),tuple(map(str,den)))
     digest.update(repr(payload).encode())
     if coef>=0:bad.append(payload)
     if power<0:critical.append(payload)
 return {'graphs':graphs,'nonconservative_graphs':nonconservative,'exact_rate_cases':rate_cases,
         'nonnegative_leading_cases':len(bad),'negative_power_critical_cases':len(critical),
         'sha256':digest.hexdigest()}

def main()->None:
 out=run_audit();print(json.dumps(out,indent=2,sort_keys=True))
 if out['nonnegative_leading_cases'] or out['negative_power_critical_cases']:raise SystemExit(1)

if __name__=='__main__':main()
