#!/usr/bin/env python3
"""Independent graph/algebra/path audit for a final-schema primary stream.

Primary JSON is comparison input only.  Every graph reduction, child
completion, displayed-tree descriptor, invariant pullback, and strict sign is
regenerated by the clean-room modules.
"""

from __future__ import annotations

from collections import Counter, defaultdict
from pathlib import Path
import argparse
import gzip
import hashlib
import itertools
import json
import sys

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))

from graph_model import (
    RootedGraph, decorated_mixed_relation, digest, mixed_code,
    rooted_graph_id, stable_json, standard_semidirected_audit,
)
from pq_extension import all_segment_insertions
from relation_universe import graph_from_object


def sha(path):
    h = hashlib.sha256()
    with path.open("rb") as stream:
        for block in iter(lambda: stream.read(1 << 20), b""):
            h.update(block)
    return h.hexdigest()


def logical_sha(path):
    h = hashlib.sha256()
    with gzip.open(path, "rb") as stream:
        for block in iter(lambda: stream.read(1 << 20), b""):
            h.update(block)
    return h.hexdigest()


def load_jsonl_gzip(path):
    with gzip.open(path, "rt") as stream:
        return [json.loads(line) for line in stream if line.strip()]


def load_family(tag):
    with gzip.open(HERE / "certificates" / f"family_{tag}.json.gz", "rt") as stream:
        obj = json.load(stream)
    family = tuple(
        tuple((int(coefficient), tuple(int(i) for i in monomial)) for coefficient, monomial in relation)
        for relation in obj["relations"]
    )
    return obj, family


def relabel_one_leaf(graph, old_label, new_label):
    labels = graph.label_map
    vertices = [v for v, label in labels.items() if label == old_label]
    if len(vertices) != 1:
        raise ValueError(("target restoration role not unique", old_label, vertices))
    if new_label in labels.values():
        raise ValueError(("new selected label already present", new_label))
    labels[vertices[0]] = new_label
    return RootedGraph.make(graph.arcs, graph.root, labels)


def normalized_state_payload(fixed_full_root_case_id, source, target,
                             port_matching, selected_port_count,
                             remaining_target_roles):
    relation = decorated_mixed_relation(source, target, tuple(map(tuple, port_matching)))
    payload = {
        "fixed_full_root_case_id": fixed_full_root_case_id,
        "source_rooted_graph_id": rooted_graph_id(source),
        "target_rooted_graph_id": rooted_graph_id(target),
        "decorated_relation_code": relation["code"],
        "direction": "source_to_target",
        "port_matching": relation["port_matching"],
        "selected_port_count": int(selected_port_count),
        "remaining_target_roles": tuple(remaining_target_roles),
    }
    return payload, digest(payload)


def graph_library(path):
    records = load_jsonl_gzip(path)
    graphs = {}
    problems = []
    for rec in records:
        gid = rec["graph_id"]
        if gid in graphs: problems.append(("duplicate graph id", gid))
        graph = graph_from_object(rec["rooted_graph"])
        audit = standard_semidirected_audit(graph)
        if not audit["ok"]: problems.append(("standard S_TC", gid, audit))
        graphs[gid] = graph
    return records, graphs, problems


def polynomial_library(path):
    records = load_jsonl_gzip(path)
    polynomials = {}
    problems = []
    for record in records:
        polynomial_id = record.get("polynomial_id")
        if not isinstance(polynomial_id, str) or len(polynomial_id) != 64:
            problems.append(("invalid polynomial id", polynomial_id))
            continue
        if polynomial_id in polynomials:
            problems.append(("duplicate polynomial id", polynomial_id))
        variable_count = int(record.get("variable_count", -1))
        terms = record.get("terms", [])
        seen = set()
        for monomial, coefficient in terms:
            monomial = tuple(int(x) for x in monomial)
            if len(monomial) != variable_count:
                problems.append((polynomial_id, "polynomial variable-count mismatch"))
            if monomial in seen:
                problems.append((polynomial_id, "duplicate polynomial monomial"))
            if int(coefficient) == 0:
                problems.append((polynomial_id, "zero polynomial coefficient"))
            seen.add(monomial)
        if terms != sorted(terms):
            problems.append((polynomial_id, "unsorted polynomial body"))
        polynomials[polynomial_id] = record
    if len({digest({"variable_count": r["variable_count"], "terms": r["terms"]})
            for r in polynomials.values()}) != len(polynomials):
        problems.append("duplicate polynomial bodies under distinct IDs")
    return records, polynomials, problems


def audit_descriptor_normalization(graph_records, graphs):
    from jc_exact import canonical_descriptor_key, descriptor_from_graph

    groups = defaultdict(list)
    changed_without = 0
    changed_wrong = 0
    for record in graph_records:
        graph = graphs[record["graph_id"]]
        minimum = canonical_descriptor_key(descriptor_from_graph(graph, "minimum"))
        without = canonical_descriptor_key(descriptor_from_graph(graph, "none"))
        wrong = canonical_descriptor_key(
            descriptor_from_graph(graph, "wrong_four_port_universe")
        )
        changed_without += minimum != without
        changed_wrong += minimum != wrong
        groups[record["standard_mixed_code_sha256"]].append(
            (record["graph_id"], minimum, without, wrong)
        )
    multi_root_groups = [rows for rows in groups.values() if len(rows) > 1]
    minimum_failures = [rows for rows in multi_root_groups
                        if len({row[1] for row in rows}) != 1]
    without_failures = [rows for rows in multi_root_groups
                        if len({row[2] for row in rows}) != 1]
    wrong_failures = [rows for rows in multi_root_groups
                      if len({row[3] for row in rows}) != 1]
    failures = []
    if minimum_failures:
        failures.append(("split-complement normalization is not root invariant",
                         [[row[0] for row in rows] for rows in minimum_failures[:10]]))
    if not without_failures:
        failures.append("removing split-complement normalization was not detected")
    if not wrong_failures:
        failures.append("wrong split-complement universe was not detected")
    return {
        "graph_count": len(graph_records),
        "standard_mixed_groups": len(groups),
        "multi_root_groups": len(multi_root_groups),
        "minimum_normalization_root_invariance_failures": len(minimum_failures),
        "no_normalization_root_invariance_failures": len(without_failures),
        "wrong_normalization_root_invariance_failures": len(wrong_failures),
        "graphs_changed_without_normalization": changed_without,
        "graphs_changed_under_wrong_normalization": changed_wrong,
        "normalization": "minimum_of_selected_side_and_full_selected_complement",
        "failures": failures,
    }


def independently_expected_children(coverage, state, graphs):
    if state["terminal_classification"] != "refined_by_next_restoration":
        return set()
    remaining = tuple(state["remaining_target_roles"])
    if not remaining: return set()
    role = remaining[0]
    next_label = f"L_{state['selected_port_count']}"
    source = graphs[coverage["source_graph_id"]]
    target = relabel_one_leaf(graphs[coverage["target_graph_id"]], role, next_label)
    matching = tuple(map(tuple, state["port_matching"])) + ((next_label, next_label),)
    expected = set()
    for insertion in all_segment_insertions(source, next_label):
        _, key = normalized_state_payload(
            coverage["root_case_id"], insertion["graph"], target, matching,
            state["selected_port_count"] + 1, remaining[1:],
        )
        expected.add(key)
    return expected


def audit_paths(states, graphs):
    failures = []
    normalized = {}
    normalization_collisions = defaultdict(list)
    for sid, state in states.items():
        coverage_roots = {cov["root_case_id"] for cov in state["raw_coverage"]}
        coverage_sources = {cov["source_graph_id"] for cov in state["raw_coverage"]}
        coverage_targets = {cov["target_graph_id"] for cov in state["raw_coverage"]}
        fixed_root = state.get("fixed_full_root_case_id")
        if fixed_root is None:
            failures.append((sid, "missing fixed_full_root_case_id in state identity"))
            fixed_root = next(iter(coverage_roots)) if len(coverage_roots) == 1 else "MIXED_ROOT_CASES"
        if coverage_roots != {fixed_root}:
            failures.append((sid, "merge across fixed full root cases", sorted(coverage_roots), fixed_root))
        if coverage_sources != {state["source_graph_id"]}:
            failures.append((sid, "merge across source rooted graph IDs", sorted(coverage_sources), state["source_graph_id"]))
        if coverage_targets != {state["target_graph_id"]}:
            failures.append((sid, "merge across target rooted graph IDs", sorted(coverage_targets), state["target_graph_id"]))
        payload, key = normalized_state_payload(
            fixed_root, graphs[state["source_graph_id"]], graphs[state["target_graph_id"]],
            state["port_matching"], state["selected_port_count"],
            state["remaining_target_roles"],
        )
        normalized[sid] = key; normalization_collisions[key].append(sid)

    for key, members in normalization_collisions.items():
        if len(members) > 1:
            failures.append(("duplicate stronger normalized state identity", key, sorted(members)))
    per_path_expectations = {}
    parent_index = defaultdict(list)
    for child_sid, child in states.items():
        for cov in child["raw_coverage"]:
            parent = cov["parent_path_binding_id"]
            if parent is not None: parent_index[parent].append((child_sid, cov))

    refined = 0; paths = 0
    for sid, state in states.items():
        declared = set(state["children"])
        if state["terminal_classification"] == "refined_by_next_restoration": refined += 1
        elif declared: failures.append((sid, "terminal state has children"))
        for cov in state["raw_coverage"]:
            paths += 1
            if cov["canonical_state_id"] != sid:
                failures.append((sid, cov["path_binding_id"], "coverage state mismatch"))
            if cov["source_graph_id"] != state["source_graph_id"] or cov["target_graph_id"] != state["target_graph_id"]:
                failures.append((sid, cov["path_binding_id"], "coverage graph mismatch"))
            if state.get("fixed_full_root_case_id") != cov["root_case_id"]:
                failures.append((sid, cov["path_binding_id"], "coverage root-case mismatch"))
            actual_ids = set(cov["child_state_ids"])
            if actual_ids != declared:
                failures.append((sid, cov["path_binding_id"], "declared/per-path child mismatch"))
            emitted_ids = {child_sid for child_sid, _ in parent_index.get(cov["path_binding_id"], ())}
            if emitted_ids != actual_ids:
                failures.append((sid, cov["path_binding_id"], "emitted/per-path child mismatch"))
            try:
                expected_keys = independently_expected_children(cov, state, graphs)
            except Exception as exc:
                failures.append((sid, cov["path_binding_id"], "child regeneration exception", repr(exc)))
                continue
            actual_keys = {normalized[x] for x in actual_ids if x in normalized}
            missing_ids = actual_ids - set(states)
            if missing_ids:
                failures.append((sid, cov["path_binding_id"], "missing child records", sorted(missing_ids)))
            if expected_keys != actual_keys:
                failures.append((
                    sid, cov["path_binding_id"], "independent child-state set mismatch",
                    sorted(expected_keys - actual_keys), sorted(actual_keys - expected_keys),
                ))
            per_path_expectations[cov["path_binding_id"]] = expected_keys

    # This is the explicit first-provenance regression: all raw presentations
    # merged into one canonical state must regenerate the same complete set.
    merged_provenance_disagreements = []
    for sid, state in states.items():
        sets = {
            tuple(sorted(per_path_expectations.get(cov["path_binding_id"], ())))
            for cov in state["raw_coverage"]
        }
        if len(sets) > 1: merged_provenance_disagreements.append(sid)
    if merged_provenance_disagreements:
        failures.append(("merged provenance child disagreement", merged_provenance_disagreements[:20]))
    return {
        "state_count": len(states),
        "path_count": paths,
        "refined_state_count": refined,
        "normalized_state_count": len(normalization_collisions),
        "normalized_collision_classes": sum(len(v) > 1 for v in normalization_collisions.values()),
        "merged_provenance_child_disagreements": len(merged_provenance_disagreements),
        "failures": failures,
    }


def audit_terminals(states, graphs, family, primary_polynomials,
                    invariant_metadata):
    from derived_invariants import (
        derive_pair_separator_on_quartet, exact_relation_pullback,
        relation_poly,
    )
    from family_engine import (
        classify_containment_pair, exact_family_deck,
        find_generic_identity_separator,
        find_generic_identity_separator_on_quartet,
    )
    from jc_exact import (
        canonical_descriptor_key, descriptor_from_graph, p_hash,
        quartet_coordinates,
    )
    counts = Counter(); failures = []; terminal_rows = []
    source_deck_cache = {}
    primary_ids_referenced = Counter()
    primary_exact_sha_by_id = defaultdict(set)
    descriptor_binding_ids = defaultdict(set)
    prescribed_quartet_witnesses = 0
    dynamic_nullspace_witnesses = 0
    for index, (sid, state) in enumerate(sorted(states.items())):
        terminal = state["terminal_classification"]
        if terminal == "refined_by_next_restoration": continue
        counts[terminal] += 1
        source = graphs[state["source_graph_id"]]; target = graphs[state["target_graph_id"]]
        if terminal in ("support_prefix_labelled_isomorphism", "labelled_isomorphism"):
            source_code = mixed_code(source)[0]; target_code = mixed_code(target)[0]
            if source_code != target_code:
                failures.append((sid, terminal, "not labelled-isomorphic"))
            terminal_rows.append({
                "state_id": sid, "classification": "labelled_isomorphism",
                "source_mixed_sha256": digest(source_code),
                "target_mixed_sha256": digest(target_code),
            })
            continue
        if terminal in ("support_prefix_triangle_redirection", "ordinary_triangle_redirection"):
            source_code = mixed_code(source, True)[0]; target_code = mixed_code(target, True)[0]
            if source_code != target_code:
                failures.append((sid, terminal, "not T-related"))
            terminal_rows.append({
                "state_id": sid, "classification": "ordinary_triangle_redirection",
                "source_t_quotient_sha256": digest(source_code),
                "target_t_quotient_sha256": digest(target_code),
            })
            continue
        if terminal != "generic_polynomial_separation":
            failures.append((sid, "unknown terminal classification", terminal)); continue
        p = int(state["selected_port_count"])
        sdesc = descriptor_from_graph(source); tdesc = descriptor_from_graph(target)
        witness = state.get("probe_witness", {})
        primary_id = witness.get("source_pullback_id")
        primary_exact_sha = witness.get("source_pullback_exact_sha256")
        chunk = witness.get("quartet_chunk")
        primary_invariant = witness.get("invariant_index")
        quartets = tuple(itertools.combinations(range(p), 4))
        if not isinstance(chunk, int) or not (0 <= chunk < len(quartets)):
            failures.append((sid, "invalid primary quartet chunk", chunk))
            continue
        if not isinstance(primary_invariant, int) or primary_invariant < 0:
            failures.append((sid, "invalid primary invariant index", primary_invariant))
            continue
        if primary_invariant >= len(invariant_metadata):
            failures.append((sid, "primary invariant index absent from metadata",
                             primary_invariant))
            continue
        primary_quartet = quartets[chunk]
        if primary_id not in primary_polynomials:
            failures.append((sid, "missing primary polynomial body", primary_id))
            continue
        if witness.get("target_pullback") != "0":
            failures.append((sid, "primary witness does not claim target zero"))
        if not isinstance(primary_exact_sha, str) or len(primary_exact_sha) != 64:
            failures.append((sid, "invalid primary exact-pullback hash"))
        primary_ids_referenced[primary_id] += 1
        primary_exact_sha_by_id[primary_id].add(primary_exact_sha)
        descriptor_binding_ids[(
            canonical_descriptor_key(sdesc), p, primary_quartet,
            primary_invariant,
        )].add((primary_id, primary_exact_sha))

        # The clean room does not trust the primary invariant selection.  It
        # independently finds a target-zero/source-nonzero invariant from its
        # separately derived family on the exact quartet claimed by the
        # primary relation.  This binds every accepted polynomial witness to
        # the exact source and target rooted graph IDs rather than to a cached
        # topology label.
        result = find_generic_identity_separator_on_quartet(
            sdesc, tdesc, primary_quartet, p, family,
        )
        dynamic_result = None
        if result is not None:
            prescribed_quartet_witnesses += 1
        else:
            dynamic_result = derive_pair_separator_on_quartet(
                sdesc, tdesc, primary_quartet, max_degree=6,
                arm_degree_hint=invariant_metadata[primary_invariant][
                    "port_arm_multidegree"
                ],
            )
            if dynamic_result is not None:
                prescribed_quartet_witnesses += 1
                dynamic_nullspace_witnesses += 1
                result = {
                    "classification": "generic_identity_separation",
                    "quartet": primary_quartet,
                    "dynamic_relation": dynamic_result["relation"],
                    "dynamic_degree": dynamic_result["degree"],
                    "dynamic_arm_degree": dynamic_result["arm_degree"],
                }
            else:
                result = find_generic_identity_separator(sdesc, tdesc, p, family)
        if result is None:
            skey = (sdesc.key, p)
            if skey not in source_deck_cache:
                source_deck_cache[skey] = exact_family_deck(sdesc, p, family)
            result = classify_containment_pair(source_deck_cache[skey], tdesc, p, family)
        if result["classification"] not in ("generic_identity_separation", "strict_sign_separation"):
            failures.append((sid, terminal, "clean-room family did not separate", result["classification"]))
        else:
            quartet = tuple(result["quartet"])
            if "dynamic_relation" in result:
                invariant = None
                dynamic_relation = result["dynamic_relation"]
                source_pullback = relation_poly(
                    quartet_coordinates(sdesc, quartet),
                    dynamic_relation, sdesc.variable_count,
                )
                target_pullback = relation_poly(
                    quartet_coordinates(tdesc, quartet),
                    dynamic_relation, tdesc.variable_count,
                )
                independent_relation_sha256 = digest(dynamic_relation)
            else:
                invariant = int(result["invariant"])
                source_pullback = exact_relation_pullback(
                    sdesc, quartet, family[invariant],
                )
                target_pullback = exact_relation_pullback(
                    tdesc, quartet, family[invariant],
                )
                independent_relation_sha256 = digest(family[invariant])
            if result["classification"] == "generic_identity_separation":
                if not source_pullback or target_pullback:
                    failures.append((sid, "invalid exact identity separator after regeneration"))
            else:
                if source_pullback or not target_pullback:
                    failures.append((sid, "invalid strict-sign separator after regeneration"))
            terminal_rows.append({
                "state_id": sid,
                "classification": result["classification"],
                "source_rooted_graph_id": state["source_graph_id"],
                "target_rooted_graph_id": state["target_graph_id"],
                "selected_port_count": p,
                "quartet": list(quartet),
                "invariant": invariant,
                "independent_relation_sha256": independent_relation_sha256,
                "independent_dynamic_degree": result.get("dynamic_degree"),
                "independent_dynamic_arm_degree": result.get("dynamic_arm_degree"),
                "source_pullback_sha256": p_hash(source_pullback),
                "source_pullback_term_count": len(source_pullback),
                "target_pullback_sha256": p_hash(target_pullback),
                "target_pullback_term_count": len(target_pullback),
                "sign": result.get("sign"),
                "primary_quartet": list(primary_quartet),
                "primary_invariant_index": primary_invariant,
                "primary_polynomial_id": primary_id,
                "primary_polynomial_body_sha256": digest({
                    "variable_count": primary_polynomials[primary_id]["variable_count"],
                    "terms": primary_polynomials[primary_id]["terms"],
                }),
                "primary_exact_pullback_sha256": primary_exact_sha,
                "independent_witness_uses_primary_quartet": tuple(quartet) == primary_quartet,
            })
    inconsistent_primary_exact = {
        polynomial_id: sorted(values)
        for polynomial_id, values in primary_exact_sha_by_id.items()
        if len(values) != 1
    }
    if inconsistent_primary_exact:
        failures.append(("primary polynomial ID has inconsistent exact hashes",
                         inconsistent_primary_exact))
    inconsistent_descriptor_bindings = {
        digest([key[0], key[1], key[2], key[3]]): sorted(values)
        for key, values in descriptor_binding_ids.items()
        if len(values) != 1
    }
    if inconsistent_descriptor_bindings:
        failures.append(("descriptor/invariant binding has multiple polynomial bodies",
                         inconsistent_descriptor_bindings))
    unreferenced_primary = sorted(set(primary_polynomials) - set(primary_ids_referenced))
    if unreferenced_primary:
        failures.append(("unreferenced primary polynomial bodies", unreferenced_primary))
    return {
        "terminal_counts": dict(sorted(counts.items())),
        "independent_terminal_record_count": len(terminal_rows),
        "terminal_record_commitment": digest(terminal_rows),
        "polynomial_binding_audit": {
            "generic_state_count": sum(primary_ids_referenced.values()),
            "primary_polynomial_bodies": len(primary_polynomials),
            "primary_polynomial_bodies_referenced": len(primary_ids_referenced),
            "descriptor_invariant_binding_classes": len(descriptor_binding_ids),
            "descriptor_invariant_binding_conflicts": len(inconsistent_descriptor_bindings),
            "primary_exact_hash_conflicts": len(inconsistent_primary_exact),
            "independent_same_quartet_separator_count": prescribed_quartet_witnesses,
            "independent_dynamic_nullspace_separator_count": dynamic_nullspace_witnesses,
            "independent_fallback_quartet_count": (
                sum(primary_ids_referenced.values()) - prescribed_quartet_witnesses
            ),
        },
        "terminal_records": terminal_rows,
        "failures": failures,
    }


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--relations", type=Path, required=True)
    parser.add_argument("--graphs", type=Path, required=True)
    parser.add_argument("--roots", type=Path, required=True)
    parser.add_argument("--polynomials", type=Path)
    parser.add_argument("--summary", type=Path)
    parser.add_argument("--expected-summary-sha256")
    parser.add_argument("--invariant-metadata", type=Path)
    parser.add_argument("--family-tag", choices=("n3", "n4_minimum"), required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--path-only", action="store_true")
    parser.add_argument("--terminal-records-output", type=Path)
    args = parser.parse_args()

    graph_records, graphs, graph_problems = graph_library(args.graphs)
    descriptor_audit = audit_descriptor_normalization(graph_records, graphs)
    state_records = load_jsonl_gzip(args.relations)
    root_records = load_jsonl_gzip(args.roots)
    if args.polynomials is None and not args.path_only:
        parser.error("--polynomials is required for a complete terminal audit")
    if args.invariant_metadata is None and not args.path_only:
        parser.error("--invariant-metadata is required for a complete terminal audit")
    if args.polynomials is not None:
        polynomial_records, primary_polynomials, polynomial_problems = polynomial_library(args.polynomials)
    else:
        polynomial_records, primary_polynomials, polynomial_problems = [], {}, []
    invariant_metadata = []
    invariant_metadata_problems = []
    if args.invariant_metadata is not None:
        metadata_object = json.loads(args.invariant_metadata.read_text())
        invariant_metadata = metadata_object.get("records", [])
        if len(invariant_metadata) != 84:
            invariant_metadata_problems.append((
                "invariant metadata record count", len(invariant_metadata), 84,
            ))
        for expected_index, record in enumerate(invariant_metadata):
            if record.get("index") != expected_index:
                invariant_metadata_problems.append((
                    "invariant metadata index", expected_index, record.get("index"),
                ))
            arm_degree = record.get("port_arm_multidegree")
            if (not isinstance(arm_degree, list) or len(arm_degree) != 4
                    or any(not isinstance(x, int) or x < 0 for x in arm_degree)):
                invariant_metadata_problems.append((
                    "invalid invariant arm degree", expected_index, arm_degree,
                ))

    summary_problems = []
    summary_audit = None
    if args.summary is not None:
        summary_sha = sha(args.summary)
        if args.expected_summary_sha256 and summary_sha != args.expected_summary_sha256:
            summary_problems.append(("summary SHA-256 mismatch", summary_sha,
                                     args.expected_summary_sha256))
        summary = json.loads(args.summary.read_text())
        runs = summary.get("runs", [])
        if len(runs) != 1:
            summary_problems.append(("expected one summary run", len(runs)))
            hard_cover = {}
        else:
            hard_cover = runs[0].get("hard_cover", {})
        expected_scope = "selected_port_count_and_exact_rooted_graph_id"
        expected_normalization = "minimum_of_quartet_side_and_complement_on_zero_sum_characters"
        if hard_cover.get("descriptor_cache_scope") != expected_scope:
            summary_problems.append(("descriptor cache scope", hard_cover.get("descriptor_cache_scope")))
        if hard_cover.get("descriptor_mask_normalization") != expected_normalization:
            summary_problems.append(("descriptor mask normalization",
                                     hard_cover.get("descriptor_mask_normalization")))
        stream_checks = {
            "relations": (args.relations, hard_cover.get("relation_stream_sha256"),
                          hard_cover.get("canonical_restored_relations")),
            "graphs": (args.graphs, hard_cover.get("graph_library_stream_sha256"),
                       hard_cover.get("graph_library_records")),
            "roots": (args.roots, hard_cover.get("root_case_stream_sha256"),
                      hard_cover.get("root_case_records")),
        }
        if args.polynomials is not None:
            stream_checks["polynomials"] = (
                args.polynomials, hard_cover.get("polynomial_library_stream_sha256"),
                hard_cover.get("polynomial_library_records"),
            )
        actual_counts = {
            "relations": len(state_records), "graphs": len(graph_records),
            "roots": len(root_records), "polynomials": len(polynomial_records),
        }
        stream_results = {}
        for name, (path, expected_logical, expected_count) in stream_checks.items():
            actual_logical = logical_sha(path)
            stream_results[name] = {
                "path": str(path), "physical_sha256": sha(path),
                "logical_sha256": actual_logical,
                "records": actual_counts[name],
            }
            if actual_logical != expected_logical:
                summary_problems.append((name, "logical stream hash mismatch",
                                         actual_logical, expected_logical))
            if actual_counts[name] != expected_count:
                summary_problems.append((name, "record-count mismatch",
                                         actual_counts[name], expected_count))
        summary_audit = {
            "physical_sha256": summary_sha,
            "descriptor_cache_scope": hard_cover.get("descriptor_cache_scope"),
            "descriptor_mask_normalization": hard_cover.get("descriptor_mask_normalization"),
            "streams": stream_results,
        }
    states = {}; duplicate_states = []
    for rec in state_records:
        sid = rec["state_id"]
        # The schema declares state_id unique.  Even byte-identical duplicate
        # records are a coverage failure: accepting them would let a missing
        # relation be hidden by duplicating another record without changing a
        # set-style commitment.
        if sid in states:
            duplicate_states.append(sid)
        states[sid] = rec
    if args.path_only:
        family_obj = {"normalized_sha256_without_hash": None}; family = None
    else:
        family_obj, family = load_family(args.family_tag)
    missing_graph_ids = sorted({
        gid for state in states.values()
        for gid in (state["source_graph_id"], state["target_graph_id"])
        if gid not in graphs
    })
    path_audit = audit_paths(states, graphs) if not missing_graph_ids else {"failures": [("missing graph IDs", missing_graph_ids)]}
    if args.path_only:
        terminal_audit = {"skipped": True, "failures": []}
    else:
        terminal_audit = audit_terminals(
            states, graphs, family, primary_polynomials, invariant_metadata,
        ) if not missing_graph_ids else {"failures": [("missing graph IDs", missing_graph_ids)]}
    root_ids = [x["root_case_id"] for x in root_records]
    entered = set(x for root in root_records for x in root["entry_state_ids"])
    missing_entries = sorted(entered - set(states))
    failures = []
    failures.extend(graph_problems)
    failures.extend(descriptor_audit.get("failures", ()))
    failures.extend(polynomial_problems)
    failures.extend(invariant_metadata_problems)
    failures.extend(summary_problems)
    failures.extend(("duplicate state", x) for x in duplicate_states)
    if len(root_ids) != len(set(root_ids)): failures.append("duplicate root case")
    if missing_entries: failures.append(("missing entry states", missing_entries))
    failures.extend(path_audit.get("failures", ()))
    failures.extend(terminal_audit.get("failures", ()))
    def looks_like_id(value):
        return isinstance(value, str) and len(value) == 64 and all(c in "0123456789abcdef" for c in value)
    def failure_category(item):
        if isinstance(item, (tuple, list)):
            if len(item) > 2 and looks_like_id(item[0]) and looks_like_id(item[1]) and isinstance(item[2], str):
                return item[2]
            if len(item) > 1 and looks_like_id(item[0]) and isinstance(item[1], str): return item[1]
            if item and isinstance(item[0], str): return item[0]
        return type(item).__name__
    failure_categories = Counter(failure_category(item) for item in failures)
    terminal_records = terminal_audit.pop("terminal_records", [])
    cert = {
        "schema": 1,
        "status": "VERIFIED" if not failures else "FALSE",
        "inputs": {
            str(args.relations): sha(args.relations),
            str(args.graphs): sha(args.graphs),
            str(args.roots): sha(args.roots),
            **({str(args.polynomials): sha(args.polynomials)} if args.polynomials else {}),
            **({str(args.summary): sha(args.summary)} if args.summary else {}),
            **({str(args.invariant_metadata): sha(args.invariant_metadata)}
               if args.invariant_metadata else {}),
        },
        "family_tag": args.family_tag,
        "family_sha256": family_obj["normalized_sha256_without_hash"],
        "graph_records": len(graph_records),
        "state_records": len(state_records),
        "root_case_records": len(root_records),
        "polynomial_records": len(polynomial_records),
        "summary_audit": summary_audit,
        "descriptor_normalization_audit": {
            k: v for k, v in descriptor_audit.items() if k != "failures"
        },
        "path_audit": {k: v for k, v in path_audit.items() if k != "failures"},
        "terminal_audit": {k: v for k, v in terminal_audit.items() if k != "failures"},
        "failure_count": len(failures),
        "failure_categories": dict(sorted(failure_categories.items())),
        "first_failures": failures[:50],
    }
    cert["normalized_sha256_without_hash"] = digest(cert)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(stable_json(cert) + "\n")
    if args.terminal_records_output is not None:
        args.terminal_records_output.parent.mkdir(parents=True, exist_ok=True)
        with gzip.GzipFile(filename=str(args.terminal_records_output), mode="wb", mtime=0) as stream:
            for record in terminal_records:
                stream.write((stable_json(record) + "\n").encode())
    print(stable_json({
        "status": cert["status"], "states": len(state_records),
        "roots": len(root_records), "failure_count": len(failures),
        "hash": cert["normalized_sha256_without_hash"],
    }))
    if failures: raise SystemExit(1)


if __name__ == "__main__":
    main()
