#!/usr/bin/env python3
"""Independent exact audit controls; imports no functions from the frozen author code.

Matrix controls extract only the cyclic involution using an odd group-order cofactor,
then count fixed vectors directly. Sp4 is generated by transvection closure rather
than enumerating symplectic bases. Cycle controls sum normalized integer partitions
and joint maximum-color/mass/sign-parity distributions, without coefficient recurrences.
Finite checks are implementation controls, never an asymptotic proof.
"""
from fractions import Fraction as F
from itertools import product, permutations
from collections import Counter, deque
from functools import lru_cache
from math import factorial, prod, log, exp, sqrt
from pathlib import Path
import hashlib, json, argparse, time

def vp2(x):
    assert x > 0
    k = 0
    while x % 2 == 0:
        x //= 2
        k += 1
    return k

def eye(n):
    return tuple(int(i == j) for i in range(n) for j in range(n))

def multiply(A, B, n, q):
    cols = [B[j::n] for j in range(n)]
    rows = [A[i*n:(i+1)*n] for i in range(n)]
    return tuple(sum(x*y for x, y in zip(row, col)) % q for row in rows for col in cols)

def power(A, m, n, q):
    out = eye(n)
    for digit in bin(m)[2:]:
        out = multiply(out, out, n, q)
        if digit == '1':
            out = multiply(out, A, n, q)
    return out

def cyclic_involution(A, n, q, group_order):
    odd = group_order >> vp2(group_order)
    y = power(A, odd, n, q)
    I = eye(n)
    if y == I:
        return None
    for _ in range(vp2(group_order)):
        next_y = multiply(y, y, n, q)
        if next_y == I:
            return y
        y = next_y
    raise AssertionError('Group-order bound or matrix membership failed')

@lru_cache(None)
def fixed_dimension(T, n, q):
    fixed = sum(all(sum(T[i*n+j]*v[j] for j in range(n)) % q == v[i] for i in range(n))
                for v in product(range(q), repeat=n))
    k = 0
    while fixed > 1:
        assert fixed % q == 0
        fixed //= q
        k += 1
    return k

def determinant_leibniz(A, n, q):
    total = 0
    for s in permutations(range(n)):
        inversions = sum(s[i] > s[j] for i in range(n) for j in range(i+1, n))
        total += (-1)**inversions * prod(A[i*n+s[i]] for i in range(n))
    return total % q

def summarize(matrices, n, q, group_order, check_special=False):
    counts = Counter(); counts_sl = Counter(); digest = hashlib.sha256(); total = 0
    for A in matrices:
        total += 1; digest.update(bytes(A))
        T = cyclic_involution(A, n, q, group_order)
        key = 'odd_order' if T is None else str(fixed_dimension(T, n, q))
        counts[key] += 1
        if check_special and determinant_leibniz(A, n, q) == 1:
            counts_sl[key] += 1
    assert total == group_order
    hits = sum(v for k, v in counts.items() if k != 'odd_order' and n <= 3*int(k) < 2*n)
    closed_hits = sum(v for k, v in counts.items() if k != 'odd_order' and n <= 3*int(k) <= 2*n)
    out = {'n':n, 'q':q, 'group_order':total, 'Q_count':hits, 'proportion':str(F(hits,total)),
           'fixed_space_histogram':dict(sorted(counts.items())), 'closed_upper_endpoint_count':closed_hits,
           'matrix_stream_sha256':digest.hexdigest()}
    if check_special:
        out['SL_order'] = sum(counts_sl.values())
        out['SL_Q_count'] = sum(v for k,v in counts_sl.items() if k != 'odd_order' and n <= 3*int(k) < 2*n)
    return out

def gl_matrices(n, q):
    # Enumerate ordered independent columns, not all candidate matrices plus elimination.
    nonzero = [v for v in product(range(q), repeat=n) if any(v)]
    def extend(cols, span):
        if len(cols) == n:
            yield tuple(cols[j][i] for i in range(n) for j in range(n))
            return
        for v in nonzero:
            if v in span:
                continue
            newspan = {tuple((u[i]+c*v[i]) % q for i in range(n)) for u in span for c in range(q)}
            yield from extend(cols+[v], newspan)
    yield from extend([], {tuple(0 for _ in range(n))})

def sp4_matrices():
    # Form J has entries J_13=J_24=1, J_31=J_42=-1. Each map x -> x+v<v,x>
    # preserves the alternating form. Complete closure plus the known order proves equality.
    generators = [(1,0,0,0),(0,1,0,0),(0,0,1,0),(0,0,0,1),
                  (1,1,0,0),(1,0,0,1),(0,1,1,0),(0,0,1,1)]
    def act(A,v):
        cov = (-v[2],-v[3],v[0],v[1])
        row = [sum(cov[k]*A[k*4+j] for k in range(4)) % 3 for j in range(4)]
        return tuple((A[i*4+j]+v[i]*row[j]) % 3 for i in range(4) for j in range(4))
    seen = {eye(4)}; todo = deque(seen)
    while todo:
        A = todo.popleft()
        yield A
        for v in generators:
            B = act(A,v)
            if B not in seen:
                seen.add(B); todo.append(B)
    assert len(seen) == 51840

@lru_cache(None)
def partitions(n, minimum=1):
    if n == 0:
        return ((),)
    return tuple((d,)+p for d in range(minimum,n+1) for p in partitions(n-d,d))

def partition_weight(parts):
    return F(1, prod(d**m * factorial(m) for d,m in Counter(parts).items()))

@lru_cache(None)
def cyclic_colors(t):
    # Enumerate exponents in C_(2^t), independently of the closed-form w_j formula.
    counts = Counter(0 if x == 0 else t-vp2(x) for x in range(2**t))
    return tuple((j,F(c,2**t)) for j,c in sorted(counts.items()))

@lru_cache(None)
def cycle_options(q,d,kind,collapse=False):
    signs = (0,1) if kind == 'signed' else (0,)
    options = []
    for sign in signs:
        order = (q**d-1 if sign == 0 else q**d+1) if kind == 'signed' else q**d-((-1)**d if kind == 'U' else 1)
        for j,w in cyclic_colors(vp2(order)):
            options.append((min(j,1) if collapse else j, sign, w/len(signs)))
    return tuple(options)

@lru_cache(None)
def partition_distribution(parts,q,kind,collapse=False):
    out = {(0,0,0):F(1)}
    for d in parts:
        nxt = {}
        for (top,mass,par),prob in out.items():
            for j,sign,w in cycle_options(q,d,kind,collapse):
                top2 = max(top,j)
                mass2 = mass+d if j == top else (d if j > top else mass)
                key = (top2,mass2,par^sign)
                nxt[key] = nxt.get(key,F(0)) + prob*w
        out = nxt
    return tuple(out.items())

def partition_model(n,q,kind,collapse=False,closed=False):
    base = kind if kind in ('GL','U') else 'signed'
    natural_n = n if base != 'signed' else (2*n+1 if kind == 'SOodd' else 2*n)
    allowed_parity = {'SOplus':0,'SOminus':1}.get(kind)
    probability = F(0); layers = Counter(); total_weight = F(0)
    for parts in partitions(n):
        pw = partition_weight(parts)
        for (top,mass,par),cw in partition_distribution(parts,q,base,collapse):
            if allowed_parity is not None and par != allowed_parity:
                continue
            weight = pw*cw*(2 if allowed_parity is not None else 1)
            total_weight += weight
            fixed = natural_n - mass*(1 if base != 'signed' else 2)
            good = natural_n <= 3*fixed and (3*fixed <= 2*natural_n if closed else 3*fixed < 2*natural_n)
            if top > 0 and good:
                probability += weight; layers[top] += weight
    assert total_weight == 1
    return probability, dict(layers)

def coefficient_controls(frozen):
    source = json.loads((frozen/'verification_results.json').read_text())
    rows = []
    for expected in source['controls']['model_results']:
        n,q,kind = expected['model_size'],expected['q'],expected['kind']
        actual,layers = partition_model(n,q,kind)
        assert actual == F(expected['p'])
        rows.append({'n':n,'q':q,'family':kind,'p':str(actual)})
    orthogonal = []
    for q in (3,5,9,17):
        for n in range(2,9):
            ps,_ = partition_model(n,q,'Sp')
            pp,_ = partition_model(n,q,'SOplus')
            pm,_ = partition_model(n,q,'SOminus')
            po,_ = partition_model(n,q,'SOodd')
            assert (pp+pm)/2 == ps and pp <= 2*ps and pm <= 2*ps
            orthogonal.append({'q':q,'rank':n,'Sp':str(ps),'SOplus':str(pp),'SOminus':str(pm),'SOodd':str(po)})
    avoidance = 0
    for L in (1,2,3,4,8):
        for rho in (F(1,2),F(1,4),F(2,3)):
            for n in range(17):
                left = sum((partition_weight(p)*prod((1-rho if d%L == 0 else F(1)) for d in p) for p in partitions(n)),F(0))
                right = prod((1-rho/(L*i) for i in range(1,n//L+1)),start=F(1))
                assert left == right; avoidance += 1
    # Direct cyclic-exponent enumeration confirms the exact color formula over finite t.
    color_cases=0
    for t in range(1,15):
        dd=dict(cyclic_colors(t))
        assert dd[0] == F(1,2**t)
        for j in range(1,t+1):
            assert dd[j] == F(2**(j-1),2**t); color_cases+=1
    return {'partition_matches':len(rows),'model_results':rows,'orthogonal_cases':orthogonal,
            'avoidance_exact_cases':avoidance,'cyclic_color_cases':color_cases}

def analytic_controls():
    # Bounded stress controls of assumptions and constants. The report gives infinite proofs.
    valuation=0; strata=0
    for q in range(3,260,2):
        a,b=vp2(q-1),vp2(q+1); c=max(a,b)
        for d in range(1,130):
            tm=vp2(q**d-1); tp=vp2(q**d+1)
            assert tm == (a if d%2 else a+b+vp2(d)-1)
            assert tp == (b if d%2 else 1)
            valuation+=1
    for a,b in [(1,c) for c in range(2,34)]+[(c,1) for c in range(2,34)]:
        for d in range(1,130):
            t=a if d%2 else a+b+vp2(d)-1
            for j in range(1,t+2):
                w=F(2**(j-1),2**t) if j<=t else F(0); accept=min(F(1),F(2**j,2**t))
                if j<a:
                    assert w<=F(2**(j-1),2**a) and accept<=F(1,2)
                elif j==a and d%2==0:
                    assert accept<=F(1,2)
                elif a<j<a+b:
                    assert (w==0 if d%2 else w<=F(2**j,2**(a+b+1)))
                    if d%2==0:assert accept<=F(1,2)
                elif j>=a+b:
                    h=2**(j-a-b+1)
                    assert not w or d%h==0
                    assert w<=F(1,2)
                    if d%(2*h)==0:assert accept<=F(1,2)
                strata+=1
    signed_strata=0
    for a,b in [(1,c) for c in range(2,34)]+[(c,1) for c in range(2,34)]:
        c=max(a,b)
        for d in range(1,130):
            ts=(a if d%2 else a+b+vp2(d)-1, b if d%2 else 1)
            for j in range(1,max(ts)+2):
                w=sum((F(2**(j-1),2**t) if j<=t else F(0) for t in ts),F(0))/2
                accept=sum((min(F(1),F(2**j,2**t)) for t in ts),F(0))/2
                if j==1:assert accept<=F(3,4)
                elif j<c:
                    assert accept<=F(3,4) and w<=F(2**j,2**(c+2))
                elif j==c and d%2==0:assert accept<=F(3,4)
                elif j>=c+1:
                    h=2**(j-c)
                    assert not w or d%h==0
                    assert w<=F(1,4)
                    if d%(2*h)==0:assert accept<=F(3,4)
                signed_strata+=1
    pointing=0
    @lru_cache(None)
    def cutoff(n,q,kind,j):
        return sum((partition_weight(p)*sum((w for (top,mass,par),w in partition_distribution(p,q,kind) if top<=j),F(0)) for p in partitions(n)),F(0))
    for q in (3,5,17):
        for kind in ('GL','U','signed'):
            for n in range(1,11):
                topmax=max(j for d in range(1,n+1) for j,sign,w in cycle_options(q,d,kind))
                for j in range(1,topmax+1):
                    left=sum((partition_weight(p)*sum((mass*w for (top,mass,par),w in partition_distribution(p,q,kind) if top==j),F(0)) for p in partitions(n)),F(0))
                    right=sum((sum((w for color,sign,w in cycle_options(q,d,kind) if color==j),F(0))*cutoff(n-d,q,kind,j) for d in range(1,n+1)),F(0))
                    assert left==right;pointing+=1
    dyadic=0
    for c in (4,8):
        for exponent in range(1,1001):
            ln_n=exponent*log(2)
            # No enormous integer or cancellation is needed in this bounded numeric stress test.
            lhs=sum(exp(-k*log(2)-(ln_n-k*log(2))/(c*2**k)) for k in range(1,exponent+1))
            rhs=8*c/ln_n+2*exp(-ln_n/2)
            assert lhs<=rhs*(1+1e-12);dyadic+=1
    return {'valuation_cases':valuation,'unsigned_layer_assumption_cases':strata,'signed_layer_assumption_cases':signed_strata,'cycle_pointing_exact_cases':pointing,
            'dyadic_numeric_stress_cases':dyadic,'numeric_tests_are_proof':False,
            'linear_constant_sum':28+384+48,'signed_constant_sum':32+384+24}

def negative_controls():
    strict,_=partition_model(3,3,'GL');closed,_=partition_model(3,3,'GL',closed=True)
    full,_=partition_model(2,5,'GL');collapse,_=partition_model(2,5,'GL',collapse=True)
    pp,_=partition_model(2,3,'SOplus');pm,_=partition_model(2,3,'SOminus');ps,_=partition_model(2,3,'Sp')
    unit,_=partition_model(3,3,'U');linear,_=partition_model(3,3,'GL')
    assert strict != closed and full != collapse and pp != pm and unit != linear
    t=(1,0,0,0,2,0,0,0,2); neg=tuple(-x%3 for x in t)
    assert fixed_dimension(t,3,3)==1 and fixed_dimension(neg,3,3)==2
    assert (1-2**(-1000))>32/(1000*log(2))+2*exp(-500*log(2))
    return {'missing_avoidance_exponential':{'n':'2^1000','unweighted_dyadic_sum_exceeds_claimed_decay':True},'arbitrary_projective_lift':{'fixed_dimensions':[1,2],'same_central_coset':True,'detected':True},'strict_endpoint':{'correct':str(strict),'closed_wrong':str(closed),'detected':True},
            'max_2adic_vs_even_odd_only':{'correct':str(full),'collapsed_wrong':str(collapse),'detected':True},
            'orthogonal_parity':{'SOplus':str(pp),'SOminus':str(pm),'unconditional':str(ps),'detected':True},
            'unitary_arithmetic_swap':{'U3_3':str(unit),'GL3_3':str(linear),'detected':True},
            'rank_one_lower_bound_excluded':{'GL2_3':'1/4','SL2_3':'0','detected':True}}

def main():
    ap=argparse.ArgumentParser();ap.add_argument('--frozen',type=Path,required=True);ap.add_argument('--output',type=Path,required=True);args=ap.parse_args()
    start=time.time();mat=[]
    for n,q in [(2,3),(2,5),(2,7),(3,3)]:
        order=prod(q**n-q**i for i in range(n))
        row=summarize(gl_matrices(n,q),n,q,order,True);row['family']='GL';mat.append(row)
        assert F(row['Q_count'],order)==partition_model(n,q,'GL')[0]
        print('GL',n,q,row['Q_count'],order,flush=True)
    row=summarize(sp4_matrices(),4,3,51840);row['family']='Sp';mat.append(row)
    assert row['Q_count']==17010 and F(row['Q_count'],51840)==partition_model(2,3,'Sp')[0]
    assert mat[-2]['Q_count']==5265
    print('Sp4',row['Q_count'],51840,flush=True)
    coeff=coefficient_controls(args.frozen);print('partition controls passed',flush=True)
    analytic=analytic_controls();print('analytic stress controls passed',flush=True)
    out={'scope':'Independent bounded controls; no finite test proves the infinite theorem.',
         'matrices':mat,'coefficients':coeff,'analytic_controls':analytic,'negative_controls':negative_controls(),
         'elapsed_seconds':round(time.time()-start,3),'all_passed':True}
    args.output.write_text(json.dumps(out,indent=2)+'\n')
    print(json.dumps({'all_passed':True,'elapsed_seconds':out['elapsed_seconds']}),flush=True)
if __name__=='__main__':main()
