#!/usr/bin/env python3
"""Read-only artifact audit; run from any directory, standard library only."""
import collections
import datetime
import hashlib
import itertools
import json
from pathlib import Path
import re
import sys

ROOT = Path(__file__).resolve().parents[1]
sys.dont_write_bytecode = True
sys.path.insert(0, str(ROOT / 'src'))
from check import inspect
from check_sorted import reconstruct
from local_cnf import build
from search_board import model
from dpll_prove import solve, read_cnf


def normalized(value):
    return json.loads(json.dumps(value))


print('UTC:', datetime.datetime.now(datetime.timezone.utc).isoformat())
print('Python:', sys.version)
listed = set()
for line in (ROOT / 'MANIFEST.sha256').read_text().splitlines():
    digest, filename = line.split('  ', 1)
    assert filename not in listed
    listed.add(filename)
    assert hashlib.sha256((ROOT / filename).read_bytes()).hexdigest() == digest, filename
originals = {str(p.relative_to(ROOT)) for p in ROOT.rglob('*') if p.is_file()
             and p.relative_to(ROOT).parts[0] not in ('review', 'tmp')
             and '__pycache__' not in p.parts and p.name != 'MANIFEST.sha256'
             and p.name != 'RESEARCH_LOG.md'}
assert listed == originals, (listed - originals, originals - listed)
print('Manifest: all', len(listed), 'original files present, covered, and unchanged.')

c = build()
assert c.names == json.loads((ROOT / 'certificates/local_variables.json').read_text())
assert c.reasons == json.loads((ROOT / 'certificates/local_clause_reasons.json').read_text())
counts = collections.Counter()
for reason in c.reasons:
    if reason.startswith(('disjoint ', 'K implies ', 'R implies ', 'occupied implies ')):
        key = 'type/occupancy'
    elif reason.startswith(('occupied ', 'ray presence ')):
        key = 'ray equivalence'
    elif reason.startswith('rook has '):
        key = 'ray upper bound'
    elif reason.startswith('rooks '):
        key = 'intervening knight'
    elif reason.startswith('knight at '):
        key = 'knight lower bound'
    elif reason == 'rightmost knight at origin':
        key = 'origin'
    else:
        raise AssertionError(reason)
    counts[key] += 1
assert sorted(counts.values()) == [1, 54, 64, 112, 126, 342]
assert len(c.names) == 174 and len(c.clauses) == 699
assert c.names['K(-1,1)'] == 19
print('Variable/reason maps regenerated exactly; clause counts:', dict(counts))
cnf_path = ROOT/'certificates/local_relaxation.cnf'
certificate = {'cnf_sha256': hashlib.sha256(cnf_path.read_bytes()).hexdigest(),
               'indexing': 'zero-based original clauses',
               'tree': solve(read_cnf(cnf_path), {}, [19])}
assert (json.dumps(certificate, indent=2)+'\n').encode() == (ROOT/'certificates/local_unsat_tree.json').read_bytes()
print('UNSAT certificate regenerated byte-for-byte, including formatting.')

# A third reconstruction uses cell-by-cell ray walking, stopping at first piece.
def walk_attacks(data):
    pieces = {tuple(p): typ for key, typ in [('knights', 'K'), ('rooks', 'R')]
              for p in data[key]}
    xmin = min(x for x, y in pieces)
    xmax = max(x for x, y in pieces)
    ymin = min(y for x, y in pieces)
    ymax = max(y for x, y in pieces)
    result = []
    for typ in 'KR':
        for (x, y), label in sorted(pieces.items()):
            if label != typ:
                continue
            if typ == 'K':
                targets = [(x+dx, y+dy) for dx,dy in itertools.product(range(-2,3), repeat=2)
                           if abs(dx*dy)==2 and (x+dx,y+dy) in pieces]
            else:
                targets = []
                for dx,dy in [(0,1),(0,-1),(1,0),(-1,0)]:
                    a,b = x+dx,y+dy
                    while xmin <= a <= xmax and ymin <= b <= ymax:
                        if (a,b) in pieces:
                            targets.append((a,b))
                            break
                        a,b = a+dx,b+dy
            result.append((typ, (x,y), sorted(q for q in targets if pieces[q]=='K'),
                           sorted(q for q in targets if pieces[q]=='R')))
    return result

for path in sorted((ROOT / 'data').glob('*.json')):
    data = json.loads(path.read_text())
    if 'search' in data:
        args = data['search']['arguments']
        n,m = args['knight_degree'],args['rook_degree']
        raw = (ROOT / 'logs' / (data['search']['name'] + '_raw_model.txt')).read_text()
        raw_true = re.findall(r'\(([KR])_(\d+)_(\d+)\s+true\)', raw)
        for typ,key in [('K','knights'),('R','rooks')]:
            assert {tuple(p) for p in data[key]} == {(int(x),int(y)) for label,x,y in raw_true if label==typ}
    else:
        n,m = ((1,1) if path.stem=='source_N1R1' else (4,1))
    a,b = inspect(data,n,m),reconstruct(data,n,m)
    assert a['valid'] and b['valid']
    assert a['attacks'] == b['attacks']
    expected = [(r['piece'],r['at'],r['attacks_knights'],r['attacks_rooks']) for r in a['attacks']]
    assert walk_attacks(data) == expected
    out_k = sum(len(r['attacks_rooks']) for r in a['attacks'] if r['piece']=='K')
    out_r = sum(len(r['attacks_knights']) for r in a['attacks'] if r['piece']=='R')
    print(path.name, 'valid', (n,m), 'pieces', (a['knight_count'],a['rook_count']),
          'directed attacks', (out_k,out_r))
    if path.stem.startswith('source_'):
        for report in [ROOT/'certificates'/(path.stem+'_attacks.json'), ROOT/'logs'/(path.stem+'_check.log')]:
            assert json.loads(report.read_text()) == normalized(a)
    elif n==4 and m==1:
        assert json.loads((ROOT/'logs/calibration_N4R1_direct.json').read_text()) == normalized(a)
    elif n==2 and m==3:
        assert json.loads((ROOT/'logs/calibration_N2R3_direct.json').read_text()) == normalized(a)

for path in sorted((ROOT/'logs').glob('*_s1.json')):
    metadata = json.loads(path.read_text())
    args = metadata['arguments']
    formula,_ = model(args['width'],args['height'],args['knight_degree'],args['rook_degree'],
                     args['symmetry'],args['parity'],args['min_knights'],args['max_knights'])
    prefix = (f"(set-option :timeout {int(args['timeout']*1000)})\n"
              f"(set-option :sat.random_seed {args['seed']})\n"
              f"(set-option :smt.random_seed {args['seed']})\n")
    assert (ROOT/'data'/(metadata['name']+'.smt2')).read_text() == prefix+formula+'\n(check-sat)\n'
    print('Exploratory formula exact:', metadata['name'], 'recorded status:', metadata['status'])
print('All artifact consistency checks passed. Exploratory solver outcomes were not rerun.')
