#!/usr/bin/env python3
"""Quotient the exported E=3/E=4 closure by isomorphism and complement.

The input graphs are generated by ``search43_e2_barrier_escape.cpp`` after
exact objective replays.  This audit binds those streams, canonicalizes every
graph and its complement with nauty ``labelg`` in both dense and sparse
modes, compares the induced partitions, and writes one canonical graph6
representative per complement-isomorphism class.

The retained representatives are independently recounted with a recursive
bitset K5 enumerator before they are accepted as later search seeds.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import subprocess
import sys
import tempfile
from collections import Counter, defaultdict
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from graph_io import complement, decode_graph6, encode_graph6  # noqa: E402


SCHEMA = "ramsey55.e2_low_closure_isomorphism_audit.v1"
ORDER = 43
FULL_MASK = (1 << ORDER) - 1


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as source:
        while block := source.read(1 << 20):
            digest.update(block)
    return digest.hexdigest()


def graph6_lines(path: Path) -> list[str]:
    result = [
        line.strip()
        for line in path.read_text(encoding="ascii").splitlines()
        if line.strip() and not line.startswith("#")
    ]
    if not result:
        raise ValueError(f"{path}: no graph6 records")
    for index, graph in enumerate(result):
        adjacency = decode_graph6(graph)
        if len(adjacency) != ORDER or encode_graph6(adjacency) != graph:
            raise ValueError(f"{path}: malformed/non-normal graph6 at {index}")
    if len(set(result)) != len(result):
        raise ValueError(f"{path}: repeated labeled graph")
    return result


def canonicalize(
    graphs: list[str],
    *,
    labelg: Path,
    sparse: bool,
    directory: Path,
    tag: str,
) -> list[str]:
    source = directory / f"{tag}.input.g6"
    target = directory / f"{tag}.output.g6"
    source.write_text(
        "".join(graph + "\n" for graph in graphs), encoding="ascii"
    )
    command = [str(labelg), "-q", "-g"]
    if sparse:
        command.append("-S")
    command.extend((str(source), str(target)))
    completed = subprocess.run(
        command,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        check=False,
    )
    if completed.returncode != 0:
        raise RuntimeError(
            f"labelg failed for {tag}: {completed.stderr.strip()}"
        )
    result = [
        line.strip()
        for line in target.read_text(encoding="ascii").splitlines()
        if line.strip() and not line.startswith("#")
    ]
    if len(result) != len(graphs):
        raise RuntimeError(
            f"labelg record count changed for {tag}: "
            f"{len(graphs)} -> {len(result)}"
        )
    return result


def partition(labels: list[str]) -> tuple[tuple[int, ...], ...]:
    groups: dict[str, list[int]] = defaultdict(list)
    for index, label in enumerate(labels):
        groups[label].append(index)
    return tuple(sorted(tuple(group) for group in groups.values()))


def normalized_labels(
    graphs: list[str], duals: list[str]
) -> list[str]:
    return [
        min(graph, dual)
        for graph, dual in zip(graphs, duals, strict=True)
    ]


def size_histogram(labels: list[str]) -> dict[str, int]:
    class_sizes = Counter(Counter(labels).values())
    return {
        str(size): class_sizes[size]
        for size in sorted(class_sizes)
    }


def clique_count(adjacency: list[int]) -> int:
    """Count all K5s once using an implementation independent of the C++ run."""

    if len(adjacency) != ORDER:
        raise ValueError("unexpected graph order")

    def recurse(candidates: int, depth: int) -> int:
        needed = 5 - depth
        if candidates.bit_count() < needed:
            return 0
        if depth == 5:
            return 1
        total = 0
        while candidates:
            low = candidates & -candidates
            vertex = low.bit_length() - 1
            candidates ^= low
            total += recurse(candidates & adjacency[vertex], depth + 1)
        return total

    return recurse(FULL_MASK, 0)


def audit_objective(
    *,
    objective: int,
    input_path: Path,
    expected_count: int,
    labelg: Path,
    temporary: Path,
    representative_path: Path,
) -> dict[str, object]:
    graphs = graph6_lines(input_path)
    if len(graphs) != expected_count:
        raise ValueError(
            f"E={objective} stream has {len(graphs)} records, "
            f"expected {expected_count}"
        )
    duals = [
        encode_graph6(complement(decode_graph6(graph))) for graph in graphs
    ]
    if any(
        encode_graph6(complement(decode_graph6(dual))) != graph
        for graph, dual in zip(graphs, duals, strict=True)
    ):
        raise AssertionError("complement involution failed")

    dense = canonicalize(
        graphs,
        labelg=labelg,
        sparse=False,
        directory=temporary,
        tag=f"e{objective}.dense",
    )
    dense_duals = canonicalize(
        duals,
        labelg=labelg,
        sparse=False,
        directory=temporary,
        tag=f"e{objective}.dense_dual",
    )
    sparse = canonicalize(
        graphs,
        labelg=labelg,
        sparse=True,
        directory=temporary,
        tag=f"e{objective}.sparse",
    )
    sparse_duals = canonicalize(
        duals,
        labelg=labelg,
        sparse=True,
        directory=temporary,
        tag=f"e{objective}.sparse_dual",
    )

    dense_partition = partition(dense)
    sparse_partition = partition(sparse)
    dense_normalized = normalized_labels(dense, dense_duals)
    sparse_normalized = normalized_labels(sparse, sparse_duals)
    dense_dual_partition = partition(dense_normalized)
    sparse_dual_partition = partition(sparse_normalized)
    if dense_partition != sparse_partition:
        raise AssertionError(
            f"E={objective}: dense/sparse isomorphism partitions disagree"
        )
    if dense_dual_partition != sparse_dual_partition:
        raise AssertionError(
            f"E={objective}: dense/sparse complement partitions disagree"
        )

    representatives = sorted(set(dense_normalized))
    conflict_splits: Counter[str] = Counter()
    for graph in representatives:
        adjacency = decode_graph6(graph)
        clique_conflicts = clique_count(adjacency)
        independent_conflicts = clique_count(complement(adjacency))
        if clique_conflicts + independent_conflicts != objective:
            raise AssertionError(
                f"E={objective}: representative recount found "
                f"{clique_conflicts}+{independent_conflicts}"
            )
        conflict_splits[
            f"{clique_conflicts},{independent_conflicts}"
        ] += 1

    representative_path.parent.mkdir(parents=True, exist_ok=True)
    representative_path.write_text(
        "".join(graph + "\n" for graph in representatives),
        encoding="ascii",
    )
    return {
        "objective": objective,
        "input_path": str(input_path.resolve()),
        "input_sha256": sha256_file(input_path),
        "labeled_graph_count": len(graphs),
        "labeled_stream_unique": True,
        "complement_involution_exact": True,
        "dense_sparse_isomorphism_partition_match": True,
        "dense_sparse_complement_partition_match": True,
        "ordinary_isomorphism_class_count": len(dense_partition),
        "ordinary_class_size_histogram": size_histogram(dense),
        "complement_isomorphism_class_count": len(representatives),
        "complement_class_size_histogram": size_histogram(
            dense_normalized
        ),
        "representative_conflict_split_counts": dict(
            sorted(conflict_splits.items())
        ),
        "all_representatives_independently_recounted": True,
        "representative_path": str(representative_path.resolve()),
        "representative_sha256": sha256_file(representative_path),
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--e3", type=Path, required=True)
    parser.add_argument("--e4", type=Path, required=True)
    parser.add_argument("--expected-e3", type=int, default=16_082)
    parser.add_argument("--expected-e4", type=int, default=73_788)
    parser.add_argument("--labelg", type=Path, required=True)
    parser.add_argument("--representatives-prefix", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    if not args.labelg.is_file():
        raise ValueError("labelg executable is missing")

    with tempfile.TemporaryDirectory(
        prefix="ramsey55-e2-low-closure."
    ) as directory:
        temporary = Path(directory)
        records = [
            audit_objective(
                objective=3,
                input_path=args.e3,
                expected_count=args.expected_e3,
                labelg=args.labelg,
                temporary=temporary,
                representative_path=Path(
                    f"{args.representatives_prefix}.e3.g6"
                ),
            ),
            audit_objective(
                objective=4,
                input_path=args.e4,
                expected_count=args.expected_e4,
                labelg=args.labelg,
                temporary=temporary,
                representative_path=Path(
                    f"{args.representatives_prefix}.e4.g6"
                ),
            ),
        ]

    result = {
        "schema": SCHEMA,
        "status": (
            "REPRODUCIBLE_FINITE_CORPUS_CLASSIFICATION_"
            "AND_INDEPENDENT_REPRESENTATIVE_RECOUNT"
        ),
        "evidence_label": "REPRODUCIBLE COMPUTATIONAL OBSERVATION",
        "valid": True,
        "source_sha256": sha256_file(Path(__file__)),
        "labelg_path": str(args.labelg.resolve()),
        "labelg_sha256": sha256_file(args.labelg),
        "records": records,
        "total_labeled_graph_count": sum(
            int(record["labeled_graph_count"]) for record in records
        ),
        "total_complement_isomorphism_class_count": sum(
            int(record["complement_isomorphism_class_count"])
            for record in records
        ),
        "claim_boundary": (
            "This classifies only the exported finite E=3/E=4 low-conflict "
            "closure. It neither classifies all low-conflict order-43 "
            "graphs nor proves existence or nonexistence of a Ramsey graph."
        ),
    }
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(
        json.dumps(result, sort_keys=True, indent=2) + "\n",
        encoding="utf-8",
    )
    print(json.dumps(result, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
