"""UNEXECUTED PR48 ROOT post-inspection SOURCE. ROOT reads and copies unchanged adjacent to A48.
Runtime is read-only for native/Git/remote/science; only ROOT-owned command evidence and exact post records are written.
All acceptance outputs and mixed-six receipts must exist. Old foreign equality is dated; current equality is bounded by the genuine post epoch.
"""
from pathlib import Path,PurePosixPath
import argparse,copy,datetime as dt,hashlib,json,math,os,re,stat,subprocess,sys,traceback,types
sys.dont_write_bytecode=True
A=Path(__file__).absolute().parent;R=A.parents[2];P=A/'post_push_foreign_epoch_preparation_v5';H=A/'acceptance_preparation_family_v3';C=A/'reviewed_candidate';K=R/'unsolved_math_prioritization/attempts/2961';B=A.parents[1];P47=A.parent/'pr47_2849'
HEAD='e2e5c8c3e5ad218f867fa753c465bb96b3687bda';BASE='60292bed09f59236aa192cb17aa138f7b4750e1a';PREP='9c525f7b540068af07477e8f794e21596d93e69e49e8dbc52972d3196eb9fda4';CONTRACT='26f89f5ebf8444f96394ca5050c503920de1b9adb7417489241fcbe04885b410';PHASE_OPERATOR='331cb4cb479113a8dbedc758e328b30a11bc93bcd052535953a4da9fd705095c'
COMMANDS=[];D=None;SOURCE=None;OUTER=None;EC=None;EPOCH=None;READY=None;SOURCE_MF=None;POST_SOURCE_MODES=None
def need(v,m):
    if not v:raise ValueError(m)
def sha(b):return hashlib.sha256(b).hexdigest()
def raw(p):need(p.is_file() and not p.is_symlink() and all(not q.is_symlink() for q in p.parents),'Regular nonsymlink input');return p.read_bytes()
def parse(b):
    def pairs(items):
        d={}
        for k,v in items:need(k not in d,'Duplicate JSON key');d[k]=v
        return d
    def fl(s):v=float(s);need(math.isfinite(v),'Nonfinite JSON');return v
    return json.loads(b,object_pairs_hook=pairs,parse_float=fl,parse_constant=lambda s:(_ for _ in ()).throw(ValueError(s)))
def load(p):return parse(raw(p))
def eq(a,b):return type(a) is type(b) and (a.keys()==b.keys() and all(eq(a[k],b[k]) for k in a) if type(a) is dict else len(a)==len(b) and all(eq(x,y) for x,y in zip(a,b)) if type(a) is list else a==b)
def safe(n):
    need(type(n) is str and n and n!='.' and '\\' not in n and '\0' not in n,'Literal member path');p=PurePosixPath(n);need(not p.is_absolute() and p.as_posix()==n and not {'.','..','.git','__pycache__'}.intersection(p.parts),'Canonical member');return n
def pin(p):return EC.ref(p) if EC is not None else dict(path=safe(p.relative_to(R).as_posix()),bytes=len(raw(p)),sha256=sha(raw(p)))
def check(base,z):
    need(type(z) is dict and set(z)=={'path','bytes','sha256'} and type(z['bytes']) is int and z['bytes']>=0 and type(z['sha256']) is str and re.fullmatch('[0-9a-f]{64}',z['sha256']),'Exact typed triple');b=raw(base/safe(z['path']));need(len(b)==z['bytes'] and sha(b)==z['sha256'],'Entire referenced body');return b
def clock(s):need(type(s) is str and s and s==s.strip(),'UTC string');v=dt.datetime.fromisoformat(s[:-1]+'+00:00' if s.endswith('Z') else s);need(v.tzinfo is not None and v.utcoffset()==dt.timedelta(0),'Aware UTC');return v
def stamp():return dt.datetime.now(dt.timezone.utc).isoformat()
def put(p,b):
    need(not p.is_symlink() and all(not q.is_symlink() for q in p.parents),'Regular output ancestors')
    with p.open('xb') as f:f.write(b);f.flush();os.fsync(f.fileno())
    need(stat.S_IMODE(p.stat().st_mode)==0o644,'ROOT operational evidence full0644')
def encode(v):return (json.dumps(v,indent=2,ensure_ascii=False,allow_nan=False)+'\n').encode()
def post_source_modes():
    return dict(runtime=EC.current_runtime_source_modes(),actual_inspector=EC.source_binding(Path(__file__),0o644),declared_ROOT_prelaunch=EC.source_binding(A/'ROOT_POST_EPOCH_V5_INSPECTION_PRELAUNCH_SOURCE.py',0o644),retained_source=EC.source_binding(D/'PRELAUNCH_SOURCE.py',0o644),retained_operator=EC.source_binding(D/'PRELAUNCH_OPERATOR.py',0o644),outer_operator=EC.source_binding(OUTER,0o644),actual_live_ROOT_operator=EC.live_operator_binding(OUTER.parent),directories=EC.directory_bindings([D])+EC.directory_bindings([OUTER.parent],0o700))
def command(argv,stdin=None):
    need(type(argv) is list and all(type(z) is str for z in argv),'Literal argv');need((argv[0]=='git' and argv[1] in {'branch','rev-parse','show','ls-tree','ls-files','diff','diff-tree','merge-base','cat-file'}) or argv==['gh','pr','view','48','--repo','AlecKriebel/Math','--json','number,url,state,isDraft,headRefOid,headRefName,baseRefName,mergeCommit,mergedAt,body'],'Readonly whitelist');need(stdin is None or (type(stdin) is bytes and argv==['git','cat-file','--batch-check']),'Only bounded literal object metadata batch stdin')
    cap=dict(schema='pr48-root-post-epoch-actual-memory-readonly/v5',operator_pid=os.getpid(),operator_sha256=sha(SOURCE),argv=argv,cwd=str(R),source=None,source_unchanged=None,stdin_supplied=stdin is not None,started_utc=stamp(),actual_execution=False,completed=False,pid=None,exit_code=None);out=err=b'';proc=None
    if stdin is not None:cap['stdin']=dict(bytes=len(stdin),sha256=sha(stdin),retained_on_disk=False,complete_body_consumed_in_memory=True)
    try:
        modes=post_source_modes();need(eq(modes,POST_SOURCE_MODES),'Actual source fullmodes immediately before readonly child');cap['mode_contract']=EC.MODE_CONTRACT;cap['source_mode_bindings_before_sha256']=sha(encode(modes))
        env=dict(os.environ,GIT_OPTIONAL_LOCKS='0',GIT_LITERAL_PATHSPECS='1')
        for k in ['GIT_DIR','GIT_WORK_TREE','GIT_INDEX_FILE','GIT_OBJECT_DIRECTORY','GIT_ALTERNATE_OBJECT_DIRECTORIES']:env.pop(k,None)
        proc=subprocess.Popen(argv,cwd=R,stdin=subprocess.DEVNULL if stdin is None else subprocess.PIPE,stdout=subprocess.PIPE,stderr=subprocess.PIPE,env=env);cap.update(actual_execution=True,pid=proc.pid);out,err=proc.communicate(stdin);cap.update(completed=True,exit_code=proc.returncode);after_modes=post_source_modes();cap['source_mode_bindings_after_sha256']=sha(encode(after_modes));cap['source_fullmodes_unchanged']=eq(modes,after_modes);need(cap['source_fullmodes_unchanged'] is True,'Actual source fullmodes immediately after readonly child')
    except BaseException:
        cap['operator_error']=traceback.format_exc()
        if proc is not None:
            try:out,err=proc.communicate();cap.update(completed=True,exit_code=proc.returncode)
            except BaseException:cap['operator_reap_error']=traceback.format_exc()
    cap.update(finished_utc=stamp(),operator_unchanged=EC.source_read(Path(__file__),0o644)[0]==raw(D/'PRELAUNCH_SOURCE.py')==SOURCE,outer_operator_unchanged=raw(OUTER)==raw(D/'PRELAUNCH_OPERATOR.py'))
    for k,b in [('stdout',out),('stderr',err)]:cap[k]=dict(bytes=len(b),sha256=sha(b),retained_on_disk=False,complete_body_consumed_in_memory=True)
    cap['status']='PASS' if cap['actual_execution'] is True and cap['completed'] is True and type(cap['pid']) is int and cap['pid']>0 and type(cap['exit_code']) is int and cap['exit_code']==0 and cap['operator_unchanged'] is True and cap['outer_operator_unchanged'] is True and cap.get('source_fullmodes_unchanged') is True and err==b'' and 'operator_error' not in cap else 'FAIL';COMMANDS.append(cap);put(D/('command_%04d.json'%len(COMMANDS)),encode(cap));need(cap['status']=='PASS' and clock(cap['started_utc'])<=clock(cap['finished_utc']),'Actual readonly failure retained, no disk copy of response body');return out
def git(*args):return command(['git',*args])
def cap4(p,expected=0):
    c=load(p);need({q.name for q in p.parent.iterdir()}=={'CAPTURE.json','prelaunch_operator.py','stdout.bin','stderr.bin'},'Exact genuine ROOT CAP4');need(c['schema']=='root-explicit-command-capture/v1' and c['actual_execution'] is True and c['completed'] is True and type(c['pid']) is int and c['pid']>0 and type(c['exit_code']) is int and c['exit_code']==expected and c['stdin_supplied'] is False and c['operator_unchanged'] is True and c['status']==('PASS' if expected==0 else 'FAIL') and c['cwd']==str(R),'Typed actual completed ROOT child with honest failure');need(sha(raw(p.parent/'prelaunch_operator.py'))==c['operator_sha256']=='c1ae969ccbbc48ed6fb486e96184da94329291a46b27d2b891ecb87185c909ec','Full genuine ROOT operator')
    for k in ['stdout','stderr']:need(c[k]['path']==k+'.bin','Literal ROOT streams');check(p.parent,c[k])
    # ROOT command success is an actual exit/status claim. Successful gh-ready
    # and git-push commands legitimately emit progress on stderr; retain it all.
    need(clock(c['started_utc'])<=clock(c['finished_utc'])<=dt.datetime.now(dt.timezone.utc),'Actual ROOT UTC');return dict(capture=pin(p),complete_capture=c,complete_members=[pin(q) for q in sorted(p.parent.iterdir())])
def native(fresh):
    rows=[];need(type(fresh['files']) is list and len(fresh['files'])==13 and len({z['path'] for z in fresh['files']})==13,'Exact13 fresh identities')
    for z in fresh['files']:
        need(set(z)=={'path','bytes','sha256','worktree_mode'} and type(z['worktree_mode']) is int and 0<=z['worktree_mode']<=0o7777,'Typed complete fresh full mode');p=R/safe(z['path']);mode=stat.S_IMODE(p.stat().st_mode);rows.append(dict(pin(p),worktree_mode=mode));need(mode==z['worktree_mode'],'Every native full mode matches actual fresh authority')
    return rows
def phase_captures(pins,overlay,fresh):
    result=[];previous_end=None;expectedrefs={k:pin(R/pins[k.replace('-','_')]) for k in ['final-plan','final-receipt','final-manifest','reconciliation-capture','previous-mirror','previous-post','fresh-preimage','root-bindings']}
    for phase in ['preflight','overlay','prepush']:
        d=A/('root_'+phase+'_actual_capture');need({q.name for q in d.iterdir()}=={'CAPTURE.json','PRELAUNCH.json','PRELAUNCH_SOURCE.py','PRELAUNCH_OPERATOR.py','stdout.bin','stderr.bin'},'Exact real phaseCAP6');c=load(d/'CAPTURE.json');pre=load(d/'PRELAUNCH.json');need(c['schema']=='ROOT_actual_reviewed_acceptance_phase_capture_v1' and c['phase']==phase and c['actual_execution'] is True and c['completed'] is True and c['status']=='PASS' and type(c['exit_code']) is int and c['exit_code']==0 and type(c['pid']) is int and c['pid']>0 and type(c['operator_pid']) is int and c['operator_pid']>0 and c['stdin_supplied'] is False and c['cwd']==str(R) and c['source_unchanged'] is True and c['operator_unchanged'] is True,'Complete typed genuine actual phase');need(all(eq(c[k],v) for k,v in pre.items() if k!='schema'),'Entire original prelaunch')
        name={'mirror':'state_mirror_reconciliation.py','post':'verify_post_acceptance.py'}.get(phase,'integrate_reviewed_partial.py');need(sha(raw(d/'PRELAUNCH_SOURCE.py'))==c['source_sha256']==sha(raw(H/name)) and sha(raw(d/'PRELAUNCH_OPERATOR.py'))==c['operator_sha256']==sha(raw(A/'run_actual_acceptance_phases.py'))==PHASE_OPERATOR,'Entire actual reviewed source/operator')
        argv=['/usr/bin/python3','-B',str(H/name),'--execute','--preparation-manifest-sha256',PREP]
        for k,z in expectedrefs.items():argv.extend(['--'+k,z['path'],'--'+k+'-sha256',z['sha256']])
        if phase not in ['mirror','post']:argv.append(phase)
        if phase=='overlay':argv.extend(['--merge-queue-preimage-sha256',overlay['automatic_merge_queue_preimage_sha256']])
        need(eq(c['argv'],argv) and eq(c['complete_literal_final_references'],expectedrefs) and eq(c['complete_literal_final_references_after'],expectedrefs) and c['complete_final_references_unchanged'] is True and c['before_after_permission_scope_checked'] is True and c['permissions_scope']['operator_child_umask']==0o022 and c['permissions_scope']['native13_full_modes_from_exact_fresh_preimage'] is True and c['permissions_scope']['owned_log_full_modes_from_exact_ROOT_author_preimages'] is True and c['protected_foreign_full_bodies_modes_unchanged'] is True,'Every literal argv/pin and scoped mode authority')
        for field in ['native13_before','native13_after']:
            rr=c[field];need(type(rr) is list and len(rr)==13 and {z['path'] for z in rr}=={z['path'] for z in fresh['files']} and all(set(z)=={'path','bytes','sha256','worktree_mode'} and type(z['bytes']) is int and type(z['worktree_mode']) is int and 0<=z['worktree_mode']<=0o7777 and z['worktree_mode']==next(x['worktree_mode'] for x in fresh['files'] if x['path']==z['path']) and re.fullmatch('[0-9a-f]{64}',z['sha256']) for z in rr),'Full actual phase13 modes, bodies may change as authorized')
        for field in ['owned_mutable_logs_before','owned_mutable_logs_after']:need(type(c[field]) is list and all(set(z)=={'path','bytes','sha256','worktree_mode'} and type(z['worktree_mode']) is int and 0<=z['worktree_mode']<=0o7777 and z['path'] in ['draft_pr_publication_program_20260930/RESEARCH_LOG.md','draft_pr_publication_program_20260930/audits/pr48_2961/ROOT_RESEARCH_LOG.md'] for z in c[field]),'Exact owned logs retain full modes; complete prefix appends checked separately')
        foreign=load(A/'integration_preflight.json')['foreign_logs'];expected_foreign=[{k:z[k] for k in ['path','bytes','sha256','worktree_mode']} for z in foreign];need(eq(c['protected_foreign_before'],expected_foreign) and eq(c['protected_foreign_after'],expected_foreign),'Complete generic protected foreign bodies/fullmodes before and after each actual phase')
        beforelogs={z['path']:z for z in c['owned_mutable_logs_before']};afterlogs={z['path']:z for z in c['owned_mutable_logs_after']};need(set(beforelogs)==set(afterlogs)=={'draft_pr_publication_program_20260930/RESEARCH_LOG.md','draft_pr_publication_program_20260930/audits/pr48_2961/ROOT_RESEARCH_LOG.md'} and all(beforelogs[n]['worktree_mode']==afterlogs[n]['worktree_mode'] for n in beforelogs),'Exactly two owned logs with preserved full modes')
        for k in ['stdout','stderr']:need(c[k]['path']==k+'.bin','Literal phase streams');check(d,c[k])
        need(raw(d/'stderr.bin')==b'' and clock(c['prepared_utc'])<=clock(c['started_utc'])<=clock(c['finished_utc'])<=dt.datetime.now(dt.timezone.utc) and (previous_end is None or previous_end<=clock(c['started_utc'])),'Whole phase streams and chronological actual intervals');previous_end=clock(c['finished_utc']);result.append(dict(capture=pin(d/'CAPTURE.json'),complete_capture=c,complete_members=[pin(q) for q in sorted(d.iterdir())]))
    for phase in ['finalize','mirror','post']:
        c,e=EC.phase_capture(phase,READY,SOURCE_MF);need(previous_end<=clock(e['utc'])<=clock(c['started_utc']),'Mixed-six actual chronology');previous_end=clock(c['finished_utc']);d=A/('root_'+phase+'_actual_capture');result.append(dict(capture=pin(d/'CAPTURE.json'),complete_capture=c,complete_members=[pin(q) for q in sorted(d.rglob('*')) if q.is_file()],whole_current_foreign_epoch=e))
    return result
def tree_entries(data):
    need(data.endswith(b'\0'),'Complete null-delimited Git tree');out={}
    for line in data[:-1].split(b'\0'):
        fields,n=line.split(b'\t',1);mode,kind,oid=fields.decode().split();name=n.decode();safe(name);need(name not in out and re.fullmatch('[0-9a-f]{40}',oid),'Unique whole Git tree entry');out[name]=dict(mode=mode,kind=kind,oid=oid)
    return out
def index_entries(data):
    need(data.endswith(b'\0'),'Complete grouped NUL-delimited index');out={}
    for line in data[:-1].split(b'\0'):
        fields,n=line.split(b'\t',1);mode,oid,stage=fields.decode().split();name=n.decode();safe(name);need(name not in out and mode in {'100644','100755'} and re.fullmatch('[0-9a-f]{40}',oid) and stage=='0','Exact unique regular stage-zero index entry');out[name]=dict(mode=mode,kind='blob',oid=oid)
    return out
def blob_identity(body,oid,size,digest):
    need(type(body) is bytes and type(size) is int and len(body)==size and sha(body)==digest and hashlib.sha1(b'blob '+str(size).encode()+b'\0'+body).hexdigest()==oid,'Complete in-place body size/SHA256 and literal Git blob identity')
    return (oid,size,digest)
def verify_object_metadata(expectations):
    expected={}
    for oid,size,digest in expectations:
        need(re.fullmatch('[0-9a-f]{40}',oid) and re.fullmatch('[0-9a-f]{64}',digest) and type(size) is int and size>=0,'Typed actual object expectation');need(oid not in expected or expected[oid]==(size,digest),'Conflicting verified whole-body object identity');expected[oid]=(size,digest)
    ids=sorted(expected);out=command(['git','cat-file','--batch-check'],(''.join(oid+'\n' for oid in ids)).encode());lines=out.splitlines();need(out.endswith(b'\n') and len(lines)==len(ids),'Complete grouped object type/size response')
    for oid,line in zip(ids,lines):
        parts=line.split(b' ');need(len(parts)==3 and parts[0].decode()==oid and parts[1]==b'blob' and re.fullmatch(b'0|[1-9][0-9]*',parts[2]) and int(parts[2])==expected[oid][0],'Every actual existing Git object type/size matches its full in-place body identity')
    return len(ids)
def bootstrap(ready):
    if not __debug__ or sys.flags.optimize or os.environ.get('PYTHONOPTIMIZE','') not in ('','0'):raise ValueError('Nonoptimized exact source')
    os.environ['GIT_OPTIONAL_LOCKS']='0';os.environ['GIT_LITERAL_PATHSPECS']='1'
    for k in ['GIT_DIR','GIT_WORK_TREE','GIT_INDEX_FILE','GIT_OBJECT_DIRECTORY','GIT_ALTERNATE_OBJECT_DIRECTORIES']:os.environ.pop(k,None)
    def raw(p,expected):
        if type(expected) is not int or p.is_symlink() or any(q.is_symlink() for q in p.parents) or not p.is_file():raise ValueError('Regular typed source mode')
        before=p.stat()
        if stat.S_IMODE(before.st_mode)!=expected:raise ValueError('Exact full07777 source mode at read')
        with p.open('rb') as stream:b=stream.read()
        after=p.stat()
        if (before.st_dev,before.st_ino,before.st_size,before.st_mtime_ns,before.st_ctime_ns,before.st_mode)!=(after.st_dev,after.st_ino,after.st_size,after.st_mtime_ns,after.st_ctime_ns,after.st_mode):raise ValueError('Source body/fullmode changed during read')
        return b
    source=raw(Path(__file__),0o644)
    if A.name!='pr48_2961' or source!=raw(P/Path(__file__).name,0o444):raise ValueError('Exact ROOT adjacent copy')
    b=raw(P/'SOURCE_READY.json',0o444)
    if hashlib.sha256(b).hexdigest()!=ready:raise ValueError('ROOT readiness hash')
    z=next(z for z in json.loads(b)['source_files'] if Path(z['path']).name=='epoch_common.py');cb=raw(R/z['path'],0o444)
    if len(cb)!=z['bytes'] or hashlib.sha256(cb).hexdigest()!=z['sha256']:raise ValueError('Cached verified common source')
    if stat.S_IMODE(P.stat().st_mode)!=0o755 or raw(R/z['path'],0o444)!=cb:raise ValueError('Prepared directory/common fullmode before cached compile')
    c=types.ModuleType('epoch_common');c.__file__=str(P/'epoch_common.py');sys.modules['epoch_common']=c;exec(compile(cb,c.__file__,'exec'),c.__dict__);c.source_read(Path(__file__),0o644);c.source_read(P/'epoch_common.py',0o444);return c,source

def main():
    global D,SOURCE,OUTER,EC,EPOCH,READY,SOURCE_MF,POST_SOURCE_MODES
    need(__debug__ and sys.flags.optimize==0 and os.environ.get('PYTHONOPTIMIZE','') in ('','0'),'Nonoptimized guards');need(A.name=='pr48_2961' and raw(Path(__file__))==raw(A/'post_push_foreign_epoch_preparation_v5/inspect_complete_actual_post_epoch_v5.py')==raw(A/'ROOT_POST_EPOCH_V5_INSPECTION_PRELAUNCH_SOURCE.py'),'ROOT exact new SOURCE/prelaunch copies; old inspector preserved')
    p=argparse.ArgumentParser();p.add_argument('--source-ready-sha256',required=True);p.add_argument('--source-manifest-sha256',required=True);p.add_argument('--foreign-epoch',required=True);p.add_argument('--foreign-epoch-sha256',required=True);p.add_argument('--epoch-author-capture',required=True);p.add_argument('--root-commit-capture',required=True);p.add_argument('--root-push-capture',required=True);p.add_argument('--root-author-capture',required=True);p.add_argument('--root-ready-capture',required=True);p.add_argument('--root-body-capture',required=True);p.add_argument('--root-merge-capture',required=True);p.add_argument('--root-stage-capture',required=True);p.add_argument('--outer-capture-directory',default='root_complete_actual_post_epoch_v5_inspection_capture');args=p.parse_args();EC,_=bootstrap(args.source_ready_sha256);READY=args.source_ready_sha256;SOURCE_MF=args.source_manifest_sha256;_,new=EC.closed_packet(READY,SOURCE_MF);original=EC.original_sources();EPOCH=EC.validated_epoch(R/safe(args.foreign_epoch),args.foreign_epoch_sha256,'post',R/safe(args.epoch_author_capture),READY,SOURCE_MF);EPOCH['_actual_path']=safe(args.foreign_epoch);safe(args.outer_capture_directory);need('/' not in args.outer_capture_directory,'Exact adjacent ROOT outer capture');OUTER=A/args.outer_capture_directory/'prelaunch_operator.py';SOURCE=raw(Path(__file__));need(sha(raw(OUTER))=='c1ae969ccbbc48ed6fb486e96184da94329291a46b27d2b891ecb87185c909ec','Genuine ROOT CAP4 operator')
    need(not (A/'ROOT_ACTUAL_POST_INSPECTION.json').exists() and not (A/'ROOT_POST_RUNTIME_EVIDENCE.json').exists() and not (A/'ROOT_POST_ACTUAL_READONLY_COMMANDS.json').exists(),'No replacement of ROOT post/evidence');os.umask(0o022)
    post=load(A/'post_acceptance_verification.json');contract=load(H/'ROOT_POST_CONTRACT.json');need(sha(raw(H/'PREPARATION_MANIFEST.json'))==PREP and sha(raw(H/'ROOT_POST_CONTRACT.json'))==CONTRACT and contract['schema']=='pr48-future-ROOT-whole-post-contract/v1' and contract['source_only'] is True,'Exact actually closed48 V3 SOURCE/contract');need(type(contract['future48_required_ROOT_complete_keyset']) is list and len(contract['future48_required_ROOT_complete_keyset'])==22,'Exact22-key normative ROOT contract')
    fresh=load(A/'ROOT_FRESH_ACCEPTANCE_INPUT_PREIMAGES.json');before_native=native(fresh);pre=load(A/'integration_preflight.json');overlay=load(A/'integration_check.json');accept=load(A/'acceptance.json');remote=load(A/'remote_merge_receipt.json');final=load(A/'integration_finalization.json');need(pre['main_before']==fresh['current_head'] and fresh['approved_by_root'] is True and fresh['schema']=='pr48-root-fresh-acceptance-input-preimages/v1','Actual fresh/preflight authority');pinnames=['preparation_manifest_sha256','final_plan','final_plan_sha256','final_receipt','final_receipt_sha256','final_manifest','final_manifest_sha256','reconciliation_capture','reconciliation_capture_sha256','previous_mirror','previous_mirror_sha256','previous_post','previous_post_sha256','fresh_preimage','fresh_preimage_sha256','root_bindings','root_bindings_sha256'];pins={n:post[n] for n in pinnames};need(pins['preparation_manifest_sha256']==PREP,'Actual phase/post SOURCE pin');caps=phase_captures(pins,overlay,fresh)
    prepared=load(H/'PREPARATION_MANIFEST.json');need(prepared['schema']=='pr48-acceptance-source-closure/v3' and prepared['self_excluded']==['PREPARATION_MANIFEST.json'] and type(prepared['files_count']) is int and prepared['files_count']==len(prepared['files'])==53 and len({z['path'] for z in prepared['files']})==53,'Exact pinned53 source before any production import')
    for z in prepared['files']:check(H,z);need(stat.S_IMODE((H/z['path']).stat().st_mode)==0o444,'Every entire prepared source body and full0444 before import')
    names={z['path'] for z in prepared['files']}|{'PREPARATION_MANIFEST.json'};need({q.relative_to(H).as_posix() for q in H.rglob('*') if q.is_file()}==names and {q.relative_to(H).as_posix() for q in H.rglob('*') if q.is_dir()}=={p.as_posix() for n in names for p in PurePosixPath(n).parents if p.as_posix()!='.'} and all(not q.is_symlink() and (q.is_file() or q.is_dir()) for q in H.rglob('*')) and stat.S_IMODE((H/'PREPARATION_MANIFEST.json').stat().st_mode)==0o444,'Complete fixed V3 SOURCE topology and self mode before ROOT runtime import')
    D=A/'ROOT_POST_EPOCH_V5_ACTUAL_READONLY_COMMANDS';D.mkdir(exist_ok=False);put(D/'PRELAUNCH_SOURCE.py',SOURCE);put(D/'PRELAUNCH_OPERATOR.py',raw(OUTER));POST_SOURCE_MODES=post_source_modes();need(eq(POST_SOURCE_MODES['runtime'],EPOCH['source_modes_before']['runtime']),'Actual inspector source versions/fullmodes equal genuine post epoch');g=EC.activate(EPOCH,'post',original,new,git)
    g.foreign_check(pre)
    actual=argparse.Namespace(execute=True,**pins);frozen,gatepins=g.gates(actual);need(eq(gatepins,pins),'Entire actual17 gate pins');g.canonical(frozen,True);g.manifest(K,'MANIFEST.json',accept['canonical_manifest_sha256'],1957,frozen=True);need(accept['canonical_manifest_entries']==1957 and len(overlay['canonical_overlay_files'])==1955,'Exact actual1957 payload+self versus1955 merge overlay');g.accepted_invariants(load(K/'acceptance.json'),pins,pre);g.accepted_invariants(accept,pins,pre,audit=True)
    merge=accept['merge_commit'];need(merge==post['merge_commit']==final['merge_commit']==remote['mergeCommit']['oid'] and git('show','-s','--format=%P',merge).decode().strip().split()==[pre['main_before'],HEAD] and git('merge-base',HEAD,'c6975ca76f9f667f1250ba403d0e6da2aafe14d0').decode().strip()==BASE,'Exact actual merge/original parent/base identity');git('merge-base','--is-ancestor',merge,'HEAD');need(git('branch','--show-current').decode().strip()=='main' and git('show','-s','--format=%T',merge).decode().strip()==post['merge_tree']==accept['merge_tree'],'Actual main and whole Git tree identity')
    patch=load(K/'ACCEPTED_QUEUE_PATCH.json');oldq=raw(A/'integration_queue_before.md');old=patch['row_before'].encode();newrow=patch['row_after'].encode();queue=oldq.replace(old,newrow,1);current_queue=g.current_epoch_queue_check(queue);need(sha(oldq)==patch['whole_before_sha256']==pre['whole_queue_before_sha256'] and sha(queue)==patch['whole_after_sha256']==overlay['whole_queue_after_sha256'] and oldq.count(old)==1 and queue.replace(newrow,old,1)==oldq,'Original merge whole queue inverse replacement is dated history; current unrelated rows authenticated separately');new=newrow;oc=old.split(b'|');nc=new.split(b'|');need([i for i in range(len(oc)) if oc[i]!=nc[i]]==[8,9,11] and oc[8].strip()==b'queued' and nc[8].strip()==b'unsolved' and oc[9].strip()==b'0/5' and nc[9].strip()==b'2/5' and oc[10]==nc[10] and oc[12]==nc[12],'Only selected Status/Turns/Findings, Chat/DOI exact')
    prefix=K.relative_to(R).as_posix()+'/';tree=tree_entries(git('ls-tree','-r','-z',merge,'--',prefix,*sorted(g.NATIVE),*fresh['protected_foreign_tracked_paths']));rr=overlay['canonical_overlay_files'];need({n for n in tree if n.startswith(prefix)}=={prefix+z['path'] for z in rr},'Entire original-head1955 Git canonical topology');changed=set(git('diff-tree','-r','--no-commit-id','--name-only','-z',pre['main_before'],merge).decode().split('\0'))-{''};need(changed=={prefix+z['path'] for z in rr}|{'unsolved_math_prioritization/QUEUE.md'},'Exact owned overlay plus one whole queue changed paths')
    current_tree=tree_entries(git('ls-tree','-r','-z',EPOCH['current_head'],'--',prefix,*sorted(g.NATIVE),*fresh['protected_foreign_tracked_paths']));grouped_index=index_entries(git('ls-files','--stage','-z','--',prefix,*sorted(g.NATIVE),*fresh['protected_foreign_tracked_paths']));need(eq(grouped_index,current_tree) and git('diff','--no-ext-diff','--no-textconv','--cached','--name-only','-z')==b'','Current selected whole index authenticated by current descendant HEAD, clean staging');need(all(eq(current_tree[n],e) for n,e in tree.items() if n.startswith(prefix) or (n in g.NATIVE and n!='unsolved_math_prioritization/QUEUE.md')),'All original canonical and other tracked native Git identities preserved; unrelated foreign commits and QUEUE authenticated in current epoch')
    expectations=[]
    for z in rr:
        n=prefix+safe(z['path']);e=tree[n];need(e['mode']=='100644' and e['kind']=='blob','All canonical merge Git100644 blobs')
        if z['path'] in g.ADMIN:
            pending=load(C/z['path']);pending.update(**g.SCIENCE,**pins,id=2961,current_context_path='CURRENT_CONTEXT_PRESENT.md',current_audit_scope_path='CURRENT_AUDIT_SCOPE_PRESENT.md',current_gate='accepted_qualified_partial',current_verdict=g.WHOLE_VERDICT,status='unsolved_accepted_standard_partial_integration_pending_remote_verification',new_whole_current_gate=g.WHOLE_VERDICT,historical_verdict_transferred=False);body=g.encode(pending)
        else:body=raw(K/z['path'])
        expectations.append(blob_identity(body,e['oid'],z['bytes'],z['sha256']))
    initial=tree_entries(git('ls-tree','-r','-z',pre['main_before'],'--',*sorted(g.NATIVE),*fresh['protected_foreign_tracked_paths']))
    saved={'draft_pr_publication_program_20260930/inventory.json':A/'integration_inventory_before.json','unsolved_math_prioritization/QUEUE.md':A/'integration_queue_before.md','unsolved_math_prioritization/state.json':A/'integration_state_before.json','unsolved_math_prioritization/history.jsonl':A/'integration_history_before.jsonl'}
    for z in fresh['files']:
        n=z['path']
        if n not in saved:need(eq(pin(R/n),{k:z[k] for k in ['path','bytes','sha256']}),'Every stable9 fresh whole worktree body retained, including ignored caches')
        if n in g.IGNORED_CACHE3:need(n not in tree and n not in initial,'Exact three ignored caches absent from both selected Git trees');continue
        need(n in tree and n in initial and tree[n]['mode']==initial[n]['mode']=='100644' and tree[n]['kind']==initial[n]['kind']=='blob','Whole tracked native Git100644')
        oldbody=raw(saved[n] if n in saved else R/n);expectations.append(blob_identity(oldbody,initial[n]['oid'],z['bytes'],z['sha256']))
        if n=='unsolved_math_prioritization/QUEUE.md':expectations.append(blob_identity(queue,tree[n]['oid'],len(queue),sha(queue)))
        else:need(eq(tree[n],initial[n]),'All other tracked native Git entries retained')
    for z in pre['foreign_logs']:
        n=z['path'];e=tree[n];need(eq(e,initial[n]) and (e['mode']+' '+e['kind']+' '+e['oid']+'\t'+n)==z['head_entry'],'Actual merge retained every declared foreign Git entry');body=git('show','--no-textconv',merge+':'+n);expectations.append(blob_identity(body,e['oid'],len(body),z['head_sha256']))
    blobs=verify_object_metadata(expectations)
    prior=load(A/'integration_state_before.json');state=load(R/'unsolved_math_prioritization/state.json');plan=load(A/'state_mirror_plan.json');intent=load(A/'state_mirror_intent.json');receipt=load(A/'state_mirror_receipt.json');proposal=load(A/'state_mirror_bindings.json');oldh=raw(A/'integration_history_before.jsonl');newh=raw(R/'unsolved_math_prioritization/history.jsonl');need(len(prior)==38 and len(state)==39 and set(state)==set(prior)|{'2961'} and all(eq(v,state[k]) for k,v in prior.items()) and eq(state,plan['state_after']) and raw(R/'unsolved_math_prioritization/state.json')==plan['state_after_bytes'].encode(),'Every38 prior state preserved and complete exact native state');need(newh==oldh+plan['history_append_bytes'].encode() and len(plan['history_append'])==1 and eq(parse(newh[len(oldh):]),plan['history_append'][0]),'Whole exact retained history prefix plus one event');event=plan['history_append'][0];need(event['id']=='2961' and event['event']=='acceptance_mirror_import' and type(event['turns_used']) is int and event['turns_used']==2 and event['turn_limit']==5 and event['status']=='unsolved' and all(type(z['turns_used']) is int for z in state.values()) and sum(z['turns_used'] for z in state.values())==47,'Exact shared original2/5 present event,39targets47turns')
    g.mirror_records(pins,pre,plan,intent,receipt,proposal);need(eq(plan,g.rebuild_saved_mirror_plan(proposal,plan['created_at_utc'],raw(A/'integration_state_before.json'),oldh)),'Entire saved plan independently rebuilt at original timestamp');previous=load(R/pins['previous_mirror']);need(eq(proposal['entries'][:-1],previous['entries']) and eq(proposal['duplicate_mirrors'],previous['duplicate_mirrors']) and len(proposal['entries'])==38 and len(proposal['duplicate_mirrors'])==1,'All previous37 primaries and one duplicate retained');m=g.mirror_module(proposal);noop=m.build_plan(R,proposal);m.validate_plan(R,noop);need(noop['history_append']==[] and noop['state_after_bytes'].encode()==raw(R/'unsolved_math_prioritization/state.json') and noop['history_append_bytes']=='' and noop['history_after_sha256']==sha(newh) and raw(R/'unsolved_math_prioritization/history.jsonl')==newh,'Fresh actual replay is a full-byte no-write no-op')
    inv=load(B/'inventory.json');beforeinv=load(A/'integration_inventory_before.json');expected=copy.deepcopy(beforeinv);chosen=next(z for z in expected['items'] if z['number']==48);chosen.update(stage='complete',outcome='unsolved_accepted_partial',queue_status='unsolved',audited_head=HEAD,merge_commit=merge,merged_at=remote['mergedAt'],workflow_completion_estimate_percent=100,original_attempts='2/5',new_substantive_attempts=0,cumulative_attempts='2/5',paper_or_new_doi_or_tracker=False);expected.update(updated_at_utc=final['utc'],last_checkpoint_utc=final['utc'],completed_count=38,program_completion_estimate_percent=38*100/180,completion_estimate_percent=38*100/180,current_pr=49);need(len(beforeinv['items'])==180 and beforeinv['completed_count']==37 and sum(z.get('stage')=='complete' for z in beforeinv['items'])==37 and eq(inv,expected) and sum(z.get('stage')=='complete' for z in inv['items'])==38,'Independent entire180 inventory, other179 records and top-level values exact')
    g.source(K);g.source(C);g.protected_foreign_paths(fresh);g.foreign_check(pre);logs=g.owned_log_append_check(pre);need([z['log'] for z in logs['logs']]==[p.relative_to(R).as_posix() for _,p in g.OWNED_OPERATIONAL_LOGS] and all(type(z['before_worktree_mode']) is int and 0<=z['before_worktree_mode']<=0o7777 and z['before_worktree_mode']==z['after_worktree_mode'] for z in logs['logs']),'Exactly authorized two full-prefix appends/fullmode preservation, generic live foreign equality actually checked');g.finalization(pins,pre)
    phase_logs={z['path']:z for z in caps[3]['complete_capture']['owned_mutable_logs_before']};after_phase_logs={z['path']:z for z in caps[3]['complete_capture']['owned_mutable_logs_after']}
    for z in logs['logs']:n=z['log'];need(eq(z['before'],{k:phase_logs[n][k] for k in ['path','bytes','sha256']}) and eq(z['after'],{k:after_phase_logs[n][k] for k in ['path','bytes','sha256']}) and z['before_worktree_mode']==phase_logs[n]['worktree_mode']==after_phase_logs[n]['worktree_mode'],'Actual finalization capture binds both whole retained prefixes, exact append bodies and all modes')
    sd=A/'root_final_reconciliation_actual_capture';sealer=load(sd/'CAPTURE.json');need({q.name for q in sd.iterdir()}=={'CAPTURE.json','PRELAUNCH_SOURCE.py','PRELAUNCH_OPERATOR.py','stdout.bin','stderr.bin'} and sha(raw(sd/'PRELAUNCH_SOURCE.py'))==sealer['source_sha256']==sha(raw(H/'seal_final_evidence.py')) and raw(sd/'PRELAUNCH_OPERATOR.py')==raw(A/'capture_root_final_operation.py'),'Complete actual sealerCAP5 source/operator');need(clock(sealer['finished_utc'])<=clock(caps[0]['complete_capture']['started_utc']),'Real sealer exited before preflight')
    for c in sealer['readonly_git_queries']:need(c['actual_execution'] is True and c['completed'] is True and type(c['pid']) is int and c['pid']>0 and type(c['exit_code']) is int and c['exit_code']==0 and c['stderr']=='' and clock(c['started_utc'])<=clock(c['finished_utc']),'Every actual readonly sealer query')
    evidence=[]
    mergeexit=load(R/safe(args.root_merge_capture))['exit_code'];need(type(mergeexit) is int and mergeexit in [0,1],'Actual original-head merge may succeed or retain the inspected QUEUE conflict; no fabricated exit')
    roles=[('source_author',args.root_author_capture,0),('ready',args.root_ready_capture,0),('body',args.root_body_capture,0),('original_merge',args.root_merge_capture,mergeexit),('exact_stage',args.root_stage_capture,0)]
    for role,path,exitcode in roles:evidence.append(dict(role=role,**cap4(R/safe(path),exitcode)))
    byrole={z['role']:z for z in evidence};author=byrole['source_author'];authorcap=author['complete_capture'];authorargv=authorcap['argv'];need(authorargv[:2]==['/usr/bin/python3','-B'] and len(authorargv)==4 and authorargv[-1]=='--personally-read-complete-source' and authorargv[2] in [value for n in ['author_ROOT_acceptance.py','author_ROOT_acceptance_v2.py','author_ROOT_acceptance_v3.py'] for value in [str(A/n),(A/n).relative_to(R).as_posix()]],'Genuine specifically read successful ROOT author argv; failed original never promoted')
    authorpath=Path(authorargv[2]) if Path(authorargv[2]).is_absolute() else R/safe(authorargv[2])
    authorout=load(R/Path(author['capture']['path']).parent/'stdout.bin');runtimepath=A/'root_acceptance_author_readonly_inputs/READONLY_INPUT_INSPECTION.json';runtime=load(runtimepath);check(R,authorout['runtime']);need(R/authorout['runtime']['path']==runtimepath and eq(authorout,dict(status='PASS_ROOT_COMPLETE_SOURCE_AND_GENUINE_ACTUAL47_FRESH_BINDINGS',actual_pid=authorcap['pid'],prepared=53,adversary=48,individual_external=4386,complete_source_captures=10,actual47_phase_captures=6,actual_readonly_Git_children=len(runtime['all_complete_readonly_Git_captures']),fresh_current_main=fresh['current_head'],protected_foreign_paths=fresh['protected_foreign_tracked_paths'],plan_references=len(load(A/'ROOT_FINAL_PLAN.json')['immutable_evidence_references']),fresh_authority=pin(A/'ROOT_FRESH_ACCEPTANCE_INPUT_PREIMAGES.json'),runtime=pin(runtimepath),future_execution_approved=False)),'Entire actual successful author stdout and precise source/runtime counters')
    need(eq(runtime['entire_fresh_native_authority'],fresh) and runtime['native13_before_after_equal'] is True and runtime['HEAD_index_foreign_body_fullmode_unchanged'] is True and runtime['source_preparation_executed_this_author'] is False and runtime['future_acceptance_completed'] is False and eq(runtime['author_source'],pin(authorpath)) and raw(authorpath)==raw(runtimepath.parent/'PRELAUNCH_OPERATOR.py'),'Entire source-bound actual author runtime and fresh authority')
    for row in runtime['all_complete_readonly_Git_captures']:
        cap=row['complete_capture'];check(R,row['capture']);need(eq(load(R/row['capture']['path']),cap) and cap['schema']=='pr48-root-author-readonly-Git-capture/v1' and cap['actual_execution'] is True and cap['completed'] is True and type(cap['pid']) is int and cap['pid']>0 and type(cap['actual_operator_pid']) is int and cap['actual_operator_pid']==authorcap['pid'] and type(cap['exit_code']) is int and cap['exit_code']==0 and cap['source'] is None and cap['source_unchanged'] is None and cap['operator_unchanged'] is True and cap['operator_sha256']==sha(raw(authorpath)) and cap['cwd']==str(R) and cap['stdin_supplied'] is False and cap['argv'][0]=='git' and cap['argv'][1] in ['branch','rev-parse','diff','ls-tree','ls-files','show'] and clock(authorcap['started_utc'])<=clock(cap['started_utc'])<=clock(cap['finished_utc'])<=clock(authorcap['finished_utc']),'Actual readonly author Git class, null source, genuine child and author interval')
        childdir=(R/row['capture']['path']).parent;need({q.name for q in childdir.iterdir()}=={'CAPTURE.json','PRELAUNCH.json','stdout.bin','stderr.bin'} and {z['path'] for z in row['complete_members']}=={q.relative_to(R).as_posix() for q in childdir.iterdir()},'Exact actual author readonly child complete four-member topology');launch=load(childdir/'PRELAUNCH.json');need(eq(launch,dict(schema='pr48-root-author-readonly-Git-prelaunch/v1',actual_operator_pid=cap['actual_operator_pid'],argv=cap['argv'],cwd=cap['cwd'],source=None,stdin_supplied=False,started_utc=cap['started_utc'])),'Entire typed actual author child prelaunch')
        for k in ['stdout','stderr']:check(R,cap[k])
        need(raw(R/cap['stderr']['path'])==b'','Whole actual author stderr')
        for z in row['complete_members']:check(R,{k:z[k] for k in ['path','bytes','sha256']});need(type(z['full_mode']) is int and stat.S_IMODE((R/z['path']).stat().st_mode)==z['full_mode'],'Actual author readonly member fullmode')
    operations=dict(ready=['gh','pr','ready','48','--repo','AlecKriebel/Math'],body=['gh','pr','edit','48','--repo','AlecKriebel/Math','--body-file',(A/'accepted_pr_body.md').relative_to(R).as_posix()],original_merge=['/usr/bin/python3','-B',str(A/'merge_original_head_ROOT.py')],exact_stage=['/usr/bin/python3','-B',str(A/'stage_original_overlay_ROOT.py')])
    for role,argv in operations.items():
        actualargv=byrole[role]['complete_capture']['argv']
        alternatives=[argv]
        if role in ['original_merge','exact_stage']:alternatives.append(argv[:2]+[Path(argv[2]).relative_to(R).as_posix()])
        need(any(eq(actualargv,value) for value in alternatives),'Exact genuine ROOT argv; only absolute or literal repository-relative script path')
    need(clock(authorcap['started_utc'])<=clock(load(A/'ROOT_SOURCE_ACCEPTANCE_REVIEW.json')['utc'])<=clock(load(A/'ROOT_IMMUTABLE_ACCEPTANCE_BINDINGS.json')['created_utc'])<=clock(authorcap['finished_utc']) and clock(authorcap['started_utc'])<=clock(fresh['created_utc'])<=clock(authorcap['finished_utc']),'Actual source inspection/approval/fresh authority created in successful actual author child')
    need(clock(authorcap['finished_utc'])<=clock(sealer['started_utc']) and clock(caps[0]['complete_capture']['finished_utc'])<=clock(byrole['ready']['complete_capture']['started_utc'])<=clock(byrole['ready']['complete_capture']['finished_utc'])<=clock(byrole['body']['complete_capture']['started_utc'])<=clock(byrole['body']['complete_capture']['finished_utc'])<=clock(byrole['original_merge']['complete_capture']['started_utc'])<=clock(byrole['original_merge']['complete_capture']['finished_utc'])<=clock(caps[1]['complete_capture']['started_utc']),'Actual author/sealer/preflight/ready/body/merge/overlay order')
    for p in sorted((A.parent/'pr45_9900007').glob('root_pr48_source_acceptance_author*/CAPTURE.json')):
        c=load(p)
        if c['exit_code']!=0:evidence.append(dict(role='preserved_failed_source_author',**cap4(p,c['exit_code'])))
    commit=cap4(R/safe(args.root_commit_capture));push=cap4(R/safe(args.root_push_capture));need(commit['complete_capture']['argv'][:2]==['git','commit'] and push['complete_capture']['argv']==['git','push','origin','main'],'Actual ROOT commit/push whitelist and complete genuine captures');evidence.extend([dict(role='successful_merge_commit',**commit),dict(role='successful_push',**push)])
    for p in sorted((A.parent/'pr45_9900007').glob('root_pr48_original_head_merge_commit*/CAPTURE.json')):
        c=load(p)
        if c['exit_code']!=0:evidence.append(dict(role='preserved_failed_commit',**cap4(p,c['exit_code'])))
    need(clock(commit['complete_capture']['started_utc'])>=clock(caps[1]['complete_capture']['finished_utc']) and clock(commit['complete_capture']['finished_utc'])<=clock(caps[2]['complete_capture']['started_utc']) and clock(caps[2]['complete_capture']['finished_utc'])<=clock(push['complete_capture']['started_utc'])<=clock(push['complete_capture']['finished_utc'])<=clock(caps[3]['complete_capture']['started_utc']),'Actual successful commit/prepush/push/finalize order')
    observed=parse(command(['gh','pr','view','48','--repo','AlecKriebel/Math','--json','number,url,state,isDraft,headRefOid,headRefName,baseRefName,mergeCommit,mergedAt,body']));need(eq(observed,remote) and remote['body']==raw(A/'accepted_pr_body.md').decode(),'Fresh entire actual remote and accepted body exact')
    expected_post={**contract['future48_required_entire_post_values'],**pins,'utc':post['utc'],'merge_commit':merge,'merge_tree':accept['merge_tree'],'actual_remote_state':'MERGED'};need(eq(post,expected_post) and clock(caps[-1]['complete_capture']['started_utc'])<=clock(post['utc'])<=clock(caps[-1]['complete_capture']['finished_utc']),'Entire typed actual verifier post created during genuine final child');need(eq(before_native,native(fresh)),'ROOT inspection leaves every native13 full body and complete fresh mode unchanged')
    root_source=load(A/'ROOT_SOURCE_ACCEPTANCE_REVIEW.json');need(eq(root_source['entire_actual_PR47_ROOT_post'],load(P47/'ROOT_ACTUAL_POST_INSPECTION.json')) and root_source['actual_PR47_native13_epoch_qualification']['mutable_native4_are_dated_observations_not_future_live_authority'] is True,'Actual completed47 retained precisely as predecessor; old native queue never future authority')
    after_native=native(fresh);need(eq(before_native,after_native),'Final native13 readback remains exact before ROOT-only outputs');result=dict(schema=contract['future48_required_ROOT_schema'],**contract['future48_required_completed_values'],utc=stamp(),entire_post=post,all_six_real_phase_captures=[z['capture'] for z in caps],current13=after_native,final_sealer_actual_capture=pin(sd/'CAPTURE.json'));need(set(result)==set(contract['future48_required_ROOT_complete_keyset']) and len(result)==22 and all(eq(result[k],v) for k,v in contract['future48_required_completed_values'].items()),'Exact22 completed ROOT keys and typed values')
    put(A/'ROOT_POST_ACTUAL_READONLY_COMMANDS.json',encode(COMMANDS));put(A/'ROOT_POST_RUNTIME_EVIDENCE.json',encode(dict(schema='pr48-root-post-runtime-evidence/v5',utc=stamp(),source=pin(Path(__file__)),complete_actual_phase_captures=caps,actual_root_operations=evidence,complete_actual_final_sealer=sealer,complete_owned_log_append_receipt=logs,actual_Git_object_metadata_unique_objects=blobs,canonical_merge_bodies_checked_in_place_by_full_Git_blob_identity=True,all_readonly_commands=pin(A/'ROOT_POST_ACTUAL_READONLY_COMMANDS.json'),native13_before=before_native,native13_after=after_native,PR47_native_epoch_is_dated_not_future_live_authority=True,foreign_live_equality_was_actually_checked=True,foreign_live_equality_scope='current genuine post epoch; original five dated only',post_push_source_manifest=EC.ref(EC.P/'SOURCE_MANIFEST.json'),post_push_source_ready=EC.ref(EC.P/'SOURCE_READY.json'),declared_delegations=EC.DELEGATIONS,actual_post_epoch={k:v for k,v in EPOCH.items() if k!='_actual_path'},readonly_response_bodies_retained_on_disk=False,mode_contract=EC.MODE_CONTRACT,source_mode_bindings_before=POST_SOURCE_MODES,source_mode_bindings_after=post_source_modes(),actual_final_three_mode_custody=[dict(phase=z['complete_capture']['phase'],before=z['complete_capture']['source_modes_before'],after=z['complete_capture']['source_modes_after']) for z in caps[3:]],no_native_Git_remote_scientific_mutations=True)));put(A/'ROOT_ACTUAL_POST_INSPECTION.json',encode(result));need(eq(after_native,native(fresh)),'Every native13 body/mode preserved through actual ROOT output authoring');g.foreign_check(pre);EC.closed_packet(READY,SOURCE_MF);need(eq(post_source_modes(),POST_SOURCE_MODES),'Actual source/ROOT operator/prelaunch fullmodes preserved through completed ROOT output authoring');EC.artifact_modes(A,['ROOT_POST_ACTUAL_READONLY_COMMANDS.json','ROOT_POST_RUNTIME_EVIDENCE.json','ROOT_ACTUAL_POST_INSPECTION.json']);print(json.dumps(dict(status='PASS_COMPLETE_ACTUAL_ROOT_POST_INSPECTION',merge_commit=merge,primary_acceptances=38,targets=39,consumed_substantive_turns=47,inspection=pin(A/'ROOT_ACTUAL_POST_INSPECTION.json'),runtime_evidence=pin(A/'ROOT_POST_RUNTIME_EVIDENCE.json'),actual_Git_object_metadata_unique_objects=blobs,canonical_merge_bodies_checked_in_place_by_full_Git_blob_identity=True)))
if __name__=='__main__':main()
