"""Write literal PR48 source-claim inventory; performs no mathematical acceptance."""
from pathlib import Path
import datetime as dt, hashlib, json, os
A=Path(__file__).resolve().parent
def sha(b):return hashlib.sha256(b).hexdigest()
def write(p,b):
    with p.open('xb') as f:f.write(b);f.flush();os.fsync(f.fileno())
def main():
    source=Path(__file__).read_bytes();write(A/'INVENTORY_PRELAUNCH_SOURCE.py',source)
    m=json.loads((A/'snapshot_manifest.json').read_bytes());n=json.loads((A/'ORIGINAL_CURRENT_NATIVE_SELECTED_READ.json').read_bytes());s=json.loads((A/'ORIGINAL_SELECTED_NATIVE_SOURCE_READ.json').read_bytes());r=json.loads((A/'ORIGINAL_COMPLETE_READ_RECEIPT.json').read_bytes())
    assert m['original_files']==r['original_files_read_in_full']==17 and m['whole_repository_diff_files']==18 and r['helper_execution_performed'] is False and r['mathematical_predicates_reproduced'] is False and r['acceptance_verdict'] is None
    text='''# PR48 original-head inventory — preservation only

This inventory records every scientific route and source-dependent claim in the original PR48 package. It gives no current mathematical verdict. Original dated PASS, source-read, runtime/model/reasoning, literature-status and gate statements are attributed claims, not present reproduction or acceptance. All original helpers remain unexecuted. ROOT acceptance, independent source/mathematical review, native transition, and merge remain pending.

## Exact target and boundary

The original plain source record has integer ID2961, code KP-4.85, title Kirby Problem4.85. It asks whether there exists a closed orientable smooth four-manifold X such that the ordinary commutator lengths in the full smooth identity component G=Diff^infinity_0(X) are unbounded. Successful resolution would require an explicit unbounded sequence in one such full group, or a theorem ruling out all such examples. The original package supplies neither and calls itself unresolved, stalled and without novelty.

The separate plain related source record has integer ID30004403, code OWR-17471-009. The original claims exact duplication with KP-4.85 and shared outcome/turn budget. Its record statement and original/clean statement fields are all preserved literally; duplicate equivalence has not been freshly authenticated against the primary reports here. No subgroup, conservative/symplectic/fiber-preserving group, covering group, fragmentation norm, stable-length-only argument, finite permutation experiment, or statement about nonorientable or lower-dimensional manifolds substitutes for the target.

The original states [a,b]=aba^-1b^-1 and composition acts on the rightmost argument first. Smooth regularity is C-infinity. For disconnected closed X, it claims finitely many components, a direct product decomposition of the identity component, and ordinary commutator length equal to the maximum component length by projection and padding; this reduction requires the stated component/group/perfectness hypotheses and independent verification.

## Original mathematical claims and exact gaps

1. **Imported perfectness and non-uniformity distinction.** Mather–Thurston perfectness gives finite ordinary lengths in the stipulated groups. The problem asks for unbounded finite lengths. These imported infinite-dimensional theorems have not been proved or source-verified by this preservation stage. The finite differentiability exception r=dimX+1 must not be used to answer the C-infinity target.
2. **Published no-middle-handle bound.** Tsuboi2012 Theorem1.1(2), printed p142, is claimed to bound width by4 for a compact even-dimensional manifold admitting a handle decomposition without middle-index handles, including four-dimensional no-2-handle manifolds. The new general theorem1.2 is stated to start in dimension6. The package claims S1xS3 has Morse/handle indices0,1,3,4 and #_k(S1xS3) has counts(1,k,0,k,1). This is a literature-credit correction to the K3 remark that only S4 is understood. No implication H2=0 => no2-handles is assumed. Fresh source-hypothesis and handle-construction verification remains required.
3. **Lemma1, displacement compression.** For H<=G and conjugates H,FHF^-1,...,F^mHF^-m commuting pairwise, h=c1...cm with ci=[ai,bi] and ai,bi in H is claimed to have ambient length<=2. T=conjugation byF; A=product T^i(ai), B=product T^i(bi) for i1..m; suffix si=c_(i+1)...cm for i0..m-1; C=product T^i(si). Claimed identity h=[C,F][A,B], using s_i s_(i-1)^-1=c_i^-1 and only inter-copy commutation. Increasing product order, arbitrary noncommuting ci, m1, empty identity case, non-injective commuting conjugate copies and reversed/prefix negative controls matter. Written proof and old controls are preserved; no identity was executed here.
4. **Lemma2, compact-isotopy portable product.** For closed connected smooth M, every element of Diff^infinity_(c,0)(MxR2), with isotopy having compact total support, is claimed to have length<=2. Imported perfectness first supplies a finite factorization. All map supports fit in MxB_R; choose L>2R and a compactly supported vector field equal to L partial_x on the full finite corridor through m translated disks. Its time-one map displaces the relevant copies, with compact support/isotopy, and Lemma1 applies. Compactness of M, finitely many factors, full trajectories inside the constant corridor, and extension in the same isotopy group are substantive hypotheses. The package does not claim the closed product MxS2 is portable.
5. **Proposition3, stabilized-element ambient bound.** For closed connected M and f in Diff^infinity_0(M), cl_Diff0(MxS2)(f xid)<=4. A smooth isotopy f_t and two open disks U,V with compactly contained cutoff supports give a(x,y)=(f_chi(y)(x),y), b(x,y)=(f composed f_chi(y)^-1(x),y), b composed a=f xid. The claimed isotopies a_s=f_(s chi), b_s=f_s composed f_(s chi)^-1 have compact total supports in MxU and MxV. Lemma2 supplies two commutators each, extended by identity into the full ambient identity component. No one-parameter-subgroup property is assumed. Smooth inverse dependence, compact support, extension, composition order and identity endpoints remain independent proof obligations. The bound concerns these stabilized elements only, all dimensions of M as stated; for surface M it is four-dimensional.
6. **Stable length and Corollary4.** The proposition applied to all powers is claimed to imply zero ambient stable commutator length on the stabilized subgroup. A homogeneous quasimorphism q with defectD is claimed conjugation invariant and bounded byD on one commutator, hence by(2k-1)D on k commutators. For k4, |n q(f xid)|<=7D implies q vanishes there. This proves no general absence of quasimorphisms on the full group. Defect conventions, inversion, homogeneity and n->infinity require review.
7. **Corollary5, no retraction for positive genus.** An abstract retraction of the full Diff0(Sigma_gxS2) onto Diff0(Sigma_g) restricting to the identity on the product inclusion would send ambient four-commutator factorizations to a uniform surface bound4. The contradiction imports BHW Corollary1.3 for closed orientable positive-genus surfaces. The claim does not require continuity of the retraction. Fresh BHW scope verification is required; genus0 is outside this consequence.
8. **General cutoff failure.** The same point-dependent-time idea need not make a diffeomorphism for a general ambient isotopy. The original example rotates S2 by angle t about the third axis and uses tau=(1+2xy)/2 in[0,1]. At w=(0,1,0), v=(-1,0,0), d tau(v)=-1, so the derivative kills v before an invertible rotation. The original independent receipt claims tangent rank1 with surviving z direction. This is a negative control, not an obstruction to every possible ambient factorization.
9. **Cocycle averaging defect.** For c(fg,x)=c(f,gx)c(g,x), target quasimorphism psi and integrability of all displayed terms, Q(f)=integral psi(c(f,x))dmu gives Q(fg)-Q(f)-Q(g)=integral psi(c(f,y))d(g_*mu-mu)(y)+E, |E|<=Dpsi. Invariance of probabilitymu removes the extra term; without it the extra term has no established uniform bound. The package blocks only the direct invariant-measure route, not all averaging constructions or all quasimorphisms. Change-of-variable conventions and integrability are explicit assumptions.
10. **No full-group invariant probability.** For positive-dimensional closed connected smooth X, the package claims the full Diff0 action admits no invariant Borel probability. A chart ball with closure in a larger chart can be shrunk/moved by local smooth isotopies into arbitrarily many pairwise disjoint small balls; invariance forces mass0; a finite chart-ball cover contradicts mass1. Atomic and singular measures are included by the claimed argument. Independent verification must justify all local isotopies and packings. Dimension0 and restricted conservative groups are outside the stated assertion.
11. **Subgroup inequality and extension.** For H<=G, cl_G(h)<=cl_H(h); unbounded subgroup lengths do not supply ambient lower bounds. Surface stabilization is the concrete claimed collapse. A subgroup quasimorphism needs a justified extension to G.
12. **Central-kernel descent criterion.** For 1->Z->Gtilde->G->1 central, a homogeneous quasimorphism on Gtilde is claimed to descend iff it vanishes on Z. Sufficiency uses additivity on commuting elements by homogenizing (az)^n=a^n z^n. Nonzero kernel values obstruct descent; a universal-cover construction requires this check. Kernel centrality and precise group/quasimorphism definitions matter.
13. **Fragmentation direction.** In the usual isotopy-fragmentation setting, the original imports cl_G(f)<=2 frag(f) from the local two-commutator bound. Unbounded fragmentation yields no ambient lower bound; zero stable length on a subgroup does not prove a uniform ordinary bound on G. The package does not assume every ball-supported mapping class is locally isotopic to identity.

The two original ledger mechanisms are surface-product transfer and cocycle averaging beyond conservative subgroups, both partial_stalled at the original dated5% estimate. Their exact gaps are no ambient lower-bound sequence/uniform factorization for arbitrary diffeomorphisms, and no replacement bounded-defect construction on the full group. Both routes remain blocked absent materially new mechanisms; preservation introduces0 substantive research turns. The current target discovery percentage is not estimated by this preparer.

## Original helpers, results, and reviews

The three Python bodies are read and syntax-parsed only. check_algebra.py and review/author_replay/check_algebra.py are byte-identical; their results JSON are also byte-identical. The author helper writes check_results.json and reads PARTIAL.md beside itself, so future replay must use an isolated writable copy and preserve its exact inputs. Its literal old receipt says all_passed true,6570 assertions,1332 exhaustiveS3 wreath cases,490 seed485 sampledS5 cases, maximum7 commutators,357 noncommuting controls,900 cutoff factorizations, and a singular derivative check. These finite checks do not prove imported perfectness, smooth support claims, an infinite-dimensional theorem or the target.

The independent helper imports SymPy and prints JSON. The old receipt says PASS,228 assertions, SymPy1.14.0, free-group cases1..9, maximum9 input commutators,108 finite cocycle action pairs and43 nonzero noninvariant defects. All24 named check counts are preserved literally, sum228, including reversed-commutator/prefix negative controls, freely reduced wreath words, a smooth determinant-one non-one-parameter matrix family, exact sphere Jacobian and rational finite-measure controls. Their structural inspection is not execution. Neither helper's conclusions are adopted as current PASS.

The original review claims author6570 byte-identical reproduction and228 independent controls, no required corrections, PASS_PARTIAL, project unsolved and no novelty. The original reviewed mathematical hash differs from final PARTIAL.md because the original says only the review-status sentence changed. Both literal hashes and the final report/hash references are preserved, and stale original result hashes are not mislabeled as final artifact hashes. SOURCE_AUDIT.md still says separate review pending, while README/log/readiness/review say it passed; this is a literal historical package inconsistency to explain, not evidence of present review. Original modelgpt-6-astra, reasoningxhigh, runtime window and reviewer identities are dated attribution fields only; actual runtime settings have not been authenticated.

## Complete original source-claim inventory

The primary-source claims requiring future literal-source verification are: K3 Problem4.85 and all remarks on printed pp259–260, attribution to Hokuto Konno; Webb OWR8/2020 Quasimorphisms on homeomorphism groups printed pp487–489, Question3 p489, DOI10.4171/OWR/2020/8; BIP group conventions, section1.3 Definition1.16, Euclidean product examples, Theorem1.18 and algebra/proof of2.2(i); Tsuboi published2012 p142 Theorem1.1(2), Theorem1.2 dimension>=6, introduction/support conventions and corrections to earlier general-position statements; BHW Theorem1.2/Corollary1.3, fine-curve-graph actual-curve conventions and introduction's no-middle-handle recollection. The original five full-PDF retrieval/read/visual-inspection/hash claims are provenance statements only in this stage. No foreign PDF, text, OCR or pixels are copied or freshly authenticated here.

Source corrections claimed: the AIM kirbylistrep.pdf URL is only a four-page workshop report, not the full K3 list; the K3 only-S4 remark needs qualification because no2handle examples include S1xS3 and connected sums; the related record's linked even-dimensional paper is Tsuboi, not its quoted label Fukui and Rybicki; the duplicate source's workshop/report date is February2020/OWR2020/8 although dataset prose mentions2021; the raw/SQLite source provenance is revision37e53eabe540fb458758e198be61634bd02ee008 with the stated dataset attribution/license. All are original source claims rather than this preparer's current findings.

The source record's literature notes also import Mather1971 Topology10 297–298 DOI10.1016/0040-9383(71)90022-X; Mather1974 CMH49 512–528 DOI10.1007/BF02566746; Thurston1974 BAMS80 304–307 DOI10.1090/S0002-9904-1974-13475-0; BIP2008 ASPM52 221–250 DOI10.2969/aspm/05210221; Tsuboi2008 ASPM52 505–524 DOI10.2969/aspm/05210505; Tsuboi2012 CMH87(1)141–185 DOI10.4171/CMH/251; BHW2022 JAMS35(1)211–231 DOI10.1090/jams/981. The listed perfectness, nonuniform surface positive-genus result, sphere/uniform dimension exceptions and triage open classifications require future theorem/scope/literature verification if relied upon. The record's metadata fields, full category/difficulty/set bodies, dated background triage and related record's source/repair fields are preserved in full as data; import/published timestamps do not certify mathematical status or proposal dates.

The original dated search claims current results through30September2026, excludes later nonorientable-surface, Hamiltonian, sphere/three-manifold bounded-cohomology and bundle/submanifold-preserving objects, and says no resolution was verified. Edtmair arXiv2509.16327 is claimed about Hamiltonian smooth perfectness/local factorizations; Monod–Nariman arXiv2111.04365 is claimed insufficient in its specified groups/degrees. Those exclusions were expressly abstract-level, not full paper audits. Their time-sensitive completeness/status is unverified here. The original prior-attempt gate claims searches of state/history/assessment/update/reset histories, related groups, all-ref paths, branches and all-state PRs found no prior2961/30004403 attempt; this stage preserves that dated claim and reads selected current/head native data but does not repeat every gate search.

## Raw/source/SQLite and native-selection semantics

All raw problems/reports and SQLite file bytes are fully read in place and hashed, with no foreign corpus-body copy. Full JSON parsing checks duplicate keys, integer sourceIDs, unique numericIDs and record/code selection. Exact raw numericIDs2961 and30004403 each match their original plain source record in full. Their SQLite rows match raw payloads, SQLite keys are strings, and each report literal is '{}'. For each exact code KP-4.85 and OWR-17471-009 the raw report key is ABSENT. This differs from a present key with null value and from a present empty object. There is no prior_report.json among the17 originals. SOURCE_AUDIT's statement 'research-results entry is null' is preserved as prose and is not adopted as actual key presence. queue.py sync supplies{} for absent report keys; show prints a wrapper {review_hash,problem,prior_research}. The original source_record and related_source_record are plain problems, not that wrapper. Both constructed wrapper representations are recorded only to make semantics explicit; queue.py is not executed.

Native catalog/history IDs are strings, unlike raw source integerIDs. Initial original_native_selected list selection incorrectly required integerID and produced empty catalog selection. It remains intact as attributed initial evidence. original_native_selected_v2 uses exact string-ID equality and records both target and related selections in full, with an explicit correction receipt. No keyword, serialized-hash substring, or descriptive search establishes selected-record identity. The initial dictionary selection already records explicit key presence/value; missing state is not present-null.

The observed current13 native inputs are the program inventory and queue/state/history/catalog/assessments/queue.py/policy/manifest/raw problems/raw reports/SQLite/related-target-groups files. Each full body is read and individually bound to bytes/SHA/full permission mode and current-main observation. Selected catalog/assessments, state key presence, all exact-ID history and assessment-history events, exact queue rows, full policy/groups and relevant queue-source functions are recorded separately for both IDs. Head native catalog/assessments/state/histories/manifest/groups are separately Git-object bound. These dated read-only observations give no authority for future main and perform no native transition. Mathematical equivalence of the duplicate, source truth and current literature status remain independent review tasks.

## Scope, failures, and pending operations

The original scientific subtree has17 blobs at Git mode100644; complete scientific and whole-repository head trees include every Git entry, kind/mode/objectID. The whole-repository diff is untruncated, binary-capable and based on actual merge base rather than the GitHub base field. All17 added science hunks reconstruct the preserved bodies byte-exactly. The full original GitHub metadata and paginated file payloads are retained along with full actual streams and source-bound execution captures.

Two genuine failed operations remain preserved: the initial head-object lookup exit128 before read-only fetch, and export_v1 exit1 because the queue includes a leading rank column and its first selector assumed the ID starts the row. Corrected export_v2 is separate, verifies any existing prior output byte equality, and writes only absent paths. The later exact-string-native-selection correction is explicitly retained rather than silently replacing initial data. No failure is converted into success in the record.

Preparer authorship is limited to the enumerated original-preparation root files and declared original subtrees. Future mathematical-review families and ROOT sibling files are excluded. Closure is prepared for ROOT's genuine external capture after the child exits; it must bind and freeze the owned files at full mode0444 and list exact directory topology. No canonical/native/index/branch/remote changes, helper reproduction, commit/push, paper or DOI action is performed by this preparation.
'''
    text+='\n## Literal pins and full scientific file manifest\n\n'
    text+='Head `'+m['head']+'`; GitHub base `'+m['github_base']+'`; actual merge base `'+m['merge_base']+'`; export-observed main `'+json.loads((A/'original_pr_metadata.json').read_bytes())['observed_main_head']+'`; typed-read-observed main `'+n['observed_main_head']+'`.\n\n'
    for row in m['files']:text+='- '+row['relative_path']+' — Git'+row['git_mode']+' blob '+row['git_object']+'; '+str(row['bytes'])+' bytes; SHA256 '+row['sha256']+'.\n'
    text+='\nOriginal foreign provenance claims (not fresh authentication):\n\n'
    for row in r['complete_original_JSON_values']['source_checksums.json']:text+='- '+row['cache_filename']+' — '+str(row['bytes'])+' bytes; SHA256 '+row['sha256']+'; '+row['url']+'.\n'
    text+='\nOriginal full diff — '+str(r['full_diff_bytes_read'])+' bytes; SHA256 '+r['full_diff_sha256']+'.\n'
    write(A/'ORIGINAL_CLAIM_INVENTORY.md',text.encode())
    at=dt.datetime.now(dt.timezone.utc).isoformat()
    log='''# PR48 original preparation research log

Scope: literal preservation and source-claim inventory only. No scientific helper executes and no mathematical acceptance, native transition or publication is authorized to this preparer. No external-individual communication. All work stays in pr48_2961; main is retained and index/remote/commit/push/paper/DOI writes are excluded. Progress percentages concern original preparation only, not discovery.

2026-10-03T05:00:43+00:00 — Original GitHub metadata/file capture started. Exact target2961/KP-4.85; independent related record30004403/OWR-17471-009 preserved as deliberately supplied original scientific data. Source preparation10%; claim validation0%; new substantive turns0.

2026-10-03T05:00:44+00:00 — Initial local head-object check genuinely exited128. Full error/stdout retained. Read-only object fetch without ref/FETCH_HEAD/tag writes then exited0 and exact commit bodies were captured. Source preparation20%; claim validation0%.

2026-10-03T05:02:45+00:00 — First export genuinely exited1 at rank-prefixed queue selection. All earlier original17 science bodies,18-path complete diff and full head-tree outputs remained retained. Separate corrected exporter verifies equality of any existing data and uses an exact queue cell. Source preparation45%; claim validation0%.

2026-10-03T05:03:21+00:00 — Corrected export exited0. Fresh OPEN draft head/base, actual mergebase,17 original blobs and complete22 scientific tree entries/36538 whole-repository tree entries bound. Complete18-path diff80679 bytes. Individually read/current13 native input bodies bound without foreign corpus-body copying. Source preparation65%; claim validation0%.

2026-10-03T05:07:10+00:00 — Typed inspection exited0. All17 scientific bodies,8 JSON values,2-line JSONL ledger and3 helper ASTs read without executing helpers; original6570/228 receipts structurally attributed. Full17 added hunks reconstruct source bytes. Both raw exact numericID records equal plain original/SQLite payloads. Both raw report keys are absent; SQLite supplies{}, no original prior file exists, and original prose null is not presence. Native list IDs are strings; initial integer selector's empty catalog is retained and separate exact-string correction supplied. Current13 reread with date/main binding; all selected states/histories/queue rows/policy/groups preserved. Source preparation85%; independent source/mathematical claim validation0%; new substantive turns0.

'''
    log+=at+' — Complete original source-claim inventory authored: all target/scope distinctions,13 mathematical families,7 additional bibliographic source claims,5 literal primary-source pins, dated status/gate/model fields, helper limits, source/plain/wrapper/prior distinctions and failed/corrected execution chain recorded. Source preparation95% pending genuine ROOT closure/readback; claim validation0%; mathematical acceptance/ROOT review/merge PENDING.\n'
    write(A/'RESEARCH_LOG.md',log.encode());assert Path(__file__).read_bytes()==source
    print(json.dumps(dict(status='ORIGINAL_CLAIM_INVENTORY_AUTHORED_ONLY',inventory_bytes=len(text.encode()),inventory_sha256=sha(text.encode()),original_preparation_percent=95,claim_validation_percent=0,helper_replays=0,acceptance_verdict=None),sort_keys=True))
if __name__=='__main__':main()
