#!/usr/bin/env python3
"""Independent finite logical/necessary-consistency controls, never an existence proof."""
import fractions,hashlib,itertools,json,pathlib
F=fractions.Fraction
counts={}
def check(name,value):
 if not value:raise AssertionError(name)
 counts[name]=counts.get(name,0)+1
def props(n,R):
 reflexive=all((i,i) in R for i in range(n))
 transitive=all((i,k) in R for i,j in R for a,k in R if j==a)
 antisymmetric=all(i==j or (j,i) not in R for i,j in R)
 symmetric=all((j,i) in R for i,j in R)
 return reflexive,transitive,antisymmetric,symmetric
sizes={}
for n in (2,3):
 cells=list(itertools.product(range(n),repeat=2));preorders=posets=0
 for mask in range(1<<len(cells)):
  R={cells[i] for i in range(len(cells)) if mask>>i&1}
  ref,trans,anti,sym=props(n,R)
  check('antisymmetry_witness_equivalence',anti==(not any(i!=j and (i,j) in R and (j,i) in R for i in range(n) for j in range(n))))
  if not(ref and trans):continue
  preorders+=1;posets+=anti
  classes={frozenset(j for j in range(n) if (i,j) in R and (j,i) in R) for i in range(n)}
  C=sorted(classes,key=lambda x:tuple(sorted(x)))
  Q={(i,j) for i,A in enumerate(C) for j,B in enumerate(C) if (min(A),min(B)) in R}
  check('preorder_mutual_quotient_is_partial_order',all(props(len(C),Q)[:3]))
  check('quotient_relation_representative_independent',all(((a,b) in R)==((i,j) in Q) for i,A in enumerate(C) for j,B in enumerate(C) for a in A for b in B))
 sizes[str(n)]={'relations':1<<len(cells),'preorders':preorders,'partial_orders':posets}
check('known_finite_preorder_counts',sizes=={'2':{'relations':16,'preorders':4,'partial_orders':3},'3':{'relations':512,'preorders':29,'partial_orders':19}})
chain={(0,0),(1,1),(0,1)}
check('nonsymmetric_relation_can_be_partial_order',props(2,chain)==(True,True,True,False))
check('mutual_distinct_pair_fails_antisymmetry',props(2,set(itertools.product(range(2),repeat=2)))==(True,True,False,True))

def stabilize(tb,rot,positive,negative):return tb-positive-negative,rot+positive-negative
for a,b in itertools.product(range(8),repeat=2):
 pair=stabilize(-1,0,a,b)
 check('same_stabilizations_preserve_classical_equality',pair==stabilize(-1,0,a,b)==(-1-a-b,a-b))
for k in range(13):
 check('balanced_both_sign_values',stabilize(-1,0,k,k)==(-1-2*k,0))
 if k:check('opposite_single_sign_rotations_mismatch',stabilize(-1,0,k,0)[1]!=stabilize(-1,0,0,k)[1])
for g,h in itertools.product(range(7),repeat=2):
 chi1,chi2=-2*g,-2*h
 possible=(-chi1)+(-chi2)==0
 check('two_way_connected_orientable_genus_constraint',possible==(g==0 and h==0))
check('wrong_tb_euler_sign_detected',(-(-2))==2 and (-2)!=2)

# Algebra of end constants after positive symplectization scaling; no geometric realization inferred.
for r1,r2 in ((F(1),F(1)),(F(2),F(3)),(F(1,3),F(5,7))):
 for a1,b1,a2,b2 in ((F(0),F(1),F(3),F(-2)),(F(-7),F(2),F(0),F(9)),(F(1,2),F(2,3),F(-1,5),F(3,8))):
  shift=r1*b1-r2*a2
  check('glued_knot_end_constants_match',r2*a2+shift==r1*b1)
  check('composite_action_difference_adds',r2*b2+shift-r1*a1==r1*(b1-a1)+r2*(b2-a2))
check('one_shift_cannot_normalize_unequal_ends',not any(F(2)+s==0 and F(3)+s==0 for s in map(F,range(-5,6))))
check('connected_multicomponent_global_shift_mismatch',F(1)-F(0)!=F(4)-F(1))

# An annulus H1 is generated by an end circle. Handles supply independent periods.
for genus in range(5):
 rank=2*genus+1
 period=[0]*rank
 if genus:period[1]=1
 check('zero_boundary_periods_force_all_only_for_annulus',(not any(period))==(genus==0))
 if genus:check('handle_period_countercontrol',period[0]==0 and any(period[1:]))

# SO(2) viewed inside U(2) has complex determinant1. The homotopy consequence is derived in prose.
for q in map(F,range(-4,5)):
 c=(1-q*q)/(1+q*q);s=2*q/(1+q*q)
 check('SO2_in_U2_complex_determinant_one',c*c+s*s==1)

root=pathlib.Path(__file__).resolve().parent
result={'assertions_passed':sum(counts.values()),'counts':counts,'finite_relation_counts':sizes,
 'source_sha256':hashlib.sha256(pathlib.Path(__file__).read_bytes()).hexdigest(),
 'scope':'Finite logic and exact classical/genus/end-constant/homology consistency. No Legendrian identification or Lagrangian cobordism construction; existence remains an attributed primary-theorem input.'}
print(json.dumps(result,indent=2))
