"""Seal the completed single joint source/configuration review; no native or services."""
from pathlib import Path
import datetime,hashlib,json,os,stat
O=Path(__file__).absolute().parent;A=O.parent;D=A/'native_publication_integration_plan_20261006/corrected_v5';now=datetime.datetime.now(datetime.timezone.utc).isoformat()
def h(b):return hashlib.sha256(b).hexdigest()
def canon(v):return (json.dumps(v,sort_keys=True,indent=2,ensure_ascii=False)+'\n').encode()
auth=json.loads((O/'EXACT_INPUT_AUTHENTICATION.json').read_bytes());normal=json.loads((O/'NORMAL_RESULTS.json').read_bytes());optimized=json.loads((O/'OPTIMIZED_RESULTS.json').read_bytes());criteria=json.loads((O/'CRITERIA_FROZEN.json').read_bytes())
for p,v in [(D/'OUTPUT_MANIFEST.json',auth['source_manifest_sha256']),(D/'EXECUTION_INPUTS_FROZEN_20261006.json',auth['execution_inputs_sha256'])]:
 if h(p.read_bytes())!=v:raise RuntimeError('exact reviewed input changed before seal')
for x in json.loads((D/'OUTPUT_MANIFEST.json').read_bytes())['files']:
 b=(D/x['relative_path']).read_bytes()
 if len(b)!=x['bytes'] or h(b)!=x['sha256']:raise RuntimeError('sealed source changed')
inputs=json.loads((D/'EXECUTION_INPUTS_FROZEN_20261006.json').read_bytes());C=A.parents[2]
for x in inputs['input_files']:
 b=(C/x['path']).read_bytes()
 if len(b)!=x['bytes'] or h(b)!=x['sha256']:raise RuntimeError('nongate input changed')
programs={Path(p['path']).name:{k:p[k] for k in ['bytes','sha256']} for p in inputs['program_files']}
report=f'''# Fresh joint PR108 V5 source and actual configuration review

The exact sealed V5 source and actual frozen execution choices are **clean within this review boundary**. Required findings: **none**. Optional findings: **none**. F10 is closed for the documented narrow physical-line guard and the authenticated actual existing configuration; F09 remains closed. This is the existing combined source/configuration review, not an extra paper or publication review. Actual helper execution, native candidate correctness, public export, acceptance and merge are still subsequent boundaries.

The reviewed source OUTPUT_MANIFEST SHA256 is {auth['source_manifest_sha256']}; its exact111 payloads/1,453,854B plus manifest and seal (113 original sealed files) were authenticated. The five-program family SHA is f0e5185cda10f88894dfc7c94146d7943de3e329b08d0700335c9a486c5a08e2. All five programs were completely read: four retain their V4 bytes and the complete regenerated V4→V5 diff changes only v3_guards.py. Previous source/seal/reviewer pins remain exact. PLAN, correction ledger, scope contracts, inert configuration template and exact prospective merge plan were read. Templates grant no execution approval. Criteria were frozen at {criteria['UTC']} before reading V5/actual inputs; the historical V4 report/source and F10 diagnosis had already been read, as the criteria file candidly records.

F10: CR/LF/CRLF partition lines physically; only ASCII space/tab advances within a clause. Empty, quoted-empty and commented default sockets no longer consume a following key. Nonempty sockets, socket continuations and direct/quoted executable alias clauses or immediate executable continuations reject. The guard explicitly is a narrow conservative field checker, not a general YAML security parser or a certificate against unrelated host tampering. All458 independent pure checks pass normally (PID{normal['actual_PID']}) and under optimization (PID{optimized['actual_PID']}); tests never call prepare, execute, assess or resource setup. Existing35-test normal/optimized custody (PIDs51704/51792) was independently authenticated in full, including observed streams, bounded prefixes, UTC/argv/exit/reaping and terminal OK; the sealed creator fixture suite was not rerun.

F09: canonical whole-control equality independently derives every field from immutable execution choices, all12 native pins and authenticated manifest before applying resources or loading queue.py. Parent rederives against its frozen bytes, checks unchanged control bytes and exact returned control/hash, requested policy, enforced CPU/FSIZE/NOFILE, advisory memory, native identity, actual deadline, exit/reaping and PID. Fresh challenges mutate/omit every control leaf, every returned result leaf, nested extras and numerical types, including valid CPU2 differing from the actual frozen CPU90. Pure source AST establishes validation-before-resource/module order. Darwin memory remains advisory; neither fixtures nor this review claim a hard memory bound or actual native workload success.

The actual readonly0444 execution input is69,303B SHA{auth['execution_inputs_sha256']}, bound to main f36cb1e34696d460b9cfb5b03425998de48c4669. The contract has **19** effective-choice keys. Every effective dictionary and all180 nongate registry pins/1,846,309B are exactly unchanged from the old V4 input; only five program paths and the guards body pin change. Every actual registry body was authenticated. Pure direct publication/Sheet/original/effective/package consumers plus proposed gate checked-artifacts consume all180 entries, with no unused or unrepresented input. Exact actual v2 publication and Sheet receipts remain unchanged and directly compatible, including row31 and blankB with existing_chat_authorized=false. The separately completed DOI10.5281/zenodo.23181280, mathematical/priority/package reviews and paperR2 were not reopened or repeated.

The actual preparer successor is independently authenticated at19 payloads/21 actual files, source SHA5bf97b1a9a9cde0a2a12d64cf14ba8e6db2352453de4def9693188b88d89d19b. Its source differs only by three V4→V5 selector/error-message replacements. All12 native baseline body pins correspond to retained actual local-read Git custody; materialized files agree. Runtime Python/git/gh binary hashes, exact Python version/path and private Git/GH config metadata pins were independently streamed, without inspecting or retaining private configuration/credential bodies. Raw JSON and SQL caches were streamed only into hashes; SQL was not opened, and no sidecar exists. Actual original15 file/body/source/absence-of-structured-ledger bindings retain claimed_solved2/5 and captured exact{{}} imported report, with zero new central proof-search turns. All46 scientific publication payload bindings remain exact.

Root's actual clean-runtime read probe PID54847 exited0; actual child PIDs54848/54849/54850 returned AlecKriebel, the unchanged OPEN draft PR108 head3526d46bf143b08e5055ffa7728c6278e9f958ea and remote main f36cb1e34696d460b9cfb5b03425998de48c4669. Its complete source, outer startup argv/exit/stdout/stderr, all three bounded stream bodies/hashes/role environments/PIDs/ordered times/reaping, frozen input hash and before/after metadata-only private configuration validation are authenticated. Root inspected actual private bodies inside its guarded probe; this auditor did not. No token/config body enters the nongate/public-copy registry. This is actual root operational custody, not success inferred from synthetic JSON flags.

The complete conservative allocation independently matches every destination by path:426 enumerated files plus one exclusive atomic slot=427≤512;12 private baselines,9 possible global outputs,208 exact copies,7 gate slots at their64KiB maxima,46 package files,9 generated metadata files,7 wrappers and128 bounded stream slots. Maximum materialized allocation135,358,232B includes the22,260,037B exclusive native atomic slot. Required space194,078,488B adds16MiB future commit reserve,32MiB headroom and8MiB runtime reserve. At {auth['free_space_timestamp']}, free space was{auth['observed_free_bytes']}B, sufficient. This is a dated snapshot: root/helper must check free space immediately before candidate creation and at later boundaries. The16MiB commit reserve is supported as a bounded-storage operational choice: the actual checkpoint script retains4096B prefixes/full counts/hashes, not duplicate49MB Gitshow bodies. It is an estimate, not a guarantee of future Git memory/disk use. No deletion or capacity workaround was used by this auditor.

Public export must remove exactly the two reviewed offered full-sheet metadata and DOI-dedup stdout bodies, while preserving private originals and their exact receipt references/pins. The helper offers all captured inputs into a private candidate; this source review does not mistakenly certify that its offers are already a public-export selection. No private runtime configuration body is offered. The two25B Git-reserved synthetic fixture configs remain exact in source and root's V5 ZIP recovery archive; they are synthetic fixtures and never live configs. Original archives, effective diagnostics, package files, state/assessment dictionaries, ledger prefixes, all unrelated catalog rows/ranks/positions and physical CSV/campaign spans have explicit preservation checks. Explained stale status/turn/eligibility projections require exact native predicates; eligibility-only unexplained false drift rejects. Target proof/import/effort and global9-path offer scope remain strict.

The review dependency graph is acyclic: prior science/service artifacts and code→immutable input; code+input+actual runtime custody→this report/verdict; those separately byte-pinned review artifacts→pre-execution/final root gates; final→six antecedent gate hashes; thin config→immutable input and all seven gates. This new report cannot be placed in input_files because it already depends on that input SHA. Root may bind its exact REPORT/VERDICT/authentication as additional gate evidence outside the immutable manifest, independently authenticate them and issue its own true review flags. The helper permits such extra evidence, but JSON flags or tests alone do not constitute root review. No thin config or actual gates were written by this auditor, and no currently nonexistent gate is declared verified.

The prospective main-only ours merge plan has no concrete flaw found: after an independently reviewed actual candidate/full DIFF and scoped native acceptance, it preserves the accepted tree exactly and incorporates authenticated originalhead as second parent. The original incoming15 attempt files plus QUEUE are accounted for by original archival bytes and reviewed effective contents. Actual tree/two-parent/head/index/CAS/GitHub MERGED/OID readbacks remain required during action. This review executed no Git or service command, no native/SQL operation, no export/install/commit/merge and no human outreach.

Auditor tooling corrections are preserved honestly. An initial count expectation20 was corrected to the actual19 keys; subsequent independent oracle mistakes compared capacity insertion order instead of destination identity and used outer PID instead of its actual child_PID field. Exact failed script versions and retained actual failure traces/custody are saved; the first direct count failure has metadata and source preservation but no separately retained PID. None changed source or configuration. The final exact-input authentication succeeded with3,442 custody/pin checks (PID58099), and the full independent semantic pure suite passes458 checks per mode. Historical files labelled SUCCESS record their real exit1 and are not success evidence.

Current joint review completion is100%. The remaining gap is fresh root gate/commissioning and current capacity/head checks, then actual private native candidate execution and complete independent candidate review before any scoped export/acceptance or merge. No new review stage, paperR3, publication, Sheet append or proof turn is requested.
'''
(O/'REPORT.md').write_text(report)
verdict={'schema':'pr108-fresh-joint-V5-source-actual-configuration-adversary/v1','UTC':now,'actual_sealer_PID':os.getpid(),'required_findings':[],'optional_findings':[],'exact_source_and_actual_frozen_choices_review_clean':True,'source_output_manifest_sha256':auth['source_manifest_sha256'],'source_core_family_sha256':'f0e5185cda10f88894dfc7c94146d7943de3e329b08d0700335c9a486c5a08e2','reviewed_program_pins':programs,'execution_inputs_sha256':auth['execution_inputs_sha256'],'main_parent':'f36cb1e34696d460b9cfb5b03425998de48c4669','effective_choice_count':19,'input_count':180,'input_bytes':1846309,'source_sealed_payloads':111,'source_original_sealed_files':113,'F09':'Closed; full immutable control/result correspondence independently challenged.','F10':'Closed in documented narrow guard and actual pinned runtime configuration; not a general YAML parser.','independent_pure_checks_per_mode':458,'independent_pure_PIDs':[normal['actual_PID'],optimized['actual_PID']],'sealed_creator_tests_per_mode':35,'sealed_creator_PIDs':[51704,51792],'exact_pin_custody_check_count':3442,'exact_auth_actual_PID':58099,'actual_root_clean_runtime_PID':54847,'actual_root_readonly_child_PIDs':[54848,54849,54850],'actual_runtime_private_configuration_process_authenticated':True,'private_body_contents_read_or_copied_by_auditor':False,'capacity_choices_and_complete_allocation_review_clean':True,'capacity_slots':427,'capacity_materialized_max_bytes':135358232,'required_free_bytes':194078488,'observed_free_bytes':auth['observed_free_bytes'],'capacity_snapshot_UTC':auth['free_space_timestamp'],'capacity_snapshot_sufficient':True,'fresh_free_space_check_before_candidate_required':True,'private_sheetbody_public_export_exclusions':2,'public_export_selection_or_native_execution_cleared':False,'native_or_SQL_execution_or_Git_or_services_by_auditor':0,'actual_new_thin_configuration_or_gates_written':False,'current_or_future_root_gates_declared_verified':False,'future_root_gates_may_bind_report_outside_immutable_manifest':True,'DAG_self_cycle_found':False,'original_status':'claimed_solved','original_budget':'2/5','original_structured_ledger_present':False,'new_central_proof_search_turns':0,'extra_PRs_processed':0,'published_DOI':'10.5281/zenodo.23181280','Sheet_range':"'Math Puzzles'!A31:D31",'Sheet_B_blank':True,'unchanged_math_priority_paper_publication_review_repeated':False,'new_paper_R3_required':False,'merge_plan_concrete_flaw_found':False,'merge_plan_is_prospective_only':True,'joint_review_completion_percent':100,'remaining_gap':'Root issues exact manifest-bound gates and commissions only after fresh head/capacity checks; actual native candidate/fullDIFF/readbacks and independent bundle review precede export, acceptance and actual merge readbacks.','all_writes_confined_to_own_new_review_folder':True,'human_contact_or_outreach_prepared_or_made':False}
(O/'VERDICT.json').write_bytes(canon(verdict))
log=f"# PR108 fresh joint source/configuration research log\n\n{criteria['UTC']}: Criteria saved beforeV5/input read; historicalV4 context already read. Review5%.\n\n{auth['UTC']}: Final exact source/input/actual-root custody authentication complete after correcting independent oracle key-count/order/outer-field mistakes;458 pure checks pass per mode. Review95%; no source/config finding.\n\n{now}: Single joint review sealed, required/optional findings none; review100%, actual native/candidate/export/merge remain unexecuted and uncleared. Math/package/publication unchanged; no extra central proof turn.\n"
(O/'RESEARCH_LOG.md').write_text(log)
files=[]
for p in sorted(O.rglob('*')):
 if not p.is_file() or p.name in ['OUTPUT_MANIFEST.json','SEAL_RECEIPT.json']:continue
 if p.is_symlink():raise RuntimeError('output symlink')
 b=p.read_bytes();files.append({'relative_path':str(p.relative_to(O)),'bytes':len(b),'sha256':h(b),'mode':format(stat.S_IMODE(p.stat().st_mode),'04o')})
manifest={'schema':'pr108-joint-V5-review-output-manifest/v1','UTC':now,'actual_sealer_PID':os.getpid(),'file_count':len(files),'total_bytes':sum(v['bytes'] for v in files),'files':files}
(O/'OUTPUT_MANIFEST.json').write_bytes(canon(manifest))
seal={'schema':'pr108-joint-V5-review-seal/v1','UTC':now,'actual_sealer_PID':os.getpid(),'sealed':True,'manifested_file_count':len(files),'allfiles_including_manifest_and_seal':len(files)+2,'manifested_bytes':manifest['total_bytes'],'output_manifest_sha256':h((O/'OUTPUT_MANIFEST.json').read_bytes()),'REPORT_sha256':h((O/'REPORT.md').read_bytes()),'VERDICT_sha256':h((O/'VERDICT.json').read_bytes()),'required_findings':[],'optional_findings':[],'source_output_manifest_sha256':auth['source_manifest_sha256'],'execution_inputs_sha256':auth['execution_inputs_sha256'],'joint_review_complete_percent':100,'native_execution_and_actual_candidate_export_merge_clearance':False}
(O/'SEAL_RECEIPT.json').write_bytes(canon(seal));print(json.dumps(seal))
