#!/usr/bin/env python3
"""Seal completed independent preexecution work, never authorizes future outputs."""
import pathlib,types,os,json
W=pathlib.Path(__file__).resolve().parent
v=types.ModuleType('seal_review');v.__file__=str(W/'verify_actual_candidate.py');exec(compile(pathlib.Path(v.__file__).read_bytes(),v.__file__,'exec'),v.__dict__)
A=v.A;D=A/'native_post_assess_carryforward_v3_20261006'
def ap(p):return {'path':str(p.relative_to(A)),**v.regular(p,retain=False)}
r=v.obj(v.regular(W/'LINEAR_CARRYFORWARD_PREEXEC_CONTROLS_normal.json'));s=v.obj(v.regular(W/'LINEAR_CARRYFORWARD_PREEXEC_CONTROLS_optimized.json'))
v.check(all(r[k]==s[k] for k in ['program_pin','action_program_pin','integration_inputs_pin','stopped_continuation_inventory_pin','stopped_CPU_continuation_inventory_pin','linear_diff_program_pin','outer_launcher_pin','future_action_outer_pin']),'Both exact final-source modes agree')
v.check(r['sealed_payload_files_authenticated']==14 and r['checks']==527438 and s['checks']==527438 and r['future_candidate_approved'] is False and s['future_candidate_approved'] is False,'Completed finite independent pure review only')
for key in ['program_pin','action_program_pin','integration_inputs_pin','stopped_continuation_inventory_pin','stopped_CPU_continuation_inventory_pin','linear_diff_program_pin','outer_launcher_pin','future_action_outer_pin']:v.audit(r[key])
v.check(not (D/'workspaces/candidate_d9eb646c1dd70e89').exists(),'New actual candidate not invented')
ad={'schema':'pr110-post-assess-carryforward-adversary/v1','UTC':v.now(),'actual_reviewer_PID':os.getpid(),'actual_review':True,'clearance':True,'required_findings':[],'template_only':False,'fixture':False,'simulated':False,'packet_sha256':v.PACKET_SHA,'program_pin':r['program_pin'],'action_program_pin':r['action_program_pin'],'outer_launcher_pin':r['outer_launcher_pin'],'integration_inputs_pin':r['integration_inputs_pin'],'stopped_continuation_inventory_pin':r['stopped_continuation_inventory_pin'],'stopped_CPU_continuation_inventory_pin':r['stopped_CPU_continuation_inventory_pin'],'linear_diff_program_pin':r['linear_diff_program_pin'],'original_resource_policy_unchanged':True,'seed_inventory_pin':ap(A/'native_post_assess_continuation_v1_20261006/SEED_INVENTORY.json'),'failed_run_root_authentication_pin':ap(A/'ROOT_FAILED_NATIVE_RUN_AUTHENTICATION_20261006.json'),'historical_assessed_main_parent':'f9f840d21305bdc353d151abe8dd5c51b6a27dd6','current_integration_main_parent':'e0a94b93520610553c001f265f210f959b591c2c','all_three_failed_workspaces_remain_nonexportable':True,'actual_preexecution_review_completion_percent':100,'future_candidate_approved':False,'live_actions_approved':False,'native_assess_calls_authorized':0,'old_workspace_writes_authorized':False,'preexecution_scope':'Only a new private no-reassessment linear carryforward under these exact reviewed sources/current inputs/bounded outer/original resources. Actual candidate, export, acceptance, PR edits, readiness and merge require later separate actual full-output review.','report_pin':ap(W/'LINEAR_CARRYFORWARD_PREEXECUTION_REPORT.md'),'control_result_pins':[ap(W/n) for n in ['LINEAR_CARRYFORWARD_PREEXEC_CONTROLS_normal.json','LINEAR_CARRYFORWARD_PREEXEC_CONTROLS_optimized.json','LINEAR_DIFF_CONTROL_normal.json','LINEAR_DIFF_CONTROL_optimized.json']],'CPU_stop_independent_custody_pin':ap(W/'CPU_STOP_CUSTODY_RESULT.json'),'sealed_preparation_manifest_pin':ap(D/'OUTPUT_MANIFEST.json'),'sealed_preparation_receipt_pin':ap(D/'SEAL_RECEIPT.json'),'reviewed_root_helper_pins':[ap(A/'publication_build_v1'/n) for n in ['commission_post_assess_carryforward_v3.py','commission_native_action_v4.py','record_native_action_v4.py']],'Git_mutations':0,'service_calls':0}
v.save('LINEAR_CARRYFORWARD_PREEXEC_ADVERSARY.json',ad)
names=['audit_CPU_stopped_offer.py','CPU_STOP_CUSTODY_RESULT.json','verify_linear_diff.py','LINEAR_DIFF_CONTROL_normal.json','LINEAR_DIFF_CONTROL_optimized.json','LINEAR_DIFF_GIT_JOURNAL_normal.json','LINEAR_DIFF_GIT_JOURNAL_optimized.json','PURE_LINEAR_STOPPED_OFFER_DIFF_normal.txt','PURE_LINEAR_STOPPED_OFFER_DIFF_optimized.txt','audit_linear_carryforward_preexecution.py','LINEAR_CARRYFORWARD_PREEXEC_CONTROLS_normal.json','LINEAR_CARRYFORWARD_PREEXEC_CONTROLS_optimized.json','LINEAR_CARRYFORWARD_PREEXEC_GIT_READS_normal.json','LINEAR_CARRYFORWARD_PREEXEC_GIT_READS_optimized.json','LINEAR_CARRYFORWARD_PREEXECUTION_REPORT.md','LINEAR_CARRYFORWARD_PREEXEC_ADVERSARY.json','seal_linear_preexecution_review.py']
files=[{'path':n,**v.regular(W/n,retain=False)} for n in names]
manifest={'schema':'pr110-independent-linear-carryforward-preexecution-manifest/v1','UTC':v.now(),'actual_sealer_PID':os.getpid(),'file_count':len(files),'total_bytes':sum(x['bytes'] for x in files),'files':files,'future_candidate_approved':False,'live_actions_approved':False}
v.save('LINEAR_CARRYFORWARD_PREEXEC_OUTPUT_MANIFEST.json',manifest)
print(json.dumps({'adversary':ap(W/'LINEAR_CARRYFORWARD_PREEXEC_ADVERSARY.json'),'manifest':ap(W/'LINEAR_CARRYFORWARD_PREEXEC_OUTPUT_MANIFEST.json'),'actual_reviewer_PID':os.getpid(),'future_candidate_approved':False}))
