#!/usr/bin/env python3
"""Seal completed actual candidate review; no live phase is executed here."""
import pathlib,types,os,json
W=pathlib.Path(__file__).resolve().parent
v=types.ModuleType('actual_review_seal');v.__file__=str(W/'verify_actual_candidate.py');exec(compile(pathlib.Path(v.__file__).read_bytes(),v.__file__,'exec'),v.__dict__)
A=v.A;D=A/'native_post_assess_carryforward_v3_20261006';candidate=D/'workspaces/candidate_d9eb646c1dd70e89'
def ap(p):return {'path':str(p.relative_to(A)),**v.regular(p,retain=False)}
r=v.obj(v.regular(candidate/'CANDIDATE_RECEIPT.json'));actual=v.obj(v.regular(W/'ACTUAL_LINEAR_CARRYFORWARD_CANDIDATE_RESULT.json'));custody=v.obj(v.regular(W/'ACTUAL_LINEAR_CARRYFORWARD_CUSTODY_RESULT.json'));pre=v.obj(v.regular(W/'LINEAR_CARRYFORWARD_PREEXEC_ADVERSARY.json'))
v.check(actual['candidate_receipt_pin']==custody['candidate_receipt_pin']==v.pin(v.regular(candidate/'CANDIDATE_RECEIPT.json')) and actual['DIFF_pin']==r['DIFF_pin'] and len(actual['actual84_complete_DIFF_application'])==84 and actual['offered_files']==84,'Actual full candidate/DIFF/output/custody match')
v.check(actual['checks']==3335361 and custody['checks']==7567 and actual['actual_output_review_complete'] is True and custody['required_findings']==[],'All final independent guards completed')
v.check(r['continuation_program_pin']==pre['program_pin'] and r['continuation_action_program_pin']==pre['action_program_pin'] and r['integration_inputs_pin']==pre['integration_inputs_pin'] and r['linear_diff_program_pin']==pre['linear_diff_program_pin'] and r['stopped_CPU_continuation_inventory_pin']==pre['stopped_CPU_continuation_inventory_pin'],'Actual output/complete source review exact bindings')
for key in ['program_pin','action_program_pin','integration_inputs_pin','linear_diff_program_pin','stopped_CPU_continuation_inventory_pin']:v.audit(pre[key])
for x in actual['full_candidate_inventory']:v.regular(candidate/x['path'],x,retain=False)
scopes=['full_actual_candidate_DIFF_and_offer_reviewed','actual_native_PID_resources_and_process_custody_authenticated','all17_originals_and_nonempty_prior_preserved','source_cache_readonly_and_original_2_of_5_no_extra_search_turn','unrelated_scores_order_physical_CSV_history_and_campaign_preserved','accepted_full_mathematical_resolution_and_bounded_priority','actual_publication_tracker_and_clean_whole_package_R1_R2','this_exact_source_and_main_only_exact_tree_integration_reviewed']
ad={'schema':'pr110-actual-native-candidate-adversary/v1','UTC':v.now(),'actual_reviewer_PID':os.getpid(),'actual_review':True,'clearance':True,'required_findings':[],'template_only':False,'fixture':False,'simulated':False,'packet_sha256':v.PACKET_SHA,'candidate':str(candidate),'candidate_receipt_pin':actual['candidate_receipt_pin'],'DIFF_pin':r['DIFF_pin'],'main_parent':r['main_parent'],'original_assessed_main_parent':r['original_assessed_main_parent'],'original_head':v.HEAD,'action_program_pin':r['continuation_action_program_pin'],'continuation_program_pin':r['continuation_program_pin'],'linear_diff_program_pin':r['linear_diff_program_pin'],'integration_inputs_pin':r['integration_inputs_pin'],'stopped_continuation_inventory_pin':r['stopped_continuation_inventory_pin'],'stopped_CPU_continuation_inventory_pin':r['stopped_CPU_continuation_inventory_pin'],'original_resource_policy_unchanged':True,'outer_launcher_pin':ap(A/'publication_build_v1/record_native_action_v4.py'),'actual_continuation_outer_launcher_pin':pre['outer_launcher_pin'],'actual_continuation_outer_receipt_pin':{'path':'actual_operations/root_actual_linear_carryforward_20261006/execution.json',**custody['outer_receipt_pin']},'scope_checks':dict.fromkeys(scopes,True),'actual_native_assess_PID':23360,'actual_continuation_PID':74654,'native_assess_calls_during_continuation':0,'live_actions_executed':False,'report_pin':ap(W/'ACTUAL_NATIVE_CANDIDATE_REPORT.md'),'actual_output_result_pin':ap(W/'ACTUAL_LINEAR_CARRYFORWARD_CANDIDATE_RESULT.json'),'actual_custody_result_pin':ap(W/'ACTUAL_LINEAR_CARRYFORWARD_CUSTODY_RESULT.json'),'preexecution_review_pin':ap(W/'LINEAR_CARRYFORWARD_PREEXEC_ADVERSARY.json'),'independent_verifier_framing_correction_pin':ap(W/'ACTUAL_CANDIDATE_VERIFIER_FRAMING_CORRECTION.md'),'actual_worker_memory_advisory_exceeded':True,'actual_continuation_memory_advisory_exceeded':True,'hard_memory_limit_claimed':False,'complete_hostile_SIGKILL_containment_claimed':False,'resource_and_process_absence_scope':'Original CPU/FSIZE/NOFILE readbacks; memory advisory only. Actual observed/recorded groups absent; no stronger exceptional containment claim.','actual_candidate_review_completion_percent':100,'workflow_completion_percent':80,'reviewer_native_assess_calls':0,'reviewer_Git_mutations':0,'reviewer_service_calls':0,'decision_scope':'Completed actual private candidate/source review. Fresh independent root actual review and per-action commissions remain required for every export/acceptance/ready/merge/status phase.'}
v.save('ACTUAL_NATIVE_CANDIDATE_ADVERSARY.json',ad)
names=['verify_actual_candidate.py','verify_linear_carryforward_actual_candidate.py','verify_linear_carryforward_actual_candidate_pre_event_order_fix.py','verify_linear_diff.py','audit_linear_carryforward_actual_custody.py','ACTUAL_LINEAR_CARRYFORWARD_CANDIDATE_RESULT.json','ACTUAL_LINEAR_CARRYFORWARD_CANDIDATE_GIT_READ_JOURNAL.json','ACTUAL_LINEAR_CARRYFORWARD_CUSTODY_RESULT.json','ACTUAL_CANDIDATE_VERIFIER_FRAMING_CORRECTION.md','ACTUAL_NATIVE_CANDIDATE_REPORT.md','ACTUAL_NATIVE_CANDIDATE_ADVERSARY.json','seal_actual_candidate_review.py']
files=[{'path':n,**v.regular(W/n,retain=False)} for n in names];manifest={'schema':'pr110-independent-actual-native-candidate-review-manifest/v1','UTC':v.now(),'actual_sealer_PID':os.getpid(),'file_count':len(files),'total_bytes':sum(x['bytes'] for x in files),'files':files,'source_action_executed':False}
v.save('ACTUAL_NATIVE_CANDIDATE_OUTPUT_MANIFEST.json',manifest)
print(json.dumps({'actual_adversary':ap(W/'ACTUAL_NATIVE_CANDIDATE_ADVERSARY.json'),'report':ap(W/'ACTUAL_NATIVE_CANDIDATE_REPORT.md'),'manifest':ap(W/'ACTUAL_NATIVE_CANDIDATE_OUTPUT_MANIFEST.json'),'actual_reviewer_PID':os.getpid(),'required_findings':[],'live_actions_executed':False}))
