from pathlib import Path
import hashlib,json,subprocess,datetime
p=Path('/Users/alec/Documents/Math/openai_followon_riesz_surface_constants')
u=Path('/Users/alec/Desktop/math')
stamp=datetime.datetime.now(datetime.timezone.utc).isoformat()
files=['README.md','CONTENTS.md','lean/docs/090.md','lean/formalization.yaml','lean/lean-toolchain','lean/lake-manifest.json']
for d in ['Universal-optimality-of-the-triangular-lattice-September-23-2026','An-atomic-certificate-for-triangular-lattice-universal-optimality-September-26-2026']:
 files += [str(q.relative_to(u)) for q in (u/'preprints'/d).rglob('*') if q.is_file()]
rows=[]
for name in sorted(set(files)):
 q=u/name
 if q.is_file(): rows.append({'path':name,'bytes':q.stat().st_size,'sha256':hashlib.sha256(q.read_bytes()).hexdigest()})
r={'checked_at_utc':stamp,'source_clone':str(u),'pinned_commit':subprocess.check_output(['git','rev-parse','HEAD'],cwd=u,text=True).strip(),'public_main_check':subprocess.check_output(['git','ls-remote','https://github.com/openai/math.git','refs/heads/main'],text=True).strip(),'files':rows,'clone_modified':False}
(p/'sources'/'UPSTREAM_MANIFEST.json').write_text(json.dumps(r,indent=2)+'\n')
(p/'RESEARCH_LOG.md').write_text(f'''# Research log: exact hypersingular Riesz constants\n\n## {stamp} — checkpoint 0: isolated intake\n\nMathematical resolution: **5%** (estimate). Publication package: **0%** (estimate).\n\nRead workspace AGENTS.md, source README, family 090 scope, both manuscript-specific citation/verification instructions, and initial triage. Triage is a hypothesis, not proof certification. No previous dedicated effort found in the local or remote tree inspected. Source clone HEAD equals the requested pin. Public main has the same hash; no later source correction was discovered in that check. Source hashes are in sources/UPSTREAM_MANIFEST.json.\n\nFive independent routes are active: main interpolation/certificate proof; atomic companion; real Lean declarations and reproducibility; finite-to-infinite bridge; classical surface theorem/corrections. Their findings will be logged with exact gaps. No outside individual was contacted. No unrelated PR was processed and no files in the separate planar project were changed.\n\nShared local main is diverged from origin/main (one local commit, 123 remote commits in initial check). Shared checkout and index must remain intact. Owned checkpoints will use a temporary index and a commit with current public main as parent, pushed directly to main without force. No GitHub release will be created.\n\nStrongest verified result at intake: the pinned manuscripts state the exact required infinite-configuration theorem. Its validity, actual formal proof and finite transfer are still under independent audit. No unconditional solution is claimed.\n''')
(p/'THEOREM_LEDGER.md').write_text('''# Exact theorem ledger\n\n## Target T1 (unresolved at intake)\nFor every real s>2, the ordered-pair unit-square minimal-energy limit\nC_(s,2)=lim_(N→∞) N^(-1-s/2) min_(x_1,...,x_N∈[0,1]^2) Σ_(i≠j)|x_i-x_j|^(-s)\nis ζ_Λ(s)=Σ_(v∈Λ\\{0})|v|^(-s), with Λ=(√3/2)^(-1/2){(j+k/2,k√3/2): j,k∈Z}, covolume one.\n\n## Target T2 (unresolved at intake)\nFor each compact smooth embedded two-dimensional surface M⊂R^p, with positive area A=H²(M), and every real s>2, the minimal ordered-pair ambient Euclidean-distance energy is asymptotic to ζ_Λ(s) A^(-s/2) N^(1+s/2). Exact boundary scope is to be taken from the checked Hardin–Saff theorem; no broader convention is assumed yet. The unit sphere coefficient is ζ_Λ(s)/(4π)^(s/2).\n\n## Input U (unverified at intake)\nFor every locally finite C⊂R² with # (C∩B_R)/(πR²)→1, and nonnegative smooth completely monotone g on (0,∞),\nliminf_(R→∞) [#(C∩B_R)]^(-1) Σ_(x≠y∈C∩B_R) g(|x-y|²) ≥ Σ_(v∈Λ\\{0})g(|v|²),\nwith equality for Λ, values in [0,∞]. Closed centered disks, ordered pairs, and liminf are exact.\n\n## Excluded conclusions\nNo microscopic crystallization, uniqueness of finite minimizers, s≤2 result, second-order surface term, or full follow-on formalization is asserted.\n\n## Success criteria\nValidate U or repair it rigorously; prove finite transfer with all tails/limits; verify classical surface theorem scope/corrections; independently audit attribution/priority; pass complete package reviews; only then publish and update tracker. Material upstream gaps block unconditional target claims.\n''')
(p/'DEPENDENCY_LEDGER.md').write_text('''# Dependency ledger\n\n| Dependency | Precise role and assumptions | Source and validation basis | Status / gap |\n|---|---|---|---|\n| U: infinite universal optimality | T1 lower bound for locally finite centered-density-one sets; g(t)=t^(-s/2) | Pinned main Theorem 1.1 and atomic Theorem 1.1; source hashes saved | Unverified; independent analytic, certificate and Lean audits pending |\n| Gaussian certificate | Radial Schwartz f≤exp(-πα|x|²), real Fourier f̂≥0, direct/dual contacts | Main construction and atomic companion | Central proof/sign estimates pending; finite checks alone are insufficient |\n| Completely monotone transfer | g smooth, (-1)^r g^(r)≥0; ordered disk liminf | Main mixtures / atomic energy sections | Pending independent review; Riesz derivatives elementary |\n| Finite/infinite bridge | Periodized side √N boxes, ε√N gaps, s>2; density rescale 1/(1+ε) | New project proof | Independent derivation pending |\n| Lattice upper bound | Covolume one, summable ζ for s>2 | Direct counting/tail proof | Pending |\n| Hardin–Saff universality | Positive H², compact embedded C¹ manifold convention; ambient norm | math-ph/0311024, exact version/corrections pending | Scope review pending |\n| BHS Conjecture 2 | Explicit two-dimensional lattice constant, normalization | Vanderbilt 235.pdf | Exact text/provenance pending |\n| Lean | Real declarations, not comparator statements; semantic equality and axiom audit | lean/docs/090.md + actual source closure | Build/semantic audit pending; no formalization claim |\n''')
(p/'APPROACH_TABLE.md').write_text('''# Approach families\n\n| Family | Mechanism | Current evidence | Status | Exact remaining gap |\n|---|---|---|---|---|\n| Main interpolation | Sharp Gaussian Fourier minorants from cardinal construction and interval certificate | Pinned explicit manuscript | Under independent falsification | Complete analytic and certificate validation |\n| Atomic interpolation | Finite atomic certificate and infinite correction | Separate companion, not treated as independent theorem merely because stated | Under independent falsification | Formula correspondence, global signs, tails |\n| Formal route | Kernel-check actual family 090 declarations | Scope document; comparator has intentional sorry | Under semantic/build audit | Actual axiom footprint and pinned build |\n| Periodization | Dense finite boxes with macroscopic gaps; cross-box tails vanish | Proposed estimate O_ε(N^(1-s/2)) | Independent derivation | Check disk energy limits and scaling, then apply validated U |\n| Lattice upper bound / classical universality | Crop Λ into squares, invoke established surface theorem | Classical known machinery | Scope verification | Exact boundary/measure/pair conventions |\n\nA route transferring the central difficulty to an equally strong unsupported claim will be marked blocked and reopened only with a materially new mechanism or evidence.\n''')
(p/'README.md').write_text('''# Exact hypersingular Riesz-energy constants on surfaces\n\nIndependent research effort, author Alec Kriebel (ORCID https://orcid.org/0009-0001-9320-500X).\n\nStatus: **input validation and conditional bridge research; no unconditional resolution or publication yet**. See THEOREM_LEDGER.md, DEPENDENCY_LEDGER.md, APPROACH_TABLE.md and RESEARCH_LOG.md. Upstream pin: adc7f1241b42e322a6451854ab7e4b4c146bf78a.\n\nAI tools are used extensively in research, drafting and verification. Automated reviews are not conventional human peer review. Publication conditions are the exact mathematical resolution, independent priority audit and complete package review required by the user. No deposit or tracker row is authorized before those conditions pass.\n''')
(p/'.gitignore').write_text('''reproducibility/atomic/\nreproducibility/formal/\nreproducibility/upstream_main/\nreproducibility/*venv*/\nsources/classical/*.pdf\nsources/classical/*.tar*\n**/__pycache__/\n**/.lake/\n**/.venv/\n**/*.olean\n**/*.ilean\n**/*.aux\n**/*.log\n**/*.out\nreceipts/private-index-*\n''')
print(json.dumps({'initialized':str(p),'upstream_files_hashed':len(rows),'utc':stamp}))
