#!/usr/bin/env python3
"""Independent HT (12),(35): determinants in Q[z]/Phi_96 and -p/q words.

No supplied calculation is imported. Cyclotomic polynomial is generated by
dividing X^n-1 by recursively generated proper-divisor polynomials. All field
operations use generic polynomial long division, not a hardcoded Phi rule.
Labels are 3-subsets of {1,...,5}, not Dynkin-label loops. Determinants use
recursive minors, not Weyl permutations. Printed output is an exact certificate.
"""
from fractions import Fraction as F
from itertools import combinations
from functools import lru_cache
import json, math, cmath, os

def trim(p):
    while len(p)>1 and p[-1]==0:p.pop()
    return p
def poly_div(a,b):
    a=trim(list(a));q=[0]*max(1,len(a)-len(b)+1)
    while len(a)>=len(b):
        i=len(a)-len(b);c=a[-1]//b[-1]
        assert c*b[-1]==a[-1]
        q[i]=c
        for j,v in enumerate(b):a[i+j]-=c*v
        trim(a)
        if a==[0]:break
    return trim(q),a
def poly_mul(a,b):
    p=[0]*(len(a)+len(b)-1)
    for i,x in enumerate(a):
        if x:
            for j,y in enumerate(b):
                if y:p[i+j]+=x*y
    return trim(p)
@lru_cache(None)
def cyclo(n):
    p=[-1]+[0]*(n-1)+[1]
    for d in range(1,n):
        if n%d==0:
            p,r=poly_div(p,cyclo(d));assert r==[0]
    return tuple(p)
MOD=cyclo(96);DEG=len(MOD)-1
ZERO=(0,)*DEG
def rem(p):
    _,r=poly_div(p,MOD)
    return tuple(r+[0]*(DEG-len(r)))
def plus(a,b):return tuple(x+y for x,y in zip(a,b))
def times(a,b):return rem(poly_mul(a,b))
def scalar(a,c):return tuple(x*c for x in a)
def power(e):
    e%=96
    return rem([0]*e+[1])
ROOT=[power(e) for e in range(96)]
ONE=ROOT[0]
def conjugate(a):
    p=ZERO
    for e,c in enumerate(a):
        if c:p=plus(p,scalar(ROOT[-e%96],c))
    return p
def determinant(m):
    if len(m)==1:return m[0][0]
    ans=ZERO
    for j,e in enumerate(m[0]):
        minor=[row[:j]+row[j+1:] for row in m[1:]]
        ans=plus(ans,scalar(times(e,determinant(minor)),(-1)**j))
    return ans
def matmul(a,b):
    result=[]
    for row in a:
        out=[]
        for col in zip(*b):
            p=ZERO
            for x,y in zip(row,col):p=plus(p,times(x,y))
            out.append(p)
        result.append(out)
    return result
def eye_num(c,charge=False):
    return [[scalar(ONE,c) if (conjugate_label[i] if charge else i)==j else ZERO
             for j in range(len(labels))] for i in range(len(labels))]
def m2mul(a,b):
    return [[sum(a[i][k]*b[k][j] for k in range(2)) for j in range(2)] for i in range(2)]
def negative_cf(p,q):
    coeff=[]
    while q:
        a=p//q;coeff.append(a);p,q=q,a*q-p
    return coeff
def dedekind(a,c):
    c=abs(c)
    return sum((F(j,c)-F(1,2))*(F((a*j)%c,c)-F(1,2)) for j in range(1,c))
def phi(m):
    a,b=m[0];c,d=m[1]
    if not c:return F(b,d)
    return F(a+d,c)-12*(1 if c>0 else -1)*dedekind(d,c)
def nz(p,den=1):return [[i,str(F(c,den))] for i,c in enumerate(p) if c]
def number(p,den=1):return sum(c*cmath.exp(2j*math.pi*i/96) for i,c in enumerate(p))/den

labels=[tuple(reversed(c))+(0,) for c in combinations(range(1,6),3)]
vectors=[tuple(F(x)-F(sum(n),4) for x in n) for n in labels]
conjugate_label=[vectors.index(tuple(-x for x in reversed(v))) for v in vectors]
sqrt6=times(plus(ROOT[12],ROOT[-12]),plus(ROOT[8],ROOT[-8]))
assert times(sqrt6,sqrt6)==scalar(ONE,6)
S=[]
for u in vectors:
    row=[]
    for v in vectors:
        matrix=[]
        for x in u:
            rr=[]
            for y in v:
                e=-16*x*y
                assert e.denominator==1
                rr.append(ROOT[int(e)%96])
            matrix.append(rr)
        row.append(scalar(times(sqrt6,determinant(matrix)),-1))
    S.append(row)
# S numerator denominator 72 follows from -1/(2*6^(3/2))=-sqrt6/72.
assert S[0][0]==scalar(sqrt6,6)
theta=[]
for v in vectors:
    e=8*sum(x*x for x in v)-60
    assert e.denominator==1
    theta.append(int(e))
assert matmul(S,S)==eye_num(72**2,charge=True)
S_star=list(map(list,zip(*[[conjugate(x) for x in row] for row in S])))
assert matmul(S,S_star)==eye_num(72**2)
ST=[[times(x,ROOT[theta[j]%96]) for j,x in enumerate(row)] for row in S]
assert matmul(matmul(ST,ST),ST)==eye_num(72**3,charge=True)

results={}
for q in (9,25):
    a=negative_cf(-64,q)
    # The source orders CF from inner coefficient to outer, then appends 0.
    C=list(reversed(a))+[0]
    m=[[1,0],[0,1]]
    for c in C:
        m=m2mul([[c,-1],[1,0]],m)
    # Apply the word separately, eliminating any state shared with matrix proof.
    v=[ONE]+[ZERO]*(len(labels)-1);den=1
    for c in C:
        next_v=[]
        for i,row in enumerate(S):
            entry=ZERO
            for x,y in zip(row,v):entry=plus(entry,times(x,y))
            next_v.append(times(ROOT[c*theta[i]%96],entry))
        v=next_v;den*=72
    expected=[[q,(q*pow(q,-1,64)-1)//64],[64,pow(q,-1,64)]]
    sign=1 if m==expected else -1
    assert m==[[sign*x for x in row] for row in expected]
    ph=phi(m);assert ph==3
    # c=5, omega=exp(2pi i*5/24)=zeta96^20.
    tau=times(v[0],ROOT[int(20*ph)%96])
    square=times(tau,conjugate(tau))
    assert square==scalar(ONE,den**2//3)
    target=scalar(plus(scalar(ROOT[-4],-1),scalar(ROOT[-20],2)),den//3)
    assert tau==target
    result={'negative_continued_fraction':a,'source_C':C,'word_matrix':m,
      'target_matrix':expected,'Rademacher_phi':str(ph),'denominator':den,
      'tau_polynomial':nz(tau,den),'magnitude_square':str(F(square[0],den**2)),
      'S3_normalized_square':'8','tau_approx':[number(tau,den).real,number(tau,den).imag]}
    results[str(q)]=result
assert results['9']['tau_polynomial']==results['25']['tau_polynomial']
print(json.dumps({'PID':os.getpid(),'method':'determinant modular surgery Q(zeta96), source negative -p/q',
 'cyclotomic_modulus':list(MOD),'labels_strict_integer_coordinates':labels,
 'conjugate_label_indices':conjugate_label,'S00_square':'1/24',
 'exact_checks':['sqrt6^2=6','S00=sqrt6/12','S^2=charge conjugation',
 'S*S_star=I','(S*Theta)^3=charge conjugation','U word matches ±[[q,b],[64,d]]',
 'Phi(U)=3','tau=(-zeta96^-4+2*zeta96^-20)/3','tau*conjugate(tau)=1/3'],
 'results':results,'equal_complex_values':True},indent=2))
