// Independent exact reconstruction of the two-forced-edge schedules.
//
// This verifier deliberately shares no code with
// src/search43_e2_barrier_escape.cpp.  It decodes the 53 frozen low-frontier
// representatives, reconstructs all 47,675 eligible first edges, scans all
// 39,511,631 eligible second edges, and exact-recounts every selected first
// and second graph.  It also independently reconstructs the neutral cycles
// generated by the 22 supplied E=2 seeds.

#include <algorithm>
#include <array>
#include <cstdint>
#include <filesystem>
#include <fstream>
#include <iostream>
#include <map>
#include <set>
#include <stdexcept>
#include <string>
#include <tuple>
#include <unordered_set>
#include <utility>
#include <vector>

namespace {

constexpr int kOrder = 43;
constexpr int kEdgeCount = kOrder * (kOrder - 1) / 2;
constexpr uint64_t kAllVertices = (uint64_t{1} << kOrder) - 1;

struct Edge {
  int u = -1;
  int v = -1;
  bool operator==(const Edge&) const = default;
  bool operator<(const Edge& other) const {
    return std::pair{u, v} < std::pair{other.u, other.v};
  }
};

struct Graph {
  std::array<uint64_t, kOrder> rows{};
};

struct Conflict {
  bool clique = false;
  std::array<int, 5> vertices{};
};

struct First {
  Edge edge;
  int height = 0;
  bool nonconflict = false;
};

struct Arguments {
  std::filesystem::path e3;
  std::filesystem::path e4;
  std::filesystem::path known_directory;
  int ceiling = 80;
};

std::vector<Edge> all_edges() {
  std::vector<Edge> result;
  result.reserve(kEdgeCount);
  for (int u = 0; u < kOrder; ++u)
    for (int v = u + 1; v < kOrder; ++v) result.push_back({u, v});
  if (static_cast<int>(result.size()) != kEdgeCount)
    throw std::runtime_error("edge enumeration is incomplete");
  return result;
}

std::vector<std::string> graph6_lines(const std::filesystem::path& path) {
  std::ifstream input(path, std::ios::binary);
  if (!input) throw std::runtime_error("cannot open graph6 stream: " + path.string());
  std::vector<std::string> result;
  std::string line;
  while (std::getline(input, line)) {
    if (!line.empty() && line.back() == '\r')
      throw std::runtime_error("graph6 stream contains a carriage return");
    if (line.empty() || line.front() == '#')
      throw std::runtime_error("graph6 stream contains a blank/comment record");
    result.push_back(line);
  }
  if (!input.eof()) throw std::runtime_error("graph6 stream read failed");
  if (result.empty()) throw std::runtime_error("graph6 stream is empty");
  return result;
}

Graph decode_graph6(const std::string& text) {
  if (text.empty() || static_cast<unsigned char>(text.front()) - 63 != kOrder)
    throw std::runtime_error("expected short graph6 of order 43");
  if (text.size() != 1 + (kEdgeCount + 5) / 6)
    throw std::runtime_error("graph6 record length is noncanonical");
  Graph graph;
  int cursor = 0;
  for (int right = 1; right < kOrder; ++right) {
    for (int left = 0; left < right; ++left) {
      const int value = static_cast<unsigned char>(text[1 + cursor / 6]) - 63;
      if (value < 0 || value >= 64)
        throw std::runtime_error("invalid graph6 payload byte");
      if ((value >> (5 - cursor % 6)) & 1) {
        graph.rows[left] |= uint64_t{1} << right;
        graph.rows[right] |= uint64_t{1} << left;
      }
      ++cursor;
    }
  }
  for (int bit = cursor; bit % 6; ++bit) {
    const int value = static_cast<unsigned char>(text[1 + bit / 6]) - 63;
    if ((value >> (5 - bit % 6)) & 1)
      throw std::runtime_error("graph6 padding is nonzero");
  }
  return graph;
}

std::string encode_graph6(const Graph& graph) {
  std::string result(1, static_cast<char>(kOrder + 63));
  int value = 0;
  int width = 0;
  for (int right = 1; right < kOrder; ++right) {
    for (int left = 0; left < right; ++left) {
      value = (value << 1) |
              static_cast<int>((graph.rows[left] >> right) & uint64_t{1});
      if (++width == 6) {
        result.push_back(static_cast<char>(value + 63));
        value = 0;
        width = 0;
      }
    }
  }
  if (width != 0) {
    value <<= 6 - width;
    result.push_back(static_cast<char>(value + 63));
  }
  return result;
}

bool present(const Graph& graph, Edge edge) {
  return (graph.rows[edge.u] >> edge.v) & uint64_t{1};
}

void toggle(Graph& graph, Edge edge) {
  graph.rows[edge.u] ^= uint64_t{1} << edge.v;
  graph.rows[edge.v] ^= uint64_t{1} << edge.u;
}

uint64_t neighborhood(const Graph& graph, int vertex, bool complement) {
  if (!complement) return graph.rows[vertex];
  return kAllVertices &
         ~(graph.rows[vertex] | (uint64_t{1} << vertex));
}

int triangle_count(const Graph& graph, uint64_t vertices, bool complement) {
  int result = 0;
  uint64_t remaining_u = vertices;
  while (remaining_u) {
    const int u = __builtin_ctzll(remaining_u);
    remaining_u &= remaining_u - 1;
    const uint64_t neighbors_u =
        remaining_u & neighborhood(graph, u, complement);
    uint64_t remaining_v = neighbors_u;
    while (remaining_v) {
      const int v = __builtin_ctzll(remaining_v);
      remaining_v &= remaining_v - 1;
      const uint64_t after_v =
          remaining_u & ~((uint64_t{1} << (v + 1)) - 1);
      result += __builtin_popcountll(
          neighbors_u & neighborhood(graph, v, complement) & after_v);
    }
  }
  return result;
}

// Exact change in the number of monochromatic five-sets after one toggle.
int flip_delta(const Graph& graph, Edge edge) {
  const uint64_t allowed =
      kAllVertices &
      ~((uint64_t{1} << edge.u) | (uint64_t{1} << edge.v));
  const uint64_t common_adjacent =
      graph.rows[edge.u] & graph.rows[edge.v] & allowed;
  const uint64_t common_nonadjacent =
      neighborhood(graph, edge.u, true) &
      neighborhood(graph, edge.v, true) & allowed;
  const int clique_fives =
      triangle_count(graph, common_adjacent, false);
  const int independent_fives =
      triangle_count(graph, common_nonadjacent, true);
  return present(graph, edge) ? independent_fives - clique_fives
                              : clique_fives - independent_fives;
}

void enumerate_fives(
    const Graph& graph, uint64_t candidates, bool complement, int depth,
    std::array<int, 5>& selected, std::vector<Conflict>& output) {
  const int needed = 5 - depth;
  if (__builtin_popcountll(candidates) < needed) return;
  if (depth == 5) {
    output.push_back({!complement, selected});
    return;
  }
  while (candidates) {
    if (__builtin_popcountll(candidates) < needed) return;
    const int vertex = __builtin_ctzll(candidates);
    candidates &= candidates - 1;
    selected[depth] = vertex;
    enumerate_fives(
        graph, candidates & neighborhood(graph, vertex, complement),
        complement, depth + 1, selected, output);
  }
}

std::vector<Conflict> all_conflicts(const Graph& graph) {
  std::vector<Conflict> output;
  std::array<int, 5> selected{};
  enumerate_fives(graph, kAllVertices, false, 0, selected, output);
  enumerate_fives(graph, kAllVertices, true, 0, selected, output);
  return output;
}

std::vector<Edge> edges_of(const Conflict& conflict) {
  std::vector<Edge> result;
  result.reserve(10);
  for (int left = 0; left < 5; ++left)
    for (int right = left + 1; right < 5; ++right) {
      int u = conflict.vertices[left];
      int v = conflict.vertices[right];
      if (u > v) std::swap(u, v);
      result.push_back({u, v});
    }
  return result;
}

std::set<Edge> conflict_union(const std::vector<Conflict>& conflicts) {
  std::set<Edge> result;
  for (const Conflict& conflict : conflicts)
    for (Edge edge : edges_of(conflict)) result.insert(edge);
  return result;
}

std::array<int, 4> shared_core(const std::vector<Conflict>& conflicts) {
  if (conflicts.size() != 2 || conflicts[0].clique != conflicts[1].clique)
    throw std::runtime_error("E=2 seed is not a same-colour pair");
  std::array<int, 4> result{};
  int cursor = 0;
  for (int vertex : conflicts[0].vertices) {
    if (std::find(
            conflicts[1].vertices.begin(), conflicts[1].vertices.end(),
            vertex) != conflicts[1].vertices.end()) {
      if (cursor >= 4) throw std::runtime_error("shared core exceeds four");
      result[cursor++] = vertex;
    }
  }
  if (cursor != 4) throw std::runtime_error("shared core is not four");
  std::sort(result.begin(), result.end());
  return result;
}

std::vector<Edge> core_edges(const std::array<int, 4>& core) {
  std::vector<Edge> result;
  for (int left = 0; left < 4; ++left)
    for (int right = left + 1; right < 4; ++right)
      result.push_back({core[left], core[right]});
  return result;
}

std::vector<std::filesystem::path> known_seed_paths(
    const std::filesystem::path& directory) {
  std::vector<std::filesystem::path> result;
  for (const auto& entry : std::filesystem::directory_iterator(directory)) {
    if (!entry.is_regular_file()) continue;
    const std::string name = entry.path().filename().string();
    if (name.rfind("line_", 0) == 0 && entry.path().extension() == ".g6")
      result.push_back(entry.path());
  }
  std::sort(result.begin(), result.end());
  if (result.size() != 22)
    throw std::runtime_error("expected exactly 22 known E=2 seed files");
  return result;
}

std::map<int, long long> reconstruct_neutral_cycles(
    const std::filesystem::path& directory,
    std::unordered_set<std::string>& global_states) {
  std::map<int, long long> length_histogram;
  for (const auto& path : known_seed_paths(directory)) {
    const auto lines = graph6_lines(path);
    if (lines.size() != 1)
      throw std::runtime_error("known E=2 seed file is not a singleton");
    Graph current = decode_graph6(lines.front());
    if (encode_graph6(current) != lines.front())
      throw std::runtime_error("known seed graph6 round trip failed");
    const std::string initial = lines.front();
    std::unordered_set<std::string> local;
    Edge previous;
    bool first = true;
    while (true) {
      const std::string code = encode_graph6(current);
      if (local.contains(code)) {
        if (code != initial)
          throw std::runtime_error("neutral walk entered a noninitial cycle");
        break;
      }
      if (local.size() >= 10000)
        throw std::runtime_error("neutral cycle exceeded safety limit");
      local.insert(code);
      if (!global_states.insert(code).second)
        throw std::runtime_error("known seed cycles overlap as labeled states");
      const auto conflicts = all_conflicts(current);
      const auto core = shared_core(conflicts);
      std::vector<Edge> neutral;
      for (Edge edge : core_edges(core))
        if (2 + flip_delta(current, edge) == 2) neutral.push_back(edge);
      std::sort(neutral.begin(), neutral.end());
      if (neutral.size() != 2)
        throw std::runtime_error("neutral state does not have degree two");
      Edge next;
      if (first) {
        next = neutral.front();
        first = false;
      } else if (neutral[0] == previous) {
        next = neutral[1];
      } else if (neutral[1] == previous) {
        next = neutral[0];
      } else {
        throw std::runtime_error("neutral walk lost its reverse edge");
      }
      toggle(current, next);
      previous = next;
    }
    ++length_histogram[static_cast<int>(local.size())];
  }
  return length_histogram;
}

uint64_t fnv_update(uint64_t digest, uint64_t value) {
  for (int byte = 0; byte < 8; ++byte) {
    digest ^= (value >> (8 * byte)) & 0xff;
    digest *= uint64_t{1099511628211};
  }
  return digest;
}

std::string map_json(const std::map<int, long long>& values) {
  std::string result = "{";
  bool first = true;
  for (const auto& [key, value] : values) {
    if (!first) result += ',';
    first = false;
    result += '"' + std::to_string(key) + "\":" + std::to_string(value);
  }
  result += '}';
  return result;
}

Arguments parse_arguments(int argc, char** argv) {
  Arguments arguments;
  for (int index = 1; index < argc; ++index) {
    const std::string option = argv[index];
    auto value = [&]() -> std::string {
      if (index + 1 == argc)
        throw std::runtime_error("missing value for " + option);
      return argv[++index];
    };
    if (option == "--e3")
      arguments.e3 = value();
    else if (option == "--e4")
      arguments.e4 = value();
    else if (option == "--known-directory")
      arguments.known_directory = value();
    else if (option == "--ceiling")
      arguments.ceiling = std::stoi(value());
    else
      throw std::runtime_error("unknown option: " + option);
  }
  if (arguments.e3.empty() || arguments.e4.empty() ||
      arguments.known_directory.empty())
    throw std::runtime_error(
        "--e3, --e4, and --known-directory are required");
  if (arguments.ceiling < 4)
    throw std::runtime_error("objective ceiling is invalid");
  return arguments;
}

}  // namespace

int main(int argc, char** argv) {
  try {
    const Arguments arguments = parse_arguments(argc, argv);
    const std::vector<Edge> edges = all_edges();
    std::vector<std::pair<int, std::string>> seed_records;
    for (const std::string& line : graph6_lines(arguments.e3))
      seed_records.push_back({3, line});
    for (const std::string& line : graph6_lines(arguments.e4))
      seed_records.push_back({4, line});
    if (seed_records.size() != 53)
      throw std::runtime_error("expected exactly 53 low-frontier seeds");
    std::set<std::string> unique_seeds;

    std::unordered_set<std::string> known_states;
    const auto neutral_cycle_lengths =
        reconstruct_neutral_cycles(arguments.known_directory, known_states);

    long long first_count = 0;
    long long first_recounts = 0;
    long long first_nonconflict = 0;
    long long first_high_conflict = 0;
    long long second_candidate_count = 0;
    long long second_count = 0;
    long long second_recounts = 0;
    long long first_without_second = 0;
    std::map<int, long long> seed_distribution;
    std::map<int, long long> first_by_source;
    std::map<int, long long> first_by_height;
    std::map<int, long long> second_by_height;
    std::map<int, long long> second_delta;
    uint64_t schedule_digest = uint64_t{1469598103934665603};

    for (size_t seed_index = 0; seed_index < seed_records.size();
         ++seed_index) {
      const auto& [expected_objective, line] = seed_records[seed_index];
      if (!unique_seeds.insert(line).second)
        throw std::runtime_error("low-frontier seed is repeated");
      const Graph seed = decode_graph6(line);
      if (encode_graph6(seed) != line)
        throw std::runtime_error("low-frontier graph6 round trip failed");
      const auto seed_conflicts = all_conflicts(seed);
      if (static_cast<int>(seed_conflicts.size()) != expected_objective)
        throw std::runtime_error("low-frontier seed objective mismatch");
      ++seed_distribution[expected_objective];
      const auto seed_union = conflict_union(seed_conflicts);

      std::vector<First> first_schedule;
      for (Edge edge : edges) {
        const bool nonconflict = !seed_union.contains(edge);
        const int height = expected_objective + flip_delta(seed, edge);
        if (nonconflict && height < expected_objective)
          throw std::runtime_error("first nonconflict edge improves objective");
        if (!(nonconflict || height > 4)) continue;
        if (height > arguments.ceiling) continue;
        first_schedule.push_back({edge, height, nonconflict});
      }
      std::sort(
          first_schedule.begin(), first_schedule.end(),
          [](const First& left, const First& right) {
            return std::tuple{
                       left.height, !left.nonconflict,
                       left.edge.u, left.edge.v
                   } <
                   std::tuple{
                       right.height, !right.nonconflict,
                       right.edge.u, right.edge.v
                   };
          });

      for (const First& first : first_schedule) {
        Graph once = seed;
        toggle(once, first.edge);
        const auto once_conflicts = all_conflicts(once);
        ++first_recounts;
        if (static_cast<int>(once_conflicts.size()) != first.height)
          throw std::runtime_error("selected first graph recount mismatch");
        ++first_count;
        ++first_by_source[expected_objective];
        ++first_by_height[first.height];
        if (first.nonconflict)
          ++first_nonconflict;
        else
          ++first_high_conflict;

        const auto once_union = conflict_union(once_conflicts);
        long long local_candidates = 0;
        bool found = false;
        std::tuple<int, int, int> selected_key;
        Edge selected;
        int selected_height = -1;
        for (Edge edge : edges) {
          if (edge == first.edge || once_union.contains(edge)) continue;
          const int height = first.height + flip_delta(once, edge);
          if (height < first.height)
            throw std::runtime_error(
                "second nonconflict edge improves objective");
          if (height > arguments.ceiling) continue;
          ++local_candidates;
          const auto key = std::tuple{height, edge.u, edge.v};
          if (!found || key < selected_key) {
            found = true;
            selected_key = key;
            selected = edge;
            selected_height = height;
          }
        }
        second_candidate_count += local_candidates;
        if (!found) {
          ++first_without_second;
          continue;
        }

        Graph twice = once;
        toggle(twice, selected);
        const auto twice_conflicts = all_conflicts(twice);
        ++second_recounts;
        if (static_cast<int>(twice_conflicts.size()) != selected_height)
          throw std::runtime_error("selected second graph recount mismatch");
        ++second_count;
        ++second_by_height[selected_height];
        ++second_delta[selected_height - first.height];

        for (uint64_t value : {
                 static_cast<uint64_t>(seed_index),
                 static_cast<uint64_t>(expected_objective),
                 static_cast<uint64_t>(first.edge.u),
                 static_cast<uint64_t>(first.edge.v),
                 static_cast<uint64_t>(first.height),
                 static_cast<uint64_t>(selected.u),
                 static_cast<uint64_t>(selected.v),
                 static_cast<uint64_t>(selected_height),
                 static_cast<uint64_t>(local_candidates),
             })
          schedule_digest = fnv_update(schedule_digest, value);
      }
    }

    std::cout
        << "{\"schema\":\"ramsey55.e2_double_forced_schedule_exact.v1\","
        << "\"valid\":true,"
        << "\"low_seed_count\":" << seed_records.size() << ','
        << "\"low_seed_objective_distribution\":"
        << map_json(seed_distribution) << ','
        << "\"known_E2_seed_count\":22,"
        << "\"known_E2_state_count\":" << known_states.size() << ','
        << "\"neutral_cycle_length_histogram\":"
        << map_json(neutral_cycle_lengths) << ','
        << "\"first_barrier_count\":" << first_count << ','
        << "\"first_barrier_exact_replays\":" << first_recounts << ','
        << "\"first_nonconflict_barrier_count\":" << first_nonconflict << ','
        << "\"first_high_conflict_barrier_count\":"
        << first_high_conflict << ','
        << "\"first_by_source_objective\":"
        << map_json(first_by_source) << ','
        << "\"first_by_height\":" << map_json(first_by_height) << ','
        << "\"second_candidate_count\":" << second_candidate_count << ','
        << "\"second_barrier_count\":" << second_count << ','
        << "\"second_barrier_exact_replays\":" << second_recounts << ','
        << "\"first_without_second_candidate_count\":"
        << first_without_second << ','
        << "\"second_by_height\":" << map_json(second_by_height) << ','
        << "\"second_delta_distribution\":" << map_json(second_delta) << ','
        << "\"objective_ceiling\":" << arguments.ceiling << ','
        << "\"selected_schedule_fnv1a64\":\"" << std::hex
        << schedule_digest << std::dec << "\"}\n";
    return 0;
  } catch (const std::exception& error) {
    std::cerr << "independent schedule audit failed: " << error.what() << '\n';
    return 2;
  }
}
