/- Generated type-inspection commands; not a proof. -/
import Kourovka
set_option pp.all true

#check @Kourovka.Ambient.I
#check @Kourovka.Ambient.V
#check @Kourovka.Ambient.B
#check @Kourovka.Ambient.B_apply
#check @Kourovka.Ambient.alternating
#check @Kourovka.Ambient.skew
#check @Kourovka.Ambient.mapVec
#check @Kourovka.Ambient.mapVec_unit
#check @Kourovka.Ambient.mapVec_add
#check @Kourovka.Ambient.mapVec_sub
#check @Kourovka.Ambient.mapVec_zero
#check @Kourovka.Ambient.mapVec_smul
#check @Kourovka.Ambient.mapVec_terms
#check @Kourovka.Ambient.mapVec_B
#check @Kourovka.Ambient.IntData.Checks.term_0
#check @Kourovka.Ambient.IntData.Checks.jacobi_0
#check @Kourovka.Ambient.IntData.Checks.term_1
#check @Kourovka.Ambient.IntData.Checks.jacobi_1
#check @Kourovka.Ambient.IntData.Checks.term_2
#check @Kourovka.Ambient.IntData.Checks.jacobi_2
#check @Kourovka.Ambient.IntData.Checks.term_3
#check @Kourovka.Ambient.IntData.Checks.jacobi_3
#check @Kourovka.Ambient.IntData.Checks.term_4
#check @Kourovka.Ambient.IntData.Checks.jacobi_4
#check @Kourovka.Ambient.IntData.Checks.term_5
#check @Kourovka.Ambient.IntData.Checks.jacobi_5
#check @Kourovka.Ambient.IntData.Checks.term_6
#check @Kourovka.Ambient.IntData.Checks.jacobi_6
#check @Kourovka.Ambient.IntData.Checks.term_7
#check @Kourovka.Ambient.IntData.Checks.jacobi_7
#check @Kourovka.Ambient.IntData.Checks.term_8
#check @Kourovka.Ambient.IntData.Checks.jacobi_8
#check @Kourovka.Ambient.IntData.Checks.term_9
#check @Kourovka.Ambient.IntData.Checks.jacobi_9
#check @Kourovka.Ambient.IntData.Checks.term_10
#check @Kourovka.Ambient.IntData.Checks.jacobi_10
#check @Kourovka.Ambient.IntData.Checks.term_11
#check @Kourovka.Ambient.IntData.Checks.jacobi_11
#check @Kourovka.Ambient.IntData.Checks.term_12
#check @Kourovka.Ambient.IntData.Checks.jacobi_12
#check @Kourovka.Ambient.IntData.Checks.term_13
#check @Kourovka.Ambient.IntData.Checks.jacobi_13
#check @Kourovka.Ambient.IntData.Checks.term_14
#check @Kourovka.Ambient.IntData.Checks.jacobi_14
#check @Kourovka.Ambient.IntData.Checks.term_15
#check @Kourovka.Ambient.IntData.Checks.jacobi_15
#check @Kourovka.Ambient.IntData.Checks.term_16
#check @Kourovka.Ambient.IntData.Checks.jacobi_16
#check @Kourovka.Ambient.IntData.Checks.term_17
#check @Kourovka.Ambient.IntData.Checks.jacobi_17
#check @Kourovka.Ambient.IntData.Checks.term_18
#check @Kourovka.Ambient.IntData.Checks.jacobi_18
#check @Kourovka.Ambient.IntData.Checks.term_19
#check @Kourovka.Ambient.IntData.Checks.jacobi_19
#check @Kourovka.Ambient.IntData.Checks.term_20
#check @Kourovka.Ambient.IntData.Checks.jacobi_20
#check @Kourovka.Ambient.IntData.Checks.term_21
#check @Kourovka.Ambient.IntData.Checks.jacobi_21
#check @Kourovka.Ambient.IntData.Checks.term_22
#check @Kourovka.Ambient.IntData.Checks.jacobi_22
#check @Kourovka.Ambient.IntData.Checks.term_23
#check @Kourovka.Ambient.IntData.Checks.jacobi_23
#check @Kourovka.Ambient.IntData.Checks.term_24
#check @Kourovka.Ambient.IntData.Checks.jacobi_24
#check @Kourovka.Ambient.IntData.Checks.term_25
#check @Kourovka.Ambient.IntData.Checks.jacobi_25
#check @Kourovka.Ambient.IntData.Checks.term_26
#check @Kourovka.Ambient.IntData.Checks.jacobi_26
#check @Kourovka.Ambient.IntData.Checks.term_27
#check @Kourovka.Ambient.IntData.Checks.jacobi_27
#check @Kourovka.Ambient.IntData.Checks.term_28
#check @Kourovka.Ambient.IntData.Checks.jacobi_28
#check @Kourovka.Ambient.IntData.Checks.term_29
#check @Kourovka.Ambient.IntData.Checks.jacobi_29
#check @Kourovka.Ambient.IntData.Checks.term_30
#check @Kourovka.Ambient.IntData.Checks.jacobi_30
#check @Kourovka.Ambient.FastBasis.entry
#check @Kourovka.Ambient.FastBasis.coeff
#check @Kourovka.Ambient.FastBasis.coord_unit
#check @Kourovka.Ambient.FastBasis.entry_sound
#check @Kourovka.Ambient.FastBasis.fromTerms_sound
#check @Kourovka.Ambient.FastBasis.bracket_sound
#check @Kourovka.Ambient.FastBasis.cast_fromTerms_sound
#check @Kourovka.Ambient.FastBasis.termVec_coeff
#check @Kourovka.Ambient.FastBasis.termCheck_of_coeff
#check @Kourovka.Ambient.IntData.term
#check @Kourovka.Ambient.IntData.termVec
#check @Kourovka.Ambient.IntData.coeff
#check @Kourovka.Ambient.IntData.nestedLeft
#check @Kourovka.Ambient.IntData.nestedRight
#check @Kourovka.Ambient.IntData.JacobiCheck
#check @Kourovka.Ambient.IntData.TermCheck
#check @Kourovka.Ambient.termCheck_all
#check @Kourovka.Ambient.jacobiCheck_all
#check @Kourovka.Ambient.mapVec_termVec
#check @Kourovka.Ambient.basis_bracket
#check @Kourovka.Ambient.termVec_coord
#check @Kourovka.Ambient.basis_coeff
#check @Kourovka.Ambient.nestedLeft_sound
#check @Kourovka.Ambient.nestedRight_sound
#check @Kourovka.Ambient.jacobi_basis_integer
#check @Kourovka.Ambient.jacobi_basis
#check @Kourovka.Ambient.leibniz
#check @Kourovka.Ambient.lieRing
#check @Kourovka.Ambient.lieAlgebra
#check @Kourovka.Analytic.geometric
#check @Kourovka.Analytic.one_sub_mul_geometric
#check @Kourovka.Analytic.geometric_mul_one_sub
#check @Kourovka.Analytic.oneSubUnit
#check @Kourovka.Analytic.oneAddUnit
#check @Kourovka.Analytic.oneAddUnit_val
#check @Kourovka.Analytic.evalHorner
#check @Kourovka.Analytic.commute_evalHorner
#check @Kourovka.Analytic.polynomialUnit
#check @Kourovka.Analytic.polynomialUnit_val
#check @Kourovka.Analytic.unitToEquiv
#check @Kourovka.Analytic.factor_zero_iff
#check @Kourovka.Analytic.factor_mem_iff
#check @Kourovka.Analytic.Tensor.T
#check @Kourovka.Analytic.Tensor.output
#check @Kourovka.Analytic.Tensor.inputLeft
#check @Kourovka.Analytic.Tensor.inputRight
#check @Kourovka.Analytic.Tensor.output_apply
#check @Kourovka.Analytic.Tensor.inputLeft_apply
#check @Kourovka.Analytic.Tensor.inputRight_apply
#check @Kourovka.Analytic.Tensor.output_inputLeft_commute
#check @Kourovka.Analytic.Tensor.output_inputRight_commute
#check @Kourovka.Analytic.Tensor.inputs_commute
#check @Kourovka.Analytic.Tensor.differential
#check @Kourovka.Analytic.Tensor.differential_apply
#check @Kourovka.Analytic.Tensor.action
#check @Kourovka.Analytic.Tensor.action_apply
#check @Kourovka.Analytic.Tensor.action_fixed_iff
#check @Kourovka.Analytic.Tensor.fixed_iff_derivation_of_factor
#check @Kourovka.BCH.Poly.coeff
#check @Kourovka.BCH.Poly.support
#check @Kourovka.BCH.Poly.coeff_nil
#check @Kourovka.BCH.Poly.coeff_cons
#check @Kourovka.BCH.Poly.coeff_append
#check @Kourovka.BCH.Poly.coeff_neg
#check @Kourovka.BCH.Poly.mem_support
#check @Kourovka.BCH.Poly.coeff_eq_zero_of_not_mem
#check @Kourovka.BCH.Poly.sumEval_eq_sum
#check @Kourovka.BCH.Poly.sumEval_eq_of_coeff_eq
#check @Kourovka.BCH.Poly.ZeroCoefficients
#check @Kourovka.BCH.Poly.zeroCoefficients_sound
#check @Kourovka.BCH.LiePoly
#check @Kourovka.BCH.LiePoly.eval
#check @Kourovka.BCH.LiePoly.expand
#check @Kourovka.BCH.LiePoly.Homogeneous
#check @Kourovka.BCH.LiePoly.dynkin_expand
#check @Kourovka.BCH.LiePoly.eval_zero_of_coeff_zero
#check @Kourovka.BCH.LieWord
#check @Kourovka.BCH.LieWord.degree
#check @Kourovka.BCH.LieWord.eval
#check @Kourovka.BCH.LieWord.degree_pos
#check @Kourovka.BCH.Poly
#check @Kourovka.BCH.Poly.neg
#check @Kourovka.BCH.Poly.shift
#check @Kourovka.BCH.Poly.mul
#check @Kourovka.BCH.Poly.comm
#check @Kourovka.BCH.Poly.sumEval
#check @Kourovka.BCH.Poly.sumEval_append
#check @Kourovka.BCH.Poly.sumEval_neg
#check @Kourovka.BCH.Poly.NonemptyWords
#check @Kourovka.BCH.Poly.nonempty_neg
#check @Kourovka.BCH.Poly.nonempty_mul
#check @Kourovka.BCH.Poly.nonempty_comm
#check @Kourovka.BCH.LieWord.expand
#check @Kourovka.BCH.LieWord.expansion_nonempty
#check @Kourovka.BCH.wordAction
#check @Kourovka.BCH.wordAction_zero
#check @Kourovka.BCH.wordAction_add
#check @Kourovka.BCH.wordAction_zsmul
#check @Kourovka.BCH.wordAction_append
#check @Kourovka.BCH.dynkinWord
#check @Kourovka.BCH.dynkinWord_append
#check @Kourovka.BCH.polyAction
#check @Kourovka.BCH.dynkin
#check @Kourovka.BCH.polyAction_zero
#check @Kourovka.BCH.polyAction_add
#check @Kourovka.BCH.polyAction_zsmul
#check @Kourovka.BCH.action_shift
#check @Kourovka.BCH.action_mul
#check @Kourovka.BCH.dynkin_shift
#check @Kourovka.BCH.dynkin_mul
#check @Kourovka.BCH.action_expand
#check @Kourovka.BCH.dynkin_expand
#check @Kourovka.BCH.eval_eq_of_dynkin_eq
#check @Kourovka.Sparse.Term
#check @Kourovka.Sparse.Vec
#check @Kourovka.Sparse.coord
#check @Kourovka.Sparse.coord_add
#check @Kourovka.Sparse.coord_smul
#check @Kourovka.Sparse.entry
#check @Kourovka.Sparse.entry_self
#check @Kourovka.Sparse.entry_add_left
#check @Kourovka.Sparse.entry_add_right
#check @Kourovka.Sparse.entry_smul_left
#check @Kourovka.Sparse.entry_smul_right
#check @Kourovka.Sparse.fromTerms
#check @Kourovka.Sparse.fromTerms_self
#check @Kourovka.Sparse.fromTerms_add_left
#check @Kourovka.Sparse.fromTerms_add_right
#check @Kourovka.Sparse.fromTerms_smul_left
#check @Kourovka.Sparse.fromTerms_smul_right
#check @Kourovka.Sparse.bracket
#check @Kourovka.Certificates.Pair
#check @Kourovka.Certificates.Row
#check @Kourovka.Certificates.Col
#check @Kourovka.Certificates.num_pairs
#check @Kourovka.Certificates.num_rows
#check @Kourovka.Certificates.num_cols
#check @Kourovka.Certificates.derivationMatrix
#check @Kourovka.Certificates.coefficient
#check @Kourovka.Certificates.matrix_entry
#check @Kourovka.Certificates.matrixLinear
#check @Kourovka.Certificates.matrix_apply
#check @Kourovka.Certificates.bracket_skew
#check @Kourovka.Certificates.delta_alternating
#check @Kourovka.Certificates.delta_skew
#check @Kourovka.Certificates.zero_of_ordered_basis
#check @Kourovka.Certificates.DerivationCondition
#check @Kourovka.Certificates.derivation_iff_delta_zero
#check @Kourovka.Certificates.kernel_iff_derivation
#check @Kourovka.Certificates.derivationsEquivKernel
#check @Kourovka.Certificates.K
#check @Kourovka.Certificates.Kmod
#check @Kourovka.Certificates.diagonalMap
#check @Kourovka.Certificates.diagonalKernelEquiv
#check @Kourovka.Certificates.diagonalKernel_card
#check @Kourovka.Certificates.padMap
#check @Kourovka.Certificates.paddedKernelEquiv
#check @Kourovka.Certificates.diagonalCoefficient
#check @Kourovka.Certificates.diagonal_prime_power_card
#check @Kourovka.Certificates.Elementary.Coord
#check @Kourovka.Certificates.Elementary.permute
#check @Kourovka.Certificates.Elementary.shearFun
#check @Kourovka.Certificates.Elementary.shear
#check @Kourovka.Certificates.Elementary.scale
#check @Kourovka.Certificates.Elementary.Op
#check @Kourovka.Certificates.Elementary.decode
#check @Kourovka.Certificates.Elementary.decodeList
#check @Kourovka.Certificates.Elementary.Circuit
#check @Kourovka.Certificates.Elementary.decodeCircuit
#check @Kourovka.Certificates.Elementary.basisCheck
#check @Kourovka.Certificates.Elementary.basisCheck_sound
#check @Kourovka.Certificates.Elementary.check
#check @Kourovka.Certificates.Elementary.check_sound
#check @Kourovka.Certificates.Elementary.check_card
#check @Kourovka.Certificates.Elementary.rejects_nonunit
#check @Kourovka.Certificates.Elementary.rejects_same_coordinate
#check @Kourovka.Certificates.Elementary.accepts_unit
#check @Kourovka.Certificates.pairData
#check @Kourovka.Certificates.pairData_ordered
#check @Kourovka.Certificates.pairAt
#check @Kourovka.Certificates.pairNumberNat
#check @Kourovka.Certificates.pairNumber_bound
#check @Kourovka.Certificates.pairNumber
#check @Kourovka.Certificates.number_at
#check @Kourovka.Certificates.at_number
#check @Kourovka.Certificates.pairEquiv
#check @Kourovka.Certificates.colEquiv
#check @Kourovka.Certificates.rowEquiv
#check @Kourovka.Certificates.Kflat
#check @Kourovka.Certificates.Kflat_def
#check @Kourovka.Certificates.InnerRank.leftInverse_00
#check @Kourovka.Certificates.InnerRank.leftInverse_01
#check @Kourovka.Certificates.InnerRank.leftInverse_02
#check @Kourovka.Certificates.InnerRank.leftInverse_03
#check @Kourovka.Certificates.InnerRank.leftInverse_04
#check @Kourovka.Certificates.InnerRank.leftInverse_05
#check @Kourovka.Certificates.InnerRank.leftInverse_06
#check @Kourovka.Certificates.InnerRank.leftInverse_07
#check @Kourovka.Certificates.InnerRank.leftInverse_08
#check @Kourovka.Certificates.InnerRank.leftInverse_09
#check @Kourovka.Certificates.InnerRank.leftInverse_10
#check @Kourovka.Certificates.InnerRank.leftInverse_11
#check @Kourovka.Certificates.InnerRank.leftInverse_12
#check @Kourovka.Certificates.InnerRank.leftInverse_13
#check @Kourovka.Certificates.InnerRank.leftInverse_14
#check @Kourovka.Certificates.InnerRank.leftInverse_15
#check @Kourovka.Certificates.InnerRank.leftInverse_16
#check @Kourovka.Certificates.InnerRank.leftInverse_17
#check @Kourovka.Certificates.InnerRank.leftInverse_18
#check @Kourovka.Certificates.InnerRank.leftInverse_19
#check @Kourovka.Certificates.InnerRank.leftInverse_20
#check @Kourovka.Certificates.InnerRank.leftInverse_21
#check @Kourovka.Certificates.InnerRank.leftInverse_22
#check @Kourovka.Certificates.InnerRank.leftInverse_23
#check @Kourovka.Certificates.InnerRank.leftInverse_24
#check @Kourovka.Certificates.InnerRank.leftInverse_25
#check @Kourovka.Certificates.InnerRank.leftInverse_26
#check @Kourovka.Certificates.InnerRank.leftInverse_27
#check @Kourovka.Certificates.InnerRank.leftInverse_28
#check @Kourovka.Certificates.InnerRank.leftInverse_29
#check @Kourovka.Certificates.InnerRank.innerColumn_derivation
#check @Kourovka.Certificates.InnerRank.innerMap_derivation
#check @Kourovka.Certificates.InnerRank.innerKernelMap
#check @Kourovka.Certificates.InnerRank.innerKernelMap_injective
#check @Kourovka.Certificates.InnerRank.kernel_finrank_lower
#check @Kourovka.Certificates.InnerRank.rational_rank_upper
#check @Kourovka.Certificates.InnerRank.extendedInnerKernel
#check @Kourovka.Certificates.InnerRank.extendedInnerKernel_injective
#check @Kourovka.Certificates.InnerRank.characteristic_zero_kernel_finrank_lower
#check @Kourovka.Certificates.InnerRank.characteristic_zero_rank_upper
#check @Kourovka.Certificates.InnerRank.inner_entry_cast
#check @Kourovka.Certificates.InnerRank.extendedInverse
#check @Kourovka.Certificates.InnerRank.extended_left_inverse
#check @Kourovka.Certificates.InnerRank.extendedExtractor
#check @Kourovka.Certificates.InnerRank.extendedExtractor_innerMap
#check @Kourovka.Certificates.InnerRank.extended_inner_injective
#check @Kourovka.Certificates.InnerRank.leftInverse_all
#check @Kourovka.Certificates.InnerRank.extractor_innerMap
#check @Kourovka.Certificates.InnerRank.innerMap_injective
#check @Kourovka.Certificates.InnerRank.Param
#check @Kourovka.Certificates.InnerRank.selectedRow
#check @Kourovka.Certificates.InnerRank.inverseCoeff
#check @Kourovka.Certificates.InnerRank.innerColumn
#check @Kourovka.Certificates.InnerRank.inner_entry_fast
#check @Kourovka.Certificates.InnerRank.innerMap
#check @Kourovka.Certificates.InnerRank.innerMap_unit
#check @Kourovka.Certificates.InnerRank.extractor
#check @Kourovka.Certificates.InnerRank.LeftInverseCheck
#check @Kourovka.Certificates.KernelSet
#check @Kourovka.Certificates.kernelPostEquiv
#check @Kourovka.Certificates.kernelPreEquiv
#check @Kourovka.Certificates.kernelTransformEquiv
#check @Kourovka.Certificates.kernelTransform_card
#check @Kourovka.Certificates.ScalarKernel.Carrier
#check @Kourovka.Certificates.ScalarKernel.equivFin
#check @Kourovka.Certificates.ScalarKernel.card
#check @Kourovka.Certificates.ScalarKernel.prime_power_card
#check @Kourovka.Certificates.ScalarKernel.zeroKernelEquiv
#check @Kourovka.Challenge.ExactOrders
#check @Kourovka.Challenge.NotebookAffirmative
#check @Kourovka.exportedTerms
#check @Kourovka.Finite.VecAt
#check @Kourovka.Finite.additiveToLinear
#check @Kourovka.Finite.additiveToLinear_apply
#check @Kourovka.Finite.additiveLinearEquiv
#check @Kourovka.Finite.additiveEquivToLinear
#check @Kourovka.Finite.additiveEquivToLinear_apply
#check @Kourovka.Finite.BracketTree
#check @Kourovka.Finite.BracketTree.length
#check @Kourovka.Finite.BracketTree.eval
#check @Kourovka.Finite.BracketTree.map
#check @Kourovka.Finite.BracketTree.length_map
#check @Kourovka.Finite.BracketTree.length_pos
#check @Kourovka.Finite.BracketTree.eval_map
#check @Kourovka.Finite.BracketTree.map_map
#check @Kourovka.Finite.BracketTree.map_id
#check @Kourovka.Finite.primePower_neZero
#check @Kourovka.Finite.RAt
#check @Kourovka.Finite.LAt
#check @Kourovka.Finite.reduce
#check @Kourovka.Finite.lift
#check @Kourovka.Finite.reduce_lift
#check @Kourovka.Finite.reduce_surjective
#check @Kourovka.Finite.reduce_bracket
#check @Kourovka.Finite.reduce_eq_zero_iff
#check @Kourovka.Finite.cardinality
#check @Kourovka.Finite.cardinality_at_depth
#check @Kourovka.Finite.lieRingAt
#check @Kourovka.Finite.lieAlgebraAt
#check @Kourovka.Finite.FullAutomorphisms.RingAut
#check @Kourovka.Finite.FullAutomorphisms.ScalarAut
#check @Kourovka.Finite.FullAutomorphisms.toScalar
#check @Kourovka.Finite.FullAutomorphisms.toInteger
#check @Kourovka.Finite.FullAutomorphisms.ringAutEquivScalarAut
#check @Kourovka.Finite.FullAutomorphisms.AdmissibleEntries
#check @Kourovka.Finite.FullAutomorphisms.toEntriesAut
#check @Kourovka.Finite.FullAutomorphisms.fromEntriesAut
#check @Kourovka.Finite.FullAutomorphisms.scalarAutEquivEntries
#check @Kourovka.Finite.FullAutomorphisms.ringAutEquivEntries
#check @Kourovka.Finite.FullAutomorphisms.full_lie_aut_card_eq_matrix_card
#check @Kourovka.Finite.tree_embed_divisible
#check @Kourovka.Finite.integer_tree_divisible
#check @Kourovka.Finite.monomial_vanishes
#check @Kourovka.Finite.standardB
#check @Kourovka.Finite.wordSpan
#check @Kourovka.Finite.bracket_mem_wordSpan
#check @Kourovka.Finite.lowerCentral_le_wordSpan
#check @Kourovka.Finite.lowerCentral_eq_bot_of_words
#check @Kourovka.Finite.target_lowerCentralSeries
#check @Kourovka.Finite.Padic.O
#check @Kourovka.Finite.Padic.Ell
#check @Kourovka.Finite.Padic.reduction
#check @Kourovka.Finite.Padic.sectionMap
#check @Kourovka.Finite.Padic.reduction_section
#check @Kourovka.Finite.Padic.reduction_surjective
#check @Kourovka.Finite.Padic.reduction_scalar_zero
#check @Kourovka.Finite.Padic.reduction_zero_iff
#check @Kourovka.Finite.Padic.quotientEquiv
#check @Kourovka.Finite.Padic.reduction_bracket
#check @Kourovka.Finite.Padic.quotient_coordinate_order
#check @Kourovka.Flag.k
#check @Kourovka.Flag.primeFact
#check @Kourovka.Flag.E
#check @Kourovka.Flag.x
#check @Kourovka.Flag.e
#check @Kourovka.Flag.f
#check @Kourovka.Flag.u
#check @Kourovka.Flag.v
#check @Kourovka.Flag.w
#check @Kourovka.Flag.q
#check @Kourovka.Flag.r
#check @Kourovka.Flag.z
#check @Kourovka.Flag.t
#check @Kourovka.Flag.y
#check @Kourovka.Flag.uv
#check @Kourovka.Flag.ad1
#check @Kourovka.Flag.ad2
#check @Kourovka.Flag.ad3
#check @Kourovka.Flag.Preserves
#check @Kourovka.Flag.IsDerivation
#check @Kourovka.Flag.F2
#check @Kourovka.Flag.F3
#check @Kourovka.Flag.x_mem_F2
#check @Kourovka.Flag.y_mem_F2
#check @Kourovka.Flag.t_mem_F3
#check @Kourovka.Flag.F2_le_F3
#check @Kourovka.Flag.F2_eq_span
#check @Kourovka.Flag.F3_eq_span
#check @Kourovka.Flag.t_ne_zero
#check @Kourovka.Flag.xt
#check @Kourovka.Flag.yt
#check @Kourovka.Flag.ef
#check @Kourovka.Flag.euv
#check @Kourovka.Flag.rt
#check @Kourovka.Flag.first_bracket
#check @Kourovka.Flag.ad1_value
#check @Kourovka.Flag.first_derivation
#check @Kourovka.Flag.e_projector
#check @Kourovka.Flag.f_projector
#check @Kourovka.Flag.uv_projector
#check @Kourovka.Flag.r_projector
#check @Kourovka.Flag.fu0
#check @Kourovka.Flag.fu1
#check @Kourovka.Flag.fu2
#check @Kourovka.Flag.fu3
#check @Kourovka.Flag.fu4
#check @Kourovka.Flag.fu5
#check @Kourovka.Flag.fv0
#check @Kourovka.Flag.fv1
#check @Kourovka.Flag.fv2
#check @Kourovka.Flag.fv3
#check @Kourovka.Flag.u2u6
#check @Kourovka.Flag.u0w5
#check @Kourovka.Flag.u0v4
#check @Kourovka.Flag.cancel_smul
#check @Kourovka.Flag.map_piece
#check @Kourovka.Flag.map_r_piece
#check @Kourovka.Flag.image_from_bracket
#check @Kourovka.Flag.Generation.n0
#check @Kourovka.Flag.Generation.value_0
#check @Kourovka.Flag.Generation.fixed_0
#check @Kourovka.Flag.Generation.zero_0
#check @Kourovka.Flag.Generation.n1
#check @Kourovka.Flag.Generation.value_1
#check @Kourovka.Flag.Generation.fixed_1
#check @Kourovka.Flag.Generation.zero_1
#check @Kourovka.Flag.Generation.n2
#check @Kourovka.Flag.Generation.value_2
#check @Kourovka.Flag.Generation.fixed_2
#check @Kourovka.Flag.Generation.zero_2
#check @Kourovka.Flag.Generation.n3
#check @Kourovka.Flag.Generation.value_3
#check @Kourovka.Flag.Generation.fixed_3
#check @Kourovka.Flag.Generation.zero_3
#check @Kourovka.Flag.Generation.n4
#check @Kourovka.Flag.Generation.value_4
#check @Kourovka.Flag.Generation.fixed_4
#check @Kourovka.Flag.Generation.zero_4
#check @Kourovka.Flag.Generation.n5
#check @Kourovka.Flag.Generation.value_5
#check @Kourovka.Flag.Generation.fixed_5
#check @Kourovka.Flag.Generation.zero_5
#check @Kourovka.Flag.Generation.n6
#check @Kourovka.Flag.Generation.value_6
#check @Kourovka.Flag.Generation.fixed_6
#check @Kourovka.Flag.Generation.zero_6
#check @Kourovka.Flag.Generation.n7
#check @Kourovka.Flag.Generation.value_7
#check @Kourovka.Flag.Generation.fixed_7
#check @Kourovka.Flag.Generation.zero_7
#check @Kourovka.Flag.Generation.n8
#check @Kourovka.Flag.Generation.value_8
#check @Kourovka.Flag.Generation.fixed_8
#check @Kourovka.Flag.Generation.zero_8
#check @Kourovka.Flag.Generation.n9
#check @Kourovka.Flag.Generation.value_9
#check @Kourovka.Flag.Generation.fixed_9
#check @Kourovka.Flag.Generation.zero_9
#check @Kourovka.Flag.Generation.n10
#check @Kourovka.Flag.Generation.value_10
#check @Kourovka.Flag.Generation.fixed_10
#check @Kourovka.Flag.Generation.zero_10
#check @Kourovka.Flag.Generation.n11
#check @Kourovka.Flag.Generation.value_11
#check @Kourovka.Flag.Generation.fixed_11
#check @Kourovka.Flag.Generation.zero_11
#check @Kourovka.Flag.Generation.n12
#check @Kourovka.Flag.Generation.value_12
#check @Kourovka.Flag.Generation.fixed_12
#check @Kourovka.Flag.Generation.zero_12
#check @Kourovka.Flag.Generation.n13
#check @Kourovka.Flag.Generation.value_13
#check @Kourovka.Flag.Generation.fixed_13
#check @Kourovka.Flag.Generation.zero_13
#check @Kourovka.Flag.Generation.n14
#check @Kourovka.Flag.Generation.value_14
#check @Kourovka.Flag.Generation.fixed_14
#check @Kourovka.Flag.Generation.zero_14
#check @Kourovka.Flag.Generation.n15
#check @Kourovka.Flag.Generation.value_15
#check @Kourovka.Flag.Generation.fixed_15
#check @Kourovka.Flag.Generation.zero_15
#check @Kourovka.Flag.Generation.n16
#check @Kourovka.Flag.Generation.value_16
#check @Kourovka.Flag.Generation.fixed_16
#check @Kourovka.Flag.Generation.zero_16
#check @Kourovka.Flag.Generation.n17
#check @Kourovka.Flag.Generation.value_17
#check @Kourovka.Flag.Generation.fixed_17
#check @Kourovka.Flag.Generation.zero_17
#check @Kourovka.Flag.Generation.n18
#check @Kourovka.Flag.Generation.value_18
#check @Kourovka.Flag.Generation.fixed_18
#check @Kourovka.Flag.Generation.zero_18
#check @Kourovka.Flag.Generation.n19
#check @Kourovka.Flag.Generation.value_19
#check @Kourovka.Flag.Generation.fixed_19
#check @Kourovka.Flag.Generation.zero_19
#check @Kourovka.Flag.Generation.n20
#check @Kourovka.Flag.Generation.value_20
#check @Kourovka.Flag.Generation.fixed_20
#check @Kourovka.Flag.Generation.zero_20
#check @Kourovka.Flag.Generation.n21
#check @Kourovka.Flag.Generation.value_21
#check @Kourovka.Flag.Generation.fixed_21
#check @Kourovka.Flag.Generation.zero_21
#check @Kourovka.Flag.Generation.n22
#check @Kourovka.Flag.Generation.value_22
#check @Kourovka.Flag.Generation.fixed_22
#check @Kourovka.Flag.Generation.zero_22
#check @Kourovka.Flag.Generation.n23
#check @Kourovka.Flag.Generation.value_23
#check @Kourovka.Flag.Generation.fixed_23
#check @Kourovka.Flag.Generation.zero_23
#check @Kourovka.Flag.Generation.n24
#check @Kourovka.Flag.Generation.value_24
#check @Kourovka.Flag.Generation.fixed_24
#check @Kourovka.Flag.Generation.zero_24
#check @Kourovka.Flag.Generation.n25
#check @Kourovka.Flag.Generation.value_25
#check @Kourovka.Flag.Generation.fixed_25
#check @Kourovka.Flag.Generation.zero_25
#check @Kourovka.Flag.Generation.n26
#check @Kourovka.Flag.Generation.value_26
#check @Kourovka.Flag.Generation.fixed_26
#check @Kourovka.Flag.Generation.zero_26
#check @Kourovka.Flag.Generation.n27
#check @Kourovka.Flag.Generation.value_27
#check @Kourovka.Flag.Generation.fixed_27
#check @Kourovka.Flag.Generation.zero_27
#check @Kourovka.Flag.Generation.n28
#check @Kourovka.Flag.Generation.value_28
#check @Kourovka.Flag.Generation.fixed_28
#check @Kourovka.Flag.Generation.zero_28
#check @Kourovka.Flag.Generation.n29
#check @Kourovka.Flag.Generation.value_29
#check @Kourovka.Flag.Generation.fixed_29
#check @Kourovka.Flag.Generation.zero_29
#check @Kourovka.Flag.Generation.n30
#check @Kourovka.Flag.Generation.value_30
#check @Kourovka.Flag.Generation.fixed_30
#check @Kourovka.Flag.Generation.zero_30
#check @Kourovka.Flag.Generation.n31
#check @Kourovka.Flag.Generation.value_31
#check @Kourovka.Flag.Generation.fixed_31
#check @Kourovka.Flag.Generation.zero_31
#check @Kourovka.Flag.Generation.n32
#check @Kourovka.Flag.Generation.value_32
#check @Kourovka.Flag.Generation.fixed_32
#check @Kourovka.Flag.Generation.zero_32
#check @Kourovka.Flag.Generation.n33
#check @Kourovka.Flag.Generation.value_33
#check @Kourovka.Flag.Generation.fixed_33
#check @Kourovka.Flag.Generation.zero_33
#check @Kourovka.Flag.Generation.n34
#check @Kourovka.Flag.Generation.value_34
#check @Kourovka.Flag.Generation.fixed_34
#check @Kourovka.Flag.Generation.zero_34
#check @Kourovka.Flag.Generation.n35
#check @Kourovka.Flag.Generation.value_35
#check @Kourovka.Flag.Generation.fixed_35
#check @Kourovka.Flag.Generation.zero_35
#check @Kourovka.Flag.Generation.n36
#check @Kourovka.Flag.Generation.value_36
#check @Kourovka.Flag.Generation.fixed_36
#check @Kourovka.Flag.Generation.zero_36
#check @Kourovka.Flag.Generation.n37
#check @Kourovka.Flag.Generation.value_37
#check @Kourovka.Flag.Generation.fixed_37
#check @Kourovka.Flag.Generation.zero_37
#check @Kourovka.Flag.Generation.n38
#check @Kourovka.Flag.Generation.value_38
#check @Kourovka.Flag.Generation.fixed_38
#check @Kourovka.Flag.Generation.zero_38
#check @Kourovka.Flag.Generation.n39
#check @Kourovka.Flag.Generation.value_39
#check @Kourovka.Flag.Generation.fixed_39
#check @Kourovka.Flag.Generation.zero_39
#check @Kourovka.Flag.Generation.n40
#check @Kourovka.Flag.Generation.value_40
#check @Kourovka.Flag.Generation.fixed_40
#check @Kourovka.Flag.Generation.zero_40
#check @Kourovka.Flag.Generation.n41
#check @Kourovka.Flag.Generation.value_41
#check @Kourovka.Flag.Generation.fixed_41
#check @Kourovka.Flag.Generation.zero_41
#check @Kourovka.Flag.Generation.n42
#check @Kourovka.Flag.Generation.value_42
#check @Kourovka.Flag.Generation.fixed_42
#check @Kourovka.Flag.Generation.zero_42
#check @Kourovka.Flag.Generation.n43
#check @Kourovka.Flag.Generation.value_43
#check @Kourovka.Flag.Generation.fixed_43
#check @Kourovka.Flag.Generation.zero_43
#check @Kourovka.Flag.Generation.n44
#check @Kourovka.Flag.Generation.value_44
#check @Kourovka.Flag.Generation.fixed_44
#check @Kourovka.Flag.Generation.zero_44
#check @Kourovka.Flag.Generation.n45
#check @Kourovka.Flag.Generation.value_45
#check @Kourovka.Flag.Generation.fixed_45
#check @Kourovka.Flag.Generation.zero_45
#check @Kourovka.Flag.Generation.n46
#check @Kourovka.Flag.Generation.value_46
#check @Kourovka.Flag.Generation.fixed_46
#check @Kourovka.Flag.Generation.zero_46
#check @Kourovka.Flag.Generation.n47
#check @Kourovka.Flag.Generation.value_47
#check @Kourovka.Flag.Generation.fixed_47
#check @Kourovka.Flag.Generation.zero_47
#check @Kourovka.Flag.Generation.n48
#check @Kourovka.Flag.Generation.value_48
#check @Kourovka.Flag.Generation.fixed_48
#check @Kourovka.Flag.Generation.zero_48
#check @Kourovka.Flag.Generation.n49
#check @Kourovka.Flag.Generation.value_49
#check @Kourovka.Flag.Generation.fixed_49
#check @Kourovka.Flag.Generation.zero_49
#check @Kourovka.Flag.Generation.n50
#check @Kourovka.Flag.Generation.value_50
#check @Kourovka.Flag.Generation.fixed_50
#check @Kourovka.Flag.Generation.zero_50
#check @Kourovka.Flag.Generation.n51
#check @Kourovka.Flag.Generation.value_51
#check @Kourovka.Flag.Generation.fixed_51
#check @Kourovka.Flag.Generation.zero_51
#check @Kourovka.Flag.Generation.n52
#check @Kourovka.Flag.Generation.value_52
#check @Kourovka.Flag.Generation.fixed_52
#check @Kourovka.Flag.Generation.zero_52
#check @Kourovka.Flag.Generation.n53
#check @Kourovka.Flag.Generation.value_53
#check @Kourovka.Flag.Generation.fixed_53
#check @Kourovka.Flag.Generation.zero_53
#check @Kourovka.Flag.Generation.n54
#check @Kourovka.Flag.Generation.value_54
#check @Kourovka.Flag.Generation.fixed_54
#check @Kourovka.Flag.Generation.zero_54
#check @Kourovka.Flag.Generation.n55
#check @Kourovka.Flag.Generation.value_55
#check @Kourovka.Flag.Generation.fixed_55
#check @Kourovka.Flag.Generation.zero_55
#check @Kourovka.Flag.Generation.n56
#check @Kourovka.Flag.Generation.value_56
#check @Kourovka.Flag.Generation.fixed_56
#check @Kourovka.Flag.Generation.zero_56
#check @Kourovka.Flag.Generation.n57
#check @Kourovka.Flag.Generation.value_57
#check @Kourovka.Flag.Generation.fixed_57
#check @Kourovka.Flag.Generation.zero_57
#check @Kourovka.Flag.Generation.n58
#check @Kourovka.Flag.Generation.value_58
#check @Kourovka.Flag.Generation.fixed_58
#check @Kourovka.Flag.Generation.zero_58
#check @Kourovka.Flag.Generation.n59
#check @Kourovka.Flag.Generation.value_59
#check @Kourovka.Flag.Generation.fixed_59
#check @Kourovka.Flag.Generation.zero_59
#check @Kourovka.Flag.Generation.n60
#check @Kourovka.Flag.Generation.value_60
#check @Kourovka.Flag.Generation.fixed_60
#check @Kourovka.Flag.Generation.zero_60
#check @Kourovka.Flag.Generation.n61
#check @Kourovka.Flag.Generation.value_61
#check @Kourovka.Flag.Generation.fixed_61
#check @Kourovka.Flag.Generation.zero_61
#check @Kourovka.Flag.Generation.n62
#check @Kourovka.Flag.Generation.value_62
#check @Kourovka.Flag.Generation.fixed_62
#check @Kourovka.Flag.Generation.zero_62
#check @Kourovka.Flag.Generation.n63
#check @Kourovka.Flag.Generation.value_63
#check @Kourovka.Flag.Generation.fixed_63
#check @Kourovka.Flag.Generation.zero_63
#check @Kourovka.Flag.Generation.n64
#check @Kourovka.Flag.Generation.value_64
#check @Kourovka.Flag.Generation.fixed_64
#check @Kourovka.Flag.Generation.zero_64
#check @Kourovka.Flag.Generation.n65
#check @Kourovka.Flag.Generation.value_65
#check @Kourovka.Flag.Generation.fixed_65
#check @Kourovka.Flag.Generation.zero_65
#check @Kourovka.Flag.Generation.n66
#check @Kourovka.Flag.Generation.value_66
#check @Kourovka.Flag.Generation.fixed_66
#check @Kourovka.Flag.Generation.zero_66
#check @Kourovka.Flag.Generation.n67
#check @Kourovka.Flag.Generation.value_67
#check @Kourovka.Flag.Generation.fixed_67
#check @Kourovka.Flag.Generation.zero_67
#check @Kourovka.Flag.Generation.n68
#check @Kourovka.Flag.Generation.value_68
#check @Kourovka.Flag.Generation.fixed_68
#check @Kourovka.Flag.Generation.zero_68
#check @Kourovka.Flag.Generation.n69
#check @Kourovka.Flag.Generation.value_69
#check @Kourovka.Flag.Generation.fixed_69
#check @Kourovka.Flag.Generation.zero_69
#check @Kourovka.Flag.Generation.n70
#check @Kourovka.Flag.Generation.value_70
#check @Kourovka.Flag.Generation.fixed_70
#check @Kourovka.Flag.Generation.zero_70
#check @Kourovka.Flag.Generation.n71
#check @Kourovka.Flag.Generation.value_71
#check @Kourovka.Flag.Generation.fixed_71
#check @Kourovka.Flag.Generation.zero_71
#check @Kourovka.Flag.Generation.n72
#check @Kourovka.Flag.Generation.value_72
#check @Kourovka.Flag.Generation.fixed_72
#check @Kourovka.Flag.Generation.zero_72
#check @Kourovka.Flag.Generation.n73
#check @Kourovka.Flag.Generation.value_73
#check @Kourovka.Flag.Generation.fixed_73
#check @Kourovka.Flag.Generation.zero_73
#check @Kourovka.Flag.Generation.n74
#check @Kourovka.Flag.Generation.value_74
#check @Kourovka.Flag.Generation.fixed_74
#check @Kourovka.Flag.Generation.zero_74
#check @Kourovka.Flag.Generation.n75
#check @Kourovka.Flag.Generation.value_75
#check @Kourovka.Flag.Generation.fixed_75
#check @Kourovka.Flag.Generation.zero_75
#check @Kourovka.Flag.Generation.n76
#check @Kourovka.Flag.Generation.value_76
#check @Kourovka.Flag.Generation.fixed_76
#check @Kourovka.Flag.Generation.zero_76
#check @Kourovka.Flag.Generation.n77
#check @Kourovka.Flag.Generation.value_77
#check @Kourovka.Flag.Generation.fixed_77
#check @Kourovka.Flag.Generation.zero_77
#check @Kourovka.Flag.Generation.n78
#check @Kourovka.Flag.Generation.value_78
#check @Kourovka.Flag.Generation.fixed_78
#check @Kourovka.Flag.Generation.zero_78
#check @Kourovka.Flag.Generation.n79
#check @Kourovka.Flag.Generation.value_79
#check @Kourovka.Flag.Generation.fixed_79
#check @Kourovka.Flag.Generation.zero_79
#check @Kourovka.Flag.Generation.n80
#check @Kourovka.Flag.Generation.value_80
#check @Kourovka.Flag.Generation.fixed_80
#check @Kourovka.Flag.Generation.zero_80
#check @Kourovka.Flag.Generation.n81
#check @Kourovka.Flag.Generation.value_81
#check @Kourovka.Flag.Generation.fixed_81
#check @Kourovka.Flag.Generation.zero_81
#check @Kourovka.Flag.Generation.n82
#check @Kourovka.Flag.Generation.value_82
#check @Kourovka.Flag.Generation.fixed_82
#check @Kourovka.Flag.Generation.zero_82
#check @Kourovka.Flag.Generation.n83
#check @Kourovka.Flag.Generation.value_83
#check @Kourovka.Flag.Generation.fixed_83
#check @Kourovka.Flag.Generation.zero_83
#check @Kourovka.Flag.Generation.n84
#check @Kourovka.Flag.Generation.value_84
#check @Kourovka.Flag.Generation.fixed_84
#check @Kourovka.Flag.Generation.zero_84
#check @Kourovka.Flag.Generation.n85
#check @Kourovka.Flag.Generation.value_85
#check @Kourovka.Flag.Generation.fixed_85
#check @Kourovka.Flag.Generation.zero_85
#check @Kourovka.Flag.Generation.n86
#check @Kourovka.Flag.Generation.value_86
#check @Kourovka.Flag.Generation.fixed_86
#check @Kourovka.Flag.Generation.zero_86
#check @Kourovka.Flag.Generation.n87
#check @Kourovka.Flag.Generation.value_87
#check @Kourovka.Flag.Generation.fixed_87
#check @Kourovka.Flag.Generation.zero_87
#check @Kourovka.Flag.Generation.target_0
#check @Kourovka.Flag.Generation.target_1
#check @Kourovka.Flag.Generation.target_2
#check @Kourovka.Flag.Generation.target_3
#check @Kourovka.Flag.Generation.target_4
#check @Kourovka.Flag.Generation.target_5
#check @Kourovka.Flag.Generation.target_6
#check @Kourovka.Flag.Generation.target_7
#check @Kourovka.Flag.Generation.target_8
#check @Kourovka.Flag.Generation.target_9
#check @Kourovka.Flag.Generation.target_10
#check @Kourovka.Flag.Generation.target_11
#check @Kourovka.Flag.Generation.target_12
#check @Kourovka.Flag.Generation.target_13
#check @Kourovka.Flag.Generation.target_14
#check @Kourovka.Flag.Generation.target_15
#check @Kourovka.Flag.Generation.target_16
#check @Kourovka.Flag.Generation.target_17
#check @Kourovka.Flag.Generation.target_18
#check @Kourovka.Flag.Generation.target_19
#check @Kourovka.Flag.Generation.target_20
#check @Kourovka.Flag.Generation.target_21
#check @Kourovka.Flag.Generation.target_22
#check @Kourovka.Flag.Generation.target_23
#check @Kourovka.Flag.Generation.target_24
#check @Kourovka.Flag.Generation.target_25
#check @Kourovka.Flag.Generation.target_26
#check @Kourovka.Flag.Generation.target_27
#check @Kourovka.Flag.Generation.target_28
#check @Kourovka.Flag.Generation.target_29
#check @Kourovka.Flag.Generation.target_30
#check @Kourovka.Flag.Generation.fixed_basis
#check @Kourovka.Flag.Generation.zero_basis
#check @Kourovka.Flag.Generation.fixed_all
#check @Kourovka.Flag.Generation.zero_all
#check @Kourovka.Flag.fixes_x
#check @Kourovka.Flag.automorphism_ad_images
#check @Kourovka.Flag.residual_sign_is_one
#check @Kourovka.Flag.full_flag_rigidity
#check @Kourovka.Flag.derivation_kills_x
#check @Kourovka.Flag.derivation_ad_images
#check @Kourovka.Flag.infinitesimal_flag_rigidity
#check @Kourovka.Flag.lieEquiv_flag_rigidity
#check @Kourovka.FlagScalars.automorphism_first_stage
#check @Kourovka.FlagScalars.derivation_first_stage
#check @Kourovka.FlagScalars.exclude_residual_sign
#check @Kourovka.Lattice.toOriginalFn
#check @Kourovka.Lattice.fromOriginalFn
#check @Kourovka.Lattice.P
#check @Kourovka.Lattice.adaptedB
#check @Kourovka.Lattice.weight
#check @Kourovka.Lattice.degree
#check @Kourovka.Lattice.weight_bounds
#check @Kourovka.Lattice.degree_bounds
#check @Kourovka.Lattice.diagonal
#check @Kourovka.Lattice.embed
#check @Kourovka.Lattice.embed_apply
#check @Kourovka.Lattice.diagonal_injective
#check @Kourovka.Lattice.embed_injective
#check @Kourovka.Lattice.embed_divisible_two
#check @Kourovka.Lattice.embed_divisible_reflect
#check @Kourovka.Lattice.Checks.embed_0
#check @Kourovka.Lattice.Checks.embed_1
#check @Kourovka.Lattice.Checks.embed_2
#check @Kourovka.Lattice.Checks.embed_3
#check @Kourovka.Lattice.Checks.embed_4
#check @Kourovka.Lattice.Checks.embed_5
#check @Kourovka.Lattice.Checks.embed_6
#check @Kourovka.Lattice.Checks.embed_7
#check @Kourovka.Lattice.Checks.embed_8
#check @Kourovka.Lattice.Checks.embed_9
#check @Kourovka.Lattice.Checks.embed_10
#check @Kourovka.Lattice.Checks.embed_11
#check @Kourovka.Lattice.Checks.embed_12
#check @Kourovka.Lattice.Checks.embed_13
#check @Kourovka.Lattice.Checks.embed_14
#check @Kourovka.Lattice.Checks.embed_15
#check @Kourovka.Lattice.Checks.embed_16
#check @Kourovka.Lattice.Checks.embed_17
#check @Kourovka.Lattice.Checks.embed_18
#check @Kourovka.Lattice.Checks.embed_19
#check @Kourovka.Lattice.Checks.embed_20
#check @Kourovka.Lattice.Checks.embed_21
#check @Kourovka.Lattice.Checks.embed_22
#check @Kourovka.Lattice.Checks.embed_23
#check @Kourovka.Lattice.Checks.embed_24
#check @Kourovka.Lattice.Checks.embed_25
#check @Kourovka.Lattice.Checks.embed_26
#check @Kourovka.Lattice.Checks.embed_27
#check @Kourovka.Lattice.Checks.embed_28
#check @Kourovka.Lattice.Checks.embed_29
#check @Kourovka.Lattice.Checks.embed_30
#check @Kourovka.Lattice.originalBasis
#check @Kourovka.Lattice.P_unit
#check @Kourovka.Lattice.diagonal_unit
#check @Kourovka.Lattice.embed_unit
#check @Kourovka.Lattice.LB_basis_coeff
#check @Kourovka.Lattice.Expr
#check @Kourovka.Lattice.Expr.eval
#check @Kourovka.Lattice.Expr.map_eval
#check @Kourovka.Lattice.Expr.eval_mem
#check @Kourovka.Lattice.Expr.approximate_map_mem
#check @Kourovka.Lattice.Expr.approximate_derivation_mem
#check @Kourovka.Lattice.embedCheck_all
#check @Kourovka.Lattice.embed_bracket
#check @Kourovka.Lattice.integer_leibniz
#check @Kourovka.Lattice.integer_jacobi_defect
#check @Kourovka.Lattice.LB_leibniz
#check @Kourovka.Lattice.lieRing
#check @Kourovka.Lattice.lieAlgebra
#check @Kourovka.Lattice.diagonal_bracket
#check @Kourovka.Lattice.IntegralGeneration.castAdd
#check @Kourovka.Lattice.IntegralGeneration.generator_value_ring
#check @Kourovka.Lattice.IntegralGeneration.closedSubmodule_eq_top
#check @Kourovka.Lattice.IntegralGeneration.denominator_unit_padic
#check @Kourovka.Lattice.IntegralGeneration.padic_generation
#check @Kourovka.Lattice.IntegralGeneration.X
#check @Kourovka.Lattice.IntegralGeneration.Y
#check @Kourovka.Lattice.IntegralGeneration.ev
#check @Kourovka.Lattice.IntegralGeneration.g0
#check @Kourovka.Lattice.IntegralGeneration.eval_0
#check @Kourovka.Lattice.IntegralGeneration.g1
#check @Kourovka.Lattice.IntegralGeneration.eval_1
#check @Kourovka.Lattice.IntegralGeneration.g2
#check @Kourovka.Lattice.IntegralGeneration.eval_2
#check @Kourovka.Lattice.IntegralGeneration.g3
#check @Kourovka.Lattice.IntegralGeneration.eval_3
#check @Kourovka.Lattice.IntegralGeneration.g4
#check @Kourovka.Lattice.IntegralGeneration.eval_4
#check @Kourovka.Lattice.IntegralGeneration.g5
#check @Kourovka.Lattice.IntegralGeneration.eval_5
#check @Kourovka.Lattice.IntegralGeneration.g6
#check @Kourovka.Lattice.IntegralGeneration.eval_6
#check @Kourovka.Lattice.IntegralGeneration.g7
#check @Kourovka.Lattice.IntegralGeneration.eval_7
#check @Kourovka.Lattice.IntegralGeneration.g8
#check @Kourovka.Lattice.IntegralGeneration.eval_8
#check @Kourovka.Lattice.IntegralGeneration.g9
#check @Kourovka.Lattice.IntegralGeneration.eval_9
#check @Kourovka.Lattice.IntegralGeneration.g10
#check @Kourovka.Lattice.IntegralGeneration.eval_10
#check @Kourovka.Lattice.IntegralGeneration.g11
#check @Kourovka.Lattice.IntegralGeneration.eval_11
#check @Kourovka.Lattice.IntegralGeneration.g12
#check @Kourovka.Lattice.IntegralGeneration.eval_12
#check @Kourovka.Lattice.IntegralGeneration.g13
#check @Kourovka.Lattice.IntegralGeneration.eval_13
#check @Kourovka.Lattice.IntegralGeneration.g14
#check @Kourovka.Lattice.IntegralGeneration.eval_14
#check @Kourovka.Lattice.IntegralGeneration.g15
#check @Kourovka.Lattice.IntegralGeneration.eval_15
#check @Kourovka.Lattice.IntegralGeneration.g16
#check @Kourovka.Lattice.IntegralGeneration.eval_16
#check @Kourovka.Lattice.IntegralGeneration.g17
#check @Kourovka.Lattice.IntegralGeneration.eval_17
#check @Kourovka.Lattice.IntegralGeneration.g18
#check @Kourovka.Lattice.IntegralGeneration.eval_18
#check @Kourovka.Lattice.IntegralGeneration.g19
#check @Kourovka.Lattice.IntegralGeneration.eval_19
#check @Kourovka.Lattice.IntegralGeneration.g20
#check @Kourovka.Lattice.IntegralGeneration.eval_20
#check @Kourovka.Lattice.IntegralGeneration.g21
#check @Kourovka.Lattice.IntegralGeneration.eval_21
#check @Kourovka.Lattice.IntegralGeneration.g22
#check @Kourovka.Lattice.IntegralGeneration.eval_22
#check @Kourovka.Lattice.IntegralGeneration.g23
#check @Kourovka.Lattice.IntegralGeneration.eval_23
#check @Kourovka.Lattice.IntegralGeneration.g24
#check @Kourovka.Lattice.IntegralGeneration.eval_24
#check @Kourovka.Lattice.IntegralGeneration.g25
#check @Kourovka.Lattice.IntegralGeneration.eval_25
#check @Kourovka.Lattice.IntegralGeneration.g26
#check @Kourovka.Lattice.IntegralGeneration.eval_26
#check @Kourovka.Lattice.IntegralGeneration.g27
#check @Kourovka.Lattice.IntegralGeneration.eval_27
#check @Kourovka.Lattice.IntegralGeneration.g28
#check @Kourovka.Lattice.IntegralGeneration.eval_28
#check @Kourovka.Lattice.IntegralGeneration.g29
#check @Kourovka.Lattice.IntegralGeneration.eval_29
#check @Kourovka.Lattice.IntegralGeneration.g30
#check @Kourovka.Lattice.IntegralGeneration.eval_30
#check @Kourovka.Lattice.IntegralGeneration.g31
#check @Kourovka.Lattice.IntegralGeneration.eval_31
#check @Kourovka.Lattice.IntegralGeneration.g32
#check @Kourovka.Lattice.IntegralGeneration.eval_32
#check @Kourovka.Lattice.IntegralGeneration.g33
#check @Kourovka.Lattice.IntegralGeneration.eval_33
#check @Kourovka.Lattice.IntegralGeneration.g34
#check @Kourovka.Lattice.IntegralGeneration.eval_34
#check @Kourovka.Lattice.IntegralGeneration.g35
#check @Kourovka.Lattice.IntegralGeneration.eval_35
#check @Kourovka.Lattice.IntegralGeneration.g36
#check @Kourovka.Lattice.IntegralGeneration.eval_36
#check @Kourovka.Lattice.IntegralGeneration.g37
#check @Kourovka.Lattice.IntegralGeneration.eval_37
#check @Kourovka.Lattice.IntegralGeneration.g38
#check @Kourovka.Lattice.IntegralGeneration.eval_38
#check @Kourovka.Lattice.IntegralGeneration.g39
#check @Kourovka.Lattice.IntegralGeneration.eval_39
#check @Kourovka.Lattice.IntegralGeneration.g40
#check @Kourovka.Lattice.IntegralGeneration.eval_40
#check @Kourovka.Lattice.IntegralGeneration.g41
#check @Kourovka.Lattice.IntegralGeneration.eval_41
#check @Kourovka.Lattice.IntegralGeneration.g42
#check @Kourovka.Lattice.IntegralGeneration.eval_42
#check @Kourovka.Lattice.IntegralGeneration.g43
#check @Kourovka.Lattice.IntegralGeneration.eval_43
#check @Kourovka.Lattice.IntegralGeneration.g44
#check @Kourovka.Lattice.IntegralGeneration.eval_44
#check @Kourovka.Lattice.IntegralGeneration.g45
#check @Kourovka.Lattice.IntegralGeneration.eval_45
#check @Kourovka.Lattice.IntegralGeneration.g46
#check @Kourovka.Lattice.IntegralGeneration.eval_46
#check @Kourovka.Lattice.IntegralGeneration.g47
#check @Kourovka.Lattice.IntegralGeneration.eval_47
#check @Kourovka.Lattice.IntegralGeneration.g48
#check @Kourovka.Lattice.IntegralGeneration.eval_48
#check @Kourovka.Lattice.IntegralGeneration.g49
#check @Kourovka.Lattice.IntegralGeneration.eval_49
#check @Kourovka.Lattice.IntegralGeneration.g50
#check @Kourovka.Lattice.IntegralGeneration.eval_50
#check @Kourovka.Lattice.IntegralGeneration.g51
#check @Kourovka.Lattice.IntegralGeneration.eval_51
#check @Kourovka.Lattice.IntegralGeneration.g52
#check @Kourovka.Lattice.IntegralGeneration.eval_52
#check @Kourovka.Lattice.IntegralGeneration.g53
#check @Kourovka.Lattice.IntegralGeneration.eval_53
#check @Kourovka.Lattice.IntegralGeneration.g54
#check @Kourovka.Lattice.IntegralGeneration.eval_54
#check @Kourovka.Lattice.IntegralGeneration.g55
#check @Kourovka.Lattice.IntegralGeneration.eval_55
#check @Kourovka.Lattice.IntegralGeneration.g56
#check @Kourovka.Lattice.IntegralGeneration.eval_56
#check @Kourovka.Lattice.IntegralGeneration.g57
#check @Kourovka.Lattice.IntegralGeneration.eval_57
#check @Kourovka.Lattice.IntegralGeneration.g58
#check @Kourovka.Lattice.IntegralGeneration.eval_58
#check @Kourovka.Lattice.IntegralGeneration.g59
#check @Kourovka.Lattice.IntegralGeneration.eval_59
#check @Kourovka.Lattice.IntegralGeneration.g60
#check @Kourovka.Lattice.IntegralGeneration.eval_60
#check @Kourovka.Lattice.IntegralGeneration.g61
#check @Kourovka.Lattice.IntegralGeneration.eval_61
#check @Kourovka.Lattice.IntegralGeneration.g62
#check @Kourovka.Lattice.IntegralGeneration.eval_62
#check @Kourovka.Lattice.IntegralGeneration.g63
#check @Kourovka.Lattice.IntegralGeneration.eval_63
#check @Kourovka.Lattice.IntegralGeneration.g64
#check @Kourovka.Lattice.IntegralGeneration.eval_64
#check @Kourovka.Lattice.IntegralGeneration.g65
#check @Kourovka.Lattice.IntegralGeneration.eval_65
#check @Kourovka.Lattice.IntegralGeneration.g66
#check @Kourovka.Lattice.IntegralGeneration.eval_66
#check @Kourovka.Lattice.IntegralGeneration.g67
#check @Kourovka.Lattice.IntegralGeneration.eval_67
#check @Kourovka.Lattice.IntegralGeneration.g68
#check @Kourovka.Lattice.IntegralGeneration.eval_68
#check @Kourovka.Lattice.IntegralGeneration.g69
#check @Kourovka.Lattice.IntegralGeneration.eval_69
#check @Kourovka.Lattice.IntegralGeneration.g70
#check @Kourovka.Lattice.IntegralGeneration.eval_70
#check @Kourovka.Lattice.IntegralGeneration.g71
#check @Kourovka.Lattice.IntegralGeneration.eval_71
#check @Kourovka.Lattice.IntegralGeneration.g72
#check @Kourovka.Lattice.IntegralGeneration.eval_72
#check @Kourovka.Lattice.IntegralGeneration.g73
#check @Kourovka.Lattice.IntegralGeneration.eval_73
#check @Kourovka.Lattice.IntegralGeneration.g74
#check @Kourovka.Lattice.IntegralGeneration.eval_74
#check @Kourovka.Lattice.IntegralGeneration.g75
#check @Kourovka.Lattice.IntegralGeneration.eval_75
#check @Kourovka.Lattice.IntegralGeneration.g76
#check @Kourovka.Lattice.IntegralGeneration.eval_76
#check @Kourovka.Lattice.IntegralGeneration.g77
#check @Kourovka.Lattice.IntegralGeneration.eval_77
#check @Kourovka.Lattice.IntegralGeneration.g78
#check @Kourovka.Lattice.IntegralGeneration.eval_78
#check @Kourovka.Lattice.IntegralGeneration.g79
#check @Kourovka.Lattice.IntegralGeneration.eval_79
#check @Kourovka.Lattice.IntegralGeneration.g80
#check @Kourovka.Lattice.IntegralGeneration.eval_80
#check @Kourovka.Lattice.IntegralGeneration.g81
#check @Kourovka.Lattice.IntegralGeneration.eval_81
#check @Kourovka.Lattice.IntegralGeneration.g82
#check @Kourovka.Lattice.IntegralGeneration.eval_82
#check @Kourovka.Lattice.IntegralGeneration.g83
#check @Kourovka.Lattice.IntegralGeneration.eval_83
#check @Kourovka.Lattice.IntegralGeneration.g84
#check @Kourovka.Lattice.IntegralGeneration.eval_84
#check @Kourovka.Lattice.IntegralGeneration.g85
#check @Kourovka.Lattice.IntegralGeneration.eval_85
#check @Kourovka.Lattice.IntegralGeneration.g86
#check @Kourovka.Lattice.IntegralGeneration.eval_86
#check @Kourovka.Lattice.IntegralGeneration.g87
#check @Kourovka.Lattice.IntegralGeneration.eval_87
#check @Kourovka.Lattice.IntegralGeneration.denominator
#check @Kourovka.Lattice.IntegralGeneration.generator
#check @Kourovka.Lattice.IntegralGeneration.denominator_not_divisible
#check @Kourovka.Lattice.IntegralGeneration.generator_value_0
#check @Kourovka.Lattice.IntegralGeneration.generator_value_1
#check @Kourovka.Lattice.IntegralGeneration.generator_value_2
#check @Kourovka.Lattice.IntegralGeneration.generator_value_3
#check @Kourovka.Lattice.IntegralGeneration.generator_value_4
#check @Kourovka.Lattice.IntegralGeneration.generator_value_5
#check @Kourovka.Lattice.IntegralGeneration.generator_value_6
#check @Kourovka.Lattice.IntegralGeneration.generator_value_7
#check @Kourovka.Lattice.IntegralGeneration.generator_value_8
#check @Kourovka.Lattice.IntegralGeneration.generator_value_9
#check @Kourovka.Lattice.IntegralGeneration.generator_value_10
#check @Kourovka.Lattice.IntegralGeneration.generator_value_11
#check @Kourovka.Lattice.IntegralGeneration.generator_value_12
#check @Kourovka.Lattice.IntegralGeneration.generator_value_13
#check @Kourovka.Lattice.IntegralGeneration.generator_value_14
#check @Kourovka.Lattice.IntegralGeneration.generator_value_15
#check @Kourovka.Lattice.IntegralGeneration.generator_value_16
#check @Kourovka.Lattice.IntegralGeneration.generator_value_17
#check @Kourovka.Lattice.IntegralGeneration.generator_value_18
#check @Kourovka.Lattice.IntegralGeneration.generator_value_19
#check @Kourovka.Lattice.IntegralGeneration.generator_value_20
#check @Kourovka.Lattice.IntegralGeneration.generator_value_21
#check @Kourovka.Lattice.IntegralGeneration.generator_value_22
#check @Kourovka.Lattice.IntegralGeneration.generator_value_23
#check @Kourovka.Lattice.IntegralGeneration.generator_value_24
#check @Kourovka.Lattice.IntegralGeneration.generator_value_25
#check @Kourovka.Lattice.IntegralGeneration.generator_value_26
#check @Kourovka.Lattice.IntegralGeneration.generator_value_27
#check @Kourovka.Lattice.IntegralGeneration.generator_value_28
#check @Kourovka.Lattice.IntegralGeneration.generator_value_29
#check @Kourovka.Lattice.IntegralGeneration.generator_value_30
#check @Kourovka.Lattice.IntegralGeneration.generator_value
#check @Kourovka.Lattice.NearIdentity.powers_natural
#check @Kourovka.Lattice.NearIdentity.ambient_power_divisible
#check @Kourovka.Lattice.NearIdentity.ell_power_divisible
#check @Kourovka.Lattice.NearIdentity.reduce_scalar_modulus
#check @Kourovka.Lattice.NearIdentity.finite_power_zero
#check @Kourovka.Lattice.NearIdentity.finiteOneAddUnit
#check @Kourovka.Lattice.NearIdentity.finiteOneAddUnit_value
#check @Kourovka.Lattice.Precision.scaled
#check @Kourovka.Lattice.Precision.scaled_le
#check @Kourovka.Lattice.Precision.scaled_mono
#check @Kourovka.Lattice.Precision.scaled_antitone
#check @Kourovka.Lattice.Precision.cancel_smul
#check @Kourovka.Lattice.Precision.cancel_scaled_membership
#check @Kourovka.Lattice.Precision.bilinear_error_enlargement
#check @Kourovka.Lattice.Precision.automorphismError
#check @Kourovka.Lattice.Precision.automorphismError_apply
#check @Kourovka.Lattice.Precision.error_scaled_bracket
#check @Kourovka.Lattice.Precision.derivation_scaled_bracket
#check @Kourovka.Lattice.Precision.arbitrary_automorphism_error_bound
#check @Kourovka.Lattice.Precision.arbitrary_derivation_error_bound
#check @Kourovka.Lattice.Precision.expressionSpan
#check @Kourovka.Lattice.Precision.approximate_lift_preserves
#check @Kourovka.Lattice.Precision.approximate_derivation_lift_preserves
#check @Kourovka.Lattice.scaledTerms
#check @Kourovka.Lattice.LB
#check @Kourovka.Lattice.LB_alternating
#check @Kourovka.Lattice.mapVec_LB
#check @Kourovka.Lattice.EmbedCheck
#check @Kourovka.Lattice.Weighted.member
#check @Kourovka.Lattice.Weighted.scaled_unit_mem
#check @Kourovka.Lattice.Weighted.entries_divisible
#check @Kourovka.Lattice.Weighted.reduced_entry_zero
#check @Kourovka.Lattice.Weighted.reduction
#check @Kourovka.Lattice.Weighted.level
#check @Kourovka.Lattice.Weighted.reduction_preserves_level
#check @Kourovka.Lattice.Weighted.weight_below_one
#check @Kourovka.Lattice.Weighted.weight_below_two
#check @Kourovka.Linear.unitVec
#check @Kourovka.Linear.unitVec_same
#check @Kourovka.Linear.unitVec_other
#check @Kourovka.Linear.decompose
#check @Kourovka.Linear.ext_basis
#check @Kourovka.Linear.linear_apply
#check @Kourovka.Linear.ext_bilinear
#check @Kourovka.Linear.ext_trilinear
#check @Kourovka.Linear.jacobiTensor
#check @Kourovka.Linear.jacobi_of_basis
#check @Kourovka.Linear.Bilinear
#check @Kourovka.Linear.post
#check @Kourovka.Linear.pre
#check @Kourovka.Linear.post_apply
#check @Kourovka.Linear.pre_apply
#check @Kourovka.Linear.transport
#check @Kourovka.Linear.transport_apply
#check @Kourovka.Linear.hom_of_basis
#check @Kourovka.Linear.delta
#check @Kourovka.Linear.delta_apply
#check @Kourovka.Sparse.bilinear
#check @Kourovka.Linear.EndCoords
#check @Kourovka.Linear.elementary
#check @Kourovka.Linear.elementary_apply
#check @Kourovka.Linear.fromEntries
#check @Kourovka.Linear.toEntries
#check @Kourovka.Linear.fromEntries_apply
#check @Kourovka.Linear.entries_fromEntries
#check @Kourovka.Linear.fromEntries_entries
#check @Kourovka.Linear.endomorphismCoordinates
#check @Kourovka.prime
#check @Kourovka.depth
#check @Kourovka.dimension
#check @Kourovka.prime_is_prime
#check @Kourovka.coordinate_exponent
#check @Kourovka.automorphism_exponent
#check @Kourovka.class_in_lazard_range
#check @Kourovka.Coordinates
#check @Kourovka.Raw.falling
#check @Kourovka.Raw.transvectant
#check @Kourovka.Raw.Summand
#check @Kourovka.Raw.summands
#check @Kourovka.Raw.moduleCoefficient
#check @Kourovka.Raw.Product
#check @Kourovka.Raw.products
#check @Kourovka.Raw.productCoefficient
#check @Kourovka.Raw.orderedCoefficient
#check @Kourovka.Raw.coefficient
#check @Kourovka.Raw.reconstructedTerms
#check @Kourovka.TableCertificate.row
#check @Kourovka.TableCertificate.row_0
#check @Kourovka.TableCertificate.row_1
#check @Kourovka.TableCertificate.row_2
#check @Kourovka.TableCertificate.row_3
#check @Kourovka.TableCertificate.row_4
#check @Kourovka.TableCertificate.row_5
#check @Kourovka.TableCertificate.row_6
#check @Kourovka.TableCertificate.row_7
#check @Kourovka.TableCertificate.row_8
#check @Kourovka.TableCertificate.row_9
#check @Kourovka.TableCertificate.row_10
#check @Kourovka.TableCertificate.row_11
#check @Kourovka.TableCertificate.row_12
#check @Kourovka.TableCertificate.row_13
#check @Kourovka.TableCertificate.row_14
#check @Kourovka.TableCertificate.row_15
#check @Kourovka.TableCertificate.row_16
#check @Kourovka.TableCertificate.row_17
#check @Kourovka.TableCertificate.row_18
#check @Kourovka.TableCertificate.row_19
#check @Kourovka.TableCertificate.row_20
#check @Kourovka.TableCertificate.row_21
#check @Kourovka.TableCertificate.row_22
#check @Kourovka.TableCertificate.row_23
#check @Kourovka.TableCertificate.row_24
#check @Kourovka.TableCertificate.row_25
#check @Kourovka.TableCertificate.row_26
#check @Kourovka.TableCertificate.row_27
#check @Kourovka.TableCertificate.row_28
#check @Kourovka.TableCertificate.row_29
#check @Kourovka.TableCertificate.row_30
#check @Kourovka.raw_table_matches_exported
#check @Kourovka.Word
#check @Kourovka.Word.eval
#check @Kourovka.Word.map_eval
#check @Kourovka.Word.fixed_eval
#check @Kourovka.Word.derivation_zero_eval
#check @Kourovka.Word.fixed_of_generation
#check @Kourovka.Word.zero_of_generation
