from pathlib import Path
import datetime as dt
import hashlib
import json
p=Path('draft_pr_publication_program_20260930/audits/pr40_2814/acceptance_revised_static_adversary_family')
def pin(q):
 r=q.read_bytes();return {'path':q.relative_to(p).as_posix(),'bytes':len(r),'sha256':hashlib.sha256(r).hexdigest()}
a=json.loads((p/'inspect_revised_inputs_actual_capture/stdout.bin').read_bytes())
b=json.loads((p/'finite_guard_controls_actual_capture/stdout.bin').read_bytes())
now=dt.datetime.now(dt.timezone.utc).isoformat()
obj={'schema':'pr40-fresh-revised-acceptance-static-assessment/v1','utc':now,'status':'PASS_QUALIFIED_SOURCE_ONLY','reviewed_preparation_manifest_sha256':a['preparation_manifest_sha256'],'mandatory_defects':[],'optional_hardening_requested':[],'all_prior_S1_through_S6_corrected':True,'scientific_attribution_regression_corrected':True,'reviewed_source_programs':5,'reviewed_source_lines':a['reviewed_source_lines'],'reviewed_members_excluding_self':15,'preserved_original_preparation_members':12,'preserved_prior_static_members':22,'current_members':239,'current_JSON_including_self':110,'all_dependencies':216,'original_scientific_files_preserved':13,'whole_review_members':25,'whole_foreign_members_separately_exact':21,'retained_actual_original_family_members':42,'retained_actual_freeze_members':4,'unique_inspected_input_members':a['unique_inspected_input_members'],'unique_inspected_input_bytes':a['unique_inspected_input_bytes'],'strict_complete_JSON_objects':a['whole_typed_JSON_objects'],'independent_predicate_controls':b['predicate_control_count'],'actual_private_publication_controls':2,'own_actual_capture_receipts':[pin(p/'inspect_revised_inputs_actual_capture/CAPTURE.json'),pin(p/'finite_guard_controls_actual_capture/CAPTURE.json')],'own_complete_results':[pin(p/'inspect_revised_inputs_actual_capture/stdout.bin'),pin(p/'finite_guard_controls_actual_capture/stdout.bin')],'report':pin(p/'REPORT.md'),'prepared_or_old_verifier_or_native_driver_import_compile_execution':False,'actual_future_final_reconciliation_integration_merge_mirror_post_claimed':False,'Git_SQL_native_shared_canonical_remote_mutations':False,'outside_communication':False,'scientific_scope_recertification_qualification':'Fresh static administrative source and exact data review; earlier operative mathematical certificates retain their reading qualifications. No renewed unexposed source-first or new full-PDF proof reading claimed.','original_substantive_attempts':0,'turn_limit':5,'new_substantive_attempts':0,'audit_turns':0,'full_problem_solved':False,'partial_valid':True,'source_hold':True,'novelty_claimed':False,'current_model':None,'current_reasoning_effort':None,'current_deadline_utc':None,'paper_or_new_DOI_or_tracker':False,'static_review_completion_percent':100,'mathematical_discovery_completion_percent':0,'root_followup':'Full root read of this fresh review and closure, followed by genuine adjacent root final reconciliation, integration and post checks using the revised source manifest.'}
(p/'ASSESSMENT.json').write_text(json.dumps(obj,sort_keys=True,indent=2)+'\n')
coverage={'schema':'pr40-fresh-revised-static-read-coverage/v1','utc':now,'entire_revised_fifteen_member_packet_read':True,'source_programs':a['source_programs'],'complete_revised_contract_scope_draft_change_record_revision_bindings_input_bindings_patch_manifest_read':True,'complete_closed_prior_static_REPORT_and_ASSESSMENT_read':True,'complete_original_SOURCE_STATUS_root_operational_mathematical_certificate_current_overview_read':True,'bound_native_driver_entire_source_read':True,'bound_native_driver_lines':len((p.parents[3]/'infrastructure/accepted_state_sync/revision2/accepted_state_sync_v2.py').read_bytes().splitlines()),'full_input_identity_and_typed_structure_inspection':pin(p/'inspect_revised_inputs_actual_capture/stdout.bin'),'original_primary_and_whole_foreign_input_bytes_rehashed_individually':True,'new_full_primary_PDF_proof_reading_claimed':False,'new_unexposed_source_first_mathematical_independence_claimed':False,'reviewed_helper_import_compile_execution':False}
(p/'READ_COVERAGE.json').write_text(json.dumps(coverage,sort_keys=True,indent=2)+'\n')
with (p/'RESEARCH_LOG.md').open('a') as f:f.write('\n## '+now+' — Review complete before strict closure\n\nAll six earlier mandatory findings are corrected; no new mandatory issue. Own input inspector actually passed600 unique files/39,835,206 bytes/242 strict JSON objects. Own44 predicate controls and two real private hardlink controls passed; complete collision/temp/preimage bytes retained. Only own sources executed, with complete actual captures. Root execution still pending. Review100%; discovery0%; original0/5,new0,audit0. Publication remains root-owned.\n')
print(json.dumps({'utc':now,'assessment':pin(p/'ASSESSMENT.json'),'report':pin(p/'REPORT.md'),'coverage':pin(p/'READ_COVERAGE.json')}))
