from pathlib import Path
import hashlib,json,datetime,subprocess,re
h=Path(__file__).resolve().parent
scopes={
'hp-v2':('Full operative §4.1 pp13–15 including Remark4.1, complete invariant-average Proposition4.2 proof, Remark4.3, Examples4.4/4.6; preceding irreducibility/Ad-orbit propositions relevant to faithful holonomy.','Finite GIT quotient of liftable representations; prove whole knot locus liftable first; exceptional fibers permitted.'),
'boyle-v1':('Introduction/definitions, complete Theorem1.1 statement, Remarks1.2/1.3 and entire §2 proof pp1–5.','Generic index-n exponent slip requires n!; actual index2 application valid; same-oriented sign lifts, projective image identical.'),
'porti2017':('Complete §3 ppII–11–II–15 including statements and proofs of Theorems3.1/3.5/3.6/3.8/3.9/3.10 and regular complete-holonomy tangent/dimension argument.','Complete cusp smooth unique complex curve; Calabi–Weil analytic foundation explicitly imported. Historical uniqueness remark superseded.'),
'crs-v3':('Full adjacent introduction Theorem1.8/Conjecture1.9/Corollary1.10 pp8–9; complete operative §5.4 proof pp41–43.','Trivial Alexander polynomial/arithmetic hypotheses and split alternative; unitary curve somewhere does not establish canonical membership.'),
'crs-v1':('Full adjacent Theorem1.8/Conjecture1.9/Corollary1.10 initial statements pp6–7.','Initial extra equivalence with no real points is removed later and is not retained.'),
'crs-published':('Full published introduction statement Theorem1.8/Conjecture1.9/Corollary1.10 pp4975–4977 compared with v3.','Corrected theorem retained; numbering rearrangement not a universal proof.'),
'long-reid':('Complete operative §§4–5 pp251–253 and relevant §6 definition-field distinction through p255.','General one-cusped construction is not an S3 knot; conditional finite-intersection obstruction valid; trace field differs from curve definition field.'),
'porti-weiss':('Complete operative §§2–6, extracted lines90–948; non-almost-product classification, identity-form/L²/boundary injection, natural obstruction integration/Artin, actual character quotient, developing-map regeneration, quadratic fold/Schläfli.','q1 gives actual smooth SU2 character arc. Orbit tangent is B1 despite printed Z1. L² and Artin are stated published foundations.'),
'kojima':('Introduction §§1.1–1.2; complete explicit local-rigidity §2.1 statement/application; exact §§5.1/6.1 convergence hypotheses; entire operative §7 proof including7.5 rational-angle intermediate and complete-cusp endpoint.','Marked global continuation and positive-angle full smooth germs; angle0 handled separately. Geometric estimates §§3–6 imported, not all independently rederived/read here. Full original HK not claimed read.'),
'boileau-porti':('Complete operative AppendixA pp173–178 and AppendixB.1 pp179–186 through end/developing-map completion; exact TheoremA statement and Proposition2.3.1/continuation application.','Spherical-cover finite/ideal endpoint exclusion, transfer H*, meridian regularity and compact real germ, strict-angle Euclidean compactness alternatives; complete cusp unique germ. Foundations/trichotomy/Culler–Shalen imported, not whole215page monograph certified.'),
'flat-table':('Full operative §4/Table1 p3816 and adjoining explanation.','Six orientable flat types and their actual listed presentations; classification imported, abelianization checked.'),
'hantzsche-wendt':('Operative introduction/classification and actual group presentation(3.1), adjoining preliminaries.','Only finite-b1 flat type has H1=Z4²; independently computed from relators.'),
'branched-cover':('Operative §5 p503 through Definition5.1 and adjoining homology-presentation statement.','H1 of double knot cover=coker(V+Vt); odd determinant follows independently for all genera.'),
 'two-bridge':('Operative introduction strict transition and entire §3 setup/Proposition3.1 with source attribution; subsequent Lemma3.2 passage inspected.','Interval/fold description is imported from cited work, actual strict Euclidean existence followed to full AppendixA; no later >pi formula certified.')}
entries=[]
for r in json.loads((h/'SOURCE_RETRIEVAL.json').read_bytes()):
 r=dict(r)
 if r['name'] in scopes:
  r['actual_read_scope'],r['verified_role']=scopes[r['name']];r['entire_source_certified']=False
  p=h/'tmp'/f"{r['name']}.pdf";b=p.read_bytes();assert r['sha256']==hashlib.sha256(b).hexdigest();assert r['text_sha256']==hashlib.sha256(p.with_suffix('.txt').read_bytes()).hexdigest()
  info=subprocess.check_output(['pdfinfo',str(p)]).decode();r['pdf_pages']=int(re.search(r'^Pages:\s*(\d+)',info,re.M).group(1))
 else:r['actual_read_scope']='PDF byte assertion failed. Complete operative theorem proof was separately genuinely read by official web PDF; see Dix-web entry and separate retry qualification.'
 entries.append(r)
k=h/'tmp/K3.pdf';kb=k.read_bytes();entries.insert(0,{'name':'K3-literal-first','url':'https://math.berkeley.edu/sites/default/files/surv-295-ruberman-watermarked-author-pdf.pdf','sha256':hashlib.sha256(kb).hexdigest(),'bytes':len(kb),'pdf_pages':436,'actual_read_scope':'Printedpp76–77, literal Problem1.85 and every adjoining remark. Both pages rendered and genuinely visually viewed before candidate, root or family interpretation.','seal':'literal_seal.json','entire_source_certified':False})
entries.append({'name':'Dix-web-primary','url':'https://escholarship.org/content/qt27j2v475/qt27j2v475_noSplash_7f3e70d717e17eaf9515cffc4ef313be.pdf','transport':'Actual fresh official web PDF text,35pages1556lines','actual_read_scope':'Preceding character/lifting definitions and Lemma3.3.2; entire operative §3.3 pp14–16 web lines836–951 incl Theorem3.3.3 and full Cor3.3.4; complete relevant Chapter5 limitations pp25–27 lines1437–1465.','proof_actually_read':True,'fresh_local_pdf_hash':None,'historical_original_sha_claimed_fresh':False,'direct_fetch_qualification':'Initial own receipt records AssertionError before PDF storage, not an HTTP403. Separate retry HTTP202 zero-byte CloudFront challenge. Earlier root/family403 receipts are historical independent actions.','entire_source_certified':False})
ledger={'utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'entries':entries,'fresh_local_pdf_count_including_K3':15,'source_first_literal_seal':'literal_seal.json','own_proof_initial_seal':'proof_seal.json','proof_seal_correction':'PROOF_SEAL_QUALIFICATION.json','read_before_old_reviews':'All above operative readings except additional Porti2004Prop3.1 detail were completed before initial own proof seal. Supplement inspected afterward is expressly cited and not used to infer verdict from oldPASS.','full_original_HK_analytic_proof_read':False,'full_Porti1998_lemma_read':False,'foundations':'Published imports with exact hypotheses checked: Calabi–Weil/L², Artin, HK as Kojima restatement, geometric compactness/Culler–Shalen, flat classification. No formal assistant verification or external human review.','priority_scope':'Existing bounded search receipts read and limitations confirmed. No fresh exhaustive priority search or worldwide open-status/novelty certificate.'}
(h/'SOURCE_READING_LEDGER.json').write_text(json.dumps(ledger,indent=2,ensure_ascii=False)+'\n');print(json.dumps({'sources':len(entries),'fresh_local_PDFs':15,'source_first':True}))
