"""Own source text/JSON finalization only; no candidate or ROOT operator execution."""
from pathlib import Path,PurePosixPath
import datetime as dt,hashlib,json,stat
R=Path('/Users/alec/Documents/Math');A=R/'draft_pr_publication_program_20260930/audits/pr48_2961';P=A/'post_push_foreign_epoch_preparation_v5';O=A/'post_push_foreign_epoch_preparation_v4';NOW=dt.datetime.now(dt.timezone.utc).isoformat()
def ref(q):
 b=q.read_bytes();return dict(path=q.relative_to(R).as_posix(),bytes=len(b),sha256=hashlib.sha256(b).hexdigest())
def mode_ref(q):return dict(ref(q),full_mode=stat.S_IMODE(q.stat().st_mode))
assert not (P/'SOURCE_READY.json').exists() and not (P/'SOURCE_MANIFEST.json').exists()
h=json.loads((P/'M4_AND_SUPERSEDED_V4_BINDINGS.json').read_bytes())
for z in h['superseded_V4']['complete_payloads']:assert mode_ref(R/z['path'])==z and z['full_mode']==0o644
assert not (O/'SOURCE_MANIFEST.json').exists()
for n in ['integrate_reviewed_partial','state_mirror_reconciliation']:assert (P/(n+'_epoch_v5.py')).read_bytes()==(O/(n+'_epoch_v4.py')).read_bytes()
review=A/'corrective_source_adversary_v4';v=json.loads((review/'VERDICT.json').read_bytes());assert v['status']=='REPAIR_REQUIRED_SOURCE' and [z['id'] for z in v['mandatory_findings']]==['M4'] and v['source_ready_sha256']=='4a2ca334cfea92fb44dfebb874de8d4b0827292b0ab3fb7e82a57de3b8746771'
h['independent_M4_binding']=dict(observed_utc=NOW,report=mode_ref(review/'REPORT.md'),verdict=mode_ref(review/'VERDICT.json'),control_source=mode_ref(review/'private_controls.py'),completed_review_read=True,candidate_approval=False,qualification='Complete rejected source evidence read; mode observations are dated. SOURCE closure never implies candidate or runtime approval.')
if (review/'SELF_MANIFEST.json').exists():
 m=mode_ref(review/'SELF_MANIFEST.json');caprows=[]
 for kind in ['close','readback']:
  d=R/('draft_pr_publication_program_20260930/audits/pr45_9900007/root_pr48_m4_adverse_source_'+kind+'_actual_capture');cap=json.loads((d/'CAPTURE.json').read_bytes());assert cap['status']=='PASS' and cap['exit_code']==0 and type(cap['pid']) is int and cap['pid']>0 and cap['actual_execution'] is True and cap['completed'] is True
  for channel in ['stdout','stderr']:
   z=cap[channel];b=(d/z['path']).read_bytes();assert len(b)==z['bytes'] and hashlib.sha256(b).hexdigest()==z['sha256']
  caprows.append(dict(capture=mode_ref(d/'CAPTURE.json'),complete_capture=cap,members=[mode_ref(q) for q in sorted(d.iterdir())]))
 assert m['full_mode']==0o444;h['independent_M4_binding']['actual_closed_adverse']=dict(self=m,complete_actual_ROOT_captures=caprows,rejection_only=True)
else:h['independent_M4_binding']['actual_closed_adverse']=None
(P/'M4_AND_SUPERSEDED_V4_BINDINGS.json').write_text(json.dumps(h,indent=2)+'\n')
results=json.loads((P/'PRIVATE_MODE_CONTROL_RESULTS.json').read_bytes());assert results['assertions']==17 and results['status']=='PASS_PRIVATE_MODELS_ONLY' and results['candidate_or_ROOT_operator_imported_compiled_executed'] is False
plan=P/'REPAIR_PLAN.md';plan.write_text(plan.read_text().replace('Source repair90%','Source repair100%'))
with (P/'RESEARCH_LOG.md').open('a') as f:f.write('\n'+NOW+' — Complete M4 report/verdict/control source now read and qualified separately. Exact shared parent predicate plus two callsites is sole residual operative change; all versions/consumer paths checked as text. Private child17049 passed17 bounded identity/snapshot/live-mode controls at '+results['started_utc']+'–'+results['finished_utc']+'. Physical24V4 bodies/full0644 remain unchanged, helpers byte-identical. No candidate/production/operator import, compilation/execution or actual copy; no ENOSPC this turn. Source repair100%; corrective review0%; recovery0%; math discovery0%.\n')
names=['epoch_common.py','author_post_push_foreign_epoch_v5.py','execute_post_push_foreign_epoch_phase_v5.py','run_post_push_foreign_epoch_phase_v5.py','inspect_complete_actual_post_epoch_v5.py','integrate_reviewed_partial_epoch_v5.py','state_mirror_reconciliation_epoch_v5.py','CONTRACT.json','REPORT.md','NATIVE_SOURCE_DATE_SURVEY.json','private_mode_controls.py','PRIVATE_MODE_CONTROL_RESULTS.json','close_SOURCE_family.py','verify_closed_SOURCE_family.py','RESEARCH_LOG.md','REPAIR_PLAN.md','ACTUAL_REJECTED_V1_SOURCE_BINDINGS.json','M2_AND_SUPERSEDED_V2_BINDINGS.json','M3_AND_SUPERSEDED_V3_BINDINGS.json','M4_AND_SUPERSEDED_V4_BINDINGS.json']
common=(P/'epoch_common.py').read_text();assert common.count('actual_outer_parent(directory);')==2 and 'directory.parent==A' in common
for n in names[:7]+['close_SOURCE_family.py','verify_closed_SOURCE_family.py']:
 s=(P/n).read_text();assert 'post_push_foreign_epoch_preparation_v4' not in s and 'ROOT_POST_EPOCH_V4_' not in s and '_foreign_epoch_v4_readonly' not in s
files=sorted(q.relative_to(P).as_posix() for q in P.rglob('*') if q.is_file());dirs=sorted(q.relative_to(P).as_posix() for q in P.rglob('*') if q.is_dir());assert set(dirs)=={q.as_posix() for n in files for q in PurePosixPath(n).parents if q.as_posix()!='.'};assert all(not q.is_symlink() and (q.is_file() or q.is_dir()) for q in P.rglob('*'));assert all(stat.S_IMODE((P/n).stat().st_mode)==0o644 for n in files);assert all(stat.S_IMODE((P/n).stat().st_mode)==0o755 for n in dirs+['.'])
ready=dict(schema='pr48-post-push-epoch-SOURCE-readiness/v5',utc=NOW,role='SOURCE preparer, not independent reviewer/ROOT authority',source_only=True,proposed_code_executed=False,production_imported_compiled_executed=False,actual_epoch_or_acceptance_approved=False,source_correction_preparation_percent=100,independent_corrective_review_percent=0,actual_recovery_percent=0,mathematical_discovery_percent=0,source_files=[ref(P/n) for n in names],mode_contract='pr48-source-operator-dependency-full07777/v5',closure_payload_files=sorted(files+['SOURCE_READY.json']),closure_payload_count=len(files)+1,closure_directory_count=len(dirs),closure_manifest_schema='pr48-post-push-epoch-source-closure/v5',closure_manifest_keyset=['schema','source_only','self_excluded','files_count','files','file_modes','directory_modes'],SOURCE_directories_full_mode=0o755,genuine_ROOT_outer_directories_full_mode=0o700,actual_ROOT_outer_parent_required=A.relative_to(R).as_posix(),actual_live_ROOT_operator_path=(A/'capture_root_command.py').relative_to(R).as_posix(),actual_live_ROOT_operator_full_mode=0o644,actual_live_ROOT_operator_parent_full_mode=0o755,actual_live_ROOT_operator_copied_by_preparer=False,superseded_unclosed_V4_READY_sha256='4a2ca334cfea92fb44dfebb874de8d4b0827292b0ab3fb7e82a57de3b8746771',M4_history=ref(P/'M4_AND_SUPERSEDED_V4_BINDINGS.json'),actual_private_controls=ref(P/'PRIVATE_MODE_CONTROL_RESULTS.json'),original_science17_pins_unchanged=True,original22_ROOT_contract_unchanged=True,original_first_three_CAPs_unchanged=True,original_closed53_unchanged=True,future=dict(ROOT_operator_copy=None,ROOT_SOURCE_manifest=None,ROOT_SOURCE_closure_capture=None,ROOT_SOURCE_separate_readback=None,independent_corrective_SOURCE_verdict=None,actual_ROOT_epochs=None,actual_final_three_captures=None,actual_ROOT_complete_post=None,approved=False),remaining_gap='ROOT full source reading/closure/separate reader, independent continuity review, genuine unchanged A48 operator copy, then actual per-role fresh epochs/three final roles/complete ROOT post. No prior source/review PASS transfers.')
with (P/'SOURCE_READY.json').open('xb') as f:f.write((json.dumps(ready,indent=2,sort_keys=True)+'\n').encode())
print(json.dumps(dict(status='READY_SOURCE_V5_ONLY_WAIT_ROOT',payload_files=len(files)+1,directories=len(dirs),bytes=sum((P/n).stat().st_size for n in files)+(P/'SOURCE_READY.json').stat().st_size,ready=ref(P/'SOURCE_READY.json'),operative=[ref(P/n) for n in ['REPORT.md','CONTRACT.json','epoch_common.py','author_post_push_foreign_epoch_v5.py','execute_post_push_foreign_epoch_phase_v5.py','run_post_push_foreign_epoch_phase_v5.py','inspect_complete_actual_post_epoch_v5.py','close_SOURCE_family.py','verify_closed_SOURCE_family.py']],M4_adverse_closed=h['independent_M4_binding']['actual_closed_adverse'] is not None,old24_unchanged=True,candidate_executed=False),indent=2))
