"""Exact Hadamard construction helpers.

The module contains the Goethals-Seidel array used by Eliahou's modular seed
and the bordered two-circulant construction from an odd-length Legendre pair.
It deliberately uses only the Python standard library.  A row is optionally
packed into a Python integer, so exact all-pairs dot products are fast through
XOR and ``int.bit_count``.
"""

from __future__ import annotations

from collections.abc import Sequence

from seed import validate_sign_sequence


Matrix = tuple[tuple[int, ...], ...]


def circulant(first_row: Sequence[int]) -> Matrix:
    validate_sign_sequence(first_row)
    n = len(first_row)
    return tuple(
        tuple(first_row[(column - row) % n] for column in range(n))
        for row in range(n)
    )


def transpose(matrix: Matrix) -> Matrix:
    return tuple(tuple(row) for row in zip(*matrix, strict=True))


def reverse_columns(matrix: Matrix) -> Matrix:
    return tuple(tuple(reversed(row)) for row in matrix)


def negate(matrix: Matrix) -> Matrix:
    return tuple(tuple(-entry for entry in row) for row in matrix)


def concatenate_block_rows(block_rows: Sequence[Sequence[Matrix]]) -> Matrix:
    if not block_rows or not block_rows[0]:
        raise ValueError("nonempty block array required")
    block_size = len(block_rows[0][0])
    result: list[tuple[int, ...]] = []
    for blocks in block_rows:
        if any(len(block) != block_size for block in blocks):
            raise ValueError("all blocks must have equal size")
        for row_index in range(block_size):
            row: list[int] = []
            for block in blocks:
                row.extend(block[row_index])
            result.append(tuple(row))
    return tuple(result)


def goethals_seidel(sequences: Sequence[Sequence[int]]) -> Matrix:
    """Construct the Goethals-Seidel array in Eliahou's convention."""

    if len(sequences) != 4:
        raise ValueError("exactly four sequences are required")
    a, b, c, d = (circulant(sequence) for sequence in sequences)
    br = reverse_columns(b)
    cr = reverse_columns(c)
    dr = reverse_columns(d)
    btr = reverse_columns(transpose(b))
    ctr = reverse_columns(transpose(c))
    dtr = reverse_columns(transpose(d))
    return concatenate_block_rows(
        (
            (a, negate(br), negate(cr), negate(dr)),
            (br, a, negate(dtr), ctr),
            (cr, dtr, a, negate(btr)),
            (dr, negate(ctr), btr, a),
        )
    )


def two_circulant_legendre(
    first: Sequence[int], second: Sequence[int]
) -> Matrix:
    """Construct the order ``2*n+2`` Hadamard candidate from a Legendre pair.

    The two input sequences must have the same odd length and sign sum one.
    This function performs those inexpensive structural checks.  Orthogonality
    is intentionally left to an exact verifier, so the construction is also
    useful when diagnosing near solutions.

    With ``A`` and ``B`` the circulants generated by the two sequences, the
    core and its two-column border are

        [ A    B   ]       [ + + ]
        [ B^T -A^T ]       [ + - ].

    The two top rows complete the standard bordered two-circulant array.
    """

    validate_sign_sequence(first)
    validate_sign_sequence(second)
    if len(first) != len(second):
        raise ValueError("Legendre sequences must have equal length")
    n = len(first)
    if n % 2 != 1:
        raise ValueError("Legendre-pair length must be odd")
    if sum(first) != 1 or sum(second) != 1:
        raise ValueError("normalized Legendre sequences must both have sum one")

    a = circulant(first)
    b = circulant(second)
    at = transpose(a)
    bt = transpose(b)

    rows: list[tuple[int, ...]] = [
        (-1, -1, *([1] * n), *([1] * n)),
        (-1, 1, *([1] * n), *([-1] * n)),
    ]
    for row_index in range(n):
        rows.append((1, 1, *a[row_index], *b[row_index]))
    for row_index in range(n):
        rows.append((1, -1, *bt[row_index], *(-x for x in at[row_index])))
    return tuple(rows)


def pack_row(row: Sequence[int]) -> int:
    validate_sign_sequence(row)
    packed = 0
    for index, entry in enumerate(row):
        if entry == 1:
            packed |= 1 << index
    return packed


def packed_dot(left: int, right: int, length: int) -> int:
    return length - 2 * (left ^ right).bit_count()


def verify_hadamard(matrix: Matrix) -> None:
    """Raise ``ValueError`` unless ``matrix`` is an exact Hadamard matrix."""

    order = len(matrix)
    if order == 0:
        raise ValueError("Hadamard matrix must be nonempty")
    for row in matrix:
        try:
            validate_sign_sequence(row, order)
        except ValueError as error:
            raise ValueError("Hadamard candidate must be a square sign matrix") from error

    packed = tuple(pack_row(row) for row in matrix)
    for left_index, left in enumerate(packed):
        for right_index in range(left_index):
            dot = packed_dot(left, packed[right_index], order)
            if dot:
                raise ValueError(
                    "Hadamard orthogonality failed for rows "
                    f"{right_index} and {left_index}: dot={dot}"
                )
