#!/usr/bin/env python3
"""CP-SAT search for the prescribed-compression Legendre pair of length 333.

For Boolean variables encoding +1 as true, define a difference bit for every
sequence, position, and independent nonzero lag.  The Legendre equation is
equivalent to

    sum_i (a_i XOR a_(i+s)) + sum_i (b_i XOR b_(i+s)) = 334

for ``s=1,...,166``.  The model also fixes all 74 column margins arising from
the conjectural ``C(37,3),D(37,3)`` compression.

The default symmetry mode chooses a lexicographically maximal representative
under the independent dihedral actions generated by shifts through multiples
of 37 and inversion ``i -> -i``.  Every such operation preserves both the LP
equations and this particular fixed compression.

``--mod9-profile`` instead fixes one catalogued exact length-9 row profile.
It replaces the generic compressed products by 18 row cardinalities and
requires ``--symmetry none`` because the generic row actions change the
chosen profile orientation.  This is a restricted exact fiber: any solution
is still a full Legendre pair, but infeasibility concerns only that profile
orbit.

An optional factor-3 compression to length 111 exposes another exact view of
the same equations.  Its entries are sums of three signs, hence belong to
``{-3,-1,1,3}``, and the two compressed PAFs must sum to 662 at lag zero and
-6 at every nonzero lag.  The cheap zero-lag form says exactly 55 of the 222
triples are monochromatic; the full form adds all 55 independent compressed
PAF equations.
"""

from __future__ import annotations

import argparse
from collections.abc import Sequence
from itertools import combinations, product
import json
from math import gcd
from pathlib import Path
import sys

from ortools.sat.python import cp_model

from legendre_333 import (
    CRT_INDEX_TABLE,
    FIXED_PLUS_COUNTS_A,
    FIXED_PLUS_COUNTS_B,
    N,
    save_verified_candidate,
    sequences_from_candidate,
    verify_fixed_compression,
    verify_legendre_pair,
)
from legendre_333_profile_catalog import ROW_SUM_PROFILES
from verify_legendre_333_profile_local import (
    KIND as PROFILE_CHECKPOINT_KIND,
    PARAMETERIZATION as PROFILE_PARAMETERIZATION,
    SCHEMA as PROFILE_CHECKPOINT_SCHEMA,
    verify_profile_checkpoint,
)


INDEPENDENT_LAGS = (N - 1) // 2


def generate_mod3_compression_tuples() -> tuple[tuple[int, ...], ...]:
    """Enumerate every possible factor-111 compression of an ``LP(333)``.

    If ``u`` and ``v`` are the two length-3 compressions, then their entries
    are odd, each vector sums to one, and

        sum(u_i^2) + sum(v_i^2) = 446.

    The last identity follows by summing the Legendre PAF equations over the
    111 lags divisible by three: the zero lag contributes 666 and the other
    110 lags contribute -2 each.  It also bounds every entry by 21, making
    exhaustive generation tiny and exact.
    """

    triples_by_energy: dict[int, list[tuple[int, int, int]]] = {}
    for triple in product(range(-21, 22, 2), repeat=3):
        if sum(triple) != 1:
            continue
        energy = sum(value * value for value in triple)
        triples_by_energy.setdefault(energy, []).append(triple)

    result: list[tuple[int, ...]] = []
    for a_energy, a_triples in triples_by_energy.items():
        for a_triple in a_triples:
            for b_triple in triples_by_energy.get(446 - a_energy, ()):
                result.append(a_triple + b_triple)
    return tuple(result)


MOD3_COMPRESSION_TUPLES = generate_mod3_compression_tuples()

MONOCHROMATIC_TRIPLE_ROWS = tuple(
    (first, second, third, int(first == second == third))
    for first, second, third in product((0, 1), repeat=3)
)


def equality_literal(
    model: cp_model.CpModel,
    left: cp_model.IntVar,
    right: cp_model.IntVar,
    name: str,
) -> cp_model.IntVar:
    """Return a Boolean literal equivalent to ``left == right``."""

    equal = model.new_bool_var(name)
    model.add(left == right).only_enforce_if(equal)
    model.add(left != right).only_enforce_if(equal.negated())
    return equal


def add_lexicographic_greater_or_equal(
    model: cp_model.CpModel,
    left: Sequence[cp_model.IntVar],
    right: Sequence[cp_model.IntVar],
    name: str,
) -> None:
    """Add the exact Boolean-vector constraint ``left >=lex right``."""

    if len(left) != len(right):
        raise ValueError("lexicographic vectors must have equal length")
    if not left:
        return
    prefix_equal = model.new_bool_var(f"{name}_prefix_0")
    model.add(prefix_equal == 1)
    for index, (left_bit, right_bit) in enumerate(zip(left, right, strict=True)):
        model.add(left_bit >= right_bit).only_enforce_if(prefix_equal)
        if index + 1 == len(left):
            break
        equal = equality_literal(model, left_bit, right_bit, f"{name}_eq_{index}")
        next_prefix = model.new_bool_var(f"{name}_prefix_{index + 1}")
        model.add(next_prefix <= prefix_equal)
        model.add(next_prefix <= equal)
        model.add(next_prefix >= prefix_equal + equal - 1)
        prefix_equal = next_prefix


def shifted_image(
    variables: Sequence[cp_model.IntVar], offset: int
) -> list[cp_model.IntVar]:
    """Return the cyclic image ``image[i] = variables[i-offset]``."""

    return [variables[(index - offset) % N] for index in range(N)]


def inverted_image(
    variables: Sequence[cp_model.IntVar],
) -> list[cp_model.IntVar]:
    """Return the group inversion image ``image[i] = variables[-i]``."""

    return [variables[-index % N] for index in range(N)]


def add_fixed_column_margins(
    model: cp_model.CpModel,
    variables: Sequence[cp_model.IntVar],
    plus_counts: Sequence[int],
    prefix: str,
) -> None:
    """Fix the 37 CRT-column sums of one binary sequence."""

    if len(variables) != N or len(plus_counts) != 37:
        raise ValueError("invalid variable or margin dimensions")
    for column, plus_count in enumerate(plus_counts):
        column_variables = [
            variables[CRT_INDEX_TABLE[row][column]] for row in range(9)
        ]
        model.add(sum(column_variables) == plus_count).with_name(
            f"{prefix}_column_margin_{column}"
        )


def add_mod3_compression_table(
    model: cp_model.CpModel,
    a: Sequence[cp_model.IntVar],
    b: Sequence[cp_model.IntVar],
) -> None:
    """Add the exact 504-row table forced by compression modulo three."""

    if len(a) != N or len(b) != N:
        raise ValueError("Legendre sequences must have length 333")
    compressed: list[cp_model.IntVar] = []
    for prefix, variables in (("a", a), ("b", b)):
        for residue in range(3):
            value = model.new_int_var(-21, 21, f"{prefix}_mod3_{residue}")
            # Each residue class has 111 signs, encoded with +1 as true.
            model.add(
                value
                == 2 * sum(variables[index] for index in range(residue, N, 3))
                - 111
            ).with_name(f"{prefix}_mod3_definition_{residue}")
            compressed.append(value)
    model.add_allowed_assignments(
        compressed, MOD3_COMPRESSION_TUPLES
    ).with_name("lp_mod3_compression")


def add_mod9_compression_equations(
    model: cp_model.CpModel,
    a: Sequence[cp_model.IntVar],
    b: Sequence[cp_model.IntVar],
) -> None:
    """Add the exact complementary PAF equations after compression to length 9.

    The two row-compressed vectors have combined PAF 594 at lag zero and -74
    at every nonzero lag.  Lag symmetry leaves five equations.  The zero-lag
    equation also bounds every odd row sum by 23, so the 90 small integer
    products have sharply bounded domains.
    """

    if len(a) != N or len(b) != N:
        raise ValueError("Legendre sequences must have length 333")
    row_compressions: list[list[cp_model.IntVar]] = []
    for prefix, variables in (("a", a), ("b", b)):
        rows: list[cp_model.IntVar] = []
        for residue in range(9):
            value = model.new_int_var(-23, 23, f"{prefix}_mod9_{residue}")
            model.add(
                value
                == 2 * sum(variables[index] for index in range(residue, N, 9))
                - 37
            ).with_name(f"{prefix}_mod9_definition_{residue}")
            rows.append(value)
        row_compressions.append(rows)

    for lag, target in ((0, 594), (1, -74), (2, -74), (3, -74), (4, -74)):
        products: list[cp_model.IntVar] = []
        for sequence_index, rows in enumerate(row_compressions):
            for row in range(9):
                lower = 0 if lag == 0 else -529
                product_variable = model.new_int_var(
                    lower, 529, f"mod9_product_{lag}_{sequence_index}_{row}"
                )
                model.add_multiplication_equality(
                    product_variable, [rows[row], rows[(row + lag) % 9]]
                )
                products.append(product_variable)
        model.add(sum(products) == target).with_name(f"lp_mod9_paf_{lag}")


def add_fixed_mod9_profile(
    model: cp_model.CpModel,
    a: Sequence[cp_model.IntVar],
    b: Sequence[cp_model.IntVar],
    profile: int,
) -> None:
    """Fix one exact length-9 compression profile with cardinalities.

    Every catalog entry already satisfies the complete compressed Legendre
    PAF equations.  Fixing its 18 row sums is therefore a stronger and much
    smaller replacement for both the generic mod-3 table and the 90 mod-9
    multiplication variables.  This defines a restricted exact sublane: a
    solution is still a genuine Legendre pair, while infeasibility applies
    only to the selected compressed-profile orbit.
    """

    if len(a) != N or len(b) != N:
        raise ValueError("Legendre sequences must have length 333")
    if not 0 <= profile < len(ROW_SUM_PROFILES):
        raise ValueError(
            f"mod9 profile must be in [0,{len(ROW_SUM_PROFILES) - 1}]"
        )
    for prefix, variables, row_sums in (
        ("a", a, ROW_SUM_PROFILES[profile][0]),
        ("b", b, ROW_SUM_PROFILES[profile][1]),
    ):
        for residue, row_sum in enumerate(row_sums):
            plus_count = (37 + row_sum) // 2
            model.add(
                sum(variables[index] for index in range(residue, N, 9))
                == plus_count
            ).with_name(f"{prefix}_fixed_mod9_profile_{profile}_{residue}")


def add_mod111_compression_equations(
    model: cp_model.CpModel,
    a: Sequence[cp_model.IntVar],
    b: Sequence[cp_model.IntVar],
    *,
    full: bool = False,
) -> None:
    """Add exact PAF equations after factor-three compression to length 111.

    If ``U[r] = X[r] + X[r+111] + X[r+222]``, compression of the LP PAF
    equations gives

        PAF(U_A, 0) + PAF(U_B, 0) = 662,
        PAF(U_A, s) + PAF(U_B, s) = -6  (1 <= s <= 55).

    The zero-lag equation alone is unusually small and integral: every
    compressed entry has square one or nine, so it is equivalent to exactly
    55 of the 222 source triples being monochromatic.  ``full=False`` adds
    only this energy equation; ``full=True`` adds all independent lags.
    These constraints are consequences of the full LP system, but expose
    useful propagation at a coarser scale.
    """

    if len(a) != N or len(b) != N:
        raise ValueError("Legendre sequences must have length 333")

    monochromatic: list[cp_model.IntVar] = []
    for prefix, variables in (("a", a), ("b", b)):
        for residue in range(111):
            same = model.new_bool_var(f"{prefix}_mod111_monochromatic_{residue}")
            model.add_allowed_assignments(
                [
                    variables[residue],
                    variables[residue + 111],
                    variables[residue + 222],
                    same,
                ],
                MONOCHROMATIC_TRIPLE_ROWS,
            ).with_name(f"{prefix}_mod111_monochromatic_table_{residue}")
            monochromatic.append(same)
    model.add(sum(monochromatic) == 55).with_name(
        "lp_mod111_monochromatic_count"
    )

    if not full:
        return

    compressed: list[list[cp_model.IntVar]] = []
    for prefix, variables in (("a", a), ("b", b)):
        values: list[cp_model.IntVar] = []
        for residue in range(111):
            value = model.new_int_var(-3, 3, f"{prefix}_mod111_{residue}")
            model.add(
                value
                == 2
                * sum(
                    variables[residue + 111 * block]
                    for block in range(3)
                )
                - 3
            ).with_name(f"{prefix}_mod111_definition_{residue}")
            values.append(value)
        compressed.append(values)

    for lag in range(1, 56):
        products: list[cp_model.IntVar] = []
        for sequence_index, values in enumerate(compressed):
            for residue in range(111):
                product_variable = model.new_int_var(
                    -9,
                    9,
                    f"mod111_product_{lag}_{sequence_index}_{residue}",
                )
                model.add_multiplication_equality(
                    product_variable,
                    [values[residue], values[(residue + lag) % 111]],
                )
                products.append(product_variable)
        model.add(sum(products) == -6).with_name(f"lp_mod111_paf_{lag}")


def add_xor_difference(
    model: cp_model.CpModel,
    left: cp_model.IntVar,
    right: cp_model.IntVar,
    name: str,
) -> cp_model.IntVar:
    """Return a Boolean variable equal to ``left XOR right``."""

    difference = model.new_bool_var(name)
    # BoolXOr requires odd parity.  x XOR y XOR (NOT d) is true exactly when
    # d == x XOR y.
    model.add_bool_xor([left, right, difference.negated()])
    return difference


def raw_column_distance_bounds(
    plus_counts: Sequence[int], lag: int
) -> tuple[int, int]:
    """Bound one sequence's cyclic Hamming distance from its column weights.

    For a nonzero column offset, two 9-bit columns of weights ``p`` and ``q``
    differ between ``abs(p-q)`` and ``min(p+q, 18-p-q)`` positions under any
    row matching.  When the offset is zero, a column is matched to its own
    cyclic row shift; exhaustive enumeration of the at most 512 column words
    gives the sharp weight-only bound.
    """

    if len(plus_counts) != 37:
        raise ValueError("expected 37 fixed column weights")
    if not 1 <= lag < N:
        raise ValueError(f"lag must be in [1,{N})")
    column_offset = lag % 37
    if column_offset:
        lower = 0
        upper = 0
        for column, weight in enumerate(plus_counts):
            shifted_weight = plus_counts[(column + column_offset) % 37]
            lower += abs(weight - shifted_weight)
            upper += min(weight + shifted_weight, 18 - weight - shifted_weight)
        return lower, upper

    row_shift = lag % 9
    if row_shift == 0:
        raise AssertionError("a nonzero lag below 333 cannot vanish modulo 333")
    per_weight: dict[int, tuple[int, int]] = {}
    for weight in set(plus_counts):
        distances: list[int] = []
        for support in combinations(range(9), weight):
            word = [False] * 9
            for row in support:
                word[row] = True
            distances.append(
                sum(word[row] != word[(row + row_shift) % 9] for row in range(9))
            )
        per_weight[weight] = (min(distances), max(distances))
    return (
        sum(per_weight[weight][0] for weight in plus_counts),
        sum(per_weight[weight][1] for weight in plus_counts),
    )


def fixed_compression_distance_bounds(
    lag: int,
) -> tuple[tuple[int, int], tuple[int, int]]:
    """Return target-tightened distance bounds for ``A`` and ``B`` at ``lag``."""

    a_lower, a_upper = raw_column_distance_bounds(FIXED_PLUS_COUNTS_A, lag)
    b_lower, b_upper = raw_column_distance_bounds(FIXED_PLUS_COUNTS_B, lag)
    target = N + 1
    return (
        (max(a_lower, target - b_upper), min(a_upper, target - b_lower)),
        (max(b_lower, target - a_upper), min(b_upper, target - a_lower)),
    )


def cyclic_shift_cycles(length: int, lag: int) -> tuple[tuple[int, ...], ...]:
    """Partition positions into the cycles of ``index -> index + lag``."""

    if length <= 0:
        raise ValueError("cycle length must be positive")
    if not 1 <= lag < length:
        raise ValueError(f"lag must be in [1,{length})")
    cycle_count = gcd(length, lag)
    cycle_length = length // cycle_count
    cycles: list[tuple[int, ...]] = []
    for start in range(cycle_count):
        cycle: list[int] = []
        index = start
        for _ in range(cycle_length):
            cycle.append(index)
            index = (index + lag) % length
        if index != start:
            raise AssertionError("shift-cycle construction did not close")
        cycles.append(tuple(cycle))
    if {index for cycle in cycles for index in cycle} != set(range(length)):
        raise AssertionError("shift cycles do not partition all positions")
    return tuple(cycles)


def add_cycle_parity_constraints(
    model: cp_model.CpModel,
    differences: Sequence[cp_model.IntVar],
    lag: int,
    total_half: cp_model.IntVar,
    prefix: str,
) -> None:
    """Expose even XOR weight on every cycle of a cyclic shift.

    Around one permutation cycle, XOR transitions return to the starting bit,
    so their cardinality is even.  When there is only one cycle, its half-
    distance is already ``total_half``; otherwise small per-cycle halves sum
    exactly to the global half-distance.
    """

    cycles = cyclic_shift_cycles(len(differences), lag)
    if len(cycles) == 1:
        model.add(sum(differences) == 2 * total_half).with_name(
            f"{prefix}_distance"
        )
        return

    cycle_halves: list[cp_model.IntVar] = []
    for cycle_index, cycle in enumerate(cycles):
        half = model.new_int_var(
            0, len(cycle) // 2, f"{prefix}_cycle_half_{cycle_index}"
        )
        model.add(
            sum(differences[index] for index in cycle) == 2 * half
        ).with_name(f"{prefix}_cycle_parity_{cycle_index}")
        cycle_halves.append(half)
    model.add(sum(cycle_halves) == total_half).with_name(
        f"{prefix}_cycle_halves"
    )


def add_exact_legendre_equations(
    model: cp_model.CpModel,
    a: Sequence[cp_model.IntVar],
    b: Sequence[cp_model.IntVar],
    last_lag: int = INDEPENDENT_LAGS,
    cycle_parity: bool = False,
) -> None:
    """Add every XOR-cardinality equation through ``last_lag``."""

    if len(a) != N or len(b) != N:
        raise ValueError("Legendre sequences must have length 333")
    if not 1 <= last_lag <= INDEPENDENT_LAGS:
        raise ValueError(f"last_lag must be in [1,{INDEPENDENT_LAGS}]")
    for lag in range(1, last_lag + 1):
        a_differences: list[cp_model.IntVar] = []
        b_differences: list[cp_model.IntVar] = []
        for index in range(N):
            shifted = (index + lag) % N
            a_differences.append(
                add_xor_difference(
                    model, a[index], a[shifted], f"a_diff_{lag}_{index}"
                )
            )
            b_differences.append(
                add_xor_difference(
                    model, b[index], b[shifted], f"b_diff_{lag}_{index}"
                )
            )
        (a_lower, a_upper), (b_lower, b_upper) = fixed_compression_distance_bounds(
            lag
        )
        # A cyclic Hamming distance is even: the XOR transitions around every
        # cycle of the shift permutation have even cardinality.  Exposing the
        # two half-distances makes that implicit parity available to the linear
        # propagator and lets the fixed-column bounds act before all XORs settle.
        a_half = model.new_int_var(
            (a_lower + 1) // 2, a_upper // 2, f"a_half_distance_{lag}"
        )
        b_half = model.new_int_var(
            (b_lower + 1) // 2, b_upper // 2, f"b_half_distance_{lag}"
        )
        if cycle_parity:
            add_cycle_parity_constraints(
                model, a_differences, lag, a_half, f"a_distance_{lag}"
            )
            add_cycle_parity_constraints(
                model, b_differences, lag, b_half, f"b_distance_{lag}"
            )
        else:
            model.add(sum(a_differences) == 2 * a_half).with_name(
                f"a_distance_{lag}"
            )
            model.add(sum(b_differences) == 2 * b_half).with_name(
                f"b_distance_{lag}"
            )
        model.add(a_half + b_half == (N + 1) // 2).with_name(f"lp_lag_{lag}")


def add_anchor_symmetry(
    model: cp_model.CpModel,
    a: Sequence[cp_model.IntVar],
    b: Sequence[cp_model.IntVar],
) -> None:
    """Use independent shifts by multiples of 37 to put +1 at CRT origin."""

    # Compression coordinate zero contains five +1s in each sequence, so an
    # independent shift through 37*t can always move one of them to index 0.
    model.add(a[0] == 1).with_name("a_origin_positive")
    model.add(b[0] == 1).with_name("b_origin_positive")


def add_dihedral_symmetry(
    model: cp_model.CpModel,
    variables: Sequence[cp_model.IntVar],
    prefix: str,
) -> None:
    """Choose a lexicographic maximum under the fixed-seed dihedral group."""

    original = list(variables)
    for row_shift in range(1, 9):
        add_lexicographic_greater_or_equal(
            model,
            original,
            shifted_image(variables, 37 * row_shift),
            f"{prefix}_rotation_{row_shift}",
        )
    inverted = inverted_image(variables)
    for row_shift in range(9):
        add_lexicographic_greater_or_equal(
            model,
            original,
            shifted_image(inverted, 37 * row_shift),
            f"{prefix}_reflection_{row_shift}",
        )


def add_hint(
    model: cp_model.CpModel,
    variables: Sequence[cp_model.IntVar],
    sequence: Sequence[int],
) -> None:
    for variable, sign in zip(variables, sequence, strict=True):
        model.add_hint(variable, int(sign == 1))


def load_search_hint(path: Path) -> tuple[tuple[int, ...], tuple[int, ...]]:
    """Load a hint, strictly auditing profile-checkpoint inputs first."""

    payload = json.loads(path.read_text(encoding="utf-8"))
    profile_markers = (
        isinstance(payload, dict)
        and (
            payload.get("kind") == PROFILE_CHECKPOINT_KIND
            or payload.get("parameterization") == PROFILE_PARAMETERIZATION
            or (
                "profile" in payload
                and "row_sums_a" in payload
                and "half_paf_residuals_1_through_166" in payload
            )
            or (
                isinstance(payload.get("schema"), str)
                and payload["schema"].startswith(
                    PROFILE_CHECKPOINT_SCHEMA.removesuffix("v1")
                )
            )
        )
    )
    if profile_markers:
        verify_profile_checkpoint(payload)
    return sequences_from_candidate(payload)


def canonicalize_hint(
    sequence: Sequence[int], symmetry: str
) -> tuple[int, ...]:
    """Move a sign hint into the selected fixed-compression symmetry chamber."""

    original = tuple(sequence)
    rotations = tuple(
        tuple(original[(index - 37 * row_shift) % N] for index in range(N))
        for row_shift in range(9)
    )
    if symmetry == "none":
        return original
    if symmetry == "anchor":
        # Any lexicographically maximal rotation starts with +1 because the
        # compression-zero column contains five positive entries.
        return max(rotations)
    if symmetry == "dihedral":
        inverted = tuple(original[-index % N] for index in range(N))
        reflected = tuple(
            tuple(inverted[(index - 37 * row_shift) % N] for index in range(N))
            for row_shift in range(9)
        )
        return max(rotations + reflected)
    raise ValueError("symmetry must be none, anchor, or dihedral")


def build_model(
    *,
    symmetry: str = "dihedral",
    last_lag: int = INDEPENDENT_LAGS,
    cycle_parity: bool = False,
    mod111_compression: str = "off",
    mod9_profile: int | None = None,
    hint: tuple[Sequence[int], Sequence[int]] | None = None,
) -> tuple[cp_model.CpModel, list[cp_model.IntVar], list[cp_model.IntVar]]:
    """Build the exact model and return it with the two primary sequences."""

    if symmetry not in {"none", "anchor", "dihedral"}:
        raise ValueError("symmetry must be none, anchor, or dihedral")
    if mod111_compression not in {"off", "energy", "full"}:
        raise ValueError("mod111_compression must be off, energy, or full")
    if mod9_profile is not None:
        if not 0 <= mod9_profile < len(ROW_SUM_PROFILES):
            raise ValueError(
                f"mod9 profile must be in [0,{len(ROW_SUM_PROFILES) - 1}]"
            )
        if symmetry != "none":
            raise ValueError(
                "a fixed mod9 profile requires --symmetry none; independent "
                "row shifts and reflections generally change its orientation"
            )
    model = cp_model.CpModel()
    a = [model.new_bool_var(f"a_{index}") for index in range(N)]
    b = [model.new_bool_var(f"b_{index}") for index in range(N)]

    add_fixed_column_margins(model, a, FIXED_PLUS_COUNTS_A, "a")
    add_fixed_column_margins(model, b, FIXED_PLUS_COUNTS_B, "b")
    if mod9_profile is None:
        add_mod3_compression_table(model, a, b)
        add_mod9_compression_equations(model, a, b)
    else:
        add_fixed_mod9_profile(model, a, b, mod9_profile)
    if mod111_compression != "off":
        add_mod111_compression_equations(
            model, a, b, full=mod111_compression == "full"
        )
    add_exact_legendre_equations(
        model, a, b, last_lag, cycle_parity=cycle_parity
    )

    if symmetry in {"anchor", "dihedral"}:
        add_anchor_symmetry(model, a, b)
    if symmetry == "dihedral":
        add_dihedral_symmetry(model, a, "a")
        add_dihedral_symmetry(model, b, "b")

    if hint is not None:
        hint_a, hint_b = hint
        fixed, _, _ = verify_fixed_compression(hint_a, hint_b)
        if not fixed:
            raise ValueError("hint does not have the prescribed length-37 compression")
        if mod9_profile is not None:
            hint_rows = tuple(
                tuple(sum(sequence[residue::9]) for residue in range(9))
                for sequence in (hint_a, hint_b)
            )
            if hint_rows != ROW_SUM_PROFILES[mod9_profile]:
                raise ValueError(
                    "hint does not have the selected fixed mod9 profile"
                )
        hint_a = canonicalize_hint(hint_a, symmetry)
        hint_b = canonicalize_hint(hint_b, symmetry)
        add_hint(model, a, hint_a)
        add_hint(model, b, hint_b)
    return model, a, b


def signs(
    solver: cp_model.CpSolver, variables: Sequence[cp_model.IntVar]
) -> tuple[int, ...]:
    return tuple(1 if solver.value(variable) else -1 for variable in variables)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--time-limit", type=float, default=3600.0)
    parser.add_argument("--workers", type=int, default=1)
    parser.add_argument(
        "--max-memory-mb",
        type=int,
        default=2048,
        help="CP-SAT memory cap in MiB (conservative default for a 16 GiB host)",
    )
    parser.add_argument("--random-seed", type=int, default=668)
    parser.add_argument("--log-search-progress", action="store_true")
    parser.add_argument(
        "--symmetry",
        choices=("none", "anchor", "dihedral"),
        default="dihedral",
    )
    parser.add_argument(
        "--hint",
        type=Path,
        help="candidate JSON used only as a CP-SAT solution hint",
    )
    parser.add_argument(
        "--repair-hint",
        action="store_true",
        help="ask CP-SAT to repair the non-solution hint before general search",
    )
    parser.add_argument(
        "--hint-conflict-limit",
        type=int,
        default=100,
        help="conflict allowance for hint repair (default 100)",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("output/legendre_pair_333.json"),
    )
    parser.add_argument(
        "--build-only",
        action="store_true",
        help="construct and validate the full model without invoking the solver",
    )
    parser.add_argument(
        "--presolve-only",
        action="store_true",
        help="stop CP-SAT after presolve; intended as a reproducibility smoke test",
    )
    parser.add_argument(
        "--diagnostic-last-lag",
        type=int,
        default=INDEPENDENT_LAGS,
        help=(
            "build only a prefix of lag equations for diagnostics; partial models "
            "can never write candidates"
        ),
    )
    parser.add_argument(
        "--cycle-parity",
        action="store_true",
        help=(
            "add experimental per-shift-cycle even-distance equations; exact but "
            "disabled by default because short benchmarks did not improve search"
        ),
    )
    parser.add_argument(
        "--mod111-compression",
        choices=("off", "energy", "full"),
        default="off",
        help=(
            "add exact factor-three compression constraints at length 111; "
            "energy adds only the 55-monochromatic-triples equation, while "
            "full adds all 56 compressed PAF equations"
        ),
    )
    parser.add_argument(
        "--mod9-profile",
        type=int,
        choices=range(len(ROW_SUM_PROFILES)),
        metavar=f"0..{len(ROW_SUM_PROFILES) - 1}",
        help=(
            "fix one catalogued exact length-9 profile; this restricted mode "
            "requires --symmetry none"
        ),
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    if args.time_limit <= 0:
        print("error: --time-limit must be positive", file=sys.stderr)
        return 2
    if args.workers <= 0:
        print("error: --workers must be positive", file=sys.stderr)
        return 2
    if args.max_memory_mb <= 0:
        print("error: --max-memory-mb must be positive", file=sys.stderr)
        return 2
    if args.hint_conflict_limit <= 0:
        print("error: --hint-conflict-limit must be positive", file=sys.stderr)
        return 2
    if args.repair_hint and args.hint is None:
        print("error: --repair-hint requires --hint", file=sys.stderr)
        return 2
    if not 1 <= args.diagnostic_last_lag <= INDEPENDENT_LAGS:
        print(
            f"error: --diagnostic-last-lag must be in [1,{INDEPENDENT_LAGS}]",
            file=sys.stderr,
        )
        return 2

    try:
        hint = load_search_hint(args.hint) if args.hint else None
        model, a_variables, b_variables = build_model(
            symmetry=args.symmetry,
            last_lag=args.diagnostic_last_lag,
            cycle_parity=args.cycle_parity,
            mod111_compression=args.mod111_compression,
            mod9_profile=args.mod9_profile,
            hint=hint,
        )
    except (OSError, ValueError, json.JSONDecodeError) as error:
        print(f"error={error}", file=sys.stderr)
        return 2

    validation_error = model.validate()
    print(model.model_stats())
    print(f"model_validation={'passed' if not validation_error else 'failed'}")
    if validation_error:
        print(validation_error, file=sys.stderr)
        return 2
    if args.diagnostic_last_lag != INDEPENDENT_LAGS:
        print(
            "warning=partial diagnostic model; omitted lag equations make it non-certifying"
        )
    if args.mod9_profile is not None:
        print(
            f"restriction=exact mod9 profile {args.mod9_profile}; "
            "infeasibility would apply only to this compressed-profile orbit"
        )
    if args.build_only:
        return 0

    print(f"workers={args.workers} max_memory_mb={args.max_memory_mb}")
    if args.hint is not None:
        print(
            f"hint={args.hint} repair_hint={args.repair_hint} "
            f"hint_conflict_limit={args.hint_conflict_limit}"
        )
    solver = cp_model.CpSolver()
    solver.parameters.max_time_in_seconds = args.time_limit
    solver.parameters.num_search_workers = args.workers
    solver.parameters.max_memory_in_mb = args.max_memory_mb
    solver.parameters.random_seed = args.random_seed
    solver.parameters.repair_hint = args.repair_hint
    solver.parameters.hint_conflict_limit = args.hint_conflict_limit
    solver.parameters.log_search_progress = args.log_search_progress
    solver.parameters.stop_after_presolve = args.presolve_only
    status = solver.solve(model)
    print(f"status={solver.status_name(status)}")
    print(f"wall_time={solver.wall_time:.3f}")
    print(f"conflicts={solver.num_conflicts}")
    print(f"branches={solver.num_branches}")

    if args.presolve_only:
        return 0
    if status not in (cp_model.FEASIBLE, cp_model.OPTIMAL):
        return 2
    if args.diagnostic_last_lag != INDEPENDENT_LAGS:
        print("partial diagnostic solutions are deliberately not written")
        return 0

    a = signs(solver, a_variables)
    b = signs(solver, b_variables)
    verification = verify_legendre_pair(a, b)
    if not verification.valid:
        print("error=solver candidate failed independent exact verification", file=sys.stderr)
        return 3
    save_verified_candidate(args.output, a, b)
    print(f"solution={args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
