#!/usr/bin/env python3
"""Verify the prime-163 obstruction to the two extreme profile sectors.

The order-three LP(333) profile equation is

    A A* + B B* = 167 delta_0

in ``Z[omega][F_37]^H``, where ``H=<10>={1,10,26}``, ``A(0)=-1``,
and ``B(0)=2``.  In either aggregate target with norm pair ``(163,4)``,
the extreme channel-energy allocation makes ``B=2 delta_0`` and hence

    A A* = 163 delta_0.

The accompanying theorem proves that no such ``A`` exists.  This verifier
uses only exact integer arithmetic and the Python standard library.  It
checks the finite arithmetic behind the cyclotomic inertness argument, the
Eisenstein prime generators, the fixed roots of unity, the Fourier
inequality, and the exact profile/local-sieve sector census.
"""

from __future__ import annotations

from collections import defaultdict
from hashlib import sha256
from itertools import product
import json
from math import gcd, isqrt
from typing import Iterable, Sequence


COLUMN_PRIME = 37
ENERGY_PRIME = 163
TOTAL_ENERGY = 167
H = (1, 10, 26)
OMEGA_UNITS = (
    (1, 0),
    (-1, 0),
    (0, 1),
    (0, -1),
    (1, 1),
    (-1, -1),
)
PI = (14, 3)
PI_BAR = (11, -3)
TARGET_MINUS = (4, -1, 0, 0)
TARGET_PLUS = (5, 1, 0, 0)
EXTREME_TARGETS = (TARGET_MINUS, TARGET_PLUS)
PROFILE_NORM_TOTAL = 54
ZERO_PROFILE_ID = 5

Eisenstein = tuple[int, int]  # a+b*omega, omega^2+omega+1=0.
Target = tuple[int, int, int, int]

EXPECTED_FIELD_CERTIFICATE_SHA256 = (
    "eb426aa6d4b04a7ba46b8fbd19344c4f02061f7df5991c7f7ea1701090ff375d"
)
EXPECTED_UNIT_CERTIFICATE_SHA256 = (
    "9d4d129edf16ad439ddddd0dfda593429576e7206fd6d380cabedf848a075549"
)
EXPECTED_FOURIER_CERTIFICATE_SHA256 = (
    "1e9dcad7ac903b7f962da4a53d384db626fb98ca5104e70370aa4b2be564a133"
)
EXPECTED_SECTOR_CERTIFICATE_SHA256 = (
    "474131d5bdb924a3f6ebe404528fa82085ff881ab38103d919c60123d6559594"
)
EXPECTED_MASTER_CERTIFICATE_SHA256 = (
    "631649252c20db62a2bd0b2200c588708b07b9eb94fa350b73cd7f3c3865f191"
)


def compact_hash(value: object) -> str:
    payload = json.dumps(value, separators=(",", ":"), sort_keys=True)
    return sha256(payload.encode("ascii")).hexdigest()


def require_hash(label: str, value: object, expected: str) -> str:
    actual = compact_hash(value)
    if expected and actual != expected:
        raise AssertionError(f"{label} hash changed: {actual} != {expected}")
    return actual


def e_add(left: Eisenstein, right: Eisenstein) -> Eisenstein:
    return left[0] + right[0], left[1] + right[1]


def e_scale(factor: int, value: Eisenstein) -> Eisenstein:
    return factor * value[0], factor * value[1]


def e_multiply(left: Eisenstein, right: Eisenstein) -> Eisenstein:
    a, b = left
    c, d = right
    return a * c - b * d, a * d + b * c - b * d


def e_conjugate(value: Eisenstein) -> Eisenstein:
    return value[0] - value[1], -value[1]


def e_norm(value: Eisenstein) -> int:
    a, b = value
    return a * a - a * b + b * b


def is_prime(value: int) -> bool:
    if value < 2:
        return False
    for divisor in range(2, isqrt(value) + 1):
        if value % divisor == 0:
            return False
    return True


def multiplicative_order(value: int, modulus: int) -> int:
    if gcd(value, modulus) != 1:
        raise ValueError("the residue must be invertible")
    current = 1
    for exponent in range(1, modulus):
        current = current * value % modulus
        if current == 1:
            return exponent
    raise AssertionError("multiplicative order search did not terminate")


def quotient_order(value: int, modulus: int, subgroup: Iterable[int]) -> int:
    subgroup_set = {member % modulus for member in subgroup}
    current = 1
    for exponent in range(1, modulus):
        current = current * value % modulus
        if current in subgroup_set:
            return exponent
    raise AssertionError("quotient order search did not terminate")


def verify_field_arithmetic() -> dict[str, object]:
    if not is_prime(COLUMN_PRIME) or not is_prime(ENERGY_PRIME):
        raise AssertionError("one of the two rational primes changed")
    if set(H) != {
        pow(10, exponent, COLUMN_PRIME) for exponent in range(3)
    }:
        raise AssertionError("H is not the subgroup generated by 10")
    if pow(10, 3, COLUMN_PRIME) != 1:
        raise AssertionError("10 no longer has order three modulo 37")

    order = multiplicative_order(ENERGY_PRIME, COLUMN_PRIME)
    order_mod_h = quotient_order(ENERGY_PRIME, COLUMN_PRIME, H)
    if (order, order_mod_h) != (36, 12):
        raise AssertionError("the prime-163 Frobenius orders changed")

    if e_conjugate(PI) != PI_BAR:
        raise AssertionError("the two Eisenstein generators are not conjugate")
    if e_norm(PI) != ENERGY_PRIME:
        raise AssertionError("pi no longer has Eisenstein norm 163")
    if e_multiply(PI, PI_BAR) != (ENERGY_PRIME, 0):
        raise AssertionError("pi*pi_bar is not 163")
    if ENERGY_PRIME % 3 != 1:
        raise AssertionError("163 no longer splits in Q(omega)")

    # Standard cyclotomic prime decomposition now gives two primes in
    # L=Q(omega,zeta_37)^H.  Each is inert of relative degree 12 over
    # Q(omega), and the displayed generators prove principality directly.
    prime_absolute_norm = ENERGY_PRIME**12
    certificate = (
        COLUMN_PRIME,
        ENERGY_PRIME,
        H,
        order,
        order_mod_h,
        PI,
        PI_BAR,
        e_multiply(PI, PI_BAR),
        prime_absolute_norm,
        (1, 12),
        (1, 12),
    )
    certificate_hash = require_hash(
        "field arithmetic", certificate, EXPECTED_FIELD_CERTIFICATE_SHA256
    )
    return {
        "full_frobenius_order": order,
        "quotient_frobenius_order": order_mod_h,
        "degree_L_over_Q_omega": 12,
        "degree_L_over_Q": 24,
        "primes_above_163": 2,
        "ramification_indices": (1, 1),
        "residue_degrees": (12, 12),
        "prime_absolute_norms": (
            prime_absolute_norm,
            prime_absolute_norm,
        ),
        "principal_generators": (PI, PI_BAR),
        "class_group_computation_needed": False,
        "certificate_sha256": certificate_hash,
    }


def norm_solutions(norm: int) -> tuple[Eisenstein, ...]:
    # 4*N(a+b*omega)=(2a-b)^2+3b^2, and symmetrically in a,b.
    coordinate_bound = isqrt(4 * norm // 3) + 1
    return tuple(
        sorted(
            (a, b)
            for a in range(-coordinate_bound, coordinate_bound + 1)
            for b in range(-coordinate_bound, coordinate_bound + 1)
            if e_norm((a, b)) == norm
        )
    )


def verify_unit_rigidity() -> dict[str, object]:
    if len(set(OMEGA_UNITS)) != 6:
        raise AssertionError("the Eisenstein unit list has a duplicate")
    if any(e_norm(unit) != 1 for unit in OMEGA_UNITS):
        raise AssertionError("an alleged Eisenstein unit has nonunit norm")

    pi_orbits = {
        e_multiply(unit, generator)
        for unit, generator in product(OMEGA_UNITS, (PI, PI_BAR))
    }
    solutions = set(norm_solutions(ENERGY_PRIME))
    if solutions != pi_orbits or len(solutions) != 12:
        raise AssertionError("the norm-163 Eisenstein elements changed")

    # Q(omega,zeta_37) is Q(zeta_111).  Its roots of unity may be written
    # uniquely as zeta_37^a*zeta_6^b.  H fixes the zeta_6 coordinate and
    # multiplies a by each member of H.  The fixed roots are exactly mu_6.
    fixed_root_pairs = tuple(
        (a, b)
        for a in range(COLUMN_PRIME)
        for b in range(6)
        if all((member - 1) * a % COLUMN_PRIME == 0 for member in H)
    )
    if fixed_root_pairs != tuple((0, b) for b in range(6)):
        raise AssertionError("the H-fixed roots of unity are not mu_6")

    certificate = (
        OMEGA_UNITS,
        tuple(sorted(solutions)),
        fixed_root_pairs,
        gcd(10 - 1, COLUMN_PRIME),
    )
    certificate_hash = require_hash(
        "unit rigidity", certificate, EXPECTED_UNIT_CERTIFICATE_SHA256
    )
    return {
        "roots_of_unity_in_L": 6,
        "norm_163_eisenstein_elements": tuple(sorted(solutions)),
        "norm_163_eisenstein_element_count": len(solutions),
        "kronecker_kernel": "u*conjugate(u)=1 implies u in mu_6",
        "certificate_sha256": certificate_hash,
    }


def target_spectral_values(target: Sequence[int]) -> tuple[Eisenstein, Eisenstein]:
    if len(target) != 4:
        raise ValueError("an aggregate target must have four coordinates")
    first, second, third, fourth = target
    return (-1 + 3 * first, 3 * second), (2 + 3 * third, 3 * fourth)


def verify_fourier_obstruction() -> dict[str, object]:
    target_values = tuple(
        (target, *target_spectral_values(target))
        for target in EXTREME_TARGETS
    )
    if target_values != (
        (TARGET_MINUS, PI_BAR, (2, 0)),
        (TARGET_PLUS, PI, (2, 0)),
    ):
        raise AssertionError("the two extreme aggregate values changed")

    norm_values = norm_solutions(ENERGY_PRIME)
    impossible_pairs = []
    for trivial_value in norm_values:
        for primitive_value in norm_values:
            fourier_sum = e_add(
                trivial_value, e_scale(COLUMN_PRIME - 1, primitive_value)
            )
            if fourier_sum == (-COLUMN_PRIME, 0):
                impossible_pairs.append((trivial_value, primitive_value))
    if impossible_pairs:
        raise AssertionError("a forbidden Fourier pair unexpectedly exists")

    lower_bound_squared = (COLUMN_PRIME - 2) ** 2 * ENERGY_PRIME
    target_squared = COLUMN_PRIME**2
    if lower_bound_squared <= target_squared:
        raise AssertionError("the exact reverse-triangle gap disappeared")

    certificate = (
        target_values,
        norm_values,
        tuple(impossible_pairs),
        lower_bound_squared,
        target_squared,
    )
    certificate_hash = require_hash(
        "Fourier obstruction",
        certificate,
        EXPECTED_FOURIER_CERTIFICATE_SHA256,
    )
    return {
        "extreme_targets": EXTREME_TARGETS,
        "target_spectral_values": target_values,
        "primitive_fourier_values_forced_constant": True,
        "fourier_zero_coefficient_identity": "S+36*q=-37",
        "reverse_triangle_lower_bound_squared": lower_bound_squared,
        "required_value_squared": target_squared,
        "candidate_pairs": len(norm_values) ** 2,
        "candidate_pairs_satisfying_identity": 0,
        "certificate_sha256": certificate_hash,
    }


def profiles() -> tuple[tuple[int, int, int], ...]:
    result = tuple(
        (first, second, 3 - first - second)
        for first in range(4)
        for second in range(4)
        if 0 <= 3 - first - second <= 3
    )
    if len(result) != 10:
        raise AssertionError("the profile alphabet no longer has ten states")
    return result


PROFILES = profiles()


def profile_value(profile_id: int) -> Eisenstein:
    first, second, third = PROFILES[profile_id]
    return first - third, second - third


def signed_profile_value(
    channel: int, class_index: int, profile_id: int
) -> Eisenstein:
    if channel not in (0, 1):
        raise ValueError("the channel must be zero or one")
    epsilon = 1 if class_index % 2 == 0 else -1
    factor = -epsilon if channel == 0 else epsilon
    return e_scale(factor, profile_value(profile_id))


def pair_signature(left_id: int, right_id: int) -> Eisenstein:
    left = profile_value(left_id)
    right = profile_value(right_id)
    return (
        (left[0] - left[1] + right[0]) % 3,
        (-left[1] + right[1]) % 3,
    )


def unrestricted_channel_dp() -> dict[tuple[int, int, int], int]:
    states: dict[tuple[int, int, int], int] = {(0, 0, 0): 1}
    for class_index in range(12):
        next_states: dict[tuple[int, int, int], int] = defaultdict(int)
        for (real, omega, energy), count in states.items():
            for profile_id in range(len(PROFILES)):
                value = signed_profile_value(0, class_index, profile_id)
                key = (
                    real + value[0],
                    omega + value[1],
                    energy + e_norm(value),
                )
                next_states[key] += count
        states = dict(next_states)
    if sum(states.values()) != 10**12:
        raise AssertionError("the unrestricted twelve-profile DP lost words")
    return states


def zero_other_channel_local_dp() -> tuple[
    dict[tuple[int, int, int], int], tuple[tuple[int, int], ...]
]:
    zero_signature = pair_signature(ZERO_PROFILE_ID, ZERO_PROFILE_ID)
    allowed_pairs = tuple(
        (left, right)
        for left in range(len(PROFILES))
        for right in range(len(PROFILES))
        if pair_signature(left, right) == zero_signature
    )
    if len(allowed_pairs) != 34:
        raise AssertionError("the zero-signature pair bucket changed")

    states: dict[tuple[int, int, int], int] = {(0, 0, 0): 1}
    for pair_index in range(6):
        next_states: dict[tuple[int, int, int], int] = defaultdict(int)
        for (real, omega, energy), count in states.items():
            for left_id, right_id in allowed_pairs:
                left = signed_profile_value(0, pair_index, left_id)
                right = signed_profile_value(0, pair_index + 6, right_id)
                key = (
                    real + left[0] + right[0],
                    omega + left[1] + right[1],
                    energy + e_norm(left) + e_norm(right),
                )
                next_states[key] += count
        states = dict(next_states)
    if sum(states.values()) != 34**6:
        raise AssertionError("the six-pair local DP lost assignments")
    return states, allowed_pairs


NONEXTREME_LOCAL_WITNESSES: tuple[
    tuple[Target, tuple[int, ...], tuple[int, ...]], ...
] = (
    (
        TARGET_MINUS,
        (5, 5, 2, 5, 5, 5, 5, 9, 5, 5, 5, 5),
        (0, 0, 1, 5, 5, 5, 5, 3, 2, 5, 5, 0),
    ),
    (
        TARGET_PLUS,
        (5, 5, 5, 5, 5, 8, 5, 5, 5, 9, 5, 5),
        (3, 5, 9, 5, 0, 6, 5, 5, 5, 5, 3, 2),
    ),
)


def audit_local_witness(
    target: Target, identifiers_a: Sequence[int], identifiers_b: Sequence[int]
) -> tuple[int, int]:
    if len(identifiers_a) != 12 or len(identifiers_b) != 12:
        raise AssertionError("a local witness has the wrong length")
    aggregate = []
    profile_energies = []
    for channel, identifiers in enumerate((identifiers_a, identifiers_b)):
        total = (0, 0)
        energy = 0
        for class_index, profile_id in enumerate(identifiers):
            value = signed_profile_value(channel, class_index, profile_id)
            total = e_add(total, value)
            energy += e_norm(value)
        aggregate.extend(total)
        profile_energies.append(energy)
    if tuple(aggregate) != target:
        raise AssertionError("a local witness has the wrong aggregate")
    if sum(profile_energies) != PROFILE_NORM_TOTAL:
        raise AssertionError("a local witness has the wrong total profile norm")
    for pair_index in range(6):
        if pair_signature(
            identifiers_a[pair_index], identifiers_a[pair_index + 6]
        ) != pair_signature(
            identifiers_b[pair_index], identifiers_b[pair_index + 6]
        ):
            raise AssertionError("a local witness fails an opposite-pair sieve")
    return 1 + 3 * profile_energies[0], 4 + 3 * profile_energies[1]


def verify_extreme_sector_census() -> dict[str, object]:
    if profile_value(ZERO_PROFILE_ID) != (0, 0):
        raise AssertionError("the unique zero profile moved")
    if sum(profile_value(index) == (0, 0) for index in range(10)) != 1:
        raise AssertionError("the profile alphabet does not have one zero")
    physical_extreme_energies = (
        1 + 3 * PROFILE_NORM_TOTAL,
        e_norm((2, 0)),
    )
    if physical_extreme_energies != (163, 4):
        raise AssertionError("the extreme physical energies changed")
    if sum(physical_extreme_energies) != TOTAL_ENERGY:
        raise AssertionError("the extreme energies no longer sum to 167")

    unrestricted = unrestricted_channel_dp()
    local, allowed_pairs = zero_other_channel_local_dp()
    target_counts = []
    for target in EXTREME_TARGETS:
        key = (target[0], target[1], PROFILE_NORM_TOTAL)
        target_counts.append(
            (
                target,
                unrestricted.get(key, 0),
                local.get(key, 0),
            )
        )
    expected_counts = (
        (TARGET_MINUS, 1_151_042_580, 1_617_192),
        (TARGET_PLUS, 1_151_042_580, 1_617_192),
    )
    if tuple(target_counts) != expected_counts:
        raise AssertionError("the two extreme-sector counts changed")

    nonextreme = tuple(
        (target, audit_local_witness(target, identifiers_a, identifiers_b))
        for target, identifiers_a, identifiers_b in NONEXTREME_LOCAL_WITNESSES
    )
    if nonextreme != (
        (TARGET_MINUS, (37, 130)),
        (TARGET_PLUS, (37, 130)),
    ):
        raise AssertionError("the nonextreme local witnesses changed")

    certificate = (
        tuple((profile_value(index), e_norm(profile_value(index))) for index in range(10)),
        len(unrestricted),
        sum(unrestricted.values()),
        len(local),
        len(allowed_pairs),
        sum(local.values()),
        tuple(target_counts),
        physical_extreme_energies,
        NONEXTREME_LOCAL_WITNESSES,
        nonextreme,
    )
    certificate_hash = require_hash(
        "extreme-sector census",
        certificate,
        EXPECTED_SECTOR_CERTIFICATE_SHA256,
    )
    return {
        "extreme_targets": EXTREME_TARGETS,
        "extreme_physical_channel_energies": physical_extreme_energies,
        "zero_channel_profile_assignment_count": 1,
        "unrestricted_channel_dp_states": len(unrestricted),
        "unrestricted_channel_words": sum(unrestricted.values()),
        "zero_signature_pair_bucket": len(allowed_pairs),
        "local_sieve_dp_states": len(local),
        "local_sieve_words": sum(local.values()),
        "target_counts": tuple(target_counts),
        "extreme_assignments_excluded_per_target": 1_617_192,
        "extreme_assignments_excluded_total": 3_234_384,
        "nonextreme_local_witness_physical_energies": nonextreme,
        "aggregate_shards_excluded": 0,
        "certificate_sha256": certificate_hash,
    }


def verify() -> dict[str, object]:
    result = {
        "field": verify_field_arithmetic(),
        "units": verify_unit_rigidity(),
        "fourier": verify_fourier_obstruction(),
        "sectors": verify_extreme_sector_census(),
    }
    master_payload = tuple(
        result[key]["certificate_sha256"]
        for key in ("field", "units", "fourier", "sectors")
    )
    result["master_certificate_sha256"] = require_hash(
        "master", master_payload, EXPECTED_MASTER_CERTIFICATE_SHA256
    )
    result["status"] = (
        "the two B=2*delta_0, A-energy-163 profile sectors are impossible; "
        "other energy sectors remain in both aggregate shards"
    )
    return result


def main() -> None:
    result = verify()
    field = result["field"]
    fourier = result["fourier"]
    sectors = result["sectors"]
    print(f"primes_above_163={field['primes_above_163']}")
    print(f"residue_degrees={field['residue_degrees']}")
    print(f"principal_generators={field['principal_generators']}")
    print(
        "reverse_triangle_gap="
        f"{fourier['reverse_triangle_lower_bound_squared']}>"
        f"{fourier['required_value_squared']}"
    )
    print(f"extreme_target_counts={sectors['target_counts']}")
    print(
        "extreme_assignments_excluded_total="
        f"{sectors['extreme_assignments_excluded_total']}"
    )
    print(
        "aggregate_shards_excluded="
        f"{sectors['aggregate_shards_excluded']}"
    )
    print(
        "master_certificate_sha256="
        f"{result['master_certificate_sha256']}"
    )
    print("PASS: prime-163 extreme-sector obstruction replayed exactly")
    print("STATUS: two target/energy sectors excluded; no whole shard excluded")


if __name__ == "__main__":
    main()
