#!/usr/bin/env python3
from fractions import Fraction as F
# Old arrangement inside Q=(-2,2)^2 generated by x=0 and y=0.
# Selector U={x+y>1/2}. Candidate polytope is the same halfspace clipped by Q.
# Test full-dimensional, lower-dimensional, tangent, outside, and split representatives.
pts={
 'inside_Q1':(F(1),F(1)),
 'outside_Q3':(F(-1),F(-1)),
 'split_in':(F(1),F(-1,4)),
 'split_out':(F(1,4),F(0)),
 'lower_inside':(F(1),F(0)),
 'lower_outside':(F(0),F(1,4)),
 'tangent':(F(1,2),F(0)),
}
def U(p): return p[0]+p[1] > F(1,2)
def P(p): return p[0]+p[1] > F(1,2)
assert all(U(p)==P(p) for p in pts.values())
assert U(pts['inside_Q1']) and not U(pts['outside_Q3'])
assert U(pts['split_in']) and not U(pts['split_out'])
assert U(pts['lower_inside']) and not U(pts['lower_outside'])
assert not U(pts['tangent']) # strict boundary, closure contact
# The retained separator is strict on all selector points and weak at outside witnesses.
for name in ('inside_Q1','split_in','lower_inside'):
    assert pts[name][0]+pts[name][1] > F(1,2)
for name in ('outside_Q3','split_out','lower_outside','tangent'):
    assert pts[name][0]+pts[name][1] <= F(1,2)
print('FIXED-ARRANGEMENT CELL CLASSIFICATION PASS')
print('LOWER-DIMENSIONAL AND TANGENT CELLS PASS')
print('STRICT/WEAK SEPARATION PASS')
