#!/usr/bin/env python3
"""Exact verifier for the root-spanning simple four-leaf JC atlas.

The finite slice consists of every binary strongly tree-child expansion of a
level-2 theta core having four labelled outgoing ports and a root in the
blob.  The verifier:

* regenerates all 27 unlabelled and 612 leaf-labelled rooted networks;
* forms the equivalence components generated by reversible root placement,
  triangle redirection T, Theta, Psi, and Omega;
* computes every generic model dimension by exact symbolic Jacobian
  elimination over Q;
* proves that six S4-orbits of exact invariants give different signatures to
  all 108 move components; and
* records, without overclaiming, the remaining one-sided containments not
  settled by these degree-at-most-five certificates.

Finite-field discovery is not used here.  Every zero test is an exact
multivariate-polynomial identity over Q.
"""

from __future__ import annotations

import argparse
from collections import Counter, defaultdict
from fractions import Fraction
from functools import reduce
from hashlib import sha256
from itertools import combinations, permutations, product
import json
from math import gcd, lcm
from pathlib import Path

from flint import fmpq, fmpq_mpoly_ctx

from enumerate_four_leaf_root_theta import (
    canonical_code,
    enumerate_networks,
    labelled_canonical_codes,
)
from generic_fourier_network import evaluate_jc_coordinates, reticulation_vertices
from jc_root_spanning_atlas_data import (
    DIRECTED_TEMPLATE,
    INVARIANT_TEMPLATES,
    NETWORK_DIMENSIONS,
)
from probe_four_leaf_jc_atlas import JC_REPRESENTATIVES, coordinate_permutation
from verify_jc_four_network_class import (
    colored_graph_isomorphisms,
    semi_directed_graph,
)


HERE = Path(__file__).resolve().parent.parent
CERTIFICATE = HERE / "certificates" / "jc_root_spanning_atlas.json"


class DisjointSet:
    def __init__(self, size):
        self.parent = list(range(size))

    def find(self, item):
        while self.parent[item] != item:
            self.parent[item] = self.parent[self.parent[item]]
            item = self.parent[item]
        return item

    def union(self, first, second):
        first = self.find(first)
        second = self.find(second)
        if first != second:
            self.parent[second] = first


def canonical_colored_graph(graph, ignore_internal=False, ignore_edge_type=False):
    colors, edges = graph
    colors = {
        vertex: ("I" if ignore_internal and not color.startswith("L") else color)
        for vertex, color in colors.items()
    }
    groups = defaultdict(list)
    for vertex, color in colors.items():
        groups[color].append(vertex)
    keys = sorted(groups)
    signature = tuple((key, len(groups[key])) for key in keys)
    starts = {}
    current = 0
    for key in keys:
        starts[key] = current
        current += len(groups[key])

    best = None
    for choices in product(*(permutations(groups[key]) for key in keys)):
        mapping = {
            vertex: starts[key] + index
            for key, choice in zip(keys, choices)
            for index, vertex in enumerate(choice)
        }
        image = []
        for edge_type, left, right in edges:
            left, right = mapping[left], mapping[right]
            if ignore_edge_type or edge_type == "U":
                left, right = sorted((left, right))
            image.append(("U" if ignore_edge_type else edge_type, left, right))
        image = tuple(sorted(image))
        if best is None or image < best:
            best = image
    return signature, best


def triangles(graph):
    colors, edges = graph
    undirected = {frozenset((left, right)) for _kind, left, right in edges}
    internal = [vertex for vertex, color in colors.items() if not color.startswith("L")]
    return [
        set(triple)
        for triple in combinations(internal, 3)
        if all(frozenset(edge) in undirected for edge in combinations(triple, 2))
    ]


def underlying_graph(graph):
    colors, edges = graph
    return (
        {
            vertex: (color if color.startswith("L") else "I")
            for vertex, color in colors.items()
        },
        tuple(
            sorted(("U",) + tuple(sorted((left, right))) for _kind, left, right in edges)
        ),
    )


def directed_edges(graph):
    return {(left, right) for kind, left, right in graph[1] if kind == "D"}


def is_triangle_redirection(first, second):
    first_triangles = triangles(first)
    second_triangles = triangles(second)
    if len(first_triangles) != 1 or len(second_triangles) != 1:
        return False
    first_triangle = first_triangles[0]
    second_triangle = second_triangles[0]
    for mapping in colored_graph_isomorphisms(
        underlying_graph(first), underlying_graph(second)
    ):
        if {mapping[vertex] for vertex in first_triangle} != second_triangle:
            continue
        transported = {
            (mapping[left], mapping[right])
            for left, right in directed_edges(first)
            if {left, right} - first_triangle
        }
        target = {
            edge for edge in directed_edges(second) if set(edge) - second_triangle
        }
        if transported == target:
            return True
    return False


def labelled_items(networks):
    items = []
    rooted_code_to_item = {}
    for network_index, network in enumerate(networks):
        edges = tuple(tuple(edge) for edge in network["edges"])
        leaves = tuple(network["leaves"])
        assignments = labelled_canonical_codes(network["vertices"], edges, leaves)
        for assignment in assignments.values():
            labels = tuple(assignment[leaf] for leaf in leaves)
            item = (network_index, labels)
            items.append(item)
            code = canonical_code(
                network["vertices"], edges, dict(zip(leaves, labels))
            )
            rooted_code_to_item[code] = item
    assert len(items) == 612 == len(rooted_code_to_item)
    return tuple(sorted(items)), rooted_code_to_item


def canonical_item(networks, rooted_code_to_item, item):
    network_index, labels = item
    network = networks[network_index]
    code = canonical_code(
        network["vertices"],
        tuple(tuple(edge) for edge in network["edges"]),
        dict(zip(network["leaves"], labels)),
    )
    return rooted_code_to_item[code]


def item_action(networks, rooted_code_to_item, item, permutation):
    network_index, labels = item
    return canonical_item(
        networks,
        rooted_code_to_item,
        (network_index, tuple(permutation[label - 1] for label in labels)),
    )


def move_components(networks):
    items, rooted_code_to_item = labelled_items(networks)
    item_index = {item: index for index, item in enumerate(items)}
    semi_graphs = [semi_directed_graph(networks[index], labels) for index, labels in items]
    disjoint = DisjointSet(len(items))

    semi_groups = defaultdict(list)
    for index, graph in enumerate(semi_graphs):
        semi_groups[canonical_colored_graph(graph)].append(index)
    assert len(semi_groups) == 216
    assert Counter(map(len, semi_groups.values())) == {2: 108, 1: 48, 5: 36, 7: 24}
    for group in semi_groups.values():
        for index in group[1:]:
            disjoint.union(group[0], index)

    underlying_groups = defaultdict(list)
    for group in semi_groups.values():
        representative = group[0]
        key = canonical_colored_graph(
            semi_graphs[representative], ignore_internal=True, ignore_edge_type=True
        )
        underlying_groups[key].append(representative)
    triangle_edges = 0
    for group in underlying_groups.values():
        for first, second in combinations(group, 2):
            if is_triangle_redirection(semi_graphs[first], semi_graphs[second]):
                disjoint.union(first, second)
                triangle_edges += 1
    assert triangle_edges == 60

    def add_orbit_edge(first, second):
        for permutation in permutations((1, 2, 3, 4)):
            disjoint.union(
                item_index[item_action(networks, rooted_code_to_item, first, permutation)],
                item_index[item_action(networks, rooted_code_to_item, second, permutation)],
            )

    # The three non-T root-local moves already have independent exact
    # stochastic-overlap verifiers.
    add_orbit_edge((0, (1, 2, 3, 4)), (13, (2, 1, 3, 4)))  # Theta
    psi = (
        (18, (1, 2, 3, 4)),
        (18, (3, 2, 1, 4)),
        (19, (2, 1, 3, 4)),
        (19, (2, 3, 1, 4)),
    )
    for target in psi[1:]:
        add_orbit_edge(psi[0], target)
    add_orbit_edge((16, (1, 2, 3, 4)), (16, (2, 1, 4, 3)))  # Omega

    components = defaultdict(list)
    for index, item in enumerate(items):
        components[disjoint.find(index)].append(item)
    components = tuple(
        sorted(
            (tuple(sorted(component)) for component in components.values()),
            key=lambda component: component[0],
        )
    )
    assert len(components) == 108
    assert Counter(map(len, components)) == {
        2: 36,
        4: 24,
        5: 12,
        7: 12,
        8: 12,
        17: 12,
    }
    return {
        "items": items,
        "rooted_code_to_item": rooted_code_to_item,
        "semi_graphs": semi_graphs,
        "components": components,
        "triangle_redirection_edges": triangle_edges,
        "semi_class_count": len(semi_groups),
        "semi_class_size_distribution": Counter(map(len, semi_groups.values())),
    }


def normalized_candidate(candidate):
    combined = defaultdict(Fraction)
    for monomial, coefficient in candidate:
        combined[tuple(sorted(monomial))] += Fraction(coefficient)
    combined = {
        monomial: coefficient for monomial, coefficient in combined.items() if coefficient
    }
    denominator = reduce(
        lcm, (coefficient.denominator for coefficient in combined.values()), 1
    )
    integers = {
        monomial: int(coefficient * denominator)
        for monomial, coefficient in combined.items()
    }
    divisor = reduce(gcd, (abs(value) for value in integers.values()))
    ordered = tuple(sorted((monomial, value // divisor) for monomial, value in integers.items()))
    if ordered[0][1] < 0:
        ordered = tuple((monomial, -coefficient) for monomial, coefficient in ordered)
    return ordered


def invariant_orbit(candidate):
    images = set()
    for permutation in permutations((1, 2, 3, 4)):
        coordinate_map = coordinate_permutation(permutation)
        image = (
            (tuple(sorted(coordinate_map[index] for index in monomial)), coefficient)
            for monomial, coefficient in candidate
        )
        images.add(normalized_candidate(tuple(image)))
    return tuple(sorted(images))


class ExactModels:
    def __init__(self, networks):
        self.networks = networks
        self.base = {}

    def coordinates(self, item):
        network_index, labels = item
        if network_index not in self.base:
            network = self.networks[network_index]
            edges = tuple(tuple(edge) for edge in network["edges"])
            reticulations = reticulation_vertices(network["vertices"])
            context = fmpq_mpoly_ctx.get(
                [
                    f"atlas_n{network_index}_p{index}"
                    for index in range(len(edges) + len(reticulations))
                ]
            )
            parameters = context.gens()
            coordinates = evaluate_jc_coordinates(
                network["vertices"],
                edges,
                dict(zip(network["leaves"], (1, 2, 3, 4))),
                JC_REPRESENTATIVES,
                parameters[: len(edges)],
                dict(zip(reticulations, parameters[len(edges) :])),
            )
            self.base[network_index] = (context, coordinates)
        context, base = self.base[network_index]
        coordinate_map = coordinate_permutation(labels)
        return context, tuple(base[index] for index in coordinate_map)


def exact_pullback(candidate, item, models):
    context, coordinates = models.coordinates(item)
    answer = context.constant(0)
    for monomial, coefficient in candidate:
        term = context.constant(coefficient)
        for coordinate in monomial:
            term *= coordinates[coordinate]
        answer += term
    return answer


def fraction_free_rank(matrix):
    """Bareiss elimination over a multivariate polynomial integral domain."""
    matrix = [list(row) for row in matrix]
    row_count = len(matrix)
    column_count = len(matrix[0])
    rank = 0
    previous = None
    pivots = []
    for column in range(column_count):
        pivot_row = next(
            (row for row in range(rank, row_count) if matrix[row][column]), None
        )
        if pivot_row is None:
            continue
        if pivot_row != rank:
            matrix[rank], matrix[pivot_row] = matrix[pivot_row], matrix[rank]
        pivot = matrix[rank][column]
        for row in range(rank + 1, row_count):
            left = matrix[row][column]
            for target_column in range(column + 1, column_count):
                numerator = (
                    pivot * matrix[row][target_column]
                    - left * matrix[rank][target_column]
                )
                if previous is not None:
                    numerator, remainder = divmod(numerator, previous)
                    assert not remainder
                matrix[row][target_column] = numerator
            matrix[row][column] = matrix[row][column] - matrix[row][column]
        pivots.append(pivot)
        previous = pivot
        rank += 1
        if rank == row_count:
            break
    return rank, tuple(pivots)


def symbolic_model_rank(network_index, network):
    edges = tuple(tuple(edge) for edge in network["edges"])
    assert len(edges) == 12
    reticulations = reticulation_vertices(network["vertices"])
    assert len(reticulations) == 2
    context = fmpq_mpoly_ctx.get(
        [f"rank_n{network_index}_p{index}" for index in range(10)]
    )
    parameters = context.gens()
    one = context.constant(1)
    coordinates = evaluate_jc_coordinates(
        network["vertices"],
        edges,
        dict(zip(network["leaves"], (1, 2, 3, 4))),
        JC_REPRESENTATIVES,
        parameters[:8] + (one, one, one, one),
        dict(zip(reticulations, parameters[8:])),
    )
    tangent = []
    for assignment, coordinate in zip(JC_REPRESENTATIVES[1:], coordinates[1:]):
        row = [coordinate.derivative(index) for index in range(10)]
        row.extend(
            int(assignment[leaf] != 0) * coordinate for leaf in range(4)
        )
        tangent.append(row)
    rank, pivots = fraction_free_rank(tangent)
    return {
        "rank": rank,
        "pivot_count": len(pivots),
        "last_pivot_sha256": sha256(str(pivots[-1]).encode()).hexdigest(),
    }


def bit_string(values):
    return "".join("1" if value else "0" for value in values)


def component_orbits_under_s4(networks, topology):
    components = topology["components"]
    item_to_component = {
        item: component_index
        for component_index, component in enumerate(components)
        for item in component
    }
    disjoint = DisjointSet(len(components))
    for component_index, component in enumerate(components):
        representative = component[0]
        for permutation in permutations((1, 2, 3, 4)):
            image = item_action(
                networks,
                topology["rooted_code_to_item"],
                representative,
                permutation,
            )
            disjoint.union(component_index, item_to_component[image])
    orbits = defaultdict(list)
    for component_index in range(len(components)):
        orbits[disjoint.find(component_index)].append(component_index)
    return tuple(tuple(sorted(orbit)) for orbit in sorted(orbits.values(), key=min))


def generate_certificate():
    expansion_count, networks = enumerate_networks()
    assert expansion_count == 112
    assert len(networks) == 27
    topology = move_components(networks)
    components = topology["components"]
    items = topology["items"]
    item_to_component = {
        item: component_index
        for component_index, component in enumerate(components)
        for item in component
    }

    ranks = []
    for network_index, network in enumerate(networks):
        rank_data = symbolic_model_rank(network_index, network)
        assert rank_data["rank"] == NETWORK_DIMENSIONS[network_index]
        ranks.append(rank_data)

    models = ExactModels(networks)
    invariant_orbits = tuple(invariant_orbit(template) for template in INVARIANT_TEMPLATES)
    assert tuple(map(len, invariant_orbits)) == (6, 3, 3, 24, 12, 12)
    all_invariants = tuple(
        invariant for orbit in invariant_orbits for invariant in orbit
    )
    assert len(all_invariants) == 60

    item_signatures = {}
    for item in items:
        item_signatures[item] = tuple(
            bool(exact_pullback(invariant, item, models))
            for invariant in all_invariants
        )

    component_signatures = []
    component_dimensions = []
    component_semi_counts = []
    for component in components:
        signatures = {item_signatures[item] for item in component}
        assert len(signatures) == 1
        component_signatures.append(next(iter(signatures)))
        dimensions = {NETWORK_DIMENSIONS[item[0]] for item in component}
        assert len(dimensions) == 1
        component_dimensions.append(next(iter(dimensions)))
        component_semi_counts.append(
            len(
                {
                    canonical_colored_graph(
                        semi_directed_graph(networks[item[0]], item[1])
                    )
                    for item in component
                }
            )
        )
    assert len(set(component_signatures)) == 108

    same_dimension_pairs = 0
    for first, second in combinations(range(len(components)), 2):
        if component_dimensions[first] == component_dimensions[second]:
            same_dimension_pairs += 1
            assert component_signatures[first] != component_signatures[second]

    directed_orbit = invariant_orbit(DIRECTED_TEMPLATE)
    directed_patterns = []
    for component in components:
        representative = component[0]
        directed_patterns.append(
            tuple(
                bool(exact_pullback(invariant, representative, models))
                for invariant in directed_orbit
            )
        )

    total_directed = 0
    six_rejected = 0
    seven_rejected = 0
    unresolved = []
    for lower in range(len(components)):
        for higher in range(len(components)):
            if component_dimensions[lower] >= component_dimensions[higher]:
                continue
            total_directed += 1
            rejected_by_six = any(
                low and not high
                for low, high in zip(
                    component_signatures[lower], component_signatures[higher]
                )
            )
            if rejected_by_six:
                six_rejected += 1
                seven_rejected += 1
                continue
            rejected_by_directed = any(
                low and not high
                for low, high in zip(
                    directed_patterns[lower], directed_patterns[higher]
                )
            )
            if rejected_by_directed:
                seven_rejected += 1
            else:
                unresolved.append((lower, higher))
    assert (total_directed, six_rejected, seven_rejected, len(unresolved)) == (
        2880,
        2304,
        2412,
        468,
    )

    component_orbits = component_orbits_under_s4(networks, topology)
    component_records = []
    for component_index, component in enumerate(components):
        component_records.append(
            {
                "id": component_index,
                "dimension": component_dimensions[component_index],
                "rooted_topology_count": len(component),
                "semi_directed_topology_count": component_semi_counts[component_index],
                "network_indices": sorted({item[0] for item in component}),
                "signature": bit_string(component_signatures[component_index]),
                "members": [
                    {"network_index": item[0], "port_labels": list(item[1])}
                    for item in component
                ],
            }
        )

    network_records = []
    for network_index, network in enumerate(networks):
        network_records.append(
            {
                "index": network_index,
                "core_index": network["core_index"],
                "subdivision_counts_by_directed_segment": network[
                    "subdivision_counts_by_directed_segment"
                ],
                "vertices": dict(sorted(network["vertices"].items())),
                "edges": network["edges"],
                "leaves": network["leaves"],
                "triangle_count_after_root_suppression": network[
                    "triangle_count_after_root_suppression"
                ],
                "generic_jc_dimension": NETWORK_DIMENSIONS[network_index],
                "rank_last_pivot_sha256": ranks[network_index][
                    "last_pivot_sha256"
                ],
            }
        )

    serialized_signature = "\n".join(
        bit_string(signature) for signature in component_signatures
    )
    return {
        "status": {
            "finite_slice_equal_dimension_classification": "PROVED",
            "one_sided_containment_classification": "UNRESOLVED",
            "stochastic_overlap_within_move_components": (
                "PROVED by the independent T, Theta, Psi, and Omega "
                "correspondence certificates plus reversible root placement"
            ),
        },
        "scope": (
            "root-spanning simple binary strongly tree-child level-2 theta "
            "networks with four labelled outgoing leaf ports under JC"
        ),
        "raw_ordinary_port_distributions": expansion_count,
        "unlabelled_rooted_networks": len(networks),
        "leaf_labelled_rooted_networks": len(items),
        "leaf_labelled_semi_directed_networks": topology["semi_class_count"],
        "semi_directed_class_size_distribution": dict(
            sorted(topology["semi_class_size_distribution"].items())
        ),
        "triangle_redirection_relations": topology[
            "triangle_redirection_edges"
        ],
        "move_components": len(components),
        "move_component_size_distribution": dict(
            sorted(Counter(map(len, components)).items())
        ),
        "move_component_dimension_distribution": dict(
            sorted(Counter(component_dimensions).items())
        ),
        "move_component_semi_count_distribution": dict(
            sorted(Counter(component_semi_counts).items())
        ),
        "component_S4_orbits": [list(orbit) for orbit in component_orbits],
        "component_S4_orbit_count": len(component_orbits),
        "exact_symbolic_dimensions": list(NETWORK_DIMENSIONS),
        "dimension_count_by_unlabelled_network": dict(
            sorted(Counter(NETWORK_DIMENSIONS).items())
        ),
        "invariant_template_supports": [
            len(template) for template in INVARIANT_TEMPLATES
        ],
        "invariant_orbit_sizes": [len(orbit) for orbit in invariant_orbits],
        "total_exact_invariants_after_S4": len(all_invariants),
        "component_signature_sha256": sha256(
            serialized_signature.encode()
        ).hexdigest(),
        "same_dimension_component_pairs_separated": same_dimension_pairs,
        "directed_template_support": len(DIRECTED_TEMPLATE),
        "directed_template_orbit_size": len(directed_orbit),
        "lower_to_higher_component_pairs": total_directed,
        "directed_containments_rejected_by_six_templates": six_rejected,
        "directed_containments_rejected_after_extra_template": seven_rejected,
        "directed_containments_unresolved": len(unresolved),
        "unresolved_directed_component_pairs": [list(pair) for pair in unresolved],
        "networks": network_records,
        "components": component_records,
    }


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--write-certificate",
        action="store_true",
        help="write the deterministic machine-readable certificate",
    )
    args = parser.parse_args()
    certificate = generate_certificate()
    # Normalize integer dictionary keys exactly as JSON does so replay compares
    # the in-memory result to the machine certificate rather than to a Python-
    # specific representation.
    certificate = json.loads(json.dumps(certificate, sort_keys=True))
    if args.write_certificate:
        CERTIFICATE.write_text(
            json.dumps(certificate, indent=2, sort_keys=True) + "\n"
        )
    else:
        assert CERTIFICATE.exists(), f"missing certificate: {CERTIFICATE}"
        expected = json.loads(CERTIFICATE.read_text())
        assert certificate == expected
    summary = {
        key: certificate[key]
        for key in (
            "unlabelled_rooted_networks",
            "leaf_labelled_rooted_networks",
            "leaf_labelled_semi_directed_networks",
            "move_components",
            "component_S4_orbit_count",
            "exact_symbolic_dimensions",
            "invariant_orbit_sizes",
            "same_dimension_component_pairs_separated",
            "directed_containments_rejected_after_extra_template",
            "directed_containments_unresolved",
        )
    }
    print(json.dumps(summary, indent=2, sort_keys=True))


if __name__ == "__main__":
    main()
