# PR108 native integration and merge plan

This is a prospective plan, not execution or merge clearance. Publication and the Google Sheet row are already complete: DOI10.5281/zenodo.23181280, Math Puzzles A31:D31 with blank chat cell. Do not republish or append again.

Native integration is scoped to problem30003996/OWR-16633-013. Use the corrected source-pinned review-bundle helper after fresh source review, a frozen actual input manifest, independently reviewed choices, root review gates and an exact current capacity check. Preserve original claimed_solved2/5 provenance and every original submitted file, the exact imported empty report, all unrelated native dictionaries, ledger prefixes, catalog rows/ranks/positions, campaign physical rows and source/cache bytes. After a successful candidate, inspect the complete diff and every offered target/native file and commission an independent candidate review. Export only audited candidate paths. Exclude full spreadsheet metadata and DOI-dedup response bodies containing unrelated sheet/row content; preserve these privately and retain their authenticated pins and reviewed target-only receipts. The supporting scientific package must remain byte-identical to the published 46 logical files.

The actual incoming branch diff from authenticated merge basec6975ca76f9f667f1250ba403d0e6da2aafe14d0 to originalhead3526d46bf143b08e5055ffa7728c6278e9f958ea contains exactly the original15 attempt files plus QUEUE.md. Actual Git read receipts are in actual_operations/native_merge_strategy_base_isolated_read and native_merge_strategy_incoming_diff. A first read ran in the primary checkout and failed to find this isolated commit; its actual failure is retained, and it mutated nothing.

After the candidate passes review and its scoped native acceptance commit is pushed/read back, preserve that accepted tree when merging the original branch history into main. The original15 bodies are already included byte-for-byte in historical_original; effective proof/diagnostics and target QUEUE cells represent the reviewed repaired result. A main-only two-parent merge using Git's ours strategy will include the authenticated originalhead as the second parent while retaining the accepted tree exactly. Before that action, require current main/remote/PR originalhead unchanged, empty own index, no tracked changes and all original incoming changes accounted for. Mark the reviewed PR ready, then create the two-parent merge on main with hooks disabled; check exact parents and tree equality to the acceptance commit, then CAS-push and authenticate GitHub MERGED state and merge OID. Do not silently substitute the original proof or broad old QUEUE changes for reviewed accepted contents. If any asserted parent/tree/status or scope check fails, stop that action and retain the real failure for reconciliation.

Root must record actual completion, DOI/Sheet/native/merge readbacks and release ownership before moving to the next literal claimed_solved draft in number order. No new branch, GitHub release, additional proof turn or human outreach is part of this plan.
