# PR108 inert native input preparation

`build_execution_inputs.py` constructs the exact effective data for the existing corrected-V4 review-bundle helper. It requires an explicit full `--main-parent` and the sealed `--helper-dir`. It writes a canonical data draft and a small audit packet within this folder. The data draft has the contract's `template_only=false`; a native run additionally requires a separately reviewed thin configuration and seven fresh gates, which this builder does not create.

The builder authenticates all twelve native baseline files from the supplied main commit and their materialized checkout counterparts. It binds the four original authentication artifacts, all fifteen preserved original files, ten effective diagnostics, the frozen package manifest and 46 logical payloads, actual publication and exact Sheet receipt closures, source/raw/cache pins without copies, all five helper sources, actual Python/Git/GH binary pins and full Python version, and the fixed clean startup and role environments. The exact current target desk assessment is preserved. The campaign note describes the published attributed resolution and historical `claimed_solved` effort `2/5`, absent original structured ledger, and zero additional central proof turns.

Private Git location files identify the repository/common directories. Git configuration and existing GH configuration/authentication files are streamed only into size/hash metadata; their contents are never inspected, retained, or printed here. Expected GH login is the parent's existing authenticated `AlecKriebel` identity. Guarded private-body validation and actual future account/live/remote checks belong to the reviewed helper boundary.

Every selected nongate file has a concrete direct helper consumer or proposed future gate checked-artifact use. The original R1 finding F01 is preserved alongside the corrected package ledger and the new clean R2 evidence. No historical clearance is turned into a new native clearance.

The helper offers every captured audit input inside its private candidate. Two exact offered bodies must be omitted from a separately reviewed public export: `publication/authenticated_inputs/actual_operations/tracker_postpub_metadata/stdout.bin` and `publication/authenticated_inputs/actual_operations/tracker_postpub_DOI_dedup/stdout.bin`, both beneath `unsolved_math_prioritization/attempts/30003996/`. Their original pinned bytes remain private and available for internal verification. The unchanged receipts retain their pin references; the public export filter does not alter the frozen execution-input bytes.

Capacity uses the helper's existing complete destination inventory with seven future gates each reserved at 65,536 bytes, the exclusive largest native atomic-write slot, bounded process streams, 32 MiB headroom, 16 MiB future-commit reserve, and 8 MiB runtime reserve. Actual final gate sizes and current free space must be refreshed at the existing execution boundary. Insufficient capacity is reported without deletion, compression, cache changes, or a fallback.

The only builder subprocesses are local read-only Git commands. It neither imports nor calls native prepare/assess entry points, makes no service call, copies no raw cache, and writes no Git state or primary index. The actual DOI is `10.5281/zenodo.23181280`; the selected row is exactly `'Math Puzzles'!A31:D31`, with blank B. Mathematical discovery is 100%; the preparation log records the separate input-preparation checkpoints.
