#!/usr/bin/env python3
"""Exact bounded searches for Route A of the dimension-four Borsuk program.

There are three independent, deterministic modes.

``a5-envelope``
    Builds the finite weak-order envelope for unions of alternating-coordinate
    orbits in the four-dimensional hyperplane sum(x_i)=0 in R^5.  It checks an
    explicit five-coloring against every ordinary opposition edge and every
    possible parity-forced near-opposition edge.

``signed-orbits``
    Enumerates every subgroup of the four-dimensional signed-permutation group
    generated by at most two elements, and every primitive canonical integer
    seed with entries in [0,bound].  All minimum-inner-product graphs and all
    reported colorings use integer arithmetic.

``signed-pair-ties``
    For aligned pairs of the canonical signed-permutation orbits, checks every
    exact radial ratio at which the two within-orbit diameters and the cross
    diameter coincide.  These triple ties are the only two-layer events not
    immediately five-colorable from the single-orbit four-colorings.

``signed-triple-ties``
    Finds triangles in the preceding pair-tie relation, hence aligned
    three-orbit configurations for which all three within diameters and all
    three cross diameters coincide.

``d4-transversals``
    Enumerates all 2^12 antipodal transversals of the 24 vectors with exactly
    two nonzero coordinates, each equal to +/-1.  It verifies a uniform
    three-coloring and non-bipartiteness for every transversal.

``positive-root-halves``
    Checks four elementary lexicographic half-root families, including the
    non-spherical variants, using exact squared distances.

``golden-transversals``
    Verifies an exact 120-vector construction over Q(sqrt(5)), a five-coloring
    of its 60-line absolute relation graph, and an unbalanced signed cycle that
    handles all 2^60 antipodal transversals at once.

No optional packages are needed.  The searches are intended as falsification
tools, not as probabilistic evidence.
"""

from __future__ import annotations

import argparse
import collections
import itertools
import math
import sys
import time
from typing import Iterable, Sequence


Point = tuple[int, ...]


def dot(x: Sequence[int], y: Sequence[int]) -> int:
    return sum(a * b for a, b in zip(x, y))


def min_inner_graph(points: Sequence[Point]) -> tuple[int | None, list[set[int]]]:
    """Return the exact minimum inner product and its graph."""
    n = len(points)
    adjacency = [set() for _ in range(n)]
    if n < 2:
        return None, adjacency
    minimum = min(dot(points[i], points[j]) for i in range(n) for j in range(i))
    for i in range(n):
        for j in range(i):
            if dot(points[i], points[j]) == minimum:
                adjacency[i].add(j)
                adjacency[j].add(i)
    return minimum, adjacency


def diameter_graph(points: Sequence[Point]) -> tuple[int | None, list[set[int]]]:
    n = len(points)
    adjacency = [set() for _ in range(n)]
    if n < 2:
        return None, adjacency

    def squared_distance(x: Point, y: Point) -> int:
        return sum((a - b) ** 2 for a, b in zip(x, y))

    maximum = max(
        squared_distance(points[i], points[j]) for i in range(n) for j in range(i)
    )
    for i in range(n):
        for j in range(i):
            if squared_distance(points[i], points[j]) == maximum:
                adjacency[i].add(j)
                adjacency[j].add(i)
    return maximum, adjacency


def greedy_dsatur(adjacency: Sequence[set[int]]) -> list[int]:
    """Construct and internally verify a deterministic proper coloring."""
    n = len(adjacency)
    colors = [-1] * n
    for _ in range(n):
        vertex = max(
            (v for v in range(n) if colors[v] < 0),
            key=lambda v: (
                len({colors[w] for w in adjacency[v] if colors[w] >= 0}),
                len(adjacency[v]),
                v,
            ),
        )
        forbidden = {colors[w] for w in adjacency[vertex] if colors[w] >= 0}
        color = 0
        while color in forbidden:
            color += 1
        colors[vertex] = color
    assert all(colors[v] != colors[w] for v in range(n) for w in adjacency[v])
    return colors


def exact_k_coloring(adjacency: Sequence[set[int]], k: int) -> list[int] | None:
    """Complete DSATUR backtracking; a returned coloring is re-verified."""
    n = len(adjacency)
    colors = [-1] * n

    def search(colored: int, used: int) -> bool:
        if colored == n:
            return True
        vertex = max(
            (v for v in range(n) if colors[v] < 0),
            key=lambda v: (
                len({colors[w] for w in adjacency[v] if colors[w] >= 0}),
                sum(colors[w] < 0 for w in adjacency[v]),
                len(adjacency[v]),
                v,
            ),
        )
        forbidden = {colors[w] for w in adjacency[vertex] if colors[w] >= 0}
        choices = [color for color in range(used) if color not in forbidden]
        if used < k and used not in forbidden:
            choices.append(used)
        for color in choices:
            colors[vertex] = color
            if search(colored + 1, max(used, color + 1)):
                return True
            colors[vertex] = -1
        return False

    if not search(0, 0):
        return None
    assert max(colors, default=-1) < k
    assert all(colors[v] != colors[w] for v in range(n) for w in adjacency[v])
    return colors


def find_clique(adjacency: Sequence[set[int]], target: int) -> tuple[int, ...] | None:
    """Find a clique of the requested size using exact bit-set backtracking."""
    n = len(adjacency)
    masks = [sum(1 << w for w in adjacency[v]) for v in range(n)]

    def search(chosen: tuple[int, ...], candidates: int) -> tuple[int, ...] | None:
        need = target - len(chosen)
        if need == 0:
            return chosen
        if candidates.bit_count() < need:
            return None
        while candidates:
            bit = candidates & -candidates
            vertex = bit.bit_length() - 1
            candidates ^= bit
            answer = search(chosen + (vertex,), candidates & masks[vertex])
            if answer is not None:
                return answer
            if candidates.bit_count() < need:
                return None
        return None

    return search((), (1 << n) - 1)


def is_bipartite(adjacency: Sequence[set[int]]) -> bool:
    side = [-1] * len(adjacency)
    for start in range(len(adjacency)):
        if side[start] >= 0:
            continue
        side[start] = 0
        queue = collections.deque([start])
        while queue:
            vertex = queue.popleft()
            for neighbor in adjacency[vertex]:
                if side[neighbor] < 0:
                    side[neighbor] = 1 - side[vertex]
                    queue.append(neighbor)
                elif side[neighbor] == side[vertex]:
                    return False
    return True


def weak_orders() -> list[Point]:
    """All 540 nonconstant weak orders on five labeled coordinates."""
    orders: list[Point] = []
    for levels in range(2, 6):
        for word in itertools.product(range(levels), repeat=5):
            if set(word) == set(range(levels)):
                orders.append(word)
    assert len(orders) == 540
    return orders


def opposition(x: Point, y: Point) -> bool:
    """Equality condition in the rearrangement inequality."""
    return all(
        (x[i] - x[j]) * (y[i] - y[j]) <= 0
        for i in range(5)
        for j in range(i)
    )


def boundary_minimum_color(x: Point) -> int:
    """A cyclic ascent starting at a globally minimum coordinate."""
    minimum = min(x)
    choices = [i for i in range(5) if x[i] == minimum and x[(i + 1) % 5] > minimum]
    assert choices
    return min(choices)


def near_opposites(x: Point) -> Iterable[Point]:
    """Reverse a strict order, then make one adjacent rank transposition."""
    assert len(set(x)) == 5
    coordinate_order = sorted(range(5), key=lambda i: x[i])
    reverse_order = coordinate_order[::-1]
    for rank in range(4):
        target_order = list(reverse_order)
        target_order[rank], target_order[rank + 1] = (
            target_order[rank + 1],
            target_order[rank],
        )
        y = [0] * 5
        for value_rank, coordinate in enumerate(target_order):
            y[coordinate] = value_rank
        yield tuple(y)


def run_a5_envelope() -> None:
    orders = weak_orders()
    index = {x: i for i, x in enumerate(orders)}
    colors = [boundary_minimum_color(x) for x in orders]

    ordinary_edges: set[tuple[int, int]] = set()
    for i, x in enumerate(orders):
        for j in range(i):
            if opposition(x, orders[j]):
                ordinary_edges.add((j, i))

    near_edges: set[tuple[int, int]] = set()
    for x in orders:
        if len(set(x)) != 5:
            continue
        i = index[x]
        for y in near_opposites(x):
            j = index[y]
            near_edges.add(tuple(sorted((i, j))))

    all_edges = ordinary_edges | near_edges
    bad = [(i, j) for i, j in all_edges if colors[i] == colors[j]]
    assert not bad
    assert len(ordinary_edges) == 8280
    assert len(near_edges - ordinary_edges) == 240
    assert len(all_edges) == 8520

    print("A5 weak-order envelope: exact verification passed")
    print(f"vertices={len(orders)}")
    print(f"ordinary_opposition_edges={len(ordinary_edges)}")
    print(f"additional_near_opposition_edges={len(near_edges - ordinary_edges)}")
    print(f"envelope_edges={len(all_edges)}")
    print("color_class_sizes=" + repr([colors.count(c) for c in range(5)]))
    print("bad_edges=0")


SignedMap = tuple[int, int, int, int]


def signed_elements() -> list[SignedMap]:
    return [
        tuple(signs[i] * (permutation[i] + 1) for i in range(4))
        for permutation in itertools.permutations(range(4))
        for signs in itertools.product((-1, 1), repeat=4)
    ]


def compose_signed(left: SignedMap, right: SignedMap) -> SignedMap:
    """Composition for maps with output_i=sign_i*input_abs(entry_i)-1."""
    answer = []
    for entry in left:
        middle = right[abs(entry) - 1]
        sign = (1 if entry > 0 else -1) * (1 if middle > 0 else -1)
        answer.append(sign * abs(middle))
    return tuple(answer)  # type: ignore[return-value]


def two_generated_signed_subgroups() -> tuple[list[SignedMap], list[frozenset[int]]]:
    elements = signed_elements()
    element_index = {g: i for i, g in enumerate(elements)}
    table = [
        [element_index[compose_signed(left, right)] for right in elements]
        for left in elements
    ]
    identity = element_index[(1, 2, 3, 4)]

    def closure(a: int, b: int) -> frozenset[int]:
        known = {identity}
        queue = [identity]
        for current in queue:
            for generator in (a, b):
                nxt = table[generator][current]
                if nxt not in known:
                    known.add(nxt)
                    queue.append(nxt)
        return frozenset(known)

    groups = {
        closure(a, b)
        for a in range(len(elements))
        for b in range(a, len(elements))
    }
    return elements, sorted(groups, key=lambda group: (len(group), tuple(group)))


def primitive_canonical_seeds(bound: int) -> list[Point]:
    seeds: list[Point] = []
    for seed in itertools.combinations_with_replacement(range(bound + 1), 4):
        if not any(seed):
            continue
        divisor = 0
        for coordinate in seed:
            divisor = math.gcd(divisor, coordinate)
        if divisor == 1:
            seeds.append(seed)
    return seeds


def apply_signed(mapping: SignedMap, point: Point) -> Point:
    return tuple(
        (1 if entry > 0 else -1) * point[abs(entry) - 1]
        for entry in mapping
    )


def run_signed_orbits(bound: int) -> None:
    started = time.monotonic()
    elements, groups = two_generated_signed_subgroups()
    seeds = primitive_canonical_seeds(bound)
    print(
        f"signed group enumeration: elements={len(elements)} "
        f"two_generated_subgroups={len(groups)} seeds={len(seeds)}",
        flush=True,
    )

    orbit_sources: dict[tuple[Point, ...], tuple[int, Point]] = {}
    for group in groups:
        for seed in seeds:
            orbit = tuple(sorted({apply_signed(elements[g], seed) for g in group}))
            orbit_sources.setdefault(orbit, (len(group), seed))
    print(f"distinct_point_orbits={len(orbit_sources)}", flush=True)

    upper_distribution: collections.Counter[int] = collections.Counter()
    size_distribution: collections.Counter[int] = collections.Counter()
    bound_distribution: collections.Counter[tuple[int, int]] = collections.Counter()
    witness: tuple[
        tuple[Point, ...], int | None, list[set[int]], list[int], tuple[int, ...], int, Point
    ] | None = None

    for orbit, (group_order, seed) in orbit_sources.items():
        minimum, adjacency = min_inner_graph(orbit)
        coloring = greedy_dsatur(adjacency)
        upper = max(coloring, default=-1) + 1
        lower = 1
        clique: tuple[int, ...] = (0,) if orbit else ()
        for target in range(upper, 1, -1):
            found = find_clique(adjacency, target)
            if found is not None:
                lower = target
                clique = found
                break
        if upper >= 3 and lower < 3 and not is_bipartite(adjacency):
            lower = 3
        upper_distribution[upper] += 1
        size_distribution[len(orbit)] += 1
        bound_distribution[(lower, upper)] += 1
        if witness is None or (upper, lower, -len(orbit)) > (
            max(witness[3], default=-1) + 1,
            len(witness[4]),
            -len(witness[0]),
        ):
            witness = (orbit, minimum, adjacency, coloring, clique, group_order, seed)

    assert witness is not None
    orbit, minimum, adjacency, coloring, clique, group_order, seed = witness
    print("orbit_size_distribution=" + repr(dict(sorted(size_distribution.items()))))
    print("verified_coloring_upper_distribution=" + repr(dict(sorted(upper_distribution.items()))))
    print("rigorous_lower_to_coloring_upper_distribution=" + repr(dict(sorted(bound_distribution.items()))))
    print(f"maximum_verified_coloring_upper={max(upper_distribution)}")
    print("strongest_witness:")
    print(f"  source_group_order={group_order}")
    print(f"  canonical_seed={seed}")
    print(f"  points={orbit}")
    print(f"  minimum_inner_product={minimum}")
    print(f"  diameter_squared={2 * dot(orbit[0], orbit[0]) - 2 * minimum if minimum is not None else 0}")
    print(f"  edges={sum(map(len, adjacency)) // 2}")
    print(f"  clique_vertices={clique}")
    print(f"  coloring={coloring}")
    print(f"elapsed_seconds={time.monotonic() - started:.3f}")


def combined_minimum_graph(
    first: Sequence[Point],
    second: Sequence[Point],
    first_adjacency: Sequence[set[int]],
    second_adjacency: Sequence[set[int]],
    cross_minimum: int,
) -> list[set[int]]:
    offset = len(first)
    adjacency = [set() for _ in range(offset + len(second))]
    for i in range(len(first)):
        for j in first_adjacency[i]:
            if i < j:
                adjacency[i].add(j)
                adjacency[j].add(i)
    for i in range(len(second)):
        for j in second_adjacency[i]:
            if i < j:
                adjacency[offset + i].add(offset + j)
                adjacency[offset + j].add(offset + i)
    for i, x in enumerate(first):
        for j, y in enumerate(second):
            if dot(x, y) == cross_minimum:
                adjacency[i].add(offset + j)
                adjacency[offset + j].add(i)
    return adjacency


def run_signed_pair_ties(bound: int) -> None:
    """Check exact triple-diameter ties for aligned canonical orbit pairs."""
    from fractions import Fraction

    started = time.monotonic()
    elements, groups = two_generated_signed_subgroups()
    seeds = primitive_canonical_seeds(bound)
    pairs_tested = 0
    ties = 0
    bound_distribution: collections.Counter[tuple[int, int]] = collections.Counter()
    strongest: tuple[int, int, int, Point, Point, Fraction, int, int] | None = None

    for group in groups:
        orbit_data: list[
            tuple[Point, tuple[Point, ...], int, int, list[set[int]]]
        ] = []
        seen: set[tuple[Point, ...]] = set()
        for seed in seeds:
            orbit = tuple(sorted({apply_signed(elements[g], seed) for g in group}))
            if orbit in seen:
                continue
            seen.add(orbit)
            minimum, adjacency = min_inner_graph(orbit)
            if minimum is None:
                continue
            norm = dot(orbit[0], orbit[0])
            diameter_squared = 2 * (norm - minimum)
            orbit_data.append((seed, orbit, norm, diameter_squared, adjacency))

        for first_data, second_data in itertools.combinations(orbit_data, 2):
            pairs_tested += 1
            seed_a, first, norm_a, diameter_a, adjacency_a = first_data
            seed_b, second, norm_b, diameter_b, adjacency_b = second_data
            ratio_squared = Fraction(diameter_a, diameter_b)

            # By common-group invariance, fixing one point of the first orbit
            # suffices to obtain the global cross minimum.
            cross_minimum = min(dot(first[0], y) for y in second)
            left = Fraction(norm_a) + ratio_squared * norm_b - diameter_a
            triple_tie = (
                (cross_minimum == 0 and left == 0)
                or (
                    cross_minimum != 0
                    and left * cross_minimum > 0
                    and left * left
                    == 4 * cross_minimum * cross_minimum * ratio_squared
                )
            )
            if not triple_tie:
                continue

            ties += 1
            adjacency = combined_minimum_graph(
                first, second, adjacency_a, adjacency_b, cross_minimum
            )
            coloring = greedy_dsatur(adjacency)
            upper = max(coloring) + 1
            lower = 1
            for target in range(upper, 1, -1):
                if find_clique(adjacency, target) is not None:
                    lower = target
                    break
            if upper >= 3 and lower < 3 and not is_bipartite(adjacency):
                lower = 3
            for target in range(lower, upper):
                exact_coloring = exact_k_coloring(adjacency, target)
                if exact_coloring is not None:
                    upper = target
                    break
                lower = target + 1
            bound_distribution[(lower, upper)] += 1
            candidate = (
                upper,
                lower,
                len(first) + len(second),
                seed_a,
                seed_b,
                ratio_squared,
                len(group),
                sum(map(len, adjacency)) // 2,
            )
            if strongest is None or (candidate[0], candidate[1], -candidate[2]) > (
                strongest[0],
                strongest[1],
                -strongest[2],
            ):
                strongest = candidate

    print("signed canonical pair triple-tie verification passed")
    print(f"bound={bound}")
    print(f"two_generated_subgroups={len(groups)}")
    print(f"canonical_seeds={len(seeds)}")
    print(f"aligned_orbit_pairs_tested={pairs_tested}")
    print(f"exact_triple_ties={ties}")
    print(
        "rigorous_lower_to_coloring_upper_distribution="
        + repr(dict(sorted(bound_distribution.items())))
    )
    print(f"strongest_tie={strongest}")
    print(f"elapsed_seconds={time.monotonic() - started:.3f}")


def run_signed_triple_ties(bound: int) -> None:
    """Check aligned canonical triples with all six distance classes tied."""
    from fractions import Fraction

    started = time.monotonic()
    elements, groups = two_generated_signed_subgroups()
    seeds = primitive_canonical_seeds(bound)
    pair_ties = 0
    triple_ties = 0
    bound_distribution: collections.Counter[tuple[int, int]] = collections.Counter()
    strongest: tuple[int, int, int, int, tuple[Point, Point, Point], int] | None = None

    for group in groups:
        orbit_data: list[
            tuple[Point, tuple[Point, ...], int, int, list[set[int]]]
        ] = []
        seen: set[tuple[Point, ...]] = set()
        for seed in seeds:
            orbit = tuple(sorted({apply_signed(elements[g], seed) for g in group}))
            if orbit in seen:
                continue
            seen.add(orbit)
            minimum, adjacency = min_inner_graph(orbit)
            if minimum is None:
                continue
            norm = dot(orbit[0], orbit[0])
            orbit_data.append((seed, orbit, norm, 2 * (norm - minimum), adjacency))

        number = len(orbit_data)
        tie_minimum: list[list[int | None]] = [
            [None] * number for _ in range(number)
        ]
        for i in range(number):
            for j in range(i):
                first = orbit_data[i]
                second = orbit_data[j]
                ratio_squared = Fraction(first[3], second[3])
                cross_minimum = min(dot(first[1][0], y) for y in second[1])
                left = Fraction(first[2]) + ratio_squared * second[2] - first[3]
                tied = (
                    (cross_minimum == 0 and left == 0)
                    or (
                        cross_minimum != 0
                        and left * cross_minimum > 0
                        and left * left
                        == 4 * cross_minimum * cross_minimum * ratio_squared
                    )
                )
                if tied:
                    tie_minimum[i][j] = tie_minimum[j][i] = cross_minimum
                    pair_ties += 1

        for i, j, k in itertools.combinations(range(number), 3):
            if (
                tie_minimum[i][j] is None
                or tie_minimum[i][k] is None
                or tie_minimum[j][k] is None
            ):
                continue
            triple_ties += 1
            layers = (orbit_data[i], orbit_data[j], orbit_data[k])
            offsets: list[int] = []
            total_vertices = 0
            for layer in layers:
                offsets.append(total_vertices)
                total_vertices += len(layer[1])
            adjacency = [set() for _ in range(total_vertices)]
            for layer_index, layer in enumerate(layers):
                offset = offsets[layer_index]
                for v in range(len(layer[1])):
                    for w in layer[4][v]:
                        if v < w:
                            adjacency[offset + v].add(offset + w)
                            adjacency[offset + w].add(offset + v)
            for first_index, second_index, cross_minimum in (
                (0, 1, tie_minimum[i][j]),
                (0, 2, tie_minimum[i][k]),
                (1, 2, tie_minimum[j][k]),
            ):
                assert cross_minimum is not None
                for v, x in enumerate(layers[first_index][1]):
                    for w, y in enumerate(layers[second_index][1]):
                        if dot(x, y) == cross_minimum:
                            a = offsets[first_index] + v
                            b = offsets[second_index] + w
                            adjacency[a].add(b)
                            adjacency[b].add(a)

            upper = max(greedy_dsatur(adjacency)) + 1
            lower = 1
            for target in range(upper, 1, -1):
                if find_clique(adjacency, target) is not None:
                    lower = target
                    break
            if upper >= 3 and lower < 3 and not is_bipartite(adjacency):
                lower = 3
            for target in range(lower, upper):
                if exact_k_coloring(adjacency, target) is not None:
                    upper = target
                    break
                lower = target + 1
            bound_distribution[(lower, upper)] += 1
            candidate = (
                upper,
                lower,
                total_vertices,
                len(group),
                (layers[0][0], layers[1][0], layers[2][0]),
                sum(map(len, adjacency)) // 2,
            )
            if strongest is None or (candidate[0], candidate[1], -candidate[2]) > (
                strongest[0],
                strongest[1],
                -strongest[2],
            ):
                strongest = candidate

    print("signed canonical full triple-tie verification passed")
    print(f"bound={bound}")
    print(f"two_generated_subgroups={len(groups)}")
    print(f"canonical_seeds={len(seeds)}")
    print(f"pair_tie_instances={pair_ties}")
    print(f"full_triple_tie_instances={triple_ties}")
    print(
        "rigorous_lower_to_coloring_upper_distribution="
        + repr(dict(sorted(bound_distribution.items())))
    )
    print(f"strongest_full_triple_tie={strongest}")
    print(f"elapsed_seconds={time.monotonic() - started:.3f}")


def d4_antipodal_representatives() -> list[Point]:
    roots: list[Point] = []
    for i, j in itertools.combinations(range(4), 2):
        for first, second in itertools.product((-1, 1), repeat=2):
            point = [0] * 4
            point[i] = first
            point[j] = second
            roots.append(tuple(point))
    return sorted(point for point in roots if point < tuple(-x for x in point))


def support_color(point: Point) -> int:
    support = frozenset(i for i, x in enumerate(point) if x)
    one_factors = (
        {frozenset((0, 1)), frozenset((2, 3))},
        {frozenset((0, 2)), frozenset((1, 3))},
        {frozenset((0, 3)), frozenset((1, 2))},
    )
    return next(color for color, factor in enumerate(one_factors) if support in factor)


def run_d4_transversals() -> None:
    representatives = d4_antipodal_representatives()
    assert len(representatives) == 12
    edge_distribution: collections.Counter[int] = collections.Counter()
    for mask in range(1 << len(representatives)):
        points = tuple(
            tuple((-1 if (mask >> i) & 1 else 1) * x for x in point)
            for i, point in enumerate(representatives)
        )
        minimum, adjacency = min_inner_graph(points)
        assert minimum == -1
        colors = [support_color(point) for point in points]
        assert all(colors[i] != colors[j] for i in range(12) for j in adjacency[i])
        # Non-bipartiteness is the exact lower bound chi >= 3; some of these
        # graphs have odd girth greater than three, so a clique test is too weak.
        assert not is_bipartite(adjacency)
        edge_distribution[sum(map(len, adjacency)) // 2] += 1

    print("D4 antipodal transversals: exact verification passed")
    print(f"transversals={1 << len(representatives)}")
    print("points_per_transversal=12")
    print("diameter_squared=6")
    print("chromatic_number=3 for every transversal")
    print("edge_count_distribution=" + repr(dict(sorted(edge_distribution.items()))))


def lexicographic_positive_half(points: Iterable[Point]) -> tuple[Point, ...]:
    answer = []
    for point in points:
        first_nonzero = next((x for x in point if x), 0)
        if first_nonzero > 0:
            answer.append(point)
    return tuple(sorted(set(answer)))


def exact_chromatic_number(adjacency: Sequence[set[int]]) -> int:
    upper = max(greedy_dsatur(adjacency), default=-1) + 1
    for k in range(1, upper + 1):
        if exact_k_coloring(adjacency, k) is not None:
            return k
    raise AssertionError("greedy coloring was not reproducible")


def run_positive_root_halves() -> None:
    a4_roots: list[Point] = []
    for i, j in itertools.combinations(range(5), 2):
        point = [0] * 5
        point[i], point[j] = 1, -1
        a4_roots.extend((tuple(point), tuple(-x for x in point)))

    d4_roots: list[Point] = []
    for i, j in itertools.combinations(range(4), 2):
        for first, second in itertools.product((-1, 1), repeat=2):
            point = [0] * 4
            point[i], point[j] = first, second
            d4_roots.append(tuple(point))

    b4_roots = list(d4_roots)
    c4_roots = list(d4_roots)
    for i in range(4):
        for sign in (-1, 1):
            short = [0] * 4
            short[i] = sign
            b4_roots.append(tuple(short))
            long = [0] * 4
            long[i] = 2 * sign
            c4_roots.append(tuple(long))

    families = (
        ("A4 differences in sum-zero R5", lexicographic_positive_half(a4_roots)),
        ("D4 signed two-support vectors", lexicographic_positive_half(d4_roots)),
        ("D4 plus unit axes", lexicographic_positive_half(b4_roots)),
        ("D4 plus doubled axes", lexicographic_positive_half(c4_roots)),
    )
    print("positive half-root exact checks:")
    for name, points in families:
        diameter_squared, adjacency = diameter_graph(points)
        chromatic = exact_chromatic_number(adjacency)
        print(
            f"  {name}: vertices={len(points)} D2={diameter_squared} "
            f"edges={sum(map(len, adjacency)) // 2} chi={chromatic}"
        )


Quadratic = tuple[int, int]  # a+b*sqrt(5)
QuadraticPoint = tuple[Quadratic, Quadratic, Quadratic, Quadratic]


def quadratic_multiply(x: Quadratic, y: Quadratic) -> Quadratic:
    return (x[0] * y[0] + 5 * x[1] * y[1], x[0] * y[1] + x[1] * y[0])


def quadratic_dot(x: QuadraticPoint, y: QuadraticPoint) -> Quadratic:
    rational = 0
    radical = 0
    for a, b in zip(x, y):
        product_value = quadratic_multiply(a, b)
        rational += product_value[0]
        radical += product_value[1]
    return (rational, radical)


def quadratic_negate(x: QuadraticPoint) -> QuadraticPoint:
    return tuple((-a, -b) for a, b in x)  # type: ignore[return-value]


def permutation_parity(permutation: Sequence[int]) -> int:
    return sum(
        permutation[i] > permutation[j]
        for i in range(len(permutation))
        for j in range(i + 1, len(permutation))
    ) % 2


def golden_vectors_scaled_by_four() -> list[QuadraticPoint]:
    """The exact vectors, multiplied by four to stay in Z[sqrt(5)]."""
    points: list[QuadraticPoint] = []
    zero = (0, 0)
    for coordinate in range(4):
        for sign in (-1, 1):
            point = [zero] * 4
            point[coordinate] = (4 * sign, 0)
            points.append(tuple(point))  # type: ignore[arg-type]
    for signs in itertools.product((-1, 1), repeat=4):
        points.append(tuple((2 * sign, 0) for sign in signs))  # type: ignore[arg-type]

    # Four times (0, 1/2, phi/2, 1/(2phi)).
    base: QuadraticPoint = ((0, 0), (2, 0), (1, 1), (-1, 1))
    even_permutations = [
        permutation
        for permutation in itertools.permutations(range(4))
        if permutation_parity(permutation) == 0
    ]
    for permutation in even_permutations:
        permuted = tuple(base[permutation[i]] for i in range(4))
        nonzero = [i for i, value in enumerate(permuted) if value != zero]
        for signs in itertools.product((-1, 1), repeat=3):
            point = list(permuted)
            for coordinate, sign in zip(nonzero, signs):
                a, b = point[coordinate]
                point[coordinate] = (sign * a, sign * b)
            points.append(tuple(point))  # type: ignore[arg-type]
    answer = sorted(set(points))
    assert len(answer) == 120
    assert {quadratic_dot(x, x) for x in answer} == {(16, 0)}
    return answer


GOLDEN_LINE_COLORING = [
    3, 4, 3, 0, 0, 1, 3, 3, 0, 4, 3, 3, 1, 1, 3, 3, 2, 4, 2, 3,
    2, 4, 0, 0, 0, 4, 2, 1, 2, 1, 2, 4, 1, 4, 1, 1, 0, 4, 1, 0,
    0, 2, 2, 4, 2, 4, 4, 3, 1, 4, 1, 3, 0, 0, 2, 3, 2, 1, 2, 0,
]


def run_golden_transversals() -> None:
    points = golden_vectors_scaled_by_four()
    seen: set[QuadraticPoint] = set()
    lines: list[QuadraticPoint] = []
    for point in points:
        if point in seen:
            continue
        opposite = quadratic_negate(point)
        seen.update((point, opposite))
        lines.append(max(point, opposite))
    assert len(lines) == 60

    target = (4, 4)  # 16*(phi/2)=8phi=4+4sqrt(5)
    negative_target = (-4, -4)
    adjacency = [set() for _ in lines]
    edge_sign: dict[tuple[int, int], int] = {}
    for i in range(len(lines)):
        for j in range(i):
            inner = quadratic_dot(lines[i], lines[j])
            if inner in (target, negative_target):
                adjacency[i].add(j)
                adjacency[j].add(i)
                edge_sign[(j, i)] = 1 if inner == target else -1

    assert sum(map(len, adjacency)) // 2 == 360
    assert set(map(len, adjacency)) == {12}
    assert len(GOLDEN_LINE_COLORING) == len(lines)
    assert all(
        GOLDEN_LINE_COLORING[i] != GOLDEN_LINE_COLORING[j]
        for i in range(len(lines))
        for j in adjacency[i]
    )

    # A switching-invariant negative cycle proves that every choice of line
    # orientations leaves at least one negative target edge.
    negative_cycle = (0, 21, 41, 36, 32, 0)
    cycle_signs = []
    for first, second in zip(negative_cycle, negative_cycle[1:]):
        cycle_signs.append(edge_sign[tuple(sorted((first, second)))])
    assert cycle_signs == [1, -1, -1, -1, 1]
    assert math.prod(cycle_signs) == -1

    # Direct exact spectrum check: apart from antipodes, no inner product is
    # below -(4+4sqrt(5)) in the scaled model.
    spectrum = {
        quadratic_dot(points[i], points[j])
        for i in range(len(points))
        for j in range(i)
        if points[j] != quadratic_negate(points[i])
    }
    assert spectrum == {
        (-4, -4),
        (-8, 0),
        (4, -4),
        (0, 0),
        (-4, 4),
        (8, 0),
        (4, 4),
    }

    print("golden 120-vector transversal verification passed")
    print("field=Q(sqrt(5)), positive embedding 2<sqrt(5)<3")
    print("vectors=120 projective_lines=60")
    print("scaled_squared_norm=16")
    print("absolute_relation_edges=360 degree=12")
    print("five_color_class_sizes=" + repr([GOLDEN_LINE_COLORING.count(c) for c in range(5)]))
    print(f"negative_cycle={negative_cycle} signs={cycle_signs}")
    print("all_antipodal_transversals_have_5_colorable_diameter_graph=true")


def parse_args(argv: Sequence[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    subparsers = parser.add_subparsers(dest="mode", required=True)
    subparsers.add_parser("a5-envelope")
    signed = subparsers.add_parser("signed-orbits")
    signed.add_argument("--bound", type=int, default=6)
    pair_ties = subparsers.add_parser("signed-pair-ties")
    pair_ties.add_argument("--bound", type=int, default=4)
    triple_ties = subparsers.add_parser("signed-triple-ties")
    triple_ties.add_argument("--bound", type=int, default=3)
    subparsers.add_parser("d4-transversals")
    subparsers.add_parser("positive-root-halves")
    subparsers.add_parser("golden-transversals")
    return parser.parse_args(argv)


def main(argv: Sequence[str] | None = None) -> None:
    args = parse_args(sys.argv[1:] if argv is None else argv)
    if args.mode == "a5-envelope":
        run_a5_envelope()
    elif args.mode == "signed-orbits":
        run_signed_orbits(args.bound)
    elif args.mode == "signed-pair-ties":
        run_signed_pair_ties(args.bound)
    elif args.mode == "signed-triple-ties":
        run_signed_triple_ties(args.bound)
    elif args.mode == "d4-transversals":
        run_d4_transversals()
    elif args.mode == "positive-root-halves":
        run_positive_root_halves()
    elif args.mode == "golden-transversals":
        run_golden_transversals()
    else:
        raise AssertionError(args.mode)


if __name__ == "__main__":
    main()
