#!/usr/bin/env python3
"""Exact irreducibility audit for the h=0 half-turn second-digit forms.

The h=0 first-placement affine space splits as X(21) + Y(15) under the
class half-turn.  The even second-digit equations have shape

    F_i(x) + G_i(y) = 0,

while the odd equations have shape

    x^T B_i y + l_i(y) = 0.

This verifier reconstructs those forms from the primary lifting code and
certifies that the relative polar operators of both even pencils generate
the full matrix algebra.  It also checks the same fact after restricting
the X pencil to the canonical y=e_0 odd-equation fiber.
"""

from __future__ import annotations

from pathlib import Path
import sys
from typing import Sequence


HERE = Path(__file__).resolve().parent
SEARCH_ROOT = HERE.parent
PHASE_ROOT = SEARCH_ROOT / "phase_second_digit"
HALFTURN_ROOT = SEARCH_ROOT / "h0_halfturn_twists"
sys.path.insert(0, str(HALFTURN_ROOT))
sys.path.insert(0, str(PHASE_ROOT))
sys.path.insert(0, str(SEARCH_ROOT))

import verify_h0_halfturn_twists as halfturn  # noqa: E402
import verify_phase_second_digit as second  # noqa: E402
from verify_lp333_order3_phase_hensel import (  # noqa: E402
    augmented_system,
    canonical_solution,
    first_digit_equations,
    matrix_rank,
    profiles_from_ids,
)
from verify_lp333_order3_trit_lift import (  # noqa: E402
    active_trit_coordinates,
)


def matrix_inverse(
    matrix: Sequence[Sequence[int]],
) -> tuple[tuple[int, ...], ...] | None:
    """Return the inverse over F_3, or None if the matrix is singular."""

    size = len(matrix)
    rows = [
        [int(value) % 3 for value in row]
        + [int(index == column) for column in range(size)]
        for index, row in enumerate(matrix)
    ]
    for column in range(size):
        pivot = next(
            (
                row
                for row in range(column, size)
                if rows[row][column]
            ),
            None,
        )
        if pivot is None:
            return None
        rows[column], rows[pivot] = rows[pivot], rows[column]
        if rows[column][column] == 2:
            rows[column] = [
                2 * value % 3 for value in rows[column]
            ]
        for row in range(size):
            if row == column or not rows[row][column]:
                continue
            factor = rows[row][column]
            rows[row] = [
                (left - factor * right) % 3
                for left, right in zip(rows[row], rows[column])
            ]
    return tuple(tuple(row[size:]) for row in rows)


def matrix_product(
    left: Sequence[Sequence[int]],
    right: Sequence[Sequence[int]],
) -> tuple[tuple[int, ...], ...]:
    columns = tuple(zip(*right))
    return tuple(
        tuple(
            sum(
                int(a) * int(b)
                for a, b in zip(row, column)
            )
            % 3
            for column in columns
        )
        for row in left
    )


class MatrixSpan:
    """Incremental exact RREF for flattened square matrices over F_3."""

    def __init__(self, size: int) -> None:
        self.size = size
        self.rows: dict[int, tuple[int, ...]] = {}

    def add(
        self,
        matrix: Sequence[Sequence[int]],
    ) -> tuple[tuple[int, ...], ...] | None:
        vector = [
            int(value) % 3 for row in matrix for value in row
        ]
        for pivot in sorted(self.rows):
            if not vector[pivot]:
                continue
            factor = vector[pivot]
            vector = [
                (left - factor * right) % 3
                for left, right in zip(vector, self.rows[pivot])
            ]
        pivot = next(
            (index for index, value in enumerate(vector) if value),
            None,
        )
        if pivot is None:
            return None
        if vector[pivot] == 2:
            vector = [2 * value % 3 for value in vector]

        # Keep the stored basis in RREF.  This is important because a newly
        # discovered pivot need not lie to the right of all prior pivots.
        for old_pivot, old_row in tuple(self.rows.items()):
            if not old_row[pivot]:
                continue
            factor = old_row[pivot]
            self.rows[old_pivot] = tuple(
                (left - factor * right) % 3
                for left, right in zip(old_row, vector)
            )
        self.rows[pivot] = tuple(vector)
        return tuple(
            tuple(vector[index * self.size:(index + 1) * self.size])
            for index in range(self.size)
        )

    def __len__(self) -> int:
        return len(self.rows)


def generated_algebra_dimension(
    polar_matrices: Sequence[Sequence[Sequence[int]]],
) -> int:
    """Dimension of the algebra generated by relative polar operators."""

    size = len(polar_matrices[0])
    base = next(
        (
            matrix
            for matrix in polar_matrices
            if matrix_inverse(matrix) is not None
        ),
        None,
    )
    if base is None:
        raise AssertionError("the polar family has no nonsingular base")
    inverse = matrix_inverse(base)
    if inverse is None:
        raise AssertionError("the selected polar base became singular")
    generators = tuple(
        matrix_product(inverse, matrix)
        for matrix in polar_matrices
    )
    identity = tuple(
        tuple(int(row == column) for column in range(size))
        for row in range(size)
    )

    span = MatrixSpan(size)
    queue: list[tuple[tuple[int, ...], ...]] = []
    for matrix in (identity,) + generators:
        reduced = span.add(matrix)
        if reduced is not None:
            queue.append(reduced)

    cursor = 0
    while cursor < len(queue) and len(span) < size * size:
        matrix = queue[cursor]
        cursor += 1
        for generator in generators:
            reduced = span.add(matrix_product(generator, matrix))
            if reduced is not None:
                queue.append(reduced)
    return len(span)


def reconstruct_forms() -> tuple[
    tuple[tuple[int, tuple[int, ...], tuple[tuple[int, ...], ...]], ...],
    tuple[tuple[int, tuple[int, ...], tuple[tuple[int, ...], ...]], ...],
]:
    profiles = profiles_from_ids(
        halfturn.PROFILE_IDS_A,
        halfturn.PROFILE_IDS_B,
    )
    coordinates = active_trit_coordinates(profiles)
    coordinate_index = {
        coordinate: index for index, coordinate in enumerate(coordinates)
    }
    class_halfturn = tuple(
        coordinate_index[
            (channel, (class_index + 6) % 12, residue)
        ]
        for channel, class_index, residue in coordinates
    )
    first_rows = augmented_system(first_digit_equations(profiles))
    coefficient_rows = tuple(row[:-1] for row in first_rows)
    fixed_rows = tuple(
        tuple(
            (
                1
                if column == index
                else -1
                if column == class_halfturn[index]
                else 0
            )
            % 3
            for column in range(54)
        )
        for index in range(54)
    )
    anti_rows = tuple(
        tuple(
            (
                1
                if column == index
                else 1
                if column == class_halfturn[index]
                else 0
            )
            % 3
            for column in range(54)
        )
        for index in range(54)
    )
    fixed_basis = second.nullspace_basis(
        coefficient_rows + fixed_rows,
        columns=54,
    )
    anti_basis = second.nullspace_basis(
        coefficient_rows + anti_rows,
        columns=54,
    )
    if (len(fixed_basis), len(anti_basis)) != (21, 15):
        raise AssertionError("the half-turn dimensions changed")

    origin = canonical_solution(first_rows, 54)
    if origin is None:
        raise AssertionError("the first placement digit became inconsistent")
    fixed_origin = tuple(
        2 * (
            int(origin[index])
            + int(origin[class_halfturn[index]])
        )
        % 3
        for index in range(54)
    )
    constants, linears, polars = second.derive_quadratics(
        second.second_digit_term_data(profiles),
        fixed_origin,
        fixed_basis + anti_basis,
    )
    plus_forms = [
        halfturn.combine_quadratics(
            constants, linears, polars, (index,), (1,)
        )
        for index in range(8)
    ]
    plus_forms.extend(
        halfturn.combine_quadratics(
            constants,
            linears,
            polars,
            (8 + index, 14 + index),
            (1, 1),
        )
        for index in range(6)
    )
    active_plus = tuple(
        form
        for form in plus_forms
        if (
            form[0]
            or any(form[1])
            or any(any(row) for row in form[2])
        )
    )
    minus_forms = tuple(
        halfturn.combine_quadratics(
            constants,
            linears,
            polars,
            (8 + index, 14 + index),
            (1, 2),
        )
        for index in range(6)
    )
    if len(active_plus) != 12 or len(minus_forms) != 6:
        raise AssertionError("the even/odd form count changed")
    return active_plus, minus_forms


def audit() -> dict[str, object]:
    plus_forms, minus_forms = reconstruct_forms()
    x_polars = tuple(
        tuple(
            tuple(polar[row][column] for column in range(21))
            for row in range(21)
        )
        for _, _, polar in plus_forms
    )
    y_polars = tuple(
        tuple(
            tuple(
                polar[21 + row][21 + column]
                for column in range(15)
            )
            for row in range(15)
        )
        for _, _, polar in plus_forms
    )
    bilinear_blocks = tuple(
        tuple(
            tuple(polar[row][21 + column] for column in range(15))
            for row in range(21)
        )
        for _, _, polar in minus_forms
    )

    # A shift x -> x+a removes every odd linear term precisely when
    # B_i^T a = -l_i for all i.  The exact stacked system is inconsistent.
    odd_center_rows = tuple(
        tuple(block[row][column] for row in range(21))
        for block in bilinear_blocks
        for column in range(15)
    )
    odd_center_rhs = tuple(
        -linear[21 + column] % 3
        for _, linear, _ in minus_forms
        for column in range(15)
    )
    odd_center_augmented = tuple(
        row + (rhs,)
        for row, rhs in zip(odd_center_rows, odd_center_rhs)
    )
    odd_center_ranks = (
        matrix_rank(odd_center_rows),
        matrix_rank(odd_center_augmented),
    )
    if odd_center_ranks != (21, 22):
        raise AssertionError("the odd common-center ranks changed")

    # Likewise, x -> x+a centers all F_i precisely when P_i a=-f_i.
    even_center_rows = tuple(
        polar[row]
        for polar in x_polars
        for row in range(21)
    )
    even_center_rhs = tuple(
        -linear[row] % 3
        for _, linear, _ in plus_forms
        for row in range(21)
    )
    even_center_augmented = tuple(
        row + (rhs,)
        for row, rhs in zip(even_center_rows, even_center_rhs)
    )
    even_center_ranks = (
        matrix_rank(even_center_rows),
        matrix_rank(even_center_augmented),
    )
    if even_center_ranks != (21, 22):
        raise AssertionError("the even common-center ranks changed")

    x_algebra_dimension = generated_algebra_dimension(x_polars)
    y_algebra_dimension = generated_algebra_dimension(y_polars)
    if x_algebra_dimension != 21**2:
        raise AssertionError("the X polar algebra is no longer full")
    if y_algebra_dimension != 15**2:
        raise AssertionError("the Y polar algebra is no longer full")

    # The canonical asymmetric slice used in the higher-digit attack is
    # y=e_0.  Its six odd equations leave a 15-dimensional linear kernel
    # in X.  Restrict every X polar form to that kernel.
    odd_slice_rows = tuple(
        tuple(block[row][0] for row in range(21))
        for block in bilinear_blocks
    )
    if matrix_rank(odd_slice_rows) != 6:
        raise AssertionError("the y=e_0 odd slice lost rank six")
    slice_basis = second.nullspace_basis(
        odd_slice_rows,
        columns=21,
    )
    if len(slice_basis) != 15:
        raise AssertionError("the y=e_0 X kernel changed dimension")
    restricted_polars = tuple(
        tuple(
            tuple(
                sum(
                    slice_basis[left][row]
                    * polar[row][column]
                    * slice_basis[right][column]
                    for row in range(21)
                    for column in range(21)
                )
                % 3
                for right in range(15)
            )
            for left in range(15)
        )
        for polar in x_polars
    )
    restricted_ranks = tuple(
        matrix_rank(polar) for polar in restricted_polars
    )
    expected_restricted_ranks = (
        15, 15, 15, 14, 13, 15, 15, 14, 14, 15, 14, 14,
    )
    if restricted_ranks != expected_restricted_ranks:
        raise AssertionError("the y=e_0 restricted ranks changed")
    restricted_algebra_dimension = generated_algebra_dimension(
        restricted_polars
    )
    if restricted_algebra_dimension != 15**2:
        raise AssertionError(
            "the y=e_0 restricted polar algebra is no longer full"
        )

    return {
        "odd_common_center_ranks": odd_center_ranks,
        "even_common_center_ranks": even_center_ranks,
        "x_polar_algebra_dimension": x_algebra_dimension,
        "x_full_matrix_dimension": 21**2,
        "y_polar_algebra_dimension": y_algebra_dimension,
        "y_full_matrix_dimension": 15**2,
        "y_e0_odd_rank": 6,
        "y_e0_x_kernel_dimension": len(slice_basis),
        "y_e0_restricted_polar_ranks": restricted_ranks,
        "y_e0_restricted_algebra_dimension": (
            restricted_algebra_dimension
        ),
        "y_e0_restricted_full_matrix_dimension": 15**2,
    }


def main() -> None:
    result = audit()
    for key, value in result.items():
        print(f"{key}={value}")
    print("PASS: h=0 even pencils are algebraically irreducible")
    print("STATUS: contraction obstruction only; no LP(333) or H(668)")


if __name__ == "__main__":
    main()
