"""UNEXECUTED PR47 ROOT post-inspection SOURCE. ROOT reads and copies unchanged adjacent to A47.
Runtime is read-only for native/Git/remote/science; only ROOT-owned command evidence and exact post records are written.
All actual acceptance outputs must exist before use. Dated foreign changes cause refusal, not invented equality.
"""
from pathlib import Path,PurePosixPath
import argparse,copy,datetime as dt,hashlib,json,math,os,re,stat,subprocess,sys,traceback
sys.dont_write_bytecode=True
A=Path(__file__).absolute().parent;R=A.parents[2];H=A/'acceptance_preparation_family';C=A/'reviewed_candidate';K=R/'unsolved_math_prioritization/attempts/2849';B=A.parents[1];P46=A.parent/'pr46_30004438'
HEAD='487327b2412c436ae69e8c52bf353a9a1fb7594e';BASE='c6975ca76f9f667f1250ba403d0e6da2aafe14d0';PREP='1a10442d9962db99c608412f53fef754870bfadf24fd76e7e899112fc38ebef1';CONTRACT='750df37c894b91f5e81e97ca894fafd8e0543b26b2b44c0c68a239f184cbfebd';PHASE_OPERATOR='684e9deb100beebb080d16aa1ed56ca9072d2e0cc2d29528d1acb4100f58da9b'
COMMANDS=[];D=None;SOURCE=None;OUTER=None
def need(v,m):
    if not v:raise ValueError(m)
def sha(b):return hashlib.sha256(b).hexdigest()
def raw(p):need(p.is_file() and not p.is_symlink() and all(not q.is_symlink() for q in p.parents),'Regular nonsymlink input');return p.read_bytes()
def parse(b):
    def pairs(items):
        d={}
        for k,v in items:need(k not in d,'Duplicate JSON key');d[k]=v
        return d
    def fl(s):v=float(s);need(math.isfinite(v),'Nonfinite JSON');return v
    return json.loads(b,object_pairs_hook=pairs,parse_float=fl,parse_constant=lambda s:(_ for _ in ()).throw(ValueError(s)))
def load(p):return parse(raw(p))
def eq(a,b):return type(a) is type(b) and (a.keys()==b.keys() and all(eq(a[k],b[k]) for k in a) if type(a) is dict else len(a)==len(b) and all(eq(x,y) for x,y in zip(a,b)) if type(a) is list else a==b)
def safe(n):
    need(type(n) is str and n and n!='.' and '\\' not in n and '\0' not in n,'Literal member path');p=PurePosixPath(n);need(not p.is_absolute() and p.as_posix()==n and not {'.','..','.git','__pycache__'}.intersection(p.parts),'Canonical member');return n
def pin(p):b=raw(p);return dict(path=safe(p.relative_to(R).as_posix()),bytes=len(b),sha256=sha(b))
def check(base,z):
    need(type(z) is dict and set(z)=={'path','bytes','sha256'} and type(z['bytes']) is int and z['bytes']>=0 and type(z['sha256']) is str and re.fullmatch('[0-9a-f]{64}',z['sha256']),'Exact typed triple');b=raw(base/safe(z['path']));need(len(b)==z['bytes'] and sha(b)==z['sha256'],'Entire referenced body');return b
def clock(s):need(type(s) is str and s and s==s.strip(),'UTC string');v=dt.datetime.fromisoformat(s[:-1]+'+00:00' if s.endswith('Z') else s);need(v.tzinfo is not None and v.utcoffset()==dt.timedelta(0),'Aware UTC');return v
def stamp():return dt.datetime.now(dt.timezone.utc).isoformat()
def put(p,b):
    need(not p.is_symlink() and all(not q.is_symlink() for q in p.parents),'Regular output ancestors')
    with p.open('xb') as f:f.write(b);f.flush();os.fsync(f.fileno())
    need(stat.S_IMODE(p.stat().st_mode)==0o644,'ROOT operational evidence full0644')
def encode(v):return (json.dumps(v,indent=2,ensure_ascii=False,allow_nan=False)+'\n').encode()
def command(argv,stdin=None):
    need(type(argv) is list and all(type(z) is str for z in argv),'Literal argv');need((argv[0]=='git' and argv[1] in {'branch','rev-parse','show','ls-tree','ls-files','diff','diff-tree','merge-base','cat-file'}) or argv==['gh','pr','view','47','--repo','AlecKriebel/Math','--json','number,url,state,isDraft,headRefOid,headRefName,baseRefName,mergeCommit,mergedAt,body'],'Read-only command whitelist');need(stdin is None or (type(stdin) is bytes and argv==['git','cat-file','--batch']),'Only literal blob batch uses bounded stdin')
    d=D/str(len(COMMANDS));d.mkdir(exist_ok=False);pre=dict(schema='pr47-root-post-readonly-prelaunch/v1',operator_pid=os.getpid(),argv=argv,cwd=str(R),prepared_utc=stamp(),source=pin(D/'PRELAUNCH_SOURCE.py'),outer_operator=pin(D/'PRELAUNCH_OPERATOR.py'),stdin_supplied=stdin is not None)
    if stdin is not None:put(d/'stdin.bin',stdin);pre['stdin']=pin(d/'stdin.bin')
    put(d/'PRELAUNCH.json',encode(pre));cap=dict(pre,schema='pr47-root-post-actual-readonly-command/v1',started_utc=stamp(),actual_execution=False,completed=False,pid=None,exit_code=None);out=err=b'';proc=None
    try:proc=subprocess.Popen(argv,cwd=R,stdin=subprocess.DEVNULL if stdin is None else subprocess.PIPE,stdout=subprocess.PIPE,stderr=subprocess.PIPE,env=dict(os.environ,GIT_OPTIONAL_LOCKS='0'));cap.update(actual_execution=True,pid=proc.pid);out,err=proc.communicate(stdin);cap.update(completed=True,exit_code=proc.returncode)
    except BaseException:
        cap['operator_error']=traceback.format_exc()
        if proc is not None:
            try:out,err=proc.communicate();cap.update(completed=True,exit_code=proc.returncode)
            except BaseException:cap['operator_reap_error']=traceback.format_exc()
    cap.update(finished_utc=stamp(),source_unchanged=raw(Path(__file__))==raw(D/'PRELAUNCH_SOURCE.py')==SOURCE,outer_operator_unchanged=raw(OUTER)==raw(D/'PRELAUNCH_OPERATOR.py'))
    for k,b in [('stdout',out),('stderr',err)]:put(d/(k+'.bin'),b);cap[k]=pin(d/(k+'.bin'))
    cap['status']='PASS' if cap['actual_execution'] is True and cap['completed'] is True and type(cap['pid']) is int and cap['pid']>0 and type(cap['exit_code']) is int and cap['exit_code']==0 and cap['source_unchanged'] is True and cap['outer_operator_unchanged'] is True and err==b'' and 'operator_error' not in cap else 'FAIL';put(d/'CAPTURE.json',encode(cap));COMMANDS.append(cap);need(cap['status']=='PASS' and clock(cap['started_utc'])<=clock(cap['finished_utc']),'Actual complete successful read-only child, failure retained');return out
def git(*args):return command(['git',*args])
def cap4(p,expected=0):
    c=load(p);need({q.name for q in p.parent.iterdir()}=={'CAPTURE.json','prelaunch_operator.py','stdout.bin','stderr.bin'},'Exact genuine ROOT CAP4');need(c['schema']=='root-explicit-command-capture/v1' and c['actual_execution'] is True and c['completed'] is True and type(c['pid']) is int and c['pid']>0 and type(c['exit_code']) is int and c['exit_code']==expected and c['stdin_supplied'] is False and c['operator_unchanged'] is True and c['status']==('PASS' if expected==0 else 'FAIL') and c['cwd']==str(R),'Typed actual completed ROOT child with honest failure');need(sha(raw(p.parent/'prelaunch_operator.py'))==c['operator_sha256']=='c1ae969ccbbc48ed6fb486e96184da94329291a46b27d2b891ecb87185c909ec','Full genuine ROOT operator')
    for k in ['stdout','stderr']:need(c[k]['path']==k+'.bin','Literal ROOT streams');check(p.parent,c[k])
    # ROOT command success is an actual exit/status claim. Successful gh-ready
    # and git-push commands legitimately emit progress on stderr; retain it all.
    need(clock(c['started_utc'])<=clock(c['finished_utc'])<=dt.datetime.now(dt.timezone.utc),'Actual ROOT UTC');return dict(capture=pin(p),complete_capture=c,complete_members=[pin(q) for q in sorted(p.parent.iterdir())])
def native(fresh):
    rows=[];need(type(fresh['files']) is list and len(fresh['files'])==13 and len({z['path'] for z in fresh['files']})==13,'Exact13 fresh identities')
    for z in fresh['files']:need(set(z)=={'path','bytes','sha256','worktree_mode'} and type(z['worktree_mode']) is int and z['worktree_mode']==0o644,'Fresh restricted full0644');p=R/safe(z['path']);mode=stat.S_IMODE(p.stat().st_mode);rows.append(dict(pin(p),worktree_mode=mode));need(mode==0o644,'Current native13 full0644')
    return rows
def phase_captures(pins,overlay,fresh):
    result=[];previous_end=None;expectedrefs={k:pin(R/pins[k.replace('-','_')]) for k in ['final-plan','final-receipt','final-manifest','reconciliation-capture','previous-mirror','previous-post','fresh-preimage','root-bindings']}
    for phase in ['preflight','overlay','prepush','finalize','mirror','post']:
        d=A/('root_'+phase+'_actual_capture');need({q.name for q in d.iterdir()}=={'CAPTURE.json','PRELAUNCH.json','PRELAUNCH_SOURCE.py','PRELAUNCH_OPERATOR.py','stdout.bin','stderr.bin'},'Exact real phaseCAP6');c=load(d/'CAPTURE.json');pre=load(d/'PRELAUNCH.json');need(c['schema']=='ROOT_actual_reviewed_acceptance_phase_capture_v1' and c['phase']==phase and c['actual_execution'] is True and c['completed'] is True and c['status']=='PASS' and type(c['exit_code']) is int and c['exit_code']==0 and type(c['pid']) is int and c['pid']>0 and type(c['operator_pid']) is int and c['operator_pid']>0 and c['stdin_supplied'] is False and c['cwd']==str(R) and c['source_unchanged'] is True and c['operator_unchanged'] is True,'Complete typed genuine actual phase');need(all(eq(c[k],v) for k,v in pre.items() if k!='schema'),'Entire original prelaunch')
        name={'mirror':'state_mirror_reconciliation.py','post':'verify_post_acceptance.py'}.get(phase,'integrate_reviewed_partial.py');need(sha(raw(d/'PRELAUNCH_SOURCE.py'))==c['source_sha256']==sha(raw(H/name)) and sha(raw(d/'PRELAUNCH_OPERATOR.py'))==c['operator_sha256']==sha(raw(A/'run_actual_acceptance_phases.py'))==PHASE_OPERATOR,'Entire actual reviewed source/operator')
        argv=['/usr/bin/python3','-B',str(H/name),'--execute','--preparation-manifest-sha256',PREP]
        for k,z in expectedrefs.items():argv.extend(['--'+k,z['path'],'--'+k+'-sha256',z['sha256']])
        if phase not in ['mirror','post']:argv.append(phase)
        if phase=='overlay':argv.extend(['--merge-queue-preimage-sha256',overlay['automatic_merge_queue_preimage_sha256']])
        need(eq(c['argv'],argv) and eq(c['complete_literal_final_references'],expectedrefs) and eq(c['complete_literal_final_references_after'],expectedrefs) and c['complete_final_references_unchanged'] is True and c['before_after_permission_scope_checked'] is True and c['permissions_scope']['operator_child_umask']==0o022 and c['permissions_scope']['arbitrary_mode_writer_correctness_accepted'] is False,'Every literal argv/pin and scoped mode authority')
        for field in ['native13_before','native13_after']:
            rr=c[field];need(type(rr) is list and len(rr)==13 and {z['path'] for z in rr}=={z['path'] for z in fresh['files']} and all(set(z)=={'path','bytes','sha256','worktree_mode'} and type(z['bytes']) is int and type(z['worktree_mode']) is int and z['worktree_mode']==0o644 and re.fullmatch('[0-9a-f]{64}',z['sha256']) for z in rr),'Full actual phase13 modes, bodies may change as authorized')
        for field in ['owned_mutable_logs_before','owned_mutable_logs_after']:need(type(c[field]) is list and all(set(z)=={'path','bytes','sha256','worktree_mode'} and type(z['worktree_mode']) is int and z['worktree_mode']==0o644 and z['path'] in ['draft_pr_publication_program_20260930/RESEARCH_LOG.md','draft_pr_publication_program_20260930/audits/pr47_2849/ROOT_RESEARCH_LOG.md'] for z in c[field]),'Exact owned logs scoped0644')
        for k in ['stdout','stderr']:need(c[k]['path']==k+'.bin','Literal phase streams');check(d,c[k])
        need(raw(d/'stderr.bin')==b'' and clock(c['prepared_utc'])<=clock(c['started_utc'])<=clock(c['finished_utc'])<=dt.datetime.now(dt.timezone.utc) and (previous_end is None or previous_end<=clock(c['started_utc'])),'Whole phase streams and chronological actual intervals');previous_end=clock(c['finished_utc']);result.append(dict(capture=pin(d/'CAPTURE.json'),complete_capture=c,complete_members=[pin(q) for q in sorted(d.iterdir())]))
    return result
def tree_entries(data):
    need(data.endswith(b'\0'),'Complete null-delimited Git tree');out={}
    for line in data[:-1].split(b'\0'):
        fields,n=line.split(b'\t',1);mode,kind,oid=fields.decode().split();name=n.decode();safe(name);need(name not in out and re.fullmatch('[0-9a-f]{40}',oid),'Unique whole Git tree entry');out[name]=dict(mode=mode,kind=kind,oid=oid)
    return out
def verify_blob_batch(expectations):
    expected={}
    for oid,size,digest in expectations:
        need(re.fullmatch('[0-9a-f]{40}',oid) and re.fullmatch('[0-9a-f]{64}',digest) and (size is None or type(size) is int and size>=0),'Typed actual blob expectation');need(oid not in expected or expected[oid][1]==digest and (size is None or expected[oid][0] is None or expected[oid][0]==size),'Conflicting full blob expectation');expected[oid]=(size if size is not None else expected.get(oid,(None,None))[0],digest)
    ids=sorted(expected);out=command(['git','cat-file','--batch'],(''.join(oid+'\n' for oid in ids)).encode());offset=0
    for oid in ids:
        end=out.find(b'\n',offset);need(end>=offset,'Complete blob header');parts=out[offset:end].split(b' ');need(len(parts)==3 and parts[0].decode()==oid and parts[1]==b'blob' and re.fullmatch(b'0|[1-9][0-9]*',parts[2]),'Exact queried blob header/type/decimal');size=int(parts[2]);start=end+1;body=out[start:start+size];need(len(body)==size and out[start+size:start+size+1]==b'\n' and (expected[oid][0] is None or size==expected[oid][0]) and sha(body)==expected[oid][1] and hashlib.sha1(b'blob '+str(size).encode()+b'\0'+body).hexdigest()==oid,'Every complete batch blob raw bytes/size/SHA256/Git object identity');offset=start+size+1
    need(offset==len(out),'No omitted or trailing batch data');return len(ids)
def main():
    global D,SOURCE,OUTER
    need(__debug__ and sys.flags.optimize==0 and os.environ.get('PYTHONOPTIMIZE','') in ('','0'),'Nonoptimized guards');need(A.name=='pr47_2849' and raw(Path(__file__))==raw(A/'root_post_operator_preparation/inspect_complete_actual_post.py')==raw(A/'ROOT_POST_INSPECTION_PRELAUNCH_SOURCE.py'),'ROOT reads and copies exact SOURCE/prelaunch adjacent; preparation path is not executable authority')
    p=argparse.ArgumentParser();p.add_argument('--root-commit-capture',required=True);p.add_argument('--root-push-capture',required=True);p.add_argument('--outer-capture-directory',default='root_complete_actual_post_inspection_capture');args=p.parse_args();safe(args.outer_capture_directory);need('/' not in args.outer_capture_directory,'Exact adjacent ROOT outer capture');OUTER=A/args.outer_capture_directory/'prelaunch_operator.py';SOURCE=raw(Path(__file__));need(sha(raw(OUTER))=='c1ae969ccbbc48ed6fb486e96184da94329291a46b27d2b891ecb87185c909ec','Genuine ROOT CAP4 operator')
    need(not (A/'ROOT_ACTUAL_POST_INSPECTION.json').exists() and not (A/'ROOT_POST_RUNTIME_EVIDENCE.json').exists() and not (A/'ROOT_POST_ACTUAL_READONLY_COMMANDS.json').exists(),'No replacement of ROOT post/evidence');os.umask(0o022)
    post=load(A/'post_acceptance_verification.json');contract=load(H/'ROOT_POST_CONTRACT.json');need(sha(raw(H/'PREPARATION_MANIFEST.json'))==PREP and sha(raw(H/'ROOT_POST_CONTRACT.json'))==CONTRACT and contract['schema']=='pr47-future-ROOT-whole-post-contract/v1' and contract['source_only'] is True,'Exact actually closed47 SOURCE/contract');need(type(contract['future47_required_ROOT_complete_keyset']) is list and len(contract['future47_required_ROOT_complete_keyset'])==22,'Exact22-key normative ROOT contract')
    fresh=load(A/'ROOT_FRESH_ACCEPTANCE_INPUT_PREIMAGES.json');before_native=native(fresh);pre=load(A/'integration_preflight.json');overlay=load(A/'integration_check.json');accept=load(A/'acceptance.json');remote=load(A/'remote_merge_receipt.json');final=load(A/'integration_finalization.json');need(pre['main_before']==fresh['current_head'] and fresh['approved_by_root'] is True and fresh['schema']=='pr47-root-fresh-acceptance-input-preimages/v1','Actual fresh/preflight authority');pinnames=['preparation_manifest_sha256','final_plan','final_plan_sha256','final_receipt','final_receipt_sha256','final_manifest','final_manifest_sha256','reconciliation_capture','reconciliation_capture_sha256','previous_mirror','previous_mirror_sha256','previous_post','previous_post_sha256','fresh_preimage','fresh_preimage_sha256','root_bindings','root_bindings_sha256'];pins={n:post[n] for n in pinnames};need(pins['preparation_manifest_sha256']==PREP,'Actual phase/post SOURCE pin');caps=phase_captures(pins,overlay,fresh)
    prepared=load(H/'PREPARATION_MANIFEST.json');need(prepared['schema']=='pr47-acceptance-source-closure/v1' and prepared['self_excluded']==['PREPARATION_MANIFEST.json'] and type(prepared['files_count']) is int and prepared['files_count']==len(prepared['files'])==126 and len({z['path'] for z in prepared['files']})==126,'Exact pinned126 source before any production import')
    for z in prepared['files']:check(H,z);need(stat.S_IMODE((H/z['path']).stat().st_mode)==0o444,'Every entire prepared source body and full0444 before import')
    names={z['path'] for z in prepared['files']}|{'PREPARATION_MANIFEST.json'};need({q.relative_to(H).as_posix() for q in H.rglob('*') if q.is_file()}==names and {q.relative_to(H).as_posix() for q in H.rglob('*') if q.is_dir()}=={p.as_posix() for n in names for p in PurePosixPath(n).parents if p.as_posix()!='.'} and all(not q.is_symlink() and (q.is_file() or q.is_dir()) for q in H.rglob('*')) and stat.S_IMODE((H/'PREPARATION_MANIFEST.json').stat().st_mode)==0o444,'Complete fixed SOURCE topology and self mode before import')
    D=A/'ROOT_POST_ACTUAL_READONLY_COMMANDS';D.mkdir(exist_ok=False);put(D/'PRELAUNCH_SOURCE.py',SOURCE);put(D/'PRELAUNCH_OPERATOR.py',raw(OUTER));sys.path.insert(0,str(H));import pr47_guards as g
    g.git_bytes=git
    actual=argparse.Namespace(execute=True,**pins);frozen,gatepins=g.gates(actual);need(eq(gatepins,pins),'Entire actual17 gate pins');g.canonical(frozen,True);g.manifest(K,'MANIFEST.json',accept['canonical_manifest_sha256'],1339,frozen=True);need(accept['canonical_manifest_entries']==1339 and len(overlay['canonical_overlay_files'])==1337,'Exact actual1339 payload+self versus1337 merge overlay');g.accepted_invariants(load(K/'acceptance.json'),pins,pre);g.accepted_invariants(accept,pins,pre,audit=True)
    merge=accept['merge_commit'];need(merge==post['merge_commit']==final['merge_commit']==remote['mergeCommit']['oid'] and git('show','-s','--format=%P',merge).decode().strip().split()==[pre['main_before'],HEAD] and git('merge-base',HEAD,BASE).decode().strip()==BASE,'Exact actual merge/original parent/base identity');git('merge-base','--is-ancestor',merge,'HEAD');need(git('branch','--show-current').decode().strip()=='main' and git('show','-s','--format=%T',merge).decode().strip()==post['merge_tree']==accept['merge_tree'],'Actual main and whole Git tree identity')
    patch=load(K/'ACCEPTED_QUEUE_PATCH.json');oldq=raw(A/'integration_queue_before.md');queue=raw(R/'unsolved_math_prioritization/QUEUE.md');old=patch['row_before'].encode();new=patch['row_after'].encode();need(sha(oldq)==patch['whole_before_sha256']==pre['whole_queue_before_sha256'] and sha(queue)==patch['whole_after_sha256']==overlay['whole_queue_after_sha256'] and oldq.count(old)==1 and oldq.replace(old,new,1)==queue and queue.replace(new,old,1)==oldq,'Whole actual fresh queue exact inverse replacement preserving every other row');oc=old.split(b'|');nc=new.split(b'|');need([i for i in range(len(oc)) if oc[i]!=nc[i]]==[8,9,11] and oc[8].strip()==b'queued' and nc[8].strip()==b'unsolved' and oc[9].strip()==b'0/5' and nc[9].strip()==b'1/5' and oc[10]==nc[10] and oc[12]==nc[12],'Only selected Status/Turns/Findings, Chat/DOI exact')
    prefix=K.relative_to(R).as_posix()+'/';tree=tree_entries(git('ls-tree','-r','-z',merge));rr=overlay['canonical_overlay_files'];need({n for n in tree if n.startswith(prefix)}=={prefix+z['path'] for z in rr},'Entire original-head1337 Git canonical topology');changed=set(git('diff-tree','-r','--no-commit-id','--name-only','-z',pre['main_before'],merge).decode().split('\0'))-{''};need(changed=={prefix+z['path'] for z in rr}|{'unsolved_math_prioritization/QUEUE.md'},'Exact owned overlay plus one whole queue changed paths')
    expectations=[]
    for z in rr:n=prefix+safe(z['path']);e=tree[n];need(e['mode']=='100644' and e['kind']=='blob','All canonical Git100644 blobs');expectations.append((e['oid'],z['bytes'],z['sha256']))
    initial=tree_entries(git('ls-tree','-r','-z',pre['main_before'],'--',*sorted(g.NATIVE),*fresh['protected_foreign_tracked_paths']))
    for z in fresh['files']:
        n=z['path']
        if n not in {'draft_pr_publication_program_20260930/inventory.json','unsolved_math_prioritization/QUEUE.md','unsolved_math_prioritization/state.json','unsolved_math_prioritization/history.jsonl'}:need(eq(pin(R/n),{k:z[k] for k in ['path','bytes','sha256']}),'Every stable9 fresh full worktree body retained, including ignored caches')
        if n in g.IGNORED_CACHE3:need(n not in tree and n not in initial,'Exact three ignored caches absent from both Git trees');continue
        need(n in tree and n in initial and tree[n]['mode']==initial[n]['mode']=='100644' and tree[n]['kind']==initial[n]['kind']=='blob','Whole tracked native Git100644')
        if n=='unsolved_math_prioritization/QUEUE.md':expectations.append((tree[n]['oid'],len(queue),sha(queue)));expectations.append((initial[n]['oid'],len(oldq),sha(oldq)))
        else:need(eq(tree[n],initial[n]),'All other tracked native Git entries retained');expectations.append((tree[n]['oid'],z['bytes'],z['sha256']))
    for z in pre['foreign_logs']:n=z['path'];e=tree[n];need(eq(e,initial[n]) and (e['mode']+' '+e['kind']+' '+e['oid']+'\t'+n)==z['head_entry'],'Actual merge retained every declared foreign Git entry');expectations.append((e['oid'],None,z['head_sha256']))
    blobs=verify_blob_batch(expectations)
    prior=load(A/'integration_state_before.json');state=load(R/'unsolved_math_prioritization/state.json');plan=load(A/'state_mirror_plan.json');intent=load(A/'state_mirror_intent.json');receipt=load(A/'state_mirror_receipt.json');proposal=load(A/'state_mirror_bindings.json');oldh=raw(A/'integration_history_before.jsonl');newh=raw(R/'unsolved_math_prioritization/history.jsonl');need(len(prior)==37 and len(state)==38 and set(state)==set(prior)|{'2849'} and all(eq(v,state[k]) for k,v in prior.items()) and eq(state,plan['state_after']) and raw(R/'unsolved_math_prioritization/state.json')==plan['state_after_bytes'].encode(),'Every37 prior state preserved and complete exact native state');need(newh==oldh+plan['history_append_bytes'].encode() and len(plan['history_append'])==1 and eq(parse(newh[len(oldh):]),plan['history_append'][0]),'Whole exact retained history prefix plus one event');event=plan['history_append'][0];need(event['id']=='2849' and event['event']=='acceptance_mirror_import' and type(event['turns_used']) is int and event['turns_used']==1 and event['turn_limit']==5 and event['status']=='unsolved' and all(type(z['turns_used']) is int for z in state.values()) and sum(z['turns_used'] for z in state.values())==45,'Exact original1/5 present event,38targets45turns')
    g.mirror_records(pins,pre,plan,intent,receipt,proposal);need(eq(plan,g.rebuild_saved_mirror_plan(proposal,plan['created_at_utc'],raw(A/'integration_state_before.json'),oldh)),'Entire saved plan independently rebuilt at original timestamp');previous=load(R/pins['previous_mirror']);need(eq(proposal['entries'][:-1],previous['entries']) and eq(proposal['duplicate_mirrors'],previous['duplicate_mirrors']) and len(proposal['entries'])==37 and len(proposal['duplicate_mirrors'])==1,'All previous36 primaries and one duplicate retained');m=g.mirror_module(proposal);noop=m.build_plan(R,proposal);m.validate_plan(R,noop);need(noop['history_append']==[] and noop['state_after_bytes'].encode()==raw(R/'unsolved_math_prioritization/state.json') and noop['history_append_bytes']=='' and noop['history_after_sha256']==sha(newh) and raw(R/'unsolved_math_prioritization/history.jsonl')==newh,'Fresh actual replay is a full-byte no-write no-op')
    inv=load(B/'inventory.json');beforeinv=load(A/'integration_inventory_before.json');expected=copy.deepcopy(beforeinv);chosen=next(z for z in expected['items'] if z['number']==47);chosen.update(stage='complete',outcome='unsolved_accepted_partial',queue_status='unsolved',audited_head=HEAD,merge_commit=merge,merged_at=remote['mergedAt'],workflow_completion_estimate_percent=100,original_attempts='1/5',new_substantive_attempts=0,cumulative_attempts='1/5',paper_or_new_doi_or_tracker=False);expected.update(updated_at_utc=final['utc'],last_checkpoint_utc=final['utc'],completed_count=37,program_completion_estimate_percent=37*100/180,completion_estimate_percent=37*100/180,current_pr=48);need(len(beforeinv['items'])==180 and beforeinv['completed_count']==36 and sum(z.get('stage')=='complete' for z in beforeinv['items'])==36 and eq(inv,expected) and sum(z.get('stage')=='complete' for z in inv['items'])==37,'Independent entire180 inventory, other179 records and top-level values exact')
    g.source(K);g.source(C);g.protected_foreign_paths(fresh);g.foreign_check(pre);logs=g.owned_log_append_check(pre);need(fresh['protected_foreign_tracked_paths']==['paper_ii_simultaneous_amplification_referee_audit_2026-08-22/logs/commands.tsv','paper_ii_simultaneous_amplification_referee_audit_2026-08-22/logs/full_transcript.log'] and all(type(z['before_worktree_mode']) is int and z['before_worktree_mode']==z['after_worktree_mode']==0o644 for z in logs['logs']),'Genuine two foreign paper logs only and exact owned0644 prefix appends; no dated live-equality substitute');g.finalization(pins,pre)
    sd=A/'root_final_reconciliation_actual_capture';sealer=load(sd/'CAPTURE.json');need({q.name for q in sd.iterdir()}=={'CAPTURE.json','PRELAUNCH_SOURCE.py','PRELAUNCH_OPERATOR.py','stdout.bin','stderr.bin'} and sha(raw(sd/'PRELAUNCH_SOURCE.py'))==sealer['source_sha256']==sha(raw(H/'seal_final_evidence.py')) and raw(sd/'PRELAUNCH_OPERATOR.py')==raw(A/'capture_root_final_operation.py'),'Complete actual sealerCAP5 source/operator');need(clock(sealer['finished_utc'])<=clock(caps[0]['complete_capture']['started_utc']),'Real sealer exited before preflight')
    for c in sealer['readonly_git_queries']:need(c['actual_execution'] is True and c['completed'] is True and type(c['pid']) is int and c['pid']>0 and type(c['exit_code']) is int and c['exit_code']==0 and c['stderr']=='' and clock(c['started_utc'])<=clock(c['finished_utc']),'Every actual readonly sealer query')
    evidence=[]
    roles=[('source_author','root_pr47_source_acceptance_author_actual_capture',0),('fresh_authority','root_pr47_fresh_acceptance_authority_actual_capture',0),('ready','root_pr47_ready_actual_capture',0),('body','root_pr47_scope_body_update_actual_capture',0),('original_merge_conflict','root_pr47_original_head_merge_actual_capture',1),('exact_stage','root_pr47_exact_overlay_stage_actual_capture',0)]
    literal_operations=dict(source_author=['/usr/bin/python3','-B',str(A/'author_ROOT_acceptance.py'),'--personally-read-complete-source'],fresh_authority=['/usr/bin/python3','-B',str(A/'prepare_fresh_acceptance_ROOT.py')],ready=['gh','pr','ready','47','--repo','AlecKriebel/Math'],body=['gh','pr','edit','47','--repo','AlecKriebel/Math','--body-file',(A/'accepted_pr_body.md').relative_to(R).as_posix()],original_merge_conflict=['/usr/bin/python3','-B',str(A/'merge_original_head_ROOT.py')],exact_stage=['/usr/bin/python3','-B',str(A/'stage_original_overlay_ROOT.py')])
    for role,name,exitcode in roles:row=cap4(A.parent/'pr45_9900007'/name/'CAPTURE.json',exitcode);need(eq(row['complete_capture']['argv'],literal_operations[role]),'Every complete genuine ROOT mutation/source-author argv');evidence.append(dict(role=role,**row))
    byrole={z['role']:z for z in evidence};authorout=load(R/Path(byrole['source_author']['capture']['path']).parent/'stdout.bin');need(eq(authorout,dict(status='PASS_ROOT_COMPLETE_SOURCE_AND_GENUINE_ACTUAL46_BINDINGS',actual_pid=byrole['source_author']['complete_capture']['pid'],prepared=126,adversary=85,individual_external=3478,complete_source_captures=27,actual46_phase_captures=6,plan_references=len(load(A/'ROOT_FINAL_PLAN.json')['immutable_evidence_references']),future_execution_approved=False)),'Entire actual author stdout/counters, not a Boolean approval');freshout=load(R/Path(byrole['fresh_authority']['capture']['path']).parent/'stdout.bin');need(eq(freshout,dict(status='PASS_FRESH_ACTUAL13_MAIN_AUTHORITY',head=fresh['current_head'],files=13,foreign=fresh['protected_foreign_tracked_paths'])) and clock(byrole['fresh_authority']['complete_capture']['started_utc'])<=clock(fresh['created_utc'])<=clock(byrole['fresh_authority']['complete_capture']['finished_utc']),'Full actual fresh authority stdout and creation interval');need(clock(byrole['source_author']['complete_capture']['started_utc'])<=clock(load(A/'ROOT_SOURCE_ACCEPTANCE_REVIEW.json')['utc'])<=clock(load(A/'ROOT_IMMUTABLE_ACCEPTANCE_BINDINGS.json')['created_utc'])<=clock(byrole['source_author']['complete_capture']['finished_utc']),'Actual SOURCE inspection and approval created inside genuine author child')
    commit=cap4(R/safe(args.root_commit_capture));push=cap4(R/safe(args.root_push_capture));need(commit['complete_capture']['argv'][:2]==['git','commit'] and push['complete_capture']['argv']==['git','push','origin','main'],'Actual ROOT commit/push whitelist and complete genuine captures');evidence.extend([dict(role='successful_merge_commit',**commit),dict(role='successful_push',**push)])
    for p in sorted((A.parent/'pr45_9900007').glob('root_pr47_original_head_merge_commit*/CAPTURE.json')):
        c=load(p)
        if c['exit_code']!=0:evidence.append(dict(role='preserved_failed_commit',**cap4(p,c['exit_code'])))
    need(clock(commit['complete_capture']['started_utc'])>=clock(caps[1]['complete_capture']['finished_utc']) and clock(commit['complete_capture']['finished_utc'])<=clock(caps[2]['complete_capture']['started_utc']) and clock(caps[2]['complete_capture']['finished_utc'])<=clock(push['complete_capture']['started_utc'])<=clock(push['complete_capture']['finished_utc'])<=clock(caps[3]['complete_capture']['started_utc']),'Actual successful commit/prepush/push/finalize order')
    observed=parse(command(['gh','pr','view','47','--repo','AlecKriebel/Math','--json','number,url,state,isDraft,headRefOid,headRefName,baseRefName,mergeCommit,mergedAt,body']));need(eq(observed,remote) and remote['body']==raw(A/'accepted_pr_body.md').decode(),'Fresh entire actual remote and accepted body exact')
    expected_post={**contract['future47_required_entire_post_values'],**pins,'utc':post['utc'],'merge_commit':merge,'merge_tree':accept['merge_tree'],'actual_remote_state':'MERGED'};need(eq(post,expected_post) and clock(caps[-1]['complete_capture']['started_utc'])<=clock(post['utc'])<=clock(caps[-1]['complete_capture']['finished_utc']),'Entire typed actual verifier post created during genuine final child');need(eq(before_native,native(fresh)),'ROOT inspection leaves every native13 full body and0644 mode unchanged')
    root_source=load(A/'ROOT_SOURCE_ACCEPTANCE_REVIEW.json');q=root_source['complete_actual_PR46_qualified_whole_post_readback'];need(eq(q['entire_qualified_dated_foreign_record'],load(P46/'ROOT_POST_DATED_FOREIGN_CHANGE_READBACK.json')) and q['dated_foreign_rows_are_not_future_live_closure_dependencies'] is True,'Mandatory genuine46 dated foreign qualification retained, never current authority');check(R,q['dated_record_reference']);check(R,q['actual_whole_post_capture']['capture']);need(eq(load(R/q['actual_whole_post_capture']['capture']['path']),q['actual_whole_post_capture']['complete_capture']),'Entire actual46 qualified whole-post CAP4')
    after_native=native(fresh);need(eq(before_native,after_native),'Final native13 readback remains exact before ROOT-only outputs');result=dict(schema=contract['future47_required_ROOT_schema'],**contract['future47_required_completed_values'],utc=stamp(),entire_post=post,all_six_real_phase_captures=[z['capture'] for z in caps],current13=after_native,final_sealer_actual_capture=pin(sd/'CAPTURE.json'));need(set(result)==set(contract['future47_required_ROOT_complete_keyset']) and len(result)==22 and all(eq(result[k],v) for k,v in contract['future47_required_completed_values'].items()),'Exact22 completed ROOT keys and typed values')
    put(A/'ROOT_POST_ACTUAL_READONLY_COMMANDS.json',encode(COMMANDS));put(A/'ROOT_POST_RUNTIME_EVIDENCE.json',encode(dict(schema='pr47-root-post-runtime-evidence/v1',utc=stamp(),source=pin(Path(__file__)),complete_actual_phase_captures=caps,actual_root_operations=evidence,complete_actual_final_sealer=sealer,complete_owned_log_append_receipt=logs,actual_blob_batch_unique_objects=blobs,all_readonly_commands=pin(A/'ROOT_POST_ACTUAL_READONLY_COMMANDS.json'),native13_before=before_native,native13_after=after_native,PR46_dated_qualification_is_archival_only=True,foreign_live_equality_was_actually_checked=True,no_native_Git_remote_scientific_mutations=True)));put(A/'ROOT_ACTUAL_POST_INSPECTION.json',encode(result));need(eq(after_native,native(fresh)),'Every native13 body/mode preserved through actual ROOT output authoring');print(json.dumps(dict(status='PASS_COMPLETE_ACTUAL_ROOT_POST_INSPECTION',merge_commit=merge,primary_acceptances=37,targets=38,consumed_substantive_turns=45,inspection=pin(A/'ROOT_ACTUAL_POST_INSPECTION.json'),runtime_evidence=pin(A/'ROOT_POST_RUNTIME_EVIDENCE.json'),actual_blob_batch_unique_objects=blobs)))
if __name__=='__main__':main()
