#!/usr/bin/env python3
"""Independent finite quotients, action groupoids, and diagonal-set triangulations."""
from itertools import permutations,product,combinations
from pathlib import Path
import json,hashlib
nassert=0

def ck(b):
 global nassert
 assert b
 nassert+=1
# A finite quotient independently certifies the nonmembership used in the proof.
S3=list(permutations(range(3)));e=(0,1,2)
def mul(a,b):return tuple(a[b[i]] for i in range(3))
def inv(a):return tuple(a.index(i) for i in range(3))
def subgroup(gens):
 s={e};todo=[e]
 while todo:
  a=todo.pop()
  for b in gens:
   c=mul(a,b)
   if c not in s:s.add(c);todo.append(c)
 return s
certificates=0
for a,b,c in product(S3,repeat=3):
 w=mul(mul(mul(c,a),inv(c)),inv(a));newb=mul(b,w)
 ck(mul(newb,inv(w))==b)
 ck(subgroup([a,newb,c])==subgroup([a,b,c]))
 if newb not in subgroup([a,b]):certificates+=1
ck(certificates>0)
a=(1,0,2);b=e;c=(0,2,1)
w=mul(mul(mul(c,a),inv(c)),inv(a))
ck(w not in subgroup([a,b]) and len(subgroup([a,b]))==2)
# Exact free-word tests are supplemental to this different finite-quotient certificate.
def red(w):
 out=[]
 for x in w:
  if out and out[-1]==-x:out.pop()
  else:out.append(x)
 return tuple(out)
def inverse(w):return tuple(-x for x in reversed(w))
def subst(w,images):
 out=[]
 for x in w:out.extend(images[x] if x>0 else inverse(images[-x]))
 return red(out)
word=(3,1,-3,-1)
alpha={1:(1,),2:(2,)+word,3:(3,)}
beta={1:(1,),2:(2,)+inverse(word),3:(3,)}
for length in range(5):
 for w0 in product((1,-1,2,-2,3,-3),repeat=length):
  if red(w0)!=w0:continue
  ck(subst(subst(w0,alpha),beta)==w0)
  ck(subst(subst(w0,beta),alpha)==w0)
  kill={1:(),2:(2,),3:(3,)}
  ck(subst(subst(w0,alpha),kill)==subst(w0,kill))
ck(red(alpha[2])==(2,3,1,-3,-1))
# Fiber criterion in finite action groupoids over B(C2).
def involutions(n):
 return [p for p in permutations(range(n)) if all(p[p[i]]==i for i in range(n))]
action_cases=0
for nx in range(4):
 for ny in range(4):
  for sx,sy in product(involutions(nx),involutions(ny)):
   for f in product(range(ny),repeat=nx):
    if any(f[sx[i]]!=sy[f[i]] for i in range(nx)):continue
    action_cases+=1
    essential=all(any(y in (f[x],sy[f[x]]) for x in range(nx)) for y in range(ny))
    full=True
    for x,x2 in product(range(nx),repeat=2):
     src={g for g in range(2) if (x if g==0 else sx[x])==x2}
     tar={g for g in range(2) if (f[x] if g==0 else sy[f[x]])==f[x2]}
     full=full and src==tar
    fiber_equiv=(len(set(f))==nx==ny)
    ck((essential and full)==fiber_equiv)
# Triangulations independently generated by noncrossing diagonal subsets.
def edge(i,j):return tuple(sorted((i,j)))
def cross(e,f):
 a,b=e;c,d=f
 return a<c<b<d or c<a<d<b
tri_counts={};flip_count=0
for N in range(3,9):
 boundary={edge(i,(i+1)%N) for i in range(N)}
 diags=[e for e in combinations(range(N),2) if e not in boundary]
 triangulations=[frozenset(t) for t in combinations(diags,N-3) if not any(cross(e,f) for e,f in combinations(t,2))]
 Ts=set(triangulations);tri_counts[str(N)]=len(Ts)
 ck(len(Ts)=={3:1,4:2,5:5,6:14,7:42,8:132}[N])
 fan=frozenset((0,i) for i in range(2,N-1));graph={t:set() for t in Ts}
 for t in Ts:
  E=boundary|set(t)
  triangles=[v for v in combinations(range(N),3) if all(e in E for e in combinations(v,2))]
  ck(len(triangles)==N-2)
  increases=[]
  for d in t:
   incident=[v for v in triangles if set(d)<=set(v)]
   ck(len(incident)==2)
   opposites=sorted((set(incident[0])|set(incident[1]))-set(d))
   new=edge(*opposites);u=frozenset((set(t)-{d})|{new})
   ck(u in Ts);ck(new not in E)
   graph[t].add(u);flip_count+=1
   if sum(0 in x for x in u)>sum(0 in x for x in t):increases.append(u)
  ck(t==fan or bool(increases))
 reached={fan};todo=[fan]
 while todo:
  t=todo.pop()
  for u in graph[t]:
   if u not in reached:reached.add(u);todo.append(u)
 ck(reached==Ts)
# Positive marked-subobject control: pointed-set quotients delete A\{0}.
interval_cases=0
for N in range(1,7):
 X=set(range(N))
 for mask in range(1<<(N-1)):
  A={0}|{i+1 for i in range(N-1) if mask>>i&1}
  tail=sorted(X-A)
  image=[]
  for bits in range(1<<len(tail)):
   C=A|{v for k,v in enumerate(tail) if bits>>k&1}
   B={0}|(C-A)
   ck(A|(B-{0})==C)
   image.append(frozenset(B));interval_cases+=1
  ck(len(set(image))==2**len(tail))
root=Path(__file__).resolve().parent
r={'status':'PASS','assertions':nassert,'finite_quotient_nonmembership_certificates':certificates,'action_groupoid_functors':action_cases,'triangulation_counts':tri_counts,'directed_flips':flip_count,'pointed_set_interval_cases':interval_cases,'artifact_sha256':hashlib.sha256((root/'author_replay/PARTIAL_RESULT.md').read_bytes()).hexdigest(),'method':'Independent S3 quotient obstruction; exact free-word substitutions; finite C2-action groupoid fibers; noncrossing diagonal enumeration; pointed-set marked intervals','limits':'These controls supplement the categorical and all-degree arguments audited in REVIEW.md; they do not establish a general arbitrary-wS characterization or novelty.'}
(root/'independent_results.json').write_text(json.dumps(r,indent=2)+'\n');print(json.dumps(r,indent=2))
