#!/usr/bin/env python3
"""Exact certificate for the noncyclic commuting tuple discussed in the audit."""
from fractions import Fraction
import json

def rank(matrix):
    a=[[Fraction(x) for x in row] for row in matrix]
    if not a: return 0
    r=0
    for c in range(len(a[0])):
        p=next((p for p in range(r,len(a)) if a[p][c]),None)
        if p is None: continue
        a[r],a[p]=a[p],a[r]
        t=a[r][c]
        a[r]=[x/t for x in a[r]]
        for k in range(len(a)):
            if k!=r:
                t=a[k][c]
                a[k]=[x-t*y for x,y in zip(a[k],a[r])]
        r+=1
    return r

def product(a,b):
    return [[sum(a[i][k]*b[k][j] for k in range(len(b))) for j in range(len(b[0]))] for i in range(len(a))]

mx=[[0,1,0],[0,0,0],[0,0,0]]
my=[[0,0,1],[0,0,0],[0,0,0]]
d1=[a+b for a,b in zip(mx,my)]
d2=[[-v for v in row] for row in my]+mx
zero3=[[0]*3 for _ in range(3)]
assert product(mx,my)==product(my,mx)==zero3
assert product(mx,mx)==product(my,my)==zero3
assert product(d1,d2)==zero3
assert rank(d1)==1 and rank(d2)==2
# 1, M_x, M_y are linearly independent; products of coordinates vanish.
# Thus the common annihilator is exactly (x,y)^2, minimally generated by
# independent degree-two monomials x^2,xy,y^2, and not by two polynomials.
flatten=lambda a:[v for row in a for v in row]
id3=[[int(i==j) for j in range(3)] for i in range(3)]
assert rank([flatten(id3),flatten(mx),flatten(my)])==3
out={"d":2,"N":3,"commuting":True,"rank_D1":rank(d1),"required_regular_rank_D1":2,"rank_D2":rank(d2),"candidate_CI_rank_threshold":2,"candidate_formula_applied_outside_scope":2,"annihilator":"(x,y)^2","verified_annihilator_minimum_generators":3,"maximum_cyclic_submodule_dimension":2,"conclusion":"D2 threshold alone falsely accepts this noncyclic faithful tuple"}
print(json.dumps(out,indent=2))
