from pathlib import Path
import datetime,hashlib,json,os,shutil
D=Path.cwd(); now=datetime.datetime.now(datetime.timezone.utc).isoformat()
gate=D.parent/'ROOT_MATHEMATICAL_GATE_20261005.json'
shutil.copy2(gate,D/'ACCEPTED_PARENT_MATHEMATICAL_GATE.json')
def files(*names):
 out=[]
 for name in names:
  p=D/name
  if p.exists():
   b=p.read_bytes();out.append({'path':name,'bytes':len(b),'sha256':hashlib.sha256(b).hexdigest()})
 return out
sources=[
 {'id':'HT-v2','title':'Hansen and Takata, Reshetikhin–Turaev invariants of Seifert 3-manifolds for classical simple Lie algebras, and their asymptotic expansions','url':'https://arxiv.org/pdf/math/0209403v2','metadata_url':'https://arxiv.org/abs/math/0209403v2','posted_UTC':'2003-02-02T04:35:03Z','publication':'Journal of Knot Theory and Its Ramifications 13 (2004), 617–668; DOI 10.1142/S0218216504003342','retrieval':'Copied authenticated private source; exact incoming chain in INCOMING_SOURCE_MANIFEST.json. Published journal PDF attempt returned HTTP 403.','read_scope':'Selected sections: normalization and full weight-lattice category in section 4, lens surgery theorem 5.1 and surrounding derivation, Remark 5.3(a), bibliography. Printed p44 independently rendered and visually read. Whole paper not read.','files':files('private_sources/hansen_takata_0209403v2.pdf','private_sources/hansen_takata_0209403v2.txt','private_sources/ht_abs_v2.html','private_sources/ht44.png'),'findings':'Old full A3 shifted r6 example has independently reproduced squared magnitude 1/3 for both L(64,9), L(64,25). Printed complex separation conflicts with exact computations.','gap':'Published final article and any erratum remain unread.'},
 {'id':'HT-v1','title':'Hansen and Takata, same preprint v1','url':'https://arxiv.org/pdf/math/0209403v1','metadata_url':'https://arxiv.org/abs/math/0209403v1','posted_UTC':'2002-09-30T12:15:32Z','retrieval':'HTTP 200 PDF authenticated in RETRIEVAL_LEDGER.json.','read_scope':'Selected Remark 5.3(a) and bibliography, extracted text. Not whole paper.','files':files('private_sources/ht_v1.pdf','private_sources/ht_v1.txt','private_sources/ht_abs_v1.html'),'findings':'The sl4 tau6 L(64,9)/L(64,25) printed lead already occurs in v1.','gap':'No entire v1/v2 textual difference audit claimed.'},
 {'id':'HT-GTM-2002','title':'Hansen and Takata, Quantum invariants of Seifert 3-manifolds and their asymptotic expansions','url':'https://msp.org/gtm/2002/04/gtm-2002-04-006s.pdf','publication_date':'2002-09-19','publication':'Geometry & Topology Monographs 4, 69–87','retrieval':'HTTP 200 PDF authenticated in ADJACENT_RETRIEVAL_LEDGER.json.','read_scope':'Selected introduction, full lattice definitions, lens formula (10), Theorem 4.2, references; whole-file search for examples, 64, separation and lens spaces. Not full read.','files':files('private_sources/ht_2002_gtm.pdf','private_sources/ht_2002_gtm.txt'),'findings':'General higher-rank lens formulas predate PR95. No explicit unequal nonzero magnitude pair in examined sections.','gap':'Other sections not fully read.'},
 {'id':'GP-v1','title':'Guadagnini and Pilo, Three-manifold invariants and their relation with the fundamental group','url':'https://arxiv.org/pdf/hep-th/9612090v1','posted_date':'1996-12-09','publication':'Communications in Mathematical Physics 192 (1998), 47–65; DOI 10.1007/s002200050290','retrieval':'Copied authenticated private source, exact chain in INCOMING_SOURCE_MANIFEST.json.','read_scope':'Section 5 and conclusions read; table headers and selected rows of Tables 1–5 examined, not all numerical rows individually read; other sections not read.','files':files('private_sources/guadagnini_pilo_9612090v1.pdf','private_sources/guadagnini_pilo_9612090v1.txt'),'findings':'Published SU3 tests report agreement for p<=20, shifted k 3..50. Lens tables exhibit phase distinctions, not asserted magnitude counterexamples. No SU5 examples in the examined scope.','gap':'This is numerical finite-range supporting evidence, not a general proof.'},
 {'id':'Zhang-1996-v1','title':'Zhang, Topological Invariants For Lens Spaces And Exceptional Quantum Groups','url':'https://arxiv.org/pdf/q-alg/9612034v1','metadata_url':'https://arxiv.org/abs/q-alg/9612034','posted_UTC':'1996-12-29T03:30:28Z','manuscript_date':'1995 (printed title page)','citation_scope':'Authenticated preprint only; journal attribution deferred to independently verified ROOT metadata','retrieval':'HTTP 200 PDF authenticated in RETRIEVAL_LEDGER.json.','read_scope':'Full extracted text of all ten pages read in nontruncated chunks. PDF not fully visually read; paper says figures available on request, none requested.','files':files('private_sources/zhang_v1.pdf','private_sources/zhang_v1.txt','private_sources/zhang_abs.html'),'findings':'Exceptional G2,F4,E8 odd-root invariants and lens surgery formulas (13),(14); no explicit unequal nonzero pair or resolution of the magnitude conjecture located.','gap':'No priority counterexample deduced from its general formula; roots and groups differ from PR95.'},
 {'id':'Zhang-Carey-1996','title':'Zhang and Carey, Quantum Groups at Odd Roots of Unity and Topological Invariants of 3-Manifolds','url':'https://link.springer.com/article/10.1007/BF02506419','author_upload_url':'https://www.researchgate.net/publication/243194401_Quantum_groups_at_odd_roots_of_unity_and_topological_invariants_of_3-manifolds','author_upload_pdf_url':'https://www.researchgate.net/profile/Alan-Carey/publication/243194401_Quantum_groups_at_odd_roots_of_unity_and_topological_invariants_of_3-manifolds/links/0deec5298a81241fda000000/Quantum-groups-at-odd-roots-of-unity-and-topological-invariants-of-3-manifolds.pdf','publication_date':'1996-12','received_date':'1995-10-16','accepted_date':'1996-05-13','publication':'Communications in Mathematical Physics 182, 619–636; DOI 10.1007/BF02506419','retrieval':'Publisher PDF endpoint returned HTML cookie/paywall page with status 200, not PDF; preserved as misnamed response and explicit HTML copy. Author-upload PDF raw-byte fetch HTTP 403; web cached extraction accessible, identified upload by Alan L. Carey.','read_scope':'Publisher metadata and abstract; author-upload cached PDF text selected introduction, section 2.2, lens section 4, section 5. OCR formulas partly garbled. Not full paper read; screenshots failed/timeouts, no visual confirmation.','files':files('private_sources/zhang_carey_1996.pdf','private_sources/zhang_carey_1996_response.html','private_sources/zhang_carey_1996_response.txt','private_sources/zhang_carey_author_upload_web.json','private_sources/zhang_carey_pdf_link_results.json','private_sources/zhang_carey_cached_pdf_text_final.json'),'findings':'Older classical odd-root lens formula antecedent. A-series explicitly uses gl(r) instead of sl(r); orthogonal construction excludes spinorial analogues. Examined lens section gives general recurrences, no explicit unequal nonzero pair.','gap':'Raw PDF bytes unavailable, final reference page not read, cached mathematical typography unreliable. Cannot assert exhaustive negative result.'},
 {'id':'Takata-1996','title':'Takata, On quantum PSU(n)-invariants for lens spaces','url':'https://www.worldscientific.com/doi/10.1142/S0218216596000497','attempted_pdf_url':'https://www.worldscientific.com/doi/pdf/10.1142/S0218216596000497','publication_date':'1996','publication':'Journal of Knot Theory and Its Ramifications (1996); unverified pages omitted','retrieval':'Primary publisher metadata/search result; PDF HTTP 403.','read_scope':'Title and bibliographic metadata only; full text unread.','files':[],'findings':'Potential projective invariant antecedent. No full ordinary SU(n) magnitude conclusion inferred.','gap':'Exact category, levels and examples not checked in full text.'},
 {'id':'HT-forthcoming-Gauss','title':'Hansen and Takata, Generalized Gauss sums and quantum invariants of lens spaces','url':'https://arxiv.org/pdf/math/0209403v2','publication_date':None,'retrieval':'Mentioned as in preparation in HT reference list; bounded exact-title/author searches did not locate a separate primary full text.','read_scope':'Bibliographic mention only; separate work unread/unlocated.','files':[],'findings':'Could potentially explain or alter the Remark 5.3 example.','gap':'Existence/publication status and contents unresolved; no assumption of withdrawal or nonpublication.'},
 {'id':'Gang-v1','title':'Dongmin Gang, Chern-Simons theory on L(p,q) lens spaces and Localization','url':'https://arxiv.org/pdf/0912.4664v1','metadata_url':'https://arxiv.org/abs/0912.4664','posted_UTC':'2009-12-23T20:15:21Z','latest_metadata_version':'v2 2010-02-01T11:37:29Z; v2 full text not read','publication':'Journal of the Korean Physical Society 74 (2019), 1119–1130; DOI 10.3938/jkps.74.1119','retrieval':'HTTP 200 PDF authenticated in LATER_RETRIEVAL_LEDGER.json.','read_scope':'Selected introduction, U(N) lens formula (1.4)/(1.5), terminal lens derivation (4.28), discussion and references. Not full paper.','files':files('private_sources/gang_abs.html','private_sources/gang_v1.pdf','private_sources/gang_v1.txt'),'findings':'General lens U(N) formula tied to HT; no explicit same-p unequal-nonzero ordinary SU5 pair in examined sections. v1 assumes an unproved sector sign for general q in comparison.','gap':'U(N) must not be silently identified with full SU(N); later corrected v2 and final article unread.'},
 {'id':'Kubo-Yokoyama-v1','title':'Kubo and Yokoyama, Topological phase, spin Chern-Simons theory and level rank duality on lens space','url':'https://arxiv.org/pdf/2108.09300v1','metadata_url':'https://arxiv.org/abs/2108.09300','posted_UTC':'2021-08-20T17:54:36Z','latest_metadata_version':'v2 2022-04-15T05:20:10Z; v2 full text unread','publication':'JHEP 04 (2022) 074; published 2022-04-13','retrieval':'HTTP 200 PDF authenticated in LATER_RETRIEVAL_LEDGER.json.','read_scope':'Selected introduction and definition (2.1), SU(N) matrix model (3.2), phase statement (3.4), Tables 2,3,6,7 and surrounding duality claims, full discussion. Not full paper.','files':files('private_sources/kubo_yokoyama_abs.html','private_sources/kubo_yokoyama_v1.pdf','private_sources/kubo_yokoyama_v1.txt'),'findings':'Lens parameter is L_b(n,1), with q fixed to 1. Tables compare level-rank dual theories, and vary n, including zeros; no comparison of L(5,1) with L(5,2).','gap':'Spin, level convention and phase subtleties forbid substituting table values into PR95; later version/final article unread.'},
 {'id':'Ohtsuki-2002','title':'Ohtsuki, Problems on invariants of knots and 3-manifolds','url':'https://msp.org/gtm/2002/04/gtm-2002-04-024s.pdf','publication_date':'2002','retrieval':'Copied authenticated private source; exact bytes in incoming manifest.','read_scope':'Unread by this family. Target accepted from parent gate/task; original conjecture/history assigned to another independent family.','files':files('private_sources/ohtsuki_2002_published.pdf','private_sources/ohtsuki_2002_published.txt'),'findings':'No independent historical formulation conclusion asserted by this family.','gap':'Deliberate division of scope; original REVIEW.md never opened.'}
]
Path('SOURCE_LEDGER.json').write_text(json.dumps({'UTC':now,'operator_PID':os.getpid(),'copyright':'PDFs, source text and renderings remain private local audit evidence; no uploads or outreach.','sources':sources},indent=2)+'\n')
queries=[
 '"L(64, 9)" quantum invariant','"quantum" "lens spaces" "SU(5)" invariant','"Conjecture 7.5" "quantum" "fundamental group"',
 '"Hansen" "Takata" "Generalized Gauss sums" quantum','"L(64,9)" "sl" quantum','"On quantum PSU(n)-invariants for lens spaces"',
 '"Generalized Gauss sums and quantum invariants of lens spaces"','"Topological invariants for lens spaces and exceptional quantum groups"','"Hansen Takata" "lens spaces" "Gauss"',
 '"Hansen" "Takata" "64" "25" invariant','"Hansen" "Takata" "Gauss sums" "forthcoming"','"quantum" "invariant" "fundamental group" "counterexample" lens','"Guadagnini" "Pilo" "conjecture" "SU" counterexample',
 '"Quantum groups at odd roots of unity and topological invariants of 3-manifolds"','"Quantum invariants of Seifert 3-manifolds and their asymptotic expansions" Hansen Takata','"lens" "SU(5)" "invariants" site:arxiv.org','"lens" "Guadagnini" "Pilo" "counterexample" site:arxiv.org',
 '"Quantum groups at odd roots" site:projecteuclid.org','"On quantum PSU(n)-invariants for lens spaces" site:worldscientific.com','"Generalized Gauss sums" "Hansen" "Takata"','"L(5,1)" "L(5,2)" "SU(5)"',
 'Zhang Carey 182 619 636 1996 quantum groups [domain projecteuclid.org]','Quantum groups at odd roots of unity topological invariants Zhang Carey [domain arxiv.org]','Takata PSU n lens spaces 1996 invariants [domain worldscientific.com]','lens SU(5) Chern Simons quantum invariant [domain arxiv.org]',
 '"absolute value" "lens spaces" "SU(n)"','"fundamental group" "SU(5)" "invariant"','"Reshetikhin–Turaev" "lens spaces" "counterexample"','"Reshetikhin-Turaev invariants of Seifert 3-manifolds for classical simple Lie algebras" "doi"',
 '"Zhang" "Carey" "619" "636" "euclid"',
 '"Chern-Simons theory on L(p,q) lens spaces and Localization"','"Topological phase, spin Chern-Simons theory and level rank duality on lens space"','"3475" "1550" "quantum"','"L(5, 1)" "L(5, 2)" "quantum" "SU"'
]
Path('SEARCH_SCOPE.json').write_text(json.dumps({'UTC_closed':now,'operator_PID':os.getpid(),'scope':'Bounded primary-source higher-rank/lens priority audit. Not worldwide novelty clearance.','queries':queries,'source_opens':'Exact source URLs and retrieval status in SOURCE_LEDGER.json and retrieval ledgers.','captures':files('private_sources/web_search_batch5.json','private_sources/web_search_batch6.json','private_sources/web_search_batch7.json','private_sources/web_search_batch8.json','private_sources/web_search_batch10.json'),'capture_limit':'Earlier web query results and miscellaneous source opens remain in complete tool transcript, not separate on-disk raw web-result files. Query strings above preserve the bounded search scope. Web calls have no shell PID/exit; recorded subprocess requirements apply to calculations and local retrievals.','excluded':'No external outreach, account actions, publication, preprint, Git, PR mutation, tracker/UI mutation; no broad rank/level scan or new PR95 proof search.','nonprimary_results':'Secondary catalogues/search snippets used only for navigation, never as mathematical evidence.','unread_additional_leads':['Brini, Griguolo, Seminara, Tanzini arXiv:0809.1610: reference/title lead only, no full text inspected','Kirby–Melvin Dedekind-sum lens examples: navigation result only; not counted as quantum magnitude evidence','Sokolov 1997 Turaev–Viro classification: root reports access failure, not inspected here']},indent=2)+'\n')
with Path('RESEARCH_LOG.md').open('a') as f:
 f.write('\n- '+now+': Bounded adjacent primary reading completed; 85% family audit completion. Older formulas authenticated and selected tables checked. Independent adversary confirms exact negative-chain surgery |tau|^2=1/3; its sine-product cross-check/report is finishing. Remaining work: final synthesis and sealed byte/process integrity manifest. No worldwide novelty conclusion.\n')
print(json.dumps({'UTC':now,'operator_PID':os.getpid(),'created':['SOURCE_LEDGER.json','SEARCH_SCOPE.json','ACCEPTED_PARENT_MATHEMATICAL_GATE.json'],'source_count':len(sources),'query_count':len(queries)},indent=2))
