# PR45 current science, source and provenance qualifications

PR45 /9900007 /AMR-098-0007 remains UNSOLVED. The original9439-byte partial proof rejects only the illustrative synchronous metric condition for a single fixed joint construction. The broader general two-process characterization is neither supplied nor ruled out. Novelty remains unestablished. The original fair binary process has independent flip probabilities1/(k+2); its shifted laws converge weakly to the stationary nonergodic constant-path mixture. The all-fixed-couplings mismatch tends to1/2 by full-path conditional projection and finite-history L1 approximation, not a finite diagnostic count. The stated metric law is tied to the stated product metric. Other compatible metrics retain the failure of convergence to zero, without a claimed identical numerical limit. Offsets are nonnegative and finite or uniformly tight, possibly dependent; arbitrary escaping offsets are excluded and can repair this example. Each-n different couplings are not one fixed coupling. Setwise convergence fails, so distinct9900005 is not revised.

Both newly closed independent families validate this original scoped claim and retain its exact gap. The probability family's separate iid duplicate-block mechanism and growing first-hit-offset construction are audit-only boundary evidence; they are not an expanded original submission, new accepted theorem or new author attempt. Its early approximation imprecision and later correction stay preserved. Neither family re-executed the original helper. Future ROOT must independently reproduce unchanged helpers in private copies and inspect all actual outputs. The historical independent helper writes its receipt beside itself; a private copied review/PARTIAL is required. Saved885/3044 labels are historical observations and finite checks never establish the arbitrary-infinite-coupling quantifier, source scope or full problem.

Historical SOURCES, source_manifest and all18 originals stay byte exact. Their September30 Asmussen access failure is a dated fact. NEW access on October3 obtained Asmussen1992's complete scanned primary PDF1177292B/SHAf97b11902da4a2a980dbf114d8dca546448ab0155c479a839e4adb398c938191; the literal family rendered all13 article pages and read OCR, visually checking pp739–741. OCR contains errors and this is a bounded scoped comparison, not an independent proof audit of the whole article. Lemma2.1 gives a sufficient continuous-time one-time-marginal condition with potentially different construction for each epsilon, small finite offset, finite eventual time and strictly stationary right-continuous comparison process; Remark2.1 allows an epsilon discrepancy. It is not necessity for arbitrary weak path-shift convergence or a single synchronous joining, and no novelty follows. NEW current presentations must not repeat the old failure as present access state.

The original Thorisson author preprint's relevant Section3 pp3–4 is available only as independently recovered indexed text here, without full original PDF or pixels. The published2011 source remains metadata/subscription preview, so no full published/preprint comparison is certified. The six-page density/Skorohod preprint was freshly retrieved and read by the literal family; it builds a sequence of copies and does not enforce their being shifts of one path. Bounded search and comparisons do not prove exhaustive literature absence or universal present openness.

Original head d9b4acf5d070d1f04ffac86a4f08916a5629ff16, dated GitHub base c6975ca76f9f667f1250ba403d0e6da2aafe14d0 and actual merge base01358d66fc67d1c462bddf31c0d4ee5b120e6737 are distinct and separately checked. Original turns remain1/5,new0,audit0. Original export's queue-prefix error and separate successful repair remain preserved as genuine administrative histories; no retrospective successful execution is fabricated. Historical model, reasoning, deadline, PASS and access claims remain dated attributions. Current model/reasoning/deadline/verdict are explicitly null. NEW whole-current review remainsPENDING after future freeze.

AI tools were used extensively. This is unrefereed work with no claimed human peer review or formal certification. Future scoped repository acceptance would publish a partial report, with no paper, new DOI or tracker row. All64 literal foreign primary/access/OCR artifacts are individually hash-bound and excluded from authored packet bodies, including PDF bytes, indexed source text, OCR, pixels and their access captures. Full raw caches/SQL are likewise dependencies only, never copied as publication bodies. Dated native bindings are historical records, not current authority; separate fresh13/current-main approval is required before and after staging. These qualifications apply globally to every current presentation and metadata wrapper while original bodies remain literal archives.

Historical literal body follows. Runtime/model/reasoning/deadline, search/access and PASS labels are dated claims. They do not approve this current packet. Read the global SOURCE_PRECISION_QUALIFICATIONS.md first; NEW whole-current review PENDING.

# Source and prior-work audit

Checked 2026-09-30. The outcome is a partial obstruction to the source's suggested synchronous coupling, with no claim of a complete characterization or historical novelty.

## Original scope

**Hermann Thorisson, Some Open Probability Problems**, Section 3, preprint pp.3–4. [Primary preprint](https://cms.dm.uba.ar/depto/public/Some%20Open%20Problems-preprint.pdf). The complete relevant section, including Theorem3.1, Corollary3.1, Problems3.1–3.3 and the Skorohod discussion, was read through indexed text from the primary PDF. The direct HTTP/HTTPS PDF endpoints returned502, and a PDF screenshot could not be recovered. A complete binary copy was not obtained; this limitation is retained rather than presenting the pinned transcription as a newly downloaded original.

The section specifies one-sided paths and deterministic shifts. Problem3.3 asks for a two-process characterization and then offers synchronous metric convergence as an example. It does not explicitly label the convergence mode or assume an ergodic limit. Random-time distributional coupling is a different preceding notion. The binary construction addresses the example in probability and almost surely; it leaves the broad question unresolved.

The primary publisher and the author's institutional record identify the published version as **Open problems in renewal, coupling and Palm theory**, Queueing Systems68,313–319(2011), [DOI10.1007/s11134-011-9241-2](https://link.springer.com/article/10.1007/s11134-011-9241-2). The publisher abstract and metadata were accessible, but the full published text was subscription content. No claim of a line-by-line published/preprint comparison is made.

## Relevant coupling literature

**Thorisson, On Coupling and Convergence in Density and in Distribution**, preprint listed by the IHP2008 program. [Full author preprint hosted by CNRS](https://interacting.math.cnrs.fr/HT_Skorohod-Dudley%204.pdf), [program listing](https://interacting.math.cnrs.fr/papers-written_ihp2008.html). The complete six-page PDF was retrieved and read. Its Theorem1 and Corollary1 construct couplings of a sequence of process copies, with agreement on growing windows under the stated density/finite-window hypotheses. The theorem does not identify those copies as shifts of one original path. Its Skorohod–Dudley statement is likewise a sequence-of-copies result. These established constructions are credited and are not a solution to the two-process consistency requirement.

**Søren Asmussen, On Coupling and Weak Convergence to Stationarity**, Annals of Applied Probability2(3),739–751(1992), [DOI10.1214/aoap/1177005657](https://doi.org/10.1214/aoap/1177005657), [author institution metadata](https://pure.au.dk/portal/en/publications/on-coupling-and-weak-convergence-to-stationarity). Metadata and the correct DOI were checked. Direct publisher PDF retrieval returned an access-challenge HTML response, so this paper was not read in full and no theorem from it is used in the proof. It remains a relevant prior-art lead, not evidence of novelty.

Current primary-source searches for the exact problem, weak shift convergence and asymptotic coupling did not identify a verified full resolution in this bounded audit. That absence is not proof that the question is still open. The supplied upstream report is earlier literature triage; its open-status label is not treated as a mathematical certificate. No outside author was contacted.

## Prior campaign attempt and distinct target

Repository/history/branch/PR checks found no earlier campaign attempt on9900007. The existing9900005 entry concerns the distinct setwise-versus-total-variation question3.1. The construction here does not satisfy setwise convergence, as the invariant event of eventually constant paths shows. It therefore does not duplicate or revise that result. A two-sided symbolic state can itself be used as the state space of a one-sided process; notation alone does not invalidate an earlier construction.

## Provenance and mathematical inputs

The pinned source record and upstream report are preserved in source_record.json. The new argument uses an explicit inhomogeneous binary chain, telescoping products, conditional-expectation approximation by finite histories, and compact product-space weak convergence. Those are standard tools. The exact finite checker supports the identities but not the infinite quantifiers. No novelty claim follows from the absence of a located identical example.
