#!/usr/bin/env python3
"""Fresh per-action root decisions after actual candidate/output review."""
from pathlib import Path
from datetime import datetime,timezone
import hashlib,json,os,sys
A=Path(__file__).resolve().parents[1];D=A/'native_post_assess_carryforward_v2_20261006';F=A/'native_actual_input_preparation_20261006/root_fresh_native_preflight_20261006/EXECUTION_INPUTS.json'
def can(x):return (json.dumps(x,sort_keys=True,ensure_ascii=False,indent=2,allow_nan=False)+'\n').encode()
def hp(b):return {'bytes':len(b),'sha256':hashlib.sha256(b).hexdigest()}
def pin(f):return {'path':str(f.relative_to(A)),**hp(f.read_bytes())}
def read(f):return json.loads(f.read_bytes())
def need(x,m):
 if not x:raise RuntimeError(m)
action=sys.argv[1];adpath=Path(sys.argv[2]);extra_path=Path(sys.argv[3]);need(action in ('export','acceptance_commit','ready','merge','status') and adpath.is_relative_to(A) and extra_path.is_relative_to(A),'Explicit reviewed action and dedicated inputs')
packet=read(F);raw=F.read_bytes();sha=hp(raw)['sha256'];W=D/'workspaces'/('candidate_'+sha[:16]);receipt=W/'CANDIDATE_RECEIPT.json';r=read(receipt);ad=read(adpath);program=D/'native_acceptance_actions_v3.py';outer=A/'publication_build_v1/record_native_action_v3.py'
need(ad['schema']=='pr110-actual-native-candidate-adversary/v1' and ad['actual_review'] is True and ad['clearance'] is True and ad['required_findings']==[] and ad['packet_sha256']==sha and ad['candidate_receipt_pin']==hp(receipt.read_bytes()) and ad['action_program_pin']==pin(program) and ad['outer_launcher_pin']==pin(outer) and ad['continuation_program_pin']==r['continuation_program_pin'] and ad['integration_inputs_pin']==r['integration_inputs_pin'],'Fresh actual candidate/source/outer adversary')
root=read(A/'ROOT_ACTUAL_NATIVE_CANDIDATE_REVIEW_AUTHENTICATION_20261006.json');need(root['main_parent']==r['main_parent'] and root['integration_inputs_pin']==r['integration_inputs_pin'] and root['candidate_receipt_pin']==hp(receipt.read_bytes()) and root['packet_sha256']==sha and root['required_findings']==[] and root['native_candidate_actual_authenticated'] is True and root['adversary_decision_pin']==pin(adpath),'Actual completed independent root candidate review')
checks={'full_actual_candidate_DIFF_and_offer_reviewed','actual_native_PID_resources_and_process_custody_authenticated','all17_originals_and_nonempty_prior_preserved','source_cache_readonly_and_original_2_of_5_no_extra_search_turn','unrelated_scores_order_physical_CSV_history_and_campaign_preserved','accepted_full_mathematical_resolution_and_bounded_priority','actual_publication_tracker_and_clean_whole_package_R1_R2','this_exact_source_and_main_only_exact_tree_integration_reviewed'}
need(set(root['scope_checks'])==checks and all(v is True for v in root['scope_checks'].values()),'Root completed all substantive scope checks')
now=datetime.now(timezone.utc).isoformat();label='pr110_'+action+'_20261006';gate={'schema':'pr110-native-action-commission/v1','role':'root','action':action,'operation_label':label,'UTC':now,'actual_root_PID':os.getpid(),'actual_review':True,'clearance':True,'required_findings':[],'template_only':False,'fixture':False,'simulated':False,'program_pin':pin(program),'packet_pin':pin(F),'packet_sha256':sha,'continuation_program_pin':r['continuation_program_pin'],'integration_inputs_pin':r['integration_inputs_pin'],'candidate_adversary_pin':pin(adpath),'candidate':str(W),'candidate_receipt_pin':hp(receipt.read_bytes()),'DIFF_pin':r['DIFF_pin'],'main_parent':r['main_parent'],'original_head':packet['identity']['original_head'],'DOI':'10.5281/zenodo.23191247','tracker_range':"'Math Puzzles'!A32:D32",'scope_checks':root['scope_checks'],'outer_launcher_pin':pin(outer),'root_actual_candidate_review':pin(A/'ROOT_ACTUAL_NATIVE_CANDIDATE_REVIEW_AUTHENTICATION_20261006.json'),'ps_current_executable':{'absolute_path':'/bin/ps',**hp(Path('/bin/ps').read_bytes())},'outer_startup_cwd':str(A.parents[2]),'outer_whole_deadline_seconds':300,'kernel_SIGKILL_before_child_registration_complete_containment_claimed':False,'process_cleanup_scope':'Actual recorded/observed groups; interrupted or unverified actions require explicit reconciliation; no blind mutation retry.'}
extra=read(extra_path);need(not(set(extra)&set(gate)),'No override of reviewed common facts');gate.update(extra);target=A/'actual_action_commissions_20261006';target.mkdir(exist_ok=True);file=target/(action+'_ROOT_GATE.json');need(not file.exists(),'Unique current action decision');file.write_bytes(can(gate));print(json.dumps({'actual_root_PID':os.getpid(),'UTC':now,'action':action,'gate':str(file),'gate_pin':pin(file),'actual_action_executed':False}))
