#!/usr/bin/env python3
"""Root's current decision after independently reading the actual sealed review."""
from pathlib import Path
from datetime import datetime,timezone
import hashlib,json,os,sys,types
A=Path(__file__).resolve().parents[1];D=A/'native_execution_programs_v1';F=A/'native_actual_input_preparation_20261006/root_fresh_native_preflight_20261006/EXECUTION_INPUTS.json'
def can(v):return (json.dumps(v,sort_keys=True,ensure_ascii=False,indent=2,allow_nan=False)+'\n').encode()
def hp(b):return {'bytes':len(b),'sha256':hashlib.sha256(b).hexdigest()}
def pin(f):return {'path':f.relative_to(A).as_posix(),**hp(f.read_bytes())}
def read(f):return json.loads(f.read_bytes())
def need(v,m):
 if not v:raise RuntimeError(m)
def module(name,file):
 m=types.ModuleType(name);m.__file__=str(file);sys.modules[name]=m;exec(compile(file.read_bytes(),str(file),'exec'),m.__dict__);return m
adpath=Path(sys.argv[1]);need(adpath.is_relative_to(A) and adpath.is_file(),'Dedicated actual adversarial decision');ad=read(adpath);packet=read(F);raw=F.read_bytes();programs={n:s['sha256'] for n,s in packet['program_files'].items()}
need(ad['schema']=='pr110-concrete-native-commission/v1' and ad['role']=='adversary' and ad['actual_review'] is True and ad['clearance'] is True and ad['template_only'] is False and ad.get('fixture',False) is False and ad.get('simulated',False) is False and ad['packet_sha256']==hp(raw)['sha256'] and ad['program_hashes']==programs and ad['main_parent']==packet['main_parent'],'Genuine exact fresh independent decision')
rootad=read(A/'ROOT_PREEXEC_ADVERSARY_AUTHENTICATION_20261006.json');need(rootad['all_manifest_payloads_authenticated']==881 and rootad['required_findings']==[] and rootad['adversary_decision_pin']==pin(adpath),'Completed root full-artifact authentication before commission')
for name,spec in packet['program_files'].items():need(hp((A/spec['path']).read_bytes())=={k:spec[k] for k in ('bytes','sha256')},'Program drift')
rootauth=read(A/'ROOT_ACTUAL_NATIVE_PACKET_AUTHENTICATION_20261006.json');need(rootauth['packet']==pin(F) and rootauth['main_parent']==packet['main_parent'] and rootauth['actual_publication_fullbody_protocol_pass'] is True and rootauth['actual_GWS_protocol_pass'] is True,'Actual complete root authentication')
roots={'mathematics':A/'ROOT_MATHEMATICAL_GATE_20261006.json','priority':A/'ROOT_PRIORITY_CLEARANCE_AFTER_M1_20261006.json','package':A/'publication_ready_v1_SEAL.json','whole_package_R1':A/'ROOT_WHOLE_PACKAGE_R1_AUTHENTICATION_20261006.json','whole_package_R2':A/'ROOT_WHOLE_PACKAGE_R2_AUTHENTICATION_20261006.json','pre_execution_adversary':adpath}
need(read(roots['mathematics'])['mathematical_clearance'] is True and read(roots['priority'])['bounded_priority_clearance'] is True and read(A/'ROOT_PUBLICATION_READINESS_V1_20261006.json')['publication_ready'] is True,'Current scientific acceptance based on full antecedents')
for n in ('whole_package_R1','whole_package_R2'):need(read(roots[n])['required_findings']==[],'Clean distinct package reviews')
for row in read(roots['package'])['files']:need(hp((A/'publication_ready_v1'/row['path']).read_bytes())=={k:row[k] for k in ('bytes','sha256')},'Unchanged published package')
outer=A/'publication_build_v1/record_native_launch.py';need(ad.get('outer_launcher_pin')==pin(outer),'Fresh reviewer must bind exact repaired outer source')
E=D/'actual_commission_v2_20261006';E.mkdir(mode=0o700,exist_ok=False);configpath=E/'CONFIG.json';env=packet['runtime']['python_environment'];cf=env.get('__CF_USER_TEXT_ENCODING','')
# Match the actual ordered argv constructed by the fully read outer source.
ordered={'PATH':'/usr/bin:/bin','LC_ALL':'C','LANG':'C','TZ':'UTC'}
if sys.platform=='darwin':ordered['__CF_USER_TEXT_ENCODING']=cf
need(ordered==env,'Exact declared clean startup environment')
argv=['/usr/bin/env','-i']+[k+'='+v for k,v in ordered.items()]+['/bin/sh',str(D/'native_launcher.sh'),packet['runtime']['binaries']['python']['resolved_absolute_path'],str(D/'native_runner.py'),str(configpath),cf]
now=datetime.now(timezone.utc).isoformat();root={'schema':'pr110-concrete-native-commission/v1','role':'root','template_only':False,'fixture':False,'simulated':False,'actual_review':True,'clearance':True,'UTC':now,'actual_root_PID':os.getpid(),'packet_sha256':hp(raw)['sha256'],'program_hashes':programs,'main_parent':packet['main_parent'],'adversary_sha256':hp(adpath.read_bytes())['sha256'],'actual_services_independently_authenticated':True,'whole_package_R1_R2_clean':True,'accepted_mathematical_full_resolution':True,'bounded_novelty_and_source_credit_checked':True,'native_candidate_preparation_commissioned':True,'exact_identity':packet['identity'],'original_source_pin':packet['original']['files']['source_record.json'],'nonempty_prior_pin':packet['original']['files']['prior_imported_report.json'],'package_manifest_pin':packet['package']['manifest'],'all_antecedent_evidence_roles_freshly_bound_to_packet':{n:{'packet_sha256':hp(raw)['sha256'],'evidence':pin(f)} for n,f in roots.items()},'final_evidence_role':'This genuine fresh current root decision, based on fully read and independently authenticated antecedent bodies; no reconstructed historical gate events.','root_preexecution_adversary_authentication':pin(A/'ROOT_PREEXEC_ADVERSARY_AUTHENTICATION_20261006.json'),'root_actual_packet_authentication':pin(A/'ROOT_ACTUAL_NATIVE_PACKET_AUTHENTICATION_20261006.json'),'root_actual_service_authentication':pin(A/'ROOT_ACTUAL_PUBLICATION_TRACKER_AUTHENTICATION_20261006.json'),'orchestration_contract_correction':'Explicitly accept frozen concrete README two fresh exact-packet adversary/root decisions in place of seven legacy validator gate files. Original mathematical, source, service and preservation evidence remains fully authenticated and bound here; no substantive scientific gate waived.','outer_launcher_pin':pin(outer),'ps_current_executable':{'absolute_path':'/bin/ps',**hp(Path('/bin/ps').read_bytes())},'outer_launcher_contract':{'argv':argv,'cwd':str(A),'environment_sha256':hashlib.sha256(can(ordered)).hexdigest(),'deadline_seconds':300,'stdout_cap':1048576,'stderr_cap':65536,'ancestry_probe_count_cap':160,'ancestry_file_count_cap':480,'ancestry_aggregate_cap':16*1024*1024},'kernel_SIGKILL_before_child_registration_complete_containment_claimed':False,'process_cleanup_scope':'Actual observed and recorded groups; trusted private preparation, no hostile same-user containment or hard Darwin memory guarantee. Interrupted or unverified runs cannot be exported.','live_export_or_Git_mutation_authorized_by_this_commission':False,'original_effort':'2/5','new_central_proof_search_turns':0}
rootpath=E/'ROOT_COMMISSION.json';rootpath.write_bytes(can(root));cfg={'schema':'pr110-concrete-native-config/v1','template_only':False,'packet':pin(F),'adversary':pin(adpath),'commission':pin(rootpath)};configpath.write_bytes(can(cfg))
r=module('native_runner',D/'native_runner.py');r.load_bootstrap(configpath)
print(json.dumps({'actual_root_PID':os.getpid(),'config':str(configpath),'root_commission':str(rootpath),'packet_sha256':hp(raw)['sha256'],'UTC':now,'actual_native_execution':False}))
