#!/usr/bin/env python3
"""Seal only this bounded priority family's public-safe records; no service/Git writes."""
from pathlib import Path
from datetime import datetime, timezone
from fractions import Fraction
import hashlib
import json

D = Path(__file__).resolve().parent
A = D.parent
UTC = datetime.now(timezone.utc).isoformat()

def pin(path, relative_to=D):
    p = Path(path)
    body = p.read_bytes()
    return {"path": str(p.relative_to(relative_to)), "bytes": len(body), "sha256": hashlib.sha256(body).hexdigest()}

def write(name, obj):
    (D / name).write_text(json.dumps(obj, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")

sources = [
    {"id": "zelik_author", "title": "A remark on a uniform Lyapunov dimension of cascade systems", "authors": ["Sergey Zelik"], "url": "https://sergey-zelik.co.uk/publications/dlyap.pdf", "body": "zelik2008_preprint.pdf", "expected_sha256": "0e7eaa6b186887bf138a8ce0fdd3cdbce0164c9956aaf308e14cd16782029141", "date": "Author body undated; associated publisher record 2008, not an authenticated identical version", "version": "author-hosted preprint, different title/numbering from publisher", "locations_read": ["Introduction pp1–3", "Section1 pp4–7", "Examples3.1–3.3 pp10–12"], "finding": "Classical decoupled products and quasiperiodic external torus framework; reviewer specialization recorded separately; no explicit Eden-refutation label authenticated", "access_gap": "Published PDF not retrieved; historical publisher PDF URL404; indexed Examples4.1–4.3 pp980–981 are lead only"},
    {"id": "turaev_zelik2002", "title": "Homoclinic bifurcations and dimension of attractors for damped nonlinear hyperbolic equations", "authors": ["Dmitry Turaev", "Sergey Zelik"], "url": "https://www.wias-berlin.de/preprint/777/wias_preprints_777.pdf", "body": "turaev_zelik2002.pdf", "expected_sha256": "91385e5ce52b84290729bde10543f28631be5af9f92c2a29a3ccd12d6d1d9c1b", "date": "2002, WIASpreprint777 printed title", "locations_read": ["Introduction pp1–4", "Theorem3.1 hypotheses and relevant conclusion", "Corollaries3.1–3.2 and Remark3.2 p27", "Theorem4.1 pp27–28", "Remark4.3 p34", "AppendixB pp38–40"], "finding": "Quasiperiodic minimal sets of dimension comparable in order to global Lyapunov dimension; not exact global maximum or strict comparison to every equilibrium and periodic orbit", "access_gap": "No gap for the listed primary preprint sections"},
    {"id": "bousch_mairesse2001", "title": "Asymptotic height optimization for topical IFS, Tetris heaps, and the finiteness conjecture", "authors": ["Thierry Bousch", "Jean Mairesse"], "url": "https://www.imo.universite-paris-saclay.fr/~thierry.bousch/preprints/artetris.pdf", "body": "bousch_mairesse2001_author.pdf", "expected_sha256": "ff30c207db3c1738282c79c08c7d0bfe577e6281d96ccdd5d891a1d17403e141", "date": "May2001 author preprint; journal JAMS15(2002)77–111", "doi": "10.1090/S0894-0347-01-00378-2", "locations_read": ["Title/abstract/introduction", "Section4.1–4.3 pp37–42, including Propositions4.1–4.2 and formulas4.9–4.12"], "finding": "Aperiodic irrational Sturmian matrix-cocycle maximizers; not an autonomous dissipative derivative/global-attractor Lyapunov-dimension example", "access_gap": "Only author version read; source notation/maximum-minimum typographic inconsistencies do not support new claims beyond explicit4.12"},
    {"id": "bochi2018v3", "title": "Ergodic optimization of Birkhoff averages and Lyapunov exponents", "authors": ["Jairo Bochi"], "url": "https://arxiv.org/pdf/1712.01612v3", "metadata_url": "https://arxiv.org/abs/1712.01612", "body": "bochi2018v3.pdf", "expected_sha256": "6c201a35d29da910a0a6b6eb9a34905fffd175c808a8be05894595e5397a9eee", "date": "arXiv v3 23April2018; body header February2,2017; arXiv history confirmed", "locations_read": ["Introduction", "Section1 periodic/generic discussion pp2–4", "Section3 pp8–10", "Selected Sturmian passages/references"], "finding": "Genericity/base regularity restrictions and known aperiodic cocycle maximizers; no automatic translation to the PR target", "access_gap": "Not read cover-to-cover; conclusions restricted to actual relevant sections"},
    {"id": "anikushin2025v10", "title": "Variational description of uniform Lyapunov exponents via adapted metrics on exterior products", "authors": ["Mikhail Anikushin"], "url": "https://arxiv.org/pdf/2304.05713v10", "metadata_url": "https://arxiv.org/abs/2304.05713v10", "body": "anikushin2025v10.pdf", "expected_sha256": "d02748f7fb50bfcf12f99b9e483b927c856c62a70953d491678575679894c01a", "date": "arXivv10 14October2025; first submission12April2023; journalNoDEA33,26(2026)", "doi": "10.1007/s00030-025-01163-2", "locations_read": ["Relevant Section3 definitions, propositions, Example3.1 and Remarks3.7–3.9 pp14–21", "AppendixA pp50–55 complete relevant variational principle and dimension conclusion", "Relevant references"], "finding": "Maximizing ergodic measure exists; generic periodic optimization distinct from universal assertion; no exact product-torus full prior counterexample found in sections read", "access_gap": "Not read all delay-equation applications; no absence claim about unread sections"},
    {"id": "anikushin2023v2", "title": "Variational description of uniform Lyapunov exponents via adapted metrics on exterior products", "authors": ["Mikhail Anikushin"], "url": "https://arxiv.org/pdf/2304.05713v2", "body": "anikushin2023v2.pdf", "expected_sha256": "32929dcf5a505e6e83d550d962a775da4a9343fabfdeafe65bd50e500e60277d", "date": "arXivv2 9June2023", "locations_read": ["Lead/keyword scan only, superseded by actual v10 relevant-section review"], "finding": "Superseded search lead; no theorem-content conclusion based on this version", "access_gap": "Not full reviewed"},
    {"id": "gelfert2003", "title": "Maximum local Lyapunov dimension bounds the box dimension. Direct proof for invariant sets on Riemannian manifolds", "authors": ["Katrin Gelfert"], "url": "https://ems.press/content/serial-article-files/35401", "body": "gelfert2003.pdf", "expected_sha256": "97f26985b8adfb1aa0e039b6701c45ae4b340934379b3a75dbc924f41bfea836", "date": "2003 ZAA22(3)553–568 printed journal header", "locations_read": ["Introduction/manifold local-dimension definition/Theorems1–2 pp553–555", "Remark5 p565", "Lorenz example pp565–567"], "finding": "Intrinsic Riemannian manifold definition is classical; dimension bounds/local-uniform distinction do not force equilibrium/periodic maximum", "access_gap": "Unneeded covering proof not fully audited; no prior negative resolution claim from it"},
]
for s in sources:
    p = D / "private_primary_sources" / s.pop("body")
    s["private_body_pin"] = pin(p)
    if s["private_body_pin"]["sha256"] != s.pop("expected_sha256"):
        raise RuntimeError("Body hash mismatch: " + s["id"])
    s["retrieved_date_UTC"] = "2026-10-06"
    s["redistributed"] = False

pg = A / "primary_source_scope_adversary_20261006/private_primary_sources/parker_goluskin_v2.pdf"
pg_pin = pin(pg, A)
if pg_pin["sha256"] != "c8e53fbd26bd51b270deb81cf318161cb14f260ab827a0996d401fee899c6e7c":
    raise RuntimeError("PG body mismatch")
sources.append({"id": "parker_goluskin_v2", "title": "Parker–Goluskin exact modern source-scope baseline", "url": "https://arxiv.org/pdf/2510.14870v2", "date": "v2 21January2026", "locations_read": ["p2 explicitly allows lower-dimensional manifold embedded in Rn", "pp5–7 full ambient tangent convention and Definition2.3"], "private_body_pin_relative_to_A111": pg_pin, "finding": "Embedded manifold allowed; ambient normal exponents must not be silently replaced by intrinsic tangent exponents", "redistributed": False})
sources.append({"id": "hunt1996_lead", "url": "https://terpconnect.umd.edu/~bhunt/papers/boxdim.html", "private_body_pin": pin(D / "private_primary_sources/hunt1996.html"), "locations_read": ["Author abstract only"], "finding": "Lead only; no full-text exclusion or theorem-content priority conclusion", "redistributed": False})
write("SOURCE_TABLE.json", {"UTC": UTC, "sources": sources, "private_storage_policy": "Copyright bodies/text/renderings are ignored and excluded from the public manifest; only metadata, URLs, locations, body hashes and original review analysis are portable.", "additional_access_gaps": ["Zelik publisher PDF historical URL returned404; author version undated and numbering differs", "Eden original thesis not read by this family", "Kaplan–Mallet-Paret–Yorke1984 torus primary lead received after independence from historical family; not read or used for a conclusion", "Hunt1996 full text not retrieved"]})

queries = [
'"Eden\'s conjecture" quasiperiodic counterexample', '"Lyapunov dimension" "torus" "Eden"', '"Lyapunov dimension" "counterexample" "periodic"', '"Lyapunov dimension" "quasiperiodic"', '"Eden conjecture" "counterexample"', '"Variational description of uniform Lyapunov exponents"', '"On the Lyapunov dimension of cascade systems" Zelik pdf', '"Eden" "hypothesis" "torus"', '"Eden" "conjecture" "aperiodic"', '"Lyapunov dimension" "saddle torus"', '"Eden\'s conjecture" "false"', '"Lyapunov dimension" "product" "periodic orbit"', '"local Lyapunov dimension" "irrational"', '"local Lyapunov dimension" "counterexamples"', '"Eden conjecture" counterexample torus product', '"On the Lyapunov dimension of cascade systems" filetype:pdf', '"Lyapunov dimension" "Eden" "generic"', '"Lyapunov dimension" "maximum" "quasi-periodic"', '"Eden" "counterexample" "Lyapunov" -growth -Dhar -Staudacher', '"maximum local Lyapunov dimension" "torus"', '"Lyapunov dimension" "saddle" "quasiperiodic"', '"Ergodic optimization of Birkhoff averages and Lyapunov exponents" Bochi pdf', '"Lyapunov dimension" "product flow"', '"Eden conjecture" "quasiperiodic" -Dhar', '"Lyapunov dimension" "irrational rotation"', '"Maximum local Lyapunov dimension" Hunt 1996 pdf', '"Eden conjecture" -growth -Dhar -Staudacher -Galileo -newconjecture -Garden -EIKASMO', '"Lyapunov dimension" "unstable torus"', '"Lyapunov dimension" "normally hyperbolic"', '"Eden" "Lyapunov" "torus" -growth -Dhar -stochastic -spectral -Staudacher', '"Eden conjecture" "suspension"', '"Lyapunov dimension" "quasiperiodic external forces"', '"global attractor" "irrational" "Lyapunov dimension"', '"counterexample" "Eden hypothesis"', '"hypothèse" "Eden" "dimension" "contre"', '"гипотеза Эдена" "контрпример"', '"Эдена" "квазипериод"', '"Eden conjecture" "counterexample" "attractor"', '"Eden hypothesis" Lyapunov counterexample', '"Lyapunov dimension" "radial"', '"Lyapunov dimension" "Hopf" "product"', '"maximal" "Lyapunov dimension" "non-periodic"', '"Eden" "Lyapunov" "counterexample" "quasi"', '"Asymptotic height optimization" "Bousch" pdf', '"Eden conjecture" "negative"', '"Lyapunov dimension" "periodic" "not attained"', '"Lyapunov dimension" "counterexample" "torus"', '"10.3934/cpaa.2008.7.971" "pdf"', '"On the Lyapunov dimension of cascade systems" "Example 4.2"', '"On the Lyapunov dimension of cascade systems" "Example 4.1"'
]
write("SEARCH_LOG.json", {"UTC": UTC, "search_session_date_UTC": "2026-10-06", "timing_precision": "Query-level timestamps were not captured. The logged actual checkpoint times bound the session; no fabricated precise per-query times are asserted.", "query_count": len(queries), "queries": queries, "method": "Phrase and mechanism search, primary author/institution/publisher/arXiv bodies read at relevant sections; search indexes and secondary bibliographies lead to originals but do not support conclusions.", "excluded_noise": "Unrelated Murray Eden first-passage/growth, Eden-Dhar-Staudacher and Garden-of-Eden material", "absence_claim_limit": "No exhaustive nonexistence of prior art is asserted.", "observed_access_failure": {"url": "https://data.aimsciences.org/aimsmath-upload/cpaa/2008/4/PDF/1534-0392_2008_4_971.pdf", "result": "404", "fallback": "Author dlyap.pdf read with differing title/numbering; no silent publisher-page authentication"}, "coordination_after_independence": ["Root identified same independently retrieved Zelik lead and requested exact specialization", "Root requested independent Turaev–Zelik implication check after own primary-source read", "Historical family independently confirmed manifold/ambient distinction", "Historical KMY1984 lead not adjudicated in this family"]})

diagnostic = pin(A / "repaired_diagnostics_v2/COUNTEREXAMPLE.md", A)
if diagnostic["sha256"] != "0e2e4e1484193c304cb2394142e24460c89a50f6ab3bb58ad838624cabb9035f":
    raise RuntimeError("Verified v2 diagnostic changed")
inputs = [diagnostic, pin(A / "ROOT_MATHEMATICAL_GATE_20261006.json", A), pin(A / "original_head_authentication_20261006/SOURCE_STATEMENT.json", A), pin(A / "original_head_authentication_20261006/PRIOR_REPORT.md", A)]

def ky(spectrum):
    spec = list(map(Fraction, spectrum))
    j = 0
    partial = Fraction(0)
    for i, v in enumerate(spec, 1):
        partial += v
        if partial >= 0:
            j = i
        else:
            break
    if j == len(spec):
        return j, Fraction(j)
    return j, Fraction(j) + sum(spec[:j]) / (-spec[j])

intrinsic = ky([0,0,-1])
ambient = ky([0,0,0,0,-1])
if intrinsic != (2, Fraction(2)) or ambient != (4, Fraction(4)):
    raise RuntimeError("Elementary zero-exponent convention control failed")
write("RESULT.json", {"UTC": UTC, "PR": 111, "original_head": "8a7270989d7064a4b97badecaa4b311db5e6d49f", "source_id": "4900006", "family": "quasiperiodic/product/radial-Hopf/saddle-torus prior art", "completion_percent": 100, "status": "COMPLETE_BOUNDED_PRIORITY_FRAMING_FINDING", "root_mathematical_gate_inherited": "PASS", "input_pins_relative_to_A111": inputs, "judgments": {"unrestricted_smooth_manifold_question": "Routine classical negative product specialization; first decisive novel resolution not cleared", "explicit_previously_published_Eden_labeled_specialization_authenticated": False, "exact_prior_matching_entire_R5_nonvacuous_theorem_located": False, "entire_R5_added_content_checkable": True, "substantial_independently_original_discovery_established_by_this_family": False, "novel_historical_Eden_resolution_cleared": False, "exhaustive_priority_complete": False, "Turaev_Zelik_theorems_logically_imply_full_strict_global_comparison": False, "Bousch_Mairesse_cocycle_automatically_realizes_target_flow": False}, "exact_specialization": {"phase": "R×(R²/Z²)", "field": "x′=−x, θ′=(1,√2)", "attractor": "{0}×T², compact minimal global for entire chosen manifold phase", "equilibria": 0, "periodic_orbits": 0, "intrinsic_spectrum": ["0","0","−1"], "intrinsic_KY_j": intrinsic[0], "intrinsic_KY_dimension": str(intrinsic[1]), "ambient_extension": "F=(-x,2πiz1,2π√2iz2) on R×C×C with phase B=R×S¹×S¹", "ambient_spectrum": ["0","0","0","0","−1"], "ambient_fixed_global_j": ambient[0], "ambient_dimension": str(ambient[1]), "extension_has_compact_global_attractor_on_all_R5": False, "deduction_status": "reviewer specialization of classical source framework, not previously published exact Eden counterexample authenticated"}, "recommendation": "Retain verified theorem/certificate; reject first-disproof framing of broad imported sentence; root to adjudicate value of modest explicit entire-R5 construction against user process.", "mutations": {"Git": False, "PR": False, "external_service": False, "publication": False}, "external_human_contact": False, "subdelegation": False, "copyright_bodies_in_manifest": False})

log = D / "RESEARCH_LOG.md"
with log.open("a", encoding="utf-8") as f:
    f.write("\n2026-10-06T18:03:30Z — Source-adjudication checkpoint: confirmed publisher2008 metadata while retaining author-version title/numbering and unavailable publisher-body gap. Verified explicit smooth-manifold product and its embedded ambient extension; fullR5 compact-attractor failure prevents identifying it with PR111. Turaev–Zelik order bounds and instability indices do not imply all-equilibrium/periodic strict local-dimension comparison. Priority family90% complete; publication novelty clearance remains withheld.\n")
    f.write("\n" + UTC + " — Completed bounded independent priority family, exact reviewer specialization, detailed report, machine source/search/result records, and public-safe manifest. All actual body hashes and pinned v2 diagnostic verified. Elementary exact KY controls distinguish intrinsic2 from ambient4. Best guess100% of this family assignment complete, not100% of exhaustive priority or the publication program. No exact prior full entire-R5 construction found; literal manifold assertion has a routine classical negative specialization; novelty as a new open-problem resolution is not cleared. No Git/PR/service/publication mutation, external outreach, or subdelegation.\n")

public = [".gitignore", "RESEARCH_LOG.md", "ZELIK_PRODUCT_SPECIALIZATION.md", "REPORT.md", "SOURCE_TABLE.json", "SEARCH_LOG.json", "RESULT.json", "finalize_audit.py"]
manifest = {"UTC": UTC, "scope": "Only original review analysis, metadata, hashes and sealing script. Copyright primary bodies/extracted text remain private and ignored.", "inputs_relative_to_A111": inputs, "members": [pin(D / p) for p in public], "excluded": ["private_primary_sources/", "tmp/"], "self_hash_policy": "Manifest excluded from own member list; authenticate this manifest externally."}
write("OUTPUT_MANIFEST.json", manifest)
for m in manifest["members"]:
    if m != pin(D / m["path"]):
        raise RuntimeError("Public manifest mismatch")
print(json.dumps({"UTC": UTC, "manifest": pin(D / "OUTPUT_MANIFEST.json"), "members": manifest["members"], "private_pdf_count": len(list((D / "private_primary_sources").glob("*.pdf"))), "exact_specialization_controls": "PASS"}, indent=2))
