#!/usr/bin/env python3
"""Exact controls for the finite extension criterion and cover bookkeeping."""
from math import gcd,lcm
from collections import Counter
from functools import lru_cache
from fractions import Fraction
import json
C=Counter()
def ck(x,k):
 assert x,k
 C[k]+=1
def supported(q,d):
 r=1
 while (g:=gcd(q,d))>1:r*=g;q//=g
 return r
for q in range(1,101):
 for d in range(1,101):
  sizes=[s for s in range(1,q+1) if q%s==0 and gcd(d*s,q)==s]
  t=supported(q,d)
  ck(t in sizes,'minimal_positive_batch_is_allowed')
  ck(all(s%t==0 for s in sizes),'all_positive_batches_divisible_by_supported_part')
  ck(all(gcd(d,q//s)==1 for s in sizes),'equivalent_batch_gcd_condition')
@lru_cache(None)
def positive_types(n,m,minimum=1):
 if n==0:return ((),)
 return tuple((d,)+p for d in range(minimum,n+1) if m%d==0 for p in positive_types(n-d,m,d))
def types(n,m):
 if m%2:return ()
 d=m//2
 return tuple(tuple(sorted([(d,-1)]*k+[(a,1) for a in p])) for k in range(1,n//d+1) for p in positive_types(n-k*d,m))
def actual_power(blocks,q):
 f=[]
 for d,s in blocks:
  start=len(f)
  f.extend((start+i+1,1) for i in range(d-1));f.append((start,s))
 fq=[]
 for i in range(len(f)):
  j=i;sign=1
  for _ in range(q):j,s=f[j];sign*=s
  fq.append((j,sign))
 seen=set();out=[]
 for i in range(len(f)):
  if i in seen:continue
  j=i;sign=1;d=0
  while j not in seen:seen.add(j);d+=1;j,s=fq[j];sign*=s
  out.append((d,sign))
 return tuple(sorted(out))
@lru_cache(None)
def possible_restrictions(n,m,q):
 return {actual_power(t,q) for t in types(n,m*q)}
for m in range(2,13,2):
 for n in range(1,11):
  for t in types(n,m):
   k=sum(s<0 for d,s in t);pos=Counter(d for d,s in t if s>0)
   for q in range(1,k+2):
    expected=k%q==0 and all(c%supported(q,d)==0 for d,c in pos.items())
    ck((t in possible_restrictions(n,m,q))==expected,'full_abstract_extension_criterion_vs_explicit_signed_powers')
    if expected:
     root=[(m*q//2,-1)]*(k//q)
     for d,c in pos.items():root.extend([(d*supported(q,d),1)]*(c//supported(q,d)))
     ck(actual_power(root,q)==t,'explicit_root_construction')
     ck(lcm(*(d*(2 if s<0 else 1) for d,s in root))==m*q,'constructed_root_exact_domain_order')
   if k==1:ck(t not in possible_restrictions(n,m,2),'one_negative_cycle_no_proper_extension')
# A connected lift is an orbit of the subgroup generated by loop monodromy.
for m in range(1,51):
 for a in range(m):
  seen=set();orbits=[]
  for i in range(m):
   if i in seen:continue
   orbit=[];j=i
   while j not in seen:seen.add(j);orbit.append(j);j=(j+a)%m
   orbits.append(orbit)
  ck(len(orbits)==gcd(a,m),'monodromy_number_of_lift_components')
  ck((len(orbits)==1)==(gcd(a,m)==1),'generator_monodromy_connected_lift')
# Four simple branch points on the torus involution quotient.
chi_cover=0;branch=4;degree=2;chi_base=Fraction(chi_cover+branch,degree)
ck(chi_base==2,'strong_inversion_boundary_underlying_sphere')
ck(chi_base-4*(1-Fraction(1,2))==0,'pillow_boundary_orbifold_Euler_zero')
ck(not 0>=2,'closed_knot_fails_ordinary_sphere_boundary_hypothesis')
print(json.dumps({'status':'PASS','exact_assertions':sum(C.values()),'categories':dict(C),'scope':'Finite arithmetic and covering controls. Myers/Thurston hypotheses, exact source-group injection and the unproved signed completion gap are treated in TURN_4.md.'},indent=2))
