#!/usr/bin/env python3
"""Exact, bounded controls. No external packages or network. See PROOF.md."""
import argparse, functools, json, pathlib, math

# Normal form x^a y^b c^d in the free class-two group, c=[y,x].
WORDS = [ [('y',1),('x',1),('y',1),('x',1),('y',1),('x',1),('y',-3),('x',-3)],
 [('y',1),('x',-1),('y',-1),('x',-3),('y',2),('x',-1),('y',1),('x',1),('y',1)],
 [('y',3),('x',-1),('y',1),('x',1),('y',1),('x',2),('y',2),('x',1),('y',1),('x',1)] ]
def collect(w):
 a=b=c=0
 for g,n in w:
  if g=='x': a+=n; c+=b*n
  else: b+=n
 return (a,b,c)

def mm(A,B,n=9):
 out=[]
 for a in A:
  b=0
  for k in range(n):
   if a>>k&1: b^=B[k]
  out.append(b)
 return tuple(out)
def add(A,B): return tuple(a^b for a,b in zip(A,B))
def rows(s): return tuple(sum(int(v)<<j for j,v in enumerate(r)) for r in s.split())
I=tuple(1<<i for i in range(9)); Z=(0,)*9
A0=rows('100000000 010001010 001011001 000100000 000010001 000001011 000000100 000000010 000000001')
A1=rows('000000000 011001010 010011001 000000000 010011001 001010011 000000000 001010011 011001010')
B0=rows('100000000 010010111 001111011 000100011 000010100 000001000 000000100 000000010 000000001')
B1=rows('000000000 011010111 010111011 010111011 001101100 000000000 010111011 001101100 010111011')
def pmul(P,Q):
 out=[Z]*(len(P)+len(Q)-1)
 for i,a in enumerate(P):
  for j,b in enumerate(Q): out[i+j]=add(out[i+j],mm(a,b))
 while len(out)>1 and out[-1]==Z: out.pop()
 return tuple(out)
def inverse_constant(A):
 cur=I
 for k in range(1,33):
  cur=mm(cur,A)
  if cur==I:
   out=I
   for j in range(k-1): out=mm(out,A)
   return out
 raise AssertionError('constant inverse bound')
def pinv(P):
 C=inverse_constant(P[0]); N=mm(C,P[1]); assert mm(N,N)==Z
 out=(C,mm(N,C)); assert pmul(P,out)==(I,) and pmul(out,P)==(I,)
 return out
X=(A0,A1);Y=(B0,B1)
def evalword(w,gens,ident,mul,inv):
 z=ident
 for g,n in w:
  a=gens[g] if n>=0 else inv(gens[g])
  for _ in range(abs(n)): z=mul(z,a)
 return z
# Every diagonal contains three 3x3 matrices encoded row-major as 9 bits.
def diag(P,d):
 out=[]
 for r in range(3):
  q=(r+d)//3; c=(r+d)%3
  C=P[q] if q<len(P) else Z
  out.append(sum(((C[3*r+i]>>(3*c+j))&1)<<(3*i+j) for i in range(3) for j in range(3)))
 return tuple(out)
def smallmul(a,b):
 z=0
 for i in range(3):
  for k in range(3):
   if a>>(3*i+k)&1: z^=((b>>(3*k))&7)<<(3*i)
 return z
# Tables for all 3x3 binary matrices: exact and constant bounded size.
MT=tuple(tuple(smallmul(a,b) for b in range(512)) for a in range(512))
def leading(a,b,d):
 return tuple(MT[a[r]][b[(r+d)%3]] ^ MT[b[r]][a[(r+1)%3]] for r in range(3))
def pack(a): return sum(v<<(9*r) for r,v in enumerate(a))
def unpack(a): return tuple(a>>(9*r)&511 for r in range(3))
def basis(vs):
 piv={}
 for v in vs:
  while v:
   k=v.bit_length()-1
   if k in piv: v^=piv[k]
   else: piv[k]=v; break
 # Unique reduced binary row-space representation, greatest pivot first.
 for k in sorted(piv):
  for j in piv:
   if j>k and piv[j]>>k&1: piv[j]^=piv[k]
 return tuple(piv[k] for k in sorted(piv,reverse=True))
def leading_orbit():
 a,b=diag(X,1),diag(Y,1)
 c=leading(b,a,1)
 V=basis([pack(c)]); result=[]; seen={}
 for i in range(1,101):
  key=(i%3,V)
  if key in seen: return {'ranks':result,'cycle_start_gamma_index':seen[key],'cycle_repeat_gamma_index':i,'cycle_period':i-seen[key],'states':list(seen)}
  seen[key]=i; result.append({'gamma_index':i,'rank':len(V),'basis':V})
  V=basis(pack(leading(unpack(v),g,i+1)) for v in V for g in [a,b])
 raise AssertionError('orbit did not cycle')

def tmul(P,Q):
 m=len(P); out=[]
 for j in range(1,m+1):
  v=[P[j-1][r]^Q[j-1][r] for r in range(3)]
  for s in range(1,j):
   for r in range(3): v[r]^=MT[P[s-1][r]][Q[j-s-1][(r+s)%3]]
  out.append(tuple(v))
 return tuple(out)
def tinv(P):
 out=[]
 for j in range(1,len(P)+1):
  v=list(P[j-1])
  for s in range(1,j):
   for r in range(3): v[r]^=MT[P[s-1][r]][out[j-s-1][(r+s)%3]]
  out.append(tuple(v))
 return tuple(out)
def tcomm(a,b): return tmul(tmul(tmul(tinv(a),tinv(b)),a),b)
def subgroup(gs,e,cap):
 gs=tuple(set(gs)-{e}); have={e}; todo=[e]
 while todo:
  a=todo.pop()
  for g in gs:
   c=tmul(a,g)
   if c not in have:
    have.add(c); todo.append(c)
    assert len(have)<=cap,'enumeration cap exceeded'
 return have

def finite_control(m):
 e=((0,0,0),)*m; x=tuple(diag(X,d) for d in range(1,m+1)); y=tuple(diag(Y,d) for d in range(1,m+1))
 assert all(evalword(w,{'x':x,'y':y},e,tmul,tinv)==e for w in WORDS)
 cap=1<<16; G=subgroup([x,y],e,cap); current=G; orders=[len(G)]
 # [K,G] generated by [k,x],[k,y] for k in K: conjugates are again products of these.
 for i in range(m+1):
  gens={tcomm(k,g) for k in current for g in [x,y]}
  nxt=subgroup(gens,e,cap); assert nxt<=current
  orders.append(len(nxt))
  if len(nxt)==1: break
  assert len(nxt)<len(current)
  current=nxt
 assert orders[-1]==1
 return {'diagonal_cutoff':m,'order':len(G),'lower_central_orders':orders,'lower_central_indices':[a//b for a,b in zip(orders,orders[1:])], 'limits':{'element_cap':cap,'all_relators_verified':True,'full_abstract_quotient':False}}

def magnus(w,cutoff=8):
 def mul(a,b):
  z=set()
  for u in a:
   for v in b:
    if len(u)+len(v)<=cutoff:
     t=u+v
     if t in z:z.remove(t)
     else:z.add(t)
  return z
 z={''}
 for g,n in w:
  gen={'',g} if n>=0 else {g*k for k in range(cutoff+1)}
  for _ in range(abs(n)):z=mul(z,gen)
 z.remove(''); deg=min(map(len,z))
 return {'degree':deg,'initial_terms':sorted(t for t in z if len(t)==deg),'terms_through_degree_8':len(z)}

def main():
 parser=argparse.ArgumentParser(); parser.add_argument('--max-cutoff',type=int,default=4); args=parser.parse_args()
 assert 1<=args.max_cutoff<=5
 exact=[evalword(w,{'x':X,'y':Y},(I,),pmul,pinv)==(I,) for w in WORDS]; assert all(exact)
 collected=[collect(w) for w in WORDS]; assert collected==[(0,0,6),(-4,4,0),(4,8,26)],collected
 gcd_entries=math.gcd(*(v for a,b,c in collected for v in (a,b)))
 det=abs(collected[1][0]*collected[2][1]-collected[1][1]*collected[2][0])
 assert (gcd_entries,det)==(4,48)
 result={'class_two_relators':collected,'abelian_smith_diagonal':[gcd_entries,det//gcd_entries], 'polynomial_matrix_relators_identity':exact,'leading_orbit':leading_orbit(),'magnus':[magnus(w) for w in WORDS], 'finite_images':[]}
 for m in range(1,args.max_cutoff+1): result['finite_images'].append(finite_control(m))
 print(json.dumps(result,indent=2))
if __name__=='__main__':main()
