"""Rebuild the bounded audit's human and machine-readable records."""
from pathlib import Path
import hashlib
import json

ROOT = Path(__file__).resolve().parent
AUDIT_DATE = "2026-10-01"
CANDIDATE = {"head": "3aa15b4ab70ddddf556c84cbba7d6528910dfceb", "sha256": "23705f2868d66526eeded2cf644d36138acd8223af13d5202ee22da415753502"}

# Payload retrieval metadata and SHA-256s are produced by fetch_sources.py.
# These annotations distinguish theorem dates from retrieval/HTTP dates.
ANNOTATIONS = {
 "owr_2006": ("Brehm, Linear Versus Piecewise Linear Embeddability of Simplicial Complexes", "OWR 12/2006; contribution pp.701–702; DOI 10.4171/owr/2006/12", "2006", "Entire contribution; exact problem, definitions, all three theorem statements and proof outline"),
 "brehm_sarkaria_1992": ("Brehm–Sarkaria, Linear vs. Piecewise-Linear Embeddability of Simplicial Complexes", "MPI/92-52 (1992); archive deposit/HTTP dates are later", "1992", "Entire 12 printed pages, including Theorems A/B, definitions, linking proofs, and all §3.2 variants"),
 "brehm_mobius_1983": ("Brehm, A nonpolyhedral triangulated Möbius strip", "Proc. AMS 89(3), November 1983, 519–522; received 1982-11-17/revised 1983-05-03", "1983-11", "Entire four-page primary proof and construction"),
 "brehm_schild_1995": ("Brehm–Schild, Realizability of the torus and the projective plane in R4", "Israel J. Math. 91 (1995) 249–251; received 1994-01-17; DOI 10.1007/BF02761649", "1995", "Entire three-page scanned statement/proof/remarks, inspected as PNG pages in tmp/brehm_schild_page-*"),
 "few_vertices": ("Frick–Hu–Scheel–Simon, Embedding dimensions of simplicial complexes on few vertices", "arXiv:2109.04855v2 2023-03-14, internal PDF date March 15; v1 2021-09-10; Ann. Comb. 27 (2023), 993–1003", "2021-09-10", "Theorems 1/4, relevant Lemmas 5/8 and proofs, introduction, small-vertex questions/remarks"),
 "newman_current": ("Newman, Linear embeddings of random complexes", "arXiv:2212.09576v3 2023-10-03, internal PDF October 4; v1 2022-12-19; v2 2023-06-27", "2022-12-19", "Relevant threshold/Janson/order-type proof, Theorem 16 and PL comparison, entire concluding discussion/retraction"),
 "newman_v1": ("Newman, Linear embeddings of random complexes (initial version)", "arXiv:2212.09576v1 2022-12-19", "2022-12-19", "Introduction, main statements, concluding PL comparison and relevant probabilistic proof; not relied on for withdrawn odd-dimensional claim"),
 "lee_nevo_v1": ("Lee–Nevo, On colorings of hypergraphs embeddable in R^d (initial version)", "arXiv:2307.14195v1 2023-07-26", "2023-07-26", "Complete Lemma 3.1 and proof; introduction, Main Theorem, chromatic construction context"),
 "lee_nevo_v3": ("Lee–Nevo, On colorings of hypergraphs embeddable in R^d", "arXiv:2307.14195v3 2026-03-09; journal online publication 2026-07-03, DOI 10.1007/s00454-026-00856-4", "2023-07-26", "Complete Lemma 3.1 proof, main/chromatic/ambient-triangulation statements and relevant constructions"),
 "heise_et_al_2014": ("Heise–Panagiotou–Pikhurko–Taraz, Coloring d-embeddable k-uniform hypergraphs", "DCG 52 (2014) 663–679; online 2014-10-17; DOI 10.1007/s00454-014-9641-2", "2014", "Definitions, link lemma, chromatic constructions Theorem 21 and monotonicity to chi(3,4), concluding questions"),
 "novik_2000": ("Novik, A Note on Geometric Embeddings of Simplicial Complexes in a Euclidean Space", "DCG 23 (2000) 293–302; DOI 10.1007/s004549910019", "2000", "Introduction/definitions, obstruction background, Theorem 3.1 and relevant bounded-cochain proof; no supplied application"),
 "surface_realization_2010": ("Hougardy–Lutz–Zelke, Surface realization by intersection functional", "Experimental Mathematics 19(1) (2010) 79–92; cached author PDF title uses Edge, journal uses Segment", "2010", "Section 2 surface realization survey, simplicial/polygonal distinctions, R3/R4/R5 status and references"),
 "matousek_book": ("Matoušek, Using the Borsuk–Ulam Theorem", "2003 original; inspected corrected second printing 2008", "2003", "Notes to §5.1, printed pp.91–92; relevant embedding recap/citations"),
 "winter_2_complexes_2024": ("Georgakopoulos–Winter, On 2-complexes embeddable in 4-space, and the excluded minors of their underlying graphs", "Undated current author PDF; first posting date not established; HTTP Last-Modified 2026-09-21 is not publication date; legacy cache key is not a date claim", None, "Introduction/main theorems, definitions §2.1 and PL convention, 4-flat/CW scope"),
 "skopenkov_hypergraph_survey": ("Skopenkov, Realizability of hypergraphs and intrinsic linking theory", "arXiv:1402.0658v7 2026-08-12; initial paper 2014-02-04; earlier title/author presentation differs", "2014-02-04", "Intrinsic linking/intersection theorem statements, PL strengthening, realization definitions, product statements"),
 "abrahamsen_kleist_miltzow_2023": ("Abrahamsen–Kleist–Miltzow, Geometric Embeddability of Complexes is ∃R-complete", "SoCG 2023 LIPIcs 258 article 1; DOI 10.4230/LIPIcs.SoCG.2023.1; arXiv:2108.02585 initial 2021", "2021", "Introduction, Theorem 1 and PL-promise formulation, technique overview; complete dimension reduction/suspension Claim 11 proof"),
 "adiprasito_benedetti_current": ("Adiprasito–Benedetti, Linear embeddings of contractible and collapsible complexes", "arXiv:1403.5217v6 2020-08-05; internal PDF August 4; initial 2014-03-20", "2014-03-20", "Introduction, Main Theorems A/B, relevant definitions and subdivision proof context; compared against v1"),
 "adiprasito_benedetti_v1": ("Adiprasito–Benedetti, On the embeddability of contractible complexes (initial version)", "arXiv:1403.5217v1 2014-03-20", "2014-03-20", "Full main statements/introduction, examples and original-linear proof; old upper-bound assertion replaced in current v6"),
 "adiprasito_patakova_current": ("Adiprasito–Patáková, A higher-dimensional version of Fáry's theorem", "arXiv:2404.12265v3 2025-03-11, internal March 13; v1 2024-04-18; BLMS first published 2025-02-27, DOI 10.1112/blms.70036", "2024-04-18", "Entire five-page current proof and definitions: Theorem 2, Lemmata 4–8, edge contractions, abstract ambient triangulation"),
 "parsa_skopenkov_joins": ("Parsa–Skopenkov, On embeddability of joins and their factors", "arXiv:2003.12285v3 2023-02-06; v1 2020-03-27; Topol. Appl. 326 (2023) 108409", "2020-03-27", "Entire four-page paper including proofs, hypotheses, and original 2006-source provenance"),
 "parsa_smith_joins": ("Parsa, Instability of the Smith index under joins and applications to embeddability", "arXiv:2103.02563v4 2022-03-16; v1 2021-03-03; Trans. AMS 375 (2022) 7149–7185", "2021-03-03", "Definitions/introduction, Theorems 1/2/7 and relevant proof context; not every Smith-class computation rederived"),
 "melikhov_joins_products": ("Melikhov, Embeddability of joins and products of polyhedra", "arXiv:2210.04015v1 2022-10-08; TMNA 60(1) (2022) 185–201; DOI 10.12775/TMNA.2022.004; some statements attributed to 2006 preprint", "2022; underlying statements 2006 where explicitly attributed", "Introduction/Theorems A–D, §§2 equivalences/proofs and PL/topological criterion; affine realization not a conclusion"),
 "newman_metadata": ("Newman arXiv version metadata", "HTML confirms initial/revised dates", "2022-12-19", "Submission history and version/DOI metadata"),
 "lee_nevo_metadata": ("Lee–Nevo arXiv version metadata", "HTML confirms v1 2023-07-26, v3 2026-03-09", "2023-07-26", "Submission history"),
 "few_vertices_metadata": ("Few-vertices arXiv metadata", "HTML initial/revised dates and journal details", "2021-09-10", "Submission history and journal metadata"),
 "lee_nevo_published": ("Lee–Nevo journal metadata", "Publisher first-publication metadata 2026-07-03", "2026-07-03", "Publication metadata; mathematical mechanism checked in both arXiv versions"),
 "newman_journal_record": ("Newman journal record", "Discrete Mathematics 349(12), December 2026, article 115331; DOI 10.1016/j.disc.2026.115331; accessible in web search before issue date", None, "Web search returned publisher abstract/introduction; direct payload fetch 403; first-online date not independently fixed"),
 "adiprasito_patakova_metadata": ("Adiprasito–Patáková arXiv metadata", "Web reader confirms v1 2024-04-18, v3 2025-03-11; raw payload 406", "2024-04-18", "Submission history read via web reader; downloaded PDF version header also verified"),
}

QUERIES = [
 ['Brehm "two minimum dimensions" embedding', 'Brehm Sarkaria "linear" "piecewise" embeddings dimension 4 1992', '"simplicial complex" "PL" "linear embedding dimension"'],
 ['"Brehm" "Sarkaria" "dimensions" embeddings gap', '"PL" "linear" "embeddings" "R4" simplicial Brehm', '"Möbius strip" "linear" "R4" Brehm', '"linear" "triangulated surfaces" "four" embedding'],
 ['"A nonpolyhedral triangulated Möbius strip" pdf', '"Can the minimal dimensions" "embeddability"', '"Linear vs. piecewise-linear embeddability" Brehm citations', '"triangulated" "surfaces" "R4" "polyhedral"'],
 ['"piecewise" "linear" "embedding dimensions" "gap"', '"simplicial" "linear" "R^4" "R^3" Brehm', '"linear hypergraphs" "embeddable" dimension', '"simplicial" "embedding dimension" "Sarkaria"'],
 ['"simplicial" "PL" "linear" "differ by"', '"Brehm" "embedding" "gap" minimum', '"simplicial" "PL embedding" "linear embedding" "5"', '"ball" "linear embedding" "R4" simplicial'],
 ['"Brehm" "Schild" "Realizability" triangulations torus projective plane', '"PL" "linear" "embeddability" "more than one"', '"triangulated surfaces" "linearly" "R4" Brehm Schild', '"simplicial complexes" "piecewise" "minimal dimensions"'],
 ['"Brehm" "Sarkaria" "linear" -"polytope" after:2006', '"simplicial" "PL" "embedding dimension" gap 2', '"Embedding dimensions of simplicial complexes" citations', '"nonrealizable" "surfaces" "R^4"'],
 ['"Some short proofs of the nonrealizability of hypergraphs"', '"nonrealizable" hypergraphs "R4"', '"simplicial" "R^4" "not" "linear" "embeddable"'],
 ['"linear embedding" "Novik" 2000', '"geometric embeddability of complexes" "complete" arxiv', '"simplicial complexes" "non-linear" "R4"'],
 ['"Brehm" "Sarkaria" "gap" embeddings', '"piecewise-linear" "linear" "embedding dimensions" gap -codes', '"linear embeddability" "dimension" "difference"', '"linear" "PL" "embeddability" "2026"'],
 ['"collapsible complexes" "linearly" "embeddings"', '"contractible" "linearly" "Grünbaum" embeddings', '"linear" "collapsible" "Brehm" complex', '"Novik" "Geometric Embeddings" pdf'],
 ['"Linear embeddings of contractible and collapsible complexes" "Theorem" "subdivision"', '"Brehm" "Sarkaria" "Adiprasito" dimensions', '"complexes" "linear" "PL" "gap of" dimension'],
 ['"A higher dimensional version of Fáry" arxiv', '"not linearly" "R4" "collapsible"', '"not linearly" "R^4" "collapsible"'],
 ['"A higher-dimensional version of Fáry" arxiv', '"Brehm" "Sarkaria" "join" embeddings', '"linear embedding dimension" "join"', '"piecewise-linear" "linear" embedding "gap" suspension'],
 ['"Brehm" "Sarkaria" joins', '"simplicial complexes" "linear" "embeddability" "suspension"', '"simplicial" "embedding dimension" "join" linear', '"A higher-dimensional version of Fáry" "arxiv.org"'],
 ['"On embeddability of joins and their" factors arxiv', '"A higher-dimensional version" "Fáry" "230"', '"Instability of the Smith index under joins" arxiv', '"PL" "linear" "Brehm" "minimum" dimension'],
 ['"A higher-dimensional version of Fáry" "240" arxiv', '"Embeddability of joins and products of polyhedra" arxiv', '"Möbius" "join" "linear" embedding', '"embedding dimension" "linear" "additivity" simplicial'],
 ['Adiprasito Patakova triangulations 2024 Fary arxiv', '"Möbius strip" "embedding dimension" join', '"piecewise-linear embeddings" "minimum" "Brehm"'],
]

ROUTES = [
 ("brehm_1983_mobius", ["brehm_mobius_1983", "brehm_schild_1995"], "Original finite 2D Möbius triangulation", "e_PL=3", "e_lin=4, proved by non-linear R3 plus cap/projective-plane R4 theorem", "No: exact one-dimension gap", "excluded_by_independent_upper_bound"),
 ("brehm_sarkaria_main_A", ["brehm_sarkaria_1992", "few_vertices"], "Finite n≥2 linking family, r=0", "e_PL=2n, from surviving few-vertex skeleton and PL upper bound", "e_lin=2n+1", "No: for n=2 the minima are 4/5", "excluded_by_independent_PL_lower_bound"),
 ("brehm_sarkaria_m3_variants", ["brehm_sarkaria_1992", "owr_2006"], "n=2, ambient m=3; arbitrary prescribed r", "e_PL≤3", "Original-linear R3 forbidden; e_lin≥4", "Original-linear R4 obstruction missing", "not_subsuming"),
 ("brehm_sarkaria_punctured_projective", ["brehm_sarkaria_1992", "owr_2006"], "n=2^k punctured projective n-manifold", "PL R^(2n−1)", "No linear R^(2n−1)", "One extra lower bound needed; n=2 has upper4", "not_subsuming"),
 ("newman_random", ["newman_current", "newman_v1"], "Random Y_d(n,n^-alpha), 1<alpha<d", "PL R^(2d)", "No original-linear R^(2d), with high probability", "d=2 gives PL≤4, not ≤3; adaptive deletion resilience not stated", "not_subsuming"),
 ("lee_nevo_linear_hypergraph", ["lee_nevo_v1", "lee_nevo_v3"], "(d+1)-uniform hypergraphs with pairwise hyperedge intersection ≤1", "PL R^d, d≥3; private-apex inflation gives triangle PL R3", "No R4 nonembedding supplied for the triangle family", "Conjunction with an affine R4 obstruction missing", "prior_ingredient_only"),
 ("chromatic", ["heise_et_al_2014", "lee_nevo_v3"], "Uniform embedded hypergraphs", "Chromatic PL constructions", "chi_L(3,4)=infinity, already chi_L(3,3)=infinity", "High chromaticity is no R4 affine obstruction", "not_subsuming"),
 ("few_vertex", ["few_vertices"], "At most d+3 vertices in relevant equivalence", "Topological/PL embeddings criterion", "Original-linear R^d equivalence", "Different vertex/same-ambient question; no target example", "not_subsuming"),
 ("AKM_complexity", ["abrahamsen_kleist_miltzow_2023"], "d≥3, k in {d−1,d}; PL embedding promised", "PL R^d", "GEM k→d remains ∃R-complete", "k=2 d=3 doesn't obstruct linear4; d=4 has k≥3", "not_subsuming"),
 ("novik_bounded_cochain", ["novik_2000"], "Finite simplicial K geometrically embeddable in R^m", "Usual obstruction vanishing needed", "Bounded integral cochain necessary", "No PL-R3 example failing affine-R4 criterion instantiated", "criterion_not_witness"),
 ("collapsible_contractible", ["adiprasito_benedetti_current", "adiprasito_benedetti_v1"], "Collapsible d-complexes or hard contractible presentation complexes", "PL upperbounds after subdivisions; R3 existence not supplied for hard presentation route", "Current theorem embeds subdivided complexes in R^(2d); obstruction in R3 only", "No same original K with PL3 and affine≥5", "not_subsuming_version_caution"),
 ("abstract_ambient_triangulation", ["adiprasito_patakova_current"], "K PL embedded in abstract PL d-manifold", "Ambient triangulation contains original K", "No global Euclidean-affine conclusion", "Abstract PL homeomorphism may bend original simplices", "not_subsuming"),
 ("surfaces", ["surface_realization_2010", "brehm_schild_1995"], "Original triangulated surfaces; orientable or with boundary eligible for PL3", "PL3 for eligible surface types; closed nonorientables excluded", "No-linear-R3 examples; arbitrary upper5; torus/RP2 upper4", "For eligible type, a no-linear-R4 proof still needed", "not_subsuming_in_checked_chain"),
 ("4_flat_graphs", ["winter_2_complexes_2024"], "Regular 2D CW complexes on a graph; PL convention", "PL R4", "No original-simplex affine comparison", "Both PL3 and affine4 obstruction missing", "not_subsuming"),
 ("intrinsic_intersection_products", ["skopenkov_hypergraph_survey"], "Classical simplex/product constructions", "Topological R4 obstruction for relevant examples", "Affine obstruction follows weaker category", "Such examples cannot be PL3", "excluded_by_category"),
 ("suspension", ["abrahamsen_kleist_miltzow_2023"], "K*S0, iterated; known positive-codimension older witnesses", "PL minimum rises by1 for witnesses by apex link lowerbound", "Affine minimum rises by1, exact Claim11", "One-dimension gaps persist; 2D target also not preserved", "not_gap_amplifying_for_examined_examples"),
 ("joins_products", ["parsa_skopenkov_joins", "parsa_smith_joins", "melikhov_joins_products"], "Topological/polyhedral joins/products, metastable hypotheses where stated", "Topological/PL implications; may lose obstructions under joins", "No affine dimension additivity theorem", "Required independent affine lowerbounds absent; 2D/R3 outside 2d≥3k+3", "not_subsuming_in_checked_chain"),
]

def write_json(name, value):
    (ROOT / name).write_text(json.dumps(value, indent=2, ensure_ascii=False) + "\n")

def main():
    ledger = json.loads((ROOT / "source_hash_ledger.json").read_text())
    failures = []
    for key, value in ledger.items():
        if not value.get("sha256"):
            continue
        payload = ROOT / value["payload"]
        if hashlib.sha256(payload.read_bytes()).hexdigest() != value["sha256"]:
            failures.append(key)
    if failures:
        raise RuntimeError("Payload hash mismatch: " + ", ".join(failures))
    annotated = []
    rows = ["# Source, date, version, and reading ledger", "", "Audit access date: 2026-10-01 UTC. SHA-256 identifies exact downloaded bytes; all raw payloads are in ignored tmp/. Full retrieval timestamps, bytes, resolved URLs, and HTTP metadata are in source_hash_ledger.json. HTTP dates are not theorem priority dates. No source below positively subsumes the target.", ""]
    for key, (title, version, first_date, scope) in ANNOTATIONS.items():
        value = ledger[key]
        annotated.append({"id": key, "title": title, "version_and_dates": version, "first_availability_record": first_date, "read_scope": scope, "payload_record": value})
        rows += [f"## {key}", "", f"**{title}.** {version}.", "", f"Read: {scope}.", "", f"[Source]({value['url']}). Access: `{value['accessed_utc']}`."]
        rows += ([f"SHA-256: `{value['sha256']}`; payload `{value['payload']}` ({value['bytes']} bytes)."] if value.get("sha256") else [f"Raw retrieval limitation: {value.get('error')}. Mathematical PDF or web reading alternatives described above."])
        rows += [""]
    (ROOT / "SOURCE_LEDGER.md").write_text("\n".join(rows) + "\n")
    write_json("source_reading_ledger.json", annotated)
    write_json("subsumption_map.json", {"audit_date": AUDIT_DATE, "target": "Finite original simplicial 2-complex K, e_PL(K)=3, e_lin(K)=5", "positive_prior_subsumptions": [], "routes": [{"route": r[0], "source_ids": r[1], "hypotheses": r[2], "PL_conclusion": r[3], "original_linear_conclusion": r[4], "exact_gap_or_missing_implication": r[5], "status": r[6], "subsumes_target": False} for r in ROUTES]})
    write_json("BOUNDED_SEARCH_RECORD.json", {"date": AUDIT_DATE, "time_window_utc": {"start": "15:23:08", "last_web_metadata_verification": "15:55 approximately", "query_batch_times": "Individual batch timestamps not retained; exact payload retrieval timestamps are in source_hash_ledger.json"}, "search_method": "Public web search in query batches, followed by full primary PDFs and citation trails where a result could plausibly subsume target", "query_batches": [{"sequence": i+1, "queries": q, "positive_exact_subsumption": False} for i,q in enumerate(QUERIES)], "primary_paths": ["OWR2006 -> Brehm1983 / BrehmSarkaria1992 / Schild1993 (cited statement only; no independent full proof claimed)", "Brehm1983 -> BrehmSchild1995 -> HougardyLutzZelke2010", "Newman2022v1/2023v3 -> BrehmSarkaria / fewvertex criterion / PL threshold statement", "LeeNevo2023v1/2026v3 -> HPT2014 / abstract ambient triangulation2025", "Novik2000 -> geometric vs PL obstruction criteria", "AKM2023 -> BrehmSarkaria / Novik / suspension / ParsaSkopenkov", "AdiprasitoBenedetti2014v1 vs2020v6", "ParsaSkopenkov2023 -> Parsa2022 / Melikhov2022 / source-attributed2006 joins-products results", "Skopenkov2026v7 -> classical topological intrinsic intersection/product obstructions", "GeorgakopoulosWinter current author PDF -> PL 4-flat scope"], "excluded_false_positives": ["fixed-ambient separation is not an exact-minimum gap2", "small-vertex open question is not Brehm's minimum-dimension problem", "no subdivision bound does not yield high minimum", "closed nonorientable surfaces cannot PL R3", "polygonal/coplanarity maps differ from simplicial complexes", "nonpolytopal does not mean nonlinearly realizable", "abstract ambient triangulation does not give Euclidean original-affine coordinates", "topological R4 nonembedding excludes PL3", "unbounded chromatic number alone does not obstruct affine R4", "unproved affine additivity under joins", "withdrawn prior-version assertions not promoted"], "limitations": ["No exhaustive citation graph export", "No complete all-language/non-indexed proceedings/theses/unpublished search", "Some direct publisher/metadata fetches failed403/406; core mathematical PDFs were available", "Undated current GeorgakopoulosWinter PDF first availability not established", "Newman journal first-online date not fixed; accessible2026 record future December issue distinguished", "No global priority proof or universal current-open certificate", "No external people contacted"], "independence": {"sibling_priority_reports_read_before_verdict": False, "parent_positive_priority_claims_received": False, "additional_parent_route_request": "joins/suspensions/products; no positive result supplied"}})
    write_json("verdict.json", {"schema_version": 1, "audit_family": "priority_exact_family", "audit_date_utc": AUDIT_DATE, "candidate": CANDIDATE, "target": {"finite": True, "original_simplicial_dimension": 2, "PL_minimum": 3, "original_linear_minimum": 5, "manifold_required": False, "small_explicit_facet_list_required": False}, "classification": "bounded_clearance", "known_prior_subsumption": False, "positive_prior_subsumptions": [], "global_priority_proven": False, "current_open_status_certified": False, "strongest_verified_priority_finding": "No examined primary theorem supplies a finite original 2-complex PL in R3 and not affine in R4; main BrehmSarkaria family has exact4/5 and Möbius witness exact3/4", "version_cautions": ["Newman odd-dimension claim withdrawn in v3; even4 route remains", "LeeNevo Lemma3.1 existed in v1 2023-07-26", "AdiprasitoBenedetti original upperbounds changed to subdivision theorem in v6", "2026 Newman December journal issue differs from first prior preprint availability"], "publication_disposition": "No exact-priority blocker found by this family; await independent other-family audits and parent decision; avoid categorical first-ever assertion based solely on negative search", "remaining_gap": "Possibility of an unlocated prior direct example or equivalent theorem, including non-indexed literature, remains", "independence": "Fixed without reading sibling priority findings; no external people contacted", "completed_bounded_audit_percent": 100, "artifacts": ["INDEPENDENT_PRIORITY_REPORT.md", "SOURCE_LEDGER.md", "source_hash_ledger.json", "source_reading_ledger.json", "subsumption_map.json", "BOUNDED_SEARCH_RECORD.json", "RESEARCH_LOG.md"], "payload_hash_check": {"checked": sum(bool(v.get('sha256')) for v in ledger.values()), "mismatches": failures}})
    print("Records rebuilt; payload hashes checked:", sum(bool(v.get("sha256")) for v in ledger.values()))

if __name__ == "__main__":
    main()
