#!/usr/bin/env python3
"""Independent audit controls, Python 3 standard library only.

No author module is imported. Identities use exact integer interpolation grids
with separately stated coordinate-degree bounds. These are not general proof
search or certificates for geometry/topology. With --author-dir, additionally
check the frozen author hashes and replay its script in a child process.
"""
from fractions import Fraction
from itertools import product
from pathlib import Path
import argparse
import hashlib
import json
import subprocess
import sys

EXPECTED_MANIFEST = 'e468ff6825bd523f60483c9bb812a577a6724a03684b75205f70340e7ffc1c8f'


def rank(rows):
    a = [list(map(Fraction, row)) for row in rows]
    piv = 0
    for col in range(len(a[0]) if a else 0):
        selected = next((row for row in range(piv, len(a)) if a[row][col]), None)
        if selected is None:
            continue
        a[piv], a[selected] = a[selected], a[piv]
        scale = a[piv][col]
        a[piv] = [value / scale for value in a[piv]]
        for row in range(piv + 1, len(a)):
            scale = a[row][col]
            a[row] = [value - scale * other for value, other in zip(a[row], a[piv])]
        piv += 1
        if piv == len(a):
            break
    return piv


def freely_reduce(word):
    stack = []
    for letter in word:
        if stack and stack[-1] == -letter:
            stack.pop()
        else:
            stack.append(letter)
    return stack


def main(author_dir=None):
    checks = {}
    cases = {}
    def check(name, condition):
        if not condition:
            raise AssertionError(name)
        checks[name] = True
    def grid(name, residual, bounds):
        # Degree <= d in each coordinate: d+1 distinct values per coordinate
        # suffice by repeated univariate interpolation. Bounds are reviewed
        # mathematical inputs and recorded in the output, not inferred by code.
        points = list(product(*(range(-1, d) for d in bounds)))
        check(name, all(residual(*point) == 0 for point in points))
        cases[name] = {'coordinate_degree_bounds': list(bounds), 'exact_points': len(points)}

    f = lambda u, v, w: v*v - w*u*u
    grid('quotient_invariant_identity', lambda x,y,z: (z*(x-y))**2-z*z*(x+y)**2+4*z*z*x*y, (2,2,2))
    check('missing_factor_negative_witness', (0*(1-1))**2-0**2*(1+1)**2 != -4*1*1)

    # All three ambient point-blowup strict transforms, independently expanded.
    grid('point_blowup_u_chart', lambda u,b,c: f(u,u*b,u*c)-u*u*(b*b-u*c), (3,2,1))
    grid('point_blowup_v_chart', lambda v,a,c: f(v*a,v,v*c)-v*v*(1-v*c*a*a), (3,2,1))
    grid('point_blowup_w_chart', lambda w,a,b: f(w*a,w*b,w)-w*w*(b*b-w*a*a), (3,2,2))
    grid('double_line_u_chart', lambda u,t,w: f(u,u*t,w)-u*u*(t*t-w), (2,2,1))
    grid('double_line_v_chart', lambda v,r,w: f(v*r,v,w)-v*v*(1-w*r*r), (2,2,1))
    grid('normalization_map', lambda u,t: f(u,u*t,t*t), (2,2))
    grid('branched_base_change', lambda u,v,t: f(u,v,t*t)-(v-u*t)*(v+u*t), (2,2,2))
    grid('branch_minor_ut_zero', lambda u,t: (-t)*u-(-u)*t, (1,1))
    grid('branch_minor_uv', lambda u,t: (-t)*1-1*t+2*t, (0,1))
    grid('branch_minor_vt', lambda u,t: 1*u-(-u)*1-2*u, (1,0))
    check('branch_normals_origin_rank_one', rank([[0,1,0],[0,1,0]]) == 1)
    check('branch_normals_nonzero_u_rank_two', rank([[0,1,-1],[0,1,1]]) == 2)
    check('branch_normals_nonzero_t_rank_two', rank([[-1,1,0],[1,1,0]]) == 2)

    # Semigroup of exponents generated by u, ut, t^2, by BFS rather than a
    # built-in membership formula. The all-degree proof is in AUDIT.md.
    bound = 16
    semigroup = {(0,0)}
    frontier = [(0,0)]
    while frontier:
        i,j = frontier.pop()
        for di,dj in ((1,0),(1,1),(0,2)):
            exponent = (i+di,j+dj)
            if max(exponent) <= bound and exponent not in semigroup:
                semigroup.add(exponent)
                frontier.append(exponent)
    tested = list(product(range(bound), repeat=2))
    check('normalization_subring_semigroup', all(((i,j) in semigroup) == (i >= 1 or j % 2 == 0) for i,j in tested))
    check('conductor_monomials', all((((i,j) in semigroup) and ((i,j+1) in semigroup)) == (i >= 1) for i,j in tested))
    cases['semigroup_and_conductor'] = {'exponents_tested_each':len(tested),'bound_exclusive':bound}

    # Independent graded-dimension control for the invariant ring. Normal
    # forms are s^i b^epsilon c^j with epsilon in {0,1}; respective weights
    # are 1,2,2. In xy=0 the invariant dimension is n+[n even].
    dimensions = []
    for n in range(61):
        count = sum(1 for e in (0,1) for j in range(n//2+1) if n-2*e-2*j >= 0)
        dimensions.append(count)
        check(f'invariant_dimension_degree_{n}', count == n+int(n%2==0))
    forms = [(i,j,e) for i,j,e in product(range(17),range(17),(0,1))]
    images = [(i+e,2*j+e) for i,j,e in forms]
    check('quotient_normal_form_no_collisions', len(images) == len(set(images)))
    cases['normal_forms'] = {'forms_tested':len(forms),'degrees_checked':61}

    # Projective cubic parametrization, with coordinate degrees <=(6,9).
    def cubic_residual(S,T):
        X = T*(S*S-T*T)
        Y = S*(S*S-T*T)
        Z = T**3
        return Y*Y*Z-X**3-X*X*Z
    grid('projective_cubic_map', cubic_residual, (6,9))
    grid('affine_cubic_map', lambda s:(s*(s*s-1))**2-(s*s-1)**3-(s*s-1)**2, (6,))
    grid('cubic_collision_x', lambda s,r: (s*s-1)-(r*r-1)-(s-r)*(s+r), (2,2))
    grid('cubic_collision_y_opposite', lambda s:s*(s*s-1)-(-s)*((-s)**2-1)-2*s*(s*s-1), (3,))
    check('projective_no_basepoint_T_nonzero', all(T**3 != 0 for T in (-3,-2,-1,1,2,3)))
    check('projective_infinity_image_nonzero', all(S**3 != 0 for S in (-3,-2,-1,1,2,3)))
    check('node_hessian', rank([[-2,0],[0,2]]) == 2)
    check('point_at_infinity_derivative', 1**2-0**2 == 1)
    roots = (Fraction(0), Fraction(-2,3))
    check('cubic_repeated_root_candidates', all(3*r*r+2*r == 0 for r in roots))
    check('cubic_exceptional_values', sorted(-r**3-r**2 for r in roots) == [Fraction(-4,27),Fraction(0)])

    # Tetrahedral sphere with vertices 0 and 1 identified; keep every edge
    # as a CW 1-cell (edge 01 is a loop, not a discarded degenerate edge).
    edges = [(i,j) for i in range(4) for j in range(i+1,4)]
    faces = [(0,1,2),(0,1,3),(0,2,3),(1,2,3)]
    quotient_vertex = {0:0,1:0,2:1,3:2}
    d1 = [[0]*len(edges) for _ in range(3)]
    for col,(i,j) in enumerate(edges):
        d1[quotient_vertex[j]][col] += 1
        d1[quotient_vertex[i]][col] -= 1
    d2 = [[0]*len(faces) for _ in edges]
    for col,(i,j,k) in enumerate(faces):
        for edge,sign in (((i,j),1),((j,k),1),((i,k),-1)):
            d2[edges.index(edge)][col] += sign
    check('quotient_sphere_boundary_squared_zero', all(sum(d1[i][k]*d2[k][j] for k in range(6)) == 0 for i in range(3) for j in range(4)))
    check('quotient_sphere_boundary_ranks', (rank(d1),rank(d2)) == (2,3))
    betti = [3-rank(d1),6-rank(d1)-rank(d2),4-rank(d2)]
    check('nodal_cubic_betti_control', betti == [1,1,1])
    # Collapse tree edges 02,03. Other generators a=01,b=12,c=13,d=23.
    # Relations: ab, ac, d, bdc^-1. Eliminate b=c=a^-1,d=1.
    relations = [[1,2],[1,3],[4],[2,4,-3]]
    replacements = {1:[1],2:[-1],3:[-1],4:[]}
    reduced = []
    for rel in relations:
        word = []
        for letter in rel:
            image = replacements[abs(letter)]
            word += image if letter > 0 else [-x for x in reversed(image)]
        reduced.append(freely_reduce(word))
    check('nodal_cubic_relators_eliminate_to_one_free_generator', all(not w for w in reduced))

    result = {
        'status':'passed',
        'dependency':'Python 3 standard library; no author imports, no network',
        'assertions':len(checks),
        'checks':checks,
        'independent_case_counts':cases,
        'nodal_cubic_cellular_betti_numbers':betti,
        'limits':[
            'Grid identity proofs require the manually checked degree bounds listed in this file.',
            'Semigroup and dimension enumerations are finite controls, not their all-degree proofs.',
            'Cellular homology alone does not certify a fundamental group; the explicit presentation argument is separately reviewed.',
            'No controls certify arbitrary-group NC projective realization or completeness of literature search.'
        ]
    }
    if author_dir is not None:
        author = Path(author_dir).resolve()
        data = (author/'SHA256SUMS').read_bytes()
        assert hashlib.sha256(data).hexdigest() == EXPECTED_MANIFEST, 'unexpected frozen manifest'
        author_files = []
        for line in data.decode().splitlines():
            digest, name = line.split(None,1)
            name = name.strip()
            assert Path(name).name == name, 'unsafe manifest entry'
            actual = hashlib.sha256((author/name).read_bytes()).hexdigest()
            assert actual == digest, name
            author_files.append(name)
        run = subprocess.run([sys.executable,str(author/'verify_controls.py')],cwd=author,capture_output=True,check=True)
        assert run.stdout == (author/'control_results.json').read_bytes(), 'author replay differs'
        parsed = json.loads(run.stdout)
        assert parsed['total_assertions'] == 506 and parsed['invariant_monomial_controls'] == 481
        result['author_replay'] = {'frozen_manifest_sha256':EXPECTED_MANIFEST,'verified_files':author_files,'byte_identical':True,'assertions':506,'bounded_parity_controls':481}
    return result


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--author-dir',type=Path)
    args = parser.parse_args()
    print(json.dumps(main(args.author_dir),indent=2,sort_keys=True))
