"""Prepare exact public completion bodies without changing their live targets."""
from pathlib import Path
from datetime import datetime,timezone
import json,copy,hashlib,stat
D=Path(__file__).resolve().parent;A=D.parent;P=A.parent.parent;R=P.parent
W=D/'completion_preparation';assert not W.exists();W.mkdir()
sha=lambda b:hashlib.sha256(b).hexdigest()
def pin(p):
 p=Path(p);b=p.read_bytes();return dict(path=str(p.relative_to(R)),bytes=len(b),sha256=sha(b),mode=stat.S_IMODE(p.stat().st_mode))
m=json.loads((D/'ROOT_PR305_ACTUAL_MERGE_VERIFICATION.json').read_bytes());post=json.loads((D/'ROOT_PR305_POST_MERGE_CUSTODY.json').read_bytes())
assert m['status']=='PASS_PR305_EXACT_ORIGINAL_HEAD_MERGED_PUBLISHED_TRACKER_VERIFIED' and post['actual_merge']==m['actual_merge']
assert m['original_author_history']=='1/5' and m['DOI']=='10.5281/zenodo.23149775'
stamp=datetime.now(timezone.utc).isoformat()
summary='PR305 completed: displayed focal pedal equality E proved, stronger positive common phase-independent outer/original multiplier M proved, and common-focal-ratio phase constancy C disproved by exact triangle. Strict nested confocal elliptical caustics, primitive convex/star signed support-line areas, reversal/repetition and separate circle case are explicit. Prior observations/even symmetry/conditional old triangular consequence/classical negative implication/established methods are credited; bounded priority with six unavailable final editions, no absolute firstness. Repaired whole-preprint round01 followed by new clean round02; current six-page v1.0 note and portable archive published at '+m['DOI']+'. All eleven metadata values and two whole public files exact; ONE tracker row '+m['tracker_range']+' preserves every prior43-column formula row. One original-head merge '+m['actual_merge']+' preserves29 historical bodies/modes/blobs and author1/5, changes only target QUEUE cells8/9/11/12. Initial outerexit1 from immediate GitHub lag retained; actual sole push62553 and fresh readonly reconciliation verified, no repeated mutation. Extensive AI use, unrefereed, no outside human review/formal certification/person contact/GitHub release/journal submission. Math100%,bounded priority100%,PRworkflow100%; persistent descending goal active.'
invp=P/'inventory.json';before=invp.read_bytes();inv=json.loads(before);prior=copy.deepcopy(inv)
item=next(x for x in inv['items'] if x['number']==305);assert item['submitted_status']=='claimed_solved' and item['original_author_turn_count']=='1/5'
assert 305 not in inv['claimed_solved_published_by_descending'] and 305 not in inv['claimed_solved_merged_by_descending'] and inv['completed_by_descending']==26
item.update(original_submitted_status='claimed_solved',disposition='merged_claimed_solved_published_zenodo_tracker_verified',mathematical_verification_percent=100,bounded_priority_percent=100,workflow_percent=100,audit_workflow_percent=100,mathematical_acceptance=True,priority_acceptance=True,preprint_ready=True,publication_ready=True,actual_merge=m['actual_merge'],accepted_head=m['original_head'],merged_at=m['merged_at'],doi=m['DOI'],zenodo_record=23149775,final_clean_review='audits/pr305_5100034/root_during_peer_pause_20261005/preprint_review_02/REVIEW_REPORT.md',current_publication_status='audits/pr305_5100034/CURRENT_PUBLICATION_STATUS.json',historical_first_priority_certified=False)
for key in ['claimed_solved_published_by_descending','claimed_solved_merged_by_descending']:inv[key].append(305)
inv['completed_by_descending']+=1
assert all(x==y for x,y in zip(prior['items'],inv['items']) if x['number']!=305)
assert len(inv['claimed_solved_published_by_descending'])==len(inv['claimed_solved_merged_by_descending'])==8
maps=[]
def prepared(name,target,b):
 p=W/name;p.write_bytes(b);p.chmod(0o644);maps.append(dict(input=pin(p),target=str(target.relative_to(R)),original_target=pin(target) if target.exists() else None))
prepared('inventory.prepared.json',invp,(json.dumps(inv,indent=2)+'\n').encode())
for name,target in [('program_log.prepared.md',P/'RESEARCH_LOG.md'),('effort_log.prepared.md',A/'RESEARCH_LOG.md')]:prepared(name,target,target.read_bytes()+('\n'+stamp+' — '+summary+' Final scoped public audit checkpoint proposed; no future commit hash or completed push claimed by this precommit log.\n').encode())
prepared('effort_readme.prepared.md',A/'README.md',(A/'README.md').read_bytes()+('\n## Current completed acceptance and publication\n\n'+summary+'\n\nCurrent acceptance: [native result](../../../problems/5100034_focal_pedal_equality/CURRENT_ACCEPTANCE.md). [Preprint and verification archive](https://doi.org/10.5281/zenodo.23149775). Earlier dated progress/limitations below remain historical records and are superseded for current disposition by this section and CURRENT_PUBLICATION_STATUS.json. The exact postcommit checkpoint receipt is separate and is not invented here.\n').encode())
publication=dict(UTC=stamp,status='MERGED_PUBLISHED_AND_TRACKER_VERIFIED',pr=305,problem='5100034',mathematical_verification_percent=100,bounded_priority_percent=100,workflow_completion_percent=100,actual_merge=m['actual_merge'],accepted_head=m['original_head'],merged_at=m['merged_at'],zenodo_record=23149775,doi=m['DOI'],doi_url='https://doi.org/'+m['DOI'],record_url=m['record_url'],tracker_range=m['tracker_range'],tracker_spreadsheet_id='1ZljUv5Q98jNXLoHK8WjwrkzSm3dhHC1-7LElcOU7y20',tracker_gid=1254632077,original_author_turn_count='1/5',original29_attempt_files_unchanged=True,unresolved_mandatory_scientific_findings=0,bounded_historical_priority=True,historical_first_priority_certified=False,extensive_AI_use=True,unrefereed=True,external_human_review=False,formal_proof_assistant_certification=False,original_native_outer_exit1_preserved=True,readonly_reconciliation_after_one_successful_push=True,no_native_or_service_action_repeated=True,no_release_journal_submission_or_external_individual_contact=True,only_submitted_claimed_solved_PRs_in_scope=True,persistent_goal_complete=False,completed_by_descending=27,published_by_descending=8,final_checkpoint_actual_postcommit_receipt_is_separate=True,public_verification_package_portable=True,private_custody_bodies_not_claimed_public=True)
prepared('publication_status.prepared.json',A/'CURRENT_PUBLICATION_STATUS.json',(json.dumps(publication,indent=2)+'\n').encode())
paths=[P/'checkpoint_305_priority_routes_034_receipt.json',A/'ROOT_MATHEMATICAL_AUDIT.md',A/'ROOT_MATHEMATICAL_ACCEPTANCE.json']
names=['ROOT_PRIORITY_AUDIT.md','ROOT_PRIORITY_ACCEPTANCE.json','ROOT_TRIANGULAR_OLD_IMPLICATION_v02.md','ROOT_PREPRINT_REVIEW02_CUSTODY.json','ROOT_FULL_PREPRINT_PUBLICATION_CLEARANCE.json','ROOT_PUBLICATION_OPERATIONAL_CLEARANCE.json','ROOT_NATIVE_REVIEW01_CUSTODY.json','ROOT_NATIVE_REVIEW02_CUSTODY.json','ROOT_NATIVE_REVIEW03_CUSTODY.json','ROOT_PR305_NATIVE_INTEGRATION_CLEARANCE.json','ROOT_ACTUAL_PUBLIC_EVIDENCE_READBACK.json','ROOT_ACTUAL_PUBLICATION_TRACKER_FINAL_CUSTODY.json','ROOT_PR305_ACTUAL_MERGE_VERIFICATION.json','ROOT_PR305_POST_MERGE_CUSTODY.json','root_close_native_integration_review03.py','root_reconcile_pr305_actual_merge_readonly.py','root_authenticate_actual_publication_tracker.py','root_verify_actual_public_evidence.py','root_prepare_pr305_completion_packet.py']
paths += [D/n for n in names]
paths += [D/'native_integration_preparation/integrate_pr305.py']+[D/'publication_preparation'/n for n in ['submission_gate.py','run_zenodo_step.py','public_identity.py','verify_public_record.py','append_tracker.py']]
for family,names in {'preprint_review_01':['REVIEW_REPORT.md','criteria_frozen.json','ALL_INPUT_BINDINGS.json'],'preprint_review_02':['REVIEW_REPORT.md','INPUT_AND_NAMESPACE_INVENTORY.json'],'publication_operations_review_01':['REVIEW_REPORT.md','REVIEW_REPORT.json','FROZEN_CRITERIA.md','OUTPUT_INVENTORY.json'],'publication_operations_review_02':['REVIEW_REPORT.md','REVIEW_REPORT.json','TEST_SUMMARY.json','INDEPENDENT_RECONSTRUCTION.md','OUTPUT_INVENTORY.json'],'native_integration_review_01':['REVIEW_REPORT.md','OUTPUT_INVENTORY.json'],'native_integration_review_02':['REVIEW_REPORT.md','OUTPUT_INVENTORY.json'],'native_integration_review_03':['REVIEW_REPORT.md','CRITERIA.json','FINAL_AUTHENTICATION.json','INPUT_INVENTORY.json','OUTPUT_INVENTORY.json','CAPTURE_RESULTS.json','CAPTURE_RESULTS_v02.json','INTEGRATION_MOCK_RESULTS.json']}.items():paths += [D/family/n for n in names]
for n in ['stage_receipt.json','inspect_draft_receipt.json','publish_receipt.json','inspect_published_receipt.json','PUBLIC_RECORD_VERIFICATION.json','TRACKER_COMPLETE.json']:paths.append(D/'publication_actual'/n)
# Public authored source/supplement/licensing and provenance are already part of
# the independently reviewed portable ZIP; include their exact frozen copies.
manifest=json.loads((D/'preprint_review02_candidate_frozen/MANIFEST.json').read_bytes())
for e in manifest['files']:paths.append(D/'preprint_review02_candidate_frozen'/e['path'])
assert len(paths)==len(set(paths))
for p in paths:
 assert p.is_file() and not p.is_symlink(),str(p)
 maps.append(dict(input=pin(p),target=str(p.relative_to(R)),original_target=pin(p)))
assert len({e['target'] for e in maps})==len(maps)
plan=dict(schema='PR305-exact-public-completion-packet/v1',UTC=stamp,status='PREPARED_EXACT_COMPLETION_CONTENT_PENDING_INDEPENDENT_ADVERSARY_AND_FRESH_WRITER_SCOPE',targets=maps,target_count=len(maps),actual_merge=m['actual_merge'],original_head=m['original_head'],original_author_turn_count='1/5',DOI=m['DOI'],tracker_range=m['tracker_range'],current_native_merge_and_publication_complete=True,global_target_writes_performed=False,math_percent=100,bounded_priority_percent=100,PR_workflow_percent=100,completed_by_descending=27,published_by_descending=8,persistent_goal_complete=False,public_scope='Authored mathematical/priority/review/operational reports and code, metadata and source/hash inventories, actual result/publication/one-own-tracker-row receipts, original preprint source+portable verification materials and five current progress proposals. No third-party PDFs/full extractions, whole other tracker rows, private process tapes, raw foreign index/diff/body records or fixture archives. Local evidence references remain references, not claims that their excluded bodies are public.',source=pin(Path(__file__).resolve()))
p=W/'CONTENT_PLAN.json';p.write_text(json.dumps(plan,indent=2)+'\n');print(json.dumps(dict(plan=pin(p),target_count=len(maps),total_selected_bytes=sum(e['input']['bytes'] for e in maps),global_writes=False,completed=27,published=8),indent=2))
