"""ROOT-only complete PR46 actual post inspection. Prepared source; ROOT reads/copies unchanged before running after all phase exits."""
from pathlib import Path
import copy,datetime as dt,hashlib,json,stat,subprocess,sys,os
sys.dont_write_bytecode=True
A=Path(__file__).resolve().parent;R=A.parents[2];H=A/'acceptance_preparation_family_v2';K=R/'unsolved_math_prioritization/attempts/30004438';B=A.parents[1]
HEAD='a39d178b10f75fb127058b08e0d0002b3ae97f8a';BASE='c6975ca76f9f667f1250ba403d0e6da2aafe14d0';PREP='f44ccf65fa4397736305881de926eafcf211c33ef9e6fec5e5596c99d252ef40';CONTRACT='b2142489e5fbc07cf80d65372891e02864db08aceef4a7ce8a8f20c88a795fb8'
sha=lambda b:hashlib.sha256(b).hexdigest()
def need(v,m):
    if not v:raise ValueError(m)
def raw(p):need(p.is_file() and not p.is_symlink() and all(not x.is_symlink() for x in p.parents),'Regular nonsymlink');return p.read_bytes()
def load(p):return g.load(p)
def eq(a,b):return g.equal(a,b)
def pin(p):b=raw(p);return {'path':p.relative_to(R).as_posix(),'bytes':len(b),'sha256':sha(b)}
def clock(s):return g.utc_clock(s,'Actual UTC')
def put(p,b):
    with p.open('xb') as h:h.write(b);h.flush();os.fsync(h.fileno())
def check(base,z):g.exact_reference(z);g.check(base,[z]);return raw(base/z['path'])
COMMANDS=[]
def git(*args):
    need(args and args[0] in {'show','ls-tree','diff','merge-base'},'Read-only Git whitelist');root=A/'ROOT_POST_ACTUAL_GIT';root.mkdir(exist_ok=True);d=root/str(len(COMMANDS));d.mkdir(exist_ok=False);source=raw(Path(__file__));operator=raw(A/'root_complete_actual_post_inspection_capture/prelaunch_operator.py')
    pre={'schema':'pr46-root-post-actual-Git-prelaunch/v1','operator_pid':os.getpid(),'argv':['git',*args],'cwd':str(R),'started_utc':dt.datetime.now(dt.timezone.utc).isoformat(),'source_sha256':sha(source),'capture_operator_sha256':sha(operator)};put(d/'PRELAUNCH.json',(json.dumps(pre,indent=2)+'\n').encode());proc=subprocess.Popen(pre['argv'],cwd=R,stdin=subprocess.DEVNULL,stdout=subprocess.PIPE,stderr=subprocess.PIPE,env=dict(os.environ,GIT_OPTIONAL_LOCKS='0'));out,err=proc.communicate();cap=dict(pre,schema='pr46-root-complete-actual-post-Git/v1',pid=proc.pid,actual_execution=True,completed=True,exit_code=proc.returncode,finished_utc=dt.datetime.now(dt.timezone.utc).isoformat(),source_unchanged=raw(Path(__file__))==source)
    for k,b in [('stdout',out),('stderr',err)]:put(d/(k+'.bin'),b);cap[k]=pin(d/(k+'.bin'))
    put(d/'CAPTURE.json',(json.dumps(cap,indent=2)+'\n').encode());COMMANDS.append(cap);need(type(cap['pid']) is int and cap['pid']>0 and proc.returncode==0 and err==b'' and cap['source_unchanged'] is True,'Actual full read-only Git capture');return out
def main():
    global g
    need(__debug__ and sys.flags.optimize==0 and os.environ.get('PYTHONOPTIMIZE','') in ('','0'),'Nonoptimized guards');need(A.name=='pr46_30004438','Copy unchanged adjacent to A46, never run preparation path');need(raw(A/'ROOT_POST_INSPECTION_PRELAUNCH_SOURCE.py')==raw(Path(__file__)),'ROOT prelaunch body');need(sha(raw(H/'PREPARATION_MANIFEST.json'))==PREP and sha(raw(H/'ROOT_POST_CONTRACT.json'))==CONTRACT,'Exact closed46V2 source and22-key contract')
    sys.path.insert(0,str(H));import pr46_guards as g
    contract=load(H/'ROOT_POST_CONTRACT.json');pre=load(A/'integration_preflight.json');post=load(A/'post_acceptance_verification.json');accept=load(A/'acceptance.json');canonical=load(K/'acceptance.json');overlay=load(A/'integration_check.json');final=load(A/'integration_finalization.json');fresh=load(A/'ROOT_FRESH_ACCEPTANCE_INPUT_PREIMAGES.json');remote=load(A/'remote_merge_receipt.json')
    need(pre['main_before']==fresh['current_head']=='8e04757bff6e5c6c25d2dbf23ce10f736da8c5c8' and fresh['approved_by_root'] is True,'Genuine fresh/preflight main authority');need(post['status']=='PASS' and type(post['program_completed_count']) is int and post['program_completed_count']==36 and post['full_problem_solved'] is True and post['full_problem_solved_by_project'] is False,'Credited already-solved result, not project discovery');merge=accept['merge_commit'];need(merge==post['merge_commit']==final['merge_commit']==remote['mergeCommit']['oid'],'Actual merge equality')
    need(git('show','-s','--format=%P',merge).decode().strip().split()==[pre['main_before'],HEAD] and git('merge-base',HEAD,BASE).decode().strip()==BASE,'Fresh first/original second parent, equal original base/mergebase');need(git('show','-s','--format=%T',merge).decode().strip()==post['merge_tree']==accept['merge_tree'],'Actual tree');need(eq(canonical,{k:v for k,v in accept.items() if k not in {'canonical_manifest_entries','canonical_manifest_sha256'}}),'Entire audit/canonical receipt')
    g.manifest(K,'MANIFEST.json',accept['canonical_manifest_sha256'],957,frozen=True);g.canonical(g.rows(load(g.C/'MANIFEST.json')['files']),True);g.source(K);need(len(g.IMMUTABLE)==8 and len(load(A/'snapshot_manifest.json')['files'])==13,'Original13/immutable8')
    prefix=K.relative_to(R).as_posix()+'/';rr=overlay['canonical_overlay_files'];need(len(rr)==955,'Entire955 overlay');expected_paths={prefix+z['path'] for z in rr}|{'unsolved_math_prioritization/QUEUE.md'};need(set(git('diff','--name-only',pre['main_before'],merge).decode().splitlines())==expected_paths,'Exact merge changed paths')
    tree=git('ls-tree','-r','-z',merge,'--',K.relative_to(R).as_posix()).decode().split('\0');entries={}
    for line in filter(None,tree):fields,n=line.split('\t');mode,kind,blob=fields.split();need(mode=='100644' and kind=='blob','Literal canonical Git100644');entries[n]=blob
    need(set(entries)=={prefix+z['path'] for z in rr},'Complete Git overlay topology')
    for z in rr:b=git('show',merge+':'+prefix+z['path']);need(len(b)==z['bytes'] and sha(b)==z['sha256'],'Whole Git overlay body')
    patch=load(K/'ACCEPTED_QUEUE_PATCH.json');before=raw(A/'integration_queue_before.md');queue=raw(R/'unsolved_math_prioritization/QUEUE.md');old=patch['row_before'].encode();new=patch['row_after'].encode();need(sha(before)==patch['whole_before_sha256'] and sha(queue)==patch['whole_after_sha256'] and before.count(old)==1 and before.replace(old,new,1)==queue and queue.replace(new,old,1)==before,'Whole queue exact replacement');oc=old.split(b'|');nc=new.split(b'|');need([i for i in range(len(oc)) if oc[i]!=nc[i]]==[8,11] and oc[9]==nc[9] and nc[9].strip()==b'0/5' and oc[10]==nc[10] and oc[12]==nc[12],'Only Status/Findings; zero-turn/Chat/DOI retained');need(git('show',merge+':unsolved_math_prioritization/QUEUE.md')==queue,'Whole Git queue')
    prior=load(A/'integration_state_before.json');state=load(R/'unsolved_math_prioritization/state.json');plan=load(A/'state_mirror_plan.json');intent=load(A/'state_mirror_intent.json');receipt=load(A/'state_mirror_receipt.json');need(len(prior)==36 and len(state)==37 and set(state)==set(prior)|{'30004438'} and all(eq(v,state[k]) for k,v in prior.items()) and eq(state,plan['state_after']),'All36 prior typed states preserved');oldh=raw(A/'integration_history_before.jsonl');newh=raw(R/'unsolved_math_prioritization/history.jsonl');need(newh==oldh+plan['history_append_bytes'].encode() and len(plan['history_append'])==1,'Exact full history prefix+one event');event=g.parse(newh[len(oldh):]);need(eq(event,plan['history_append'][0]) and event['id']=='30004438' and event['event']=='acceptance_mirror_import' and type(event['turns_used']) is int and event['turns_used']==0 and event['turn_limit']==5 and event['status']=='already_solved','Ordinary present already_solved0/5 event');need(all(type(z['turns_used']) is int for z in state.values()) and sum(z['turns_used'] for z in state.values())==44 and intent['status']=='COMPLETED' and receipt['current_targets']==37 and receipt['primary_acceptances']==36 and receipt['history_events_added']==1 and receipt['new_proof_turns']==0,'37targets44turns36primary')
    inv=load(B/'inventory.json');before_inv=load(A/'integration_inventory_before.json');need(len(before_inv['items'])==180 and before_inv['completed_count']==35 and sum(z.get('stage')=='complete' for z in before_inv['items'])==35,'Entire before inventory');expected=copy.deepcopy(before_inv);chosen=next(z for z in expected['items'] if z['number']==46);chosen.update(stage='complete',outcome='already_solved_accepted_known_result',queue_status='already_solved',audited_head=HEAD,merge_commit=merge,merged_at=remote['mergedAt'],workflow_completion_estimate_percent=100,original_attempts='0/5',original_source_verification_responses=1,new_substantive_attempts=0,cumulative_attempts='0/5',paper_or_new_doi_or_tracker=False);expected.update(updated_at_utc=final['utc'],last_checkpoint_utc=final['utc'],completed_count=36,program_completion_estimate_percent=20.0,completion_estimate_percent=20.0,current_pr=47);need(eq(inv,expected) and sum(z.get('stage')=='complete' for z in inv['items'])==36,'Independent entire180 inventory,35 prior+selected46, next47/20%')
    changed={'draft_pr_publication_program_20260930/inventory.json','unsolved_math_prioritization/QUEUE.md','unsolved_math_prioritization/state.json','unsolved_math_prioritization/history.jsonl'};current13=[];need(len(fresh['files'])==13 and len({z['path'] for z in fresh['files']})==13,'Literal fresh13')
    for z in fresh['files']:
        q=R/z['path'];p=pin(q);need(type(z['worktree_mode']) is int and stat.S_IMODE(q.stat().st_mode)==z['worktree_mode'],'Full fresh native mode')
        if z['path'] not in changed:need(eq(p,{k:z[k] for k in ['path','bytes','sha256']}),'Stable9 exact')
        current13.append({**p,'worktree_mode':stat.S_IMODE(q.stat().st_mode)})
    caps=[];previous_end=None
    for phase in ['preflight','overlay','prepush','finalize','mirror','post']:
        d=A/('root_'+phase+'_actual_capture');need({p.name for p in d.iterdir()}=={'CAPTURE.json','PRELAUNCH.json','PRELAUNCH_SOURCE.py','PRELAUNCH_OPERATOR.py','stdout.bin','stderr.bin'},'Exact phaseCAP6');c=load(d/'CAPTURE.json');pp=load(d/'PRELAUNCH.json');need(c['actual_execution'] is True and c['completed'] is True and c['status']=='PASS' and type(c['exit_code']) is int and c['exit_code']==0 and type(c['pid']) is int and c['pid']>0 and type(c['operator_pid']) is int and c['operator_pid']>0 and c['source_unchanged'] is True and c['operator_unchanged'] is True and c['stdin_supplied'] is False and c['cwd']==str(R),'Genuine typed complete phase');need(all(eq(c[k],v) for k,v in pp.items() if k!='schema'),'Entire prelaunch');name={'mirror':'state_mirror_reconciliation.py','post':'verify_post_acceptance.py'}.get(phase,'integrate_reviewed_partial.py');need(c['argv'][:3]==['/usr/bin/python3','-B',str(H/name)] and sha(raw(d/'PRELAUNCH_SOURCE.py'))==c['source_sha256']==sha(raw(H/name)) and sha(raw(d/'PRELAUNCH_OPERATOR.py'))==c['operator_sha256']==sha(raw(A/'run_actual_acceptance_phases.py')),'Exact actual phase argv/source/operator')
        argv=['/usr/bin/python3','-B',str(H/name),'--execute','--preparation-manifest-sha256',PREP]
        for flag in ['final-plan','final-receipt','final-manifest','reconciliation-capture','previous-mirror','previous-post','fresh-preimage','root-bindings']:
            key=flag.replace('-','_');argv.extend(['--'+flag,pins[key],'--'+flag+'-sha256',pins[key+'_sha256']])
        if phase not in ['mirror','post']:argv.append(phase)
        if phase=='overlay':argv.extend(['--merge-queue-preimage-sha256',overlay['automatic_merge_queue_preimage_sha256']])
        need(eq(c['argv'],argv),'Entire literal phase argv')
        for channel in ['stdout','stderr']:need(c[channel]['path']==channel+'.bin','Literal phase stream');check(d,c[channel])
        need(raw(d/'stderr.bin')==b'' and clock(c['started_utc'])<=clock(c['finished_utc'])<=dt.datetime.now(dt.timezone.utc),'Whole phase streams/aware clocks');need(previous_end is None or previous_end<=clock(c['started_utc']),'Actual phase ordering');previous_end=clock(c['finished_utc']);caps.append(pin(d/'CAPTURE.json'))
    pins={n:post[n] for n in ['preparation_manifest_sha256','final_plan','final_plan_sha256','final_receipt','final_receipt_sha256','final_manifest','final_manifest_sha256','reconciliation_capture','reconciliation_capture_sha256','previous_mirror','previous_mirror_sha256','previous_post','previous_post_sha256','fresh_preimage','fresh_preimage_sha256','root_bindings','root_bindings_sha256']};previous=load(R/pins['previous_mirror']);need((R/pins['previous_mirror']).parent==A.parent/'pr45_9900007','Actual previous45');proposal=load(A/'state_mirror_bindings.json');g.mirror_proposal(proposal,pins);g.mirror_records(pins,pre,plan,intent,receipt,proposal);need(eq(g.rebuild_saved_mirror_plan(proposal,plan['created_at_utc'],raw(A/'integration_state_before.json'),oldh),plan),'Entire saved plan reconstructed at actual timestamp');mod=g.mirror_module(proposal);s=raw(R/'unsolved_math_prioritization/state.json');h=raw(R/'unsolved_math_prioritization/history.jsonl');noop=mod.build_plan(R,proposal);mod.validate_plan(R,noop);need(noop['history_append']==[] and noop['state_after_bytes'].encode()==s and noop['history_append_bytes']=='' and noop['history_after_sha256']==sha(h) and raw(R/'unsolved_math_prioritization/state.json')==s and raw(R/'unsolved_math_prioritization/history.jsonl')==h,'Fresh no-write exact no-op')
    g.accepted_invariants(canonical,pins,pre);g.accepted_invariants(accept,pins,pre,audit=True);g.source(K);g.protected_foreign_paths(fresh['protected_foreign_tracked_paths']);need(len(fresh['protected_foreign_tracked_paths'])==5,'All five actual protected foreign paths');g.foreign_check(pre);g.owned_log_append_check(pre)
    for n in sorted(changed):body=git('show',merge+':'+n);entry=git('ls-tree','-z',merge,'--',n);need(body==(queue if n.endswith('/QUEUE.md') else git('show',pre['main_before']+':'+n)) and entry.decode().startswith('100644 blob ') and entry.decode().endswith('\t'+n+'\0'),'Whole tracked native Git body/mode')
    sd=A/'root_final_reconciliation_actual_capture';need({p.name for p in sd.iterdir()}=={'CAPTURE.json','PRELAUNCH_SOURCE.py','PRELAUNCH_OPERATOR.py','stdout.bin','stderr.bin'},'Actual finalCAP5');sealer=load(sd/'CAPTURE.json');need(sealer['actual_execution'] is True and sealer['completed'] is True and sealer['status']=='PASS' and type(sealer['exit_code']) is int and sealer['exit_code']==0 and type(sealer['pid']) is int and sealer['pid']==60897 and sealer['source_unchanged'] is True and eq(sealer['native13_before'],sealer['native13_after']) and sealer['main_head_before']==sealer['main_head_after'],'Genuine completed60897 sealer, equality within its own epoch only');need(sha(raw(sd/'PRELAUNCH_SOURCE.py'))==sealer['source_sha256']==sha(raw(H/'seal_final_evidence.py')) and sha(raw(sd/'PRELAUNCH_OPERATOR.py'))=='ded1b43627fb695cf5ca2f279647a4b0bbafec79d4bf5aa91b363ed5029d291e','Complete actual sealer source/operator')
    for channel in ['stdout','stderr']:check(sd,sealer[channel])
    fr=load(A/'final_review/ROOT_FINAL_RECONCILIATION.json');need(raw(sd/'stderr.bin')==b'' and clock(sealer['started_utc'])<=clock(fr['utc'])<=clock(sealer['finished_utc']),'Whole sealer streams/receipt UTC; no equality to newer fresh snapshot')
    for c in sealer['readonly_git_queries']:need(c['actual_execution'] is True and c['completed'] is True and type(c['pid']) is int and c['pid']>0 and type(c['exit_code']) is int and c['exit_code']==0 and c['stderr']=='' and clock(c['started_utc'])<=clock(c['finished_utc']),'Every actual readonly sealer query')
    expected_post={**contract['required_entire_post_values'],**pins,'utc':post['utc'],'merge_commit':merge,'merge_tree':accept['merge_tree'],'actual_remote_state':'MERGED'};need(eq(post,expected_post),'Entire exact typed verifier post, not subset flags');observed=g.parse(subprocess.check_output(['gh','pr','view','46','--repo','AlecKriebel/Math','--json','number,state,isDraft,headRefOid,baseRefName,headRefName,body,mergeCommit,mergedAt,url'],cwd=R));need(eq(observed,remote),'Fresh entire actual remote')
    result={'schema':contract['required_ROOT_schema'],**contract['required_completed_values'],'utc':dt.datetime.now(dt.timezone.utc).isoformat(),'entire_post':post,'all_six_real_phase_captures':caps,'current13':current13,'final_sealer_actual_capture':pin(sd/'CAPTURE.json')};need(set(result)==set(contract['required_ROOT_complete_keyset']) and len(result)==22,'Exact22-key complete ROOT post');need(all(eq(result[k],v) for k,v in contract['required_completed_values'].items()),'Every explicit completed value');put(A/'ROOT_POST_ACTUAL_GIT_COMMANDS.json',(json.dumps(COMMANDS,indent=2)+'\n').encode());put(A/'ROOT_ACTUAL_POST_INSPECTION.json',(json.dumps(result,indent=2)+'\n').encode());print(json.dumps({'status':'PASS_COMPLETE_ACTUAL_ROOT_POST_INSPECTION','merge_commit':merge,'primary_acceptances':36,'targets':37,'consumed_substantive_turns':44,'inspection':pin(A/'ROOT_ACTUAL_POST_INSPECTION.json')}))
if __name__=='__main__':main()
