"""Own bounded SOURCE audit authorship only; no candidate/ROOT helper execution."""
from pathlib import Path
import datetime as dt,hashlib,json,os,stat
R=Path('/Users/alec/Documents/Math');A=R/'draft_pr_publication_program_20260930/audits/pr48_2961';F=A/'corrective_source_adversary_v4';P=A/'post_push_foreign_epoch_preparation_v4';OLD=A/'corrective_source_adversary_v3';NOW=dt.datetime.now(dt.timezone.utc).isoformat();SHA='4a2ca334cfea92fb44dfebb874de8d4b0827292b0ab3fb7e82a57de3b8746771'
def raw(q):
    assert q.is_file() and not q.is_symlink() and all(not p.is_symlink() for p in q.parents);return q.read_bytes()
def ref(q):
    b=raw(q);return dict(path=q.relative_to(R).as_posix(),bytes=len(b),sha256=hashlib.sha256(b).hexdigest(),full_mode=stat.S_IMODE(q.stat().st_mode))
def put(n,v):
    b=(json.dumps(v,indent=2,allow_nan=False)+'\n').encode() if type(v) is not str else v.encode()
    with (F/n).open('xb') as q:q.write(b)
    assert stat.S_IMODE((F/n).stat().st_mode)==0o644
rows={}
def add(z):
    assert ref(R/z['path'])==z
    if z['path'] in rows:assert rows[z['path']]==z
    rows[z['path']]=z
old=json.loads(raw(OLD/'FIXED_INPUT_BINDINGS.json'));assert old['fixed_rows_count']==172
for z in old['fixed_rows']:add(z)
families=old['exact_preserved_families'][:]
files=sorted(q for q in P.rglob('*') if q.is_file());dirs=sorted(q for q in P.rglob('*') if q.is_dir());assert len(files)==24 and len(dirs)==4
for q in files:add(ref(q));assert stat.S_IMODE(q.stat().st_mode)==0o644
families.append(dict(path=P.relative_to(R).as_posix(),payload_count=24,payload_names=[q.relative_to(P).as_posix() for q in files],directory_names=['.']+[q.relative_to(P).as_posix() for q in dirs],full_file_mode=0o644,full_directory_mode=0o755))
mf=json.loads(raw(OLD/'SELF_MANIFEST.json'));assert hashlib.sha256(raw(OLD/'SELF_MANIFEST.json')).hexdigest()=='563dd629787b0d7012544ae0a47b7c1832896c8001c043dadf9a908e60e17d32' and mf['files_count']==24 and mf['verdict_status']=='REPAIR_REQUIRED_SOURCE'
for z in mf['files']:
    q=OLD/z['path'];b=raw(q);assert len(b)==z['bytes'] and hashlib.sha256(b).hexdigest()==z['sha256'];add(ref(q));assert stat.S_IMODE(q.stat().st_mode)==0o444
add(ref(OLD/'SELF_MANIFEST.json'))
families.append(dict(path=OLD.relative_to(R).as_posix(),payload_count=25,payload_names=sorted([z['path'] for z in mf['files']]+['SELF_MANIFEST.json']),directory_names=[z['path'] for z in mf['directory_modes']],full_file_mode=0o444,full_directory_mode=0o755))
history=json.loads(raw(P/'M3_AND_SUPERSEDED_V3_BINDINGS.json'));caps=history['actual_completed_M3_adverse_binding']['complete_actual_ROOT_captures'];assert [z['complete_capture']['pid'] for z in caps]==[3854,4081]
outerdirs=[]
for z in caps:
    for t in z['members']:add(t)
    q=R/z['capture']['path'];actual=json.loads(raw(q));assert actual==z['complete_capture'] and actual['exit_code']==0 and actual['status']=='PASS';assert stat.S_IMODE(q.parent.stat().st_mode)==0o700
    outerdirs.append(dict(path=q.parent.relative_to(R).as_posix(),full_mode=0o700))
assert not (P/'SOURCE_MANIFEST.json').exists() and hashlib.sha256(raw(P/'SOURCE_READY.json')).hexdigest()==SHA
assert not (A/'capture_root_command.py').exists() and not (A/'capture_root_command.py').is_symlink()
for t in json.loads(raw(P/'SOURCE_READY.json'))['source_files']:
    assert {k:rows[t['path']][k] for k in t}==t
result=json.loads(raw(F/'private_actual_capture/stdout.json'));cap=json.loads(raw(F/'private_actual_capture/CAPTURE.json'));assert result['checks']==22 and result['actual_private_pid']==cap['pid']==12372 and cap['operator_pid']==12371 and cap['status']=='PASS' and cap['exit_code']==0
for z in result['other_parent_counterexamples']:assert z['V4_context_unchanged'] is True and z['actual_outer_parent_equals_selected_operator_parent'] is False
put('FIXED_INPUT_BINDINGS.json',dict(schema='pr48-v4-independent-fixed-source-and-historical-bindings/v1',observed_utc=NOW,fixed_rows_count=len(rows),fixed_rows=[rows[k] for k in sorted(rows)],exact_preserved_families=families,additional_genuine_outer_directory=old['additional_genuine_outer_directory'],additional_genuine_outer_directories=outerdirs,candidate_SOURCE_manifest_absent_at_observation=True,candidate_closure_required=False,qualification='Rejected V4 remains unclosed full0644. V3 candidate/old V2 stay unclosed and exact; genuine M3 review24+self25 is separately closed444 with genuine3854/4081 receipts. No native live or future runtime authority. Complete custody reads are not new mathematical proof.'))
finding=dict(id='M4',title='Named A48 live operator is not reconciled to actual outer capture parent in author/caller roles',locations=['epoch_common.py:92-95','author_post_push_foreign_epoch_v4.py:35','run_post_push_foreign_epoch_phase_v4.py:30','capture_root_command.py:12','capture_root_command.py:24-25'],mechanism='Author/caller accept any safe repository-relative outer path. live_operator_binding always describes A48/capture_root_command.py without requiring directory.parent==A48. c1ae creates its genuine outer beside its actual source parent; another-parent invocation can therefore describe the healthy A48 copy while omitting actual running source permissions.',actual_private_pid=12372,actual_private_modes=[0o600,0o2644,0o4644],selected_live_mode=0o644,snapshot_mode=0o644,outer_mode=0o700,repair='Add one explicit exact parent identity predicate at the common actual-live/operator boundary: outer.parent must equal A48. Preserve typed live0644/c1ae/whole snapshot equality/parent0755 and outer0700. ROOT must use the reviewed A48 copy for all actual author/caller/inspector outer invocations.',reasonably_repairable=True,mathematical_defect=False)
put('VERDICT.json',dict(schema='pr48-post-push-epoch-independent-SOURCE-verdict/v1',status='REPAIR_REQUIRED_SOURCE',utc=NOW,source_ready_sha256=SHA,mandatory_findings=[finding],production_executed=False,future_acceptance_approved=False,review_continuity='Same corrective investigator as original M1/M2/M3; no blind new mathematical family or credit.',M2_four_outer0700_roles_preserved=True,M3_literal_named_live_source_mode_repair_verified=True,complete_actual_operator_identity_custody_verified=False,checked_current_candidate_payloads=24,fixed_input_bindings=len(rows),actual_private_controls=dict(caller_pid=12371,pid=12372,checks=22,capture='private_actual_capture/CAPTURE.json',whole_stdout_sha256=cap['stdout']['sha256'],whole_stderr_sha256=cap['stderr']['sha256']),original_science_and22_ROOT_contract_unchanged=True,original_first_three_receipts_unchanged=True,actual_recovery_completion_percent=0,source_review_completion_percent=100,mathematical_credit=0,remaining_gap='Narrow exact actual-outer-parent repair and corrective SOURCE review; genuine ROOT closure/readback, unchanged A48 operator copy, actual final3 roles and completed22 post, then separately reviewed PR49 mixed-phase consumer.'))
put('REPORT.md',f'''# PR48 corrective V4 SOURCE audit

REPAIR_REQUIRED_SOURCE, mandatory M4. Bound READY`{SHA}` adds the intended typed live0644/c1ae/whole-snapshot-equality/actualparent0755 descriptor and propagates it through author/caller/inspector contexts. It correctly rejects the original M3 named-live chmod examples. However, author/caller still permit an outer capture from another source parent, so the named source is not necessarily the actual running operator. One exact parent-identity requirement reasonably repairs this operational defect. No mathematical flaw or new credit is asserted.

Scope was recorded before implementation reading at2026-10-03T17:11:12.069303UTC. This is explicit same-investigator corrective continuity from the closed M3 rejection; the earlier V2 PASS is preserved incomplete history. No blind/new mathematical family is claimed. The actual M3 evidence SELF563dd629… remains full0444, all24 payloads/self25 rechecked, and genuine ROOT closure3854/separate readback4081 CAP4 full bodies/modes were rechecked as completed adverse-evidence operations only. Rejected candidate24V3 and old45V2 stay unclosed0644 and unchanged.

## Complete source changes and working repair

All nine operative/closure sources were read completely as text and compared against V3 with explicit literal filename/path/schema substitutions; the full residual diff is saved in COMPLETE_SOURCE_CHANGE_MAP.json. Common adds only the M3 history member, actual-live descriptor function and its author/caller context entries. Inspector adds the same live descriptor. Other actors/closers have no residual change. Finalizer and mirror are byte-identical. Contract changed keys are fully recorded: versioned schemas plus live path/SHA/modes/future copy/M3 qualification, without scientific contract or native/foreign predicate relaxation. Original acceptance_preparation_family_v3 and native revision2 paths were never normalized away.

Common94–95 reads the named A48 source with the existing stable regular full07777 reader, requires0644, entire c1ae2593B SHA and bytes equal outer/prelaunch_operator.py, and binds A48parent0755. Author103/caller104 and inspector37 add this descriptor to their before/after contexts. The actual readonly digests, epoch validation264, phase validation356, caller immediate child boundaries and final inspector runtime evidence therefore carry the named descriptor. Private controls confirm M3 live600/2644/4644 now reject; liveparent700/2755, outer755/2700, invalid mode types and whole snapshot substitution reject. M2 four typed outer700 roles and own/source/prelaunch755 remain unchanged.

The exact original science17, closed53 source, ordinary unsolved2961/shared30004403 budget2/5,new0/audit0, subgroup4/allpowers/qualified averaging partial scope, original first3 genuine receipts, merge209581a4627b01745974837fe7adab62ab8c0af7 and original22-key ROOT scientific post conditions remain intact. Current per-role HEAD/whole index/complete foreign body-fullmode/native13 scope, whole QUEUE accepted-target/absent-alias and unrelated-row preservation, exact two logs, absent-only recovery and honest failed19622 history remain required. Later post-mirror drift still refuses. New final3 must be genuine V4 actual sources/argv/dependencies/streams; no old receipt is relabeled. No future recovery, paper, DOI, ROOT approval or PR49 consumer compatibility exists yet.

## M4 actual source identity gap and genuine private counterexample

Author35 and caller30 accept `R/safe(--outer-capture-directory)` without constraining that directory's parent to A48. Common92–95 validates the chosen outer snapshot700/644 but always describes the fixed A48 live source. The unchanged c1ae operator12/24–25 puts an actual CAP4 beside its own source parent. Hence a genuine-style other-parent outer can be reconciled against a healthy A48 copy while permissions of the actual other-parent running source are omitted. Inspector already constrains its outer to A48 adjacency; the shared boundary needs that exact identity for author/caller as well.

Actual private caller12371 launched handwritten child12372, exit0,2026-10-03T17:15:09.195208–17:15:09.231174UTC. Its22 selected controls include three real filesystem counterexamples: healthy selected-A48 source644/parent755, another-parent c1ae source chmod644→600/2644/4644, retained other-parent snapshot644 and outer700. Whole actual/selected/snapshot bodies stay c1ae. All three complete V4 modeled contexts remain equal, while actual-live644 and required outer.parent==selectedparent reject. Only private fixtures changed; all sources restored644 and directories755. No candidate or c1ae code was imported, compiled or executed. Full prelaunch sources/operator/argv/PIDs/times/stdout5801B SHA`{cap['stdout']['sha256']}` and empty stderr are retained in private_actual_capture.

ROOT explicitly confirms the concrete plan uses only unchanged A48 c1ae for ALL author/caller/inspector production outer roles. That plan needs a runtime source predicate, not an implicit assumption. Add one explicit `outer.parent==A48` requirement at live/operator binding before context formation. Retain all fullmode/body/snapshot predicates and outer700; no new exception is needed. A48/capture_root_command.py remains absent at this dated review and is to be copied/reread by ROOT only after clean review; its absence is not held as future mutable authority in the custody ledger.

FIXED_INPUT_BINDINGS.json has{len(rows)} unique full body/fullmode rows in place, including current24, prior selected172, closed M3review25 and genuine CAP4s8; no corpus copies or native live hashes were added. This bound V4 SOURCE rejection review is100% complete; actual recovery0%, mathematical discovery0%. Remaining work is the exact narrow repair/review, genuine ROOT-only closure/readback/runtime operations and complete22 post, then separate PR49 consumer repair. Own short evidence closer/readback remain unexecuted; they may freeze this adverse review only, never candidate V4 or production authority.
''')
put('RESEARCH_LOG.md',NOW+' — V4 literal named-live M3 repair and narrow residual propagation verified; private actual12371/12372 exit0,22checks, three real other-parent chmod counterexamples show M4 identity gap. ROOT all-A48 plan acknowledged, one explicit parent predicate required. Strongest result: repairable operational SOURCE rejection. Source review100%; actual recovery0%; discovery0%. Prior rejected/source/capture families intact; no proposed production/native/Git/remote/ROOT action.\n')
for n in ['closure_common.py','close_adverse_family.py','verify_closed_adverse_family.py']:
    s=raw(OLD/n).decode().replace('corrective_source_adversary_v3','corrective_source_adversary_v4').replace('pr48-corrective-v3','pr48-corrective-v4').replace('3e53126a491880c8aefc614f1c40a5fb965dfcb4c11678cd085e1394369650f8',SHA)
    if n=='closure_common.py':
        s=s.replace("==len(rows)==172","==len(rows)=="+str(len(rows))).replace("z['directory_names']),0o644)","z['directory_names']),z['full_file_mode'])").replace("==['M3']","==['M4']")
        anchor="    verdict=load(F/'VERDICT.json');"
        insertion="    for z in v['additional_genuine_outer_directories']:\n        p=R/safe(z['path']);need(type(z['full_mode']) is int and z['full_mode']==0o700 and p.is_dir() and not p.is_symlink() and all(not q.is_symlink() for q in p.parents) and stat.S_IMODE(p.stat().st_mode)==0o700,'Each genuine M3 outer full700')\n"
        assert s.count(anchor)==1;s=s.replace(anchor,insertion+anchor)
    put(n,s)
names=sorted(q.relative_to(F).as_posix() for q in F.rglob('*') if q.is_file());ds=sorted(['.']+[q.relative_to(F).as_posix() for q in F.rglob('*') if q.is_dir()]);assert all(not q.is_symlink() and (q.is_file() or q.is_dir()) for q in F.rglob('*'))
assert all(stat.S_IMODE((F/n).stat().st_mode)==0o644 for n in names) and all(stat.S_IMODE((F/d).stat().st_mode)==0o755 for d in ds)
def own(n):return {k:v for k,v in ref(F/n).items() if k!='full_mode'}|{'path':n}
put('READY.json',dict(schema='pr48-corrective-v4-adverse-readiness/v1',utc=NOW,status='READY_FOR_ROOT_ADVERSE_EVIDENCE_READING_AND_CLOSURE_ONLY',source_only=True,production_executed=False,future_acceptance_approved=False,candidate_source_ready_sha256=SHA,candidate_SOURCE_manifest_at_review=None,candidate_closure_required=False,closure_payload_files=sorted(names+['READY.json']),closure_directory_names=ds,fixed_own_files=[own(n) for n in names],ROOT_closer_argv=['/usr/bin/python3','-B',str(F/'close_adverse_family.py'),'--execute','--personally-read-complete-source','--ready-sha256','ACTUAL_READY_SHA'],ROOT_reader_argv=['/usr/bin/python3','-B',str(F/'verify_closed_adverse_family.py'),'--self-manifest-sha256','ACTUAL_CLOSED_SELF_SHA'],own_closer_and_reader_executed=False,no_self_manifest_authored=True,mandatory_findings=['M4'],source_review_completion_percent=100,actual_recovery_percent=0,mathematical_credit=0,qualification='Same independent corrective reviewer; rejected unclosed V4 stays fixed644; freeze adverse evidence only.'))
print(json.dumps(dict(status='READY_REPAIR_REQUIRED_SOURCE_M4',actual_author_pid=os.getpid(),utc=NOW,fixed_rows=len(rows),payload_count=len(names)+1,relative_dirs=len(ds)-1,READY=ref(F/'READY.json'),REPORT=ref(F/'REPORT.md'),VERDICT=ref(F/'VERDICT.json'),common=ref(F/'closure_common.py'),closer=ref(F/'close_adverse_family.py'),reader=ref(F/'verify_closed_adverse_family.py')),indent=2))
