#!/usr/bin/env python3
"""Generate a deterministic CNF encoding of normalized odd-n Turyn sequences.

The Boolean convention is:

    variable = false  <=>  sequence sign = +1
    variable = true   <=>  sequence sign = -1

For n = 2m+1, the four normalized sequences have lengths n+1,n+1,n,n
and the forms in Definition 7(i) of Edmondson--Seberry--Anderson (1994).
Every nonzero aperiodic autocorrelation sum is encoded as an exact
cardinality constraint on the signs of its product terms.

No SAT library is used.  XORs and a bitonic cardinality network are emitted
directly as Tseitin CNF, so the resulting DIMACS file is reproducible with
the Python standard library alone.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
from pathlib import Path
from typing import BinaryIO, TypeAlias


Bit: TypeAlias = bool | int


def negate(bit: Bit) -> Bit:
    if isinstance(bit, bool):
        return not bit
    return -bit


class CNF:
    """Low-memory streaming DIMACS builder."""

    def __init__(self, output: Path) -> None:
        self.output = output
        self.body_path = output.with_suffix(output.suffix + ".body.tmp")
        self.body: BinaryIO = self.body_path.open("wb")
        self.variables = 0
        self.clauses = 0
        self.primary_names: dict[str, int] = {}
        self.xor_cache: dict[tuple[int, int], int] = {}

    def new_variable(self, name: str | None = None) -> int:
        self.variables += 1
        if name is not None:
            if name in self.primary_names:
                raise ValueError(f"duplicate primary name: {name}")
            self.primary_names[name] = self.variables
        return self.variables

    def add_clause(self, literals: list[int] | tuple[int, ...]) -> None:
        # Remove duplicate literals and discard tautologies.  Sorting makes
        # the generated byte stream independent of set/dict iteration order.
        unique = set(literals)
        if any(-literal in unique for literal in unique):
            return
        ordered = sorted(unique, key=lambda literal: (abs(literal), literal < 0))
        line = " ".join(str(literal) for literal in ordered)
        self.body.write(f"{line} 0\n".encode("ascii"))
        self.clauses += 1

    def add_bit_clause(self, bits: list[Bit] | tuple[Bit, ...]) -> None:
        """Add a disjunction of Boolean expressions represented as Bits."""

        literals: list[int] = []
        for bit in bits:
            if bit is True:
                return
            if bit is False:
                continue
            literals.append(bit)
        self.add_clause(literals)

    def assert_bit(self, bit: Bit, value: bool) -> None:
        if isinstance(bit, bool):
            if bit != value:
                self.add_clause(())
            return
        self.add_clause((bit if value else -bit,))

    def xor(self, left: Bit, right: Bit) -> Bit:
        if isinstance(left, bool):
            return negate(right) if left else right
        if isinstance(right, bool):
            return negate(left) if right else left
        if left == right:
            return False
        if left == -right:
            return True

        left_variable = abs(left)
        right_variable = abs(right)
        if left_variable > right_variable:
            left_variable, right_variable = right_variable, left_variable
        key = (left_variable, right_variable)
        output = self.xor_cache.get(key)
        if output is None:
            output = self.new_variable()
            self.xor_cache[key] = output
            # output <=> left_variable XOR right_variable
            self.add_clause((left_variable, right_variable, -output))
            self.add_clause((-left_variable, -right_variable, -output))
            self.add_clause((left_variable, -right_variable, output))
            self.add_clause((-left_variable, right_variable, output))

        complemented = (left < 0) ^ (right < 0)
        return -output if complemented else output

    def disjunction(self, left: Bit, right: Bit) -> Bit:
        if isinstance(left, bool):
            return True if left else right
        if isinstance(right, bool):
            return True if right else left
        if left == right:
            return left
        if left == -right:
            return True
        output = self.new_variable()
        # output <=> left OR right
        self.add_clause((-left, output))
        self.add_clause((-right, output))
        self.add_clause((left, right, -output))
        return output

    def conjunction(self, left: Bit, right: Bit) -> Bit:
        if isinstance(left, bool):
            return right if left else False
        if isinstance(right, bool):
            return left if right else False
        if left == right:
            return left
        if left == -right:
            return False
        output = self.new_variable()
        # output <=> left AND right
        self.add_clause((left, -output))
        self.add_clause((right, -output))
        self.add_clause((-left, -right, output))
        return output

    def comparator(self, left: Bit, right: Bit) -> tuple[Bit, Bit]:
        """Return (min, max) in the Boolean order false < true."""

        return self.conjunction(left, right), self.disjunction(left, right)

    def sort_bits(self, inputs: list[Bit]) -> list[Bit]:
        wires = list(inputs)
        if not wires:
            return []
        network_size = 1 << (len(wires) - 1).bit_length()
        wires.extend([False] * (network_size - len(wires)))

        # Batcher bitonic sorting network, ascending (false before true).
        width = 2
        while width <= network_size:
            stride = width // 2
            while stride:
                for index in range(network_size):
                    partner = index ^ stride
                    if partner <= index:
                        continue
                    low, high = self.comparator(wires[index], wires[partner])
                    if (index & width) == 0:
                        wires[index], wires[partner] = low, high
                    else:
                        wires[index], wires[partner] = high, low
                stride //= 2
            width *= 2
        return wires

    def exactly(self, inputs: list[Bit], target: int) -> None:
        fixed_true = sum(bit is True for bit in inputs)
        wires = [bit for bit in inputs if not isinstance(bit, bool)]
        target -= fixed_true
        if target < 0 or target > len(wires):
            self.add_clause(())
            return
        if not wires:
            if target:
                self.add_clause(())
            return
        sorted_wires = self.sort_bits(wires)
        network_size = len(sorted_wires)
        split = network_size - target
        for index, wire in enumerate(sorted_wires):
            self.assert_bit(wire, index >= split)

    def cardinality_in(self, inputs: list[Bit], allowed: set[int]) -> None:
        """Constrain the number of true inputs to belong to ``allowed``."""

        fixed_true = sum(bit is True for bit in inputs)
        wires = [bit for bit in inputs if not isinstance(bit, bool)]
        shifted = {
            count - fixed_true
            for count in allowed
            if fixed_true <= count <= fixed_true + len(wires)
        }
        if not shifted:
            self.add_clause(())
            return
        if not wires:
            return

        sorted_wires = self.sort_bits(wires)
        network_size = len(sorted_wires)
        for count in range(len(wires) + 1):
            if count in shifted:
                continue
            if count == 0:
                # Exact count zero has the last output false.
                self.assert_bit(sorted_wires[-1], True)
            else:
                # Exact count k has ... false,true ... at this boundary.
                boundary = network_size - count
                before = sorted_wires[boundary - 1]
                after = sorted_wires[boundary]
                self.add_bit_clause((before, negate(after)))

    def finish(
        self,
        metadata_path: Path,
        *,
        n: int,
        lag_term_counts: list[int],
        row_sums: bool,
    ) -> None:
        self.body.close()
        self.output.parent.mkdir(parents=True, exist_ok=True)
        with self.output.open("wb") as destination:
            destination.write(f"p cnf {self.variables} {self.clauses}\n".encode("ascii"))
            with self.body_path.open("rb") as source:
                while block := source.read(1 << 20):
                    destination.write(block)
        self.body_path.unlink()

        digest = hashlib.sha256()
        with self.output.open("rb") as source:
            while block := source.read(1 << 20):
                digest.update(block)
        metadata = {
            "schema": "tu-normalized-odd-cnf-v1",
            "n_short": n,
            "long_length": n + 1,
            "primary_variables": self.primary_names,
            "primary_variable_count": len(self.primary_names),
            "cnf_variables": self.variables,
            "cnf_clauses": self.clauses,
            "lag_term_counts": lag_term_counts,
            "row_sum_consequence": row_sums,
            "cnf_file": self.output.name,
            "cnf_sha256": digest.hexdigest(),
        }
        metadata_path.write_text(
            json.dumps(metadata, indent=2, sort_keys=True) + "\n",
            encoding="utf-8",
        )


def normalized_odd_sequences(cnf: CNF, n: int) -> tuple[list[Bit], ...]:
    if n < 3 or n % 2 == 0:
        raise ValueError("this generator requires an odd n >= 3")
    m = (n - 1) // 2
    a = [cnf.new_variable(f"a{index}") for index in range(2, m + 1)]
    b = [cnf.new_variable(f"b{index}") for index in range(2, m + 1)]
    c = [cnf.new_variable(f"c{index}") for index in range(1, m + 1)]
    d = [cnf.new_variable(f"d{index}") for index in range(1, m + 1)]

    sequence_a: list[Bit] = [
        False,
        False,
        *a,
        *(negate(bit) for bit in reversed(a)),
        True,
        True,
    ]
    sequence_b: list[Bit] = [
        False,
        False,
        *b,
        *(negate(bit) for bit in reversed(b)),
        True,
        False,
    ]
    sequence_c: list[Bit] = [
        False,
        *c,
        *reversed(c[:-1]),
        False,
    ]
    sequence_d: list[Bit] = [
        False,
        *d,
        *reversed(d[:-1]),
        False,
    ]
    expected_lengths = (n + 1, n + 1, n, n)
    actual_lengths = tuple(
        len(sequence)
        for sequence in (sequence_a, sequence_b, sequence_c, sequence_d)
    )
    if actual_lengths != expected_lengths:
        raise AssertionError((actual_lengths, expected_lengths))
    return sequence_a, sequence_b, sequence_c, sequence_d


def encode(n: int, output: Path, metadata: Path, *, row_sums: bool = True) -> None:
    output.parent.mkdir(parents=True, exist_ok=True)
    cnf = CNF(output)
    sequences = normalized_odd_sequences(cnf, n)
    lag_term_counts: list[int] = []
    for lag in range(1, n + 1):
        product_signs: list[Bit] = []
        for sequence in sequences:
            for index in range(max(0, len(sequence) - lag)):
                product_signs.append(cnf.xor(sequence[index], sequence[index + lag]))
        if len(product_signs) % 2:
            raise AssertionError(f"odd term count at lag {lag}")
        lag_term_counts.append(len(product_signs))
        cnf.exactly(product_signs, len(product_signs) // 2)
    if row_sums:
        # Evaluating the complementary identity at z=1 gives
        #
        #   sum(A)^2 + sum(B)^2 + sum(C)^2 + sum(D)^2 = 4n+2.
        #
        # For the odd-n normalized forms sum(A)=0 and sum(B)=2.  At n=41,
        # the only possibility is |sum(C)|=|sum(D)|=9, hence each short
        # sequence has either 16 or 25 negative entries.
        if n != 41:
            raise ValueError("the implemented row-sum specialization is for n=41")
        for short_sequence in sequences[2:]:
            cnf.cardinality_in(short_sequence, {16, 25})
    cnf.finish(metadata, n=n, lag_term_counts=lag_term_counts, row_sums=row_sums)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--n", type=int, default=41, help="short length (odd)")
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--metadata", type=Path)
    parser.add_argument(
        "--no-row-sums",
        action="store_true",
        help="omit the n=41 row-sum consequence (used for small regressions)",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    output = args.output.resolve()
    metadata = (
        args.metadata.resolve()
        if args.metadata is not None
        else output.with_suffix(output.suffix + ".json")
    )
    try:
        encode(args.n, output, metadata, row_sums=not args.no_row_sums)
    except BaseException:
        body_path = output.with_suffix(output.suffix + ".body.tmp")
        if body_path.exists():
            os.unlink(body_path)
        raise
    print(metadata.read_text(encoding="utf-8"), end="")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
