# PR108 priority adjudication

The exact all-root hardness resolution is supported as a substantive new contribution relative to the primary literature inspected. The completed dated audit located no covering prior theorem or valid exact transfer. The decision is to prepare an attributed resolution note, followed by fresh whole-package review. It is not a publication-package certificate or an absolute historical first claim.

Three independently frozen mechanism families examined exact-question history, the classical Martin integer lift, and classical tree/routing/compatible-network hardness. A fourth fresh adversary independently assessed the combined evidence and relevant primary sources. Root read the complete final reports and verdicts and authenticated their final artifacts. The candidate proof resolves the literal finite all-root/full-orientation objective; the classical formulation itself is not claimed as new. Projected integrality, routing/path objectives, predecessor pairs, colored arborescences and optional-terminal common-root Steiner objects do not give a checked covering result merely by related terminology.

F01 was a real defect in the classical V1 literature comparison: dropping flow charges can leave optional-terminal Steiner support. Corrected V2 withdraws that assertion and confines the minimum spanning-arborescence conclusion to the stated mandatory-support setting. Root independently read the complete exact primary section4.3.2 and the entire corrected report; the fresh adjudication adversary checked V2 and preserved V1. No covering theorem follows from this repair. All current statements must use corrected V2.

The remaining unavailable original Martin, Hu and SEA texts and imperfect indexing are recorded historical limits, not an identified essential covering theorem. No claim is made that those full proofs were inspected. A dated statement that no earlier proof was located is supported; an assertion of absolute first discovery or continuing open status in2026 is not. A concrete prior exact theorem or valid parameter-preserving objective transfer will reopen the disposition. B=2, transpose and positive shift cannot rescue independent novelty if such a covering antecedent is later found.

The publication package must present the exact problem and self-contained proof, credit Kaibel and the classical formulation, preserve original effort2/5 with no original structured ledger, avoid unsupported extensions and the false global optimum identity, and disclose extensive AI assistance and lack of conventional human refereeing. No extra central proof-search turn was used. Whole-package review rounds, publication, tracker update and native integration remain undone.

2026-10-06T05:39:13.202700+00:00 — mathematical100%, priority audit100%, PR108workflow50%; program16/99=16.16%.
