#!/usr/bin/env python3
"""Render one self-contained workflow; it does not require a remote Lean project."""
from pathlib import Path

ROOT=Path(__file__).resolve().parent
UPLOAD='actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02'

def main():
    lines=['# Generated by environment/make_workflow.py; the embedded scripts are also shipped separately.',
      '# Only prepares the exact compiler/dependencies. It does NOT claim to prove the paper.',
      '# Put this one file at .github/workflows/bell-lean-offline.yml in AlecKriebel/Math.',
      'name: Bell Lean 4.19 offline environment',
      '', 'on:', '  workflow_dispatch:', '  push:', '    paths:',
      '      - .github/workflows/bell-lean-offline.yml', '',
      'permissions:', '  contents: read', '', 'concurrency:',
      '  group: bell-lean-offline-${{ github.ref }}', '  cancel-in-progress: false', '',
      'jobs:', '  export:', '    runs-on: ubuntu-22.04', '    timeout-minutes: 120',
      '    env:', '      BELL_EXPORT_REPOSITORY: ${{ github.repository }}',
      '      BELL_EXPORT_COMMIT: ${{ github.sha }}',
      '      BELL_EXPORT_RUN_ID: ${{ github.run_id }}',
      '    steps:', '      - name: Materialize the embedded exact pins and bootstrap scripts',
      '        shell: bash', '        run: |', '          set -euo pipefail']
    for name in ('export_environment.py','restore_environment.py','pins.json'):
        delimiter='BELL_EOF_'+name.replace('.','_').upper()
        source=(ROOT/name).read_text()
        assert delimiter not in source.splitlines()
        lines.append(f"          cat > {name} <<'{delimiter}'")
        lines.extend('          '+s for s in source.splitlines())
        lines.append('          '+delimiter)
    lines += [
      '      - name: Install the release decompressor',
      '        run: |', '          sudo apt-get update',
      '          sudo apt-get install -y zstd',
      '      - name: Prepare and test the pinned Linux toolchain and Mathlib dependencies',
      '        shell: bash', '        run: |', '          set -euo pipefail',
      '          python3 export_environment.py \\',
      '            --work "$RUNNER_TEMP/bell-lean419-export-${{ github.run_id }}-${{ github.run_attempt }}" \\',
      '            --output "$GITHUB_WORKSPACE/offline-export" \\',
      '            --pins "$GITHUB_WORKSPACE/pins.json" \\',
      '            --restore "$GITHUB_WORKSPACE/restore_environment.py"',
      '      - name: Upload the manifest, restore helper, and smoke-test receipts',
      '        uses: '+UPLOAD, '        with:',
      '          name: bell-lean419-manifest', '          path: |',
      '            offline-export/environment-manifest.json',
      '            offline-export/PARTS.sha256',
      '            offline-export/restore_environment.py',
      '            offline-export/receipts/',
      '          if-no-files-found: error', '          retention-days: 30',
    ]
    for i in range(12):
        lines += [f'      - name: Upload compiler/cache part {i:02d}',
          '        uses: '+UPLOAD, '        with:',
          f'          name: bell-lean419-part{i:02d}',
          f'          path: offline-export/bell-lean419-linux-x64.tar.gz.part-{i:02d}',
          '          compression-level: 0', '          if-no-files-found: ignore',
          '          retention-days: 30']
    lines += ['      - name: Retain bootstrap diagnostics even on failure',
      '        if: always()', '        uses: '+UPLOAD, '        with:',
      '          name: bell-lean419-bootstrap-logs', '          path: |',
      '            offline-export/logs/', '            offline-export/export-failure.json',
      '          if-no-files-found: ignore', '          retention-days: 30',
      '      - name: State the verification boundary in the run summary',
      '        if: success()', '        run: |',
      '          echo "Prepared Lean/Mathlib only. No Bell-paper theorem was verified by this exporter." >> "$GITHUB_STEP_SUMMARY"',
      '          echo "Keep the manifest artifact and every numbered part artifact together." >> "$GITHUB_STEP_SUMMARY"']
    (ROOT/'bell-lean-offline.yml').write_text('\n'.join(lines)+'\n')
    print(ROOT/'bell-lean-offline.yml')

if __name__=='__main__': main()
