#!/usr/bin/env python3
"""Exact circuit projection for fixed-species mass-action networks.

This implementation is independent of the inherited package.  It enumerates
support-minimal nonnegative dependencies of the stoichiometric columns, maps
them to Jacobian-factor generators, and provides an exact cone decomposition
used by the red-team tests.
"""
from __future__ import annotations

import itertools
import math
from dataclasses import dataclass
from functools import reduce
from typing import Iterable, Sequence

import sympy as sp


@dataclass(frozen=True)
class CircuitRay:
    support: tuple[int, ...]
    vector: tuple[int, ...]

    def as_matrix(self) -> sp.Matrix:
        return sp.Matrix(self.vector)


@dataclass(frozen=True)
class ProjectedCone:
    gamma: sp.Matrix
    source: sp.Matrix
    rays: tuple[CircuitRay, ...]
    generators: tuple[tuple[sp.Rational, ...], ...]
    span_rank: int


def _integer_primitive(values: Sequence[sp.Expr]) -> tuple[int, ...]:
    rationals = [sp.Rational(v) for v in values]
    denominators = [int(v.q) for v in rationals]
    common = 1
    for d in denominators:
        common = math.lcm(common, d)
    integers = [int(v * common) for v in rationals]
    common_gcd = reduce(math.gcd, (abs(x) for x in integers if x), 0)
    if common_gcd == 0:
        raise ValueError("zero vector cannot define a ray")
    integers = [x // common_gcd for x in integers]
    first = next(x for x in integers if x)
    if first < 0:
        integers = [-x for x in integers]
    return tuple(integers)


def _positive_kernel_generator(matrix: sp.Matrix) -> tuple[int, ...] | None:
    """Return the primitive all-positive generator when ker(matrix) is 1D."""
    basis = matrix.nullspace()
    if len(basis) != 1:
        return None
    primitive = _integer_primitive(list(basis[0]))
    if all(x > 0 for x in primitive):
        return primitive
    if all(x < 0 for x in primitive):
        return tuple(-x for x in primitive)
    return None


def enumerate_circuit_rays(gamma: sp.Matrix) -> tuple[CircuitRay, ...]:
    """Enumerate all extreme rays of {v>=0: gamma*v=0} exactly.

    For a cone cut out by a homogeneous matrix inside the nonnegative orthant,
    an extreme ray has support S with rank(gamma_S)=|S|-1 and a one-dimensional
    kernel generated by a vector strictly positive on S.  Its support has size
    at most rank(gamma)+1.
    """
    gamma = sp.Matrix(gamma)
    n, m = gamma.shape
    max_support = min(m, gamma.rank() + 1)
    rays: dict[tuple[int, ...], CircuitRay] = {}
    for size in range(1, max_support + 1):
        for support in itertools.combinations(range(m), size):
            sub = gamma[:, support]
            if sub.rank() != size - 1:
                continue
            positive = _positive_kernel_generator(sub)
            if positive is None:
                continue
            full = [0] * m
            for index, value in zip(support, positive):
                full[index] = value
            vector = tuple(full)
            # A positive dependency on a support of nullity one is automatically
            # support-minimal; no proper subset can have a nonzero dependency.
            rays[vector] = CircuitRay(tuple(support), vector)
    return tuple(sorted(rays.values(), key=lambda r: (len(r.support), r.support, r.vector)))


def enumerate_circuit_rays_by_cofactors(gamma: sp.Matrix) -> tuple[CircuitRay, ...]:
    """Independent cofactor implementation used as a cross-check.

    It never calls ``Matrix.nullspace``.  For each candidate support, it selects
    independent rows, computes the signed maximal minors, and tests positivity.
    """
    gamma = sp.Matrix(gamma)
    n, m = gamma.shape
    max_support = min(m, gamma.rank() + 1)
    rays: dict[tuple[int, ...], CircuitRay] = {}
    for size in range(1, max_support + 1):
        for support in itertools.combinations(range(m), size):
            sub = gamma[:, support]
            if sub.rank() != size - 1:
                continue
            if size == 1:
                local = (1,)
            else:
                selected_rows = None
                for rows in itertools.combinations(range(n), size - 1):
                    row_sub = sub[list(rows), :]
                    if row_sub.rank() == size - 1:
                        selected_rows = row_sub
                        break
                if selected_rows is None:
                    continue
                cofactors = []
                for col in range(size):
                    minor = selected_rows[:, [j for j in range(size) if j != col]]
                    cofactors.append((-1) ** col * int(minor.det()))
                local = _integer_primitive(cofactors)
            if not (all(x > 0 for x in local) or all(x < 0 for x in local)):
                continue
            if all(x < 0 for x in local):
                local = tuple(-x for x in local)
            full = [0] * m
            for index, value in zip(support, local):
                full[index] = value
            vector = tuple(full)
            if gamma * sp.Matrix(vector) != sp.zeros(n, 1):
                raise AssertionError("cofactor vector failed the kernel check")
            rays[vector] = CircuitRay(tuple(support), vector)
    return tuple(sorted(rays.values(), key=lambda r: (len(r.support), r.support, r.vector)))


def jacobian_factor(gamma: sp.Matrix, source: sp.Matrix, flux: Sequence[sp.Expr]) -> sp.Matrix:
    gamma = sp.Matrix(gamma)
    source = sp.Matrix(source)
    if gamma.shape != source.shape:
        raise ValueError("gamma and source matrices must have equal shape")
    if len(flux) != gamma.cols:
        raise ValueError("flux dimension mismatch")
    return sp.simplify(gamma * sp.diag(*map(sp.Rational, flux)) * source.T)


def _flatten(matrix: sp.Matrix) -> tuple[sp.Rational, ...]:
    return tuple(sp.Rational(matrix[i, j]) for i in range(matrix.rows) for j in range(matrix.cols))


def project_flux_cone(gamma: sp.Matrix, source: sp.Matrix) -> ProjectedCone:
    gamma = sp.Matrix(gamma)
    source = sp.Matrix(source)
    if gamma.shape != source.shape:
        raise ValueError("gamma and source matrices must have equal shape")
    rays = enumerate_circuit_rays(gamma)
    generators = tuple(_flatten(jacobian_factor(gamma, source, ray.vector)) for ray in rays)
    nonzero = [sp.Matrix(g) for g in generators if any(x != 0 for x in g)]
    span_rank = sp.Matrix.hstack(*nonzero).rank() if nonzero else 0
    return ProjectedCone(gamma, source, rays, generators, span_rank)


def strictly_positive_flux_exists(rays: Sequence[CircuitRay], reaction_count: int) -> bool:
    if reaction_count == 0:
        return False
    covered = [False] * reaction_count
    for ray in rays:
        for index in ray.support:
            covered[index] = True
    return all(covered)


def canonical_positive_flux(rays: Sequence[CircuitRay], reaction_count: int) -> tuple[int, ...] | None:
    if not strictly_positive_flux_exists(rays, reaction_count):
        return None
    total = [0] * reaction_count
    for ray in rays:
        for i, value in enumerate(ray.vector):
            total[i] += value
    if not all(value > 0 for value in total):
        raise AssertionError("covered rays did not produce a positive flux")
    return tuple(total)


def decompose_flux(flux: Sequence[sp.Expr], rays: Sequence[CircuitRay], gamma: sp.Matrix) -> tuple[tuple[sp.Rational, CircuitRay], ...]:
    """Decompose a nonnegative kernel vector into circuit rays exactly.

    The proof is constructive: at each step choose a ray contained in the
    current support and subtract the largest nonnegative multiple.  At least
    one coordinate disappears, so at most ``m`` steps are needed.
    """
    gamma = sp.Matrix(gamma)
    residual = [sp.Rational(x) for x in flux]
    if len(residual) != gamma.cols or any(x < 0 for x in residual):
        raise ValueError("flux must be a nonnegative vector of the correct size")
    if gamma * sp.Matrix(residual) != sp.zeros(gamma.rows, 1):
        raise ValueError("flux is not in the stoichiometric kernel")
    pieces: list[tuple[sp.Rational, CircuitRay]] = []
    while any(x > 0 for x in residual):
        support = {i for i, x in enumerate(residual) if x > 0}
        candidates = [ray for ray in rays if set(ray.support).issubset(support)]
        if not candidates:
            raise AssertionError("enumerated circuits do not generate the kernel cone")
        ray = min(candidates, key=lambda r: (len(r.support), r.support))
        coefficient = min(residual[i] / sp.Rational(ray.vector[i]) for i in ray.support)
        if coefficient <= 0:
            raise AssertionError("nonpositive decomposition coefficient")
        residual = [sp.simplify(x - coefficient * ray.vector[i]) for i, x in enumerate(residual)]
        if any(x < 0 for x in residual):
            raise AssertionError("circuit subtraction left the nonnegative cone")
        pieces.append((coefficient, ray))
    return tuple(pieces)


def reconstruct_from_decomposition(pieces: Sequence[tuple[sp.Expr, CircuitRay]], reaction_count: int) -> sp.Matrix:
    vector = sp.zeros(reaction_count, 1)
    for coefficient, ray in pieces:
        vector += sp.Rational(coefficient) * ray.as_matrix()
    return sp.simplify(vector)


def projected_formula_summary(gamma: sp.Matrix, source: sp.Matrix) -> dict[str, int | bool]:
    cone = project_flux_cone(gamma, source)
    return {
        "species": gamma.rows,
        "reactions": gamma.cols,
        "stoichiometric_rank": gamma.rank(),
        "circuit_rays": len(cone.rays),
        "projected_span_dimension": cone.span_rank,
        "strict_positive_flux": strictly_positive_flux_exists(cone.rays, gamma.cols),
    }
