/- Generated inspection commands; not a proof. -/
import Kourovka

#print axioms Kourovka.Ambient.I
#print axioms Kourovka.Ambient.V
#print axioms Kourovka.Ambient.B
#print axioms Kourovka.Ambient.B_apply
#print axioms Kourovka.Ambient.alternating
#print axioms Kourovka.Ambient.skew
#print axioms Kourovka.Ambient.mapVec
#print axioms Kourovka.Ambient.mapVec_unit
#print axioms Kourovka.Ambient.mapVec_add
#print axioms Kourovka.Ambient.mapVec_sub
#print axioms Kourovka.Ambient.mapVec_zero
#print axioms Kourovka.Ambient.mapVec_smul
#print axioms Kourovka.Ambient.mapVec_terms
#print axioms Kourovka.Ambient.mapVec_B
#print axioms Kourovka.Ambient.IntData.Checks.term_0
#print axioms Kourovka.Ambient.IntData.Checks.jacobi_0
#print axioms Kourovka.Ambient.IntData.Checks.term_1
#print axioms Kourovka.Ambient.IntData.Checks.jacobi_1
#print axioms Kourovka.Ambient.IntData.Checks.term_2
#print axioms Kourovka.Ambient.IntData.Checks.jacobi_2
#print axioms Kourovka.Ambient.IntData.Checks.term_3
#print axioms Kourovka.Ambient.IntData.Checks.jacobi_3
#print axioms Kourovka.Ambient.IntData.Checks.term_4
#print axioms Kourovka.Ambient.IntData.Checks.jacobi_4
#print axioms Kourovka.Ambient.IntData.Checks.term_5
#print axioms Kourovka.Ambient.IntData.Checks.jacobi_5
#print axioms Kourovka.Ambient.IntData.Checks.term_6
#print axioms Kourovka.Ambient.IntData.Checks.jacobi_6
#print axioms Kourovka.Ambient.IntData.Checks.term_7
#print axioms Kourovka.Ambient.IntData.Checks.jacobi_7
#print axioms Kourovka.Ambient.IntData.Checks.term_8
#print axioms Kourovka.Ambient.IntData.Checks.jacobi_8
#print axioms Kourovka.Ambient.IntData.Checks.term_9
#print axioms Kourovka.Ambient.IntData.Checks.jacobi_9
#print axioms Kourovka.Ambient.IntData.Checks.term_10
#print axioms Kourovka.Ambient.IntData.Checks.jacobi_10
#print axioms Kourovka.Ambient.IntData.Checks.term_11
#print axioms Kourovka.Ambient.IntData.Checks.jacobi_11
#print axioms Kourovka.Ambient.IntData.Checks.term_12
#print axioms Kourovka.Ambient.IntData.Checks.jacobi_12
#print axioms Kourovka.Ambient.IntData.Checks.term_13
#print axioms Kourovka.Ambient.IntData.Checks.jacobi_13
#print axioms Kourovka.Ambient.IntData.Checks.term_14
#print axioms Kourovka.Ambient.IntData.Checks.jacobi_14
#print axioms Kourovka.Ambient.IntData.Checks.term_15
#print axioms Kourovka.Ambient.IntData.Checks.jacobi_15
#print axioms Kourovka.Ambient.IntData.Checks.term_16
#print axioms Kourovka.Ambient.IntData.Checks.jacobi_16
#print axioms Kourovka.Ambient.IntData.Checks.term_17
#print axioms Kourovka.Ambient.IntData.Checks.jacobi_17
#print axioms Kourovka.Ambient.IntData.Checks.term_18
#print axioms Kourovka.Ambient.IntData.Checks.jacobi_18
#print axioms Kourovka.Ambient.IntData.Checks.term_19
#print axioms Kourovka.Ambient.IntData.Checks.jacobi_19
#print axioms Kourovka.Ambient.IntData.Checks.term_20
#print axioms Kourovka.Ambient.IntData.Checks.jacobi_20
#print axioms Kourovka.Ambient.IntData.Checks.term_21
#print axioms Kourovka.Ambient.IntData.Checks.jacobi_21
#print axioms Kourovka.Ambient.IntData.Checks.term_22
#print axioms Kourovka.Ambient.IntData.Checks.jacobi_22
#print axioms Kourovka.Ambient.IntData.Checks.term_23
#print axioms Kourovka.Ambient.IntData.Checks.jacobi_23
#print axioms Kourovka.Ambient.IntData.Checks.term_24
#print axioms Kourovka.Ambient.IntData.Checks.jacobi_24
#print axioms Kourovka.Ambient.IntData.Checks.term_25
#print axioms Kourovka.Ambient.IntData.Checks.jacobi_25
#print axioms Kourovka.Ambient.IntData.Checks.term_26
#print axioms Kourovka.Ambient.IntData.Checks.jacobi_26
#print axioms Kourovka.Ambient.IntData.Checks.term_27
#print axioms Kourovka.Ambient.IntData.Checks.jacobi_27
#print axioms Kourovka.Ambient.IntData.Checks.term_28
#print axioms Kourovka.Ambient.IntData.Checks.jacobi_28
#print axioms Kourovka.Ambient.IntData.Checks.term_29
#print axioms Kourovka.Ambient.IntData.Checks.jacobi_29
#print axioms Kourovka.Ambient.IntData.Checks.term_30
#print axioms Kourovka.Ambient.IntData.Checks.jacobi_30
#print axioms Kourovka.Ambient.FastBasis.entry
#print axioms Kourovka.Ambient.FastBasis.coeff
#print axioms Kourovka.Ambient.FastBasis.coord_unit
#print axioms Kourovka.Ambient.FastBasis.entry_sound
#print axioms Kourovka.Ambient.FastBasis.fromTerms_sound
#print axioms Kourovka.Ambient.FastBasis.bracket_sound
#print axioms Kourovka.Ambient.FastBasis.cast_fromTerms_sound
#print axioms Kourovka.Ambient.FastBasis.termVec_coeff
#print axioms Kourovka.Ambient.FastBasis.termCheck_of_coeff
#print axioms Kourovka.Ambient.IntData.term
#print axioms Kourovka.Ambient.IntData.termVec
#print axioms Kourovka.Ambient.IntData.coeff
#print axioms Kourovka.Ambient.IntData.nestedLeft
#print axioms Kourovka.Ambient.IntData.nestedRight
#print axioms Kourovka.Ambient.IntData.JacobiCheck
#print axioms Kourovka.Ambient.IntData.TermCheck
#print axioms Kourovka.Ambient.termCheck_all
#print axioms Kourovka.Ambient.jacobiCheck_all
#print axioms Kourovka.Ambient.mapVec_termVec
#print axioms Kourovka.Ambient.basis_bracket
#print axioms Kourovka.Ambient.termVec_coord
#print axioms Kourovka.Ambient.basis_coeff
#print axioms Kourovka.Ambient.nestedLeft_sound
#print axioms Kourovka.Ambient.nestedRight_sound
#print axioms Kourovka.Ambient.jacobi_basis_integer
#print axioms Kourovka.Ambient.jacobi_basis
#print axioms Kourovka.Ambient.leibniz
#print axioms Kourovka.Ambient.lieRing
#print axioms Kourovka.Ambient.lieAlgebra
#print axioms Kourovka.Analytic.geometric
#print axioms Kourovka.Analytic.one_sub_mul_geometric
#print axioms Kourovka.Analytic.geometric_mul_one_sub
#print axioms Kourovka.Analytic.oneSubUnit
#print axioms Kourovka.Analytic.oneAddUnit
#print axioms Kourovka.Analytic.oneAddUnit_val
#print axioms Kourovka.Analytic.evalHorner
#print axioms Kourovka.Analytic.commute_evalHorner
#print axioms Kourovka.Analytic.polynomialUnit
#print axioms Kourovka.Analytic.polynomialUnit_val
#print axioms Kourovka.Analytic.unitToEquiv
#print axioms Kourovka.Analytic.factor_zero_iff
#print axioms Kourovka.Analytic.factor_mem_iff
#print axioms Kourovka.Analytic.Tensor.T
#print axioms Kourovka.Analytic.Tensor.output
#print axioms Kourovka.Analytic.Tensor.inputLeft
#print axioms Kourovka.Analytic.Tensor.inputRight
#print axioms Kourovka.Analytic.Tensor.output_apply
#print axioms Kourovka.Analytic.Tensor.inputLeft_apply
#print axioms Kourovka.Analytic.Tensor.inputRight_apply
#print axioms Kourovka.Analytic.Tensor.output_inputLeft_commute
#print axioms Kourovka.Analytic.Tensor.output_inputRight_commute
#print axioms Kourovka.Analytic.Tensor.inputs_commute
#print axioms Kourovka.Analytic.Tensor.differential
#print axioms Kourovka.Analytic.Tensor.differential_apply
#print axioms Kourovka.Analytic.Tensor.action
#print axioms Kourovka.Analytic.Tensor.action_apply
#print axioms Kourovka.Analytic.Tensor.action_fixed_iff
#print axioms Kourovka.Analytic.Tensor.fixed_iff_derivation_of_factor
#print axioms Kourovka.BCH.Poly.coeff
#print axioms Kourovka.BCH.Poly.support
#print axioms Kourovka.BCH.Poly.coeff_nil
#print axioms Kourovka.BCH.Poly.coeff_cons
#print axioms Kourovka.BCH.Poly.coeff_append
#print axioms Kourovka.BCH.Poly.coeff_neg
#print axioms Kourovka.BCH.Poly.mem_support
#print axioms Kourovka.BCH.Poly.coeff_eq_zero_of_not_mem
#print axioms Kourovka.BCH.Poly.sumEval_eq_sum
#print axioms Kourovka.BCH.Poly.sumEval_eq_of_coeff_eq
#print axioms Kourovka.BCH.Poly.ZeroCoefficients
#print axioms Kourovka.BCH.Poly.zeroCoefficients_sound
#print axioms Kourovka.BCH.LiePoly
#print axioms Kourovka.BCH.LiePoly.eval
#print axioms Kourovka.BCH.LiePoly.expand
#print axioms Kourovka.BCH.LiePoly.Homogeneous
#print axioms Kourovka.BCH.LiePoly.dynkin_expand
#print axioms Kourovka.BCH.LiePoly.eval_zero_of_coeff_zero
#print axioms Kourovka.BCH.LieWord
#print axioms Kourovka.BCH.LieWord.degree
#print axioms Kourovka.BCH.LieWord.eval
#print axioms Kourovka.BCH.LieWord.degree_pos
#print axioms Kourovka.BCH.Poly
#print axioms Kourovka.BCH.Poly.neg
#print axioms Kourovka.BCH.Poly.shift
#print axioms Kourovka.BCH.Poly.mul
#print axioms Kourovka.BCH.Poly.comm
#print axioms Kourovka.BCH.Poly.sumEval
#print axioms Kourovka.BCH.Poly.sumEval_append
#print axioms Kourovka.BCH.Poly.sumEval_neg
#print axioms Kourovka.BCH.Poly.NonemptyWords
#print axioms Kourovka.BCH.Poly.nonempty_neg
#print axioms Kourovka.BCH.Poly.nonempty_mul
#print axioms Kourovka.BCH.Poly.nonempty_comm
#print axioms Kourovka.BCH.LieWord.expand
#print axioms Kourovka.BCH.LieWord.expansion_nonempty
#print axioms Kourovka.BCH.wordAction
#print axioms Kourovka.BCH.wordAction_zero
#print axioms Kourovka.BCH.wordAction_add
#print axioms Kourovka.BCH.wordAction_zsmul
#print axioms Kourovka.BCH.wordAction_append
#print axioms Kourovka.BCH.dynkinWord
#print axioms Kourovka.BCH.dynkinWord_append
#print axioms Kourovka.BCH.polyAction
#print axioms Kourovka.BCH.dynkin
#print axioms Kourovka.BCH.polyAction_zero
#print axioms Kourovka.BCH.polyAction_add
#print axioms Kourovka.BCH.polyAction_zsmul
#print axioms Kourovka.BCH.action_shift
#print axioms Kourovka.BCH.action_mul
#print axioms Kourovka.BCH.dynkin_shift
#print axioms Kourovka.BCH.dynkin_mul
#print axioms Kourovka.BCH.action_expand
#print axioms Kourovka.BCH.dynkin_expand
#print axioms Kourovka.BCH.eval_eq_of_dynkin_eq
#print axioms Kourovka.Sparse.Term
#print axioms Kourovka.Sparse.Vec
#print axioms Kourovka.Sparse.coord
#print axioms Kourovka.Sparse.coord_add
#print axioms Kourovka.Sparse.coord_smul
#print axioms Kourovka.Sparse.entry
#print axioms Kourovka.Sparse.entry_self
#print axioms Kourovka.Sparse.entry_add_left
#print axioms Kourovka.Sparse.entry_add_right
#print axioms Kourovka.Sparse.entry_smul_left
#print axioms Kourovka.Sparse.entry_smul_right
#print axioms Kourovka.Sparse.fromTerms
#print axioms Kourovka.Sparse.fromTerms_self
#print axioms Kourovka.Sparse.fromTerms_add_left
#print axioms Kourovka.Sparse.fromTerms_add_right
#print axioms Kourovka.Sparse.fromTerms_smul_left
#print axioms Kourovka.Sparse.fromTerms_smul_right
#print axioms Kourovka.Sparse.bracket
#print axioms Kourovka.Certificates.Pair
#print axioms Kourovka.Certificates.Row
#print axioms Kourovka.Certificates.Col
#print axioms Kourovka.Certificates.num_pairs
#print axioms Kourovka.Certificates.num_rows
#print axioms Kourovka.Certificates.num_cols
#print axioms Kourovka.Certificates.derivationMatrix
#print axioms Kourovka.Certificates.coefficient
#print axioms Kourovka.Certificates.matrix_entry
#print axioms Kourovka.Certificates.matrixLinear
#print axioms Kourovka.Certificates.matrix_apply
#print axioms Kourovka.Certificates.bracket_skew
#print axioms Kourovka.Certificates.delta_alternating
#print axioms Kourovka.Certificates.delta_skew
#print axioms Kourovka.Certificates.zero_of_ordered_basis
#print axioms Kourovka.Certificates.DerivationCondition
#print axioms Kourovka.Certificates.derivation_iff_delta_zero
#print axioms Kourovka.Certificates.kernel_iff_derivation
#print axioms Kourovka.Certificates.derivationsEquivKernel
#print axioms Kourovka.Certificates.K
#print axioms Kourovka.Certificates.Kmod
#print axioms Kourovka.Certificates.diagonalMap
#print axioms Kourovka.Certificates.diagonalKernelEquiv
#print axioms Kourovka.Certificates.diagonalKernel_card
#print axioms Kourovka.Certificates.padMap
#print axioms Kourovka.Certificates.paddedKernelEquiv
#print axioms Kourovka.Certificates.diagonalCoefficient
#print axioms Kourovka.Certificates.diagonal_prime_power_card
#print axioms Kourovka.Certificates.Elementary.Coord
#print axioms Kourovka.Certificates.Elementary.permute
#print axioms Kourovka.Certificates.Elementary.shearFun
#print axioms Kourovka.Certificates.Elementary.shear
#print axioms Kourovka.Certificates.Elementary.scale
#print axioms Kourovka.Certificates.Elementary.Op
#print axioms Kourovka.Certificates.Elementary.decode
#print axioms Kourovka.Certificates.Elementary.decodeList
#print axioms Kourovka.Certificates.Elementary.Circuit
#print axioms Kourovka.Certificates.Elementary.decodeCircuit
#print axioms Kourovka.Certificates.Elementary.basisCheck
#print axioms Kourovka.Certificates.Elementary.basisCheck_sound
#print axioms Kourovka.Certificates.Elementary.check
#print axioms Kourovka.Certificates.Elementary.check_sound
#print axioms Kourovka.Certificates.Elementary.check_card
#print axioms Kourovka.Certificates.Elementary.rejects_nonunit
#print axioms Kourovka.Certificates.Elementary.rejects_same_coordinate
#print axioms Kourovka.Certificates.Elementary.accepts_unit
#print axioms Kourovka.Certificates.pairData
#print axioms Kourovka.Certificates.pairData_ordered
#print axioms Kourovka.Certificates.pairAt
#print axioms Kourovka.Certificates.pairNumberNat
#print axioms Kourovka.Certificates.pairNumber_bound
#print axioms Kourovka.Certificates.pairNumber
#print axioms Kourovka.Certificates.number_at
#print axioms Kourovka.Certificates.at_number
#print axioms Kourovka.Certificates.pairEquiv
#print axioms Kourovka.Certificates.colEquiv
#print axioms Kourovka.Certificates.rowEquiv
#print axioms Kourovka.Certificates.Kflat
#print axioms Kourovka.Certificates.Kflat_def
#print axioms Kourovka.Certificates.InnerRank.leftInverse_00
#print axioms Kourovka.Certificates.InnerRank.leftInverse_01
#print axioms Kourovka.Certificates.InnerRank.leftInverse_02
#print axioms Kourovka.Certificates.InnerRank.leftInverse_03
#print axioms Kourovka.Certificates.InnerRank.leftInverse_04
#print axioms Kourovka.Certificates.InnerRank.leftInverse_05
#print axioms Kourovka.Certificates.InnerRank.leftInverse_06
#print axioms Kourovka.Certificates.InnerRank.leftInverse_07
#print axioms Kourovka.Certificates.InnerRank.leftInverse_08
#print axioms Kourovka.Certificates.InnerRank.leftInverse_09
#print axioms Kourovka.Certificates.InnerRank.leftInverse_10
#print axioms Kourovka.Certificates.InnerRank.leftInverse_11
#print axioms Kourovka.Certificates.InnerRank.leftInverse_12
#print axioms Kourovka.Certificates.InnerRank.leftInverse_13
#print axioms Kourovka.Certificates.InnerRank.leftInverse_14
#print axioms Kourovka.Certificates.InnerRank.leftInverse_15
#print axioms Kourovka.Certificates.InnerRank.leftInverse_16
#print axioms Kourovka.Certificates.InnerRank.leftInverse_17
#print axioms Kourovka.Certificates.InnerRank.leftInverse_18
#print axioms Kourovka.Certificates.InnerRank.leftInverse_19
#print axioms Kourovka.Certificates.InnerRank.leftInverse_20
#print axioms Kourovka.Certificates.InnerRank.leftInverse_21
#print axioms Kourovka.Certificates.InnerRank.leftInverse_22
#print axioms Kourovka.Certificates.InnerRank.leftInverse_23
#print axioms Kourovka.Certificates.InnerRank.leftInverse_24
#print axioms Kourovka.Certificates.InnerRank.leftInverse_25
#print axioms Kourovka.Certificates.InnerRank.leftInverse_26
#print axioms Kourovka.Certificates.InnerRank.leftInverse_27
#print axioms Kourovka.Certificates.InnerRank.leftInverse_28
#print axioms Kourovka.Certificates.InnerRank.leftInverse_29
#print axioms Kourovka.Certificates.InnerRank.innerColumn_derivation
#print axioms Kourovka.Certificates.InnerRank.innerMap_derivation
#print axioms Kourovka.Certificates.InnerRank.innerKernelMap
#print axioms Kourovka.Certificates.InnerRank.innerKernelMap_injective
#print axioms Kourovka.Certificates.InnerRank.kernel_finrank_lower
#print axioms Kourovka.Certificates.InnerRank.rational_rank_upper
#print axioms Kourovka.Certificates.InnerRank.extendedInnerKernel
#print axioms Kourovka.Certificates.InnerRank.extendedInnerKernel_injective
#print axioms Kourovka.Certificates.InnerRank.characteristic_zero_kernel_finrank_lower
#print axioms Kourovka.Certificates.InnerRank.characteristic_zero_rank_upper
#print axioms Kourovka.Certificates.InnerRank.inner_entry_cast
#print axioms Kourovka.Certificates.InnerRank.extendedInverse
#print axioms Kourovka.Certificates.InnerRank.extended_left_inverse
#print axioms Kourovka.Certificates.InnerRank.extendedExtractor
#print axioms Kourovka.Certificates.InnerRank.extendedExtractor_innerMap
#print axioms Kourovka.Certificates.InnerRank.extended_inner_injective
#print axioms Kourovka.Certificates.InnerRank.leftInverse_all
#print axioms Kourovka.Certificates.InnerRank.extractor_innerMap
#print axioms Kourovka.Certificates.InnerRank.innerMap_injective
#print axioms Kourovka.Certificates.InnerRank.Param
#print axioms Kourovka.Certificates.InnerRank.selectedRow
#print axioms Kourovka.Certificates.InnerRank.inverseCoeff
#print axioms Kourovka.Certificates.InnerRank.innerColumn
#print axioms Kourovka.Certificates.InnerRank.inner_entry_fast
#print axioms Kourovka.Certificates.InnerRank.innerMap
#print axioms Kourovka.Certificates.InnerRank.innerMap_unit
#print axioms Kourovka.Certificates.InnerRank.extractor
#print axioms Kourovka.Certificates.InnerRank.LeftInverseCheck
#print axioms Kourovka.Certificates.KernelSet
#print axioms Kourovka.Certificates.kernelPostEquiv
#print axioms Kourovka.Certificates.kernelPreEquiv
#print axioms Kourovka.Certificates.kernelTransformEquiv
#print axioms Kourovka.Certificates.kernelTransform_card
#print axioms Kourovka.Certificates.ScalarKernel.Carrier
#print axioms Kourovka.Certificates.ScalarKernel.equivFin
#print axioms Kourovka.Certificates.ScalarKernel.card
#print axioms Kourovka.Certificates.ScalarKernel.prime_power_card
#print axioms Kourovka.Certificates.ScalarKernel.zeroKernelEquiv
#print axioms Kourovka.Challenge.ExactOrders
#print axioms Kourovka.Challenge.NotebookAffirmative
#print axioms Kourovka.exportedTerms
#print axioms Kourovka.Finite.VecAt
#print axioms Kourovka.Finite.additiveToLinear
#print axioms Kourovka.Finite.additiveToLinear_apply
#print axioms Kourovka.Finite.additiveLinearEquiv
#print axioms Kourovka.Finite.additiveEquivToLinear
#print axioms Kourovka.Finite.additiveEquivToLinear_apply
#print axioms Kourovka.Finite.BracketTree
#print axioms Kourovka.Finite.BracketTree.length
#print axioms Kourovka.Finite.BracketTree.eval
#print axioms Kourovka.Finite.BracketTree.map
#print axioms Kourovka.Finite.BracketTree.length_map
#print axioms Kourovka.Finite.BracketTree.length_pos
#print axioms Kourovka.Finite.BracketTree.eval_map
#print axioms Kourovka.Finite.BracketTree.map_map
#print axioms Kourovka.Finite.BracketTree.map_id
#print axioms Kourovka.Finite.primePower_neZero
#print axioms Kourovka.Finite.RAt
#print axioms Kourovka.Finite.LAt
#print axioms Kourovka.Finite.reduce
#print axioms Kourovka.Finite.lift
#print axioms Kourovka.Finite.reduce_lift
#print axioms Kourovka.Finite.reduce_surjective
#print axioms Kourovka.Finite.reduce_bracket
#print axioms Kourovka.Finite.reduce_eq_zero_iff
#print axioms Kourovka.Finite.cardinality
#print axioms Kourovka.Finite.cardinality_at_depth
#print axioms Kourovka.Finite.lieRingAt
#print axioms Kourovka.Finite.lieAlgebraAt
#print axioms Kourovka.Finite.FullAutomorphisms.RingAut
#print axioms Kourovka.Finite.FullAutomorphisms.ScalarAut
#print axioms Kourovka.Finite.FullAutomorphisms.toScalar
#print axioms Kourovka.Finite.FullAutomorphisms.toInteger
#print axioms Kourovka.Finite.FullAutomorphisms.ringAutEquivScalarAut
#print axioms Kourovka.Finite.FullAutomorphisms.AdmissibleEntries
#print axioms Kourovka.Finite.FullAutomorphisms.toEntriesAut
#print axioms Kourovka.Finite.FullAutomorphisms.fromEntriesAut
#print axioms Kourovka.Finite.FullAutomorphisms.scalarAutEquivEntries
#print axioms Kourovka.Finite.FullAutomorphisms.ringAutEquivEntries
#print axioms Kourovka.Finite.FullAutomorphisms.full_lie_aut_card_eq_matrix_card
#print axioms Kourovka.Finite.tree_embed_divisible
#print axioms Kourovka.Finite.integer_tree_divisible
#print axioms Kourovka.Finite.monomial_vanishes
#print axioms Kourovka.Finite.standardB
#print axioms Kourovka.Finite.wordSpan
#print axioms Kourovka.Finite.bracket_mem_wordSpan
#print axioms Kourovka.Finite.lowerCentral_le_wordSpan
#print axioms Kourovka.Finite.lowerCentral_eq_bot_of_words
#print axioms Kourovka.Finite.target_lowerCentralSeries
#print axioms Kourovka.Finite.Padic.O
#print axioms Kourovka.Finite.Padic.Ell
#print axioms Kourovka.Finite.Padic.reduction
#print axioms Kourovka.Finite.Padic.sectionMap
#print axioms Kourovka.Finite.Padic.reduction_section
#print axioms Kourovka.Finite.Padic.reduction_surjective
#print axioms Kourovka.Finite.Padic.reduction_scalar_zero
#print axioms Kourovka.Finite.Padic.reduction_zero_iff
#print axioms Kourovka.Finite.Padic.quotientEquiv
#print axioms Kourovka.Finite.Padic.reduction_bracket
#print axioms Kourovka.Finite.Padic.quotient_coordinate_order
#print axioms Kourovka.Flag.k
#print axioms Kourovka.Flag.primeFact
#print axioms Kourovka.Flag.E
#print axioms Kourovka.Flag.x
#print axioms Kourovka.Flag.e
#print axioms Kourovka.Flag.f
#print axioms Kourovka.Flag.u
#print axioms Kourovka.Flag.v
#print axioms Kourovka.Flag.w
#print axioms Kourovka.Flag.q
#print axioms Kourovka.Flag.r
#print axioms Kourovka.Flag.z
#print axioms Kourovka.Flag.t
#print axioms Kourovka.Flag.y
#print axioms Kourovka.Flag.uv
#print axioms Kourovka.Flag.ad1
#print axioms Kourovka.Flag.ad2
#print axioms Kourovka.Flag.ad3
#print axioms Kourovka.Flag.Preserves
#print axioms Kourovka.Flag.IsDerivation
#print axioms Kourovka.Flag.F2
#print axioms Kourovka.Flag.F3
#print axioms Kourovka.Flag.x_mem_F2
#print axioms Kourovka.Flag.y_mem_F2
#print axioms Kourovka.Flag.t_mem_F3
#print axioms Kourovka.Flag.F2_le_F3
#print axioms Kourovka.Flag.F2_eq_span
#print axioms Kourovka.Flag.F3_eq_span
#print axioms Kourovka.Flag.t_ne_zero
#print axioms Kourovka.Flag.xt
#print axioms Kourovka.Flag.yt
#print axioms Kourovka.Flag.ef
#print axioms Kourovka.Flag.euv
#print axioms Kourovka.Flag.rt
#print axioms Kourovka.Flag.first_bracket
#print axioms Kourovka.Flag.ad1_value
#print axioms Kourovka.Flag.first_derivation
#print axioms Kourovka.Flag.e_projector
#print axioms Kourovka.Flag.f_projector
#print axioms Kourovka.Flag.uv_projector
#print axioms Kourovka.Flag.r_projector
#print axioms Kourovka.Flag.fu0
#print axioms Kourovka.Flag.fu1
#print axioms Kourovka.Flag.fu2
#print axioms Kourovka.Flag.fu3
#print axioms Kourovka.Flag.fu4
#print axioms Kourovka.Flag.fu5
#print axioms Kourovka.Flag.fv0
#print axioms Kourovka.Flag.fv1
#print axioms Kourovka.Flag.fv2
#print axioms Kourovka.Flag.fv3
#print axioms Kourovka.Flag.u2u6
#print axioms Kourovka.Flag.u0w5
#print axioms Kourovka.Flag.u0v4
#print axioms Kourovka.Flag.cancel_smul
#print axioms Kourovka.Flag.map_piece
#print axioms Kourovka.Flag.map_r_piece
#print axioms Kourovka.Flag.image_from_bracket
#print axioms Kourovka.Flag.Generation.n0
#print axioms Kourovka.Flag.Generation.value_0
#print axioms Kourovka.Flag.Generation.fixed_0
#print axioms Kourovka.Flag.Generation.zero_0
#print axioms Kourovka.Flag.Generation.n1
#print axioms Kourovka.Flag.Generation.value_1
#print axioms Kourovka.Flag.Generation.fixed_1
#print axioms Kourovka.Flag.Generation.zero_1
#print axioms Kourovka.Flag.Generation.n2
#print axioms Kourovka.Flag.Generation.value_2
#print axioms Kourovka.Flag.Generation.fixed_2
#print axioms Kourovka.Flag.Generation.zero_2
#print axioms Kourovka.Flag.Generation.n3
#print axioms Kourovka.Flag.Generation.value_3
#print axioms Kourovka.Flag.Generation.fixed_3
#print axioms Kourovka.Flag.Generation.zero_3
#print axioms Kourovka.Flag.Generation.n4
#print axioms Kourovka.Flag.Generation.value_4
#print axioms Kourovka.Flag.Generation.fixed_4
#print axioms Kourovka.Flag.Generation.zero_4
#print axioms Kourovka.Flag.Generation.n5
#print axioms Kourovka.Flag.Generation.value_5
#print axioms Kourovka.Flag.Generation.fixed_5
#print axioms Kourovka.Flag.Generation.zero_5
#print axioms Kourovka.Flag.Generation.n6
#print axioms Kourovka.Flag.Generation.value_6
#print axioms Kourovka.Flag.Generation.fixed_6
#print axioms Kourovka.Flag.Generation.zero_6
#print axioms Kourovka.Flag.Generation.n7
#print axioms Kourovka.Flag.Generation.value_7
#print axioms Kourovka.Flag.Generation.fixed_7
#print axioms Kourovka.Flag.Generation.zero_7
#print axioms Kourovka.Flag.Generation.n8
#print axioms Kourovka.Flag.Generation.value_8
#print axioms Kourovka.Flag.Generation.fixed_8
#print axioms Kourovka.Flag.Generation.zero_8
#print axioms Kourovka.Flag.Generation.n9
#print axioms Kourovka.Flag.Generation.value_9
#print axioms Kourovka.Flag.Generation.fixed_9
#print axioms Kourovka.Flag.Generation.zero_9
#print axioms Kourovka.Flag.Generation.n10
#print axioms Kourovka.Flag.Generation.value_10
#print axioms Kourovka.Flag.Generation.fixed_10
#print axioms Kourovka.Flag.Generation.zero_10
#print axioms Kourovka.Flag.Generation.n11
#print axioms Kourovka.Flag.Generation.value_11
#print axioms Kourovka.Flag.Generation.fixed_11
#print axioms Kourovka.Flag.Generation.zero_11
#print axioms Kourovka.Flag.Generation.n12
#print axioms Kourovka.Flag.Generation.value_12
#print axioms Kourovka.Flag.Generation.fixed_12
#print axioms Kourovka.Flag.Generation.zero_12
#print axioms Kourovka.Flag.Generation.n13
#print axioms Kourovka.Flag.Generation.value_13
#print axioms Kourovka.Flag.Generation.fixed_13
#print axioms Kourovka.Flag.Generation.zero_13
#print axioms Kourovka.Flag.Generation.n14
#print axioms Kourovka.Flag.Generation.value_14
#print axioms Kourovka.Flag.Generation.fixed_14
#print axioms Kourovka.Flag.Generation.zero_14
#print axioms Kourovka.Flag.Generation.n15
#print axioms Kourovka.Flag.Generation.value_15
#print axioms Kourovka.Flag.Generation.fixed_15
#print axioms Kourovka.Flag.Generation.zero_15
#print axioms Kourovka.Flag.Generation.n16
#print axioms Kourovka.Flag.Generation.value_16
#print axioms Kourovka.Flag.Generation.fixed_16
#print axioms Kourovka.Flag.Generation.zero_16
#print axioms Kourovka.Flag.Generation.n17
#print axioms Kourovka.Flag.Generation.value_17
#print axioms Kourovka.Flag.Generation.fixed_17
#print axioms Kourovka.Flag.Generation.zero_17
#print axioms Kourovka.Flag.Generation.n18
#print axioms Kourovka.Flag.Generation.value_18
#print axioms Kourovka.Flag.Generation.fixed_18
#print axioms Kourovka.Flag.Generation.zero_18
#print axioms Kourovka.Flag.Generation.n19
#print axioms Kourovka.Flag.Generation.value_19
#print axioms Kourovka.Flag.Generation.fixed_19
#print axioms Kourovka.Flag.Generation.zero_19
#print axioms Kourovka.Flag.Generation.n20
#print axioms Kourovka.Flag.Generation.value_20
#print axioms Kourovka.Flag.Generation.fixed_20
#print axioms Kourovka.Flag.Generation.zero_20
#print axioms Kourovka.Flag.Generation.n21
#print axioms Kourovka.Flag.Generation.value_21
#print axioms Kourovka.Flag.Generation.fixed_21
#print axioms Kourovka.Flag.Generation.zero_21
#print axioms Kourovka.Flag.Generation.n22
#print axioms Kourovka.Flag.Generation.value_22
#print axioms Kourovka.Flag.Generation.fixed_22
#print axioms Kourovka.Flag.Generation.zero_22
#print axioms Kourovka.Flag.Generation.n23
#print axioms Kourovka.Flag.Generation.value_23
#print axioms Kourovka.Flag.Generation.fixed_23
#print axioms Kourovka.Flag.Generation.zero_23
#print axioms Kourovka.Flag.Generation.n24
#print axioms Kourovka.Flag.Generation.value_24
#print axioms Kourovka.Flag.Generation.fixed_24
#print axioms Kourovka.Flag.Generation.zero_24
#print axioms Kourovka.Flag.Generation.n25
#print axioms Kourovka.Flag.Generation.value_25
#print axioms Kourovka.Flag.Generation.fixed_25
#print axioms Kourovka.Flag.Generation.zero_25
#print axioms Kourovka.Flag.Generation.n26
#print axioms Kourovka.Flag.Generation.value_26
#print axioms Kourovka.Flag.Generation.fixed_26
#print axioms Kourovka.Flag.Generation.zero_26
#print axioms Kourovka.Flag.Generation.n27
#print axioms Kourovka.Flag.Generation.value_27
#print axioms Kourovka.Flag.Generation.fixed_27
#print axioms Kourovka.Flag.Generation.zero_27
#print axioms Kourovka.Flag.Generation.n28
#print axioms Kourovka.Flag.Generation.value_28
#print axioms Kourovka.Flag.Generation.fixed_28
#print axioms Kourovka.Flag.Generation.zero_28
#print axioms Kourovka.Flag.Generation.n29
#print axioms Kourovka.Flag.Generation.value_29
#print axioms Kourovka.Flag.Generation.fixed_29
#print axioms Kourovka.Flag.Generation.zero_29
#print axioms Kourovka.Flag.Generation.n30
#print axioms Kourovka.Flag.Generation.value_30
#print axioms Kourovka.Flag.Generation.fixed_30
#print axioms Kourovka.Flag.Generation.zero_30
#print axioms Kourovka.Flag.Generation.n31
#print axioms Kourovka.Flag.Generation.value_31
#print axioms Kourovka.Flag.Generation.fixed_31
#print axioms Kourovka.Flag.Generation.zero_31
#print axioms Kourovka.Flag.Generation.n32
#print axioms Kourovka.Flag.Generation.value_32
#print axioms Kourovka.Flag.Generation.fixed_32
#print axioms Kourovka.Flag.Generation.zero_32
#print axioms Kourovka.Flag.Generation.n33
#print axioms Kourovka.Flag.Generation.value_33
#print axioms Kourovka.Flag.Generation.fixed_33
#print axioms Kourovka.Flag.Generation.zero_33
#print axioms Kourovka.Flag.Generation.n34
#print axioms Kourovka.Flag.Generation.value_34
#print axioms Kourovka.Flag.Generation.fixed_34
#print axioms Kourovka.Flag.Generation.zero_34
#print axioms Kourovka.Flag.Generation.n35
#print axioms Kourovka.Flag.Generation.value_35
#print axioms Kourovka.Flag.Generation.fixed_35
#print axioms Kourovka.Flag.Generation.zero_35
#print axioms Kourovka.Flag.Generation.n36
#print axioms Kourovka.Flag.Generation.value_36
#print axioms Kourovka.Flag.Generation.fixed_36
#print axioms Kourovka.Flag.Generation.zero_36
#print axioms Kourovka.Flag.Generation.n37
#print axioms Kourovka.Flag.Generation.value_37
#print axioms Kourovka.Flag.Generation.fixed_37
#print axioms Kourovka.Flag.Generation.zero_37
#print axioms Kourovka.Flag.Generation.n38
#print axioms Kourovka.Flag.Generation.value_38
#print axioms Kourovka.Flag.Generation.fixed_38
#print axioms Kourovka.Flag.Generation.zero_38
#print axioms Kourovka.Flag.Generation.n39
#print axioms Kourovka.Flag.Generation.value_39
#print axioms Kourovka.Flag.Generation.fixed_39
#print axioms Kourovka.Flag.Generation.zero_39
#print axioms Kourovka.Flag.Generation.n40
#print axioms Kourovka.Flag.Generation.value_40
#print axioms Kourovka.Flag.Generation.fixed_40
#print axioms Kourovka.Flag.Generation.zero_40
#print axioms Kourovka.Flag.Generation.n41
#print axioms Kourovka.Flag.Generation.value_41
#print axioms Kourovka.Flag.Generation.fixed_41
#print axioms Kourovka.Flag.Generation.zero_41
#print axioms Kourovka.Flag.Generation.n42
#print axioms Kourovka.Flag.Generation.value_42
#print axioms Kourovka.Flag.Generation.fixed_42
#print axioms Kourovka.Flag.Generation.zero_42
#print axioms Kourovka.Flag.Generation.n43
#print axioms Kourovka.Flag.Generation.value_43
#print axioms Kourovka.Flag.Generation.fixed_43
#print axioms Kourovka.Flag.Generation.zero_43
#print axioms Kourovka.Flag.Generation.n44
#print axioms Kourovka.Flag.Generation.value_44
#print axioms Kourovka.Flag.Generation.fixed_44
#print axioms Kourovka.Flag.Generation.zero_44
#print axioms Kourovka.Flag.Generation.n45
#print axioms Kourovka.Flag.Generation.value_45
#print axioms Kourovka.Flag.Generation.fixed_45
#print axioms Kourovka.Flag.Generation.zero_45
#print axioms Kourovka.Flag.Generation.n46
#print axioms Kourovka.Flag.Generation.value_46
#print axioms Kourovka.Flag.Generation.fixed_46
#print axioms Kourovka.Flag.Generation.zero_46
#print axioms Kourovka.Flag.Generation.n47
#print axioms Kourovka.Flag.Generation.value_47
#print axioms Kourovka.Flag.Generation.fixed_47
#print axioms Kourovka.Flag.Generation.zero_47
#print axioms Kourovka.Flag.Generation.n48
#print axioms Kourovka.Flag.Generation.value_48
#print axioms Kourovka.Flag.Generation.fixed_48
#print axioms Kourovka.Flag.Generation.zero_48
#print axioms Kourovka.Flag.Generation.n49
#print axioms Kourovka.Flag.Generation.value_49
#print axioms Kourovka.Flag.Generation.fixed_49
#print axioms Kourovka.Flag.Generation.zero_49
#print axioms Kourovka.Flag.Generation.n50
#print axioms Kourovka.Flag.Generation.value_50
#print axioms Kourovka.Flag.Generation.fixed_50
#print axioms Kourovka.Flag.Generation.zero_50
#print axioms Kourovka.Flag.Generation.n51
#print axioms Kourovka.Flag.Generation.value_51
#print axioms Kourovka.Flag.Generation.fixed_51
#print axioms Kourovka.Flag.Generation.zero_51
#print axioms Kourovka.Flag.Generation.n52
#print axioms Kourovka.Flag.Generation.value_52
#print axioms Kourovka.Flag.Generation.fixed_52
#print axioms Kourovka.Flag.Generation.zero_52
#print axioms Kourovka.Flag.Generation.n53
#print axioms Kourovka.Flag.Generation.value_53
#print axioms Kourovka.Flag.Generation.fixed_53
#print axioms Kourovka.Flag.Generation.zero_53
#print axioms Kourovka.Flag.Generation.n54
#print axioms Kourovka.Flag.Generation.value_54
#print axioms Kourovka.Flag.Generation.fixed_54
#print axioms Kourovka.Flag.Generation.zero_54
#print axioms Kourovka.Flag.Generation.n55
#print axioms Kourovka.Flag.Generation.value_55
#print axioms Kourovka.Flag.Generation.fixed_55
#print axioms Kourovka.Flag.Generation.zero_55
#print axioms Kourovka.Flag.Generation.n56
#print axioms Kourovka.Flag.Generation.value_56
#print axioms Kourovka.Flag.Generation.fixed_56
#print axioms Kourovka.Flag.Generation.zero_56
#print axioms Kourovka.Flag.Generation.n57
#print axioms Kourovka.Flag.Generation.value_57
#print axioms Kourovka.Flag.Generation.fixed_57
#print axioms Kourovka.Flag.Generation.zero_57
#print axioms Kourovka.Flag.Generation.n58
#print axioms Kourovka.Flag.Generation.value_58
#print axioms Kourovka.Flag.Generation.fixed_58
#print axioms Kourovka.Flag.Generation.zero_58
#print axioms Kourovka.Flag.Generation.n59
#print axioms Kourovka.Flag.Generation.value_59
#print axioms Kourovka.Flag.Generation.fixed_59
#print axioms Kourovka.Flag.Generation.zero_59
#print axioms Kourovka.Flag.Generation.n60
#print axioms Kourovka.Flag.Generation.value_60
#print axioms Kourovka.Flag.Generation.fixed_60
#print axioms Kourovka.Flag.Generation.zero_60
#print axioms Kourovka.Flag.Generation.n61
#print axioms Kourovka.Flag.Generation.value_61
#print axioms Kourovka.Flag.Generation.fixed_61
#print axioms Kourovka.Flag.Generation.zero_61
#print axioms Kourovka.Flag.Generation.n62
#print axioms Kourovka.Flag.Generation.value_62
#print axioms Kourovka.Flag.Generation.fixed_62
#print axioms Kourovka.Flag.Generation.zero_62
#print axioms Kourovka.Flag.Generation.n63
#print axioms Kourovka.Flag.Generation.value_63
#print axioms Kourovka.Flag.Generation.fixed_63
#print axioms Kourovka.Flag.Generation.zero_63
#print axioms Kourovka.Flag.Generation.n64
#print axioms Kourovka.Flag.Generation.value_64
#print axioms Kourovka.Flag.Generation.fixed_64
#print axioms Kourovka.Flag.Generation.zero_64
#print axioms Kourovka.Flag.Generation.n65
#print axioms Kourovka.Flag.Generation.value_65
#print axioms Kourovka.Flag.Generation.fixed_65
#print axioms Kourovka.Flag.Generation.zero_65
#print axioms Kourovka.Flag.Generation.n66
#print axioms Kourovka.Flag.Generation.value_66
#print axioms Kourovka.Flag.Generation.fixed_66
#print axioms Kourovka.Flag.Generation.zero_66
#print axioms Kourovka.Flag.Generation.n67
#print axioms Kourovka.Flag.Generation.value_67
#print axioms Kourovka.Flag.Generation.fixed_67
#print axioms Kourovka.Flag.Generation.zero_67
#print axioms Kourovka.Flag.Generation.n68
#print axioms Kourovka.Flag.Generation.value_68
#print axioms Kourovka.Flag.Generation.fixed_68
#print axioms Kourovka.Flag.Generation.zero_68
#print axioms Kourovka.Flag.Generation.n69
#print axioms Kourovka.Flag.Generation.value_69
#print axioms Kourovka.Flag.Generation.fixed_69
#print axioms Kourovka.Flag.Generation.zero_69
#print axioms Kourovka.Flag.Generation.n70
#print axioms Kourovka.Flag.Generation.value_70
#print axioms Kourovka.Flag.Generation.fixed_70
#print axioms Kourovka.Flag.Generation.zero_70
#print axioms Kourovka.Flag.Generation.n71
#print axioms Kourovka.Flag.Generation.value_71
#print axioms Kourovka.Flag.Generation.fixed_71
#print axioms Kourovka.Flag.Generation.zero_71
#print axioms Kourovka.Flag.Generation.n72
#print axioms Kourovka.Flag.Generation.value_72
#print axioms Kourovka.Flag.Generation.fixed_72
#print axioms Kourovka.Flag.Generation.zero_72
#print axioms Kourovka.Flag.Generation.n73
#print axioms Kourovka.Flag.Generation.value_73
#print axioms Kourovka.Flag.Generation.fixed_73
#print axioms Kourovka.Flag.Generation.zero_73
#print axioms Kourovka.Flag.Generation.n74
#print axioms Kourovka.Flag.Generation.value_74
#print axioms Kourovka.Flag.Generation.fixed_74
#print axioms Kourovka.Flag.Generation.zero_74
#print axioms Kourovka.Flag.Generation.n75
#print axioms Kourovka.Flag.Generation.value_75
#print axioms Kourovka.Flag.Generation.fixed_75
#print axioms Kourovka.Flag.Generation.zero_75
#print axioms Kourovka.Flag.Generation.n76
#print axioms Kourovka.Flag.Generation.value_76
#print axioms Kourovka.Flag.Generation.fixed_76
#print axioms Kourovka.Flag.Generation.zero_76
#print axioms Kourovka.Flag.Generation.n77
#print axioms Kourovka.Flag.Generation.value_77
#print axioms Kourovka.Flag.Generation.fixed_77
#print axioms Kourovka.Flag.Generation.zero_77
#print axioms Kourovka.Flag.Generation.n78
#print axioms Kourovka.Flag.Generation.value_78
#print axioms Kourovka.Flag.Generation.fixed_78
#print axioms Kourovka.Flag.Generation.zero_78
#print axioms Kourovka.Flag.Generation.n79
#print axioms Kourovka.Flag.Generation.value_79
#print axioms Kourovka.Flag.Generation.fixed_79
#print axioms Kourovka.Flag.Generation.zero_79
#print axioms Kourovka.Flag.Generation.n80
#print axioms Kourovka.Flag.Generation.value_80
#print axioms Kourovka.Flag.Generation.fixed_80
#print axioms Kourovka.Flag.Generation.zero_80
#print axioms Kourovka.Flag.Generation.n81
#print axioms Kourovka.Flag.Generation.value_81
#print axioms Kourovka.Flag.Generation.fixed_81
#print axioms Kourovka.Flag.Generation.zero_81
#print axioms Kourovka.Flag.Generation.n82
#print axioms Kourovka.Flag.Generation.value_82
#print axioms Kourovka.Flag.Generation.fixed_82
#print axioms Kourovka.Flag.Generation.zero_82
#print axioms Kourovka.Flag.Generation.n83
#print axioms Kourovka.Flag.Generation.value_83
#print axioms Kourovka.Flag.Generation.fixed_83
#print axioms Kourovka.Flag.Generation.zero_83
#print axioms Kourovka.Flag.Generation.n84
#print axioms Kourovka.Flag.Generation.value_84
#print axioms Kourovka.Flag.Generation.fixed_84
#print axioms Kourovka.Flag.Generation.zero_84
#print axioms Kourovka.Flag.Generation.n85
#print axioms Kourovka.Flag.Generation.value_85
#print axioms Kourovka.Flag.Generation.fixed_85
#print axioms Kourovka.Flag.Generation.zero_85
#print axioms Kourovka.Flag.Generation.n86
#print axioms Kourovka.Flag.Generation.value_86
#print axioms Kourovka.Flag.Generation.fixed_86
#print axioms Kourovka.Flag.Generation.zero_86
#print axioms Kourovka.Flag.Generation.n87
#print axioms Kourovka.Flag.Generation.value_87
#print axioms Kourovka.Flag.Generation.fixed_87
#print axioms Kourovka.Flag.Generation.zero_87
#print axioms Kourovka.Flag.Generation.target_0
#print axioms Kourovka.Flag.Generation.target_1
#print axioms Kourovka.Flag.Generation.target_2
#print axioms Kourovka.Flag.Generation.target_3
#print axioms Kourovka.Flag.Generation.target_4
#print axioms Kourovka.Flag.Generation.target_5
#print axioms Kourovka.Flag.Generation.target_6
#print axioms Kourovka.Flag.Generation.target_7
#print axioms Kourovka.Flag.Generation.target_8
#print axioms Kourovka.Flag.Generation.target_9
#print axioms Kourovka.Flag.Generation.target_10
#print axioms Kourovka.Flag.Generation.target_11
#print axioms Kourovka.Flag.Generation.target_12
#print axioms Kourovka.Flag.Generation.target_13
#print axioms Kourovka.Flag.Generation.target_14
#print axioms Kourovka.Flag.Generation.target_15
#print axioms Kourovka.Flag.Generation.target_16
#print axioms Kourovka.Flag.Generation.target_17
#print axioms Kourovka.Flag.Generation.target_18
#print axioms Kourovka.Flag.Generation.target_19
#print axioms Kourovka.Flag.Generation.target_20
#print axioms Kourovka.Flag.Generation.target_21
#print axioms Kourovka.Flag.Generation.target_22
#print axioms Kourovka.Flag.Generation.target_23
#print axioms Kourovka.Flag.Generation.target_24
#print axioms Kourovka.Flag.Generation.target_25
#print axioms Kourovka.Flag.Generation.target_26
#print axioms Kourovka.Flag.Generation.target_27
#print axioms Kourovka.Flag.Generation.target_28
#print axioms Kourovka.Flag.Generation.target_29
#print axioms Kourovka.Flag.Generation.target_30
#print axioms Kourovka.Flag.Generation.fixed_basis
#print axioms Kourovka.Flag.Generation.zero_basis
#print axioms Kourovka.Flag.Generation.fixed_all
#print axioms Kourovka.Flag.Generation.zero_all
#print axioms Kourovka.Flag.fixes_x
#print axioms Kourovka.Flag.automorphism_ad_images
#print axioms Kourovka.Flag.residual_sign_is_one
#print axioms Kourovka.Flag.full_flag_rigidity
#print axioms Kourovka.Flag.derivation_kills_x
#print axioms Kourovka.Flag.derivation_ad_images
#print axioms Kourovka.Flag.infinitesimal_flag_rigidity
#print axioms Kourovka.Flag.lieEquiv_flag_rigidity
#print axioms Kourovka.FlagScalars.automorphism_first_stage
#print axioms Kourovka.FlagScalars.derivation_first_stage
#print axioms Kourovka.FlagScalars.exclude_residual_sign
#print axioms Kourovka.Lattice.toOriginalFn
#print axioms Kourovka.Lattice.fromOriginalFn
#print axioms Kourovka.Lattice.P
#print axioms Kourovka.Lattice.adaptedB
#print axioms Kourovka.Lattice.weight
#print axioms Kourovka.Lattice.degree
#print axioms Kourovka.Lattice.weight_bounds
#print axioms Kourovka.Lattice.degree_bounds
#print axioms Kourovka.Lattice.diagonal
#print axioms Kourovka.Lattice.embed
#print axioms Kourovka.Lattice.embed_apply
#print axioms Kourovka.Lattice.diagonal_injective
#print axioms Kourovka.Lattice.embed_injective
#print axioms Kourovka.Lattice.embed_divisible_two
#print axioms Kourovka.Lattice.embed_divisible_reflect
#print axioms Kourovka.Lattice.Checks.embed_0
#print axioms Kourovka.Lattice.Checks.embed_1
#print axioms Kourovka.Lattice.Checks.embed_2
#print axioms Kourovka.Lattice.Checks.embed_3
#print axioms Kourovka.Lattice.Checks.embed_4
#print axioms Kourovka.Lattice.Checks.embed_5
#print axioms Kourovka.Lattice.Checks.embed_6
#print axioms Kourovka.Lattice.Checks.embed_7
#print axioms Kourovka.Lattice.Checks.embed_8
#print axioms Kourovka.Lattice.Checks.embed_9
#print axioms Kourovka.Lattice.Checks.embed_10
#print axioms Kourovka.Lattice.Checks.embed_11
#print axioms Kourovka.Lattice.Checks.embed_12
#print axioms Kourovka.Lattice.Checks.embed_13
#print axioms Kourovka.Lattice.Checks.embed_14
#print axioms Kourovka.Lattice.Checks.embed_15
#print axioms Kourovka.Lattice.Checks.embed_16
#print axioms Kourovka.Lattice.Checks.embed_17
#print axioms Kourovka.Lattice.Checks.embed_18
#print axioms Kourovka.Lattice.Checks.embed_19
#print axioms Kourovka.Lattice.Checks.embed_20
#print axioms Kourovka.Lattice.Checks.embed_21
#print axioms Kourovka.Lattice.Checks.embed_22
#print axioms Kourovka.Lattice.Checks.embed_23
#print axioms Kourovka.Lattice.Checks.embed_24
#print axioms Kourovka.Lattice.Checks.embed_25
#print axioms Kourovka.Lattice.Checks.embed_26
#print axioms Kourovka.Lattice.Checks.embed_27
#print axioms Kourovka.Lattice.Checks.embed_28
#print axioms Kourovka.Lattice.Checks.embed_29
#print axioms Kourovka.Lattice.Checks.embed_30
#print axioms Kourovka.Lattice.originalBasis
#print axioms Kourovka.Lattice.P_unit
#print axioms Kourovka.Lattice.diagonal_unit
#print axioms Kourovka.Lattice.embed_unit
#print axioms Kourovka.Lattice.LB_basis_coeff
#print axioms Kourovka.Lattice.Expr
#print axioms Kourovka.Lattice.Expr.eval
#print axioms Kourovka.Lattice.Expr.map_eval
#print axioms Kourovka.Lattice.Expr.eval_mem
#print axioms Kourovka.Lattice.Expr.approximate_map_mem
#print axioms Kourovka.Lattice.Expr.approximate_derivation_mem
#print axioms Kourovka.Lattice.embedCheck_all
#print axioms Kourovka.Lattice.embed_bracket
#print axioms Kourovka.Lattice.integer_leibniz
#print axioms Kourovka.Lattice.integer_jacobi_defect
#print axioms Kourovka.Lattice.LB_leibniz
#print axioms Kourovka.Lattice.lieRing
#print axioms Kourovka.Lattice.lieAlgebra
#print axioms Kourovka.Lattice.diagonal_bracket
#print axioms Kourovka.Lattice.IntegralGeneration.castAdd
#print axioms Kourovka.Lattice.IntegralGeneration.generator_value_ring
#print axioms Kourovka.Lattice.IntegralGeneration.closedSubmodule_eq_top
#print axioms Kourovka.Lattice.IntegralGeneration.denominator_unit_padic
#print axioms Kourovka.Lattice.IntegralGeneration.padic_generation
#print axioms Kourovka.Lattice.IntegralGeneration.X
#print axioms Kourovka.Lattice.IntegralGeneration.Y
#print axioms Kourovka.Lattice.IntegralGeneration.ev
#print axioms Kourovka.Lattice.IntegralGeneration.g0
#print axioms Kourovka.Lattice.IntegralGeneration.eval_0
#print axioms Kourovka.Lattice.IntegralGeneration.g1
#print axioms Kourovka.Lattice.IntegralGeneration.eval_1
#print axioms Kourovka.Lattice.IntegralGeneration.g2
#print axioms Kourovka.Lattice.IntegralGeneration.eval_2
#print axioms Kourovka.Lattice.IntegralGeneration.g3
#print axioms Kourovka.Lattice.IntegralGeneration.eval_3
#print axioms Kourovka.Lattice.IntegralGeneration.g4
#print axioms Kourovka.Lattice.IntegralGeneration.eval_4
#print axioms Kourovka.Lattice.IntegralGeneration.g5
#print axioms Kourovka.Lattice.IntegralGeneration.eval_5
#print axioms Kourovka.Lattice.IntegralGeneration.g6
#print axioms Kourovka.Lattice.IntegralGeneration.eval_6
#print axioms Kourovka.Lattice.IntegralGeneration.g7
#print axioms Kourovka.Lattice.IntegralGeneration.eval_7
#print axioms Kourovka.Lattice.IntegralGeneration.g8
#print axioms Kourovka.Lattice.IntegralGeneration.eval_8
#print axioms Kourovka.Lattice.IntegralGeneration.g9
#print axioms Kourovka.Lattice.IntegralGeneration.eval_9
#print axioms Kourovka.Lattice.IntegralGeneration.g10
#print axioms Kourovka.Lattice.IntegralGeneration.eval_10
#print axioms Kourovka.Lattice.IntegralGeneration.g11
#print axioms Kourovka.Lattice.IntegralGeneration.eval_11
#print axioms Kourovka.Lattice.IntegralGeneration.g12
#print axioms Kourovka.Lattice.IntegralGeneration.eval_12
#print axioms Kourovka.Lattice.IntegralGeneration.g13
#print axioms Kourovka.Lattice.IntegralGeneration.eval_13
#print axioms Kourovka.Lattice.IntegralGeneration.g14
#print axioms Kourovka.Lattice.IntegralGeneration.eval_14
#print axioms Kourovka.Lattice.IntegralGeneration.g15
#print axioms Kourovka.Lattice.IntegralGeneration.eval_15
#print axioms Kourovka.Lattice.IntegralGeneration.g16
#print axioms Kourovka.Lattice.IntegralGeneration.eval_16
#print axioms Kourovka.Lattice.IntegralGeneration.g17
#print axioms Kourovka.Lattice.IntegralGeneration.eval_17
#print axioms Kourovka.Lattice.IntegralGeneration.g18
#print axioms Kourovka.Lattice.IntegralGeneration.eval_18
#print axioms Kourovka.Lattice.IntegralGeneration.g19
#print axioms Kourovka.Lattice.IntegralGeneration.eval_19
#print axioms Kourovka.Lattice.IntegralGeneration.g20
#print axioms Kourovka.Lattice.IntegralGeneration.eval_20
#print axioms Kourovka.Lattice.IntegralGeneration.g21
#print axioms Kourovka.Lattice.IntegralGeneration.eval_21
#print axioms Kourovka.Lattice.IntegralGeneration.g22
#print axioms Kourovka.Lattice.IntegralGeneration.eval_22
#print axioms Kourovka.Lattice.IntegralGeneration.g23
#print axioms Kourovka.Lattice.IntegralGeneration.eval_23
#print axioms Kourovka.Lattice.IntegralGeneration.g24
#print axioms Kourovka.Lattice.IntegralGeneration.eval_24
#print axioms Kourovka.Lattice.IntegralGeneration.g25
#print axioms Kourovka.Lattice.IntegralGeneration.eval_25
#print axioms Kourovka.Lattice.IntegralGeneration.g26
#print axioms Kourovka.Lattice.IntegralGeneration.eval_26
#print axioms Kourovka.Lattice.IntegralGeneration.g27
#print axioms Kourovka.Lattice.IntegralGeneration.eval_27
#print axioms Kourovka.Lattice.IntegralGeneration.g28
#print axioms Kourovka.Lattice.IntegralGeneration.eval_28
#print axioms Kourovka.Lattice.IntegralGeneration.g29
#print axioms Kourovka.Lattice.IntegralGeneration.eval_29
#print axioms Kourovka.Lattice.IntegralGeneration.g30
#print axioms Kourovka.Lattice.IntegralGeneration.eval_30
#print axioms Kourovka.Lattice.IntegralGeneration.g31
#print axioms Kourovka.Lattice.IntegralGeneration.eval_31
#print axioms Kourovka.Lattice.IntegralGeneration.g32
#print axioms Kourovka.Lattice.IntegralGeneration.eval_32
#print axioms Kourovka.Lattice.IntegralGeneration.g33
#print axioms Kourovka.Lattice.IntegralGeneration.eval_33
#print axioms Kourovka.Lattice.IntegralGeneration.g34
#print axioms Kourovka.Lattice.IntegralGeneration.eval_34
#print axioms Kourovka.Lattice.IntegralGeneration.g35
#print axioms Kourovka.Lattice.IntegralGeneration.eval_35
#print axioms Kourovka.Lattice.IntegralGeneration.g36
#print axioms Kourovka.Lattice.IntegralGeneration.eval_36
#print axioms Kourovka.Lattice.IntegralGeneration.g37
#print axioms Kourovka.Lattice.IntegralGeneration.eval_37
#print axioms Kourovka.Lattice.IntegralGeneration.g38
#print axioms Kourovka.Lattice.IntegralGeneration.eval_38
#print axioms Kourovka.Lattice.IntegralGeneration.g39
#print axioms Kourovka.Lattice.IntegralGeneration.eval_39
#print axioms Kourovka.Lattice.IntegralGeneration.g40
#print axioms Kourovka.Lattice.IntegralGeneration.eval_40
#print axioms Kourovka.Lattice.IntegralGeneration.g41
#print axioms Kourovka.Lattice.IntegralGeneration.eval_41
#print axioms Kourovka.Lattice.IntegralGeneration.g42
#print axioms Kourovka.Lattice.IntegralGeneration.eval_42
#print axioms Kourovka.Lattice.IntegralGeneration.g43
#print axioms Kourovka.Lattice.IntegralGeneration.eval_43
#print axioms Kourovka.Lattice.IntegralGeneration.g44
#print axioms Kourovka.Lattice.IntegralGeneration.eval_44
#print axioms Kourovka.Lattice.IntegralGeneration.g45
#print axioms Kourovka.Lattice.IntegralGeneration.eval_45
#print axioms Kourovka.Lattice.IntegralGeneration.g46
#print axioms Kourovka.Lattice.IntegralGeneration.eval_46
#print axioms Kourovka.Lattice.IntegralGeneration.g47
#print axioms Kourovka.Lattice.IntegralGeneration.eval_47
#print axioms Kourovka.Lattice.IntegralGeneration.g48
#print axioms Kourovka.Lattice.IntegralGeneration.eval_48
#print axioms Kourovka.Lattice.IntegralGeneration.g49
#print axioms Kourovka.Lattice.IntegralGeneration.eval_49
#print axioms Kourovka.Lattice.IntegralGeneration.g50
#print axioms Kourovka.Lattice.IntegralGeneration.eval_50
#print axioms Kourovka.Lattice.IntegralGeneration.g51
#print axioms Kourovka.Lattice.IntegralGeneration.eval_51
#print axioms Kourovka.Lattice.IntegralGeneration.g52
#print axioms Kourovka.Lattice.IntegralGeneration.eval_52
#print axioms Kourovka.Lattice.IntegralGeneration.g53
#print axioms Kourovka.Lattice.IntegralGeneration.eval_53
#print axioms Kourovka.Lattice.IntegralGeneration.g54
#print axioms Kourovka.Lattice.IntegralGeneration.eval_54
#print axioms Kourovka.Lattice.IntegralGeneration.g55
#print axioms Kourovka.Lattice.IntegralGeneration.eval_55
#print axioms Kourovka.Lattice.IntegralGeneration.g56
#print axioms Kourovka.Lattice.IntegralGeneration.eval_56
#print axioms Kourovka.Lattice.IntegralGeneration.g57
#print axioms Kourovka.Lattice.IntegralGeneration.eval_57
#print axioms Kourovka.Lattice.IntegralGeneration.g58
#print axioms Kourovka.Lattice.IntegralGeneration.eval_58
#print axioms Kourovka.Lattice.IntegralGeneration.g59
#print axioms Kourovka.Lattice.IntegralGeneration.eval_59
#print axioms Kourovka.Lattice.IntegralGeneration.g60
#print axioms Kourovka.Lattice.IntegralGeneration.eval_60
#print axioms Kourovka.Lattice.IntegralGeneration.g61
#print axioms Kourovka.Lattice.IntegralGeneration.eval_61
#print axioms Kourovka.Lattice.IntegralGeneration.g62
#print axioms Kourovka.Lattice.IntegralGeneration.eval_62
#print axioms Kourovka.Lattice.IntegralGeneration.g63
#print axioms Kourovka.Lattice.IntegralGeneration.eval_63
#print axioms Kourovka.Lattice.IntegralGeneration.g64
#print axioms Kourovka.Lattice.IntegralGeneration.eval_64
#print axioms Kourovka.Lattice.IntegralGeneration.g65
#print axioms Kourovka.Lattice.IntegralGeneration.eval_65
#print axioms Kourovka.Lattice.IntegralGeneration.g66
#print axioms Kourovka.Lattice.IntegralGeneration.eval_66
#print axioms Kourovka.Lattice.IntegralGeneration.g67
#print axioms Kourovka.Lattice.IntegralGeneration.eval_67
#print axioms Kourovka.Lattice.IntegralGeneration.g68
#print axioms Kourovka.Lattice.IntegralGeneration.eval_68
#print axioms Kourovka.Lattice.IntegralGeneration.g69
#print axioms Kourovka.Lattice.IntegralGeneration.eval_69
#print axioms Kourovka.Lattice.IntegralGeneration.g70
#print axioms Kourovka.Lattice.IntegralGeneration.eval_70
#print axioms Kourovka.Lattice.IntegralGeneration.g71
#print axioms Kourovka.Lattice.IntegralGeneration.eval_71
#print axioms Kourovka.Lattice.IntegralGeneration.g72
#print axioms Kourovka.Lattice.IntegralGeneration.eval_72
#print axioms Kourovka.Lattice.IntegralGeneration.g73
#print axioms Kourovka.Lattice.IntegralGeneration.eval_73
#print axioms Kourovka.Lattice.IntegralGeneration.g74
#print axioms Kourovka.Lattice.IntegralGeneration.eval_74
#print axioms Kourovka.Lattice.IntegralGeneration.g75
#print axioms Kourovka.Lattice.IntegralGeneration.eval_75
#print axioms Kourovka.Lattice.IntegralGeneration.g76
#print axioms Kourovka.Lattice.IntegralGeneration.eval_76
#print axioms Kourovka.Lattice.IntegralGeneration.g77
#print axioms Kourovka.Lattice.IntegralGeneration.eval_77
#print axioms Kourovka.Lattice.IntegralGeneration.g78
#print axioms Kourovka.Lattice.IntegralGeneration.eval_78
#print axioms Kourovka.Lattice.IntegralGeneration.g79
#print axioms Kourovka.Lattice.IntegralGeneration.eval_79
#print axioms Kourovka.Lattice.IntegralGeneration.g80
#print axioms Kourovka.Lattice.IntegralGeneration.eval_80
#print axioms Kourovka.Lattice.IntegralGeneration.g81
#print axioms Kourovka.Lattice.IntegralGeneration.eval_81
#print axioms Kourovka.Lattice.IntegralGeneration.g82
#print axioms Kourovka.Lattice.IntegralGeneration.eval_82
#print axioms Kourovka.Lattice.IntegralGeneration.g83
#print axioms Kourovka.Lattice.IntegralGeneration.eval_83
#print axioms Kourovka.Lattice.IntegralGeneration.g84
#print axioms Kourovka.Lattice.IntegralGeneration.eval_84
#print axioms Kourovka.Lattice.IntegralGeneration.g85
#print axioms Kourovka.Lattice.IntegralGeneration.eval_85
#print axioms Kourovka.Lattice.IntegralGeneration.g86
#print axioms Kourovka.Lattice.IntegralGeneration.eval_86
#print axioms Kourovka.Lattice.IntegralGeneration.g87
#print axioms Kourovka.Lattice.IntegralGeneration.eval_87
#print axioms Kourovka.Lattice.IntegralGeneration.denominator
#print axioms Kourovka.Lattice.IntegralGeneration.generator
#print axioms Kourovka.Lattice.IntegralGeneration.denominator_not_divisible
#print axioms Kourovka.Lattice.IntegralGeneration.generator_value_0
#print axioms Kourovka.Lattice.IntegralGeneration.generator_value_1
#print axioms Kourovka.Lattice.IntegralGeneration.generator_value_2
#print axioms Kourovka.Lattice.IntegralGeneration.generator_value_3
#print axioms Kourovka.Lattice.IntegralGeneration.generator_value_4
#print axioms Kourovka.Lattice.IntegralGeneration.generator_value_5
#print axioms Kourovka.Lattice.IntegralGeneration.generator_value_6
#print axioms Kourovka.Lattice.IntegralGeneration.generator_value_7
#print axioms Kourovka.Lattice.IntegralGeneration.generator_value_8
#print axioms Kourovka.Lattice.IntegralGeneration.generator_value_9
#print axioms Kourovka.Lattice.IntegralGeneration.generator_value_10
#print axioms Kourovka.Lattice.IntegralGeneration.generator_value_11
#print axioms Kourovka.Lattice.IntegralGeneration.generator_value_12
#print axioms Kourovka.Lattice.IntegralGeneration.generator_value_13
#print axioms Kourovka.Lattice.IntegralGeneration.generator_value_14
#print axioms Kourovka.Lattice.IntegralGeneration.generator_value_15
#print axioms Kourovka.Lattice.IntegralGeneration.generator_value_16
#print axioms Kourovka.Lattice.IntegralGeneration.generator_value_17
#print axioms Kourovka.Lattice.IntegralGeneration.generator_value_18
#print axioms Kourovka.Lattice.IntegralGeneration.generator_value_19
#print axioms Kourovka.Lattice.IntegralGeneration.generator_value_20
#print axioms Kourovka.Lattice.IntegralGeneration.generator_value_21
#print axioms Kourovka.Lattice.IntegralGeneration.generator_value_22
#print axioms Kourovka.Lattice.IntegralGeneration.generator_value_23
#print axioms Kourovka.Lattice.IntegralGeneration.generator_value_24
#print axioms Kourovka.Lattice.IntegralGeneration.generator_value_25
#print axioms Kourovka.Lattice.IntegralGeneration.generator_value_26
#print axioms Kourovka.Lattice.IntegralGeneration.generator_value_27
#print axioms Kourovka.Lattice.IntegralGeneration.generator_value_28
#print axioms Kourovka.Lattice.IntegralGeneration.generator_value_29
#print axioms Kourovka.Lattice.IntegralGeneration.generator_value_30
#print axioms Kourovka.Lattice.IntegralGeneration.generator_value
#print axioms Kourovka.Lattice.NearIdentity.powers_natural
#print axioms Kourovka.Lattice.NearIdentity.ambient_power_divisible
#print axioms Kourovka.Lattice.NearIdentity.ell_power_divisible
#print axioms Kourovka.Lattice.NearIdentity.reduce_scalar_modulus
#print axioms Kourovka.Lattice.NearIdentity.finite_power_zero
#print axioms Kourovka.Lattice.NearIdentity.finiteOneAddUnit
#print axioms Kourovka.Lattice.NearIdentity.finiteOneAddUnit_value
#print axioms Kourovka.Lattice.Precision.scaled
#print axioms Kourovka.Lattice.Precision.scaled_le
#print axioms Kourovka.Lattice.Precision.scaled_mono
#print axioms Kourovka.Lattice.Precision.scaled_antitone
#print axioms Kourovka.Lattice.Precision.cancel_smul
#print axioms Kourovka.Lattice.Precision.cancel_scaled_membership
#print axioms Kourovka.Lattice.Precision.bilinear_error_enlargement
#print axioms Kourovka.Lattice.Precision.automorphismError
#print axioms Kourovka.Lattice.Precision.automorphismError_apply
#print axioms Kourovka.Lattice.Precision.error_scaled_bracket
#print axioms Kourovka.Lattice.Precision.derivation_scaled_bracket
#print axioms Kourovka.Lattice.Precision.arbitrary_automorphism_error_bound
#print axioms Kourovka.Lattice.Precision.arbitrary_derivation_error_bound
#print axioms Kourovka.Lattice.Precision.expressionSpan
#print axioms Kourovka.Lattice.Precision.approximate_lift_preserves
#print axioms Kourovka.Lattice.Precision.approximate_derivation_lift_preserves
#print axioms Kourovka.Lattice.scaledTerms
#print axioms Kourovka.Lattice.LB
#print axioms Kourovka.Lattice.LB_alternating
#print axioms Kourovka.Lattice.mapVec_LB
#print axioms Kourovka.Lattice.EmbedCheck
#print axioms Kourovka.Lattice.Weighted.member
#print axioms Kourovka.Lattice.Weighted.scaled_unit_mem
#print axioms Kourovka.Lattice.Weighted.entries_divisible
#print axioms Kourovka.Lattice.Weighted.reduced_entry_zero
#print axioms Kourovka.Lattice.Weighted.reduction
#print axioms Kourovka.Lattice.Weighted.level
#print axioms Kourovka.Lattice.Weighted.reduction_preserves_level
#print axioms Kourovka.Lattice.Weighted.weight_below_one
#print axioms Kourovka.Lattice.Weighted.weight_below_two
#print axioms Kourovka.Linear.unitVec
#print axioms Kourovka.Linear.unitVec_same
#print axioms Kourovka.Linear.unitVec_other
#print axioms Kourovka.Linear.decompose
#print axioms Kourovka.Linear.ext_basis
#print axioms Kourovka.Linear.linear_apply
#print axioms Kourovka.Linear.ext_bilinear
#print axioms Kourovka.Linear.ext_trilinear
#print axioms Kourovka.Linear.jacobiTensor
#print axioms Kourovka.Linear.jacobi_of_basis
#print axioms Kourovka.Linear.Bilinear
#print axioms Kourovka.Linear.post
#print axioms Kourovka.Linear.pre
#print axioms Kourovka.Linear.post_apply
#print axioms Kourovka.Linear.pre_apply
#print axioms Kourovka.Linear.transport
#print axioms Kourovka.Linear.transport_apply
#print axioms Kourovka.Linear.hom_of_basis
#print axioms Kourovka.Linear.delta
#print axioms Kourovka.Linear.delta_apply
#print axioms Kourovka.Sparse.bilinear
#print axioms Kourovka.Linear.EndCoords
#print axioms Kourovka.Linear.elementary
#print axioms Kourovka.Linear.elementary_apply
#print axioms Kourovka.Linear.fromEntries
#print axioms Kourovka.Linear.toEntries
#print axioms Kourovka.Linear.fromEntries_apply
#print axioms Kourovka.Linear.entries_fromEntries
#print axioms Kourovka.Linear.fromEntries_entries
#print axioms Kourovka.Linear.endomorphismCoordinates
#print axioms Kourovka.prime
#print axioms Kourovka.depth
#print axioms Kourovka.dimension
#print axioms Kourovka.prime_is_prime
#print axioms Kourovka.coordinate_exponent
#print axioms Kourovka.automorphism_exponent
#print axioms Kourovka.class_in_lazard_range
#print axioms Kourovka.Coordinates
#print axioms Kourovka.Raw.falling
#print axioms Kourovka.Raw.transvectant
#print axioms Kourovka.Raw.Summand
#print axioms Kourovka.Raw.summands
#print axioms Kourovka.Raw.moduleCoefficient
#print axioms Kourovka.Raw.Product
#print axioms Kourovka.Raw.products
#print axioms Kourovka.Raw.productCoefficient
#print axioms Kourovka.Raw.orderedCoefficient
#print axioms Kourovka.Raw.coefficient
#print axioms Kourovka.Raw.reconstructedTerms
#print axioms Kourovka.TableCertificate.row
#print axioms Kourovka.TableCertificate.row_0
#print axioms Kourovka.TableCertificate.row_1
#print axioms Kourovka.TableCertificate.row_2
#print axioms Kourovka.TableCertificate.row_3
#print axioms Kourovka.TableCertificate.row_4
#print axioms Kourovka.TableCertificate.row_5
#print axioms Kourovka.TableCertificate.row_6
#print axioms Kourovka.TableCertificate.row_7
#print axioms Kourovka.TableCertificate.row_8
#print axioms Kourovka.TableCertificate.row_9
#print axioms Kourovka.TableCertificate.row_10
#print axioms Kourovka.TableCertificate.row_11
#print axioms Kourovka.TableCertificate.row_12
#print axioms Kourovka.TableCertificate.row_13
#print axioms Kourovka.TableCertificate.row_14
#print axioms Kourovka.TableCertificate.row_15
#print axioms Kourovka.TableCertificate.row_16
#print axioms Kourovka.TableCertificate.row_17
#print axioms Kourovka.TableCertificate.row_18
#print axioms Kourovka.TableCertificate.row_19
#print axioms Kourovka.TableCertificate.row_20
#print axioms Kourovka.TableCertificate.row_21
#print axioms Kourovka.TableCertificate.row_22
#print axioms Kourovka.TableCertificate.row_23
#print axioms Kourovka.TableCertificate.row_24
#print axioms Kourovka.TableCertificate.row_25
#print axioms Kourovka.TableCertificate.row_26
#print axioms Kourovka.TableCertificate.row_27
#print axioms Kourovka.TableCertificate.row_28
#print axioms Kourovka.TableCertificate.row_29
#print axioms Kourovka.TableCertificate.row_30
#print axioms Kourovka.raw_table_matches_exported
#print axioms Kourovka.Word
#print axioms Kourovka.Word.eval
#print axioms Kourovka.Word.map_eval
#print axioms Kourovka.Word.fixed_eval
#print axioms Kourovka.Word.derivation_zero_eval
#print axioms Kourovka.Word.fixed_of_generation
#print axioms Kourovka.Word.zero_of_generation
