"""Read full complete evidence and author final first-party SOURCE verdict/bindings only."""
import datetime as dt,hashlib,json,os,stat
from pathlib import Path
F=Path(__file__).absolute().parent;R=F.parent.parents[2]
def need(v,n):
 if not v:raise ValueError(n)
def sha(b):return hashlib.sha256(b).hexdigest()
def regular(p):
 need(not p.is_symlink() and all(not q.is_symlink() for q in p.parents) and stat.S_ISREG(p.stat().st_mode),'Regular nonsymlink');return p.read_bytes()
def load(p):return json.loads(regular(p))
def dump(p,o):
 with p.open('x') as h:json.dump(o,h,indent=2,allow_nan=False);h.write('\n');h.flush();os.fsync(h.fileno())
rows={};observed_owned=[]
for name,key in [('CONTROL_RESULTS_V3.json','whole_fixed_body_rows'),('GATE_CONTROL_RESULTS_V3.json','whole_fixed_rows')]:
 o=load(F/name)
 for rr in o[key]:
  p=R/rr['path'];b=regular(p);need(len(b)==rr['bytes'] and sha(b)==rr['sha256'] and stat.S_IMODE(p.stat().st_mode)==rr['full_mode'],'Final repeated full body/full mode');need(rr['path'] not in rows or rows[rr['path']]==rr,'Duplicate stable exact body')
  if p.is_relative_to(F):observed_owned.append(rr)
  else:rows[rr['path']]=rr
controls=[]
for name,code,pid in [('controls_actual_capture',1,58409),('controls_actual_capture_v2',1,61867),('controls_actual_capture_v3',0,62526),('gate_controls_actual_capture',1,65140),('gate_controls_actual_capture_v2',1,65880),('gate_controls_actual_capture_v3',0,66232),('mathematical_spot_actual_capture',0,68260),('expected_negative_actual_capture',1,68262)]:
 d=F/name;c=load(d/'CAPTURE.json');pre=load(d/'PRELAUNCH.json');need(type(c['pid']) is int and c['pid']==pid and type(c['exit_code']) is int and c['exit_code']==code and c['actual_execution'] is True and c['completed'] is True and c['source_unchanged'] is True and c['operator_unchanged'] is True and c['production_import_compile_or_execution'] is False,'Exact completed failed/positive private actual');need(pre['source_sha256']==sha(regular(d/'PRELAUNCH_SOURCE.py'))==c['source_sha256'] and pre['operator_sha256']==sha(regular(d/'PRELAUNCH_OPERATOR.py'))==c['operator_sha256'],'Complete prelaunch sources')
 need(regular(Path(c['argv'][-1]))==regular(d/'PRELAUNCH_SOURCE.py'),'Executed private source unchanged')
 for k in ['stdout','stderr']:b=regular(d/(k+'.bin'));need(len(b)==c[k]['bytes'] and sha(b)==c[k]['sha256'],'Entire completed streams')
 controls.append({'directory':name,'expected_actual_pid':pid,'expected_exit_code':code,'interpretation':'EXPECTED_PRIVATE_REJECTION' if name=='expected_negative_actual_capture' else 'PASS_PRIVATE_CONTROLS' if code==0 else 'FAILED_OWN_AUDIT_SCRIPT_PRESERVED_NOT_PROMOTED','complete_capture':c})
source=F.parent/'current_preparation_family';mf=sha(regular(source/'PREPARATION_MANIFEST.json'));need(mf=='ee165341f8980110f1362a19c27f697db6df2e68eac01cc110a31c8d08ee9640','Actual SOURCE closure pin')
for name in ['REPORT.md','close_family.py','verify_family_readonly.py','INDEPENDENT_RECONSTRUCTION.md','PRIMARY_READ_NOTES.md']:regular(F/name)
report_sha=sha(regular(F/'REPORT.md'));utc=dt.datetime.now(dt.timezone.utc).isoformat()
b={'schema':'pr48-independent-SOURCE-adversary-complete-read-bindings/v1','utc':utc,'actual_inspection_pid':os.getpid(),'source_manifest_sha256':mf,'builder_sha256':sha(regular(source/'prepare_current_packet.py')),'operator_sha256':sha(regular(source/'capture_root_builder_operation.py')),'whole_external_read_rows':list(rows.values()),'unique_complete_external_bodies':len(rows),'complete_external_read_bytes':sum(rr['bytes'] for rr in rows.values()),'own_historical_full_mode_observations_before_own_future_closure':observed_owned,'own_historical_modes_are_observations_not_future_live_mode_requirements':True,'completed_private_controls':controls,'current_inspection_capture_unfinished_at_this_authoring_time':True,'current_inspection_capture_must_be_read_completed_by_ROOT_closer_after_child_exit':True,'four_actual_closed_input_schemas':load(F/'CONTROL_RESULTS_V3.json')['four_distinct_closed_inputs'],'SOURCE_actual_closing_pid':50088,'SOURCE_actual_separate_readonly_pid':50493,'production_or_helper_import_compile_execution':False,'native_index_remote_changes':False,'foreign_raw_SQL_PDF_OCR_pixel_bodies_copied':False,'future_acceptance_approved':False}
dump(F/'AUDIT_BINDINGS.json',b)
v={'schema':'pr48-independent-current-SOURCE-adversary-verdict/v1','utc':utc,'actual_authoring_pid':os.getpid(),'verdict':'PASS_STATED_UNSOLVED_PARTIAL_AND_CLOSED_SOURCE_CONTRACT','report_sha256':report_sha,'audit_bindings_sha256':sha(regular(F/'AUDIT_BINDINGS.json')),'source_preparation_manifest_sha256':mf,'builder_sha256':b['builder_sha256'],'operator_sha256':b['operator_sha256'],'mandatory_mathematical_corrections':[],'mandatory_source_corrections':[],'optional_guard_limits':load(F/'CONTROL_RESULTS_V3.json')['exact_optional_guard_limits']+['Lexical dot requires downstream file/inventory guards; scalar duplicate_id equality alone does not reject an equal float, while actual fixed plain IDs are integers.'],'inherited_context_disclosed':True,'reused_agent_prepared_unrelated_PR47_V2':True,'prepared_PR48_SOURCE':False,'source_first_reconstruction_before_full_old_reports':True,'blind_mathematical_independence_claimed':False,'historical_or_prior_family_PASS_transferred':False,'production_or_helper_import_compile_execution':False,'foreign_raw_SQL_PDF_OCR_pixel_bodies_copied':False,'full_target_resolved':False,'status_recommendation':'unsolved','duplicate_id':30004403,'duplicate_shared_budget':True,'original_substantive_attempts':2,'turn_limit':5,'new_substantive_attempts':0,'audit_turns':0,'paper':False,'DOI':False,'tracker':False,'native_index_remote_changes':False,'future_acceptance_approved':False,'candidate_frozen':False,'new_whole_current_gate':'PENDING','own_closure_executed_by_reviewer':False,'ready_for_ROOT_actual_self_only_closure':True,'ROOT_actual_closure_and_separate_postexit_readonly_capture_required':True,'assigned_SOURCE_audit_completion_estimate_percent':100,'target_discovery_completion_estimate_percent':0,'unrefereed':True,'human_peer_reviewed':False,'AI_tools_used_extensively':True}
dump(F/'VERDICT.json',v)
with (F/'RESEARCH_LOG.md').open('a') as h:h.write('\n'+utc+': Final SOURCE checkpoint. Complete fixed-body readback and all8 previous completed actual private captures/streams preserved:4 own failed audit runs,3 successes and1 expected rejection. Source verdict PASS_STATED_UNSOLVED_PARTIAL_AND_CLOSED_SOURCE_CONTRACT; mandatory repairs none. Mathematical167 exact controls and gate364 passed. Assigned SOURCE audit100%; target0%; shared2/5 new0 audit0. READY for ROOT actual self-only closer and separate postexit readonly verifier. No ownclosure/production/native/index/remote/paper/DOI/tracker or external communication.\n')
print(json.dumps({'status':'READY_SOURCE_ONLY_BINDINGS_AND_VERDICT','actual_pid':os.getpid(),'report_sha256':report_sha,'audit_bindings_sha256':v['audit_bindings_sha256'],'complete_external_bodies':len(rows),'complete_external_bytes':b['complete_external_read_bytes'],'previous_actual_captures':len(controls),'future_acceptance':False}))
