#!/usr/bin/env python3
"""Exact parameter certificates for the unchanged October 4 type construction.

Standard-library rational arithmetic only.  All inequalities used in the
mathematical audit are asserted exactly; floats are descriptive output only.
No matching outcome or group-ring witness is generated by this script.
"""
from fractions import Fraction as F
from pathlib import Path
import hashlib
import json


def quotient(q):
    v = q * q + q + 1
    p = F(q + 1, v)
    a = F(1, (q + 1) ** 2)
    # Rows/columns: E (extras), O (ordinary mates of extras), R (remaining).
    return [
        [7 * p * p, 6 * a, (v - 7) * a],
        [F(3, 2), 7 * p * p, (v - 7) * p * p],
        [7 * p * p, 7 * a, (v - 8) * a],
    ]


def ratios(q, x):
    return [
        sum(a * b for a, b in zip(row, x)) / x[i]
        for i, row in enumerate(quotient(q))
    ]


def serialize(x):
    return {"exact": str(x), "decimal_for_orientation_only": float(x)}


def main():
    root = Path(__file__).resolve().parents[2]
    source = root / "sources/preprints/A-Torsion-Free-Group-Algebra-That-Is-Not-Directly-Finite-October-4-2026/build/sections"
    expected = {
        "random.tex": "bb172b92ba622e262c2bf124e70c3cd55922200083c09db658615759b81323c4",
        "patterns.tex": "20c6cc1f3fb035150831e5091c98313f04e7a9d8aaa347507020b176394ed4ea",
        "planar.tex": "e3a1a4e23dd6871a9746ffde05d32297e695f3167b8efa0f0a4cad5da8c9ae6b",
        "algebra.tex": "71fe26eab4e6a01564a687c522bbceb8923182c0201af9685eac84d9f86a141f",
    }
    for name, digest in expected.items():
        assert hashlib.sha256((source / name).read_bytes()).hexdigest() == digest

    x = [F(193, 500), F(1), F(97, 250)]
    mu = F(503, 500)
    lower = {}
    for q in [4, 8, 16]:
        r = ratios(q, x)
        assert all(z > mu for z in r)
        v = q * q + q + 1
        assert max(x) == 1
        c = 7 * x[0] + 7 * x[1] + (v - 7) * x[2]
        lower[str(q)] = {
            "positive_vector": [str(z) for z in x],
            "row_ratios": [serialize(z) for z in r],
            "growth_factor_lower_bound": str(mu),
            "word_sum_prefactor_lower_bound": str(c),
        }

    q = 32
    v = q * q + q + 1
    p = F(q + 1, v)
    f = [F(1), F(13, 5), F(1)]
    lam = F(987, 1000)
    upper_ratios = ratios(q, f)
    assert all(z < lam for z in upper_ratios)
    prefactor = 7 * f[0] + 7 * f[1] + (v - 7) * f[2]
    assert prefactor == F(5376, 5)

    # The source's coarser vector f=(1,4,1) already works at q=32.
    original_upper = F(q, q + 1) + 7 * p * p + F(21, (q + 1) ** 2)
    original_extra = (F(3, 2) + (v + 21) * p * p) / 4
    assert original_upper < 1 and original_extra < 1
    # These bounds also prove the same certificate for every q >= 32:
    assert F(21, 33) + F(7 * 33, 32 ** 2) == F(9709, 11264) < 1
    assert F(3, 2) + 1 + F(1, 32) + F(22, 32 ** 2) < 4

    # Explicit choices for the girth and expansion estimates.
    c0 = F(1, 100)
    rho = F(1, 10 ** 6)
    assert 2 * (v + 7) / p < 2 ** 17  # log(2)<1 gives c0*log(.)<17/100.
    assert q + 8 < 2 ** 6             # 2*c0*log(d_*)<12/100.
    assert 17 * rho < p / 4
    # e<3, C2=8*e*|T|/33, D=2*C2/p, C3=(e/2)^2*max(1,D)^17.
    d_bound = F(48 * (v + 7), 33) / p
    c3_bound = F(9, 4) * d_bound ** 17
    assert d_bound < 50000
    assert c3_bound * F(1, 10 ** 87) < F(1, 2)  # rho^(29/2)=10^-87.

    # Simultaneous balanced extra-type assignments are feasible already at
    # m=13; this is a type certificate, not a successful graph certificate.
    m = 13
    am = F(33 * m - 1, 4)
    bm = F(33 * (m - 1), 4)
    assert am.denominator == bm.denominator == 1
    ceil = lambda z: -((-z.numerator) // z.denominator)
    assert 7 * ceil(am / v) + 1 < m - 1
    assert 7 * ceil(bm / v) < m - 1
    assert F(7 * 33, 4 * v) == F(33, 604) < 1

    report = {
        "scope": "Unchanged prescribed types, inverse pairs, turn weights, and asymptotic matching method; no numeric matching witness or novelty claim",
        "source_commit": "adc7f1241b42e322a6451854ab7e4b4c146bf78a",
        "verified_source_sha256": expected,
        "excluded_parameters": lower,
        "q32": {
            "v": v, "alphabet_size": v + 7, "rose_generators": (v + 7) // 2,
            "p": str(p), "degrees": [33, 37, 40],
            "positive_vector": [str(z) for z in f],
            "row_ratios": [serialize(z) for z in upper_ratios],
            "word_decay_factor_upper_bound": str(lam),
            "word_sum_prefactor_upper_bound": str(prefactor),
            "original_vector_bounds": [serialize(original_upper), serialize(original_extra)],
            "line_capacity_coefficient": "33/604", "type_assignment_checked_at_m": m,
            "c0": str(c0), "rho": str(rho), "expansion_exponent": "29/2",
            "small_k_exponent": "29/4", "D_bound": str(d_bound),
            "C3_rho_power_bound": serialize(c3_bound * F(1, 10 ** 87)),
            "minimum_degree_after_two_edge_deletions": 31,
        },
    }
    print(json.dumps(report, indent=2))


if __name__ == "__main__":
    main()
