#!/usr/bin/env python3
"""Clean-room verifier for the fixed-full hard-cover root inventory.

This file deliberately uses only the Python standard library.  It does not
import the primary implementation and it does not construct Fourier tensors.
The finite grammar is reconstructed from the locked core data.  The frozen
root and relation streams are treated as outputs to be checked.
"""

from __future__ import annotations

import argparse
import copy
import gzip
import hashlib
import io
import itertools
import json
import sys
from collections import Counter, defaultdict
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Iterable, Iterator


HERE = Path(__file__).resolve().parent
REPO = HERE.parents[1]

CORE_PATH = REPO / "primary/certificates/core_universe.json"


@dataclass(frozen=True)
class StreamSpec:
    name: str
    selected_outgoing: int
    allowed_source_cores: frozenset[str]
    root_path: Path
    relation_path: Path
    expected_records: int
    expected_decompressed_sha256: str
    expected_normalized_sha256: str


# The two normalized hashes below commit to the mathematical relation keys
# regenerated by normalize_relation().  They are intentionally independent of
# gzip metadata and JSON whitespace.  They are filled from the first clean
# regeneration and protected by the mutation suite.
SPECS = (
    StreamSpec(
        name="n3",
        selected_outgoing=3,
        allowed_source_cores=frozenset({"cycle", "theta-0", "theta-1", "theta-3"}),
        root_path=REPO / "primary/certificates/hard_cover_root_cases_n3_schema3_n3_full.jsonl.gz",
        relation_path=REPO / "primary/certificates/hard_cover_n3_schema3_n3_full.jsonl.gz",
        expected_records=5344,
        expected_decompressed_sha256="1ea38de7057295d8adbb4cd86cff269f7259d490b442bb8f96da350f7ad03583",
        expected_normalized_sha256="3ee8cfbd40544c4753222b0b97b13b95d6ca12b6161771ce410718dc0c58af26",
    ),
    StreamSpec(
        name="theta2_n4",
        selected_outgoing=4,
        allowed_source_cores=frozenset({"theta-2"}),
        root_path=REPO / "primary/certificates/hard_cover_root_cases_n4_schema3_theta2_full.jsonl.gz",
        relation_path=REPO / "primary/certificates/hard_cover_n4_schema3_theta2_full.jsonl.gz",
        expected_records=132,
        expected_decompressed_sha256="0afc6dfc357b1578e5bfeb56baf467723240211f4355d573422581db61bc4c66",
        expected_normalized_sha256="d79a847c35172374638cac935e5efed05cf37f1caf4b1bf8fe889d79a44a2904",
    ),
)


class VerificationError(RuntimeError):
    pass


def canonical_json(value: Any) -> str:
    return json.dumps(value, sort_keys=True, separators=(",", ":"), ensure_ascii=True)


def digest_text(value: str) -> str:
    return hashlib.sha256(value.encode("utf-8")).hexdigest()


def decompressed_sha256(path: Path) -> str:
    h = hashlib.sha256()
    with gzip.open(path, "rb") as handle:
        for block in iter(lambda: handle.read(1 << 20), b""):
            h.update(block)
    return h.hexdigest()


def iter_jsonl_gz(path: Path) -> Iterator[dict[str, Any]]:
    with gzip.open(path, "rt", encoding="utf-8") as handle:
        for line_number, line in enumerate(handle, 1):
            try:
                record = json.loads(line)
            except json.JSONDecodeError as exc:
                raise VerificationError(f"{path}:{line_number}: invalid JSON: {exc}") from exc
            if not isinstance(record, dict):
                raise VerificationError(f"{path}:{line_number}: record is not an object")
            yield record


def require(condition: bool, message: str) -> None:
    if not condition:
        raise VerificationError(message)


def load_cores(path: Path = CORE_PATH) -> dict[str, dict[str, Any]]:
    payload = json.loads(path.read_text(encoding="utf-8"))
    cores = payload.get("cores")
    require(isinstance(cores, list), "core_universe.json has no core list")
    result: dict[str, dict[str, Any]] = {}
    for core in cores:
        cid = core.get("id")
        require(isinstance(cid, str) and cid not in result, f"bad or duplicate core id {cid!r}")
        result[cid] = core
    require(
        set(result) == {"cycle", "theta-0", "theta-1", "theta-2", "theta-3"},
        f"primitive universe mismatch: {sorted(result)}",
    )
    return result


def sink_count(core: dict[str, Any]) -> int:
    if core["id"] == "cycle":
        return 1
    return sum(sequence.count("X") for sequence in core["path_event_sequences"])


def support_size(core: dict[str, Any]) -> int:
    return int(core["minimum_repair_size"]) + sink_count(core)


def vertex_roles(core: dict[str, Any]) -> dict[str, str]:
    """Roles used for source-support automorphisms.

    The incoming boundary fixes S.  Every path-sink child has a distinct
    selected label in a rigid source support, so X0, X1 are fixed separately.
    Branch vertices may move only when their T/R roles agree.
    """

    if core["id"] == "cycle":
        return {"S": "SOURCE", "X": "SINK_0"}
    roles = {
        "S": "SOURCE",
        "U": f"BRANCH_{core['branch_roles'][0]}",
        "V": f"BRANCH_{core['branch_roles'][1]}",
    }
    for segment in core["segments"]:
        for vertex in (segment["tail"], segment["head"]):
            if vertex.startswith("X"):
                roles[vertex] = f"SINK_{vertex[1:]}"
    return roles


def source_segment_automorphisms(core: dict[str, Any]) -> tuple[tuple[int, ...], ...]:
    """Enumerate the tiny role-preserving directed multigraph automorphism group."""

    segments = [(segment["tail"], segment["head"]) for segment in core["segments"]]
    roles = vertex_roles(core)
    role_classes: dict[str, list[str]] = defaultdict(list)
    for vertex, role in roles.items():
        role_classes[role].append(vertex)

    vertex_maps: list[dict[str, str]] = [{}]
    for vertices in role_classes.values():
        next_maps: list[dict[str, str]] = []
        for image in itertools.permutations(vertices):
            local = dict(zip(vertices, image))
            for old in vertex_maps:
                next_maps.append({**old, **local})
        vertex_maps = next_maps

    answer: set[tuple[int, ...]] = set()
    for vertex_map in vertex_maps:
        possible_images: list[list[int]] = []
        for tail, head in segments:
            image = (vertex_map[tail], vertex_map[head])
            matches = [index for index, edge in enumerate(segments) if edge == image]
            if not matches:
                break
            possible_images.append(matches)
        else:
            for permutation in itertools.permutations(range(len(segments))):
                if all(permutation[index] in possible_images[index] for index in range(len(segments))):
                    answer.add(tuple(permutation))
    require(answer, f"no source automorphism for {core['id']}")
    return tuple(sorted(answer))


def transform_source_support(
    core: dict[str, Any],
    repair_index: int,
    words: list[list[str]],
    segment_permutation: tuple[int, ...],
) -> tuple[int, list[list[str]]]:
    repairs = core["minimum_repairs"]
    old_repair = repairs[repair_index]
    new_repair = sorted(segment_permutation[segment] for segment in old_repair)
    require(new_repair in repairs, f"repair set not invariant for {core['id']}: {new_repair}")
    new_repair_index = repairs.index(new_repair)
    new_words: list[list[str] | None] = [None] * len(words)
    for old_segment, new_segment in enumerate(segment_permutation):
        transformed: list[str] = []
        for token in words[old_segment]:
            if token.startswith("Q_REPAIR_"):
                old_anchor = int(token.rsplit("_", 1)[1])
                anchor_segment = segment_permutation[old_repair[old_anchor]]
                new_anchor = new_repair.index(anchor_segment)
                token = f"Q_REPAIR_{new_anchor}"
            transformed.append(token)
        new_words[new_segment] = transformed
    require(all(word is not None for word in new_words), "segment automorphism is not bijective")
    return new_repair_index, [list(word) for word in new_words if word is not None]


def generate_source_supports(
    cores: dict[str, dict[str, Any]], selected_outgoing: int, allowed: frozenset[str]
) -> set[str]:
    """Regenerate the rigid anchored source supports, modulo fixed-label automorphisms."""

    canonical: set[str] = set()
    for cid in sorted(allowed):
        require(cid in cores, f"required source core omitted: {cid}")
        core = cores[cid]
        extra = selected_outgoing - support_size(core)
        require(extra in (0, 1), f"unsupported source probe count {extra} for {cid}")
        raw: list[tuple[int, list[list[str]]]] = []
        for repair_index, repair in enumerate(core["minimum_repairs"]):
            base = [[] for _ in core["segments"]]
            for anchor_index, segment in enumerate(repair):
                base[segment] = [f"Q_REPAIR_{anchor_index}"]
            if extra == 0:
                raw.append((repair_index, base))
            else:
                # The only positive-extra case in these streams is the cycle:
                # insert the single probe in every word gap.
                for segment, word in enumerate(base):
                    for position in range(len(word) + 1):
                        expanded = [entry[:] for entry in base]
                        expanded[segment].insert(position, "P_0")
                        raw.append((repair_index, expanded))

        automorphisms = source_segment_automorphisms(core)
        for repair_index, words in raw:
            orbit = [
                transform_source_support(core, repair_index, words, automorphism)
                for automorphism in automorphisms
            ]
            canonical_repair, canonical_words = min(
                orbit, key=lambda item: (item[0], canonical_json(item[1]))
            )
            canonical.add(canonical_json([cid, canonical_repair, canonical_words]))
    return canonical


def weak_compositions(total: int, slots: int) -> Iterator[tuple[int, ...]]:
    require(total >= 0 and slots >= 1, "invalid weak composition request")
    if slots == 1:
        yield (total,)
        return
    for bars in itertools.combinations(range(total + slots - 1), slots - 1):
        previous = -1
        counts: list[int] = []
        for bar in bars + (total + slots - 1,):
            counts.append(bar - previous - 1)
            previous = bar
        yield tuple(counts)


def build_target_completion(
    core: dict[str, Any],
    selected_outgoing: int,
    incoming_selected: bool,
    sink_mask: int,
    repair_index: int,
    counts: tuple[int, ...],
) -> tuple[list[Any], list[str], list[str]]:
    """Build one unquotiented target completion from the finite grammar."""

    cid = core["id"]
    repairs = core["minimum_repairs"]
    repair = repairs[repair_index]
    sinks = sink_count(core)
    selected_sink_count = sink_mask.bit_count()
    ordinary_count = selected_outgoing + 1 - int(incoming_selected) - selected_sink_count
    require(ordinary_count >= 0, "too many selected special ports")
    require(sum(counts) == ordinary_count, "ordinary-port count mismatch")
    require(len(counts) == len(core["segments"]), "segment-word count mismatch")

    words: list[list[str]] = []
    cursor = 0
    for segment, count in enumerate(counts):
        word = [f"O_{index}" for index in range(cursor, cursor + count)]
        cursor += count
        if segment in repair and count == 0:
            word.append(f"D_REPAIR_{repair_index}_{segment}")
        words.append(word)

    dummy_roles = [
        f"D_REPAIR_{repair_index}_{segment}" for segment in repair if counts[segment] == 0
    ]
    dummy_roles.extend(
        f"D_SINK_{index}" for index in range(sinks) if not ((sink_mask >> index) & 1)
    )
    if not incoming_selected:
        dummy_roles.append("INCOMING")

    selected_labels = [f"O_{index}" for index in range(ordinary_count)]
    selected_labels.extend(
        f"SINK_{index}" for index in range(sinks) if (sink_mask >> index) & 1
    )
    if incoming_selected:
        selected_labels.append("INCOMING")

    provenance = [
        cid,
        sink_mask,
        None if cid == "cycle" else repair_index,
        words,
        dummy_roles,
        incoming_selected,
    ]
    return provenance, selected_labels, dummy_roles


def generate_raw_target_universe(
    cores: dict[str, dict[str, Any]], selected_outgoing: int
) -> dict[str, tuple[list[str], list[str]]]:
    """Generate the full pre-isomorphism target completion grammar.

    The primary stream may contain only an algebraically selected subset.  The
    raw universe is deliberately larger and is used only for a structural
    membership/exhaustiveness check.
    """

    universe: dict[str, tuple[list[str], list[str]]] = {}
    for cid in sorted(cores):
        core = cores[cid]
        sinks = sink_count(core)
        for incoming_selected in (False, True):
            for sink_mask in range(1 << sinks):
                ordinary_count = selected_outgoing + 1 - int(incoming_selected) - sink_mask.bit_count()
                if ordinary_count < 0:
                    continue
                for repair_index in range(len(core["minimum_repairs"])):
                    for counts in weak_compositions(ordinary_count, len(core["segments"])):
                        provenance, selected_labels, dummy_roles = build_target_completion(
                            core,
                            selected_outgoing,
                            incoming_selected,
                            sink_mask,
                            repair_index,
                            counts,
                        )
                        key = canonical_json(provenance)
                        value = (selected_labels, dummy_roles)
                        if key in universe:
                            require(universe[key] == value, f"inconsistent duplicate target provenance {key}")
                        universe[key] = value
    return universe


def source_selected_labels(core: dict[str, Any], provenance: list[Any]) -> list[str]:
    words = provenance[2]
    tokens = [token for word in words for token in word]
    probes = sorted((token for token in tokens if token.startswith("P_")), key=lambda x: int(x[2:]))
    repairs = sorted(
        (token for token in tokens if token.startswith("Q_REPAIR_")),
        key=lambda x: int(x.rsplit("_", 1)[1]),
    )
    require(len(repairs) == int(core["minimum_repair_size"]), "source repair-label count mismatch")
    labels = probes + repairs
    labels.extend(f"Q_SINK_{index}" for index in range(sink_count(core)))
    labels.append("INCOMING")
    return labels


def normalize_relation(root_case: dict[str, Any]) -> dict[str, Any]:
    """Canonical mathematical key, excluding opaque implementation ids."""

    return {
        "selected_outgoing": root_case["selected_outgoing"],
        "selected_signature_sha256": root_case["selected_signature_sha256"],
        "source_provenance": root_case["source_provenance"],
        "target_provenance": root_case["target_provenance"],
        # The restoration-role order is part of a nonretaining directed root
        # relation.  It must not be collapsed to a target-only topology key.
        "target_dummy_roles": root_case["target_dummy_roles"],
        "target_position_to_label": root_case["target_position_to_label"],
    }


def normalized_inventory_sha256(records: Iterable[dict[str, Any]]) -> str:
    normalized = sorted(canonical_json(normalize_relation(record["root_case"])) for record in records)
    return digest_text("\n".join(normalized) + "\n")


def crosswalk_records(spec: StreamSpec, records: Iterable[dict[str, Any]]) -> Iterator[dict[str, Any]]:
    for record in records:
        normalized = normalize_relation(record["root_case"])
        yield {
            "schema": 1,
            "stream": spec.name,
            "global_root_case_index": record["global_root_case_index"],
            "root_case_id": record["root_case_id"],
            "normalized_relation_sha256": digest_text(canonical_json(normalized)),
            "normalized_relation": normalized,
            "entry_state_ids": record["entry_state_ids"],
        }


def write_crosswalk(path: Path, all_records: list[tuple[StreamSpec, list[dict[str, Any]]]]) -> None:
    """Write a deterministic, complete normalized root crosswalk."""

    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("wb") as raw:
        with gzip.GzipFile(filename="", mode="wb", fileobj=raw, mtime=0) as zipped:
            with io.TextIOWrapper(zipped, encoding="utf-8", newline="\n") as text:
                for spec, records in all_records:
                    for record in crosswalk_records(spec, records):
                        text.write(canonical_json(record))
                        text.write("\n")


def validate_root_records(
    spec: StreamSpec,
    records: list[dict[str, Any]],
    cores: dict[str, dict[str, Any]],
    *,
    enforce_fixed_commitments: bool = True,
) -> dict[str, Any]:
    require(len(records) == spec.expected_records, f"{spec.name}: record count {len(records)} != {spec.expected_records}")
    source_universe = generate_source_supports(cores, spec.selected_outgoing, spec.allowed_source_cores)
    target_universe = generate_raw_target_universe(cores, spec.selected_outgoing)

    seen_ids: set[str] = set()
    seen_normalized: set[str] = set()
    source_provenance_to_id: dict[str, str] = {}
    target_provenance_to_id: dict[str, str] = {}
    source_id_to_provenance: dict[str, str] = {}
    target_id_to_provenance: dict[str, str] = {}
    source_id_to_signature: dict[str, str] = {}

    for expected_index, record in enumerate(records):
        require(record.get("schema") == 1, f"{spec.name}:{expected_index}: root stream schema")
        require(record.get("global_root_case_index") == expected_index, f"{spec.name}: noncontiguous root index {expected_index}")
        root_case = record.get("root_case")
        require(isinstance(root_case, dict), f"{spec.name}:{expected_index}: missing root_case")
        root_case_id = record.get("root_case_id")
        require(root_case_id == digest_text(canonical_json(root_case)), f"{spec.name}:{expected_index}: root_case_id mismatch")
        require(root_case_id not in seen_ids, f"{spec.name}: duplicate root id {root_case_id}")
        seen_ids.add(root_case_id)

        require(root_case["selected_outgoing"] == spec.selected_outgoing, f"{spec.name}:{root_case_id}: selected_outgoing")
        source_provenance = root_case["source_provenance"]
        source_key = canonical_json(source_provenance)
        require(source_key in source_universe, f"{spec.name}:{root_case_id}: source outside rigid-support grammar")
        source_core_id = source_provenance[0]
        require(source_core_id in spec.allowed_source_cores, f"{spec.name}:{root_case_id}: forbidden source core {source_core_id}")
        source_labels = source_selected_labels(cores[source_core_id], source_provenance)
        require(root_case["source_selected_labels"] == source_labels, f"{spec.name}:{root_case_id}: source labels not derived")
        require(
            root_case["source_position_to_label"] == list(range(spec.selected_outgoing + 1)),
            f"{spec.name}:{root_case_id}: source anchor is not identity",
        )

        target_provenance = root_case["target_provenance"]
        target_key = canonical_json(target_provenance)
        require(target_key in target_universe, f"{spec.name}:{root_case_id}: target outside completion grammar")
        expected_target_labels, expected_dummy_roles = target_universe[target_key]
        require(root_case["target_selected_labels"] == expected_target_labels, f"{spec.name}:{root_case_id}: target selected labels")
        require(
            Counter(root_case["target_dummy_roles"]) == Counter(expected_dummy_roles)
            and len(root_case["target_dummy_roles"]) == len(expected_dummy_roles),
            f"{spec.name}:{root_case_id}: target dummy-role multiset",
        )
        require(root_case["target_incoming_selected"] is target_provenance[-1], f"{spec.name}:{root_case_id}: incoming mode mismatch")

        transport = root_case["target_position_to_label"]
        expected_positions = list(range(spec.selected_outgoing + 1))
        require(sorted(transport) == expected_positions, f"{spec.name}:{root_case_id}: port transport is not a permutation")
        require(len(root_case["target_selected_labels"]) == spec.selected_outgoing + 1, f"{spec.name}:{root_case_id}: target arity")

        reconstructed = {
            "selected_outgoing": spec.selected_outgoing,
            "selected_signature_sha256": root_case["selected_signature_sha256"],
            "source_position_to_label": expected_positions,
            "source_primitive_id": root_case["source_primitive_id"],
            "source_provenance": source_provenance,
            "source_selected_labels": source_labels,
            # The hard-cover root fixes a restoration-role order.  Its
            # admissible role multiset is regenerated above; the order itself
            # is retained as part of the decorated directed relation.
            "target_dummy_roles": root_case["target_dummy_roles"],
            "target_incoming_selected": target_provenance[-1],
            "target_position_to_label": transport,
            "target_primitive_id": root_case["target_primitive_id"],
            "target_provenance": target_provenance,
            "target_selected_labels": expected_target_labels,
        }
        require(reconstructed == root_case, f"{spec.name}:{root_case_id}: full regenerated root_case differs")

        normalized_key = canonical_json(normalize_relation(root_case))
        require(normalized_key not in seen_normalized, f"{spec.name}: duplicate mathematical root relation")
        seen_normalized.add(normalized_key)

        functional_pairs = (
            (source_provenance_to_id, source_key, root_case["source_primitive_id"], "source provenance->id"),
            (target_provenance_to_id, target_key, root_case["target_primitive_id"], "target provenance->id"),
            (source_id_to_provenance, root_case["source_primitive_id"], source_key, "source id->provenance"),
            (target_id_to_provenance, root_case["target_primitive_id"], target_key, "target id->provenance"),
            (source_id_to_signature, root_case["source_primitive_id"], root_case["selected_signature_sha256"], "source id->signature"),
        )
        for mapping, key, value, label in functional_pairs:
            if key in mapping:
                require(mapping[key] == value, f"{spec.name}:{root_case_id}: nonfunctional {label}")
            mapping[key] = value

        entries = record.get("entry_state_ids")
        require(isinstance(entries, list) and entries == sorted(set(entries)), f"{spec.name}:{root_case_id}: bad entry-state list")

    require(seen_ids == set(sorted(seen_ids)), "internal id-set failure")
    require([record["root_case_id"] for record in records] == sorted(seen_ids), f"{spec.name}: roots are not id-sorted")
    observed_sources = {canonical_json(record["root_case"]["source_provenance"]) for record in records}
    require(observed_sources == source_universe, f"{spec.name}: frozen source support inventory differs from regenerated grammar")

    normalized_sha = normalized_inventory_sha256(records)
    if enforce_fixed_commitments and not spec.expected_normalized_sha256.startswith("TO_BE_FILLED"):
        require(normalized_sha == spec.expected_normalized_sha256, f"{spec.name}: normalized inventory commitment mismatch")

    return {
        "records": len(records),
        "source_supports": len(source_universe),
        "target_raw_grammar": len(target_universe),
        "target_provenances_used": len(target_provenance_to_id),
        "selected_signatures": len(set(source_id_to_signature.values())),
        "normalized_sha256": normalized_sha,
    }


def validate_relation_forest(spec: StreamSpec, roots: list[dict[str, Any]]) -> dict[str, int]:
    expected_entries = {record["root_case_id"]: set(record["entry_state_ids"]) for record in roots}
    states_by_root: dict[str, set[str]] = defaultdict(set)
    children_by_root: dict[str, set[str]] = defaultdict(set)
    relation_count = 0
    for record in iter_jsonl_gz(spec.relation_path):
        relation_count += 1
        root_case_id = record.get("fixed_full_root_case_id")
        require(root_case_id in expected_entries, f"{spec.name}: relation points to unknown root {root_case_id}")
        state_id = record.get("state_id")
        require(isinstance(state_id, str), f"{spec.name}: relation without state id")
        require(state_id not in states_by_root[root_case_id], f"{spec.name}: duplicate state {state_id}")
        states_by_root[root_case_id].add(state_id)
        children = record.get("children")
        require(isinstance(children, list), f"{spec.name}:{state_id}: children is not a list")
        children_by_root[root_case_id].update(children)
        for raw in record.get("raw_coverage", []):
            require(raw.get("root_case_id") == root_case_id, f"{spec.name}:{state_id}: raw coverage changes root key")

    require(set(states_by_root) == set(expected_entries), f"{spec.name}: relation forest omits a root")
    for root_case_id, states in states_by_root.items():
        dangling = children_by_root[root_case_id] - states
        require(not dangling, f"{spec.name}:{root_case_id}: dangling child states")
        actual_entries = states - children_by_root[root_case_id]
        require(actual_entries == expected_entries[root_case_id], f"{spec.name}:{root_case_id}: entry-state roots mismatch")
    return {"relations": relation_count, "root_forests": len(states_by_root)}


def run_one(
    spec: StreamSpec,
    cores: dict[str, dict[str, Any]],
    *,
    records_override: list[dict[str, Any]] | None = None,
    enforce_fixed_commitments: bool = True,
    check_relation_forest: bool = True,
) -> dict[str, Any]:
    if records_override is None:
        stream_sha = decompressed_sha256(spec.root_path)
        require(stream_sha == spec.expected_decompressed_sha256, f"{spec.name}: frozen root stream hash mismatch")
        roots = list(iter_jsonl_gz(spec.root_path))
    else:
        roots = records_override
        stream_sha = "IN_MEMORY_MUTATION"
    summary = validate_root_records(
        spec,
        roots,
        cores,
        enforce_fixed_commitments=enforce_fixed_commitments,
    )
    if check_relation_forest and records_override is None:
        summary.update(validate_relation_forest(spec, roots))
    summary["decompressed_stream_sha256"] = stream_sha
    return summary


def expect_rejection(label: str, action: Any) -> str:
    try:
        action()
    except VerificationError as exc:
        return f"PASS {label}: rejected ({exc})"
    raise VerificationError(f"mutation was accepted: {label}")


def run_mutations(cores: dict[str, dict[str, Any]]) -> list[str]:
    n3, n4 = SPECS
    n3_records = list(iter_jsonl_gz(n3.root_path))
    n4_records = list(iter_jsonl_gz(n4.root_path))
    transcript: list[str] = []

    omitted_core = copy.deepcopy(cores)
    del omitted_core["theta-3"]
    transcript.append(
        expect_rejection(
            "omitted primitive core",
            lambda: run_one(n3, omitted_core, records_override=copy.deepcopy(n3_records), enforce_fixed_commitments=False, check_relation_forest=False),
        )
    )

    omitted_repair = copy.deepcopy(cores)
    omitted_repair["theta-2"]["minimum_repairs"] = omitted_repair["theta-2"]["minimum_repairs"][:-1]
    transcript.append(
        expect_rejection(
            "omitted minimum repair",
            lambda: run_one(n4, omitted_repair, records_override=copy.deepcopy(n4_records), enforce_fixed_commitments=False, check_relation_forest=False),
        )
    )

    altered_incoming = copy.deepcopy(n3_records)
    target = altered_incoming[0]["root_case"]
    target["target_incoming_selected"] = not target["target_incoming_selected"]
    target_id = digest_text(canonical_json(target))
    altered_incoming[0]["root_case_id"] = target_id
    transcript.append(
        expect_rejection(
            "altered incoming role",
            lambda: run_one(n3, cores, records_override=altered_incoming, enforce_fixed_commitments=False, check_relation_forest=False),
        )
    )

    altered_transport = copy.deepcopy(n3_records)
    target = altered_transport[0]["root_case"]
    # Preserve bijectivity: this is a genuinely different relative port
    # correspondence, not merely malformed data.
    target["target_position_to_label"][0], target["target_position_to_label"][1] = (
        target["target_position_to_label"][1],
        target["target_position_to_label"][0],
    )
    altered_transport[0]["root_case_id"] = digest_text(canonical_json(target))
    altered_transport.sort(key=lambda record: record["root_case_id"])
    for index, record in enumerate(altered_transport):
        record["global_root_case_index"] = index
    transcript.append(
        expect_rejection(
            "altered port transport",
            lambda: run_one(n3, cores, records_override=altered_transport, enforce_fixed_commitments=True, check_relation_forest=False),
        )
    )

    altered_restoration = copy.deepcopy(n3_records)
    restoration_target = next(
        record["root_case"] for record in altered_restoration if len(record["root_case"]["target_dummy_roles"]) >= 2
    )
    restoration_target["target_dummy_roles"][0], restoration_target["target_dummy_roles"][1] = (
        restoration_target["target_dummy_roles"][1],
        restoration_target["target_dummy_roles"][0],
    )
    restoration_record = next(record for record in altered_restoration if record["root_case"] is restoration_target)
    restoration_record["root_case_id"] = digest_text(canonical_json(restoration_target))
    altered_restoration.sort(key=lambda record: record["root_case_id"])
    for index, record in enumerate(altered_restoration):
        record["global_root_case_index"] = index
    transcript.append(
        expect_rejection(
            "altered nonretaining restoration order",
            lambda: run_one(n3, cores, records_override=altered_restoration, enforce_fixed_commitments=True, check_relation_forest=False),
        )
    )

    duplicate = copy.deepcopy(n4_records)
    duplicate.append(copy.deepcopy(duplicate[-1]))
    transcript.append(
        expect_rejection(
            "duplicated root",
            lambda: run_one(n4, cores, records_override=duplicate, enforce_fixed_commitments=False, check_relation_forest=False),
        )
    )

    deleted = copy.deepcopy(n4_records[:-1])
    transcript.append(
        expect_rejection(
            "deleted root",
            lambda: run_one(n4, cores, records_override=deleted, enforce_fixed_commitments=False, check_relation_forest=False),
        )
    )
    return transcript


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--mutations", action="store_true", help="run mandatory in-memory mutation tests")
    parser.add_argument("--print-commitments", action="store_true", help="print regenerated normalized hashes")
    parser.add_argument(
        "--write-crosswalk",
        type=Path,
        help="write the complete deterministic normalized root crosswalk to this gzip path",
    )
    args = parser.parse_args(argv)

    cores = load_cores()
    summaries: dict[str, Any] = {}
    all_records: list[tuple[StreamSpec, list[dict[str, Any]]]] = []
    for spec in SPECS:
        records = list(iter_jsonl_gz(spec.root_path))
        all_records.append((spec, records))
        summaries[spec.name] = run_one(spec, cores, records_override=None)
    print("VERIFIED fixed-full inventory grammar and frozen root streams")
    print(json.dumps(summaries, indent=2, sort_keys=True))
    if args.print_commitments:
        for name, summary in summaries.items():
            print(f"COMMITMENT {name} {summary['normalized_sha256']}")
    if args.write_crosswalk:
        output_path = args.write_crosswalk
        if not output_path.is_absolute():
            output_path = Path.cwd() / output_path
        write_crosswalk(output_path, all_records)
        print(
            f"WROTE crosswalk {output_path} "
            f"records={sum(len(records) for _, records in all_records)} "
            f"sha256={hashlib.sha256(output_path.read_bytes()).hexdigest()}"
        )
    if args.mutations:
        for line in run_mutations(cores):
            print(line)
        print("VERIFIED all mandatory inventory mutations rejected")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except VerificationError as exc:
        print(f"FALSE: {exc}", file=sys.stderr)
        raise SystemExit(1)
