#!/usr/bin/env python3
"""Independent finite controls. No formal verification of analytic theorems."""
from fractions import Fraction
from hashlib import sha256
from math import comb
from pathlib import Path
import json
import subprocess
import sys

F = Fraction
artifacts = Path(__file__).resolve().parents[1] / "artifacts"
manifest = artifacts / "SHA256SUMS"
expected_manifest = "7e8014501eac1508b685c502304b8d502711d99ad87c8e25c9966041b0d4cb0b"
assert sha256(manifest.read_bytes()).hexdigest() == expected_manifest
checked_files = []
for entry in manifest.read_text().splitlines():
    digest, filename = entry.split(maxsplit=1)
    assert "/" not in filename and filename not in (".", "..")
    assert sha256((artifacts / filename).read_bytes()).hexdigest() == digest
    checked_files.append(filename)

run = subprocess.run(
    [sys.executable, str(artifacts / "verify.py")],
    cwd=artifacts, check=True, capture_output=True, text=True,
)
assert run.stdout == (artifacts / "verification.json").read_text()

# Independent coefficient multiplication in Q(sqrt(2)).
def quadratic_product(a, b):
    terms = [F(0), F(0), F(0)]
    for i, x in enumerate(a):
        for j, y in enumerate(b):
            terms[i + j] += x * y
    return (terms[0] + 2 * terms[2], terms[1])

beta = quadratic_product((-1, 1), (-1, 1))
assert beta == (3, -2)
assert quadratic_product(beta, (3, 2)) == (1, 0)
assert tuple(2 * (x / 2) for x in beta) == beta
assert F(707, 500) ** 2 < 2 < F(283, 200) ** 2
assert 3 - 2 * F(283, 200) == F(17, 100) > 0

# Check every coefficient of the finite Abel identity for each test length.
abel_coefficients = 0
for n in range(1, 65):
    alpha = [F(1, k * k) for k in range(1, n + 1)]
    for j in range(n):
        coefficient = alpha[-1] + sum(
            (alpha[k] - alpha[k + 1] for k in range(j, n - 1)), F(0)
        )
        assert coefficient == alpha[j]
        abel_coefficients += 1
    terminal = n * alpha[-1]
    assert terminal + sum(
        ((k + 1) * (alpha[k] - alpha[k + 1]) for k in range(n - 1)), F(0)
    ) == sum(alpha, F(0))
    x = [F((k % 4) ** 2, k + 1) for k in range(1, n + 1)]
    partial = []
    for value in x:
        partial.append(value + (partial[-1] if partial else F(0)))
    bound = max(value / (k + 1) for k, value in enumerate(partial))
    assert sum((a * value for a, value in zip(alpha, x)), F(0)) <= bound * sum(alpha, F(0))

# Negative control: a linear partial-sum bound alone does not allow rising weights.
x_bad, alpha_bad = (F(0), F(2)), (F(0), F(1))
assert sum(a * x for a, x in zip(alpha_bad, x_bad)) > sum(alpha_bad)
# Negative control: coefficient-modulus differences cannot be replaced by
# complex differences in the theorem's conclusion.
assert (abs(-1) - abs(1)) ** 2 == 0
assert abs(-1 - 1) ** 2 == 4

# Log(F(z)/z) = 2 log(phi(z)): low-degree normalization controls.
normalization_cases = 0
for b in (F(-2, 3), F(0), F(3, 5)):
    for c in (F(-1, 4), F(0), F(7, 8)):
        phi_log = (b, c - b * b / 2)
        square_log = (2 * b, b * b + 2 * c - (2 * b) ** 2 / 2)
        assert square_log == tuple(2 * x for x in phi_log)
        normalization_cases += 1

# Coefficients generated by (1-t) p'(t) = p(t)/2, p(0)=1.
a = [F(1)]
for m in range(160):
    a.append(a[-1] * (F(m) + F(1, 2)) / (m + 1))
for m, value in enumerate(a):
    assert value == F(comb(2 * m, m), 4 ** m)
    if m:
        assert value * value >= F(1, 4 * m)
    assert (2 * m + 1) ** 2 - 4 * m * (m + 1) == 1
b = [a[k // 2] if k % 2 == 0 else F(0) for k in range(322)]
d = [abs(b[k]) - abs(b[k - 1]) for k in range(1, len(b))]
assert d[0] == -1
for m in range(1, 161):
    assert d[2 * m - 1:2 * m + 1] == [a[m], -a[m]]
    assert sum((x * x for x in d[:2 * m + 1]), F(0)) == 1 + 2 * sum(
        (x * x for x in a[1:m + 1]), F(0)
    )

# Exact finite controls for the constants in the radial argument.
for j in range(1, 20):
    r = F(j, 20)
    finite_log = sum((r ** (2 * k) / k for k in range(1, 41)), F(0))
    assert finite_log <= r * r / (1 - r * r) <= r / (2 * (1 - r))
for n in range(1, 201):
    radius = 1 - F(1, 2 * n)
    coefficient = F(17, 2) / (radius ** (2 * n - 1) * (1 - radius) * n)
    assert coefficient == 17 * F(2 * n, 2 * n - 1) ** (2 * n - 1)
    assert coefficient < 50

print(json.dumps({
    "all_controls_passed": True,
    "reviewed_manifest_sha256": expected_manifest,
    "reviewed_artifact_count": len(checked_files),
    "supplied_verifier_stdout_matches_saved_json_exactly": True,
    "arithmetic": "exact integers and fractions",
    "beta_positive_lower_bound": "17/100",
    "abel_identity_coefficients_checked": abel_coefficients,
    "abel_test_lengths": 64,
    "increasing_weight_negative_control_detected": True,
    "complex_difference_negative_control_detected": True,
    "log_normalization_cases": normalization_cases,
    "endpoint_recurrence_steps": 160,
    "endpoint_partial_sum_cases": 160,
    "radial_series_bound_cases": 19,
    "radius_constant_cases": 200,
    "analytic_theorem_formally_verified": False,
    "infinite_convergence_proved_by_finite_controls": False,
}, indent=2, sort_keys=True))
