from pathlib import Path
import datetime,difflib,hashlib,json,os,shutil
A=Path(__file__).resolve().parent; O=A/'repaired_diagnostics_v1'; N=A/'repaired_diagnostics_v2'; N.mkdir(exist_ok=False)
original=(O/'PROOF.md').read_text()
old_header='**30003997 / OWR-16633-014. Complete proof candidate; independent review pending.** One reduction family. The proof uses destination-dependent costs in \\(\\{0,1\\}\\) on a four-layer directed acyclic graph. It also gives a strictly positive \\(\\{1,2\\}\\)-cost version. Historical priority is not established; no novelty claim is made.'
new_header='**30003997 / OWR-16633-014. Mathematical audit verified; prior hardness corollary identified.** The original one-family reduction and its one-entry 1/5 ledger are preserved. The direct 3SAT proof below uses destination-dependent costs in \\(\\{0,1\\}\\) on a four-layer directed acyclic graph and gives a strictly positive \\(\\{1,2\\}\\)-cost version. The advertised hardness bundle follows from a published 2022 construction; no substantive novelty is established. The exact minimum-unsatisfied-clause identity is verified, while its exact historical priority remains unresolved.'
old_priority='The classical input theorem is 3SAT\'s NP-completeness, credited to the standard Cook–Karp reduction framework. A bounded search of the exact source, title and destination-dependent path-cost terminology did not identify a prior proof of this precise restricted statement. That does not establish historical novelty.'
new_priority='The classical input theorem is 3SAT\'s NP-completeness, credited to the standard Cook–Karp reduction framework. The completed priority audit identified Chapoullié–Szigeti, *On packing time-respecting arborescences*, Discrete Optimization45(2022),100702, DOI10.1016/j.disopt.2022.100702, Theorem13 and its full proof on printed pp.11–12. Subdividing its colored parallel root options and charging each sink destination for the incompatible first arc recovers every advertised hardness restriction here, including the positive-cost offset. This is an explicit elementary corollary, not identical printed cost-table wording. The [checkable comparison](../root_priority_20261006/ROOT_PRIOR_THEOREM_COMPARISON.md) states the complete transformation and the distinct-pair notation convention. Earliest priority is not claimed. Identity(7) remains a verified explanatory correspondence whose exact historical priority is unresolved; no separate consequential optimization or approximation theorem is claimed.'
if original.count(old_header)!=1 or original.count(old_priority)!=1:raise RuntimeError('unexpected existing proof metadata')
current=original.replace(old_header,new_header).replace(old_priority,new_priority)
(N/'PROOF.md').write_text(current)
for f in ['verify.py','independent_checks.py']:shutil.copyfile(O/f,N/f)
(N/'priority_metadata_update.diff').write_text(''.join(difflib.unified_diff(original.splitlines(keepends=True),current.splitlines(keepends=True),fromfile='dated-math-gate-v1/PROOF.md',tofile='current-prior-assessment-v2/PROOF.md')))
(N/'REPAIR_NOTES.md').write_text('# Current effective audited package\n\nThe immutable submitted attempt is unchanged. Version1 is the dated mathematical-gate snapshot, with the explicit preprocessing and exception-guard repairs. Version2 changes only the review header and the historical-priority paragraph to record the verified prior hardness corollary and the qualified exact-identity finding. All mathematical sections and both checker files are unchanged from version1. Fresh actual normal/optimized receipts are regenerated for this version; no proof-search turn is added. This is a preserved audit package, not a publication or a merged source PR.\n')
script=(A/'validate_repaired_diagnostics_v2.py').read_text().replace("D=A/'repaired_diagnostics_validation_v2_20261006'","D=A/'effective_prior_package_v2_validation_20261006'").replace("R=A/'repaired_diagnostics_v1'","R=A/'repaired_diagnostics_v2'")
(A/'validate_effective_prior_package_v2.py').write_text(script)
def pin(p):
 b=p.read_bytes();return {'file':str(p.relative_to(A)),'bytes':len(b),'sha256':hashlib.sha256(b).hexdigest()}
r={'UTC':datetime.datetime.now(datetime.timezone.utc).isoformat(),'actual_operator_PID':os.getpid(),'metadata_only_priority_update':True,'mathematical_reduction_unchanged':True,'checker_bytes_unchanged':True,'original_archive_unchanged':True,'proof_search_turns_added':0,'current_package':'repaired_diagnostics_v2','dated_snapshot':'repaired_diagnostics_v1','pins':[pin(p) for p in N.iterdir() if p.is_file()]}
(A/'EFFECTIVE_PRIOR_PACKAGE_V2_PROPAGATION_20261006.json').write_text(json.dumps(r,indent=2)+'\n')
print(json.dumps(r))
