"""SOURCE packet assembly and static validation only; never imports/runs integration helper."""
import ast, datetime as dt, hashlib, json, os, stat, sys
from pathlib import Path
def sha(b):return hashlib.sha256(b).hexdigest()
def jb(x):return (json.dumps(x,ensure_ascii=False,sort_keys=True,indent=2)+'\n').encode()
def must(ok,m):
 if not ok:raise RuntimeError(m)
def main():
 own=Path(__file__).resolve().parent;audit=own.parent;repo=own.parents[3];started=dt.datetime.now(dt.timezone.utc).isoformat()
 def pin(p):
  p=p.resolve();p.relative_to(repo);return {'path':p.relative_to(repo).as_posix(),'sha256':sha(p.read_bytes())}
 def custody(p):
  r=json.loads(p.read_bytes())['files'];items=[dict(v,path=k) for k,v in r.items()] if isinstance(r,dict) else r
  for x in items:
   f=Path(x['path']);f=f if f.is_absolute() else p.parent/f;f.resolve().relative_to(p.parent);b=f.read_bytes();m=x.get('full_mode_07777',x.get('full_mode',x.get('mode')));m=int(m,8) if isinstance(m,str) else m
   must(len(b)==x['bytes'] and sha(b)==x['sha256'] and stat.S_IMODE(f.stat().st_mode)==m,'Frozen custody differs')
  return {'index':pin(p),'exact_member_count':len(items),'all_bodies_sizes_and_modes_verified':True}
 helper=own/'integrate_published_result.py';source=helper.read_bytes();parsed=ast.parse(source,filename=str(helper));compile(parsed,str(helper),'exec')
 constants={}
 for n in parsed.body:
  if isinstance(n,ast.Assign) and len(n.targets)==1 and isinstance(n.targets[0],ast.Name) and n.targets[0].id in ['CLAIM','HEAD','ID','CODE']:
   constants[n.targets[0].id]=ast.literal_eval(n.value)
 must(constants['HEAD']=='4ecc453d6f9ec2e64cdb2d4b41c018fffbe85b29' and constants['ID']=='30003354','Helper constants differ')
 auth=json.loads((audit/'original_preparation_family/ORIGINAL_AUTHENTICATION.json').read_bytes());inspect=json.loads((own/'READONLY_INSPECTION.json').read_bytes());must(inspect['eligible_at_current_intake'] is True and inspect['all_17_fresh_remote_science_bodies_modes_and_blobs_verified'] is True,'Actual remote source inspection missing')
 final=json.loads((audit/'ROOT_FINAL_PREPRINT_PACKAGE_ADJUDICATION_20261003.json').read_bytes());manifest=audit/'publication_package_v1/zenodo-deposit.json';final_files=[]
 for x in final['exact_publication_files']:
  p=repo/x['path'];b=p.read_bytes();must(len(b)==x['bytes'] and sha(b)==x['sha256'] and stat.S_IMODE(p.stat().st_mode)==x['full_mode'],'Final exact package changed');final_files.append(pin(p))
 must(len(final_files)==6,'Expected six operative preparation artifacts');must(sha(manifest.read_bytes())==final['zenodo_manifest']['sha256'],'Final manifest drift')
 inputs={'schema':'pr57-ordered-publication-operation-source-bindings/v1','prepared_UTC':dt.datetime.now(dt.timezone.utc).isoformat(),'actual_preparer_pid':os.getpid(),'ROOT_authority':False,'helper_executed':False,'PR':57,'reviewed_head':constants['HEAD'],'problem_id':constants['ID'],'problem_code':constants['CODE'],'exact_claim':constants['CLAIM'],'source_revision':inspect['source_revision'],'original_budget':'1/5','new_central_proof_attempts':0,'integration_helper':pin(helper),'actual_readonly_inspection':pin(own/'READONLY_INSPECTION.json'),'ROOT_final_package_adjudication':pin(audit/'ROOT_FINAL_PREPRINT_PACKAGE_ADJUDICATION_20261003.json'),'ROOT_priority_adjudication':pin(audit/'ROOT_PRIORITY_ADJUDICATION_20261003.json'),'ROOT_current_exact_package_readback':pin(audit/'root_ordered_resumption_20261004/EXACT_READY_PACKAGE_READBACK.json'),'original_authentication':pin(audit/'original_preparation_family/ORIGINAL_AUTHENTICATION.json'),'original_custody':pin(audit/'original_preparation_family/SELF_MANIFEST.json'),'current_SOURCE_custody':pin(audit/'current_preparation_family/SOURCE.json'),'priority_custody':pin(audit/'priority_audit_family/SELF_MANIFEST.json'),'manifest':pin(manifest),'clean_reviews':[pin(audit/'preprint_round1_adversary/VERDICT.json'),pin(audit/'preprint_round2_wholepackage_adversary/VERDICT.json')],'review_reports':[pin(audit/'preprint_round1_adversary/REPORT.md'),pin(audit/'preprint_round2_wholepackage_adversary/REPORT.md')],'review_custodies':[pin(audit/'preprint_round1_adversary/SOURCE.json'),pin(audit/'preprint_round2_wholepackage_adversary/SOURCE.json')],'final_artifacts':final_files+[pin(manifest)],'original_upstream_report_field_present':False,'raw_report_key_present':False,'SQL_report_is_NULL':False,'SQL_report_literal':'{}','original_source_record_flat_problem':True,'current_SQL_typed_pair_review_hash':inspect['catalog_review_hash_SQL_typed_pair'],'original_ledger_file':'turns.json','original_status_file_present':False,'original_turns_jsonl_present':False,'all_17_fresh_remote_science':inspect['fresh_remote_science'],'actual_git_writer_window_claimed':False,'actual_publication_claimed':False,'actual_tracker_row_claimed':False}
 out=own/'SOURCE_BINDINGS.json';must(not out.exists(),'SOURCE bindings already exist; preserve');out.write_bytes(jb(inputs))
 cs=[custody(repo/inputs[k]['path']) for k in ['original_custody','current_SOURCE_custody','priority_custody']]+[custody(repo/x['path']) for x in inputs['review_custodies']]
 now=dt.datetime.now(dt.timezone.utc).isoformat();log=('# PR57 ordered publication operations research log\n\n'
       '- 2026-10-04T04:53:57.955548Z — Read-only status-first inspection (actual PID38248) confirmed OPEN draft exact head, literal claimed_solved1/5 and all17 incoming remote body/mode/blob identities. Native queued0/5; no native attempts/state/history. Original source is flat; raw report and original upstream_report field absent, SQL non-NULL TEXT {}. Source operations preparation40%; actual publication/tracker/native execution0% as observed. No new proof attempt.\n'
       '- '+now+' — Prepared guarded exact-head merge and present-day acceptance mirror SOURCE helper; static parse/compile only, no helper execution. Bound current actual ROOT ready-package readback and all exact source/metadata/review artifacts; verified all frozen custody members. Operations source preparation100%; mathematical and bounded-priority audits are existing completed ROOT inputs, not new child review. Real publication/tracker/window/native execution remain ROOT workflow gates, without child authority or completion claim. No native Git/index/ref write, upload, spreadsheet write, PR edit, PDF compile, editor operation or human contact.\n')
 (own/'RESEARCH_LOG.md').write_text(log)
 report=('# PR57 ordered publication operations SOURCE report\n\n'
         'SOURCE-only operations preparation is complete. integrate_published_result.py is unexecuted. Its exact interface is in HELPER_INTERFACE.md; SOURCE_BINDINGS.json pins the operative source, six package artifacts and exact two-file manifest, current ROOT revalidation, original authentication/custody and two separate review rounds. ROOT must personally read this helper and supply actual publication/tracker/final-gate evidence and a genuinely acknowledged exclusive PR57 native-integration window.\n\n'
         'Actual fresh read-only inspection PID38248 at2026-10-04T04:53:57.955548Z authenticated OPEN draft PR57, head4ecc453d6f9ec2e64cdb2d4b41c018fffbe85b29, submitted claimed_solved1/5, all17 complete remote science bodies plus modes/blobs, and exact incoming18-file domain. main and remote were d6bf1f8bd45c786d786a8f2dce3bb4002964ceb1 with the entire index empty and8 unrelated dirty tracked paths. No original commit object was locally available. Native target was queued0/5 with no original attempt paths or target state/history. Those are dated observations and must be freshly checked before mutation.\n\n'
         'PR57 differs from PR50/55 precedent: source_record.json is the flat problem itself; its upstream_report field is absent. Raw selected report key is also absent; SQL selected fallback is non-NULL TEXT {}. No raw or wrapper null is present. The genuine ledger is turns.json, not status.json or turns.jsonl. Its single original turn and budget5 remain unchanged. The current native typed-pair fingerprint is '+inspect['catalog_review_hash_SQL_typed_pair']+'. The hypothetical null-pair digest '+inspect['hypothetical_null_pair_hash_not_original_report']+' is distinct and has no original-report evidentiary authority.\n\n'
         'The helper accepts only the precisely stated finite-integer plane/sphere negative answer, ordinary compact-open metric/map topologies, smooth complete strictly positive-curvature witnesses, and r1 nonlinear correction. It retains bounded priority qualifications, credits classical mechanisms and records extensive AI use/unrefereed status. It claims no RP2, noninteger or smooth-topology result, abstract-homeomorphism obstruction, exhaustive priority guarantee or formal/human-refereed certification. The written universal proof supplies all-r validity;374 finite diagnostics are supplementary.\n\n'
         'The PR title/body files are unsubmitted templates with actual-service placeholders. No PR metadata was changed. No other PR science, especially PR56, was processed. The existing PR50 editor was left untouched; there was no tab opening, compilation or PDF generation.\n\n'
         'The short PR55 intake window observed during inspection is insufficient for PR57 merge. The helper checks an explicit PR57 native-integration pause, pins acknowledged window bytes, requires the whole empty index and frozen foreign dirty path set/bodies/modes, and rechecks preservation before mutation. It imports the original object only within that real window if necessary. The merge changes only the native target queue four cells while retaining every original scientific byte/mode/blob; the mirror adds only current acceptance/result plus one state/history event after actual GitHub exact merge readback. Real commands are serially captured with argv/PID/UTC/exit/streams; failures retain partial state, no recovery mutation and no blind retry.\n\n'
         'Static validation parsed and compiled the helper without importing or executing it; all frozen custody sizes/hashes/modes and operative package hashes were checked. This establishes source consistency, not ROOT authority or a new mathematical verdict. At this checkpoint source preparation is100%; child-executed publication/tracker/native integration is0%.\n')
 (own/'REPORT.md').write_text(report)
 readiness={'schema':'pr57-ordered-publication-operations-SOURCE-readiness/v1','UTC':now,'actual_builder_pid':os.getpid(),'status':'SOURCE_READY_FOR_ROOT_FULL_READ','source_only':True,'ROOT_authority':False,'helper_executed':False,'source_bindings':pin(out),'integration_helper':pin(helper),'actual_readonly_inspection':pin(own/'READONLY_INSPECTION.json'),'static_AST_parse_and_compile':True,'no_integration_import_or_execution':True,'custody_checks':cs,'operations_preparation_percent':100,'child_publication_tracker_native_execution_percent':0,'actual_PR57_window_acquired':False,'old_frozen_packets_mutated':False,'native_Git_index_ref_PR_Zenodo_tracker_mutation':False,'human_contact':False,'editor_or_PDF_compilation_operation':False,'new_central_proof_attempts':0,'original_budget':'1/5','strongest_verified_result':constants['CLAIM'],'remaining':'ROOT full helper review, actual repository-kit upload and intended metadata/public bytes checks, GWS tracker append/readback, actual exclusive PR57 window, actual exact merge/mirror and owned checkpoint.'}
 (own/'READINESS.json').write_bytes(jb(readiness))
 record={'schema':'pr57-SOURCE-build-and-static-check/v1','actual_pid':os.getpid(),'actual_argv':sys.argv,'started_UTC':started,'finished_UTC':dt.datetime.now(dt.timezone.utc).isoformat(),'helper_pin':pin(helper),'AST_parse_and_compile':True,'helper_imported_or_executed':False,'custody_checks':cs,'mutation_scope':'Only new ordered_publication_operations_20261004 SOURCE packet','source_build_complete':True};(own/'SOURCE_BUILD_RECORD.json').write_bytes(jb(record))
 print(json.dumps({'status':readiness['status'],'helper':pin(helper),'source_bindings':pin(out),'all_frozen_custody_member_count':sum(x['exact_member_count'] for x in cs),'operations_preparation_percent':100,'helper_executed':False},indent=2))
if __name__=='__main__':main()
