#!/usr/bin/env python3
"""Exact replay of the target-174/record-60 cyclic nine-minor certificate.

The target descriptor is rebuilt from the frozen graph signatures.  Nine
2-by-2 minors in the zero-character Fourier block are divided only by their
strictly positive monomial factors.  Their reduced coefficient dictionaries
are compared with the closed formulas F_s and E_st below.  Two further sparse
polynomial identities eliminate the E_st and give the cyclic ratio
obstruction.
"""

from __future__ import annotations

import collections
import json
from pathlib import Path

import search_simplex_homogeneous as audit


HERE = Path(__file__).resolve().parent
REPORT = HERE / "RECORD60_CYCLIC_CERTIFICATE_AUDIT.json"
TARGET_INDEX = 174
SECTOR_NAMES = ("C", "G", "T")
CYCLIC_CASES = (
    # r is the XOR of the two distinct sectors s,t.
    (0, 1, 2),
    (1, 0, 2),
    (2, 0, 1),
)


def sparse_add(*terms):
    """Add (integer multiplier, sparse polynomial) pairs."""
    answer = collections.defaultdict(int)
    for multiplier, polynomial in terms:
        for exponent, coefficient in polynomial.items():
            answer[exponent] += multiplier * coefficient
    return {
        exponent: coefficient
        for exponent, coefficient in answer.items()
        if coefficient
    }


def sparse_mul(*polynomials):
    if not polynomials:
        raise ValueError("at least one polynomial is required")
    answer = polynomials[0]
    for polynomial in polynomials[1:]:
        answer = audit.sparse_mul(answer, polynomial)
    return answer


def variable(width, index):
    exponent = [0] * width
    exponent[index] = 1
    return {tuple(exponent): 1}


def constant(width, value=1):
    return {(0,) * width: value}


def build_closed_form(descriptor, lambda_index=None, b_edge=2):
    """Build F_s, E_st and their named ingredients as sparse polynomials."""
    width = 3 * descriptor.edge_class_count + descriptor.retic_count
    if lambda_index is None:
        lambda_index = 3 * descriptor.edge_class_count
    one = constant(width)
    p = variable(width, lambda_index)
    q = sparse_add((1, one), (-1, p))

    # The four edge triples participating in the normalized minors.
    a = {sector: variable(width, 3 * 0 + sector) for sector in range(3)}
    b = {
        sector: variable(width, 3 * b_edge + sector) for sector in range(3)
    }
    c = {sector: variable(width, 3 * 4 + sector) for sector in range(3)}
    d = {sector: variable(width, 3 * 5 + sector) for sector in range(3)}

    K = {
        sector: sparse_add(
            (1, sparse_mul(p, a[sector], b[sector])),
            (1, sparse_mul(q, c[sector])),
        )
        for sector in range(3)
    }
    L = {
        sector: sparse_add(
            (1, sparse_mul(p, a[sector])),
            (1, sparse_mul(q, b[sector], c[sector])),
        )
        for sector in range(3)
    }
    F = {
        sector: sparse_add(
            (1, b[sector]),
            (-1, sparse_mul(d[sector], d[sector], K[sector], L[sector])),
        )
        for sector in range(3)
    }

    M = {}
    E = {}
    for s in range(3):
        for t in range(3):
            if s == t:
                continue
            r = ((s + 1) ^ (t + 1)) - 1
            M[s, t] = sparse_add(
                (1, sparse_mul(p, b[s], a[r])),
                (1, sparse_mul(q, b[t], c[r])),
            )
            E[s, t] = sparse_add(
                (1, sparse_mul(d[r], M[s, t])),
                (-1, sparse_mul(d[s], d[t], K[s], L[t])),
            )

    return {
        "width": width,
        "one": one,
        "p": p,
        "q": q,
        "a": a,
        "b": b,
        "c": c,
        "d": d,
        "K": K,
        "L": L,
        "F": F,
        "M": M,
        "E": E,
    }


def extract_reduced_minor(
    sparse_outputs, coordinate_index, character_sum, rows, columns
):
    full, coordinates = audit.minor_polynomial(
        sparse_outputs, coordinate_index, character_sum, rows, columns
    )
    common, reduced = audit.factor_positive_monomial(full)
    return {
        "full": full,
        "coordinates": coordinates,
        "common": common,
        "reduced": reduced,
    }


def digest_record(polynomial):
    return {
        "term_count": len(polynomial),
        "sha256": audit.polynomial_digest(polynomial),
    }


def consequence_records(closed):
    records = []
    for r, s, t in CYCLIC_CASES:
        b = closed["b"]
        d = closed["d"]
        F = closed["F"]
        E = closed["E"]
        K = closed["K"]
        L = closed["L"]
        M = closed["M"]

        C = sparse_add(
            (1, sparse_mul(d[r], d[r], M[s, t], M[t, s])),
            (-1, sparse_mul(b[s], b[t])),
        )
        # C is in the ideal generated by F_s,F_t,E_st,E_ts.  This is
        # coefficient-dictionary equality, not division or a numerical test.
        cross_combination = sparse_add(
            (1, sparse_mul(E[s, t], d[r], M[t, s])),
            (1, sparse_mul(d[s], d[t], K[s], L[t], E[t, s])),
            (-1, sparse_mul(b[s], F[t])),
            (-1, sparse_mul(b[t], F[s])),
            (1, sparse_mul(F[s], F[t])),
        )
        if C != cross_combination:
            raise AssertionError((r, "cross consequence identity"))

        factor_one = sparse_add(
            (1, b[t]), (-1, sparse_mul(b[s], b[r]))
        )
        factor_two = sparse_add(
            (1, sparse_mul(b[t], b[r])), (-1, b[s])
        )
        final_lhs = sparse_add(
            (1, sparse_mul(b[r], C)),
            (1, sparse_mul(b[s], b[t], F[r])),
        )
        final_rhs = sparse_mul(
            d[r],
            d[r],
            closed["p"],
            closed["q"],
            closed["a"][r],
            closed["c"][r],
            factor_one,
            factor_two,
        )
        if final_lhs != final_rhs:
            raise AssertionError((r, "final factor identity"))

        records.append(
            {
                "r": SECTOR_NAMES[r],
                "s": SECTOR_NAMES[s],
                "t": SECTOR_NAMES[t],
                "cross_consequence": digest_record(C),
                "cross_combination": digest_record(cross_combination),
                "cross_identity": (
                    "C_r = E_st*d_r*M_ts + d_s*d_t*K_s*L_t*E_ts "
                    "- b_s*F_t - b_t*F_s + F_s*F_t"
                ),
                "factor_polynomial": digest_record(final_lhs),
                "factor_identity": (
                    "b_r*C_r + b_s*b_t*F_r = "
                    "d_r^2*p*(1-p)*a_r*c_r"
                    "*(b_t-b_s*b_r)*(b_t*b_r-b_s)"
                ),
                "coefficient_dictionary_equalities": True,
            }
        )
    return records


def mutation_tests(
    targets, descriptor, sparse_outputs, coordinate_index, closed, consequences
):
    del consequences
    mutations = []

    def rejected(name, condition):
        if not condition:
            raise AssertionError((name, "mutation unexpectedly accepted"))
        mutations.append({"name": name, "result": "REJECTED"})

    # Wrong graph direction.
    wrong_descriptor = targets[175]["descriptor"]
    wrong_outputs = audit.atlas.output_sparse_polynomials(wrong_descriptor)
    wrong_f = extract_reduced_minor(
        wrong_outputs, coordinate_index, 0, (0, 1), (0, 1)
    )["reduced"]
    rejected("wrong_target_175", wrong_f != closed["F"][0])

    # Wrong Fourier block for the first diagonal minor.
    wrong_block = extract_reduced_minor(
        sparse_outputs, coordinate_index, 1, (0, 1), (0, 1)
    )["reduced"]
    rejected("F_C_wrong_character_sum_1", wrong_block != closed["F"][0])

    wrong_b = build_closed_form(descriptor, b_edge=1)
    rejected("wrong_b_edge_1", wrong_b["F"][0] != closed["F"][0])

    wrong_lambda = build_closed_form(
        descriptor, lambda_index=3 * descriptor.edge_class_count + 1
    )
    rejected("wrong_inheritance_lambda_1", wrong_lambda["F"][0] != closed["F"][0])

    # Ordered E_ST is not the transposed E_TS formula.
    rejected("transpose_E_CG_formula", closed["E"][0, 1] != closed["E"][1, 0])

    wrong_e_block = extract_reduced_minor(
        sparse_outputs, coordinate_index, 1, (0, 1), (0, 2)
    )["reduced"]
    rejected("E_CG_wrong_character_sum_1", wrong_e_block != closed["E"][0, 1])

    # Mutate the two eliminant identities themselves.
    r, s, t = CYCLIC_CASES[0]
    b = closed["b"]
    d = closed["d"]
    F = closed["F"]
    E = closed["E"]
    K = closed["K"]
    L = closed["L"]
    M = closed["M"]
    C = sparse_add(
        (1, sparse_mul(d[r], d[r], M[s, t], M[t, s])),
        (-1, sparse_mul(b[s], b[t])),
    )
    missing_quadratic = sparse_add(
        (1, sparse_mul(E[s, t], d[r], M[t, s])),
        (1, sparse_mul(d[s], d[t], K[s], L[t], E[t, s])),
        (-1, sparse_mul(b[s], F[t])),
        (-1, sparse_mul(b[t], F[s])),
    )
    rejected("omit_F_s_F_t_from_cross_identity", C != missing_quadratic)

    final_lhs = sparse_add(
        (1, sparse_mul(b[r], C)),
        (1, sparse_mul(b[s], b[t], F[r])),
    )
    wrong_factor_one = sparse_add(
        (1, b[t]), (1, sparse_mul(b[s], b[r]))
    )
    correct_factor_two = sparse_add(
        (1, sparse_mul(b[t], b[r])), (-1, b[s])
    )
    wrong_final_rhs = sparse_mul(
        d[r],
        d[r],
        closed["p"],
        closed["q"],
        closed["a"][r],
        closed["c"][r],
        wrong_factor_one,
        correct_factor_two,
    )
    rejected("plus_sign_in_first_ratio_factor", final_lhs != wrong_final_rhs)
    return mutations


def main():
    _, _, _, targets = audit.cross.build_universes()
    target = targets[TARGET_INDEX]
    descriptor = target["descriptor"]
    if target["record_id"] != 60:
        raise AssertionError(target["record_id"])
    sparse_outputs = audit.atlas.output_sparse_polynomials(descriptor)
    coordinate_index = {
        assignment: index
        for index, assignment in enumerate(audit.atlas.k3p_assignments(4))
    }
    closed = build_closed_form(descriptor)

    diagonal_records = []
    for sector in range(3):
        character = sector + 1
        extracted = extract_reduced_minor(
            sparse_outputs,
            coordinate_index,
            0,
            (0, character),
            (0, character),
        )
        if extracted["reduced"] != closed["F"][sector]:
            raise AssertionError((sector, "F formula mismatch"))
        diagonal_records.append(
            {
                "sector": SECTOR_NAMES[sector],
                "character_sum": 0,
                "rows": [0, character],
                "columns": [0, character],
                "coordinate_indices": list(extracted["coordinates"]),
                "full_minor": digest_record(extracted["full"]),
                "positive_monomial_exponent": list(extracted["common"]),
                "reduced_minor": digest_record(extracted["reduced"]),
                "closed_formula": "F_s=b_s-d_s^2*K_s*L_s",
                "coefficient_dictionary_equality": True,
            }
        )

    ordered_cross_records = []
    for s in range(3):
        for t in range(3):
            if s == t:
                continue
            character_s = s + 1
            character_t = t + 1
            r = (character_s ^ character_t) - 1
            extracted = extract_reduced_minor(
                sparse_outputs,
                coordinate_index,
                0,
                (0, character_s),
                (0, character_t),
            )
            if extracted["reduced"] != closed["E"][s, t]:
                raise AssertionError((s, t, "E formula mismatch"))
            ordered_cross_records.append(
                {
                    "s": SECTOR_NAMES[s],
                    "t": SECTOR_NAMES[t],
                    "r_equals_s_xor_t": SECTOR_NAMES[r],
                    "character_sum": 0,
                    "rows": [0, character_s],
                    "columns": [0, character_t],
                    "coordinate_indices": list(extracted["coordinates"]),
                    "full_minor": digest_record(extracted["full"]),
                    "positive_monomial_exponent": list(extracted["common"]),
                    "reduced_minor": digest_record(extracted["reduced"]),
                    "closed_formula": (
                        "E_st=d_r*(p*b_s*a_r+(1-p)*b_t*c_r)"
                        "-d_s*d_t*K_s*L_t"
                    ),
                    "coefficient_dictionary_equality": True,
                }
            )

    consequences = consequence_records(closed)
    mutations = mutation_tests(
        targets,
        descriptor,
        sparse_outputs,
        coordinate_index,
        closed,
        consequences,
    )

    payload = {
        "schema": "k3p-record60-cyclic-nine-minor-audit-v1",
        "status": "PASS",
        "target_index": TARGET_INDEX,
        "record_id": target["record_id"],
        "old_split": target["old_split"],
        "old_order": target["old_order"],
        "descriptor_sha256": audit.cross.digest(
            audit.cross.descriptor_payload(descriptor)
        ),
        "edge_signatures": [list(row) for row in descriptor.edge_signatures],
        "inputs": {
            "frozen_primitive_sha256": audit.sha_file(audit.cross.PRIMITIVE_PATH),
            "crossbridge_compiler_sha256": audit.sha_file(
                audit.PARENT / "explore_crossbridge_atlas.py"
            ),
            "k3p_compiler_sha256": audit.sha_file(audit.cross.ATLAS_PATH),
            "audit_script_sha256": audit.sha_file(Path(__file__).resolve()),
        },
        "notation": {
            "p": "lambda_0",
            "q": "1-lambda_0",
            "a_s": "edge-class 0 spectrum in sector s",
            "b_s": "edge-class 2 spectrum in sector s",
            "c_s": "edge-class 4 spectrum in sector s",
            "d_s": "edge-class 5 spectrum in sector s",
            "K_s": "p*a_s*b_s+(1-p)*c_s",
            "L_s": "p*a_s+(1-p)*b_s*c_s",
        },
        "diagonal_minor_records": diagonal_records,
        "ordered_cross_minor_records": ordered_cross_records,
        "consequence_records": consequences,
        "strict_sign_logic": {
            "minor_division": (
                "Every removed monomial is a product of strict edge spectra "
                "and lambda_1, hence is positive on D3+."
            ),
            "final_prefactor": (
                "d_r^2*p*(1-p)*a_r*c_r is strictly positive because every "
                "edge spectrum and both inheritance branches are strict."
            ),
            "ratio_branches": (
                "For every r with {r,s,t}={C,G,T}, vanishing forces "
                "b_r in {b_t/b_s,b_s/b_t}."
            ),
            "contradiction": (
                "Set B_s=-log(b_s)>0.  The three branches say "
                "B_r=abs(B_t-B_s) for every r.  For an index r with maximal "
                "B_r, the right side is strictly smaller than B_r, impossible."
            ),
            "domain_scope": (
                "Only 0<b_s,a_s,c_s,d_s<1 and 0<p<1 are used; these are "
                "strict consequences of the true principal domain D3+."
            ),
        },
        "flattening_conclusion": (
            "Rank at most four would force all four nonzero Fourier blocks to "
            "have rank one, hence these nine zero-block minors to vanish.  The "
            "cyclic contradiction proves rank greater than four at every "
            "strict D3+ target-174 point."
        ),
        "mutation_tests": mutations,
    }
    REPORT.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n")
    print(
        json.dumps(
            {
                "status": payload["status"],
                "diagonal_identities": len(diagonal_records),
                "ordered_cross_identities": len(ordered_cross_records),
                "cyclic_eliminants": len(consequences),
                "mutations_rejected": len(mutations),
            },
            sort_keys=True,
        )
    )


if __name__ == "__main__":
    main()
