"""Write reviewer-only final findings and retain complete actually used source bodies."""
from pathlib import Path
import difflib, gzip, json, os
from capture import HERE, pin, write, now, digest
A=HERE.parent; F=A/'preprint_package_v02'
def main():
 checkpoint=json.loads((HERE/'INDEPENDENT_RECONSTRUCTION_CHECKPOINT.json').read_text())
 old=HERE/'DERIVATION.md'; before=old.read_bytes()
 assert digest(before)==checkpoint['derivation']['sha256']
 preserved=HERE/'DERIVATION_checkpoint_50.md';preserved.write_bytes(before)
 text=before.decode().replace('epsilon=2^-j/(4d)','epsilon=2^(-j/(4d))').replace('2^-j/2.','2^(-j/2).').replace('2^-3j/4 probability','2^(-3j/4) probability')
 assert text!=before.decode()
 old.write_text(text)
 write(HERE/'DERIVATION_EDITORIAL_RECONCILIATION.json',dict(UTC=now(),actual_recorder_PID=os.getpid(),historical_checkpoint=pin(HERE/'INDEPENDENT_RECONSTRUCTION_CHECKPOINT.json'),historical_original=checkpoint['derivation'],literal_preserved_original=pin(preserved),current_derivation=pin(old),complete_diff=''.join(difflib.unified_diff(before.decode().splitlines(keepends=True),text.splitlines(keepends=True),fromfile='DERIVATION-at-independent50%-checkpoint.md',tofile='DERIVATION-final-explicit-exponents.md')),reason='Only disambiguate three plain-text exponent expressions in reviewer-owned derivation. Candidate formula and mathematical conclusion unchanged. Earlier literal checkpoint remains true for the archived original bytes.',candidate_modified=False))
 auth=json.loads((HERE/'AUTHENTICATION_AND_REPLAY.json').read_text());cross=json.loads((HERE/'EVIDENCE_CROSSCHECK.json').read_text())
 failed=json.loads((HERE/'process_evidence/package_evidence_crosscheck/execution.json').read_text());passed=json.loads((HERE/'process_evidence/package_evidence_crosscheck_v02/execution.json').read_text())
 assert failed['actual_child_PID']==55642 and failed['exit_code']==1 and passed['actual_child_PID']==56459 and passed['exit_code']==0
 write(HERE/'TOOL_CHECK_FAILURES.json',dict(UTC=now(),actual_recorder_PID=os.getpid(),events=[
 dict(kind='preliminary_file_locator',observed_tool_chunk='e5558d',observed_failure='rg emitted missing-directory error for a guessed priority_auxiliary_adversary_01 path; extant target/mechanism files were returned',underlying_rg_missing_path_exit=2,outer_piped_exit_not_asserted=True,actual_PID_unknown=True,complete_native_tape_available=False,qualification='Earlier log called the tool exit2. The missing-directory rg error is established; the rightmost pipeline exit is not independently retained. No candidate or scientific failure.'),
 dict(kind='wrong_primary_scan_suffix',observed_tool_chunk='6ceaa2',observed_exit_code=1,observed_failure='FileNotFoundError for hs-28.png.xz; actual retained page is hs-28.png and was then visually read',actual_PID_unknown=True,complete_native_tape_available=False,correct_actual_body=pin(A/'priority_mechanism_adversary_01/private_sources/hs-28.png')),
 dict(kind='wrong_text_output_locator',observed_exit_code=1,observed_failure='No match in empty native_runs/primary_text_dist6_001/stdout.bin because pdftotext wrote the explicit Grubb_dist6.txt output; actual derivative then read',actual_PID_unknown=True,complete_native_tape_available=False,correct_actual_body=pin(A/'math_spectral_adversary_01/private_primary_sources/Grubb_dist6.txt')),
 dict(kind='first_version_of_this_review_checker',execution=pin(HERE/'process_evidence/package_evidence_crosscheck/execution.json'),actual_PID=55642,exit_code=1,full_source_and_complete_native_streams_retained=True,reason='Historical0644 launch versus same helper frozen0444 mode; distinct corrected checker validates both epochs',corrected_execution=pin(HERE/'process_evidence/package_evidence_crosscheck_v02/execution.json'),corrected_actual_PID=56459,corrected_exit_code=0,correction=pin(HERE/'CHECKER_MODE_CORRECTION.json'),terminology='First reviewer checker in correction means the first version of this second reviewer own helper; it does not mean the first-review agent.'),
 dict(kind='earlier_ROOT_freeze_schema_checker',actual_failed_PID=41183,failed_exit_code=1,actual_local_check_PID=41184,local_check_exit_code=0,corrected_helper_actual_PID=41861,disclosure=pin(F/'ROOT_LOCAL_CHECK_FREEZE_SCHEMA_CORRECTION.json'),qualification='Successful local response had no status key; earlier helper made an unsupported schema assertion. No successful local or scientific check rerun.'),
 dict(kind='fresh_official_final_access',responses=[pin(HERE/n)for n in ['FRESH_CV2011_FINAL_ACCESS_CHECK.json','FRESH_CV2011_CWI_FINAL_LINK_CHECK.json']],observed_failure='Official publisher PDF and CWI final-version links inaccessible through actual web tool',qualification='No theorem-body exclusion or manuscript-to-final identity inferred'),
 dict(kind='fresh_Grubb_url_access',observed_failure='Web open of MN16.pdf returned InternalError; existing retained exact primary body read',complete_web_response_file_retained=False,qualification='This records the observed tool failure only; no full response capture invented'),
 dict(kind='reported_capacity_interruption',observation=pin(HERE/'CONTINUATION_OBSERVATION.json'),precise_outage_bounds_unknown=True,upstream_attestation=False,scientific_checks_repeated=False)
 ],limits='For locator/web failures without a retained raw native tape, only the observed tool result is recorded. No invented PIDs, exact outage duration or reconstructed completed process result. Actual failed reviewer process has full genuine prelaunch bytes/streams.'))
 manifest=json.loads((F/'SECOND_CANDIDATE_MANIFEST.json').read_text());receipt=json.loads((HERE/'fresh_replay/REPLAY_RECEIPT.json').read_text())
 write(HERE/'VERDICT.json',dict(status='PASS_REVISED_SCOPED_THEOREM_AND_COMPLETE_PACKAGE_NO_UNRESOLVED_ISSUES',UTC=now(),actual_recorder_PID=os.getpid(),original_head='eb6e0e999521d84a65f9857d338cad76b84d30db',original_submitted_status='claimed_solved',original_author_turn_count='2/5',candidate_manifest=pin(F/'SECOND_CANDIDATE_MANIFEST.json'),candidate_public_files=23,PDF=pin(F/'spectral_tensor_consistency.pdf'),ZIP=pin(F/'spectral_tensor_verification.zip'),record_metadata=pin(F/'record_metadata.json'),independent_derivation=pin(old),historical_independence_checkpoint=pin(HERE/'INDEPENDENT_RECONSTRUCTION_CHECKPOINT.json'),report=pin(HERE/'REPORT.md'),reading_ledger=pin(HERE/'READ_LEDGER.md'),mandatory_unresolved_issues=[],new_nonmandatory_suggestions=[],earlier_global_clarifications=[dict(id=n,status='CLOSED_GLOBALLY')for n in ['C1','C2','C3','C4']],analytically_verified='Explicit smooth unknown tensor/density, exact stationary fixed-positive-lag conormal model: density C2, interior tensor/divergence local uniform, global projected tensor L2, Borel data estimators; current supplementary regularization route also checks out.',scoped_priority='No contradiction found in independently inspected decisive primary passages; actual inaccessible CV2011 publisher-final and other full-body gaps remain disclosed; bounded dated audit only, no unconditional worldwide firstness.',actual_runner_PID=45361,actual_control_PIDs=[e['native_execution']['actual_child_PID']for e in receipt['native_executions']],all_eight_exit_zero=True,independently_compared_exact_leaves=auth['independently_compared_exact_leaves'],floating_diagnostic_leaves=auth['floating_diagnostic_leaves'],finite_controls_are_not_infinite_theorem_proof=True,all_eight_PDF_pages_visually_inspected=True,reused_existing_actual_render=True,new_compile_or_render_claimed=False,fresh_PDF_extractor_PID=45536,full_byte_crosscheck_count=len(cross['full_byte_checked_pins']),native_build_PIDs=[r['PID']for r in cross['native_build_readbacks']],actual_local_upload_kit_check_PID=41184,local_check_is_not_publication=True,correction_history=pin(HERE/'TOOL_CHECK_FAILURES.json'),candidate_modified=False,external_communication=False,Git_or_PR_or_service_or_tracker_mutated=False,publication_clearance=False,merge_authority=False,human_peer_review=False,custody_limit='Actual native recorder/Popen self-report and retained exact sources/complete streams; no independent upstream clock, OS binary attestation, exhaustive global search or formal proof certificate.'))
 # Archive literal complete inputs, not just selected excerpts or hashes.
 primary=[]
 for name in ['reiss_original','cv2006','cv2011','chen2009_author','gobet','chorowski','nickl','gw2025','abjn']:
  primary.append(A/'priority_target_adversary_01/private_sources'/(name+'.txt'))
 for name in ['bal2013_author','kohn1988','lenzen2004','hansen2008']:
  primary.append(A/'priority_mechanism_adversary_01/private_sources'/(name+'.txt'))
 primary += [A/'math_empirical_adversary_01/grubb_regular_spectral_primary.txt',A/'math_spectral_adversary_01/private_primary_sources/Grubb_dist6.txt',A/'priority_mechanism_adversary_01/private_sources/hs-28.png',*[A/'math_scope_adversary_01'/('reiss-'+str(i)+'.png')for i in [45,46,47]],A/'ROOT_PRIORITY_ADJUDICATION.md',A/'ROOT_FIRST_PREPRINT_REVIEW_ADJUDICATION.json',A/'snapshot_manifest.json',F/'SECOND_CANDIDATE_MANIFEST.json',F/'BUILD_RECEIPT.json',F/'ROOT_NATIVE_EDITOR_COMPILE_ACCEPTANCE.json',F/'GLOBAL_REPAIR_RECEIPT.json',F/'ROOT_LOCAL_CHECK_FREEZE_SCHEMA_CORRECTION.json',A/'preprint_package_v01/AUTHORING_PATH_RECONCILIATION_02.json',A/'frozen_first_preprint_candidate/ARCHIVE_MANIFEST.json',*[A/'preprint_adversary_01'/n for n in ['REPORT.md','DERIVATION.md','VERDICT.json']]]
 selected=dict.fromkeys(primary+[Path(r['path'])for r in manifest['files']]+[Path(r['path'])for r in cross['full_byte_checked_pins']])
 sources=[]; skipped=[]
 for p in selected:
  assert p.is_file(),str(p)
  if p.is_relative_to(HERE):continue # Own complete originals already retained literally.
  if not p.is_relative_to(A):
   skipped.append(dict(input=pin(p),reason='External executable/runtime binary pinned but not redistributed.'))
   continue
  assert not p.is_symlink(),str(p)
  sources.append(p)
 target=HERE/'source_archives';target.mkdir(exist_ok=False)
 rows=[]
 for i,p in enumerate(sources):
  b=p.read_bytes();dest=target/('%04d.bin.gz'%i);dest.write_bytes(gzip.compress(b,mtime=0));assert gzip.decompress(dest.read_bytes())==b
  rows.append(dict(original=pin(p),complete_copy=pin(dest),codec='gzip',logical_bytes=len(b),logical_sha256=digest(b),reading_extent='See READ_LEDGER.md; complete retention is not a whole-body manual-reading claim.'))
 write(HERE/'SOURCE_ARCHIVE_INDEX.json',dict(UTC=now(),actual_recorder_PID=os.getpid(),complete_body_copies=rows,unredistributed_external_binary_anchors=skipped,all_requested_primary_bodies_included=all(any(r['original']['path']==str(p)for r in rows)for p in primary),limits='Reused exact previous primary text derivatives/page renders, not new retrieval/extraction/OCR/render claims. Private reviewer source archive, not preprint payload. Raw earlier-review tapes are retained where in the authenticated inventory; not all such tapes manually read.'))
 assert all(pin(r['original']['path'])==r['original']for r in rows)
 (HERE/'RESEARCH_LOG.md').write_text((HERE/'RESEARCH_LOG.md').read_text()+'\n'+now()+' — Proof, scoped primary comparison, all8page visual review, exact actual8suite replay, metadata, full archive/build/provenance and allC1–C4 repairs verified. No unresolved issue; final reports and complete actually used input archives written. Review estimated95%; native final evidence authentication and immutable closure remain. Actual recorder PID '+str(os.getpid())+'.\n\nQualification of initial locator note: underlying rg reported a nonexistent auxiliary path; the precise rightmost piped-tool exit is not independently retained. The earlier exit2 phrasing is preserved as historical text, not repeated as a certified pipeline result. Own first checker actual55642exit1 versus corrected56459exit0 fully retained; historical launch0644 and final0444 are different custody epochs.\n')
 print(json.dumps(dict(status='REPORTS_AND_COMPLETE_SOURCE_ARCHIVE_PREPARED',actual_recorder_PID=os.getpid(),source_body_copies=len(rows),external_binary_anchors=len(skipped),stored_review_bytes=sum(p.stat().st_size for p in HERE.rglob('*')if p.is_file()),mandatory_issues=0,new_optional_issues=0)))
if __name__=='__main__': main()
