#!/usr/bin/env python3
"""Adversarial independent check of the credited Rizzoli--Thomas example.

Input: frozen authors' literal MonomialGen data; no import/execution of either
frozen verifier or authors' GAP code. Group enumeration uses dense matrix
multiplication; regular vectors are computed via Gaussian-elimination fixed
spaces, not by orbit size or signed-permutation action. NumPy is used only for
small dense integer matrix products (entries at most 36 before mod 3).
"""
import ast
import hashlib
import itertools
import json
import re
from collections import Counter
from pathlib import Path
import numpy as np

ROOT = Path(__file__).resolve().parents[1]
OUT = Path(__file__).resolve().parent
D = 9
I = np.eye(D, dtype=np.int64)
Z = (0,) * D

def key(A):
    return tuple(int(x) for x in A.flat)

def kernel_mod3(A):
    a = [[int(x) % 3 for x in row] for row in A]
    n = len(a[0])
    pivots = []
    r = 0
    for c in range(n):
        pivot = next((j for j in range(r, len(a)) if a[j][c]), None)
        if pivot is None:
            continue
        a[r], a[pivot] = a[pivot], a[r]
        inv = a[r][c]  # 1^-1=1 and 2^-1=2 in F3
        a[r] = [(inv * x) % 3 for x in a[r]]
        for j in range(len(a)):
            if j != r:
                mult = a[j][c]
                a[j] = [(a[j][k] - mult * a[r][k]) % 3 for k in range(n)]
        pivots.append(c)
        r += 1
        if r == len(a):
            break
    basis = []
    for f in range(n):
        if f in pivots:
            continue
        v = [0] * n
        v[f] = 1
        for j, c in enumerate(pivots):
            v[c] = -a[j][f] % 3
        basis.append(tuple(v))
    return basis

def span(basis):
    vectors = [Z]
    for b in basis:
        vectors = [tuple((v[j] + t*b[j]) % 3 for j in range(D))
                   for v in vectors for t in range(3)]
    return vectors

def add(v, w):
    return tuple((a+b) % 3 for a, b in zip(v, w))

def sub(v, w):
    return tuple((a-b) % 3 for a, b in zip(v, w))

def code(v):
    return sum(a * 3**j for j, a in enumerate(v))

# Calibration controls for the kernel implementation, including a non-diagonal
# action and nonsymmetric 3-cycle matrix (row/column convention control).
assert len(span(kernel_mod3(I-I))) == 3**D
assert span(kernel_mod3(2*I-I)) == [Z]
sign = I.copy(); sign[0,0] = 2
sf = span(kernel_mod3(sign.T-I))
assert len(sf) == 3**8 and all(v[0] == 0 for v in sf)
trans = I.copy(); trans[[0,1]] = trans[[1,0]]
tf = span(kernel_mod3(trans.T-I))
assert len(tf) == 3**8 and all(v[0] == v[1] for v in tf)
cycle = I.copy(); cycle[:3,:3] = [[0,1,0],[0,0,1],[1,0,0]]
cf = span(kernel_mod3(cycle.T-I))
assert len(cf) == 3**7 and all(v[0] == v[1] == v[2] for v in cf)

source = (ROOT/'source/external_counterexamples_degree_19683.g').read_text()
raw = re.findall(r'MonomialGen\(9,\s*(\[[^\]]+\]),\s*(\[[^\]]+\])\)', source)
assert len(raw) == 3
gens = []
parsed = []
for ptext, stext in raw:
    p, s = ast.literal_eval(ptext), ast.literal_eval(stext)
    assert sorted(p) == list(range(D)) and set(s) <= {1,2}
    A = np.zeros((D,D), dtype=np.int64)
    for i in range(D):
        A[i,p[i]] = s[i]
    assert np.array_equal(A@A.T % 3, I)
    gens.append(A)
    parsed.append({'images':p, 'signs':s})

# Closure by full dense multiplication. The finite monoid generated by
# invertible matrices is a group; all inverses are additionally checked below.
mats = {key(I): I}
queue = [I]
for A in queue:
    for B in gens:
        AB = A@B % 3
        k = key(AB)
        if k not in mats:
            mats[k] = AB
            queue.append(AB)
assert len(mats) == 1152
assert all(key(A.T) in mats for A in queue)
assert all(key(A@B % 3) in mats for A in queue for B in gens)
assert all(key(B@A % 3) in mats for A in queue for B in gens)

# Identify the permutation complement directly, independent of IRREDSOL.
assert np.array_equal(gens[0]@gens[0] % 3, I)
powers9 = [I]
for k in range(9):
    powers9.append(powers9[-1]@gens[1] % 3)
assert np.array_equal(powers9[9], I)
assert all(not np.array_equal(powers9[k], I) for k in range(1,9))
assert np.array_equal(gens[0]@gens[1]@gens[0] % 3, gens[1].T % 3)
complement = {key(A) for A in powers9[:9]} | {key(A@gens[0] % 3) for A in powers9[:9]}
assert len(complement) == 18 and complement <= set(mats)
assert all(set(int(x) for x in mats[k].flat) <= {0,1} for k in complement)

diagonal = [A for A in queue if np.array_equal(A, np.diag(A.diagonal()))]
assert len(diagonal) == 64
images = {tuple(int(np.flatnonzero(row)[0]) for row in A) for A in queue}
assert len(images) == 18
assert {p[0] for p in images} == set(range(D))
assert len({tuple(int(A[i,i]) for A in diagonal) for i in range(D)}) == D
# Explicitly realize every coordinate projection as an F3-linear combination
# of group matrices. This gives the precise irreducibility certificate.
for i in range(D):
    projection = sum((int(A[i,i])*A for A in diagonal), start=np.zeros((D,D),dtype=np.int64)) % 3
    expected = np.zeros((D,D), dtype=np.int64); expected[i,i]=1
    assert np.array_equal(projection, expected)
# Dropping the diagonal generator is a negative irreducibility control:
# pure permutations fix the all-ones line, so transitivity alone is insufficient.
assert all(np.array_equal(np.ones(D,dtype=np.int64)@A % 3, np.ones(D,dtype=np.int64)) for A in gens[:2])
assert not np.array_equal(np.ones(D,dtype=np.int64)@gens[2] % 3, np.ones(D,dtype=np.int64))

V = list(itertools.product(range(3), repeat=D))
stabs = Counter({v:0 for v in V})
nullities = Counter()
for A in queue:
    basis = kernel_mod3(A.T-I)
    fixed = span(basis)
    assert len(set(fixed)) == 3**len(basis)
    # Validate every generated fixed vector against the dense row action.
    X = np.asarray(fixed,dtype=np.int64)
    assert np.array_equal(X@A % 3, X)
    stabs.update(fixed)
    nullities[len(basis)] += 1
assert len(stabs) == 3**D and min(stabs.values()) >= 1
assert sum(stabs.values()) == sum(n * 3**d for d,n in nullities.items())
assert sum(stabs.values()) == len(queue)*67  # Burnside, independent orbit-count control
R = {v for v,n in stabs.items() if n == 1}
assert len(R) == 1152 and Z not in R
assert {sub(Z,r) for r in R} == R
r = min(R, key=code)
assert len({tuple(int(x) for x in np.asarray(r)@A % 3) for A in queue}) == 1152
assert {tuple(int(x) for x in np.asarray(r)@A % 3) for A in queue} == R

z = (1,1,1,1,1,1,0,0,0)  # fixed advertised witness, not selected from holes
assert z != Z and stabs[z] == 24 and z not in R
common = [w for w in V if stabs[w] == 1 and stabs[sub(w,z)] == 1]
assert not common
# Positive controls: zero and a regular vector have common neighbors, and
# a zero displacement has exactly |R|. Prevent constant-empty graph logic.
self_common = [w for w in V if stabs[w] == 1 and stabs[sub(w,Z)] == 1]
regular_common = [w for w in V if stabs[w] == 1 and stabs[sub(w,r)] == 1]
assert len(self_common) == 1152 and len(regular_common) > 0
shifted_stabs = Counter(stabs[sub(w,z)] for w in R)
assert 1 not in shifted_stabs

# Independent sumset via coordinate tuples. This makes no use of the frozen
# base-3 vector arrays, Boolean masks or indexing expressions.
twoR = {add(a,b) for a in R for b in R}
holes = set(V) - twoR
assert len(twoR) == 19587 and len(holes) == 96 and z in holes
assert Z in twoR and R <= twoR
for h in holes:
    assert any(sub(h,r) in twoR for r in R)

# Compare independent outputs only after establishing all mathematical facts.
frozen = json.loads((ROOT/'SMALL_COUNTEREXAMPLE_REPLAY.json').read_text())
R_digest = hashlib.sha256(json.dumps(sorted(map(code,R)),separators=(',',':')).encode()).hexdigest()
assert R_digest == frozen['regular_vector_codes_sha256']
assert parsed == frozen['generators']
assert Counter(stabs.values()) == Counter({int(k):v for k,v in frozen['stabilizer_size_histogram'].items()})
assert sorted(holes, key=code) == list(map(tuple,frozen['hole_vectors']))
assert list(z) == frozen['witness_z'] and code(z) == frozen['witness_z_code']

result = {
    'status':'PASS',
    'scope':'Independent exact audit of Rizzoli--Thomas degree-19683 base-two counterexample only; no novelty claim.',
    'manifest_sha256': '6064e8e6da4d87e3a94e42c3a8fd575db421e2364e914671ad66b38f52cfeb03',
    'independent_method':'dense matrix closure; exact mod-3 RREF fixed spaces; tuple-arithmetic exhaustive neighbor and sumset checks',
    'degree':len(V), 'point_stabilizer_order':len(queue), 'affine_group_order':len(V)*len(queue),
    'diagonal_order':len(diagonal), 'coordinate_image_order':len(images),
    'point_stabilizer_structure':'C2^6 semidirect D18; pure permutation complement verified via dihedral relations',
    'coordinate_transitive':True, 'explicit_coordinate_projectors':9,
    'fixedspace_dimension_histogram':dict(sorted(nullities.items())),
    'total_fixed_point_incidence':sum(stabs.values()), 'orbits_by_Burnside':sum(stabs.values())//len(queue),
    'stabilizer_size_histogram':dict(sorted(Counter(stabs.values()).items())),
    'regular_vectors':len(R), 'regular_orbits':1, 'base_size':2,
    'explicit_regular_base':[list(Z),list(r)],
    'regular_vector_codes_sha256':R_digest,
    'twoR_size':len(twoR), 'holes':len(holes),
    'witness_pair':[list(Z),list(z)], 'witness_z_code':code(z),
    'witness_z_stabilizer':stabs[z], 'common_neighbors':len(common),
    'candidate_vectors_tested':len(V),
    'stabilizers_of_w_minus_z_for_regular_w':dict(sorted(shifted_stabs.items())),
    'self_pair_common_neighbors_positive_control':len(self_common),
    'regular_pair_common_neighbors_positive_control':len(regular_common),
    'distance_shell_sizes':[1,len(R),len(twoR)-len(R)-1,len(holes)], 'diameter':3,
    'kernel_calibration_controls':'identity, -identity, diagonal sign, transposition, 3-cycle passed',
    'negative_irreducibility_control':'permutation generators fix all-ones line; sign generator does not',
    'comparison_to_frozen_json':'generators, regular-set digest, stabilizer histogram, all 96 holes and fixed witness identical',
    'holes_vectors_sorted_by_frozen_code':[list(v) for v in sorted(holes,key=code)]
}
(OUT/'INDEPENDENT_EXACT_CHECK.json').write_text(json.dumps(result,indent=2)+'\n')
print(json.dumps({k:v for k,v in result.items() if k != 'holes_vectors_sorted_by_frozen_code'},indent=2))
