"""Portable, explicit finite-group constructions; identity is always element 0."""
from itertools import product, permutations
from pathlib import Path
import json
import numpy as np

def generated(generators, identity, mul):
    elements=[identity]; index={identity:0}
    for x in elements:
        for g in generators:
            y=mul(x,g)
            if y not in index:
                index[y]=len(elements);elements.append(y)
    table=np.array([[index[mul(x,y)] for y in elements] for x in elements],dtype=np.int32)
    return elements, table

def permutation_group(n, generators):
    def mul(x,y):return tuple(x[y[i]] for i in range(n))
    return generated([tuple(g) for g in generators],tuple(range(n)),mul)

def cycle(n,*cycles):
    g=list(range(n))
    for c in cycles:
        for i in range(len(c)):g[c[i]]=c[(i+1)%len(c)]
    return tuple(g)

def symmetric(n):return permutation_group(n,[cycle(n,tuple(range(n))),cycle(n,(0,1))])
def alternating(n):return permutation_group(n,[cycle(n,(0,1,i)) for i in range(2,n)])
def cyclic(n):return generated([1%n],0,lambda x,y:(x+y)%n)
def dihedral(n): # order 2n
    return generated([(1,0),(0,1)],(0,0),lambda x,y:((x[0]+(-1)**x[1]*y[0])%n,(x[1]+y[1])%2))
def quaternion(n=2): # generalized quaternion order 4n, n a power of 2
    return generated([(1,0),(0,1)],(0,0),lambda x,y:((x[0]+(-1)**x[1]*y[0]+n*x[1]*y[1])%(2*n),(x[1]+y[1])%2))
def direct(a,b):
    ea,ta=a;eb,tb=b
    return generated([(i,0) for i in range(len(ea))]+[(0,j) for j in range(len(eb))],(0,0),lambda x,y:(int(ta[x[0],y[0]]),int(tb[x[1],y[1]])))

def unitriangular(n,p):
    pairs=[(i,j) for i in range(n) for j in range(i+1,n)];pos={ij:k for k,ij in enumerate(pairs)}
    def mul(a,b):return tuple((a[z]+b[z]+sum(a[pos[i,k]]*b[pos[k,j]] for k in range(i+1,j)))%p for z,(i,j) in enumerate(pairs))
    gens=[]
    for i in range(n-1):
        g=[0]*len(pairs);g[pos[i,i+1]]=1;gens.append(tuple(g))
    return generated(gens,(0,)*len(pairs),mul)

def sl2(p,projective=False):
    def canonical(a):return min(a,tuple((-x)%p for x in a)) if projective else a
    def mul(a,b):
        return canonical(((a[0]*b[0]+a[1]*b[2])%p,(a[0]*b[1]+a[1]*b[3])%p,(a[2]*b[0]+a[3]*b[2])%p,(a[2]*b[1]+a[3]*b[3])%p))
    return generated([canonical((1,1,0,1)),canonical((0,-1%p,1,0))],canonical((1,0,0,1)),mul)

def gl(n,p):
    def mul(a,b):return tuple(sum(a[i*n+k]*b[k*n+j] for k in range(n))%p for i in range(n) for j in range(n))
    ident=tuple(int(i==j) for i in range(n) for j in range(n));gens=[]
    for i in range(n):
      for j in range(n):
        if i!=j:
          g=list(ident);g[i*n+j]=1;gens.append(tuple(g))
    # all invertible diagonal entries; no choice of primitive root necessary
    for k in range(2,p):g=list(ident);g[0]=k;gens.append(tuple(g))
    return generated(gens,ident,mul)

def elementary_semidirect(p,n,A):
    # F_p^n semidirect cyclic group generated by A.
    A=np.array(A,dtype=np.int32).reshape(n,n);I=np.eye(n,dtype=np.int32)
    powers=[I];B=A.copy()
    while not np.array_equal(B,I):powers.append(B);B=B@A%p
    m=len(powers)
    def mul(x,y):return (tuple((np.array(x[0])+powers[x[1]]@np.array(y[0]))%p),(x[1]+y[1])%m)
    z=(0,)*n;gens=[(tuple(int(i==j) for j in range(n)),0) for i in range(n)]+[(z,1%m)]
    return generated(gens,(z,0),mul)

def save(name,group,destination):
    path=Path(destination);path.mkdir(parents=True,exist_ok=True)
    elements,table=group
    (path/f'{name}_group.json').write_text(json.dumps({'name':name,'order':len(elements),'elements':elements},default=int)+'\n')
    with (path/f'{name}_table.txt').open('w') as f:
        f.write(str(len(elements))+'\n');np.savetxt(f,table,fmt='%d')
    return table
