# PR46: credited full ambient-interior result for real-periodic rational maps

For every d>=2, a nonempty ordinary real-open subset of the full dimension2d+1 real degree-d rational-map space has exclusively RP1 periodic points at all positive periods. This is the existing Kozhasov–Kummer2020 preprint result. The proposal corrects the imported lower-dimensional/open-status assessment and claims no new discovery or certified journal publication. Status: already_solved; original0/5 with one source-verification response; new0; audit0. No paper/new DOI/tracker. NEW whole-current reviewPENDING.

Read SOURCE_STATUS.md with SOURCE_PRECISION_QUALIFICATIONS.md and CURRENT_SOURCE_STATUS_CONTEXT.md. original_archive preserves all13 original bodies; first-party original preparation, both closed mathematical families, true ROOT reproduction and separate approval records remain inspectable. Finite controls support identities; the proof supplies the all-degree/all-period and full ambient scope. Historical source hashes, runtime, review PASS, and publication-state sentences remain dated attributions. Current runtime/verdict fields are null. Extensive AI use; unrefereed; no claimed human peer review or formal certification. This prospective presentation supplies no acceptance or execution approval.


V2 execution chronology qualification: the builder writes original inner GIT_COMMANDS.json incrementally in git() finally blocks while the builder is alive. The frozen inner copy is a prepublication prefix. The outer operator does not write inner commands; only its completed OUTER CAPTURE.json is written after child exit. ROOT must fully inspect the original final inner command record and complete streams AFTER actual child exit before promotion. Closed superseded V1 claimed otherwise in one reference field; its bytes remain unchanged and are preserved as dated first-party source evidence. V2 repairs that administrative claim and capture anchors without changing science or producing approval.

Every actual ROOT JSON prerequisite (read ledger, science card, fresh13, evidence bindings) additionally requires operative_preparation_directory exactly current_preparation_family_v2. For the exact-key fresh13/evidence objects this is an additional required key; old-schema identities for science/evidence remain stable while the directory and pinned SOURCE closure identify V2. The future outer prelaunch schema is PR46_ROOT_BUILDER_PRELAUNCH_v2; actual outer schema PR46_ROOT_ACTUAL_BUILDER_OPERATION_v2; inner/outer directory prefixes are root_pr46_current_v2_build_ and root_pr46_current_v2_outer_.
