#!/usr/bin/env python3
"""Independent audit, not importing the author verifier.
Finite groups are generated by SymPy's Schreier-Sims implementation from cycle
notation. All subgroups are recovered top-down as kernels of F_2 characters,
using exact Gaussian elimination on character equations. Author data is read
only after independent results have been constructed, for comparison.
"""
import argparse
from collections import Counter
import hashlib
import itertools
import json
from pathlib import Path
import platform
import sympy
from sympy.combinatorics import Permutation, PermutationGroup

ROOT = Path(__file__).resolve().parent
DEFAULT_AUTHOR = ROOT.parent / 'kourovka_2515' / 'safe_output'

def need(ok, label):
    if not ok:
        raise AssertionError(label)

def perm(n, cycles):
    p = Permutation(list(range(n)))
    for c in cycles:
        p = p * Permutation(*[v - 1 for v in c], size=n)
    return p

def arrays(group):
    return sorted(tuple(p.array_form) for p in group.generate_schreier_sims())

def right_product(x, y):
    return tuple(y[x[i]] for i in range(len(x)))

def orbit_cycles(p):
    # Include singleton orbits, avoiding any convention about support of a 1-cycle.
    unseen = set(range(len(p)))
    result = []
    while unseen:
        seed = min(unseen)
        q, x = set(), seed
        while x not in q:
            q.add(x)
            x = p[x]
        need(x == seed, 'orbit closes at seed')
        unseen -= q
        result.append(frozenset(q))
    return result

def block(B, G):
    for p in G:
        image = frozenset(p[x] for x in B)
        if B & image and image != B:
            return False
    return True

def all_characters(table, H):
    """Solutions to f(xy)+f(x)+f(y)=0 for all x,y in H, over F_2."""
    order = sorted(H)
    positions = {g: i for i, g in enumerate(order)}
    basis = {}
    for x in order:
        for y in order:
            row = (1 << positions[x]) ^ (1 << positions[y]) ^ (1 << positions[table[x][y]])
            while row:
                pivot = row.bit_length() - 1
                if pivot not in basis:
                    basis[pivot] = row
                    break
                row ^= basis[pivot]
    free = [i for i in range(len(order)) if i not in basis]
    answers = []
    for assignment in range(1 << len(free)):
        solution = sum(((assignment >> j) & 1) << i for j, i in enumerate(free))
        for pivot in sorted(basis):
            if (basis[pivot] & solution).bit_count() & 1:
                solution ^= 1 << pivot
        need(all((row & solution).bit_count() % 2 == 0 for row in basis.values()), 'nullspace check')
        answers.append(frozenset(g for i, g in enumerate(order) if not ((solution >> i) & 1)))
    return answers

def subgroup_lattice_by_descent(G):
    lookup = {g: i for i, g in enumerate(G)}
    table = [[lookup[right_product(x, y)] for y in G] for x in G]
    top = frozenset(range(len(G)))
    pending, known, maximals = [top], set(), {}
    while pending:
        H = pending.pop()
        if H in known:
            continue
        known.add(H)
        kernels = set(all_characters(table, H)) - {H}
        need(all(2 * len(K) == len(H) for K in kernels), 'character kernels index 2')
        maximals[H] = kernels
        pending.extend(kernels - known)
    # Every proper subgroup of a finite 2-group is contained in a maximal
    # subgroup, and every maximal subgroup has index 2. Recursive descent is complete.
    for H in known:
        need(0 in H and all(table[x][y] in H for x in H for y in H), 'subgroup closure')
    return sorted(known, key=lambda H: (len(H), sorted(H))), maximals, table

def run(author_dir):
    A = perm(8, [(1,3,2,4),(5,7),(6,8)])
    B = perm(8, [(1,5),(2,6),(3,7),(4,8)])
    Z = perm(8, [(3,4),(5,6)])
    PG = PermutationGroup(A, B)
    G = arrays(PG)
    need(PG.order() == 32 and PG.is_transitive(), 'Schreier-Sims group')
    need(len(G) == 32 and tuple(Z.array_form) in G, 'enumeration and Z membership')

    # Recover the destination-indexed function from the permutations. This
    # goes in the opposite direction from the author's parity construction.
    params = {}
    for p in G:
        t = p[0] // 2
        need(all(p[2*v] // 2 == (v ^ t) == p[2*v+1] // 2 for v in range(4)), 'translation quotient')
        f = [0] * 4
        for v in range(4):
            f[v ^ t] = p[2*v] % 2
            need(p[2*v+1] % 2 == (1 ^ f[v ^ t]), 'fibre flip')
        need(sum(f) % 2 == t % 2, 'parity constraint')
        params[p] = (tuple(f), t)
    need(len(set(params.values())) == 32, 'all parity-model elements occur')
    for p, q in itertools.product(G, repeat=2):
        # right_product applies p first, then q.
        f, t = params[p]; g, u = params[q]
        predicted = tuple(g[v] ^ f[v ^ u] for v in range(4)), t ^ u
        need(params[right_product(p, q)] == predicted, 'independent right-action semidirect law')

    lattice, maximals, table = subgroup_lattice_by_descent(G)
    transitive = [H for H in lattice if {G[i][0] for i in H} == set(range(8))]
    top = frozenset(range(32))
    need(len(lattice) == 50 and transitive == [top], 'all subgroups and minimal transitivity')
    phi = frozenset.intersection(*maximals[top])
    stabilizer = frozenset(i for i, p in enumerate(G) if p[0] == 0)
    need(len(phi) == 8 and len(stabilizer) == 4 and stabilizer <= phi, 'Frattini via all maximal subgroups')
    need(all(params[G[i]][1] == 0 for i in phi), 'Frattini equals even base')

    all_blocks = [frozenset(i for i in range(8) if bits >> i & 1) for bits in range(1, 256)]
    all_blocks = [C for C in all_blocks if block(C, G)]
    records = []
    cyclic_subgroups = set()
    passing = []
    for k, p in enumerate(G):
        power = tuple(range(8)); cyclic = set()
        while power not in cyclic:
            cyclic.add(power); power = right_product(power, p)
        cyclic_subgroups.add(frozenset(cyclic))
        support_tests = []
        for C in orbit_cycles(p):
            crossing = []
            for j, z in enumerate(G):
                zC = frozenset(z[x] for x in C)
                if C & zC and C != zC:
                    crossing.append(j)
            support_tests.append({'cycle': sorted(x + 1 for x in C), 'is_block': not crossing,
                                  'crossing_element_indices': crossing})
        records.append({'element_index': k, 'cycle_tests': support_tests})
        if all(test['is_block'] for test in support_tests):
            passing.append(k)
    need(len(cyclic_subgroups) < 32 and len(passing) < 32, 'cyclic enumeration is nontrivial')
    C = frozenset([0,4]); zC = frozenset(Z(x) for x in C)
    need(C in orbit_cycles(tuple(B.array_form)) and zC == frozenset([0,5]) and C & zC == frozenset([0]), 'exact crossing witness')
    # A nontrivial cyclic orbit is a full cycle even when the element has
    # additional disjoint cycles. Do not test only supports of whole elements.
    need(not block(C, G), 'C is not a block')

    q1 = [p for p in G if params[p][1] == 1]
    q2 = [p for p in G if params[p][1] == 2]
    lift_orders = Counter()
    for p, q in itertools.product(q1, q2):
        Q = PermutationGroup(Permutation(p), Permutation(q))
        lift_orders[int(Q.order())] += 1
        need(Q.order() == 32, 'every quotient lift pair generates whole P')
        # Verify difference proof at the level of the recovered functions.
        f, _ = params[p]; g, _ = params[q]
        h = tuple(f[v] ^ f[v ^ 1] for v in range(4))
        c = tuple(f[v] ^ f[v ^ 2] ^ g[v] ^ g[v ^ 1] for v in range(4))
        h2 = tuple(h[v ^ 2] for v in range(4))
        span = {tuple((i*h[v]) ^ (j*h2[v]) ^ (k*c[v]) for v in range(4))
                for i,j,k in itertools.product(range(2), repeat=3)}
        need(len(span) == 8 and all(sum(x) % 2 == 0 for x in span), 'three independent even vectors')
        need(all(c[v] ^ c[v ^ 1] == 1 for v in range(4)), 'D1 c is constant one')
    need(dict(lift_orders) == {32: 64}, '64 lift pairs')

    # First wreath group is reconstructed from three permutations, rather
    # than enumerated from pairs of precomputed elements.
    a16 = Permutation(list(A.array_form) + list(range(8,16)))
    b16 = Permutation(list(B.array_form) + list(range(8,16)))
    swap = Permutation(list(range(8,16)) + list(range(8)))
    WG = PermutationGroup(a16, b16, swap)
    W = arrays(WG)
    need(WG.order() == 2048 and len(W) == 2048 and WG.is_transitive(), 'first wreath Schreier-Sims')
    bottom = frozenset(range(8))
    need(block(bottom, W), 'first wreath bottom block')
    stabilizing = [p for p in W if p[0] < 8]
    image_multiplicity = Counter(tuple(p[:8]) for p in stabilizing)
    need(set(image_multiplicity) == set(G) and set(image_multiplicity.values()) == {32}, 'first wreath exact restriction and kernel')
    first_lifts_B = [p for p in stabilizing if tuple(p[:8]) == tuple(B.array_form)]
    first_lifts_Z = [p for p in stabilizing if tuple(p[:8]) == tuple(Z.array_form)]
    for b, z in itertools.product(first_lifts_B, first_lifts_Z):
        need(C in orbit_cycles(b), 'arbitrary lift complete cycle')
        image = frozenset(z[x] for x in C)
        need(image == zC and C & image == frozenset([0]), 'arbitrary lift crossing')
    need(len(first_lifts_B) * len(first_lifts_Z) == 1024, 'all first-wreath lift combinations')

    # Positive and diagnostic controls independent of the supplied certificate.
    regular = PermutationGroup(perm(8, [(1,2),(3,4),(5,6),(7,8)]),
                               perm(8, [(1,3),(2,4),(5,7),(6,8)]), B)
    R = arrays(regular)
    need(len(R) == 8 and regular.is_transitive(), 'regular elementary abelian control')
    need(all(block(c, R) for r in R for c in orbit_cycles(r)), 'positive control passes')
    D = PermutationGroup(perm(4,[(1,2)]),perm(4,[(1,3,2,4)]))
    Darr = arrays(D)
    need(all(block(c,Darr) for p in D.generators for c in orbit_cycles(tuple(p.array_form))), 'generator-only trap passes generators')
    need(any(not block(c,Darr) for p in Darr for c in orbit_cycles(p)), 'generator-only trap fails group')

    # Author comparison is deliberately last. No author-generated data controls
    # independent generation, enumeration, or predicate definitions above.
    cert = json.loads((author_dir / 'FINITE_CERTIFICATE.json').read_text())
    need([[x+1 for x in p] for p in G] == cert['elements_one_based'], 'author element list matches')
    masks = [sum(1 << i for i in H) for H in lattice]
    need(masks == cert['subgroup_masks'], 'author subgroup masks match independent character descent')
    results = {
      'status':'PASS', 'python':platform.python_version(), 'sympy':sympy.__version__,
      'group_order':32, 'subgroups':len(lattice),
      'subgroup_order_histogram':dict(sorted(Counter(len(H) for H in lattice).items())),
      'transitive_subgroups':1, 'all_proper_subgroups_intransitive':True,
      'maximal_subgroups':len(maximals[top]), 'frattini_order':len(phi), 'point_stabilizer_order':len(stabilizer),
      'point_stabilizer_in_frattini':True, 'cyclic_subgroup_count':len(cyclic_subgroups),
      'element_order_histogram':dict(sorted(Counter(len(C) for C in [frozenset(tuple(q.array_form) for q in PermutationGroup(Permutation(p)).generate_schreier_sims()) for p in G]).items())),
      'nonempty_subsets_checked_for_blocks':255, 'block_count':len(all_blocks),
      'block_size_histogram':dict(sorted(Counter(len(C) for C in all_blocks).items())),
      'cycle_support_checks_including_singletons':sum(len(r['cycle_tests']) for r in records),
      'elements_with_all_cycle_supports_blocks':len(passing),
      'elements_with_crossing_cycle':len(G)-len(passing),
      'lift_pair_orders':dict(lift_orders), 'first_wreath_order':len(W),
      'first_wreath_block_stabilizer_order':len(stabilizing), 'first_wreath_restriction_kernel_order':32,
      'first_wreath_crossing_lift_combinations_checked':1024,
      'author_certificate_matches':True, 'positive_control_passes':True,
      'generator_only_test_trap_detected':True,
      'infinite_theorem':'Deductive audit in INFINITE_PROOF_AUDIT.md; not inferred from enumeration.'
    }
    witness_cert = {'elements_one_based':[[x+1 for x in p] for p in G], 'subgroup_masks':masks,
                    'all_blocks_one_based':[sorted(x+1 for x in C) for C in all_blocks],
                    'all_element_cycle_tests':records,
                    'cyclic_subgroup_masks':sorted(sum(1 << G.index(p) for p in K) for K in cyclic_subgroups),
                    'frattini_element_indices':sorted(phi), 'point_stabilizer_element_indices':sorted(stabilizer),
                    'maximal_subgroup_masks':sorted(sum(1<<i for i in H) for H in maximals[top])}
    return results, witness_cert

def main():
    parser=argparse.ArgumentParser()
    parser.add_argument('--author-dir',type=Path,default=DEFAULT_AUTHOR)
    parser.add_argument('--check',action='store_true')
    args=parser.parse_args()
    results, certificate=run(args.author_dir)
    for filename,value in [('INDEPENDENT_RESULTS.json',results),('INDEPENDENT_CERTIFICATE.json',certificate)]:
        path=ROOT/filename
        if args.check:
            need(json.loads(path.read_text())==json.loads(json.dumps(value)),filename+' drift')
        else:
            path.write_text(json.dumps(value,indent=2,sort_keys=True)+'\n')
    print(json.dumps(results,indent=2,sort_keys=True))

if __name__=='__main__':
    main()
