from pathlib import Path
import json,hashlib,datetime,os,subprocess
A=Path(__file__).resolve().parent;C=A.parents[2];P=A.parents[1]
def load(p):return json.loads(p.read_text())
def require(c,m):
 if not c:raise RuntimeError(m)
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def now():return datetime.datetime.now(datetime.timezone.utc).isoformat()
release=load(A/'actual_checkpoints/source_acceptance/RECEIPT.json');ready=load(A/'ROOT_READY_FOR_PUBLICATION.json');pub=load(A/'actual_operations/zenodo_publish/stdout.bin');ins=load(A/'actual_operations/zenodo_inspect_published/stdout.bin');tracker=load(A/'ROOT_TRACKER_RECORD.json');pr=load(A/'actual_operations/pr91_final_readback/stdout.bin');native=load(A/'native_acceptance_20261005/PREPARED_RECEIPT.json');download=load(A/'ROOT_PUBLIC_DEPOSIT_VERIFICATION.json')
require(release['remote_verified'] and release['parent']==pr['mergeCommit']['oid']==native['merge_commit'],'release ancestry')
require(pr['state']=='MERGED' and pr['headRefOid']==ready['head'] and pr['body']==(A/'PR91_ACCEPTED_BODY.md').read_text(),'final PR body/head')
require(pub['state']==ins['state']=='published' and all(pub[k]==ins[k] for k in ['environment','title','files','metadata_normalizations','id','doi','doi_url','record_url']) and pub['metadata_normalizations']==[] and pub['doi_resolution']['status']==ins['doi_resolution']['status']=='resolved','publication/DOI')
require(tracker['unique_verified'] and tracker['DOI']==pub['doi'] and download['all_seven_downloaded_bytes_match_reviewed_payloads'],'tracker/download')
for row in ready['payloads']:require(sha(A/'publication_package_v1'/row['file'])==row['sha256'],'published local byte mutation')
for row in load(A/'original_source_authentication_20261005/ORIGINAL_BLOB_MANIFEST.json')['files']:require(sha(Path(row['preserved_path']))==row['sha256'],'incoming archive mutation')
N=C/'unsolved_math_prioritization/attempts/30003052';require(native['native_optimized_runs_passed'] and sha(N/'CLASSIFICATION.md')==native['current_artifact_sha256'],'native checker gate')
for rel in ['status.json','readiness.json']:
 x=load(N/rel);require(x['DOI']==pub['doi'] and x['artifact_sha256']==native['current_artifact_sha256'] and x['status']=='claimed_solved' and x['new_central_proof_search_turns']==0,'native accepted state')
for rel,digest in load(N/'frozen_artifacts.json').items():require(sha(N/rel)==digest,'native frozen digest')
rows=[s for s in (C/'unsolved_math_prioritization/QUEUE.md').read_text().splitlines() if '| 30003052 / OWR-14215-004 |' in s];require(len(rows)==1,'queue identity');cells=rows[0].split('|');require(cells[8].strip()=='claimed_solved' and cells[9].strip()=='1/5' and cells[12].strip()==pub['doi_url'],'queue accepted row')
x={'schema':'pr91-actual-completion/v1','UTC':now(),'actual_operator_PID':os.getpid(),'PR':91,'head':ready['head'],'literal_submitted_status':'claimed_solved','original_budget':'1/5','new_central_proof_search_turns':0,'DOI':pub['doi'],'record_url':pub['record_url'],'tracker_range':tracker['range'],'merge_commit':pr['mergeCommit']['oid'],'scientific_acceptance_commit':release['commit'],'source_checkpoint_remote_verified':True,'full_target_verified':True,'whole_package_rounds':2,'mandatory_findings_remaining':[],'bounded_priority_audit_complete':True,'priority_disposition':'explicit historical mixed completion by credited classical specialization, no firstness or continued-openness claim','incoming_bodies_preserved':20,'all_seven_published_downloads_byte_identical':True,'exact_metadata_verified':True,'native_optimized_checks':[473,473,907],'workflow_estimate_percent':100,'dated_program_completed':12,'dated_program_total':99,'dated_program_percent':100*12/99,'metadata_checkpoint_push_pending':True,'advance_to_next_status_intake_after_metadata_push':True,'primary_checkout_mutated':False,'primary_synchronization_pending':True,'persistent_goal_complete':False}
(A/'ROOT_FINAL_COMPLETION_ACTUAL_RECEIPT_20261005.json').write_text(json.dumps(x,indent=2,sort_keys=True)+'\n')
progress=load(P/'CURRENT_PROGRESS.json');progress.update({'UTC':x['UTC'],'current_PR_workflow_percent':100,'current_actual_completion_record':'audits/pr91_30003052/ROOT_FINAL_COMPLETION_ACTUAL_RECEIPT_20261005.json','current_native_integration_complete':True,'current_isolated_native_lifecycle_complete':True,'completion_metadata_checkpoint_pending_at_snapshot':True,'advance_to_next_PR_authorized_now':False,'fully_completed_count':12,'fully_completed_eligible_PRs':sorted(set(progress['fully_completed_eligible_PRs']+[91])),'fully_completed_fraction_percent':100*12/99,'workflow_estimate_percent':100*12/99,'published_PRs':sorted(set(progress['published_PRs']+[91])),'last_completed_PR':91,'last_published_PR':91,'last_completed_DOI':pub['doi'],'last_published_DOI':pub['doi'],'last_completed_PR_workflow_percent':100,'last_completed_acceptance_commit':release['commit'],'last_completed_scientific_checkpoint_commit':release['commit'],'last_completed_merge_commit':pr['mergeCommit']['oid'],'last_completed_tracker_range':tracker['range'],'last_completed_actual_final_gate':'audits/pr91_30003052/ROOT_FINAL_COMPLETION_ACTUAL_RECEIPT_20261005.json','last_completed_record':'audits/pr91_30003052/ROOT_FINAL_COMPLETION_ACTUAL_RECEIPT_20261005.json','last_completed_final_completion_readback':None,'last_completed_metadata_checkpoint_commit':None,'last_completed_outcome':'verified_full_closed_ball_Koopman_classification_published','last_completed_mathematical_and_package_review_percent':100,'last_completed_priority_audit_percent':100,'last_completed_priority_clearance':True,'last_completed_priority_hold':None,'last_completed_full_source_solved':True,'last_completed_publication_authorization':True,'last_completed_scientific_disposition_record':'audits/pr91_30003052/ROOT_READY_FOR_PUBLICATION.json','next_eligible_PR_after_current_completion':None,'next_eligible_order_requires_fresh_status_check':True,'next_numeric_intake_cursor':92,'remaining_current_step':'PR91 scientific workflow complete: reviewed, published, uniquely tracked, merged and accepted-source checkpoint pushed. Completion metadata checkpoint is prepared; next fresh status-only intake follows its verified push.','workflow_estimate_definition':'Eight published workflows, three credited prior-result dispositions and one verified partial disposition divided by dated 99-PR census.'});(P/'CURRENT_PROGRESS.json').write_text(json.dumps(progress,indent=2,sort_keys=True)+'\n')
with (A/'RESEARCH_LOG.md').open('a') as f:f.write('\n### '+x['UTC']+' — PR91 scientific completion, workflow 100%; dated program 12/99 (12.12%)\nExact reviewed package published as '+pub['doi']+', DOI resolved, all seven public download bytes authenticated, unique tracker row '+tracker['range']+', unchanged head merged. Accepted native theorem, explicit checker guards and refreshed receipts/frozen hashes are pushed in main '+release['commit']+'. Full target verified; two sequential fresh package reviews clean after the required attribution repair. Classical scope and bounded priority gaps remain explicit; no firstness or human-referee claim. Incoming twenty bodies and budget 1/5 unchanged. This completion metadata checkpoint is prepared for its final verified main push; next ordered status intake remains gated on that push. Overall persistent goal stays active.\n')
paths=[str((A/rel).relative_to(C)) for rel in ['ROOT_FINAL_COMPLETION_ACTUAL_RECEIPT_20261005.json','RESEARCH_LOG.md','finalize_PR91.py','SOURCE_ACCEPTANCE_CHECKPOINT_SELECTION.json','PR91_ACCEPTED_BODY.md','actual_checkpoints/source_acceptance/RECEIPT.json','actual_checkpoints/source_acceptance/PROCESS_JOURNAL.json']]+[str((P/'CURRENT_PROGRESS.json').relative_to(C))]
for label in ['checkpoint_source_acceptance','pr91_final_body_update','pr91_final_readback']:
 paths.extend(str(p.relative_to(C)) for p in (A/'actual_operations'/label).iterdir() if p.is_file())
(A/'COMPLETION_METADATA_SELECTION.json').write_text(json.dumps({'paths':sorted(set(paths))},indent=2)+'\n');print(json.dumps(x))
