"""Prepare current native acceptance only after verified publication, tracker, and merge.
Runs on the independent main checkout, never the primary checkout's index.
"""
from pathlib import Path
import json,subprocess,hashlib,datetime,os
A=Path(__file__).resolve().parent;C=A.parents[2];P=A.parents[1];D=A/'native_acceptance_20261005';D.mkdir(exist_ok=False);records=[]
def now():return datetime.datetime.now(datetime.timezone.utc).isoformat()
def require(c,m):
 if not c:raise RuntimeError(m)
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def dump(p,x):p.write_text(json.dumps(x,indent=2,sort_keys=True)+'\n')
def run(argv,cwd=C):
 start=now();p=subprocess.Popen(argv,cwd=cwd,stdout=subprocess.PIPE,stderr=subprocess.PIPE);out,err=p.communicate();i=len(records)
 for name,b in [('stdout',out),('stderr',err)]:(D/(str(i)+'.'+name+'.bin')).write_bytes(b)
 records.append({'argv':argv,'cwd':str(cwd),'PID':p.pid,'UTC_start':start,'UTC_end':now(),'exit_code':p.returncode,'stdout_file':str(i)+'.stdout.bin','stderr_file':str(i)+'.stderr.bin','stdout_sha256':hashlib.sha256(out).hexdigest(),'stderr_sha256':hashlib.sha256(err).hexdigest()});dump(D/'PROCESS_JOURNAL.json',{'operator_PID':os.getpid(),'records':records});require(p.returncode==0,err.decode()[:1000]);return out
def git(*args):return run(['git',*args])
ready=json.loads((A/'ROOT_READY_FOR_PUBLICATION.json').read_text());require(ready['publication_clearance'] and ready['whole_package_rounds']==2,'review gate')
pub=json.loads((A/'actual_operations/zenodo_publish/stdout.bin').read_bytes());require(pub['state']=='published' and pub['environment']=='production' and pub['doi'],'published receipt');doi=pub['doi'];url=pub['doi_url']
tracker=json.loads((A/'ROOT_TRACKER_RECORD.json').read_text());require(tracker['unique_verified'] and tracker['DOI']==doi,'tracker')
pr=json.loads((A/'actual_operations/pr91_merged_readback/stdout.bin').read_bytes());require(pr['state']=='MERGED' and pr['headRefOid']=='2ea84c5de45cb92783b5b55057af1f52590be6bf','merge state/head');merge=pr['mergeCommit']['oid']
require(git('symbolic-ref','--short','HEAD').strip()==b'main','not main');old=git('rev-parse','HEAD').strip().decode();require(not git('diff','--cached','--name-only','-z'),'foreign staged')
git('fetch','--no-tags','https://github.com/AlecKriebel/Math.git','main');base=git('rev-parse','FETCH_HEAD').strip().decode();git('merge-base','--is-ancestor',old,base);git('merge-base','--is-ancestor',merge,base)
# Mixed reset in this private checkout preserves all worktree bodies; its own index was empty.
git('reset','--mixed','--quiet',base)
orig=json.loads((A/'original_source_authentication_20261005/ORIGINAL_BLOB_MANIFEST.json').read_text());native=C/'unsolved_math_prioritization/attempts/30003052';paths=[]
for row in orig['files']:
 source=Path(row['preserved_path']);require(sha(source)==row['sha256'],'original archive changed')
 b=git('show',base+':'+row['path']);require(hashlib.sha256(b).hexdigest()==row['sha256'],'merged native body changed')
 target=C/row['path'];require(not target.exists() or target.read_bytes()==b,'foreign native worktree edit');target.parent.mkdir(parents=True,exist_ok=True);target.write_bytes(b);paths.append(row['path'])
# Minimal active-checker repairs; mathematical bodies are unchanged.
for rel in ['verify.py','review/author_replay/verify.py']:
 p=native/rel;s=p.read_text();before='    assert bool(v),k';after='    if not bool(v):\n        raise AssertionError(k)';require(s.count(before)==1,'submitted guard occurrence');p.write_text(s.replace(before,after))
p=native/'review/independent_checks.py';s=p.read_text();before=' assert bool(x),label';after=' if not bool(x):\n  raise AssertionError(label)';require(s.count(before)==1,'independent guard occurrence');p.write_text(s.replace(before,after))
classification=native/'CLASSIFICATION.md';s=classification.read_text();heading='**Complete classification candidate for 30003052 / OWR-14215-004; separate adversarial review pending.**';require(heading in s,'old candidate header')
s=s.replace(heading,'**Verified full classification for 30003052 / OWR-14215-004; accepted after independent mathematical and publication-package reviews.**')
s+='\n## 8. Publication acceptance and priority scope (2026-10-05)\n\nThe self-contained research note is [The mixed point spectrum of a matrix contraction on its closed unit ball]('+url+'). It expressly answers the mixed point-spectrum converse left open in Küster 2015 Theorem 3.1.14(i); the 2016 contribution states only its inclusion. The missing factorization is a short specialization of the classical Jacobs–de Leeuw–Glicksberg mechanism, identified with composition by the contractive peripheral projection. The prior peripheral, interior and nilpotent point-spectrum cases are credited; the entire J-nonempty full-disk row already follows immediately from the 2015 interior inclusion and spectral closure. A bounded primary-source audit found no earlier explicit completion in inspected scope, with ordinary edition/coverage gaps disclosed. No firstness, new general mechanism, novel full-disk spectrum, or continuous 2015–2026 openness claim is made.\n\nTwo sequential new whole-package adversarial AI reviews were completed. The first required a source-attribution precision repair, applied globally; the second reviewed the corrected bytes. Current native checkers use explicit guards that remain active under Python -O. Immutable incoming 20-file bodies and original 1/5 author history remain archived in the program audit. AI tools were used extensively; the work is unrefereed without conventional human peer review.\n'
classification.write_text(s);current_hash=sha(classification)
# Reproduce active native entry points with optimization enabled and capture their actual receipts.
author_raw=run(['/usr/bin/python3','-E','-B','-O',str(native/'verify.py')],native);author=json.loads(author_raw);require(author['exact_assertions']==473 and author['status']=='PASS' and author['artifact_sha256']==current_hash,'native author receipt');(native/'verification.json').write_bytes(author_raw)
replay_raw=run(['/usr/bin/python3','-E','-B','-O',str(native/'review/author_replay/verify.py')],native/'review/author_replay');replay=json.loads(replay_raw);require(replay['exact_assertions']==473 and replay['status']=='PASS','native replay');(native/'review/author_replay/verification.json').write_bytes(replay_raw)
ind_raw=run(['/usr/bin/python3','-E','-B','-O',str(native/'review/independent_checks.py')],native/'review');ind=json.loads(ind_raw);require(ind['exact_assertions']==907 and ind['status']=='PASS','native independent')
package_rel='../../../draft_pr_publication_program_20260930/audits/pr91_30003052/publication_package_v1/publicfiles'
(native/'README.md').write_text('# 30003052: verified linear-map Koopman spectrum classification\n\nThe complete theorem in CLASSIFICATION.md has been independently verified in the exact arbitrary-complex-norm, closed-ball C(U) setting. The self-contained [research note]('+url+') explicitly completes the mixed point-spectrum converse from Küster 2015 Th3.1.14(i), using a short classical JdLG specialization. Known special cases and the already immediate full-disk row are credited. No worldwide firstness or continuing-openness claim is made; the public priority supplement documents bounded coverage and edition gaps.\n\nTwo successive fresh whole-package AI adversarial reviews completed; first-round attribution wording was corrected before the new second review. AI tools were used extensively; this is an unrefereed preprint without conventional human peer review.\n\nThe [portable package]('+package_rel+'/README.md) contains current source, explicit optimization-safe verifiers, recorded results and provenance. It supplies 2720 distinct finite controls per mode: 2154 exact/discrete and 566 floating diagnostics. Finite controls supplement the written proof. Current native entry points also reproduce 473/907 counts under Python -O.\n\nOriginal submission/review bodies and their exact incoming hashes are retained in the audit archive. Original author budget 1/5 is preserved; no new central proof-search turns were used. DOI: '+doi+'; tracker: '+tracker['range']+'.\n')
for name in ['status.json','readiness.json']:
 p=native/name;x=json.loads(p.read_text());x.update({'status':'claimed_solved','full_target_verified':True,'accepted_as_full_resolution':True,'DOI':doi,'record_url':pub['record_url'],'publication_date':'2026-10-05','publication_version':'1.0','whole_package_review_rounds':2,'mandatory_publication_findings_remaining':[],'bounded_priority_audit_complete':True,'historical_priority_established':False,'priority_scope':'explicit completion of historical mixed converse by attributed classical specialization; no firstness claim','artifact_sha256':current_hash,'submitted_artifact_sha256':'0abd5dd0918905b3a6c1e9c62a57097645bba6334cb625a4a4e88f2c12c4416b','current_checkers_optimization_safe':True,'human_peer_review':False,'new_central_proof_search_turns':0})
 if name=='readiness.json':x.update({'remaining_hold':None,'proof_completion_estimate_percent':100,'validation_completion_estimate_percent':100,'separate_review':'PASS_COMPLETE_CLASSIFICATION_AND_CORRECTED_PUBLICATION_PACKAGE'})
 dump(p,x)
p=native/'review/review_summary.json';x=json.loads(p.read_text());x.update({'historical_review_report_about_submission':True,'submitted_artifact_sha256':x['artifact_sha256'],'artifact_sha256':current_hash,'author_receipt_byte_identical':False,'current_receipt_note':'Active native code guards repaired and receipts refreshed; original exact replay is preserved in immutable incoming archive.','publication_package_review_rounds':2,'mandatory_corrections_remaining':[],'DOI':doi,'bounded_priority_scope':'attributed short classical specialization explicitly answers historical converse; no firstness claim'});x['historical_review_files']=x.pop('publication_files');dump(p,x)
freeze={name:sha(native/name) for name in ['CLASSIFICATION.md','verify.py','verification.json','source_record.json','source_manifest.json']};dump(native/'frozen_artifacts.json',freeze)
with (native/'RESEARCH_LOG.md').open('a') as f:f.write('\n### '+now()+' — publication acceptance preparation, workflow 95%\nVerified result and complete corrected package published as '+doi+'; tracker '+tracker['range']+'. Two fresh full-package reviews completed. Current native guards repaired without changing mathematics, actual optimized entry points pass. Incoming 20 bodies and original budget 1/5 preserved in audit archive. Final main checkpoint push remains pending.\n')
queue=C/'unsolved_math_prioritization/QUEUE.md';qb=git('show',base+':unsolved_math_prioritization/QUEUE.md').decode();require(not queue.exists() or queue.read_text()==qb,'foreign queue worktree edits');lines=qb.splitlines();indices=[i for i,s in enumerate(lines) if '| 30003052 / OWR-14215-004 |' in s];require(len(indices)==1,'queue row unique');i=indices[0];cells=lines[i].split('|');require(cells[8].strip()=='claimed_solved' and cells[9].strip()=='1/5','queue status/budget');cells[11]=' 2026-10-05: Verified full closed-ball C(U) classification; explicit mixed converse completed by credited classical JdLG specialization. Known cases and immediate full-disk consequence credited. Two fresh whole-package AI reviews, attribution repair and optimization-safe verifiers; unrefereed, bounded priority audit, no firstness claim. PR91 accepted and preprint published. ';cells[12]=' '+url+' ';lines[i]='|'.join(cells);queue.parent.mkdir(parents=True,exist_ok=True);queue.write_text('\n'.join(lines)+'\n');paths.append(str(queue.relative_to(C)))
accept={'schema':'pr91-native-acceptance-preparation/v1','UTC':now(),'actual_operator_PID':os.getpid(),'PR':91,'head':pr['headRefOid'],'merge_commit':merge,'base_commit':base,'DOI':doi,'record_url':pub['record_url'],'tracker_range':tracker['range'],'original_budget':'1/5','new_central_proof_search_turns':0,'incoming_bodies_unchanged':20,'native_exact_controls':[473,473,907],'native_optimized_runs_passed':True,'current_artifact_sha256':current_hash,'native_paths':paths,'main_checkpoint_pending':True,'primary_checkout_mutated':False,'primary_synchronization_pending':True}
dump(D/'PREPARED_RECEIPT.json',accept);print(json.dumps({k:v for k,v in accept.items() if k!='native_paths'}))
