from pathlib import Path
from datetime import datetime,timezone
import ast,gzip,hashlib,json,os,stat
R=Path('/Users/alec/Documents/Math');P=R/'draft_pr_descending_audit_20261002';A=P/'audits/pr301_30004365';O=Path(__file__).parent;S=P/'SHARED_GIT_WINDOW_STATUS.json';sha=lambda b:hashlib.sha256(b).hexdigest();load=lambda p:json.loads(Path(p).read_bytes());checks=0;reads=[]
def check(v,m):
 global checks
 checks+=1
 if not v:raise RuntimeError(m)
def pin(p):
 p=Path(p);b=p.read_bytes();x=dict(path=str(p),bytes=len(b),sha256=sha(b),mode=stat.S_IMODE(p.stat().st_mode));reads.append(x);return x
def stored(x):
 p=Path(x['path']);b=p.read_bytes();check(len(b)==x['bytes'] and sha(b)==x['sha256'],'complete archived body');return b
def text(p):
 pin(p);return Path(p).read_text()
def source(p):
 s=text(p);return s,ast.parse(s)
baseline=A/'checkpoint_039_preparation/KNOWN_HELD_BASELINE.json';bp=pin(baseline);check(bp['bytes']==13248332 and bp['sha256']=='8818e87480cb49f81f729c0129afd4142e2812060900618f350145cf06ec310c','exact baseline body');rows=load(baseline)['files'];paths={x['path'] for x in rows};planpath=A/'checkpoint_041_preparation/CONTENT_PLAN.json';plan=load(planpath);pin(planpath);owned=set(plan['allowed_paths']);check(len(rows)==len(paths)==41253 and sum(x['bytes'] for x in rows)==1273600002,'complete unique domain/sum');check(str(S) not in paths,'literal live control absent');overlap=[x for x in rows if str(Path(x['path']).relative_to(R)) in owned];check(not overlap and len(owned)==97,'no owned97 overlap');suffix=[x for x in rows if x['path'].endswith('/SHARED_GIT_WINDOW_STATUS.json')];check(len(suffix)==19 and sum(x['bytes'] for x in suffix)==10288,'19 fixture suffix matches');retained=[x for x in rows if not x['path'].endswith('/SHARED_GIT_WINDOW_STATUS.json')];check(len(retained)==41234 and sum(x['bytes'] for x in retained)==1273589714,'precise suffix retained domain');literal=[x for x in rows if x['path']!=str(S) and str(Path(x['path']).relative_to(R)) not in owned];check(literal==rows,'literal selected domain equals entire baseline');independent=load(O/'INDEPENDENT_BASELINE_DOMAIN.json');check(independent['count']==len(rows) and independent['suffix_match_count']==len(suffix) and independent['suffix_control_name_matches']==suffix,'earlier independently derived domain reproduced')
D06=A/'branch_correction_adversary_06';s06,t06=source(D06/'check_complete_bindings.py');check("if x['path'].endswith('/SHARED_GIT_WINDOW_STATUS.json'):continue" in s06,'actual06 suffix exclusion');r06=load(D06/'branch_correction_preparation_v03_BINDINGS_RESULT.json');pin(D06/'branch_correction_preparation_v03_BINDINGS_RESULT.json');check(r06['known_held_noncontrol_verified_count']==len(retained) and r06['known_held_verified_bytes']==sum(x['bytes'] for x in retained) and r06['checked_predicates']==41496,'actual06 result quantities')
C06=D06/'captures/v03-complete-binding-custody';e06=load(C06/'execution.json');pin(C06/'execution.json');q06=load(C06/'request.json');start06=load(C06/'started.json');check(all(e06[k]==v for k,v in q06.items()) and e06['actual_PID']==start06['actual_PID'] and datetime.fromisoformat(e06['UTC'])<=datetime.fromisoformat(start06['start_UTC'])<=datetime.fromisoformat(e06['end_UTC']) and e06['actual_PID']==r06['actual_PID']==29661 and e06['exit_code']==0 and e06['parent_reaped'] and e06['failure'] is None,'actual06 native envelope');z06=e06['streams']['stdout'];out06=gzip.decompress(stored(z06['stored']));check(len(out06)==z06['logical_bytes'] and sha(out06)==z06['logical_sha256'],'full06 stdout');outjson=json.loads(out06);check(outjson['known_held_noncontrol_verified_count']==41234 and outjson['known_held_verified_bytes']==1273589714,'actual06 native output counts');z=e06['streams']['stderr'];err=gzip.decompress(stored(z['stored']));check(not err and len(err)==z['logical_bytes'] and sha(err)==z['logical_sha256'],'full06 stderr')
for x in e06['source_inputs']:
 b=gzip.decompress(stored(x['stored']));check(len(b)==x['input']['bytes'] and sha(b)==x['input']['sha256'],'complete06 prelaunch source');
 if x['input']['path']==str(D06/'check_complete_bindings.py'):check(b.decode()==s06,'executed06 predicate body exact')
D08=A/'checkpoint041_adversary_01';s08,t08=source(D08/'audit_content.py');check("if x['path']==str(S) or str(Path(x['path']).relative_to(R)) in owned:excluded+=1;continue" in s08,'actual08 literal exclusion');r08=load(D08/'CONTENT_CUSTODY_RESULTS.json');pin(D08/'CONTENT_CUSTODY_RESULTS.json');check(r08['held_nonowned_noncontrol_count']==41253 and r08['held_nonowned_noncontrol_bytes']==1273600002 and r08['held_excluded_owned_or_control_count']==0,'actual08 quantities');C08=D08/'captures/content-custody';e08=load(C08/'execution.json');pin(C08/'execution.json');check(e08['actual_PID']==r08['actual_review_driver_PID']==69774 and e08['exit_code']==0 and e08['parent_reaped'] and e08['full_stream_capture_complete'] and not e08['capture_exception'],'actual08 successful envelope')
for name in ('stdout','stderr'):
 x=e08[name];b=gzip.decompress(stored(x['archive']));check(len(b)==x['logical_bytes'] and sha(b)==x['logical_sha256'],'full08 stream')
 if name=='stdout':check(json.loads(b)==r08,'complete actual08 output equals saved custody JSON')
 else:check(not b,'actual08 empty stderr')
for x in e08['prelaunch_sources']:
 b=gzip.decompress(stored(x['archive']));check(len(b)==x['input']['bytes'] and sha(b)==x['input']['sha256'],'full08 prelaunch source')
 if x['input']['path']==str(D08/'audit_content.py'):check(b.decode()==s08,'actual08 predicate source unchanged')
report06=text(D06/'REPORT.md');report08=text(D08/'REPORT.md');scope08=load(D08/'READ_SCOPE.json');pin(D08/'READ_SCOPE.json');check('41252' in report06 and '1,273,589,714' in report06,'06 prose discrepancy preserved');check('41,252' in report08 and scope08['full_held_nonowned_noncontrol_checked_paths']==41252 and scope08['full_held_nonowned_noncontrol_checked_bytes']==1273589714,'08 hardcoded prose/read-scope discrepancy preserved')
WP=A/'checkpoint_041_preparation';actualpath=A/'ROOT_ACTUAL_COMPLETED_CHECKPOINT041_ACCEPTANCE.json';actualpin=pin(actualpath);check(actualpin['bytes']==584228 and actualpin['sha256']=='7e4c4cbf0544f533ad3781e832a5d5ff050a33e3b420f6fe60f9fecbe5f09c70' and actualpin['mode']==0o444,'exact actual041 ROOT acceptance');actual=load(actualpath);check(actual['status']=='ROOT_ACCEPTS_ACTUAL_PR301_COMPLETED_CHECKPOINT041' and actual['actual_ROOT_recorder_PID']==84900 and actual['actual_checkpoint_PID']==82834 and actual['actual_checkpoint_exit_code']==0 and actual['commit']=='6144d964777214c6963a915288c18fcf97b42026' and actual['known_nonowned_held_count']==41253 and len(actual['all_actual_native_captures_authenticated'])==844 and actual['all_known_nonowned_held_complete_bodies_modes_preserved'],'actual041 accepted count and native scope');vp=pin(WP/'root_verify_actual_checkpoint041_v02.py');check(vp==actual['ROOT_source'] and vp['sha256']=='41d07aef658ee2e6bd25b585b77387b6f94feb7ba130104083313de9b61b5755','actual executed041 validator source')
predicates=[]
for p in (WP/'root_checkpoint041.py',WP/'root_grant_checkpoint041_v02.py',WP/'root_verify_actual_checkpoint041_v02.py',A/'branch_correction_preparation_v03/root_gate_and_readback_v03.py',A/'branch_correction_metadata_completion_v01/root_gate_and_readback.py'):
 s,t=source(p);check(".endswith('/SHARED_GIT_WINDOW_STATUS.json')" not in s,'listed genuine ROOT predicates not suffix exclusion');matches=[dict(line=i,text=l) for i,l in enumerate(s.splitlines(),1) if "x['path']!=str(S)" in l or "x['path']==str(S)" in l];check(matches,'literal control predicate present');predicates.append(dict(source=pin(p),literal_control_predicate_lines=matches))
check(pin(WP/'root_checkpoint041.py')==actual['source'],'executed checkpoint source pin');outerpin=actual['actual_outer_execution'];outer=load(outerpin['path']);check(pin(outerpin['path'])==outerpin and outer['actual_operator_PID']==82834 and outer['exit_code']==0 and outer['status']=='ACTUAL_CHECKPOINT041_OUTER_COMPLETED' and not outer['failed_or_uncertain_execution_not_reclassified'],'actual041 outer completed result')
priorpath=A/'ROOT_ACTUAL_PR301_CORRECTION_ACCEPTANCE.json';priorpin=pin(priorpath);prior=load(priorpath);check(prior['status']=='ROOT_ACCEPTS_ACTUAL_PR301_CREDITED_CORRECTION_PUBLICATION' and prior['ROOT_source']==pin(A/'branch_correction_metadata_completion_v01/root_gate_and_readback.py') and prior['all41253_known_held_noncontrol_paths_preserved'],'actual metadata acceptance literal count');log=text(A/'ROOT_CONTINUATION_LOG.md');check('one owned control checked separately' in log,'interpretive log error remains visible for additive repair')
result=dict(status='PASS_EXACT_ADDITIVE_COUNT_AND_PROVENANCE_ERRATUM',UTC=datetime.now(timezone.utc).isoformat(),actual_erratum_driver_PID=os.getpid(),explicit_predicates=checks,baseline=bp,baseline_count=41253,baseline_bytes=1273600002,literal_live_control_in_baseline=False,owned97_overlap_count=0,suffix_omitted_count=19,suffix_omitted_bytes=10288,exact19_suffix_fixture_entries=suffix,actual06_checked_count=41234,actual06_checked_bytes=1273589714,actual06_native_PID=29661,actual08_checked_count=41253,actual08_checked_bytes=1273600002,actual08_excluded_count=0,actual08_native_PID=69774,actual041_ROOT_acceptance=actualpin,actual041_ROOT_native_PID=84900,actual041_checkpoint_native_PID=82834,actual041_checkpoint_exit_code=0,actual041_native_captures=844,actual041_held_count=41253,actual041_commit=actual['commit'],actual_metadata_acceptance=priorpin,full_literal_predicate_coverage_includes_all19=True,ROOT_predicate_source_pins=predicates,full_read_pins=reads,closed_errors_preserved=True,held_body_reads_repeated=False,actual_publication_or_Git_mutations_repeated=False,no_new_scientific_or_priority_review=True,execution_authority_granted=False,unresolved_issues=[])
with (O/'RESULTS.json').open('x') as f:json.dump(result,f,indent=2);f.write('\n')
print(json.dumps({k:v for k,v in result.items() if k not in ('full_read_pins','ROOT_predicate_source_pins','exact19_suffix_fixture_entries')},indent=2))
