from pathlib import Path
import sqlite3,json,hashlib,datetime,os
A=Path(__file__).resolve().parent;D=A/'original_source_authentication_20261005';R=Path('/Users/alec/Documents/Math/unsolved_math_prioritization');pins=[]
def require(c,m):
 if not c:raise RuntimeError(m)
def read(rel):
 p=R/rel;b=p.read_bytes();pins.append({'path':str(p),'bytes':len(b),'sha256':hashlib.sha256(b).hexdigest(),'mode':p.stat().st_mode&0o777});return json.loads(b)
problems=read('cache/problems.json');prior=read('cache/research_results.json');catalog=read('catalog.json');p=R/'cache/catalog.sqlite';b=p.read_bytes();pins.append({'path':str(p),'bytes':len(b),'sha256':hashlib.sha256(b).hexdigest(),'mode':p.stat().st_mode&0o777});del b
dataset=read('manifest.json');require(all(dataset['files'][Path(r['path']).name]['bytes']==r['bytes'] and dataset['files'][Path(r['path']).name]['sha256']==r['sha256'] for r in pins if Path(r['path']).name in ['problems.json','research_results.json']),'cache/manifest mismatch')
c=sqlite3.connect('file:'+str(p)+'?mode=ro&immutable=1',uri=True);revision=c.execute('SELECT revision FROM metadata').fetchone()[0];require(revision==dataset['revision'],'dataset revision mismatch');row=c.execute('SELECT payload,report FROM records WHERE key=?',('10300055',)).fetchone();require(row is not None,'SQL row absent');sql=json.loads(row[0]);report=None if row[1] is None else json.loads(row[1]);raw=[r for r in problems if r['id']==10300055];cat=[r for r in catalog if str(r['id'])=='10300055'];require(len(raw)==len(cat)==1,'raw/catalog identity');raw=raw[0];cat=cat[0];code='AMR-102-0055';require(raw['problem_number']==sql['problem_number']==cat['problem_number']==code,'source code')
submitted=json.loads((D/'original_attempt/upstream_record.json').read_text())['record'];submitted_prior=json.loads((D/'original_attempt/upstream_record.json').read_text())['prior_report'];require(submitted==sql,'submitted/SQL source mismatch');require(prior[code]==report==submitted_prior,'prior pair mismatch')
require(raw==sql,'raw/SQL payload mismatch');require(sql['research_classification']==report['classification'],'flat classification')
require(cat['review_hash']==hashlib.sha256(json.dumps([sql,report],sort_keys=True).encode()).hexdigest(),'catalog review hash')
x={'schema':'pr97-sourcepair-authentication/v1','UTC':datetime.datetime.now(datetime.timezone.utc).isoformat(),'actual_source_reader_PID':os.getpid(),'dataset_revision':revision,'problem_id':10300055,'problem_code':code,'submitted_source_equals_SQL_payload':True,'raw_problem_fields_match':True,'flat_added_fields':sorted(set(sql)-set(raw)),'proposed_by_field_present':'proposed_by' in raw,'proposed_by_value_is_null':raw.get('proposed_by') is None,'raw_prior_key_present':code in prior,'raw_prior_typed_value':prior.get(code),'SQL_report_is_NULL':row[1] is None,'SQL_report_typed_value':report,'submitted_prior_matches_raw_and_SQL':True,'review_hash':cat['review_hash'],'statement_hash':cat['statement_hash'],'catalog_selected':cat,'full_data_pins':pins,'original_budget':'2/5','new_central_proof_search_turns':0,'mathematical_clearance':False,'priority_clearance':False};(D/'SOURCEPAIR_AUTHENTICATION.json').write_text(json.dumps(x,indent=2,sort_keys=True)+'\n');print(json.dumps({k:v for k,v in x.items() if k not in ['catalog_selected','full_data_pins','raw_prior_typed_value','SQL_report_typed_value']}))
