from pathlib import Path
import datetime,hashlib,json,os
A=Path(__file__).resolve().parent
now=datetime.datetime.now(datetime.timezone.utc).isoformat()
require=lambda c,m: None if c else (_ for _ in ()).throw(RuntimeError(m))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
families=[]
for name in ['priority_question_history_20261006','priority_linear_contact_mechanism_20261006','priority_covering_interpretation_adversary_20261006']:
    p=A/'root_priority_evidence_authentication_20261006'/(name+'.json')
    d=json.loads(p.read_text());require(d['all_closed_bodies_verified'],'Family not authenticated')
    for r in d['pins']:require(sha(Path(r['path']))==r['sha256'],'Closed input changed')
    families.append({'family':name,'authentication_sha256':sha(p),'manifest_sha256':d['manifest_sha256'],'own_files':d['own_files'],'borrowed_files':d['borrowed_files'],'ROOT_full_report_and_independent_analysis_read':True,'report_sha256':sha(A/name/'REPORT.md')})
V=A/'credited_verification_candidate_v2'; repro=A/'root_credited_candidate_reproduction_20261006/RESULT.json'
d=json.loads(repro.read_text());require(d['passed'] and d['current_candidate_sha256']==sha(V/'CANDIDATE.md'),'Credited candidate not reproduced')
proofpin=sha(V/'CANDIDATE.md')
r={'schema':'pr97-root-bounded-priority-adjudication/v1','UTC':now,'operator_PID':os.getpid(),'PR':97,'problem_id':10300055,'submitted_head':'fb50facb2a7389bb272bbf0b5cbd80c24c79b992','literal_submitted_status':'claimed_solved','original_effort':'2/5','new_central_proof_search_turns':0,'closed_families':families,'mathematical_clearance_retained':True,'mathematical_proof_changed':False,'candidate':str(V/'CANDIDATE.md'),'candidate_sha256':proofpin,'normal_optimized_reproduction_passed':True,'author_diagnostics':87,'independent_diagnostics':89,'reproduction_receipt_sha256':sha(repro),'prior_affine_mechanism_authenticated':True,'prior_affine_mechanism':'Dathe–Khoule2012 Definition2.1 and Theorem2.2, printed102–103, n=1 with beta=omega and identically-zero mixed term','ordinary_smooth_tightness':'Our standard derived corollary of that known criterion, ET neighborhood tightness and finite smooth Gray; not a literally printed2012 answer','extra_C1_C2_disk_assertion':'Mathematically checked; historical novelty unestablished','exact_prior_printed_Calegari13_2_answer_authenticated':False,'absence_of_discovery_is_firstness_proof':False,'historical_firstness_established':False,'current_open_status_established':False,'exhaustive_novelty_established':False,'bounded_priority_audit_completed':True,'strict_priority_clearance':False,'full_original_already_solved_disposition_established':False,'mathematical_failure_or_reason_to_close_PR':False,'access_gaps':['Final AMS2003 Calegari chapter DOI10.1090/pspum/071/2024640','Full Eliashberg–Thurston Confoliations1998','Dathe–Rukimbira2011 published body DOI10.1515/advgeom.2010.043','Khoule–Ndiaye–Wade2025 full body DOI10.1007/s00022-025-00742-z','Identified Mitsumatsu Warsaw/Japanese full texts'],'PR95_priority_waiver_applies':False,'PR97_qualified_publication_human_authorization':False,'publication_clearance':False,'publication_service_mutations':[],'native_PR_or_QUEUE_mutated':False,'whole_package_reviews_completed':0,'next_step':'Prepare a concrete unpublished credited note for full package review; retain no-new-historical-resolution framing and publication hold. No exception or final disposition is inferred.','workflow_estimate_percent':30,'priority_audit_estimate_percent':85,'program_completed':13,'dated_eligible_total':99,'program_completion_percent':100*13/99}
(A/'ROOT_PRIORITY_ADJUDICATION_20261006.json').write_text(json.dumps(r,indent=2,sort_keys=True)+'\n')
p=A.parent.parent/'CURRENT_PROGRESS.json'; current=json.loads(p.read_text());current.update(UTC=now,current_PR_workflow_percent=30,current_priority_audit_percent=85,current_bounded_priority_audit_complete=True,current_priority_audit_complete=False,current_priority_clearance=False,current_priority_adjudication='audits/pr97_10300055/ROOT_PRIORITY_ADJUDICATION_20261006.json',current_fresh_priority_agents=[x['family'] for x in families],current_repaired_candidate='audits/pr97_10300055/credited_verification_candidate_v2',current_repaired_candidate_sha256=proofpin,current_package_preparation_percent=5,current_package='audits/pr97_10300055/contingent_credited_note_v1',current_package_preparation_agent='pr97_contingent_credited_note_preparation_20261006',current_publication_authorization=False,current_user_authorized_qualified_publication=False,remaining_current_step='Three bounded priority reviews closed and authenticated: general affine mechanism is prior art, ordinary tightness is a classical corollary, firstness remains unestablished. Prepare a concrete unpublished credited note for whole-package review; no PR97 priority waiver or publication authority.')
p.write_text(json.dumps(current,indent=2,sort_keys=True)+'\n')
with (A/'RESEARCH_LOG.md').open('a') as log:
    log.write('\n## '+now+' — deep bounded priority adjudication and necessary attribution repair\n\nROOT fully read and authenticated three closed priority reports:95+97+21 own payload files and14+6+20 borrowed input pins. General Dathe–Khoule2012 criterion covers the exact nonclosed zero-mixed-term pencil; a new independent adversary confirms ordinary smooth tightness as our classical ET/finite-Gray corollary. No exact prior printed answer was located, and no firstness/current-openness claim follows. Final2003chapter and other identified full-text gaps remain unread. Candidatev2 credits the antecedent without changing the proof or verifier sources; four actual normal/optimized runs again reproduce87/89 diagnostics and the new proof hash. Original and v1 artifacts preserved. An unpublished concise credited note is being prepared to make any later disposition concrete and reviewable; publication remains unauthorized forPR97, with no inheritedPR95 waiver. Math100%, bounded priority attemptcomplete but strict priority85%/uncleared, workflow30%, program13/99 (13.13%). Zero extra proof-search turns; no PR/QUEUE/Zenodo/tracker changes.\n')
print(json.dumps({'UTC':now,'candidate_sha256':proofpin,'strict_priority_clearance':False,'publication_clearance':False,'workflow_estimate_percent':30,'record':'ROOT_PRIORITY_ADJUDICATION_20261006.json'}))
