"""Independent exact controls for the frozen KP-1.17 partial packet.
No imported author checker code. Deep topology is audited in the review.
"""
import json
from collections import Counter
from fractions import Fraction
from functools import lru_cache
from itertools import combinations, combinations_with_replacement, product, permutations
from math import gcd
import sympy as sp
from sympy.matrices.normalforms import smith_normal_form
C=Counter()
def ck(ok,label):
    assert ok,label
    C[label]+=1
# Independent deletion-contraction, with loops discarded after contraction.
@lru_cache(None)
def trees(n,edges):
    edges=tuple(e for e in edges if e[0]!=e[1])
    if n==1:return 1
    if len(edges)<n-1:return 0
    u,v=edges[0]
    labels=[j for j in range(n) if j!=v]
    ren={j:i for i,j in enumerate(labels)}
    def image(j):return ren[u if j==v else j]
    contracted=tuple(sorted(tuple(sorted((image(a),image(b)))) for a,b in edges[1:]))
    return trees(n,edges[1:])+trees(n-1,contracted)
def determinant(A):
    # Rational Gaussian elimination, distinct from author's Bareiss/Sympy paths.
    A=[[Fraction(x) for x in row] for row in A]; ans=Fraction(1)
    for j in range(len(A)):
        k=next((k for k in range(j,len(A)) if A[k][j]),None)
        if k is None:return 0
        if k!=j:A[k],A[j]=A[j],A[k];ans=-ans
        q=A[j][j];ans*=q
        for k in range(j+1,len(A)):
            f=A[k][j]/q
            for h in range(j,len(A)):A[k][h]-=f*A[j][h]
    return int(ans)
def canonical(n,edges):
    return n,min(tuple(Counter(tuple(sorted((p[u],p[v]))) for u,v in edges)[e]
                 for e in combinations(range(n),2)) for p in permutations(range(n)))
small={};five={};graph_count=0
for n in range(2,7):
    pairs=list(combinations(range(n),2))
    for m in range(n,7):
        for ids in combinations_with_replacement(range(len(pairs)),m):
            edges=tuple(pairs[i] for i in ids); t=trees(n,edges)
            if not t:continue
            lap=[[0]*n for _ in range(n)]
            for u,v in edges:
                lap[u][u]+=1;lap[v][v]+=1;lap[u][v]-=1;lap[v][u]-=1
            ck(t==determinant([row[:-1] for row in lap[:-1]]),'deletion_contraction_vs_rational_laplacian')
            if any(trees(n,edges[:j]+edges[j+1:])==0 for j in range(m)):continue
            graph_count+=1;ck(t>=m,'bridgeless_edge_bound_controls')
            val=(n,m,t,tuple(sorted(sum(v in e for e in edges) for v in range(n))))
            if t<=4:small[canonical(n,edges)]=val
            if t==5:five[canonical(n,edges)]=val
ck(set(small.values())=={(2,2,2,(2,2)),(2,3,3,(3,3)),(2,4,4,(4,4)),(3,3,3,(2,2,2)),(3,4,4,(2,2,4)),(4,4,4,(2,2,2,2))},'all_six_small_graph_classes')
ck(set(five.values())=={(2,5,5,(5,5)),(3,4,5,(2,3,3)),(5,5,5,(2,2,2,2,2))},'all_three_determinant_five_graph_classes')
# Linear-fractional gluing algebra derived from the displayed column convention.
r,s=sp.symbols('r s',integer=True);p=r*r+r-1
A=sp.Matrix([[r+1,-p],[1,-r]])
ck(sp.expand(A.det())==-1,'family_orientation')
ck((A*A-A-sp.eye(2)).applyfunc(sp.expand)==sp.zeros(2),'family_exchange_matrix_obstruction')
ck((A*(-sp.eye(2))-(-sp.eye(2))*A).applyfunc(sp.expand)==sp.zeros(2),'linear_boundary_equivariance')
f=A*sp.Matrix([6,1]);d=sp.expand(f[0]-6*f[1])
ck(sp.expand(d-(-r*r+11*r-29))==0,'fiber_intersection_polynomial')
ck(sp.expand(4*d+(2*r-11)**2)==5,'fiber_mismatch_square_obstruction')
ck(all(z*z%8!=5 for z in range(8)),'fiber_mismatch_never_zero_integer')
ck(sp.cancel(((r+1)*s-p)/(s-r)-(r+1+1/(s-r)))==0,'slope_map_exact_identity')
ck(sp.factor((r+1-1/(r-1))-1)==(r*r-r-1)/(r-1),'slope_endpoint_difference')
# An integer presentation with a unit pivot gives exact H1 cyclic, not just determinant.
for n in range(2,202):
    q=n*n+n-1;M=sp.Matrix([[1,-n-1],[0,q]])
    D=smith_normal_form(M,domain=sp.ZZ)
    ck([abs(int(D[j,j])) for j in range(2)]==[1,q],'independent_smith_cyclic_family')
    ck(q%2==1 and gcd(n+1,q)==1,'both_inclusions_generate_odd_homology')
    ck(1<n+1<q-1,'exchange_cannot_induce_deck_action')
    ck((n*n-n-1)>0,'endpoint_inside_trefoil_lspace_arc')
    for u,v in product(range(-14,15),range(1,10)):
        if u>v:continue
        z=Fraction(u,v);im=n+1+1/(z-n)
        ck(n+1-Fraction(1,n-1)<=im<=n+1,'rational_entire_complement_controls')
# Boundary kernel generated by central fiber and preferred longitude.
e,k=sp.symbols('e k');B=sp.Matrix([[e,0],[k,e]])
ck(B*sp.Matrix([6,1])-e*sp.Matrix([6,1])==sp.Matrix([0,6*k]),'central_fiber_forces_zero_shear')
# K4 kernel is realized by translations of half-integral torus points.
F=list(product((0,1),repeat=2)); perms=[]
for t in F:
    q=tuple(F.index(((x+t[0])%2,(y+t[1])%2)) for x,y in F);perms.append(q)
    ck(tuple(q[q[j]] for j in range(4))==tuple(range(4)),'kernel_involution')
    ck(sum(q[j]==j for j in range(4))==(4 if t==(0,0) else 0),'three_mutation_double_transpositions')
ck(len(set(perms))==4,'four_kernel_classes')
# Independent permutation D8 negative control: nonconjugate reflection classes do not commute.
rot=(1,2,3,0);ref=(0,3,2,1);ident=(0,1,2,3)
def mul(g,h):return tuple(g[h[j]] for j in range(len(g)))
def inv(g):return tuple(g.index(j) for j in range(len(g)))
G={ident};stack=[ident]
while stack:
    g=stack.pop()
    for h in (rot,ref):
        z=mul(g,h)
        if z not in G:G.add(z);stack.append(z)
ck(len(G)==8,'actual_dihedral_permutation_group')
classes=[{mul(mul(g,t),inv(g)) for g in G} for t in (ref,mul(rot,ref))]
ck(not classes[0]&classes[1],'nonconjugate_reflection_classes')
ck(all(mul(g,h)!=mul(h,g) for g,h in product(*classes)),'no_commuting_representatives_of_two_classes')
iv=[g for g in G if g!=ident and mul(g,g)==ident]
ck(all(any(t!=g and mul(g,t)==mul(t,g) for t in iv) for g in iv),'each_class_still_has_commuting_partner')
# Fox coloring matrices for closed braids, independently generated from local crossings.
def matmul(B,A):return [[sum(B[i][k]*A[k][j] for k in range(len(A))) for j in range(len(A))] for i in range(len(A))]
def eye(n):return [[int(i==j) for j in range(n)] for i in range(n)]
def braid(n,w):
    A=eye(n);perm=list(range(n))
    for z in w:
        i=abs(z)-1;B=eye(n)
        if z>0:B[i][i],B[i][i+1],B[i+1][i],B[i+1][i+1]=2,-1,1,0
        else:B[i][i],B[i][i+1],B[i+1][i],B[i+1][i+1]=0,1,-1,2
        A=matmul(B,A);perm[i],perm[i+1]=perm[i+1],perm[i]
    R=[[A[i][j]-int(i==j) for j in range(n)] for i in range(n)]+[[1]+[0]*(n-1)]
    seen=set();cycles=0
    for i in range(n):
        if i in seen:continue
        cycles+=1;j=i
        while j not in seen:seen.add(j);j=perm[j]
    return R,cycles
def rank2(rows,n):
    rows=[sum((v%2)<<i for i,v in enumerate(row)) for row in rows];rank=0
    for j in range(n):
        k=next((k for k in range(rank,len(rows)) if rows[k]>>j&1),None)
        if k is None:continue
        rows[k],rows[rank]=rows[rank],rows[k]
        for h in range(len(rows)):
            if h!=rank and rows[h]>>j&1:rows[h]^=rows[rank]
        rank+=1
    return rank
for length in range(7):
    for w in product((1,-1,2,-2),repeat=length):
        R,c=braid(3,w);ck(3-rank2(R,3)==c-1,'fox_mod_two_component_formula')
for m in range(1,20):
    R,c=braid(2,[1]*m);D=smith_normal_form(sp.Matrix(R),domain=sp.ZZ)
    ck(sorted(abs(int(D[j,j])) for j in range(2))==[1,m],'two_strand_torus_homology')
R,c=braid(3,[1,2]*5);D=smith_normal_form(sp.Matrix(R),domain=sp.ZZ)
ck(c==1 and all(abs(int(D[j,j]))==1 for j in range(3)),'actual_torus35_perfect_cover_abelianization')
# ADE determinants through leaf Schur complements, a closed arm formula.
def arm_star_det(arms):
    return Fraction(2)-sum(Fraction(k,k+1) for k in arms)
for n in range(4,105):
    arms=[1,1,n-3];den=1
    for k in arms:den*=k+1
    ck(den*arm_star_det(arms)==4,'D_all_parities_order_four')
for arms,target in [([1,2,2],3),([1,2,3],2),([1,2,4],1)]:
    den=1
    for k in arms:den*=k+1
    ck(den*arm_star_det(arms)==target,'E_orders')
print(json.dumps({'status':'PASS','exact_assertions':sum(C.values()),'families':dict(sorted(C.items())), 'enumerated_bridgeless_graphs':graph_count,'small_graph_classes':sorted(set(small.values())),'determinant_five_classes':sorted(set(five.values())), 'limitations':'Exact finite controls and symbolic identities only. The independent written audit checks the infinite topology and source hypotheses; original remains unsolved 5/5.'},indent=2,sort_keys=True))
