#!/usr/bin/env python3
"""New independent controls for complete flags, pivots, weights and tilts."""
from fractions import Fraction as F
from itertools import product, combinations
from collections import Counter,defaultdict
from math import log,exp,ceil
import datetime,json,random

def canonical(rows):
    a=[list(map(F,r)) for r in rows if any(r)]
    if not a:return ()
    r=0
    for c in range(len(a[0])):
        p=next((i for i in range(r,len(a)) if a[i][c]),None)
        if p is None:continue
        a[r],a[p]=a[p],a[r];v=a[r][c];a[r]=[x/v for x in a[r]]
        for i in range(len(a)):
            if i!=r and a[i][c]:
                v=a[i][c];a[i]=[x-v*y for x,y in zip(a[i],a[r])]
        r+=1
        if r==len(a):break
    return tuple(tuple(x for x in row) for row in a if any(row))
def inside(row,V):return len(canonical((*V,row)))==len(V)
def quotient(w):return tuple(w[i]-w[0] for i in range(1,len(w)))
def hist(B):
    h=Counter({0:1})
    for x in B:
        old=h.copy()
        for s,n in old.items():h[s+x]+=n
    return h
def p_of(B,window):
    return prod(F(1,n) if n in B else F(n-1,n) for n in window)
def prod(xs):
    a=F(1)
    for x in xs:a*=x
    return a
def space_checks():
    records=[];nc=0
    for k in range(2,5):
        cube=tuple(product((0,1),repeat=k));one=(1,)*k
        pending=[canonical((one,))];seen=set(pending)
        while pending:
            V=pending.pop();S=tuple(x for x in cube if inside(x,V))
            images={quotient(x) for x in S}
            assert len(images)<=2**len(V)-1
            nc+=1
            for w in cube:
                W=canonical((*V,w))
                if W not in seen:seen.add(W);pending.append(W)
        records.append({'k':k,'all_cube_generated_spaces_containing_diagonal':len(seen)})
    return records,nc
def pivot_checks():
    all_n=0;targets=0;odds=0
    B=tuple(range(2,10))
    fibers=defaultdict(list)
    for bits in product((0,1),repeat=len(B)):
        fibers[sum(x*b for x,b in zip(B,bits))].append(bits)
    for k in (2,3,4):
        for fiber in fibers.values():
            for reps in combinations(fiber,k):
                one=(1,)*k;V=canonical((one,));piv=[];flag=[];free=[]
                for idx in range(len(B)-1,-1,-1):
                    w=tuple(t[idx] for t in reps)
                    if inside(w,V):free.append((B[idx],w))
                    else:
                        piv.append((B[idx],w));V=canonical((*V,w));flag.append(V)
                t=len(piv)
                assert k<=2**t
                assert len(canonical(tuple(quotient(w) for x,w in piv)))==t
                # This identity tests every target class generated by this witness,
                # plus three arbitrary affine shifts. Injectivity is independent of target.
                residual=tuple(sum(x*quotient(w)[i] for x,w in free) for i in range(k-1))
                pivotval=tuple(sum(x*quotient(w)[i] for x,w in piv) for i in range(k-1))
                assert tuple(a+b for a,b in zip(residual,pivotval))==(0,)*(k-1)
                for shift in ((0,)*(k-1),tuple(range(1,k)),(7,)*(k-1),(-3,)*(k-1)):
                    assert tuple(a+b+s for a,b,s in zip(residual,pivotval,shift))==shift
                    targets+=1
                all_n+=1
    window=tuple(range(2,13))
    for bits in product((0,1),repeat=len(window)):
        S={n for n,b in zip(window,bits) if b}
        for deleted in combinations(sorted(S),min(3,len(S))):
            R=S-set(deleted)
            assert p_of(S,window)/p_of(R,window)==prod(F(1,n-1) for n in deleted)
            odds+=1
    return all_n,targets,odds
def moment_checks():
    out=[]
    for n in range(1,15):
        EM2=F(0);tiltN=F(0);Z=F(0);lambda_=F(4)
        for tail in product((0,1),repeat=n-1):
            B=(1,)+tuple(i+2 for i,b in enumerate(tail) if b)
            p=p_of(set(B),range(1,n+1));m=max(hist(B).values());EM2+=p*m*m
            w=p*lambda_**len(B);Z+=w;tiltN+=w*len(B)
        exact=F((n+1)*(n+2)*(n+3),6)
        lower=exact/F((4*n+1)**2)
        assert Z==exact and EM2>=lower
        out.append({'n':n,'exact_EM2':str(EM2),'Jensen_lower':str(lower),'tilted_mean_N':str(tiltN/Z)})
    return out
def streams():
    records=[];rejected=[]
    for seed in range(100,180):
        rng=random.Random(seed);B=[]
        for n in range(1,4097):
            if rng.random()<1/n:B.append(n)
        if len(B)>20:
            rejected.append({'seed':seed,'selected':len(B),'reason':'explicit exact-DP capacity; no uncensored frequency claim'})
            continue
        a=tuple(x for x in B if x<=64);b=tuple(x for x in B if x>64)
        m=max(hist(B).values())
        assert max(hist(a).values())*max(hist(b).values())<=m<=2**len(a)*max(hist(b).values())
        records.append({'seed':seed,'N4096':len(B),'M4096':m})
    return {'streams':records,'censored':rejected,'meaning':'whole-path deterministic convolution controls only; no universality evidence'}
def main():
    spaces,nc=space_checks();pivs,affine,odds=pivot_checks()
    return {'created_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'space_controls':spaces,'quotient_coset_checks':nc,'all_distinct_equal_sum_witnesses_2_to_9':pivs,'affine_target_identities':affine,'exact_deletion_odds_checks':odds,'moments':moment_checks(),'streams':streams(),'asymptotic_status':'controls complement proof; no finite count establishes universal asymptotics'}
if __name__=='__main__':print(json.dumps(main(),indent=2))
